### ISSUE TITLE
Agent should report dispatch failures... somewhere

### ISSUE THREAD

**Issue by rayh** [aws/amazon-ecs-agent#10]
I've had two cases where containers fail to start:
- machine is out of disk space
- repository is insecure, so docker fails to pull

In both cases, the task fails, but without tailing the logs on the machine, I wasn't aware as to why.  Perhaps the Agent could send errors to CloudWatch?  Or would the recommended approach be to bake my own AMI with cloud watch agent set up for those log files?

**Comment by euank** [comment]
The [recent release](https://github.com/aws/amazon-ecs-agent/releases/tag/v0.0.3) of the agent now propogates some errors to the backend. These errors are shown as a 'reason' field when you describe the task.

The agent does not currently send errors to CloudWatch, but you can use the CloudWatch agent in conjunction with volume mounts or the agent's logfile.

I'm closing this issue in favor fo the two more specific issues, #9 and #24. If you think those don't capture everything here, feel free to add to them or create new ones.

Thanks for the suggestion!
