### ISSUE TITLE
Documentation: LVM thin_pool_autoextend_threshold described incorrectly

### ISSUE THREAD

**Issue by cjtenny** [aws/amazon-ecs-agent#1001]
### Summary
LVM thin_pool_autoextend_threshold described incorrectly

### Description
https://aws.amazon.com/premiumsupport/knowledge-center/docker-thin-pool/ states:
This may be caused by Logical Volume Manager (LVM) auto-extending the volume. By default, LVM extends the thin pool when it reaches 100% utilization; the pool is extended by 20% of the total volume size. This can be verified with thin_pool_autoextend_threshold and thin_pool_autoextend_percent parameters in the LVM configuration file /etc/lvm/lvm.conf.

lvm.conf states:
Configuration option activation/thin_pool_autoextend_threshold.
Auto-extend a thin pool when its usage exceeds this percent.
Setting this to 100 disables automatic extension.

**Comment by aaithal** [comment]
Hi @cjtenny, thanks a lot for bringing this to our attention. We have fixed this in our docs. Please let us know if you have any follow-up questions/comments. Thanks!
