### ISSUE TITLE
AWS ECS CLI container deployment failing with OutOfMemory Issue for a t2.medium instance

### ISSUE THREAD

**Issue by binitdatta** [aws/amazon-ecs-agent#1027]
### Summary
I am trying to follow this AWS ECS CLI tutorial at http://docs.aws.amazon.com/AmazonECS/latest/developerguide/ECS_CLI_tutorial.html. The demo works fine. However, when I am trying to deploy my own container in the same cluster, it is failing with 137 OutofMemory Error.

### Description
Steps.

1. Github Repo
`https://github.com/rollingstonetechnology/udemy-rsmortgage-eureka-service-discovery-ha-docker`

2. Clone the repo
`[git clone https://github.com/rollingstonetechnology/udemy-rsmortgage-eureka-service-discovery-ha-docker.git](url)`

Steps 3 - 16 are working fine in which I am trying to run the docker container manually in AWS EC2
3. `cd udemy-rsmortgage-eureka-service-discovery-ha-docker`

4. `clean package`

5. `sudo docker build -t binitdatta-eurekaservice .`

6. `sudo docker images`

7. `sudo docker run -p 8761:8761 -t binitdatta-eurekaservice`

8. `sudo docker ps` 

9. `aws ecr get-login --no-include-email --region us-west-2
`
10. `sudo docker login -u AWS -p <paste>`

11. `sudo docker rmi binitdatta-eurekaservice -f`

12. `sudo docker build -t eureka-service-repository .`

13. `sudo docker tag eureka-service-repository:latest 107222267664.dkr.ecr.us-west-2.amazonaws.com/eureka-service-repository:latest`

14. `sudo docker push 107222267664.dkr.ecr.us-west-2.amazonaws.com/eureka-service-repository:latest`

15. Create Docker compone t file called docker-compose.yml

[version: '2'
services:
  eureka-service-repository:
    image: 107222267664.dkr.ecr.us-west-2.amazonaws.com/eureka-service-repository
    cpu_shares: 100
    mem_limit: 524288000
    ports:
      - "8761:8761"](url)

16. I defined the following two environment variables within my .bashrc file

`ecs-cli configure --region us-west-2 --access-key $AWS_ACCESS_KEY_ID --secret-key $AWS_SECRET_ACCESS_KEY --cluster ecs-cli-binit-demo`

16. 

`ecs-cli up --keypair eCommerceSampleKeyPair --capability-iam --size 1 --instance-type t2.medium
`
16. 

`ecs-cli compose --file docker-compose.yml up
`
17. See the docker process

`[ec2-user@ip-172-31-27-242 udemy-rsmortgage-eureka-service-discovery-ha-docker]$ ecs-cli ps
Name                                                            State                                                                                 Ports                         TaskDefinition
3b8d3a18-109d-48fc-9421-12029452ebe5/eureka-service-repository  RUNNING                                                                               35.165.151.54:8761->8761/tcp  ecscompose-udemy-rsmortgage-eureka-service-discovery-ha-docker:3
3d776ca5-7963-44be-b7e7-aeb1af0a251c/eureka-service-repository  STOPPED ExitCode: 137                                                                 0.0.0.0:8761->8761/tcp        ecscompose-udemy-rsmortgage-eureka-service-discovery-ha-docker:2
4fb322f1-bfa0-4c05-aae3-5e015422d449/wordpress                  STOPPED ExitCode: 0                                                                   0.0.0.0:80->80/tcp            ecscompose-ec2-user:1
4fb322f1-bfa0-4c05-aae3-5e015422d449/mysql                      STOPPED ExitCode: 0                                                                                                 ecscompose-ec2-user:1
a7505818-7b3d-4a6b-a90b-f47aac10ae60/eureka-service-repository  STOPPED ExitCode: 137 Reason: OutOfMemoryError: Container killed due to memory usage  0.0.0.0:8761->8761/tcp        ecscompose-udemy-rsmortgage-eureka-service-discovery-ha-docker:1
f07919ca-d1a0-4f81-a809-7d71d72c4375/eureka-service-repository  STOPPED ExitCode: 137 Reason: OutOfMemoryError: Container killed due to memory usage  0.0.0.0:8761->8761/tcp        ecscompose-udemy-rsmortgage-eureka-service-discovery-ha-docker:3
[ec2-user@ip-172-31-27-242 udemy-rsmortgage-eureka-service-discovery-ha-docker]$`

Any help would be much appreciated. Thanks in advance.

### Expected Behavior
The task should run and I should be able to access the container at port 8761. 

### Observed Behavior

`[ec2-user@ip-172-31-27-242 udemy-rsmortgage-eureka-service-discovery-ha-docker]$ ecs-cli ps
Name                                                            State                                                                                 Ports                         TaskDefinition
3b8d3a18-109d-48fc-9421-12029452ebe5/eureka-service-repository  RUNNING                                                                               35.165.151.54:8761->8761/tcp  ecscompose-udemy-rsmortgage-eureka-service-discovery-ha-docker:3
3d776ca5-7963-44be-b7e7-aeb1af0a251c/eureka-service-repository  STOPPED ExitCode: 137                                                                 0.0.0.0:8761->8761/tcp        ecscompose-udemy-rsmortgage-eureka-service-discovery-ha-docker:2
4fb322f1-bfa0-4c05-aae3-5e015422d449/wordpress                  STOPPED ExitCode: 0                                                                   0.0.0.0:80->80/tcp            ecscompose-ec2-user:1
4fb322f1-bfa0-4c05-aae3-5e015422d449/mysql                      STOPPED ExitCode: 0                                                                                                 ecscompose-ec2-user:1
a7505818-7b3d-4a6b-a90b-f47aac10ae60/eureka-service-repository  STOPPED ExitCode: 137 Reason: OutOfMemoryError: Container killed due to memory usage  0.0.0.0:8761->8761/tcp        ecscompose-udemy-rsmortgage-eureka-service-discovery-ha-docker:1
f07919ca-d1a0-4f81-a809-7d71d72c4375/eureka-service-repository  STOPPED ExitCode: 137 Reason: OutOfMemoryError: Container killed due to memory usage  0.0.0.0:8761->8761/tcp        ecscompose-udemy-rsmortgage-eureka-service-discovery-ha-docker:3
[ec2-user@ip-172-31-27-242 udemy-rsmortgage-eureka-service-discovery-ha-docker]$`

**Comment by binitdatta** [comment]
I tried the same experiment with a t2.large instance with 8 GB of memory. 

`ecs-cli up --keypair eCommerceSampleKeyPair --capability-iam --size 1 --instance-type t2.large`

Same Error 

`35850b79-4f7e-4ff8-9d75-9069913b1c6c/eureka-service-repository  STOPPED ExitCode: 137 Reason: OutOfMemoryError: Container killed due to memory usage  34.213.238.79:8761->8761/tcp  ecscompose-udemy-rsmortgage-eureka-service-discovery-ha-docker:3`

Thanks,

Binit

**Comment by PettitWesley** [comment]
@binitdatta, thanks for your question. Please note that the ECS CLI has its own GitHub repo: [https://github.com/aws/amazon-ecs-cli](https://github.com/aws/amazon-ecs-cli). 

I am not certain exactly what has caused your out of memory error- I'd suggest increasing the mem_limit or try specifying [memory reservation](https://docs.docker.com/engine/admin/resource_constraints/#limit-a-containers-access-to-memory) without mem_limit.

**Comment by binitdatta** [comment]
Thanks, @PettitWesley . I will try today with memory reservation limits.

Thanks for the ecs-cli repo,

Binit

**Comment by binitdatta** [comment]
Hi  @PettitWesley,

Working!!. This is the docker-compose.yml file

`version: '2'
services:
  eureka-service-repository:
    image: 107222267664.dkr.ecr.us-west-2.amazonaws.com/eureka-service-repository
    cpu_shares: 100
    mem_limit: 1073741824
    ports:
      - "8761:8761"`

Thanks, again.  Closing this.
