### ISSUE TITLE
Container Dependencies should be resolved when stop container

### ISSUE THREAD

**Issue by joker1007** [aws/amazon-ecs-agent#1032]
### Summary

If containers in a task have dependency to other container,
Agent should resolve dependency.
Otherwise, it makes a probrem in some cases.

#### Examples
- a container buffering log data in itself memory.
- a container is agent of log forwarding middlware. (scribe, fluentd, logstash or so)
- buffering container send buffering logs to agent container in every several secs.

in this case, If agent container is stopped before buffering container stop,
buffering log data is lost.

If ecs-agent blocks to stop log agent container until buffering container is stopped,
I can avoid this probrem.

For this reason, I think that ecs-agent should resove dependency graph reversely oriented when task is stopped.

### Expected Behavior
- A container links to other container
- First stop a container that links to other container, then stop linked container

I guess following code is related.

amazon-ecs-agent/agent/engine/dependencygraph/graph.go
```go
func verifyStatusResolvable(target *api.Container, existingContainers map[string]*api.Container, dependencies []string, resolves func(*api.Container, *api.Container) bool) bool {
	targetGoal := target.GetDesiredStatus()
	if targetGoal != target.GetSteadyStateStatus() && targetGoal != api.ContainerCreated {
		// A container can always stop, die, or reach whatever other state it
		// wants regardless of what dependencies it has
		return true
	}

	for _, dependency := range dependencies {
		maybeResolves, exists := existingContainers[dependency]
		if !exists {
			return false
		}
		if !resolves(target, maybeResolves) {
			return false
		}
	}
	return true
}
```

**Comment by samuelkarp** [comment]
@joker1007 Thanks for opening this.  We're already tracking this feature request in https://github.com/aws/amazon-ecs-agent/issues/474, so I'll close this one.
