### ISSUE TITLE
Flaky Agent unit test: TestHandlerStopsWhenContextIsCancelled

### ISSUE THREAD

**Issue by aaithal** [aws/amazon-ecs-agent#1039]
### Summary

The `TestHandlerStopsWhenContextIsCancelled` test is flaky

### Description

* This travis build failed: https://travis-ci.org/aws/amazon-ecs-agent/builds/293890257?utm_source=github_status&utm_medium=notification
* Also:
```
$ go test -count 10000 ./agent/acs/handler/... -run TestHandlerStopsWhenContextIsCancelled
FAIL
FAIL	github.com/aws/amazon-ecs-agent/agent/acs/handler	3.249s
--- FAIL: TestHandlerStopsWhenContextIsCancelled (0.00s)
	controller.go:132: Unexpected call to *mock_wsclient.MockClientServer.Serve([]) at /Users/aithal/workspace/src/github.com/aws/amazon-ecs-agent/agent/acs/handler/acs_handler.go:333 because: 

```

### Expected Behavior
Unit test should pass

### Observed Behavior
Unit test should fails

### Environment Details

NA

**Comment by samuelkarp** [comment]
Closing since https://github.com/aws/amazon-ecs-agent/pull/1038 was merged.
