### ISSUE TITLE
Support for sha256 style tags

### ISSUE THREAD

**Issue by euank** [aws/amazon-ecs-agent#104]
Docker supports immutable tags, but these are not supported by ECS currently. Task definitions + the agent should properly support these tags as they are useful for many usecases (e.g. actually immutable task-definisions / deployments) and could allow better caching.

Example: `busybox@sha256:5b2fff9306bd9380ee85f96adaf67097f5b9e95d37da995099875b9e95913063`

**Comment by mdub** [comment]
I'm surprised that, almost two years later, ECS still doesn't support immutable image references.

**Comment by samuelkarp** [comment]
Immutable image references are now supported in ECS.
