### ISSUE TITLE
Agent mark container known status as stopped for inspection error

### ISSUE THREAD

**Issue by richardpen** [aws/amazon-ecs-agent#1043]
### Summary

ECS Agent marks the container known status as stopped if the inspect api returned an error when the agent is synchronizing the container status with docker on agent start. This could cause a problem if this is an transient error, agent may stop managing the container and leave it running forever.

### Description

Agent marks the container as known stopped [here](https://github.com/aws/amazon-ecs-agent/blob/0dcd02c16ab1f34852e61e0642a36a3cc72fb17f/agent/engine/docker_task_engine.go#L263), we may want to set the desired status as stopped or have different behavior based on the error type.

### Expected Behavior
All the containers should be stopped if the task is stopped.

**Comment by samuelkarp** [comment]
> periodically synchronizing the container status with docker

That code only gets executed when the agent starts up; it's not executed periodically.

**Comment by richardpen** [comment]
@samuelkarp Looks like I read the code wrong, updated the description.
