### ISSUE TITLE
Cannot set uid as user parameter, invalid regexp for uid 501

### ISSUE THREAD

**Issue by alemazz** [aws/amazon-ecs-agent#1049]
### Summary
Can't set uid as --user parameter, invalid regexp

### Description
On Docker you can provide --user, a uid like 501, to solve FS permissions on containers that use shared volumes 

(i.e) docker run -d --user=501 -v /var/lib/zookeeper:/var/lib/zookeeper -v /var/log/zookeeper:/var/log/zookeeper confluent/zookeeper

### Expected Behavior

Register successfully the task definition provided

### Observed Behavior

Defining:

{
  "containerDefinitions": [
    {
      "name": "zookeeper",
      "image": "confluent/zookeeper",
      "portMappings": [
        {
          "containerPort": 2181,
          "hostPort": 2181
        }
      ],
      "memory": 512,
      "user": "501",
      "essential": true
    }
  ],
  "family": "test"
}
the ecs register-task-definition call returns:

An error occurred (ClientException) when calling the RegisterTaskDefinition operation: user contains invalid characters, does not match pattern ^([a-z_][a-z0-9_-]{0,30})$

### Environment Details

OS: MacOSX
aws-cli version: aws-cli/1.11.179 Python/2.7.10 Darwin/16.7.0 botocore/1.7.37

### Supporting Log Snippets

Task definition example:

{
  "containerDefinitions": [
    {
      "name": "zookeeper",
      "image": "confluent/zookeeper",
      "portMappings": [
        {
          "containerPort": 2181,
          "hostPort": 2181
        }
      ],
      "memory": 512,
      "user": "501",
      "essential": true
    }
  ],
  "family": "test"
}

<img width="1328" alt="schermata 2017-11-02 alle 22 19 18" src="https://user-images.githubusercontent.com/5594894/32350877-e86cd560-c01b-11e7-940c-6c76c68a8b5d.png">

**Comment by alemazz** [comment]
resolved my issue specifying: 

"environment": [
        {
          "name": "USER",
          "value": "999"
        }
      ],

but probably it would be nice to have fixed

**Comment by adnxn** [comment]
@alemazz Good catch! Thanks for bringing this to our attention. I'm tagging this as bug and tracking for a fix on our service side.

**Comment by richardpen** [comment]
@alemazz Thanks for reporting this, our backend has fixed this issue. So now you should be able to register the task definition with `"user": "501",`. I'm closing this issue now.
