### ISSUE TITLE
"Network Bindings - not configured" although there are port mappings in the container.

### ISSUE THREAD

**Issue by bs-thomas** [aws/amazon-ecs-agent#1063]
### Summary
I have a task definition with 3 services:
* src (not essential)
* ssh-service (essential)  port mapping from 2211 -> 22
* web-service (essential)  port mapping from 8011 -> 80

### Description
When I look at the task via the web console, it has this screen showing web-service
"Network bindings - not configured".

![image](https://user-images.githubusercontent.com/2464920/32601983-7251799e-c57f-11e7-8e7b-ca81dbed8395.png)

In reality though, I SSH into the EC2 container, and did a "docker ps", and it is binded.  I also verify that I can actually connect to the container via IPADDRESS:8011 using HTTP.

![image](https://user-images.githubusercontent.com/2464920/32602031-92b4dac8-c57f-11e7-8863-72e35430c94d.png)

### Expected Behavior
Show properly list out the port mappings for web-service.

### Observed Behavior
Shows "Networking bindings - not configured"

### Environment Details
Nothing special, simply create an ECS cluster, create a task with the 3 containers like I have above, and will notice that for one container, the "Network Bindings" info is missing.

### Supporting Log Snippets
I got the logs, but please kindly email me at thomas@beamstyle.com.hk, I will send them to you for investigation.

**Comment by nmeyerhans** [comment]
We've confirmed that this is a software bug and have prepared a fix in #1067. We will be including the fix in release 1.15.1, which we hope to publish on Monday, 11/13.

**Comment by nmeyerhans** [comment]
We've released agent version [1.15.1](https://github.com/aws/amazon-ecs-agent/releases/tag/v1.15.1) including a fix for this issue. It's available [on Docker Hub] and in the 2017.09.b ECS Optmized AMI.
