### ISSUE TITLE
ECS Container Metadata doesn't contain task revision

### ISSUE THREAD

**Issue by endofcake** [aws/amazon-ecs-agent#1066]
### Summary
ECS Container Metadata doesn't contain task version.
EDIT: I meant task revision.

### Description

This is a feature request. ECS Container Metadata provides some useful information, including `TaskARN`. I'd like to be also able to see human-readable task version, as it's very helpful in many cases to be able to have this information directly, without having to query the API by `TaskARN`.

Thanks!

**Comment by jtoberon** [comment]
By "task version," do you mean the task definition revision as described [here](https://docs.aws.amazon.com/cli/latest/reference/ecs/describe-task-definition.html)?

**Comment by endofcake** [comment]
@jtoberon , correct, I meant task revision.
Basically it'd be very useful for us to be able to get this without doing something like `aws ecs describe-task-definition --task-definition "arn:aws:ecs:ap-southeast-2:<whatever>" --query 'taskDefinition.revision' --output text`, which requires AWS CLI installed + extra IAM permissions.

**Comment by aaithal** [comment]
We've released a new [version of the ECS agent](https://github.com/aws/amazon-ecs-agent/releases/tag/v1.17.3), which should fix this issue. Closing this for now.
