### ISSUE TITLE
"Network Bindings - not configured" although there are port mappings in the container.

### ISSUE THREAD

**Issue by jmetzmeier** [aws/amazon-ecs-agent#1075]
This is a duplicate of #1057, #1063, and possibly #1064. #1063 was closed as fixed in version 1.15.1, however, I had a chance to test today and the problem is still present in that version.

**Comment by nmeyerhans** [comment]
Can you provide me with ecs-agent agent logs and a task ID that saw impact? Are you using the ECS Optimized AMI? The logs would be in `/var/log/ecs/`

**Comment by jmetzmeier** [comment]
I sent the logs and task information to you via email. I am building an AMI using the ECS Optimized AMI as a base. Our only changes to the AMI is some basic user creation and the addition of a monitoring daemon (built via packer). I tested 1.5.0 with the vanilla AMI and still encountered the issue, but did not test vanilla with 1.5.1. The version we were using before I upgraded the AMI was 1.14.3, which continues to work properly.

**Comment by nmeyerhans** [comment]
@jmetzmeier Thanks for reporting this. We were able to confirm the issue and reproduce it here, and you can see @richardpen has just proposed a fix. I don't have an ETA for including this in a release at this time, but stay tuned for updates...

**Comment by bndw** [comment]
I believe I'm running into this as well with agent version `1.15.1`. 

* I have portMappings defined for my container
* They're being mapped by Docker
    ```
    0.0.0.0:32771->80/tcp
    ```
* `describe-tasks` does not show them (note no `networkBindings` attr):
    ```json
    {
        "containerArn": "arn:aws:ecs:us-east-2:xxx:container/b63f46d8-b45c-461b-aa56-958737b2a5c9",
        "taskArn": "arn:aws:ecs:us-east-2:xxx:task/982d52c6-8401-4fbc-b18e-76eaa09cf353",
        "lastStatus": "RUNNING",
        "name": "streamline-sidecar"
  }
  ```

**Comment by nmeyerhans** [comment]
@bndw Yes, it certainly sounds like it. We're releasing 1.15.2 today with a complete fix. Apologies for the inconvenience.

**Comment by bndw** [comment]
Thanks for the fast response @nmeyerhans

**Comment by nmeyerhans** [comment]
[Agent 1.15.2](https://github.com/aws/amazon-ecs-agent/releases/tag/v1.15.2) is available now. You can get it [from Docker Hub](https://hub.docker.com/r/amazon/amazon-ecs-agent/tags/). It's also on the latest ECS optimized AMI, 2017.09.c. The list of regional AMI IDs is available [in our docs](http://docs.aws.amazon.com/AmazonECS/latest/developerguide/ecs-optimized_AMI.html), or you can use the following command to determine the AMI ID for a given region:

    aws ec2 describe-images --owner 591542846629 --region us-west-2 --filter=Name=name,Values=amzn-ami-2017.09.c-amazon-ecs-optimized

**Comment by ctaggart** [comment]
Any idea if this bug still affects ECS Fargate?
https://forums.aws.amazon.com/thread.jspa?threadID=270940&tstart=0

**Comment by jhaynes** [comment]
@ctaggart You shouldn't be running into this bug on Fargate. If you are, please feel free to contact support. We can potentially try to debug here, but support will probably be a better option.

**Comment by guizmaii** [comment]
I confirm that this bug is always present in Fargate.

**Comment by nathando** [comment]
This cannot be closed because it still happens. Fargate does not report network bindings correctly at all. We need this information

**Comment by nietzscheson** [comment]
> This cannot be closed because it still happens. Fargate does not report network bindings correctly at all. We need this information

Yes, same for here!

![image](https://user-images.githubusercontent.com/1699198/160870963-416e4965-c086-41a9-a25d-3e0fe2e8f16e.png)
