### ISSUE TITLE
Verify windows cpu metrics calculation and cpu percent meaning

### ISSUE THREAD

**Issue by richardpen** [aws/amazon-ecs-agent#1081]
### Summary

The cpu metrics on windows is a little different from linux when the container has exhausted the lots of cpu on the instance which has multiple cpu cores. On windows it's showing 100% where on linux it's showing 100*cpucore%. We need to verify the cpu metrics on windows is calculated correctly.

Setting the cpu percent on windows by using cpushare/1024*cpucore, is this the right math to do? If the cpushares is small, there could be a chance cpupercent will be 0? Do we need to keep both cpushares and cpupercent, or just have one?

**Comment by richardpen** [comment]
Docker stats calculate the cpu percentage using the math:
`cpuPercent = (cpuDelta / systemDelta) * onlineCPUs * 100.0 #(onlineCPUS=len(cpu_usage)`
The reason why windows doesn't has >100% cpu usage like linux is due to the `len(cpu_usage)` is zero on windows.

Docker stats from windows:
```
"cpu_stats": {
    "cpu_usage": {
      "usage_in_usermode": 42031250,
      "total_usage": 103437500,
      "usage_in_kernelmode": 42031250
    },
    "throttling_data": {}
  },
```

Docker stats from linux:
```
"cpu_stats": {
      "cpu_usage": {
        "percpu_usage": [
          34386454727,
          33411699747,
          20987229560,
          20640361611
        ],
        "usage_in_usermode": 5610000000,
        "total_usage": 109425745645,
        "usage_in_kernelmode": 52840000000
      },
      "system_cpu_usage": 984307030000000,
      "throttling_data": {}
    },
```

**Comment by samuelkarp** [comment]
Does this mean that we're unaffected?  Do we need to divide the delta by the number of CPUs or not?

**Comment by richardpen** [comment]
I think we want to divide the delta by the number of CPUs, as this will give us the same result as `docker stats` on windows. If we don't divide, then it will have the same behavior like linux, where the cpu percent will be 100% * number of CPUs.

**Comment by samuelkarp** [comment]
What does TCS expect for metrics?  That's really what I'm interested in, not the `docker stats` output.  TCS will then scale the metrics by the CPU parameter in the task definition.

**Comment by richardpen** [comment]
Sorry I missed something in previous response. After some tests and looking at the code, the tcs will have the same metrics on windows and linux even though the docker stats outputs are different. Because we convert the CPU usage to be <100% for linux, see [here](https://github.com/aws/amazon-ecs-agent/blob/master/agent/stats/utils.go#L46). 

Eg: container uses 4 cpu cores on a instance will be shown 400%(on linux) and 100%(on windows) by docker stats, but TCS will report 100% cpu usage, and the cloudwatch graph will shows 100% for both linux and windows.
