### ISSUE TITLE
mechanism to limit the amount of memory used for containers

### ISSUE THREAD

**Issue by tomyan** [aws/amazon-ecs-agent#111]
The agent uses the `ReadMemInfo` function in the github.com/docker/docker/pkg/system package to determine available memory:

https://github.com/aws/amazon-ecs-agent/blob/d71b00248efad687c98bc1e9a8a7a6703e978a76/agent/api/api_client.go#L121

It seems that this is sent back to the ECS service, which allocates tasks to the instance consuming this amount of memory. This doesn't take into account anything else running on the instance (e.g. the agent, we run containers for shipping logs, etc). We would therefore like an option to reserve some of the memory for other things running on the system.

This is therefore a feature request that an option is added to allow an amount of memory to be reserved - perhaps an environment variable called `ECS_RESERVE_MEMORY_MB`. Please can you let me know what you think of this feature - whether it's worth sending a pull request that implements it?

Thanks

Tom

**Comment by euank** [comment]
This is now released, closing. Thanks again!
