### ISSUE TITLE
Windows ECS Task Stuck in Pending

### ISSUE THREAD

**Issue by sd-charris** [aws/amazon-ecs-agent#1135]
### Summary
When using the new Windows ECS Optimized instance with ECS Services, all tasks report as running (although they are un-reachable via the alb) momentarily then transition into Stopped and a new task is created and which does not move past Pending.

### Description
We recently introduced 2 new instances into our cluster with the new Windows ECS Optimized Instance AMI.  We have already configured a few ECS services in the cluster than were working fine with the 1.14.3 version of the ECS Agent.  The running tasks have a single container which is sourced from our Private Docker Feed (authentication is setup via environment variables - ECS_ENGINE_AUTH_TYPE, ECS_ENGINE_AUTH_DATA).  We updated our User Data script to account for the new process for launching the ecs-agent:

```
[Environment]::SetEnvironmentVariable("ECS_ENGINE_AUTH_TYPE", "dockercfg", "Machine")
[Environment]::SetEnvironmentVariable("ECS_ENGINE_AUTH_DATA", '{"privaterepo.com": {"auth": "SOMEBASE64ENCODEDSECRET"}}', "Machine")

Import-Module ECSTools
Initialize-ECSAgent -Cluster Hero-WindowsCluster -EnableTaskIAMRole

new-netfirewallrule -displayname 'ECS and DockerEphemeralPorts' -direction inbound -action allow -protocol tcp -LocalPort 23, 5000-65535
```

The agent appears to start up fine and pulls the docker images from our repo just fine.  Prior to the ecs agent picking up the tasks it needs to place, the command 'Docker ps' works just fine and reports no running containers.  The ecs agent picks up the tasks it needs to run and they transition from None -> Running shortly there after.  It remains in the running state momentarily and then transitions into Stopped where another task is placed which does not move out of Running.  At this point the command 'docker ps' is unresponsive.

### Expected Behavior
When placing a task on the new Windows Optimized ECS image the task transitions to Running and if configured as a ECS Service it will be placed in the appropriate target group.

### Observed Behavior
When placing a task on the windows optimized ecs image the task transitions from running to stopped and it remains unresponsive.  

### Environment Details
Windows_Server-2016-English-Full-ECS_Optimized-2017.11.24 (ami-0b60bc73)

### Supporting Log Snippets
An error we are seeing in the Logs:

Error getting message from ws backend: error: [websocket: close 1002 (protocol error): Channel long idle: No message is received, close the channel], messageType: [-1] 

Error from tcs; backing off: websocket: close 1002 (protocol error): Channel long idle: No message is received, close the channel

Error transitioning container module="TaskEngine" task="microsvc:25 arn:aws:ecs:us-west-2:ACCOUNTID:task/SOMEGUID, TaskStatus: (RUNNING->STOPPED) Containers: [microsvc (RUNNING->STOPPED),]" container="microsvc(privaterepo.com/microsvc:2.0.46-master) (RUNNING->STOPPED)" state="STOPPED" error="Could not transition to stopped; timed out after waiting 1m0s"

**Comment by tehshwann** [comment]
@sd-charris are you able to use the 'dockercfg' engine auth type successfully on Windows in other cases?

**Comment by sd-charris** [comment]
The dockercfg engine auth type was working successfully with the windows container host AMI and the previous ecs agent.  It "seems" to be pulling the image correctly, in the past when pulling from our repo failed the error reported was pretty explicit.

**Comment by tehshwann** [comment]
@sd-charris could you share the AMI / AWS region that you had this working with?

The Windows_Server-2016-English-Full-ECS_Optimized-2017.11.24 (ami-0b60bc73) AMI is running Docker 17.06 EE, and I suspect the older AMIs had Docker CE... but I wanted to make sure.

**Comment by sd-charris** [comment]
@tehshwann 
Windows_Server-2016-English-Full-ECS_Optimized-2017.11.24 (ami-0b60bc73) 
US-WEST-2

**Comment by msheppard-nf** [comment]
@sd-charris Do your task definitions have a value for CPU defined?

**Comment by sd-charris** [comment]
@msheppard-nf We have it currently set to "100"

```
    "containerDefinitions": [
        {
            "name": "microsvc",
            "image": "privaterepo.com/microsvc:2.0.46-master",
            "portMappings": [
                {
                    "hostPort": 0,
                    "protocol": "tcp",
                    "containerPort": 80
                }
            ],
            "cpu": 100,
            "memory": 500,
            "environment": [
                {
                    "name": "ServiceName",
                    "value": "microsvc"
                }
            ],
            "dnsServers": null,
            "mountPoints": [],
            "volumesFrom": [],
            "essential": true
        }
    ]
```

**Comment by petderek** [comment]
@sd-charris 

The newest agent enforces CPU limits on windows, whereas limits weren't enforced in earlier releases. Consider trying the same task with a higher `cpu` value, such as 512.

**Comment by sd-charris** [comment]
Setting it to 512 worked!  Thank you!

Is there a way to ignore the limits, or incorporate a soft/hard limit?  It feels like our biggest resource cost is starting up iis the first time.

**Comment by aaithal** [comment]
Hi @sd-charris, we do not recommend ignoring limits here as tasks could get into issues describe in #1144. Closing this issue for now as the original issue seems to have been resolved. Feel free to chime in to the discussion in #1144 or to create a new issue if you have other questions/comments. 

Thanks,
Anirudh
