### ISSUE TITLE
Docker versions comparator

### ISSUE THREAD

**Issue by sharanyad** [aws/amazon-ecs-agent#1137]
### Summary
Docker remote API versions do not follow [semantic versioning](https://semver.org/).  
There are few instances in agent, where Docker API versions are compared. Hence, having a version comparator for them will be useful.

### Description
Currently, to compare Docker API versions, we have to add a zero patch to make them compliant with semver eg. change 1.24 -> 1.24.0 and then use the comparator [here](https://github.com/aws/amazon-ecs-agent/blob/master/agent/utils/compare_versions.go). Add a separate comparator for remote API versions.

**Comment by adnxn** [comment]
closing issue, merged with #1625. expected to be released with agent v1.22.0
