### ISSUE TITLE
AWS ECS cluster instances coming up on their own even after the cluster is deleted

### ISSUE THREAD

**Issue by binitdatta** [aws/amazon-ecs-agent#1150]
### Description

I created an ECS cluster with three member instances for testing. Once I was done, I terminated all three. I then deleted the cluster. However, the member instances keep coming up no matter how many times I deleted them manually.

This is not a desirable  situation for me as my bill would go very high.

I would like to know what could be a possible reason for this to happen.

### Expected Behavior

ECS member instance stay terminated when the cluster is deleted and instances are terminated manually.

### Observed Behavior

ECS instances keep getting automatically even after I deleted them manually.

**Comment by samuelkarp** [comment]
You probably have an Auto Scaling group that is launching new instances.  From [the documentation](https://docs.aws.amazon.com/AmazonECS/latest/developerguide/deregister_container_instance.html):

> Note
>
> If your instance is maintained by an Auto Scaling group or AWS CloudFormation stack, terminate the instance by updating the Auto Scaling group or AWS CloudFormation stack. Otherwise, the Auto Scaling group re-creates the instance after you terminate it.

You'll want to ensure you remove the Auto Scaling group to prevent it from launching new instances.

**Comment by samuelkarp** [comment]
We haven't heard back from you in a few days, so I'm closing this.  Please let us know if you continue to have difficulty removing the Auto Scaling group.
