### ISSUE TITLE
UI Problem in ECS UI Console

### ISSUE THREAD

**Issue by Alonreznik** [aws/amazon-ecs-agent#1153]
Hi!
I know that this is maybe not the correct forum for UI critical problem, however, there is no answer in the official forum. 

ECS console has a critic problem in the last week that hadn't been resolved yet. 

We're encountering with a bug when we try to update our service in some cluster from the task definition screen.
If we make a new task definition from the last one, and then (after it created) - go to the +Actions+>Update Service - We can't pass the second step of the load balancer. The button just doesn't work and the console returns an error of:

```
Uncaught TypeError: Cannot read property 'loadBalancer' of undefined
    at Object.n.step2Next [as onClick] (ecs_console_prod_f21ea5079ac90dcfac72a76d15774cb678834831.gz.js:151)
    at y.f.buttonPress (ecs_console_prod_f21ea5079ac90dcfac72a76d15774cb678834831.gz.js:151)
    at ecs_console_prod_f21ea5079ac90dcfac72a76d15774cb678834831.gz.js:7
    at E (ecs_console_prod_f21ea5079ac90dcfac72a76d15774cb678834831.gz.js:7)
    at y.$eval (ecs_console_prod_f21ea5079ac90dcfac72a76d15774cb678834831.gz.js:7)
    at y.$apply (ecs_console_prod_f21ea5079ac90dcfac72a76d15774cb678834831.gz.js:7)
    at HTMLElement.<anonymous> (ecs_console_prod_f21ea5079ac90dcfac72a76d15774cb678834831.gz.js:7)
    at HTMLElement.dispatch (ecs_console_prod_f21ea5079ac90dcfac72a76d15774cb678834831.gz.js:2)
    at HTMLElement.u (ecs_console_prod_f21ea5079ac90dcfac72a76d15774cb678834831.gz.js:2)
```

Our container doesn't use the load balancer, so we did not configure any. 

Please fix it or send it to the right person for fix.
That is something the **Make our deployment almost impossible**.

Thanks for your help

Alon

**Comment by jahkeup** [comment]
Hi @Alonreznik, thanks for the detailed report! I've sent this issue along to the right people internally to get their input on the matter.

**Comment by underq** [comment]
Hi,
We have the same critical problem to update service, however the stacktrace is not identical :

```
Error: n.elbDataObject is undefined
n.step2Next@https://d1blsl7w6pcvbk.cloudfront.net/js/ecs_console_prod_f21ea5079ac90dcfac72a76d15774cb678834831.gz.js:151:788428
f.buttonPress@https://d1blsl7w6pcvbk.cloudfront.net/js/ecs_console_prod_f21ea5079ac90dcfac72a76d15774cb678834831.gz.js:151:59998
recurse/<@https://d1blsl7w6pcvbk.cloudfront.net/js/ecs_console_prod_f21ea5079ac90dcfac72a76d15774cb678834831.gz.js:7:194618
E@https://d1blsl7w6pcvbk.cloudfront.net/js/ecs_console_prod_f21ea5079ac90dcfac72a76d15774cb678834831.gz.js:7:206219
$eval@https://d1blsl7w6pcvbk.cloudfront.net/js/ecs_console_prod_f21ea5079ac90dcfac72a76d15774cb678834831.gz.js:7:146027
$apply@https://d1blsl7w6pcvbk.cloudfront.net/js/ecs_console_prod_f21ea5079ac90dcfac72a76d15774cb678834831.gz.js:7:146252
compile/</<@https://d1blsl7w6pcvbk.cloudfront.net/js/ecs_console_prod_f21ea5079ac90dcfac72a76d15774cb678834831.gz.js:7:206269
dispatch@https://d1blsl7w6pcvbk.cloudfront.net/js/ecs_console_prod_f21ea5079ac90dcfac72a76d15774cb678834831.gz.js:2:38254
u@https://d1blsl7w6pcvbk.cloudfront.net/js/ecs_console_prod_f21ea5079ac90dcfac72a76d15774cb678834831.gz.js:2:34134
```

Hoping that may help you to resolve the bug.

Best Regards
Benjamin

**Comment by Tushar-Tilwani** [comment]
Developer from ECS here. We confirmed this is a bug and we are currently deploying a bug fix for this issue. The bug fix should be deployed to all regions by end of day Jan 5th (PST). Thank you for bringing this to our attention.

**Comment by Alonreznik** [comment]
Hi @Tushar-Tilwani and Jake. Thank you for your response. 
Please pay attention to the official forum next time. The bug was opened there over than a week until I've opened it here.

Thank you for your fix
Alon

**Comment by richardpen** [comment]
@Alonreznik @underq Thanks for reporting this issue. The bug fix for the UI has been deployed to all regions.
