### ISSUE TITLE
Application Logs in ECS

### ISSUE THREAD

**Issue by priyankasudhindra** [aws/amazon-ecs-agent#1159]
I have two EC2 instances running on a cluster and I need help in identifying where the application logs are being written.

Thanks in advance.

**Comment by richardpen** [comment]
@priyankasudhindra I think you are looking for the container logs, right? If you are using the default logging driver, then the container logs can be acquired by `docker logs container_id` or it's stored `/var/lib/docker/containers/<container id>/<container id>-json.log`. If you are using other logging drivers, you may need to check your logging driver configuration for the logs eg: the [awslogs logging driver](https://docs.docker.com/engine/admin/logging/awslogs/) will send the container logs to Amazon CloudWatch Logs.

**Comment by priyankasudhindra** [comment]
Thank you so much @richardpen.
That helped.
