### ISSUE TITLE
log file name

### ISSUE THREAD

**Issue by DaveBlooman** [aws/amazon-ecs-agent#116]
When launching the agent, the log file appends the current date onto the end of the file, is there a way to prevent this?
Docker version 1.5
OS : Centos 6
Agent : Latest

**Comment by DaveBlooman** [comment]
This appears to have occurred after 1.0, could there be an option for later versions to use a specific file name?

**Comment by euank** [comment]
This change happened in v1.1.0.
As a workaround, you could set ECS_LOGFILE="", not background it, and redirect stdout/stderr to a file named as you expect, but that's a bit hacky and won't work for all cases.
I'll take this as a feature request.

Out of curiosity, is the desire for the old behavior so that the logfile can be managed by another program instead?

**Comment by DaveBlooman** [comment]
I want to send logs to AWS cloudwatch using the awslogs package, which requires a file.  I haven't looked into a container based solution yet, but I don't believe awslogs package can fuzzy match a log file.   [Info here](http://docs.aws.amazon.com/AmazonCloudWatch/latest/DeveloperGuide/QuickStartEC2Instance.html)

If there is a way, it would be great know.

**Comment by aaithal** [comment]
Hi @DaveBlooman, CW logs lets you stream rotating log files: http://docs.aws.amazon.com/AmazonCloudWatch/latest/DeveloperGuide/AgentReference.html

You can also specify regexes for 'file' as denoted in the same link.

**Comment by DaveBlooman** [comment]
Damn, just missing an *

Have logs working great on the latest version, thanks for the help

**Comment by jsok** [comment]
+1 on this issue.

Wouldn't it be more sensible to call the "current" log file the same as that specified in `LOG_FILE` and only append the date once it's rotated out?

I'm trying to pick up the ECS logs using rsyslogd (it does have wildcard support but only in more recent versions).

**Comment by joostdevries** [comment]
@aaithal could this be reopened? It's quite annoying that I cannot use syslog to capture log output and can also not use syslog to process the files..

**Comment by joshuamcdo** [comment]
I agree, this is creating hours worth of research and work around just to be able to work with these 'log files'...  Just my opinion that the log file should be a single file by default and only have a .1 .2 .3 appended to each rotation accordingly.

**Comment by aaithal** [comment]
I have created #287 to track this as the issue is a bit different from the initial request of processing log files in Cloudwatch.
