### ISSUE TITLE
 -v

### ISSUE THREAD

**Issue by pat-clark-avalara** [aws/amazon-ecs-agent#1175]

**Comment by richardpen** [comment]
@pat-clark-avalara Given there isn't much context in this issue, I'm assuming you mean the `-v` option to print out the agent version, please correct me if that's not what you mean.

Actually the agent does support the `-version` eg:
```
$ docker run amazon/amazon-ecs-agent:latest -version
Amazon ECS Agent:
	Version: 1.16.0
	Commit: adf84ba
	Dirty: true
```
