### ISSUE TITLE
Unable to use TCP with gelf for docker logs

### ISSUE THREAD

**Issue by mariusmitrofan** [aws/amazon-ecs-agent#1180]
### Summary
When using the any ECS default AMI (including the latest one), one cannot send container logs to a TCP endpoint that is running GELF.

### Description
What I mean is, if one would set "gelf-address" to be something similar to "tcp://gelf_endpoint_here:12201" whilst having the "Log Configuration" set to "gelf", the task definition which runs that container will fail.

The error which pops up is : "STOPPED (CannotCreateContainerError: API error (500): gelf:)"

### Expected Behavior
I am expecting the container to start and send logs to my gelf TCP endpoint.

### Observed Behavior
Task Definition fails using any AMI (tested 3 versions).

This might be a problem caused by the fact that the AMI is not running on the "actual" latest docker version, but unfortunately, I can't test that theory.

### Environment Details
Sample config :
agent version = 1.16.1
docker version = 17.06.2-ce

**Comment by richardpen** [comment]
@mariusmitrofan Thanks for reaching out to us, currently the latest version of Docker supported on ECS Optimized AMI is [17.06.2-ce](https://docs.aws.amazon.com/AmazonECS/latest/developerguide/ecs-optimized_AMI.html), however the tcp support for gelf logging driver is added in Docker [17.11.0-ce](https://docs.docker.com/release-notes/docker-ce/#17110-ce-2017-11-20). So this is why you got this error when trying to use gelf with tcp in your task. I'll mark this as a feature request, we will update when we have the supported docker version 17.11.0-ce in ECS Optimized AMI.

**Comment by mariusmitrofan** [comment]
@richardpen Thanks for the info. Any idea what's the timeline on this maybe?

**Comment by richardpen** [comment]
@mariusmitrofan Generally we don't talk our roadmap publicly. Currently, the supported version in ECS Optimized AMI is `17.06.2`, which is a little behind the latest version `17.12.0-ce`, we will update here whenever we have more information.

Thanks

**Comment by zikphil** [comment]
Any updates about 17.11.0-ce ?

**Comment by richardpen** [comment]
@mariusmitrofan @dagus  @zikphil We have released docker 17.12.0-ce in ECS Optimized AMI [2017.09.j](https://docs.aws.amazon.com/AmazonECS/latest/developerguide/ecs-optimized_AMI.html). You should be able to use the gelf logging driver by setting the `ECS_AVAILABLE_LOGGING_DRIVERS` environment variable now. I'm closing this issue now, feel free to reopen if you have any further questions.
