### ISSUE TITLE
 Status reason	OutOfMemoryError: Container killed due to memory usage Exit Code	137

### ISSUE THREAD

**Issue by dulimitta** [aws/amazon-ecs-agent#1187]
I am trying to launch a Fargate instance with Task memory (MiB)1024, Task CPU (unit)512, Container Hard/Soft Memory 500 MiB. It is a very simple service.
The service is failing to start with below error.

 Status reason	OutOfMemoryError: Container killed due to memory usage Exit Code	137

**Comment by aaithal** [comment]
Hi @dulimitta, we're sorry that you're running into this issue. It usually means that your application needs more memory that what you have allocated for it. You could try increasing the memory limit for your container/task. You could also profile how much memory is needed by the container by running it on a host that you control and determine the optimal value for that. 

If you continue running into issues, our recommendation would be to get in touch with [AWS support](https://console.aws.amazon.com/support/home) as they'd be the best people to help you with such issues. I am closing this issue for now. If you run into any ECS agent issues, feel free to create issues in this repository. 

Thanks,
Anirudh

**Comment by Vihanth** [comment]
@dulimitta  did you find any solution for this problem? I'm stuck with the same problem.

**Comment by dulimitta** [comment]
@Vihanth yes. one of our services was generating a bunch of logs which caused the issue. It is always good to push the logs to cloud watch so that the containers will be clean.

**Comment by leedahl** [comment]
Was it a memory issue or a disk issue then, dulimitta?  I am trying to understand if I need more disk space or memory for my application.

**Comment by dulimitta** [comment]
apparently it was a disk space issue, @leedahl 
initially thought memory issue.
