### ISSUE TITLE
Best practice to ship ECS agent logs to Cloudwatch Logs?

### ISSUE THREAD

**Issue by melo** [aws/amazon-ecs-agent#1188]
Hi,

is there a best practice recommended by the ECS agent team to ship ECS agents logs to Cloudwatch Logs?

Using the Cloudwatch logs collector? Can we expect native shipping of logs directly from the agent? 

Thanks,

**Comment by aaithal** [comment]
Hi @melo, thank you for reaching out to us regarding this. Please take a look at our [documentation page](https://docs.aws.amazon.com/AmazonECS/latest/developerguide/using_cloudwatch_logs.html) for more information on how to do this. 

Thanks,
Anirudh

**Comment by melo** [comment]
@aaithal sorry if I wasn't clear, I wasn't talking about container instance logs, we already ship those to Cloudwatch Logs.

I'm talking about the container agent itself, the ECS Agent logs, that currently are written in the `/var/log/ecs/` directory on each of our EC2 instances that are part of the ECS cluster.

I want to ship those logs to Cloudwatch.

Thank you,

**Comment by aaithal** [comment]
Right, the documentation page I linked do talk about how that can be done. If you search for `/var/log/ecs` in that page, you should be able to spot it, in [this](https://docs.aws.amazon.com/AmazonECS/latest/developerguide/using_cloudwatch_logs.html#cwlogs_user_data) section.

**Comment by melo** [comment]
@aaithal my apologies, I missed that one...

Thank you for your time.

**Comment by robertoandrade** [comment]
Is there an equivalent to doing that on Windows ECS cluster instances?

**Comment by Zogoo** [comment]
It seems like lots of things changed. @melo , @aaithal could you guys share with me "cloud watch config json" file that allows to ship ECS agent to CloudWatch.

**Comment by angelcar** [comment]
Hi @Zogoo 

You just need to add a configuration similar to the following:

```json
{
    "logs": {
        "logs_collected": {
            "files": {
                "collect_list": [
                    {
                        "file_path": "/var/log/ecs/ecs-agent.log*",
                        "log_group_name": "/var/log/ecs/ecs-agent.log"
                    }
                ]
            }
        }
    }
}
```

For more information related to CloudWatch Agent configuration, please refer to: https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/create-cloudwatch-agent-configuration-file.html
