### ISSUE TITLE
ECS - Repository

### ISSUE THREAD

**Issue by dulimitta** [aws/amazon-ecs-agent#1189]
### Supporting Log Snippets

Not positive if I am posting the question in the right place.

Do I need one ECS repository for one image? I feel like I can store multiple versions of an image in one repository. Can't I store multiple images in one single repository? 

docker build -t app1 .
docker tag app1:latest xxxxxx.dkr.ecr.us-east-1.amazonaws.com/app1:latest
docker push xxxxxx.dkr.ecr.us-east-1.amazonaws.com/app1:latest

**Comment by aaithal** [comment]
Hi @dulimitta, thanks for reaching out to us with this question. However, I'd recommend reading the documentation for [ECR](https://docs.aws.amazon.com/AmazonECR/latest/userguide/what-is-ecr.html) or reaching out to AWS Support via [forums](forums.aws.amazon.com) or getting in touch with [AWS support](https://console.aws.amazon.com/support/home) for best practices when dealing with ECR images. 

Depending on your use case, the suggestion might be to go multiple repositories. But, I'd defer it to one of the 3 places above to get more information about best practices. 

Thanks,
Anirudh
