### ISSUE TITLE
TestTaskMetadataValidator fails with older agents

### ISSUE THREAD

**Issue by samuelkarp** [aws/amazon-ecs-agent#1191]
### Summary
TestTaskMetadataValidator fails with older agents

### Description
[TestTaskMetadataValidator](https://github.com/aws/amazon-ecs-agent/blob/27a1a4de898f3d4a402327ddcfe77408e0eb9ef8/agent/functional_tests/tests/functionaltests_unix_test.go#L673-L674) does not `agent.RequireVersion(>=1.17.0)`, so it fails when run with an old agent.

### Expected Behavior
Test is skipped for an agent that is to old

### Observed Behavior
Test runs and fails

**Comment by richardpen** [comment]
This has been fixed in #1218
