### ISSUE TITLE
hostsetup.ps1 for Windows agent needs some attention

### ISSUE THREAD

**Issue by tehshwann** [aws/amazon-ecs-agent#1198]
### Summary

Instance configuration code for Task IAM Roles via hostsetup.ps1 requires fixes implemented in the AWS ECS Optimized Windows AMI in the ECSTools powershell module.

### Description

A number of issues, including race conditions and timing issues such as this one (https://github.com/aws/amazon-ecs-agent/pull/1042) have been fixed and implemented in the 'ECSTools' powershell module shipped with the ECS Optimized Windows image for AWS Elastic Container Service. These fixes were not implemented in this code base. The fixes should be integrated somehow.

I suspect there are a number of dependencies on hostsetup.ps1 that require some extra thought.

Option would be to copy the ECSTools code into hostsetup.ps1... but this will allow the two to diverge over time.

A second, more reliable but more costly, option would be to refactor this agent code base to use the ECSTools module, and flesh out the dependencies on hostsetup.ps1 as it is today that may or may not work with that model.

The biggest concern is that ECSTools interacts with agent as a Windows Service, and hostsetup.ps1 assumes agent is an exe running via a scheduled task.

### Environment Details

ECS Windows w/ hostsetup.ps1 for use of Task IAM Roles

**Comment by aaithal** [comment]
@tehshwann since we are recommending that `ECSTools` ps module be used to install/manage ECS agent, can we just get rid of the `hostSetup` script in the agent repo?

**Comment by tehshwann** [comment]
@aaithal i think that makes sense as long as the hostsetup references in tests and test setup are updated to point to the module rather than the hostsetup. This would require the module to expose the hostsetup function though, which it does not today.

**Comment by yunhee-l** [comment]
The old script (hostsetup.ps1) is outdated at this point, and we are looking into easier way of vending ECSTools module to customers which contains the replacement script. You have worked around by copying it from an ECS Optimized AMI instance.

**Comment by adnxn** [comment]
> But it looks like ECS task roles are broken. 
> Am I missing something here?

@brubtsov: have you looked at these [instructions for windows task roles](https://docs.aws.amazon.com/AmazonECS/latest/developerguide/windows_task_IAM_roles.html). 

there is a part about 

> "Before containers can access the credential proxy on the container instance to get credentials, the container must be bootstrapped with the required networking commands."

I suspect this is the part you are missing.

**Comment by adnxn** [comment]
> The old script (hostsetup.ps1) is outdated at this point, and we are looking into easier way of vending ECSTools module to customers which contains the replacement script. You have worked around by copying it from an ECS Optimized AMI instance.

 closing this issue since hostsetup.ps1 is outdated.

**Comment by SleeperSmith** [comment]
> we are looking into easier way of vending ECSTools module to customers which contains the replacement script

@yunhee-l So any pointers on where to find official documentation on installing ECS agent outside of ecs optimised windows ami?
