### ISSUE TITLE
Containers stops frequently

### ISSUE THREAD

**Issue by dulimitta** [aws/amazon-ecs-agent#1202]
The ECS containers are stopping and starting frequently.
Some requests are failing because of this issue. Some containers are never reachable.

**Comment by aaithal** [comment]
Hi @dulimitta, we're sorry to hear that you're running into this. Can you please provide more details about the issue that you're running into (We'd also appreciate it if you could fill out as many fields as possible in the issue template)? 

1. Are your containers stopping on their own accord? If yes, are they running out of memory? Have you looked at your container logs/exit codes etc?
1. Is the ECS agent behaving erratically (throwing errors, exceptions, getting stuck etc)? Are the ECS agent logs emitting any errors? If this is the case, we'd need ECS agent logs (which you can send to aithal at amazon dot com). 
1. Is Docker daemon behaving erratically? 


Please take a look at [ECS Troubleshooting doc](https://docs.aws.amazon.com/AmazonECS/latest/developerguide/troubleshooting.html) and [ECS Logs Collector documentation](https://docs.aws.amazon.com/AmazonECS/latest/developerguide/ecs-logs-collector.html) as well.

Thanks,
Anirudh

**Comment by dulimitta** [comment]
Thanks, @aaithal for the quick reply. 
Yes, the containers stopping on their own. I don't see out of memory error in ecs logs.
Some containers are never reachable and some are random. 
Please check your emails for ecs logs.
Thank you.

**Comment by aaithal** [comment]
Hi @dulimitta, thanks for sending those logs. I do not see any errors in the ECS agent from the logs you sent. I took a quick look at the stopped tasks in the service that you sent me over the email. All of these have been stopped with the reason "Essential container in task exited", which means that the container in the task stopped on its own. Please take a look at the container logs to figure out what's going wrong here. Here's some links, which could be helpful in this regard:

* https://docs.docker.com/engine/reference/commandline/container_logs/
* https://docs.aws.amazon.com/AmazonECS/latest/developerguide/using_awslogs.html

Please reach out to  [AWS support](https://console.aws.amazon.com/support/home) if you need more help debugging this. 

Thanks,
Anirudh

**Comment by dulimitta** [comment]
Thank you @aaithal 
I could see some errors in the container logs and that is so obvious that they are restarting. 
But I could not see any errors in few containers which are not reachable using their private IP addresses. 
I can see connection timeouts in error logs. 
Is there a way to troubleshoot this issue?
