### ISSUE TITLE
Wire context into methods that invokes Docker API Call

### ISSUE THREAD

**Issue by richardpen** [aws/amazon-ecs-agent#1212]
### Summary

Agent wrapped all the Docker API call into an [interface](https://github.com/aws/amazon-ecs-agent/blob/master/agent/engine/docker_container_engine.go#L95), where a timeout duration was passed in as a parameter. A context was created inside the method itself to cancel the call, but there is no way to cancel the context from the caller. So instead of passing the timeout duration, a context should be created in the caller and passed to the call so that it can be canceled from the caller.

### Expected Behavior
The Docker API call can be canceled from the caller.

### Observed Behavior
Docker API can only be canceled with a timeout, there isn't a way to cancel it before the timeout in the caller.

**Comment by aaithal** [comment]
Related: https://travis-ci.org/aws/amazon-ecs-agent/builds/348472578?utm_source=github_status&utm_medium=notification

```
--- FAIL: TestRemoveImageTimeout (0.01s)
	<autogenerated>:1: missing call(s) to *mock_dockeriface.MockClient.RemoveImage(is equal to image)
	<autogenerated>:1: aborting test due to missing call(s)
=== RUN   TestRemoveImage
--- FAIL: TestRemoveImage (0.02s)
	docker_client_test.go:970: Did not expect error, err: Could not transition to removing image; timed out after waiting 2ms
	<autogenerated>:1: missing call(s) to *mock_dockeriface.MockClient.RemoveImage(is equal to image)
	<autogenerated>:1: aborting test due to missing call(s)
```

**Comment by richardpen** [comment]
```
--- FAIL: TestInspectContainerTimeout (0.00s)
 	<autogenerated>:1: missing call(s) to *mock_dockeriface.MockClient.InspectContainerWithContext(is equal to id, is anything)
 	<autogenerated>:1: aborting test due to missing call(s)
```
