### ISSUE TITLE
ECS is not working as expected

### ISSUE THREAD

**Issue by praveen070290** [aws/amazon-ecs-agent#1215]
### Summary

ECS is not working properly.

### Description

I am new in cloud, I am trying to deploy a .net application in ECS windows cluster and when i try to create a cluster an instance will launch automatically, but unfortunately the system doesn't not have any application, only ecs application is installed and i need to install EC2Config application then i need to install the EC2ElasticGPUs after i installed both it was working for sometime and it through a error as below in the ECS log console, i.e.  `Error running http api: listen tcp 127.0.0.1:51679: bind: Only one usage of each socket address (protocol/network address/port) is normally permitted. ` 
(because of the above issue when i run a task its status stuck in pending, for fixing this issue i did some registry update and also not worked), another interesting things is i tried to create a linux cluster and it is working as expected. I am working on this for last one week and still having issue. It would be great if some one help on this.

**Comment by aaithal** [comment]
Hi @praveen070290, 

As per my response [here](https://github.com/aws/amazon-ecs-agent/issues/731#issuecomment-360520052), this Github repository is not the right medium to seek the kind of help you're looking for. We use to dive help investigate any ECS agent issues and it seems like you're not running into that. I'd recommend contacting [AWS support](https://console.aws.amazon.com/support/home) for this. 

Thanks,
Anirudh
