### ISSUE TITLE
ERROR: Service:AmazonECS, Code:ClientException, Message:TCP host port '3000' is mapped multiple times in task., Class:com.amazonaws.services.ecs.model.ClientException

### ISSUE THREAD

**Issue by sharma02gaurav** [aws/amazon-ecs-agent#1220]
### Summary

I am getting the following error while trying to deploy a multi docker container through AWS EBS.

**Comment by aaithal** [comment]
Hi @sharma02gaurav, as hinted by the error message, you seem to have multiple containers attempting to use the same port in the task. Once you modify that, this error should go away. Also, the Elastic Beanstalk support team would be best suited to recommend how your beanstalk environment translates to an ECS environment. I'd recommend contacting [AWS support](https://console.aws.amazon.com/support/home) if you need further assistance.
