### ISSUE TITLE
Assign dynamic ports to environment variables

### ISSUE THREAD

**Issue by alexbilbie** [aws/amazon-ecs-agent#1242]
### Summary

Make assigned dynamic ports available to containers as environment variables.

This is so containers can register their actual ports with service discovery services.

### Description

Given a task which has one container running with bridge networking and is internally listening on port `2345` and is assigned the port `6789` by the operating system; in order to discover which port has been assigned the current method requires:

1. Get the cluster name from `http://localhost:51678/v1/metadata`
2. Get the container ID by reading `/proc/1/cpuset`
3. Get the task ARN from `http://172.17.0.1:51678/v1/tasks?dockerid={docker ID from above}`
4. Call ECS DescribeTasks API filtering by cluster name and task ARN to get the port mapping
5. Setting environment variables such as `PORT_2345=6789`

Ideally the ECS agent would set these environment variables on the container.

**Comment by adnxn** [comment]
@alexbilbie if I understand your use case correctly, I think it can be covered by using the agent's [container metadata file](https://docs.aws.amazon.com/AmazonECS/latest/developerguide/container-metadata.html). By enabling this feature, you can query the information about a task, container, and container instance from within the container or from the container instance by reading the metadata file for each container.

Let me know if that works for you. Thanks.

**Comment by alexbilbie** [comment]
That looks like exactly what I'm after. Thank you @adnxn
