### ISSUE TITLE
Fargate: CannotPullContainer located on ECS registry when using private networking

### ISSUE THREAD

**Issue by mfornasa** [aws/amazon-ecs-agent#1246]
### Summary
Can't create Fargate services in a private networking environment.

### Description
When configuring a service in Fargate with no public IP address, I get:
```
CannotPullContainerError: API error (500): Get https://XXX.dkr.ecr.us-east-1.amazonaws.com/v2/: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
```

I tried to follow the instructions in comment https://github.com/aws/amazon-ecs-agent/issues/1128#issuecomment-351545461:

* I set up a private subnet in a brand new VPC
* I create a NAT gateway for the VPC subnet
* I create an entry in the route table `0.0.0.0/0 -> nat_gw_xxx`

However, the error is still present.

### Expected Behavior
The service is created.

### Observed Behavior
The service is not created as the image pull fails.

**Comment by richardpen** [comment]
@mfornasa Sorry for the late response, I wasn't able to find out reason given the constraint information here. If you are still experiencing the problem please reach out to our customer support, they can have a better overview of your network setting and help you configure the networks.

**Comment by mfornasa** [comment]
@richardpen can you confirm that it’s possible to use Fargate without a public IP address?

**Comment by richardpen** [comment]
@mfornasa Yes, it's possible to use Fargate without public IP address, but you'll need to set up the NAT Gateway or NAT instance in your VPC to give the ENI internet access. You can find the setup details for task without public IP in this [document](https://aws.amazon.com/blogs/compute/task-networking-in-aws-fargate/).
