### ISSUE TITLE
image pull: measure and introduce InactivityTimeout parameter

### ISSUE THREAD

**Issue by adnxn** [aws/amazon-ecs-agent#1249]
Today image pulls could potentially hang due to underlying issues with docker and the agent will only fall back on the [pullImageTimeout](https://github.com/aws/amazon-ecs-agent/blob/761937f7fb98a06bea00c4f55f9c594560e73725/agent/engine/docker_client.go#L66). We should evaluate reasonable duration for an [InactivityTimeout](https://github.com/fsouza/go-dockerclient/blob/ca33ff277b527ce11b793e62f9ba244129b01caf/image.go#L301) and add it to the pull image options [here](https://github.com/aws/amazon-ecs-agent/blob/c051f10b219cac94c14cc533c050902bce354219/agent/engine/docker_client.go).

**Comment by aaithal** [comment]
We've released a new [version of the ECS agent](https://github.com/aws/amazon-ecs-agent/releases/tag/v1.17.3), which should fix this issue. Closing this for now.
