### ISSUE TITLE
ECS optimized AMI no longer starts ecs service

### ISSUE THREAD

**Issue by sgendler-stem** [aws/amazon-ecs-agent#1250]
### Summary
Latest ECS-optimized AMI requires manual intervention to start ecs service on instance

### Description
I updated my cluster to use the latest ECS-optimized AMI for us-east-1: ami-5e414e2 at the same time that I also increased the size of my instances to m5.large (from t2.small).  I didn't change anything else, initially, yet the new instances came up without joining the ECS cluster.  Checking the /etc/ecs/ecs.config file, everything looked normal.  I eventually figured out that there was no ecs service running.  Manually running 'start ecs' as root fixed the problem - a step that I did not used to have to execute explicitly.  Easy enough to modify user_data accordingly, but I don't see anything in the documentation that suggests it should be necessary, and I've been through a number of AMIs in the past using the same user_data, without having to explicitly execute 'start ecs' at any time

### Expected Behavior
I expected the ECS service to start automatically and to automatically detect changes to the config that occur via user-data at init time.  

### Observed Behavior
New instances do not join the ECS cluster until I manually run 'start ecs' as root or add a line to my user-data which does the same

### Environment Details
```
# docker info
Containers: 2
 Running: 1
 Paused: 0
 Stopped: 1
Images: 3
Server Version: 17.09.1-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 06b9cb35161009dcb7123345749fef02f7cea8e0
runc version: 3f2f8b84a77f73d38244dd690525642a72156c64
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.9.77-31.58.amzn1.x86_64
Operating System: Amazon Linux AMI 2017.09
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 7.51GiB
Name: ip-10-1-121-41
ID: OBIH:X32C:W3WP:LBYM:SERO:3QFC:TLAS:7PAD:QOKD:LZJJ:T64M:43B2
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

```
# curl http://localhost:51678/v1/metadata
{"Cluster":"ecs_prod_stemops_com","ContainerInstanceArn":"arn:aws:ecs:us-east-1:317003745839:container-instance/7d5f8b75-6dd9-4f92-862a-e138ec9d0dc1","Version":"Amazon ECS Agent - v1.17.0 (761937f7)"
```

```
# df -h 
Filesystem      Size  Used Avail Use% Mounted on
/dev/nvme0n1p1   99G  1.6G   97G   2% /
devtmpfs        3.8G   48K  3.8G   1% /dev
tmpfs           3.8G     0  3.8G   0% /dev/shm
overlay          99G  1.6G   97G   2% /var/lib/docker/overlay2/928add444a00ca6db967e431cf3518ec5e5154698ab61aa481c8cc3bb9c57374/merged
shm              64M     0   64M   0% /var/lib/docker/containers/4e81470b6a7276ae640556c6eec6a22d382f43aee0501d11f1b6e6c3fd3a7a8a/shm
```

**Comment by jahkeup** [comment]
@sgendler-stem I wasn't able to reproduce this by running with the ami provided (I think you meant `ami-5e414e24`,  `amzn-ami-2017.09.h-amazon-ecs-optimized`) on an m5.large. The ECS Optimized AMI is tuned to account for the disk changes on the m5 platform. However I see that you are using `overlay`  in the `docker info` output above, which suggests that docker is being reconfigured. Without any changes, the `ecs` and `docker` services are configured to start on boot - if docker is reconfigured, it would have to be restarted. This would cause the `ecs` service to stop as result of docker stopping as it runs as a container itself.

This behavior is similar to a known side effect of docker restarting (there's a [related Github issue in the `ecs-init` repo](https://github.com/aws/amazon-ecs-init/issues/135) that details the problem). For now if your user data is modifying the storage parameters for docker and restarting it, it must also start the `ecs` service.

**Comment by sgendler-stem** [comment]
I suspect my problem was caused by the fact that I was trying to start an ECS task from the user_data (via cloud-config) before ECS was getting started, and my script for doing so was sitting in an infinite loop while waiting for ECS metadata to be available.  As a result, cloud-config wasn't finishing, which was keeping ECS service from being started (I'm guessing).  At any rate, explicitly starting ECS before calling the script or removing the script entirely was sufficient to make it work again.

**Comment by jahkeup** [comment]
I'm glad to hear the Agent was able to start. I'm to close this for now; if you have additional questions or feedback regarding this issue, feel free to add that here and reopen it for further exploration.
