### ISSUE TITLE
logging: include version and commit hash in agent logs

### ISSUE THREAD

**Issue by adnxn** [aws/amazon-ecs-agent#1258]
We should `seelog.Info(...)` the agent version and commit hash in the agent logs during startup. I'm thinking somewhere around where we dump the "Loaded config" at `seelog.Debug` level [here](https://github.com/aws/amazon-ecs-agent/blob/c051f10b219cac94c14cc533c050902bce354219/agent/app/agent.go#L131) .

**Comment by aaithal** [comment]
We've released a new [version of the ECS agent](https://github.com/aws/amazon-ecs-agent/releases/tag/v1.17.3), which should fix this issue. Closing this for now.
