### ISSUE TITLE
Add support in task definitions for more dockerConfig options

### ISSUE THREAD

**Issue by Munchery-ReeseLevine** [aws/amazon-ecs-agent#127]
We'd like to be able to set more options when running a task definition. Specifically, on the command line our command is `docker run -it <image> <cmd>`, and it would be awesome to set the same options when calling in to the remote API. It looks like the dockerGo client already supports these options, but the ecs-agent does not allow them to be configured.

**Comment by cyrus-one** [comment]
+1 would love a fix for this. thanks!

**Comment by shinshinwu** [comment]
+1 as well have had similar issue!

**Comment by DrakeW** [comment]
+1 same issue, definitely need this feature!

**Comment by leethomas** [comment]
+1 It'd be great to have this.

**Comment by euank** [comment]
I'd like to hear what use cases you have here and what options you're missing to help us better understand the feature request and prioritize things appropriately.

Thanks,
Euan

**Comment by Munchery-ReeseLevine** [comment]
On my end, I'm trying to run some tests on docker containers, which include running a browser within the container. Specifically, the -i (openStdin) and -t (tty) flags allow the container to run the executables I need and keep stdin open so I can ssh into it and run the actual test commands. Right now, the current hack I'm using is to hard code the options as true and run a modified ecs-agent on the instance. Of course, there are still bugs in the CI service we use so I can't say that this fixes all my problems 100%, but so far it looks promising.

**Comment by manishrajkarnikar** [comment]
+1
Another use case: be able to alter /etc/hosts. Docker allows it by using --add-host. There is no way to do that in ECS right now.

**Comment by oli-g** [comment]
+1
We would like to set the `log-driver` and `hostname` options in the task definitions.

**Comment by therealjessesanford** [comment]
Please add this. There is no way to use fuse drivers within docker containers without the security risk of running them with --privileged. Hence we cannot mount s3 as a mount point using s3 fuse.

**Comment by michaelgruber** [comment]
+1 Need support for `--env-file` flag.

We have variables we need to keep out of our task definitions. Currently our best option seems to be editing `/etc/syconfig/` with user data. Something like:

```bash
#!/bin/bash
yum install -y aws-cli
aws s3 cp s3://my-bucket/myenvlist /etc/myenvlist
echo 'OPTIONS="--env-file=/etc/myenvlist"' > /etc/sysconfig/docker
```

Even if that works it means having a separate cluster for each task needing an `env-file` or one `env-file` containing variables for all tasks in a cluster. An `env_file` task definition option would solve this for us. Ideally it would allow an s3 endpoint:

```json
"containerDefinitions":[
  {
    "env_file":[
      { "bucket":"my-bucket", "key":"myenvlist" }
    ]
  }
]
```

Elastic Beanstalk lets you do [something similar](http://docs.aws.amazon.com/elasticbeanstalk/latest/dg/create_deploy_docker_image.html#docker-singlecontainer-dockerrun-privaterepo) in the ` Dockerrun.aws.json` for docker private repository configuration:

```json
"Authentication":{
  "Bucket":"my-bucket",
  "Key":"mydockercfg"
},
```

**Comment by jessecollier** [comment]
I've added logging driver support via ENV vars, check out my comment here:
https://github.com/aws/amazon-ecs-agent/issues/123#issuecomment-144505824

Might be possible to add support for other things until Amazon gets it into UI.

**Comment by mweather** [comment]
I'd love to be able to use the `--volume-driver` flag, and the new `docker volume create` functionality.

**Comment by lukaswelte** [comment]
Volumes are indeed the biggest missing thing in ECS right now.
EFS would solve this issue but is just not ready and thus supporting docker volumes and the pluggable drivers would fill this gap.

**Comment by euank** [comment]
Since this issue was opened, we've got closer to parity with the set of Docker config options.
I think it makes more sense to track remaining gaps individually, such as with #236 (volume drivers).

Additional issues for any more specific instances of this are welcome.
Best,
Euan

**Comment by wallnerryan** [comment]
@mweather see https://github.com/aws/amazon-ecs-agent/issues/236 as ```euank``` mentioned
