### ISSUE TITLE
Flaky unit test: TestLoadImageTimeoutError

### ISSUE THREAD

**Issue by sharanyad** [aws/amazon-ecs-agent#1282]
### Description
The test misses a mock docker client call and is flaky due to this.

### Expected Behavior
test passes

### Observed Behavior
test fails

### Supporting Log Snippets
```
--- FAIL: TestLoadImageTimeoutError (0.00s)

	<autogenerated>:1: missing call(s) to *mock_dockeriface.MockClient.LoadImage(is anything)

	<autogenerated>:1: aborting test due to missing call(s)
 
```

**Comment by aaithal** [comment]
should be fixed with #1312
