### ISSUE TITLE
UI ECS Error

### ISSUE THREAD

**Issue by Alonreznik** [aws/amazon-ecs-agent#1283]
Hi!
I know it's not your responsibilities, but again, the UI team has some bugs which prevent us to create new task definition in the UI, and the UI team doesn't respond!

When I try to create a new revision of my task definition, I get the following error:
Unable to create a revision of Task Definition

In the console I get Bad Request for that call:
https://us-east-2.console.aws.amazon.com/ecs/proxy/taskDefinitions/register?region=us-east-2

and there are more than 1000 (!!!) errors!

Please fix

Thanks

Alon

**Comment by richardpen** [comment]
@Alonreznik Thanks for bringing this to us, I have let the UI team know about this issue, will let you know when there is an update.

**Comment by Alonreznik** [comment]
Hi @richardpen 
Thanks for your answer.
Hope it all be resolved soon.

**Comment by Alonreznik** [comment]
Hi.
Attached

![image](https://user-images.githubusercontent.com/8024926/37149298-30d72aea-22d6-11e8-999c-de35ea5d1a27.png)

![image](https://user-images.githubusercontent.com/8024926/37149746-d531d332-22d7-11e8-8eb7-56d7a6a990c3.png)


Just made a new revision from my current one, which is already running on prod.
![image](https://user-images.githubusercontent.com/8024926/37149370-60b776b6-22d6-11e8-8095-4c201f68cacc.png)

Then, Changed the image in the container definition to be with the new version.

The json is (I've changed the configurations of items that may discover our paths or configs):

`{
    "executionRoleArn": null,
    "containerDefinitions": [
        {
            "dnsSearchDomains": null,
            "logConfiguration": {
                "logDriver": "syslog"
            },
            "entryPoint": null,
            "portMappings": [],
            "command": [
                "python",
                "/path/to/python"
            ],
            "linuxParameters": {
                "capabilities": null,
                "sharedMemorySize": null,
                "tmpfs": null,
                "devices": null,
                "initProcessEnabled": true
            },
            "cpu": 64,
            "environment": [
                {
                    "name": "CONFIG_BUCKET",
                    "value": "bucket"
                },
                {
                    "name": "ENV_SETTINGS_PATH",
                    "value": "/path/to/settings"
                },
                {
                    "name": "ENVIRONMENT",
                    "value": "dev"
                },
                {
                    "name": "QUEUE_NAME",
                    "value": "queue-name"
                },
                {
                    "name": "REGION",
                    "value": "region"
                },
                {
                    "name": "RUN_AS_SERVICE",
                    "value": "1"
                }
            ],
            "ulimits": null,
            "dnsServers": null,
            "mountPoints": [
                {
                    "readOnly": false,
                    "containerPath": "/path/of/mount",
                    "sourceVolume": "EFS"
                }
            ],
            "workingDirectory": "/home",
            "dockerSecurityOptions": null,
            "memory": 300,
            "memoryReservation": 75,
            "volumesFrom": null,
            "image": "012922587834.dkr.ecr.us-east-2.amazonaws.com/rivery/riveryback:6.4.5",
            "disableNetworking": null,
            "healthCheck": null,
            "essential": true,
            "links": null,
            "hostname": null,
            "extraHosts": null,
            "user": "root",
            "readonlyRootFilesystem": null,
            "dockerLabels": null,
            "privileged": true,
            "name": "riveryback-feeder"
        }
    ],
    "memory": null,
    "taskRoleArn": "task role arn",
    "family": "riveryback-feeder-service-new",
    "requiresCompatibilities": null,
    "networkMode": "bridge",
    "cpu": null,
    "volumes": [
        {
            "name": "EFS",
            "host": {
                "sourcePath": "/path/of/mount"
            }
        }
    ],
    "placementConstraints": []
}`

**Comment by Alonreznik** [comment]
Hi there.
Are there any updates?

Thanks
Alon

**Comment by Tushar-Tilwani** [comment]
Hey Alon,
We working on the issue. Meanwhile to get your revision working remove the two properties `sharedMemorySize` and `tmpfs` from the `linuxParameters` object and then try to save the task definition revision. (use Configure via Json)

So

``` 
"linuxParameters": {
                "capabilities": null,
                "sharedMemorySize": null,
                "tmpfs": null,
                "devices": null,
                "initProcessEnabled": true
            }
```

Should be

```
"linuxParameters": {
                "capabilities": null,
                "devices": null,
                "initProcessEnabled": true
            }
```

Let me know if this doesn't fix it or if there any more questions.

**Comment by Alonreznik** [comment]
Hi @Tushar-Tilwani .
Thanks for your fix. It looks it's all working now.

Alon

**Comment by bkielbasa** [comment]
Hello,

Today, I had the same problem
<img width="664" alt="image" src="https://user-images.githubusercontent.com/1235620/129352355-9aee7d72-c086-4e86-9298-304602df3ea9.png">

What I did is get the old revision, change **nothing**, and click Create button. The `linuxParameters` is a `null`.
