### ISSUE TITLE
Retry EC2 metadata reads

### ISSUE THREAD

**Issue by euank** [aws/amazon-ecs-agent#129]
I've observed the EC2 metadata service reads failing at various times. The [ruby SDK](https://github.com/aws/aws-sdk-ruby/blob/fa195fdd27799ce8dd3b3b146e677836fecd2fce/aws-sdk-core/lib/aws-sdk-core/instance_profile_credentials.rb#L42) has retries with backoff when reading credentials from it, and it would make sense to use those counts / timings as inspiration probably, as well as take it as a sign that this is a good thing to do.

**Comment by samuelkarp** [comment]
Closing as [v1.3.1](https://github.com/aws/amazon-ecs-agent/releases/tag/v1.3.1) has been released.
