### ISSUE TITLE
Disk space issue on ECS instances

### ISSUE THREAD

**Issue by dulimitta** [aws/amazon-ecs-agent#1299]
### Supporting Log Snippets

Hi,

My ECS instances are getting out of space very fast. One instance with 8 containers says it has a lot of space, whereas the other instance with same no of containers says no space. I identified that the instance which will be running for a day or 2 is getting filled. I have very minimal application logs.
Is there a way I can get more root volume? Is there a way to handle this scenario better? Please suggest.

**Comment by sharanyad** [comment]
@dulimitta To understand the issue, we may need more information such as the following:
- Does the application container consume a lot of disk space?
- What are the error messages about running out of space? 
- Are you using the ECS optimized AMI? 
- output of `docker info | grep "Data Space"` and `df -h`

**Comment by dulimitta** [comment]
Thanks, @sharanyad for your quick reply.

- No, applications are very small micro-services, with the lightweight java images. We don't have too much logging as well.
- There are no errors as such. But when I try to run services from AWS console, the server is not allowing the ECS to launch instances. Then I verified in ECS instance.
- Yes, I am using ECS optimized AMI. ami-ba722dc0

``
sudo docker info | grep "Data Space"
 Data Space Used: 3.786GB
 Data Space Total: 23.33GB
 Data Space Available: 19.54GB

``

``
df -h
Filesystem      Size  Used Avail Use% Mounted on
/dev/nvme0n1p1  7.8G  7.8G     0 100% /
devtmpfs         16G  120K   16G   1% /dev
tmpfs            16G     0   16G   0% /dev/shm


``

**Comment by sharanyad** [comment]
@dulimitta Thanks for the information! From `docker info` and `df -h` outputs, it looks like Docker might not be the reason for disk space being full. Could you please check which specific directory in root is consuming the most space?

**Comment by dulimitta** [comment]
We just started this server a day ago. Not using it for any other operations except running the ECS containers. Do you have any suggestion to check on that?

**Comment by dulimitta** [comment]
```

[root@ip-172-31-2-82 ~]# du -h / | grep '[0-9\.]\+G'
7.1G    /var/lib/docker/containers/76e632eb6f24494c3ac5938c4d281350ae0c567728c0c22128dfa5dc389f0e7e
7.1G    /var/lib/docker/containers
9.2G    /var/lib/docker/devicemapper/mnt
9.2G    /var/lib/docker/devicemapper
17G     /var/lib/docker
17G     /var/lib
17G     /var
du: cannot access ‘/proc/2534/task/2543/fdinfo/12’: No such file or directory
du: cannot access ‘/proc/13192/task/13192/fd/4’: No such file or directory
du: cannot access ‘/proc/13192/task/13192/fdinfo/4’: No such file or directory
du: cannot access ‘/proc/13192/fd/3’: No such file or directory
du: cannot access ‘/proc/13192/fdinfo/3’: No such file or directory
4.0K    /usr/share/locale/zh_CN.GB2312/LC_MESSAGES
8.0K    /usr/share/locale/zh_CN.GB2312
17G     /


```

**Comment by dulimitta** [comment]
@sharanyad  we figured out the service which is causing the issue, your suggestions helped us to narrow down the analysis. thank you.

**Comment by sharanyad** [comment]
@dulimitta Glad you could figure it out! I am closing this issue for now, please feel free to reopen if you need anything more.

**Comment by brycedrennan** [comment]
@dulimitta @sharanyad Which service was it? What was the issue? Running into the same problem.

**Comment by dulimitta** [comment]
@brycecarman We have micro-services running on EC2 instances. One service was using a lot of disk space for writing logs.

**Comment by brycedrennan** [comment]
Yeah turned out to be the same thing except the service was the ecs-agent itself. go figure.

**Comment by rchekaluk** [comment]
@brycedrennan Did you come up with any resolution or remediation to `amazon-ecs-agent` consuming disk?

**Comment by brycedrennan** [comment]
@rchekaluk No. I just spun up new  instances and deleted the old ones.

**Comment by dulimitta** [comment]
In my case, it was not ecs-agent issue. One of the services was trying something recursive and dumping a lot of log. The story ended happily after correct the code.

**Comment by ricxsar** [comment]
Hi all. I have experience the same issues where my ecs instance is full. The instance has one wordpress docker image running. After one day the instance is full. Upon investigation, the `/var/lib/docker/` consumes all the storage. See below screenshots:

![full_storage](https://user-images.githubusercontent.com/8968902/59892215-c1971a80-940a-11e9-9d11-0d725fb1091c.png)
![docker_storage](https://user-images.githubusercontent.com/8968902/59892219-c65bce80-940a-11e9-882a-65853c917116.png)
![docker_lib_too_large](https://user-images.githubusercontent.com/8968902/59892230-cd82dc80-940a-11e9-90cc-3358688442ba.png)
![docker_version](https://user-images.githubusercontent.com/8968902/59892448-b2649c80-940b-11e9-8998-bea2a3de3d30.png)

I also inspected the logs of the docker but it is normal.
Please investigate it further. Thanks
