### ISSUE TITLE
Unable to reinstall AWS PV Driver Version 7.2.0 on AWS EC2 Win 2012

### ISSUE THREAD

**Issue by gnanasekar6914** [aws/amazon-ecs-agent#1315]
I have been using a Windows Server 2012R2 (i-18f5c730) which became unreachable after boot.
As this was a know issue with Windows Server 2012R2 AMI versions before Sept 2014. Amazon Support was able to provide instructions via case 260838031 on how to recover connectivity to the instance.

Part of the instructions given to prevent it from occurring again was to 

1) Uninstall the AWS PV Driver Version 7.2.0 via "Programs and Features.”

2) Reboot the machine when prompted by the uninstaller.

3) Download and install the [AWS Certified](https://mindmajix.com/aws-certified-training) PV Driver Installer from: https://s3.amazonaws.com/ec2-windows-drivers/AWS+PV+7.2.0/MicrosoftSigned/Installer/AWSPVDriverPackager.exe 

However at step 3 the downloaded installer is unable to install and shows the error log as attached.

Any suggestions on how to troubleshoot this further?

The support case does not seem to accept any replies 

Thanks for the help in advance

**Comment by aaithal** [comment]
Hi @gnanasekar6914, this doesn't look like an issue with the ECS agent or Docker on windows. Can you please follow up with AWS support on this? 

Thanks,
Anirudh
