### ISSUE TITLE
-e none

### ISSUE THREAD

**Issue by FernandoMiguel** [aws/amazon-ecs-agent#1318]
### Summary
command includes `-e none` which is deprecated

### Description
I tried to push to ECR and got the following error:
`denied: Your Authorization Token has expired. Please run 'aws ecr get-login' to fetch a new one.`

So I run `$ aws ecr get-login`

It returned : 
`docker login -u AWS -p <AUTH-REDACTED> -e none https://<ACCOUNTID>.dkr.ecr.eu-west-1.amazonaws.com`

When you run the output of that, you get: 
`unknown shorthand flag: 'e' in -e`

The correct command is:
`aws ecr get-login --no-include-email --region`

### Expected Behavior
for the output to be 
`aws ecr get-login --no-include-email --region`

### Observed Behavior
command includes `-e none` which is deprecated

**Comment by samuelkarp** [comment]
Hi @FernandoMiguel!  This repository is for tracking issues with the ECS agent, not for issues with the AWS CLI or issues with ECR.  I'm going to close this, but you're welcome to file an issue against the [AWS CLI](https://github.com/aws/aws-cli/issues/new) or post on the [AWS Forums](https://forums.aws.amazon.com/forum.jspa?forumID=187).

**Comment by FernandoMiguel** [comment]
thanks @samuelkarp 
this has been filed with the internal team , since it was deem to be a server side issue.
thaks
