### ISSUE TITLE
Question: Has anyone used Jenkins to launch multiple jobs in containers with AWS ECS on the same instance? 

### ISSUE THREAD

**Issue by leethomas** [aws/amazon-ecs-agent#134]
I'm running into an issue where the first job runs instantly, but the second job always waits for 2 minutes before starting with a "Pending - Waiting for more executors" message.

**Comment by euank** [comment]
AWS has a [blog post](https://blogs.aws.amazon.com/application-management/post/Tx32RHFZHXY6ME1/Set-up-a-build-pipeline-with-Jenkins-and-Amazon-ECS) describing a build pipeline with Jenkins / ECS which might be relevant.
You also might be able to get more input from other users on the [AWS Forum](https://forums.aws.amazon.com/forum.jspa?forumID=187).

Best,
Euan
