### ISSUE TITLE
CloudFormation creating new EC2 instance by change of Access token to private registry

### ISSUE THREAD

**Issue by saideekshith** [aws/amazon-ecs-agent#1343]
Hello,
I'm using cloud formation to build ECS infrastructure in AWS. we are using Gitlab-CI as our Continuous Integration tool. As a part of access to our private registry we are generating new token for every deploy,but I'm facing issue like the whole EC2 instance is being replaced every time change in Access token. Is there any way I can fix the issue.

**Comment by adnxn** [comment]
@saideekshith, this issue does not seem directly related to the ECS agent and I suggest reaching out to [AWS support](https://aws.amazon.com/premiumsupport/) or asking on the [AWS forums](https://forums.aws.amazon.com/index.jspa).
