### ISSUE TITLE
unit test failure: TestStartContainerTimeout

### ISSUE THREAD

**Issue by sharanyad** [aws/amazon-ecs-agent#1352]
### Summary
[`TestStartContainerTimeout`](https://github.com/aws/amazon-ecs-agent/blob/bbd87e2274b319b47987991427406e06b84192df/agent/dockerclient/dockerapi/docker_client_test.go#L436) fails intermittently

### Expected Behavior
test passes

### Observed Behavior
test fails intermittently

### Environment Details
[Appveyor](https://ci.appveyor.com/project/AmazonECS/amazon-ecs-agent/build/2117)

### Supporting Log Snippets
```
--- FAIL: TestStartContainerTimeout (0.00s)
	<autogenerated>:1: missing call(s) to *mock_dockeriface.MockClient.StartContainerWithContext(is equal to id, is nil, is anything) c:/gopath/src/github.com/aws/amazon-ecs-agent/agent/dockerclient/dockerapi/docker_client_test.go:442
	<autogenerated>:1: aborting test due to missing call(s)
```

**Comment by haikuoliu** [comment]
This is fixed in #1348
