### ISSUE TITLE
update service task family:task revision Invalid revision number

### ISSUE THREAD

**Issue by diegoraulqc** [aws/amazon-ecs-agent#1354]
### Summary

When using a bash script to automate the task definition registration and update service, the update service fails.

### Description

I'm using the following script to automate the register-task-definition and update-service for a deployment in ecs. 

bash script:
```
#external variables
CLUSTNAME=$CLUSTERNAME
CNAME=$ECSNAME
REPO=$REPOSITORYNAME

TASK_FAMILY="$CNAME-task"
CONTAINER_NAME="$CNAME-container"
SERVICE_NAME="$CNAME-service"

aws ecs register-task-definition --cli-input-json file://taskdef-file.json
# Update the service with the new task definition and desired count
# Get the task revision number
TASK_REVISION=`aws ecs describe-task-definition --task-definition $TASK_FAMILY | egrep "revision" | tr "/" " " | awk '{print $2}' | sed 's/"$//'`
aws ecs update-service --cluster $CLUSTNAME --service $SERVICE_NAME --task-definition $TASK_FAMILY:$TASK_REVISION
```
I'm having a error when executing the script but if i run line by line nothing fails. I think that is a race problem between the task definition registration and the update-service that doesn't notice the change inmediately.
The script was working fine a few months ago. (Last use was in February).

### Expected Behavior
The script should work as it has work for the last months updating the service with the task definition.

### Observed Behavior
the script fails with the following message: 
An error occurred (InvalidParameterException) when calling the UpdateService operation: Invalid revision number

### Environment Details

aws-cli/1.15.2  Python/3.5.2 Linux/4.13.0-38-generic
Docker version 17.05.0-ce, build 89658be

Thanks for the help.

**Comment by adnxn** [comment]
@diegoraulqc, thanks for bringing this to our attention. It's a useful datapoint for us that may suggest increased latency for register-task-definition calls. 

As a path forward for now, we suggest adding retry logic to your script.

**Comment by adnxn** [comment]
@diegoraulqc, closing this since we have not heard back. Feel free to update this if you have any new information. Thanks.

**Comment by sidharth15** [comment]
I'm experiencing the same issue. The RegisterTaskDefinition api in java is throwing the following exception. There shouldn't be anything wrong with the parameter values as the same method is used for registering multiple task definitions with similar values, but the exception gets thrown just for this single call.

Stack trace :
Exception starting task: pcmsshop - ClientException: Invalid TaskDefinition revision. (Service: AmazonECS; Status Code: 400; Error Code: ClientException; Request ID: 7687b587-62a2-11e9-8c60-cf4b1be9fa01)\ncom.amazonaws.services.ecs.model.ClientException: Invalid TaskDefinition revision. (Service: AmazonECS; Status Code: 400; Error Code: ClientException; Request ID: 7687b587-62a2-11e9-8c60-cf4b1be9fa01)\n\tat com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleErrorResponse(AmazonHttpClient.java:1639)\n\tat com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeOneRequest(AmazonHttpClient.java:1304)\n\tat com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeHelper(AmazonHttpClient.java:1056)\n\tat com.amazonaws.http.AmazonHttpClient$RequestExecutor.doExecute(AmazonHttpClient.java:743)\n\tat com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeWithTimer(AmazonHttpClient.java:717)\n\tat com.amazonaws.http.AmazonHttpClient$RequestExecutor.execute(AmazonHttpClient.java:699)\n\tat com.amazonaws.http.AmazonHttpClient$RequestExecutor.access$500(AmazonHttpClient.java:667)\n\tat com.amazonaws.http.AmazonHttpClient$RequestExecutionBuilderImpl.execute(AmazonHttpClient.java:649)\n\tat com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:513)\n\tat com.amazonaws.services.ecs.AmazonECSClient.doInvoke(AmazonECSClient.java:2620)\n\tat com.amazonaws.services.ecs.AmazonECSClient.invoke(AmazonECSClient.java:2596)\n\tat com.amazonaws.services.ecs.AmazonECSClient.executeRegisterTaskDefinition(AmazonECSClient.java:1877)\n\tat com.amazonaws.services.ecs.AmazonECSClient.registerTaskDefinition(AmazonECSClient.java:1852)\n\tat
