### ISSUE TITLE
ECS agent fails to start tasks with non blocking fluentd logging driver options if fluentd is unavailable

### ISSUE THREAD

**Issue by tomelliff** [aws/amazon-ecs-agent#1379]
### Summary
ECS agent fails to start tasks with non blocking fluentd logging driver options if fluentd is unavailable

### Description
As mentioned in https://github.com/aws/amazon-ecs-agent/issues/1088#issuecomment-387358548 I've just noticed that ECS is also failing to start tasks that are using non blocking log opts when using the fluentd logging driver if the fluentd endpoint is unavailable. Did you want me to raise a new issue for this or is this going to be related here and thus needs fixing before this issue can be considered fixed?

I have the following logging driver config:
```
...
      "logConfiguration": {
        "logDriver": "fluentd",
        "options": {
          "mode": "non-blocking",
          "max-buffer-size": "4m",
          "tag": "unparsed.frontend.staging"
        }
      },
...
```
but the task refuses to start when fluentd isn't running yet:
```
2018-05-08T10:18:52Z [INFO] Task engine [arn:aws:ecs:eu-west-1:340242599322:task/21ec9330-8aef-4c2d-9695-f5be6c9ae415]: starting container: frontend
2018-05-08T10:18:52Z [INFO] Task engine [arn:aws:ecs:eu-west-1:340242599322:task/21ec9330-8aef-4c2d-9695-f5be6c9ae415]: error transitioning container [frontend] to [RUNNING]: API error (500): failed to initialize logging driver: dial tcp 127.0.0.1:24224: getsockopt: connection refused

2018-05-08T10:18:52Z [WARN] Managed task [arn:aws:ecs:eu-west-1:340242599322:task/21ec9330-8aef-4c2d-9695-f5be6c9ae415]: Error starting/provisioning container[frontend]; marking its desired status as STOPPED: API error (500): failed to initialize logging driver: dial tcp 127.0.0.1:24224: getsockopt: connection refused
```
For reference I'm running fluentd as a ghetto daemon set by scheduling 1000 tasks across the cluster and they have host networking binding to 24224 which means only a single task can run on an ECS container instance at a time. Unfortunately ECS throttles rescheduling these tasks so it can take a while before the log shipper task is scheduled on to new nodes and so new tasks take a while to be schedulable on the container instance.

### Expected Behavior
Task starts without needing the fluentd socket to be open and just buffers log output until max-buffer-size is reached at which point logs are discarded.

### Observed Behavior
ECS agent fails to start the task

### Environment Details
ECS Agent version: 1.17.3
Docker version: 18.03.0-ce

**Comment by tomelliff** [comment]
Hmmmm, I might be wrong on how this actually works because the following fails locally when not running Fluentd:
```
docker run -it --rm --log-driver fluentd --log-opt fluentd-addrescalhost:24224 --log-opt mode=non-blocking --log-opt max-buffer-size=4m alpine:latest
```
but this works:
```
docker run -it --rm --log-driver fluentd --log-opt fluentd-addrescalhost:24224 --log-opt fluentd-async-connect=true alpine:latest
```
So I guess it might be a question for upstream in Moby instead?

**Comment by mseiwald** [comment]
Setting `fluentd-async-connect=true` seems to only delay the problem until Docker's internal log buffer is full. After that the containers are still stopped...

**Comment by yunhee-l** [comment]
@mseiwald could you please open a new issue with description of your issue?
