### ISSUE TITLE
Automated cleanup of non-ECS docker images

### ISSUE THREAD

**Issue by mwarkentin** [aws/amazon-ecs-agent#1380]
### Summary

We're using Convox as a PaaS on top of ECS. During application deploys, the instance that is running the convox API container performs a `docker pull` on the image to be deployed in order to analyze it. This means that those instances in our cluster were using up docker disk space at a much higher rate than our others. We expected the ECS automated cleanup to be handling these images, but it appears that the cleanup process only cleans up images created through ECS itself.

It would be nice if ECS had the option to clean up all unused Docker images regardless of where they come from. Our alternatives right now are `docker system prune --all` on a cron, doing the same via AWS Systems Manager, or monitoring and manually cleaning up as needed.

### Description

> @samuelkarp [9:43 PM]
> @mwarkentin, thats correct; the agent tracks what it pulls and only deletes those. The reason it does that is to avoid impacting containers that might be run on the instance outside ECS and to avoid deleting something that was intentionally pulled there to cache.

Because this could impact use cases like the above, this functionality could be optional and be enabled by a new config option.

Initial functionality from https://github.com/aws/amazon-ecs-agent/issues/118.

**Comment by adnxn** [comment]
closing issue, merged to `dev` with https://github.com/aws/amazon-ecs-agent/pull/1752
