### ISSUE TITLE
Incorrect "Memory Available" for ECS instance

### ISSUE THREAD

**Issue by jehadassaf** [aws/amazon-ecs-agent#1381]
Hello,

I have two t2.medium instances in the cluster, on each of them `free -m` reports around 2800 available while under the ECS Cluster in the console it's showing 1520. 
Also, launching an instance of a task with memoryReservation of 128 and memory 256 takes up double the reported available memory.

Am I doing something wrong or is this a bug?

This is on a ECS-optimized AMI (latest) - ami-aff65ad2.

**Comment by richardpen** [comment]
The `free -m` will show the actual available memory that is not used by any process, which includes the memory that was allocated to container but not used by the container. While the ECS console only shows the memory that was not allocated to container even it's not actually used. So for example:
* Instance has 4G memory
* One container was allocated with 2G memory(by memory/memoryReservation)
* The process inside the container only use 1G memory
Then the `free -m` will show `4G - 1G - memory_used_by_other_process = 3G - memory_used_by_other_process`, but the ECS console will show `4G - 2G = 2G` 

ECS provides the realtime resource usage in the cluster level, as documented [here](https://docs.aws.amazon.com/AmazonECS/latest/developerguide/cloudwatch-metrics.html). Please let me know if you have any further question.

**Comment by jehadassaf** [comment]
That is correct, however that is not happening in this case.

As you can see below, I have 2 instances with 4G each. I am running 6 tasks (3 per instance) and each task has memory limit 256M and memoryReservation 128M.

For available memory calculation, ECS uses the memoryReservation from what I understand.
So, on each instance I should have available 4G - (128M x 3). Even if it would take the hard memory limit of 256M into account, I should still see available of 3G or more. But I am shown 1520M available. 

So in essence: 

- Instance has 4G memory
- Three tasks are running with allocated 128MB reservation and 256M hard limit each
- Memory available shows 1520M

```
[ec2-user@ip-172-XX-XXX-XXX ~]$ free -m
             total       used       free     shared    buffers     cached
Mem:          3952       1242       2710         11        107        695
-/+ buffers/cache:        439       3513
Swap:            0          0          0
```

```
[ec2-user@ip-172-XX-XXX-XXX ~]$ docker stats
CONTAINER ID        NAME                                                   CPU %               MEM USAGE / LIMIT   MEM % 
c8de2af9867b        ecs-app_web-50-web-b28cc89dd2cd9ba0a501                0.02%               59.98MiB / 256MiB   23.43%
cf4d26d9ddbc        ecs-app_web-50-internalecspause-9490cef684c7e3871300   0.00%               628KiB / 3.86GiB    0.02% 
5605acdc1e99        ecs-app_worker-30-worker-8893e8e1babdb6e1e101          0.02%               75.93MiB / 256MiB   29.66%
f84f36462940        ecs-app_worker-30-worker-82d78085b3fea29d0a00          0.02%               75.89MiB / 256MiB   29.64%
620a2cef70b6        ecs-agent                                              0.24%               10.4MiB / 3.86GiB   0.26% 
```

![cluster-memory-available](https://user-images.githubusercontent.com/1734495/39854272-ae5d4802-542f-11e8-8d16-aee5352cc24e.png)
![instance-details](https://user-images.githubusercontent.com/1734495/39854287-be651856-542f-11e8-8fbc-f5a80520e5f0.png)
![cluster-status](https://user-images.githubusercontent.com/1734495/39854288-c24337c8-542f-11e8-930a-278e294005bd.png)
![cluster-reservation](https://user-images.githubusercontent.com/1734495/39854290-c622c2c8-542f-11e8-80b1-9d7ba2fdee92.png)

**Comment by richardpen** [comment]
@jehadassaf It looks like you have 4 containers on that instance, did you missed something? I also did the same setup, registered a t2.medium instance and started 3 tasks with the following task definition, which shows 3568 available memory.
```
{
"family": "memoryReservation",
    "containerDefinitions": [
    {
        "name": "busybox",
        "image": "busybox",
        "cpu": 10,
        "command":  [ "sh", "-c", "while [ true ]; do sleep 1s; date +%T; done"],
        "memory": 256,
        "memoryReservation": 128
    }
    ]
}
```
In order to help figure out the cause, can you share the following information with me: penyin (at) amazon.com
* account id
* container instance id of both
* region

Thanks,
Peng

**Comment by jehadassaf** [comment]
@richardpen yes, there are actually 5 containers running, but only 3 are my tasks, the other two are the ecs-agent and some other container which I'm not sure what it's for, but it seems ecs-related as well (ecs-app_web-50-**internalecspause**-9490cef684c7e3871300). It's weird and I never saw it until you pointed it out. As you can see, the console shows 3 running tasks...

I'll send you the details via email - thanks for looking into this.

**Comment by jehadassaf** [comment]
With Peng's help I was able to identify the issue: I had the `sharedMemorySize` in `linuxParameters` section of the task definition set to 1024. Setting this is basically the same as adding that on top of the `memoryReservation`. So in my case I had the following task definition, which yielded a task consuming 1152M available memory

```json
{
    "taskDefinition": {
        "containerDefinitions": [
            {
                "memoryReservation": 128,
                "name": "worker",
                "linuxParameters": {
                    "sharedMemorySize": 1024
                },
                "memory": 256,
                "cpu": 0
            }
        ]
    }
}
```

Thanks for the help @richardpen !
