### ISSUE TITLE
Multiple EC2 instances experienced connection issues with ECS

### ISSUE THREAD

**Issue by ldm810** [aws/amazon-ecs-agent#1387]
### Summary

On 5/14 around 12:30 PM EST, multiple of our ECS Clusters reported 0 CPU utilization. This was because the ec2 instance could not connect to the ECS service.  Why did this happen? What monitoring can we add so that we are aware of such errors?

### Description

When we looked at the ecs-agent logs on the instances corresponding to the clusters, we saw the following error messages

`2018-05-14T17:08:32Z [ERROR] Error connecting to TCS: websocket client: unable to dial ecs-t-2.us-east-1.amazonaws.com response: : read tcp [IP ADDRESS]->[IP ADDRESS]: i/o timeout`
`2018-05-14T17:02:11Z [WARN] Error creating a websocket client: read tcp [ip address]->[ip address]: read: connection reset by peer`

### Expected Behavior
The EC2 instance should be able to connect to the ECS service

### Observed Behavior
We learned about the error because our clusters reported 0 cpu utilization 

### Environment Details
Amazon ECS Agent - v1.17.3

**Comment by ldm810** [comment]
@richardpen Thanks. This did happen in `us-east-1`.

**Comment by richardpen** [comment]
@ldm810 I'm closing this issue, feel free to open an issue if you run into a problem in ECS Agent.
