### ISSUE TITLE
Windows emptyvolume container (microsoft/nanoserver) tag should maybe be configurable?

### ISSUE THREAD

**Issue by bboerst** [aws/amazon-ecs-agent#1390]
### Summary
The emptyvolume container that is triggered in a Windows environment is being pulled from microsoft/nanoserver:latest which is currently based on a 2016 build.  This limits the ability to use the amazon-ecs-agent on other versions of Windows running as the host.

### Description
With AWS's recent release of AMIs for semi-annual builds (1709 and 1803; example: ami-b4a8d8cc in us-west-2), we would like to use these new versions as the base for our ECS cluster architecture due to the many container fixes that are included in them.

There is however an issue with using the amazon-ecs-agent with Windows versions other than 2016 because the emptyvolume container is hard-coded to pull microsoft/nanoserver:latest (https://github.com/aws/amazon-ecs-agent/blob/159ae5c3067e0a0d7387ff68af2a28bc90f3baaa/agent/engine/emptyvolume/constants_windows.go#L21).  The 'latest' tag at this point in time is synonymous with the 'sac2016' tag.  So what happens is that our container image that is based on :1803 is instantiated on our 1803 ECS cluster instance; along with that, an emptyvolume container is also instantiated, but the emptyvolume container triggers an error: "The operating system of the container does not match the operating system of the host" because the empty volume container is being pulled as 'latest'/'sac2016' and not microsoft/nanoserver:1803.
This particular behavior is documented by Microsoft here: https://docs.microsoft.com/en-us/virtualization/windowscontainers/deploy-containers/version-compatibility which basically states: 'Because Windows Server Containers and the underlying host share a single kernel, the container’s base image must match that of the host.' The only way around this limitation is to either match the container build version to the Windows host version (1803) or run the container with the --isolation=hyperv flag which I don't believe is possible.

I thought I'd submit this issue to possibly make the emptyvolume container tag for nanoserver more flexible as it would help people that want to use Windows versions other than 2016.  I'd hate to suggest yet another configurable parameter for the agent but I believe that this would give the most flexibility.  Maybe something like ECS_WINDOWS_EMPTYVOLUME_NANOSERVER_TAG ?

**Comment by haikuoliu** [comment]
Hi @bboerst,

Thanks for bringing this to our attention. We are currently working on migrating to the docker volume api, so that the empty volume will be created directly with the volume API, and the empty container is no longer required. We will let you know when this is done.

Haikuo

**Comment by tekmaven** [comment]
Could someone from AWS comment on the status of this?  We would also like to run build 1803 for our ECS cluster.  Microsoft has fixed a lot of docker issues since 2016 LTS.

**Comment by haikuoliu** [comment]
Hi @bboerst, @tekmaven,

The [Agent 1.19.0](https://github.com/aws/amazon-ecs-agent/releases/tag/v1.19.0) is released, and we have replaced empty volume with local driver docker volume in this version. I am gonna close this issue, feel free to reopen it if you have any other questions related to this issue.

**Comment by haikuoliu** [comment]
@bboerst @tekmaven,

The Agent [1.20.0](https://github.com/aws/amazon-ecs-agent/releases/tag/v1.20.0) is released, and the empty volume is replaced, so I am going to close this issue, let me know if there are other questions about this 😊
