### ISSUE TITLE
Error Pulling Packge from ECS: ProcessUtilityVMImage "The system cannot find the path specified."

### ISSUE THREAD

**Issue by mattdone01** [aws/amazon-ecs-agent#1392]
### Summary
When I pull an image from ECR I get the following output. From what i have read there is an issue with microsoft/dotnet:2.1-sdk-nanoserver-1709. The docer version needs to be 17.10

`C:\Users\Administrator>docker pull 268189374995.dkr.ecr.ap-southeast-2.amazonaws.com/ditno.mongodbwatcher:dev
dev: Pulling from ditno.mongodbwatcher
407ada6e90de: Extracting [==================================================>]  81.04MB/81.04MB
1b9ade35fece: Download complete
6de46ca30836: Download complete
3a2d64ee7afd: Download complete
96fbfe7b9171: Download complete
292f4011680f: Download complete
4d2d7923f405: Download complete
ef20e97b9dc8: Download complete
b4de3a4b43dd: Download complete
3463f7da6af2: Download complete
fb3ae81bdd0d: Download complete
failed to register layer: re-exec error: exit status 1: output: ProcessUtilityVMImage \\?\C:\ProgramData\docker\windowsfilter\351b26b948a8ff7991599d94b7541ed6aa49ca58133303498e7286584597d42e\UtilityVM: The system cannot find the path specified.`

### Description

The issue is failed to register layer: re-exec error: exit status 1: output: ProcessUtilityVMImage \\?\C:\ProgramData\docker\windowsfilter\351b26b948a8ff7991599d94b7541ed6aa49ca58133303498e7286584597d42e\UtilityVM: The system cannot find the path specified.`

### Expected Behaviour
That ECS Windows Agent would pull the image successfully

### Observed Behavior
It fails to pull the image form ECR.

### Environment Details
**docker info**
C:\Users\Administrator>docker info
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 2
Server Version: 17.06.2-ee-10
Storage Driver: windowsfilter
 Windows:
Logging Driver: json-file
Plugins:
 Volume: local
 Network: l2bridge l2tunnel nat null overlay transparent
 Log: awslogs etwlogs fluentd json-file logentries splunk syslog
Swarm: inactive
Default Isolation: process
Kernel Version: 10.0 14393 (14393.2214.amd64fre.rs1_release_1.180402-1758)
Operating System: Windows Server 2016 Datacenter
OSType: windows
Architecture: x86_64
CPUs: 2
Total Memory: 4GiB
Name: EC2AMAZ-RHSK6TE
ID: HYRW:725W:EX6L:YSQB:CN5Z:OXVV:4FTS:KXNN:2CK2:VZKY:IBJF:HLDG
Docker Root Dir: C:\ProgramData\docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

**This is my docker file.**
FROM microsoft/dotnet:2.1-aspnetcore-runtime-nanoserver-1709 AS base
WORKDIR /app

FROM microsoft/dotnet:2.1-sdk-nanoserver-1709 AS build
WORKDIR /src
COPY Ditno.MongoDbWatcher/Ditno.MongoDbWatcher.csproj Ditno.MongoDbWatcher/
RUN dotnet restore Ditno.MongoDbWatcher/Ditno.MongoDbWatcher.csproj
COPY . .
WORKDIR /src/Ditno.MongoDbWatcher
RUN dotnet build Ditno.MongoDbWatcher.csproj -c Release -o /app

FROM build AS publish
RUN dotnet publish Ditno.MongoDbWatcher.csproj -c Release -o /app

FROM base AS final
WORKDIR /app
COPY --from=publish /app .
ENTRYPOINT ["dotnet", "Ditno.MongoDbWatcher.dll"]

**Comment by aaithal** [comment]
Hi @mattdone01, I'm closing this issue for now. Please let us know if you have any follow-up questions/comments.

Thanks,
Anirudh
