### ISSUE TITLE
health check passes but container still killed by ALB

### ISSUE THREAD

**Issue by FernandoMiguel** [aws/amazon-ecs-agent#1397]
### Summary
health check is 200 but ALB still kills container

### Description
we have a flask app with an health check on `/`
it's a basic check and mostly returns 200

our app receives posts on `/divido`

sometimes, a query can make it fail, and it returns `500`
`10.10.51.108 - - [29/May/2018 13:42:00] "POST /divido HTTP/1.1" 500 -`

once this happens the ALB will kill the container , even though the `/` HC is passing
`10.10.51.108 - - [29/May/2018 13:42:00] "GET / HTTP/1.1" 200 -`

### Expected Behavior
for the ALB validate the HC before killing the container

### Observed Behavior
ALB saw an error 500 on a different pass of the HC and killed the container

### Environment Details
agent 1.17

**Comment by FernandoMiguel** [comment]
from the Events log
`service staging-ms-divido (instance i-xxx) (port 32826) is unhealthy in target-group ecs-staging-ms-divido due to (reason Request timed out)`

**Comment by haikuoliu** [comment]
Hi @FernandoMiguel,

Container health check is for ECS scheduler, it's not designed for ALB. You can see details [here](https://aws.amazon.com/about-aws/whats-new/2018/03/amazon-ecs-supports-container-health-checks-and-task-health-mana/).

For your case, you may want to configure your ALB's health check, see instructions [here](https://docs.aws.amazon.com/elasticloadbalancing/latest/classic/elb-healthchecks.html).

Thanks,
Haikuo

**Comment by aaithal** [comment]
Hi @FernandoMiguel , I'm closing this issue for now. Please let us know if you have any follow-up questions/comments.

Thanks,
Anirudh
