### ISSUE TITLE
flaky unit test: TestTaskWithSteadyStateResourcesProvisioned

### ISSUE THREAD

**Issue by adnxn** [aws/amazon-ecs-agent#1405]
`TestTaskWithSteadyStateResourcesProvisioned` appears to intermittently fail in CI with `panic: test timed out after 25s`.

However running it in isolation with `go test . -v -run=TestTaskWithSteadyStateResourcesProvisioned -count=10000`, does not seem to reproduce the failure.

**Comment by yunhee-l** [comment]
Fix is already merged.
