### ISSUE TITLE
Add support for S3 images

### ISSUE THREAD

**Issue by nahiluhmot** [aws/amazon-ecs-agent#141]
Hey there,

First of all, thanks for your work on this agent, I'm looking forward to using it in production soon! However, there is one issue preventing me from doing so. I don't use Docker registries for performance and reliability reasons, and instead host my images on S3. After looking through your code, it appears only registries are supported. Would you be open to accepting a pull request that adds support for pulling images from S3?

**Comment by samuelkarp** [comment]
Yeah, we'd definitely be open to a pull request of that nature.

**Comment by samuelkarp** [comment]
@nahiluhmot Are you still interested in contributing something of this nature?

**Comment by nahiluhmot** [comment]
@samuelkarp Sorry for the delayed response. I would definitely be interesting in contributing that. I have a branch based off an old version of the repo currently, so I'll have to rebase it off of the current `dev` branch and clean it up a bit.

**Comment by ellenthsu** [comment]
We've introduced Elastic Registry Service which solves for this use case

See more here - https://aws.amazon.com/ecr/
