### ISSUE TITLE
Logs inside ECS to cloudwatch.

### ISSUE THREAD

**Issue by rachuta** [aws/amazon-ecs-agent#1416]
I trying to publish custom logs to cloudwatch, These custom logs are created inside the ECS under log directory. What is the way to get these logs, all the documentation shows getting the syslogs and io logs for ECS.

Any pointers will be helpful.

**Comment by JasonSwindle** [comment]
This should help, as it uses the CloudWatch Agent to ship whatever logs you want from the EC2 instance.

https://docs.aws.amazon.com/AmazonECS/latest/developerguide/using_cloudwatch_logs.html

**Comment by richardpen** [comment]
@rachuta As we haven't heard from you for a long time, I'm assuming the suggestion above has solved your problem. Close this issue now, feel free to reopen if you need further assistance.
