### ISSUE TITLE
ECS Service Discovery registering to Route53 before service is healthy

### ISSUE THREAD

**Issue by SaikiranDaripelli** [aws/amazon-ecs-agent#1421]
### Summary
ECS Service Discovery registering to Route53 before service is healthy

### Description
ECS Service Discovery registering to Route53 before service is healthy, Route53 is returning SRV records in dig as soon as task starts and is not waiting for initial health success.

Below is my setup:
I am trying with ECS service discovery in bridge mode with SRV record type, and i configured HealthCheck Custom config FailureThreshold as 1, and health check grace period as 900. 
My service takes around 180 secs to become healthy(Java based service), while target group is correctly waiting for my service to become healthy before routing traffic,  Route53 is retuning SRV records before service turns healthy. This behaviour is rendering ECS service discovery useless.

### Expected Behavior
Route53 should return SRV records only after service turns healthy.

### Observed Behavior
Route53 should is returning service SRV records before service turns healthy.

**Comment by hridyeshpant** [comment]
are you using container health?  https://aws.amazon.com/about-aws/whats-new/2018/03/amazon-ecs-supports-container-health-checks-and-task-health-mana/

**Comment by SaikiranDaripelli** [comment]
@hridyeshpant I am using ALB/Target group healthchecks to did not configure Docker healthchecks. Does service discovery depends on Docker healthchecks and not on Target group healthcheck?

**Comment by bzcnsh** [comment]
@SaikiranDaripelli 

ALB probably does not know what to check until ECS puts SRV record into route 53.

**Comment by bitbrain** [comment]
According to [the official documentation](https://docs.aws.amazon.com/AmazonECS/latest/developerguide/service-discovery.html):
> You can configure service discovery for an ECS service that is behind a load balancer, but service discovery traffic is always routed to the task and not the load balancer.
Which implies to me that ALB does not integrate in any way with Route 53/Service Discovery. Make sure you configure your health [within the task definition](https://docs.aws.amazon.com/AmazonECS/latest/developerguide/task_definition_parameters.html#container_definition_healthcheck).

You can provide a `startPeriod` within your task definition (disabled by default). This probably is what you are looking for.

**Comment by hridyeshpant** [comment]
@SaikiranDaripelli i can conform and had discussion with AWS team. They are working on this fix but no ETA.

**Comment by bitbrain** [comment]
@hridyeshpant Okay, this definitely sounds like a bug to me. Good to hear AWS is aware of this.

**Comment by schmohlio** [comment]
bumping this as well. This is a non-starter for a lot of teams looking to use ECS with service discovery. A huge sell of rolling updates + health checks is to validate the service before bringing it online to avoid downtime.

**Comment by ellenthsu** [comment]
Thank you all for providing feedback on this issue. We've deployed a fix for this where we register instances as unhealthy in ECS Service Discovery during the SD provisioning state.

**Comment by spaszek** [comment]
@ellenthsu As random as it might it sound, is there a way to force the agent into registering unhealthy instances?

**Comment by schmohlio** [comment]
@spaszek why not just set a fake health check on the instance? there are examples on AWS, but something like `echo "hello world"` should suffice.

**Comment by avivek** [comment]
We try to fake a health check using some kind of a setup container, which will say it is healthy in expectation of a dependent container, starting later, to find the DNS record.
But what we found is that the DNS record is only created after all the dependent containers in a task start. This makes it impossible for a container to run expecting a DNS record.

**Comment by schmohlio** [comment]
It seems that this bug has resurfaced. We are seeing DNS records show up for hosts in `RUNNING` state before they reach `HEALTHY`.  

@ellenthsu we've filed support tickets for this but haven't make much traction. Seems like a serious bug. Is there something that changed in how the underlying Cloud Map APIs interact with ECS?

**Comment by schmohlio** [comment]
More specifically, we see that previous container versions are stopped before the new container version is HEALTHY (they are stopped when new containers are RUNNING).

**Comment by guoqings** [comment]
@schmohlio we have identified a situation where some slow start tasks could be treated healthy prematurely. We have responded in the opened ticket and will deploy an improvement this month to mitigate that issue.

**Comment by schmohlio** [comment]
thank you @guoqings for the update! Will look out for the deployment.

**Comment by pocockn** [comment]
> @spaszek why not just set a fake health check on the instance? there are examples on AWS, but something like `echo "hello world"` should suffice.

I'm stuck with this issue. My service tries to create a listener at 'serviceName:portNumber' but fails because the record doesn't get added to route53 because the health check fails. Could you point me to one of these examples of a fake health check?

**Comment by donaltuohy** [comment]
Hi I'm still seeing this issue. We have a slow starting task and it's been registered in service discovery before it's ready which is resulting downtime on deployments. Is anyone else still seeing this behaviour?

**Comment by pmcdonald-metropolis** [comment]
Still hitting this bug in 2024. Tasks are getting registered to service discovery before they are healthy which is causing down time.
