### ISSUE TITLE
High CPU Gathering Stats for Lots of Containers

### ISSUE THREAD

**Issue by jcbowman** [aws/amazon-ecs-agent#1422]
When there are a lot of containers on an ECS Host the docker-containerd process will consistently consume up to 100% CPU on the Host. This is rooted in the fact that ECS is constantly streaming container stats from Docker for each container.

We have a proposed enhancement in a forked repo that allows users to opt into polling for stats instead of streaming. Any thoughts before opening a PR? PR in our forked repo: https://github.com/inmar/amazon-ecs-agent/pull/1

**Specifics:**
Our team runs about 150-180 containers per host, most individually pretty minor on resource usage. We observed the CPU for those hosts was often nearly pegged, regardless of instance size/type. The culprit was determined to be docker-containerd: using the latest ECS-Optimized AMI the **docker-containerd process consumes around 100% CPU continuously.**

**Troubleshooting Steps:**
- Setting `ECS_DISABLE_METRICS` flag to false in amazon-ecs-agent, the CPU consumption by docker-containerd instantly dropped to nearly 0, and our next highest consumer CPU process was one of our containers, at a fraction of a percent.
- Upgrading to Docker 18, with metrics collection enabled, improved docker-containerd from 100% CPU down to about 25% CPU. A major improvement, but still consuming much more CPU than we would like simply to collect basic metrics.
- We tested a forked version of amazon-ecs-agent to poll for docker metrics instead of leaving streams open. With a polling interval of 15s, under Docker 18, the docker-containerd CPU **dropped from 25% to about 2.5 - 5%.**

Below are some CloudWatch snapshots of our different tests.

CPU Usage With Latest ECS Optimized AMI (Docker 17):
![original ami](https://user-images.githubusercontent.com/3932125/41823238-ba7a32f8-77ca-11e8-870c-8cf8bf83e44b.PNG)

Moving ECS Cluster from Docker 18 to Docker 18 + Stat Polling:
_About halfway through the day on 6/22 we deployed the new AMI that has Docker stat polling enabled. The Y-axis is a little misleading because of the peaks, but it is dropping from about 20-25% CPU to 10-12% CPU._ 
![docker 18 to docker 18 with stat polling](https://user-images.githubusercontent.com/3932125/41823249-e36057ce-77ca-11e8-8dfa-151e376be6f2.PNG)

**Comment by yunhee-l** [comment]
Hi,
Thank you very much for taking time to investigate and implement this. 
On a quick glance we have some questions, for example, whether losing granularity of 1 second aggregate metrics would be ok with other users or not. It could be made configurable, but in that case, would DefaultPollingMetricsWaitDuration=1 second result in the same CPU pattern as before?

ECS Agent team will do a bit more investigation on our side for this issue and update.

Thank you.
Yunhee Lee

**Comment by jcbowman** [comment]
Hey,

Thanks for looking into it.

Just to add some data points to the testing the team does on your side - we tested with different polling intervals and saw roughly the same CPU usage for 1 second polling intervals as leaving the Stream open. Here were our results for our servers.

| Sleep Interval (seconds)  | docker-containerd CPU |
| ------------- | ------------- |
| 30 | 0.5 - 3%  |
| 15 | 2.5 - 5%  |
| 7 | 3.5 - 8% |
| 3 | 8.0 - 16% |
| 1 | 16  - 25% |

**Comment by jcbowman** [comment]
@boynux We set the `ECS_DISABLE_METRICS` flag to true and saw the CPU immediately drop for the `docker-containerd` process. I would give that a try.

https://docs.aws.amazon.com/AmazonECS/latest/developerguide/ecs-agent-config.html

The downside is that if you do that then you will lose your CloudWatch Metrics.

**Comment by yunhee-l** [comment]
Hi @jcbowman 
Sorry for the delay in getting back to you. We have done some investigation internally and seems like metric aggregation > 1sec isn't going to cause problems, although there is a max limit of 1min. 
We would need the polling duration to be configurable, but you can go ahead and open a pull request and we can discuss these over the PR. 

Thank you.

**Comment by boynux** [comment]
@jcbowman what kind of metrics do we lose if we disable them? We use CPU utilization metric on  container level to do auto scaling. Is that going to be affected?

**Comment by jcbowman** [comment]
@boynux Good point - it might be affected. I believe it disables the CPU and Memory metrics for the containers.

**Comment by yunhee-l** [comment]
PR has been pushed, this will feature be included in our next release. Keeping this open to track.

**Comment by adnxn** [comment]
closing issue since #1646 released with https://github.com/aws/amazon-ecs-agent/releases/tag/v1.24.0
