### ISSUE TITLE
Miss attribute from container instance

### ISSUE THREAD

**Issue by liangnuaa** [aws/amazon-ecs-agent#1429]
### Summary

I am trying to run a task, but got a error: container-instance is missing an attribute required by your task.

### Description

The task needs these two attributes:
![image](https://user-images.githubusercontent.com/18162490/42233510-a6c19386-7ea6-11e8-929b-75edfaf9a0fe.png)
But the container instance missed the attribute "name": "com.amazonaws.ecs.capability.task-iam-role" attribute.

**Comment by liangnuaa** [comment]
Is there a way to add this attribute to this container instance or do I need to update ecs agent?

**Comment by sharanyad** [comment]
@liangnuaa Is the environment variable `ECS_ENABLE_TASK_IAM_ROLE` set to true in the container instance? Which agent and Docker versions are you using? You can also find more documentation about enabling Task IAM roles [here](https://docs.aws.amazon.com/AmazonECS/latest/developerguide/task-iam-roles.html#enable_task_iam_roles).

**Comment by liangnuaa** [comment]
Thank you, Sharanyad! The ECS_ENABLE_TASK_IAM_ROLE is not set to true, that's the reason.
