### ISSUE TITLE
Improve error message for failed pulls due to full disk

### ISSUE THREAD

**Issue by samuelkarp** [aws/amazon-ecs-agent#1434]
### Summary
When we pull images, the pull can fail for a variety of reasons.  One reason is due to lack of disk space either in the temporary directory where layers are pulled before being uncompressed or in the layer store itself.  We don't surface these errors very well.

See https://github.com/aws/amazon-ecs-agent/issues/1425

### Expected Behavior
An easy-to-understand error message is surfaced as the container's "reason" field through a DescribeTasks API call.

### Observed Behavior
This message is logged to the agent log file:

```
DockerGoClient: failed to pull image 123456789012.dkr.ecr.ap-southeast-2.amazonaws.com/my-image: write /var/lib/docker/tmp/GetImageBlob721002426: no space left on device
```

**Comment by adnxn** [comment]
> An easy-to-understand error message is surfaced as the container's "reason" field through a DescribeTasks API call.

Any suggestions for an easy-to-understand error message? And as always, feel free to open a PR 😛

**Comment by suneyz** [comment]
We are now providing "no space left" through "status reason" field. 

Sample output:
````
Status reason: CannotPullContainerError: failed to register layer: Error processing tar file(exit status 1): write /tmp/my_large_file: no space left on device
````
