### ISSUE TITLE
containers in the same task definitions are not linking

### ISSUE THREAD

**Issue by thishandp7** [aws/amazon-ecs-agent#1436]
### Description
I have a Client-side and a Server side application. Both running in separate containers. Server-side provides APIs to the client-side. The client runs at port 8080 and the server runs at 8081. Everything works perfectly in docker-compose(I'm using docker compose 3). But, when I put everything in ECS the client-side couldn't locate and fetch the data from the server container.

I am defining both of the containers in one task definition and linking my server to the client. When I ssh into my EC2 instance, I can see both the Client and the Server containers are running at 0.0.0.0:8080 and 0.0.0.0:8081 respectively. Also when I inspect the docker network inside the EC2 instance I can see both of these containers are listed in it. As far as I know, this should work without any issues.

I even tried awsvpc network mode. still no use.

Here is the task definition
```
"CartTaskDefinition": {
   "Type": "AWS::ECS::TaskDefinition",
   "Properties": {
      "ContainerDefinitions": [
       {
          "Name": "cs-cart",
          "Image": "thishandp7/cs-cart",
          "Memory": 400,
          "PortMappings":[
            {
               "ContainerPort": "8080",
               "HostPort": "8080"
            }
          ],
          "Links": [
              "cs-server"
           ]
       },
       {
          "Name": "cs-server",
          "Image": "thishandp7/cs-server",
          "Memory": 450,
          "PortMappings":[
           {
              "ContainerPort": "8081",
              "HostPort": "8081"
           }
          ],
       }
     ]
   }
}
```

### Expected Behavior
Containers in the same task defintion should be able to communicate once they're linked

### Observed Behavior
Containers in the same task defintion are not communicating even though they're linked

### Environment Details
I'm using an autoscaling group with an application load balancer(also tried with classic load balancer)

EC2 instance security Group Ingress rules:
```
"SecurityGroupIngress" : [
 {
   "IpProtocol" : "tcp",
   "FromPort" : 8080,
   "ToPort" : 8080,
   "SourceSecurityGroupId" : { "Ref": "ElbSecurityGroup" }
 },
 {
   "IpProtocol" : "tcp",
   "FromPort" : 8081,
   "ToPort" : 8081,
   "SourceSecurityGroupId" : { "Ref": "ElbSecurityGroup" }
 },
 {
   "IpProtocol" : "tcp",
   "FromPort" : 22,
   "ToPort" : 22,
   "CidrIp" : "0.0.0.0/0"
 }
],

```
PS: I don't want to use Fargate

**Comment by FernandoMiguel** [comment]
how is one container addressing the other?
via the instance IP ? via a load balancer?

**Comment by richardpen** [comment]
@thishandp7 Can you tell us what's the address used in your client when it tries to talk to the server?  The client should be able to use `cs-server:8081` to talk to the server, see the documentation [here](https://docs.docker.com/network/links/#environment-variables).

**Comment by richardpen** [comment]
@thishandp7 I'm closing this issue for now as we haven't heard from you for a while. Feel free to reopen if you have any question in the future.

**Comment by utkarsh-cc** [comment]
@thishandp7 were you able to solve this issue? i am also facing the same problem
