### ISSUE TITLE
Docker timeout error messages suggest ECS_CONTAINER_[START/STOP]_TIMEOUT are ignored

### ISSUE THREAD

**Issue by mclaugsf** [aws/amazon-ecs-agent#1440]
### Summary
I am submitting several AWS Batch jobs and seeing errors like this:

<pre>
CannotInspectContainerError: Could not transition to inspecting; timed out after waiting 30s
</pre>

and this: 

<pre>
DockerTimeoutError: Could not transition to created; timed out after waiting 4m0s
</pre>

However, here is my ECS config file:

<pre>
[ec2-user@ip-10-0-0-244 ~]$ cat /etc/ecs/ecs.config
<b>ECS_CONTAINER_STOP_TIMEOUT=5m</b>
<b>ECS_CONTAINER_START_TIMEOUT=10m</b>
ECS_CLUSTER=Nextflow-1TB-Timeout_Batch_5fcdae08-6c0f-378f-992a-cdd267cbd40a
ECS_DISABLE_IMAGE_CLEANUP=false
ECS_ENGINE_TASK_CLEANUP_WAIT_DURATION=2m
ECS_IMAGE_CLEANUP_INTERVAL=10m
ECS_IMAGE_MINIMUM_CLEANUP_AGE=10m
ECS_NUM_IMAGES_DELETE_PER_CYCLE=5
ECS_RESERVED_MEMORY=32
ECS_AVAILABLE_LOGGING_DRIVERS=["json-file","awslogs"]
</pre>

Did the task really wait 30s/4m or did the values of 5m/10m get picked up?

### Description

There are several _aws cli s3 cp_ processes running pulling somewhat large files (i.e. 5Gb) into running containers.  This makes Docker unresponsive which causes these errors for the task, so I am experimenting with changing the timeout values.

### Expected Behavior

I would like the jobs to run without erroring out, but what I'm really reporting here is that the error messages do not seem to be observing the environment variables in /etc/ecs/ecs.config

### Observed Behavior

The error messages are reporting default values for _ECS_CONTAINER_STOP_TIMEOUT_ and _ECS_CONTAINER_START_TIMEOUT_ instead of the values set in /etc/ecs/ecs.config

### Environment Details

docker info:
<pre>
[ec2-user@ip-10-0-0-244 ~]$ docker info
Containers: 1
 Running: 1
 Paused: 0
 Stopped: 0
Images: 2
Server Version: 17.12.1-ce
Storage Driver: devicemapper
 Pool Name: docker-docker--pool
 Pool Blocksize: 524.3kB
 Base Device Size: 1.074TB
 Backing Filesystem: ext4
 Udev Sync Supported: true
 Data Space Used: 676.9MB
 Data Space Total: 1.061TB
 Data Space Available: 1.06TB
 Metadata Space Used: 790.5kB
 Metadata Space Total: 1.074GB
 Metadata Space Available: 1.073GB
 Thin Pool Minimum Free Space: 106.1GB
 Deferred Removal Enabled: true
 Deferred Deletion Enabled: true
 Deferred Deleted Device Count: 0
 Library Version: 1.02.135-RHEL7 (2016-11-16)
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 9b55aab90508bd389d7654c4baf173a981477d55
runc version: 9f9c96235cc97674e935002fc3d78361b696a69e
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.14.33-51.37.amzn1.x86_64
Operating System: Amazon Linux AMI 2018.03
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 7.792GiB
Name: ip-10-0-0-244
ID: 5G6X:VXC3:5OXV:KUF6:XS2G:F4TQ:K3ME:ZAPM:RVGR:TV6J:2Q5N:6MS3
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
</pre>

sudo lvs:
<pre>
[ec2-user@ip-10-0-0-244 ~]$ sudo lvs
  LV          VG     Attr       LSize   Pool Origin Data%  Meta%  Move Log Cpy%Sync Convert
  docker-pool docker twi-aot--- 988.00g             0.06   0.07
</pre>

curl http://localhost:51678/v1/metadata:
<pre>
[ec2-user@ip-10-0-0-244 ~]$ curl http://localhost:51678/v1/metadata
{"Cluster":"Nextflow-1TB-Timeout_Batch_5fcdae08-6c0f-378f-992a-cdd267cbd40a","ContainerInstanceArn":"arn:aws:ecs:us-east-1:317432334668:container-instance/a2d55cb1-be2d-4da5-a6a8-a1a3ba8d95cc","Version":"Amazon ECS Agent - v1.18.0 (c0defea9)"}
</pre>

df -h:
<pre>
[ec2-user@ip-10-0-0-244 ~]$ df -h
Filesystem      Size  Used Avail Use% Mounted on
devtmpfs        3.9G   84K  3.9G   1% /dev
tmpfs           3.9G     0  3.9G   0% /dev/shm
/dev/xvda1      7.8G  1.4G  6.4G  18% /
</pre>

### Supporting Log Snippets
logs available on request.

**Comment by sharanyad** [comment]
@mclaugsf There is no way to configure the inspect and create container timeouts in ECS agent today. 
`ECS_CONTAINER_START_TIMEOUT` is the timeout for starting a container and `ECS_CONTAINER_STOP_TIMEOUT` is the time to wait after a container has stopped before force killing it. More documentation [here](https://docs.aws.amazon.com/AmazonECS/latest/developerguide/ecs-agent-config.html). 
It is possible that you might be running out of EBS burst credits. If you can share me the task ARNs for which the Docker timeouts are seen, I shall be able to check up on that. You can also share them directly via email - sharanyd at amazon.com 

Sharanya

**Comment by mclaugsf** [comment]
@sharanyad thank you for letting me know that the ECS_CONTAINER_START_TIMEOUT and ECS_CONTAINER_STOP_TIMEOUT variables will not change the timeouts the way I anticipated.

I just emailed you the task ARNs for some of the tasks that failed with Docker timeout errors.

**Comment by sharanyad** [comment]
As mentioned, it looks like the volume IO utilization is close to 100% in those instances which is causing the Docker operations to timeout. I would suggest using a larger/different volume type such as Provisioned IOPS SSD for this workload. Different volume types are documented [here](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/EBSVolumeTypes.html).

**Comment by sharanyad** [comment]
I'm closing this issue for now. Please feel free to reopen if the suggestions do not work. Thanks!

**Comment by m4ce** [comment]
@sharanyad, I am also bumping into this issue and I am unable to figure out why it's happening. We are using AWS Batch with a mixture of on-demand and spot instances. Our workloads don't really do anything expensive on EBS, it should be very little IO. Is there anything else I should be looking into? I also unable to verify the burst credits as the instances get automatically destroyed by Batch.

Note that I also set `ECS_DISABLE_IMAGE_CLEANUP` to `true` as we bumped into the following issue at times: "CannotInspectContainerError: could not transition to inspecting, timed out after waiting 30s". The docker image that we run rarely gets refreshed intra-day so we don't really need to be aggressive there in cleaning up.

**Comment by rajataggarwal91** [comment]
> @sharanyad, I am also bumping into this issue and I am unable to figure out why it's happening. We are using AWS Batch with a mixture of on-demand and spot instances. Our workloads don't really do anything expensive on EBS, it should be very little IO. Is there anything else I should be looking into? I also unable to verify the burst credits as the instances get automatically destroyed by Batch.
> 
> Note that I also set `ECS_DISABLE_IMAGE_CLEANUP` to `true` as we bumped into the following issue at times: "CannotInspectContainerError: could not transition to inspecting, timed out after waiting 30s". The docker image that we run rarely gets refreshed intra-day so we don't really need to be aggressive there in cleaning up.

Were you able to fix your issue?

**Comment by microbioticajon** [comment]
@sharanyad, I am also bumping into this issue in AWS Batch. For me it occurs on lightweight tasks with heavy write against a 200GB gp2 (600iops) volume. There are about 8 or so tasks running parallel on a freshly provisioned node writing 8GBs(ish) of files to the volume. Usually one of the tasks fails with "Could not transition to inspecting; timed out after waiting 30s".

I am monitoring the burst capacity of the volume of the node and not noticing any significant drop in burst capacity. Moving to provisioned IOPs is relatively expensive compared to asking the Agent to wait a little longer when inspecting during periodic spikes in activity.

Opening up the default timeouts to configuration would be quite helpful in this regard.

**Comment by Kushal2511** [comment]
> @sharanyad, I am also bumping into this issue in AWS Batch. For me it occurs on lightweight tasks with heavy write against a 200GB gp2 (600iops) volume. There are about 8 or so tasks running parallel on a freshly provisioned node writing 8GBs(ish) of files to the volume. Usually one of the tasks fails with "Could not transition to inspecting; timed out after waiting 30s".
> 
> I am monitoring the burst capacity of the volume of the node and not noticing any significant drop in burst capacity. Moving to provisioned IOPs is relatively expensive compared to asking the Agent to wait a little longer when inspecting during periodic spikes in activity.
> 
> Opening up the default timeouts to configuration would be quite helpful in this regard.

I was facing the same issue where my job was getting successfully executed however AWS Batch showed it as failed due to inspect time out error. When I browsed ecs agent release note page, I found out that this in agent version 1.54.1 AWS batch has started getting exit code from docker events in case docker inspect fails. This results in task getting successful even though docker inspect didn't provide response in 30 seconds. 

https://github.com/aws/amazon-ecs-agent/releases

**Comment by yihengli** [comment]
I have seen similar issues as described in this post (https://forums.aws.amazon.com/thread.jspa?threadID=298314) in AWS Batch.

We have some jobs that need to download some zip files from s3 to EBS and unpack them for the application to consume. The IO will peak around that time and cause "CannotInspectContainerError" for itself or other jobs on the same machine.  (though they still have burst credit). 

Currently my workaround is to
1) retry if such error happens (as this IO peak is only happened once or twice per job)
2) limit the instance type to only 2cores or 4 cores machines when submitting jobs. The it will have less chance to have multiple job IO peak at the same time.

However, it would be great if we have some control in terms of the inspectTimeout.

**Comment by azvoleff** [comment]
I am seeing the same error on AWS Batch when running workloads with heavy i/o to from S3. Is there any chance of seeing a configurable timeout for inspection?
