### ISSUE TITLE
Dynamic hostname using go template

### ISSUE THREAD

**Issue by atul-chegg** [aws/amazon-ecs-agent#1469]
Is it possible to set task hostname using template? Ref: https://docs.docker.com/engine/swarm/services/#create-services-using-templates

**Comment by adnxn** [comment]
@atul-chegg, to clarify and correct me if im wrong: Are you trying to use templates feature to run containers on ECS? It seems to be tied to `docker service create`. 

Or did you mean to ask this question in to the [amazon-ecs-cli](https://github.com/aws/amazon-ecs-cli) project?

**Comment by atul-chegg** [comment]
@adnxn Yes, I was looking if similar feature exist in ECS.

**Comment by adnxn** [comment]
@atul-chegg: We don't provide support for templated parameters today.

So i have a better understanding of what you are trying to do - What is your use case exactly?

**Comment by adnxn** [comment]
closing issue for now, feel free to update if you have more information.
