### ISSUE TITLE
[scripts/publishing-common.sh] $DRYRUN variable validation

### ISSUE THREAD

**Issue by zmrow** [aws/amazon-ecs-agent#1472]
### Summary

The [dryval()](https://github.com/aws/amazon-ecs-agent/blob/master/scripts/publishing-common.sh#L32) function in ```scripts/publishing-common.sh``` doesn't currently do any validation on the value of the ```${DRYRUN}``` variable. 

### Description

Because no validation is done on the ```${DRYRUN}``` variable and all "truthy" values are accepted, it is possible that actions will be actually be taken when a dry-run is intended.  We should check against an explicit "true" or "false" and do the right thing, or throw an error otherwise.

For example:

```
$ DRYRUN=

$ if $DRYRUN; then echo "YAY"; fi
YAY
```
or more maliciously:

```
$ DRYRUN=yes

$ if $DRYRUN; then echo "YAY"; fi
y
y
y
y
y
y
...
and it will never end
```

### Expected Behavior
Internally, if the variable ```$DRYRUN``` is set to ```true```, then the calling script will simply echo the command it would run, instead of running the command.

If ```$DRYRUN``` is set to ```false```, then commands will be echoed AND run.

If ```$DRYRUN``` is anything else, echo an error message and stop.

### Observed Behavior
I have not observed this behavior in any script currently using ```publishing-common.sh```, however we should protect ourselves from this in the future.

**Comment by yunhee-l** [comment]
https://github.com/aws/amazon-ecs-agent/pull/1502 fixes this, push pending dev branch unfreeze after AMI release.

**Comment by yunhee-l** [comment]
PR #1502 has been pushed, resolving this.
