### ISSUE TITLE
any doccument on copying docker images between 2 aws accounts?

### ISSUE THREAD

**Issue by rohit756** [aws/amazon-ecs-agent#1484]
I have two aws accounts 
1 for dev 
2 for prod

currently Im using 
aws ecr grt-login
docker pull to local from dev
docker push tp prod from local

I am looking for a script which does this, so that I dont have to pull images to my local

Thanks

**Comment by rohit756** [comment]
@aws-dash

**Comment by rohit756** [comment]
@amazon-ecs-bot

**Comment by rohit756** [comment]
@richardpen

**Comment by adnxn** [comment]
> any doccument on copying docker images between 2 aws accounts?

Maybe you're looking for something like this? This one is for [grant access to a secondary account](https://aws.amazon.com/premiumsupport/knowledge-center/secondary-account-access-ecr/) and here's a more detailed one on [configuring ECR repository policies](https://docs.aws.amazon.com/AmazonECR/latest/userguide/RepositoryPolicyExamples.html).

ECR doesnt have a copy image API, you would have to write your own script to actually copy images between different repos.
