### ISSUE TITLE
/v1/tasks response contract changed

### ISSUE THREAD

**Issue by jcbowman** [aws/amazon-ecs-agent#1486]
### Summary

The response contract for the /v1/tasks endpoint appears to have recently changed. In 1.18.0 the contract followed this schema:

`Tasks[].Containers[].DockerId`

In 1.19.0 the following schema is being returned:

`Tasks[].Containers[].DockerID`

### Expected Behavior
I would expect the same contract to be returned between minor versions of the agent. I would also expect the endpoints to be versioned if the contract is going to change.

*Documentation for this endpoint:*
https://docs.aws.amazon.com/AmazonECS/latest/developerguide/ecs-agent-introspection.html

**Comment by jcbowman** [comment]
It looks like this might have been fixed with https://github.com/aws/amazon-ecs-agent/pull/1473

Is there a plan to push the fix to 1.19?

Thanks!

**Comment by adnxn** [comment]
> I would expect the same contract to be returned between minor versions of the agent. I would also expect the endpoints to be versioned if the contract is going to change.

As you should! We're doing a `1.19.1` release with the fix. Hold tight! Thank you.

**Comment by adnxn** [comment]
/ping @jcbowman, release with the fix is out https://github.com/aws/amazon-ecs-agent/releases/tag/v1.19.1

**Comment by grahamlyons** [comment]
I've been affected by this too. The Datadog agent fails to export any metrics for Docker containers when using 1.19 of the ECS agent: https://github.com/DataDog/dd-agent/blob/46961dddbe700f6f0cf8f66b59ed7215de9f5f47/utils/orchestrator/ecsutil.py#L84

I'm downgrading to 1.18 for now. What's the ETA on release?

**Comment by adnxn** [comment]
@jcbowman, @grahamlyons: The `1.19.1` ECS agent has been [released](https://github.com/aws/amazon-ecs-agent/releases/tag/v1.19.1) along with the [amzn-ami-2018.03.c-amazon-ecs-optimized](https://docs.aws.amazon.com/AmazonECS/latest/developerguide/ecs-optimized_AMI.html) AMI.

**Comment by grahamlyons** [comment]
Wunderbar. Thank you for that.

**Comment by adnxn** [comment]
closing issue since `1.19.1` has been released with the fix for this breaking contract.

**Comment by jcbowman** [comment]
Thanks! It works as expected for us.
