### ISSUE TITLE
Expose Volumes via Agent Introspection API

### ISSUE THREAD

**Issue by CpuID** [aws/amazon-ecs-agent#1516]
### Summary

It would be extremely convenient if the ECS Agent could expose the attached Volumes to each ECS Task via the `/v1/tasks` API endpoint, as `.Tasks[].Volumes` (jq syntax).

### Description

Right now you can get `Containers`, each with `DockerId`, but not the volumes created as part of the ECS task definition. These are created using random IDs, with no labels which makes it sub-optimal to trace these back to the task definition.

You can do it in a roundabout way by interrogating the container for mountpoints and based on the matching path decipher which volume ID is involved. Would be much easier to short circuit this via the agent API if possible though and just get the Volume ID natively as `.Tasks[].Volumes.DockerId`

**Comment by yunhee-l** [comment]
Agent 1.20.2 release completed, closing.
