### ISSUE TITLE
T3 instances and max ENIs

### ISSUE THREAD

**Issue by IngmarStein** [aws/amazon-ecs-agent#1542]
According to https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/using-eni.html, a t3.large instance should have a maximum of 3 ENIs and can therefore host 2 tasks using the awsvpc networking mode, just like a t2.large instance.
When we upgraded our cluster from t2 to t3, we found that each instance can now only host 1 task using the awsvpc networking mode. Beyond that, the agent is unable to place tasks with a reference to the "RESOURCE:ENI" error.

Does ecs-agent need to be updated for the new instance types?

**Comment by adnxn** [comment]
> Does ecs-agent need to be updated for the new instance types?

That shouldn't be the case. Though - which version of the agent are you on right now? I'm going to try to repro this, we expect t3s to also host 2 awsvpc tasks.

**Comment by IngmarStein** [comment]
I'm running 1.20.1.

**Comment by IngmarStein** [comment]
Support has answered my question:

> Please note, with the T3 instance type, ENI association is divided to the container instance, EBS volume and tasks. With that being said ,with a t3.large having a maximum of 3 ENI, one ENI would be for the instance, the ECS secondary volume and one for that single task that actually got hosted. The difference between the t2 and t3 is that t2 does not require a dedicated ENI association for an EBS volume, this is the reason why you are able to host 2 tasks on it. […] With that being said,  I would recommend to continuing using the t2 instance type as this allows the running of 2 tasks.

**Comment by FernandoMiguel** [comment]
@IngmarStein thanks for sharing.
this is crap !!

**Comment by IngmarStein** [comment]
Reopening because of this revised answer:

> I have investigated further into your issue. 
> 
> I was able to replicate the error that you have experienced, by spinning up my own cluster and changing to t3.larges. As this is not expected behaviour, as per the documentation, I have reached out to the service team to provide a clearer understanding of what is going on, hopefully in an attempt to get a better solution for you.
> 
> The support for t3 instances in ECS is not official yet. Although the t3 is available as General Available in EC2, there definitely appears to be a few bugs to iron out before full support and General Availablilty in ECS is available. This can be seen when trying to create a new ECS Cluster through the AWS console. I am sure that it will become available officially soon.
> 
> With regards to my previous statement regarding the ENI and EBS volumes, I believe I may have misinterpreted some of our documentation, related to EBS volumes and ENI[1]. The limitation is actually related to maximum number of EBS volumes, and the concept of attachments. As a result, I may have been incorrect in my explanation. At this stage, I think the safest bet is to await feedback from the Service Team in this regard.

**Comment by IngmarStein** [comment]
Apparently, this is resolved now:
> My apologies for the delayed response, I was actively working with the service team and I can see now the issue has been resolved and you can now run two tasks on a t3.large container instance.

**Comment by tabrezfcoos-maker** [comment]
hi, you can use c5,c6, or m5 version of instance with vpc trunking enabled so that we can aattch max eni upto 10 eni's per instances with awsvpc-mode in ecs with ec2 type.
