### ISSUE TITLE
Remove non-running containers based on disk usage stats

### ISSUE THREAD

**Issue by dgouldin** [aws/amazon-ecs-agent#1550]
### Summary
It would be great if instead of configuring a static `ECS_ENGINE_TASK_CLEANUP_WAIT_DURATION` for removing stopped containers, a cleanup could be triggered based on disk usage.

### Description
When starting and stopping containers rapidly, it's easy to exhaust the available space on `/dev/xvdcz`. While it's possible to configure ecs-agent to more quickly remove stopped containers, a static configuration is sub-optimal when there's significant variance in the rate of stopped containers.

As I understand it, the intent is to avoid running out of disk space while keeping stopped containers available for inspection as long as possible. But IMO both goals would be better served by removing old containers based on a target max % disk usage.

Thanks for your consideration!

**Comment by samuelkarp** [comment]
@dgouldin Thanks for sending this feature request!  We're tracking that in https://github.com/aws/amazon-ecs-agent/issues/70, so I'm going to close this one since it's a duplicate.
