### ISSUE TITLE
Unable to pull private image from dockerhub 

### ISSUE THREAD

**Issue by Hemanshu1belani** [aws/amazon-ecs-agent#1552]
### Summary
After updating ecs-agent from 1.14.5 to 1.20.1 I'm getting below error in log file while pulling image from private repo in dockerhub

**requested access to the resource is denied unauthorized: authentication required**

### Logs

time="2018-08-30T03:58:28.192238484Z" level=debug msg="Calling POST /v1.21/images/create?fromImage=name%2Frepo%3Atag"
time="2018-08-30T03:58:28.192411565Z" level=debug msg="Trying to pull name/repo from https://registry-1.docker.io v2"
time="2018-08-30T03:58:30.989044052Z" level=error msg="Not continuing with pull after error: errors:\ndenied: requested access to the resource is denied\nunauthorized: authentication required\n"
time="2018-08-30T03:58:30.989088211Z" level=info msg="Ignoring extra error returned from registry: unauthorized: authentication required"

###  ecs.config

I tried changing below config in ecs.config but issue still remains.

ECS_ENGINE_AUTH_TYPE=docker
ECS_ENGINE_AUTH_DATA={"my.registry.example.com": {"username": "myUsername","password": "myPassword"},"https://index.docker.io/v1/user": {"username": "my-dockerhub-username","password": "my-dockerhub-password","email": "my-optinallyincluded-email"}}

-- OR --

ECS_ENGINE_AUTH_TYPE=docker
ECS_ENGINE_AUTH_DATA={"https://index.docker.io/v1/":{"username":"my-dockerhub-username","password":"my-dockerhub-password","email":"email@mail.com"}}

-- OR --

ECS_ENGINE_AUTH_TYPE=dockercfg
ECS_ENGINE_AUTH_DATA={"https://index.docker.io/v1/":{"auth":"auth","email":"email@email.com"}}

### Environment
Amazon ECS Optimized - ami-cf03d2ac
Docker version : 18.03.1-ce
ecs-agent version : 1.20.1

**Comment by haikuoliu** [comment]
Hi @Hemanshu1belani 

Can you please send me the Agent log so that I can help you? You can remove all the sensitive info in the log, my email is haikuo at amazon.com.

Also, have you tried to restart the Agent after you set those variables so that Agent can load them?

Thanks,
Haikuo

**Comment by Hemanshu1belani** [comment]
Hi @haikuoliu 
I have mailed you the log file along with the output of "docker inspect container-id".
Also, I restart docker and agent every time I change ecs.config file. I even tried restarting EC2.

Thanks,
Hemanshu

**Comment by haikuoliu** [comment]
Hi @Hemanshu1belani 

I tried to reproduce your issue, but I wasn't able to get the pull access denied error, here is my step to reproduce the issue:

1. Register a private registry on hub.docker.com, push an image to it.
2. Update the Agent using `sudo yum update -y ecs-init`
3. Edit the `/etc/ecs/ecs.config`: 
```
ECS_CLUSTER=HaikuoCluster
ECS_ENGINE_AUTH_TYPE=docker
ECS_ENGINE_AUTH_DATA={"https://index.docker.io/v1/":{"username":"my_user_name","password":"my_password","email":"my_email"}}
```
4. Restart the Agent, and run a task on the instance, the Agent works as expected.

However, if I switch to the server endpoint that you sent me, I got the pull access denied error. 

I suspect that the auth data in your config file could probably be wrong, can you login using `docker login server` with the same info in your ecs config file, to make sure your auth data is correct? 

Thanks,
Haikuo

**Comment by Hemanshu1belani** [comment]
@haikuoliu docker login server works perfectly fine, but same configuration in ecs.config does not work. 
I tried again with your server endpoint, but same error.
I'll start again from scratch and try to reproduce the same.

**Comment by Hemanshu1belani** [comment]
@haikuoliu we are using AWS nodejs sdk to create Task with below containerDefinitions

`containerDefinitions: [
        {
          environment: [],
          name: NAME,
          image: IMAGE,
          cpu: CPU,
          memory: MEMORY,
          portMappings: [
          {
            containerPort: portNumber,
            hostPort: portNumber
          }
          ],
          command: [
          docker.command,
          docker.fileName,
          portNumber.toString()
          ],
          ulimits: [
            {
              name : "cpu",
              softLimit : 30,
              hardLimit : 30
            }
          ],
          essential: true
        }
      ]`

I went through [Private Registry Authentication for Tasks](https://docs.aws.amazon.com/AmazonECS/latest/developerguide/private-auth.html) but could not find a way to provide docker credentials.

I was under the assumption that aws nodejs sdk uses docker credentials from docker config file
[Private Registry Authentication for Container Instances](https://docs.aws.amazon.com/AmazonECS/latest/developerguide/private-auth-container-instances.html)

Am I missing something? Or how do I provide docker credentials for aws nodejs sdk

**Comment by haikuoliu** [comment]
@Hemanshu1belani 

There are two options for you to get access to private registry:
1. [Private registry for task](https://docs.aws.amazon.com/AmazonECS/latest/developerguide/private-auth.html): this is a new feature released recently, you need to store your credentials in secret manager and provide the secret manager arn in task definition. The nodejs sdk you are using to create task definition will not retrieve docker credentials for you automatically.
2. [Private registry for container instance](https://docs.aws.amazon.com/AmazonECS/latest/developerguide/private-auth-container-instances.html): this is the way you were using.

Are you trying to use option 1 instead of option 2? If option 2 still doesn't work for you, I'd suggest starting from scratch with a latest ECS optimized AMI and see if it works.

**Comment by Hemanshu1belani** [comment]
@haikuoliu  : It worked with latest ECS optimized AMI. Not sure why isn't working on my old ECS optimized AMI. 
Thanks :)

**Comment by haikuoliu** [comment]
@Hemanshu1belani Good to know that! I am going to close this issue, let me know if you have more questions.
