### ISSUE TITLE
Container VOLUME already with data form image gets empty when mounting

### ISSUE THREAD

**Issue by brahama** [aws/amazon-ecs-agent#1556]
### Summary

I have an image with /web with some data for the webapp.. I create one VOlume in the task definition like WEB_DATA. Once its deployed, with the mountpoint set; the path is empty.
How can i do to setup a persistent VOLUME for this case. I want to re-use this volume in case the task restarts. But the data is already in the image. SO i want that data also to be in the mounted volume. Sorry if it is not clear. Thanks!

**Comment by FernandoMiguel** [comment]
If you have a cluster of more than one host, you can't assume it will restart to the same host (depending on your allocation policy)
For persistent storage, you will have to use something LIKE AWS EFS

**Comment by FernandoMiguel** [comment]
If you have a single host (no high availability) you can create a host volume in the ecs task, but it will override the contents of the Docker volume, sadly.
I have an old ticket open with this

**Comment by FernandoMiguel** [comment]
https://github.com/aws/amazon-ecs-agent/issues/1123

**Comment by FernandoMiguel** [comment]
The workaround is to copy the data to s3 and bootstrap it to EFS

**Comment by haikuoliu** [comment]
Hi @brahama persistent volume is not supported by ECS yet, so this is a feature request, I will close it in favor of #1123, feel free to comment on that thread.

Thanks,
Haikuo
