### ISSUE TITLE
Using ECS Agent 1.20.1 and Service constantly registers a new instance which then fails health check

### ISSUE THREAD

**Issue by ldm810** [aws/amazon-ecs-agent#1564]
### Summary

I am using ECS Agent version 1.20.1 and randomly throughout the day, the service reports that it is adding an instance to the elb. 

Then, the service reports (in the same second) that an instance is unhealthy. It takes the task down on that instance and brings it back up.

When I look at my instance, I do not see any logs of healthchecks. 

### Description

I want to understand the following:
- Why is the service registering an instance (we do not have autoscaling) if the service is steady?
- Why is it that right after that an instance is unhealthy if I do not see any healthcheck logs
Sometimes during this time we see backend connection errors, but not always

### Expected Behavior
- I should see logs for the healthchecks
- The service should not randomly log that it is registering an instance because all instances are already registered to the elb

### Observed Behavior
- No healthcheck logs
- The service is adding an instance to the elb (I do not know how to check which instance) and at the same time, reports that an instance is unhealthy.

### Environment Details

Operating System: Amazon Linux AMI 2018.03
Amazon ECS Agent - v1.20.1 (02a6a9ff)

**Comment by haikuoliu** [comment]
Hi @ldm810 

To enable our dev team to better investigate this, can you please send the following information to me at: haikuo (at) amazon.com

Account ID
Region
Cluster Name
Service Name
Time range when this issue happened

Thanks,
Haikuo
