### ISSUE TITLE
Docker 500 Error if task definition does not explicitly specify command

### ISSUE THREAD

**Issue by Tomdarkness** [aws/amazon-ecs-agent#157]
If you have a docker image built from a Dockerfile with an ENTRYPOINT but in the ECS task definition you don't specify the command parameter then the ECS agent is unable to run the container:

```
[WARN] Error with docker; stopping container module="TaskEngine" task="removed, Status: (NONE->RUNNING) Containers: [container-name (NONE->RUNNING),container-name (CREATED->RUNNING),]" container=container:tag (CREATED->RUNNING)" err="API error (500): No command specified 
```

Running the actual image via `docker run <image name>` works perfectly fine. Also works fine if I copy the ENTRYPOINT from my docker file into the command parameter of my ECS task definition.

This has only started happening very recently. It actually broke my whole deployment because none of my task definitions have the command parameter set in the task definition - they all were working perfectly fine before using whatever was set as the entrypoint in the dockerfile.

**Comment by samuelkarp** [comment]
Hi @Tomdarkness,

Thanks for reporting this issue.  We have identified the problem and will update this issue with more information as it becomes available.

Sam

**Comment by samuelkarp** [comment]
Hi @Tomdarkness,

We have addressed the problem and you should no longer experience this behavior.  Please let us know if it continues.

Thanks,
Sam

**Comment by elitaylor** [comment]
@samuelkarp,

I am having this exact issue when I start an ECS task via ElasticBeanstalk. If I specify the ENTRYPOINT or CMD in the dockerrun.aws.json, the container will start but will then immediately dies. 

Does EB not support long-running tasks?

Why do I need to explicitly specify an ENTRYPOINT or CMD to run a container image that already has that specified when it was built with the Dockerfile?

This definitely could be user error or something that EB does not support, I'm just not sure!

Thank you!
