### ISSUE TITLE
Feature request for container meta data file to include ECS host instance IP address

### ISSUE THREAD

**Issue by cloudpal** [aws/amazon-ecs-agent#1575]
### Summary

Customers are using instance meta data inside of the container to get IP address of the host ECS instance. This is a security risk as enabling instance meta data allows for querying IAM credentials as well.  

### Description

Instance meta data are typically disabled due to security risk of being able to query IAM roles/credentials. To avoid using instance meta data, containers use the container specific meta data file. However, currently the ECS host IP field is not present in container metadata file. Request to include host IP address field to the container meta data file.

**Comment by adnxn** [comment]
closing issue, changes have been merged into `dev` with #1730
