### ISSUE TITLE
No swap file on AWS ECS AMIs?

### ISSUE THREAD

**Issue by alexzaytsev-newsroomly** [aws/amazon-ecs-agent#1580]
### Summary
I launched enough tasks that my RAM usage went close to 95% of physical RAM on my EC2 (c5.large) host. I noticed that if load goes up a bid, the machine goes to 100% CPU usage with at least 50% in system time and some 30-40% in kswapd process

### Description
Below are some commands and their output that show that there are no swap files
```
[ec2-user@ip-10-1-0-251 ~]$ cat /etc/*-release
NAME="Amazon Linux AMI"
VERSION="2018.03"
ID="amzn"
ID_LIKE="rhel fedora"
VERSION_ID="2018.03"
PRETTY_NAME="Amazon Linux AMI 2018.03"
ANSI_COLOR="0;33"
CPE_NAME="cpe:/o:amazon:linux:2018.03:ga"
HOME_URL="http://aws.amazon.com/amazon-linux-ami/"
Amazon Linux AMI release 2018.03
[ec2-user@ip-10-1-0-251 ~]$ cat /proc/swaps
Filename				Type		Size	Used	Priority
[ec2-user@ip-10-1-0-251 ~]$ free
             total       used       free     shared    buffers     cached
Mem:       3796068    3287128     508940     120148     127728    1761744
-/+ buffers/cache:    1397656    2398412
Swap:            0          0          0
```

What is the expected behaviour here? Why is swap off by default?

**Comment by petderek** [comment]
Hey,

This is the expected behavior. Swap can be effective to handle memory overflow, but its usefulness varies by workload.

If its appropriate for your workload, enabling swap is one way to solve the problem. An alternative way you can do this is by reserving additional memory for your instance by setting the `ECS_RESERVED_MEMORY` variable described in our README. Setting this variable will increase the memory reservation, and therefore decrease the total amount of memory that ECS sees as available on your instance.

Feel free to reopen this if you have additional questions.

**Comment by alexzaytsev-newsroomly** [comment]
@petderek Yes, i do have questions.
In our case, i had an instance where the underlying OS's RAM usage was at some 95% at which point AWS Linux invoked kswapd0 which couldn't do anything but try to compact it as there was no swap. So i ended up with my cluster using 100% CPU trying to swap to a 0 sized disk.

What is the recommended approach to deal with this? What's the required free RAM for ECS cluster instances?

**Comment by NightKhaos** [comment]
If you intend to run your instance "hot", i.e. using a large percentage of the RAM, and are not going to add any additional swap manually, you should configure tweaking the settings of the `vm.swappiness` setting in the kernel runtime settings such that the kernel is configured not to swap at all. The default setting for the Linux Kernel is `60`, however obviously in your use case this isn't working for you as it is trying to swap too aggressively and using up CPU cycles in the process. Setting it to `0` will disable swap completely, meaning the kernel will never try and page out any memory.

```
sudo sysctl -w vm.swappiness=0
```

Be careful with this setting, if you create any swap files or partitions, with this setting set to `0`, the kernel will not use swap at all (at least for kernel 3.5 and higher). If you want it to be a conservative swap, i.e. only swap when it has no RAM free, you should set the value to `1`. Through this isn't recommended as preemptive swapping has some benefits.

**Comment by alexzaytsev-newsroomly** [comment]
@NightKhaos so what is the better approach for ECS optimized AWS Linux AMI? Enable swap or disable it in the kernel?

**Comment by NightKhaos** [comment]
> @NightKhaos so what is the better approach for ECS optimized AWS Linux AMI? Enable swap or disable it in the kernel?

Honestly it depends on your use case. If you're working with large tasks that have a lot of infrequently accessed memory that can be paged without a significant performance hit, then enabling swap may be applicable.

However, if your tasks are all going to benefit from having all of their working memory in memory, then I would disable swap with the `sysctl` command I mentioned above.
