### ISSUE TITLE
Docker registry v2 support

### ISSUE THREAD

**Issue by OscarBarrett** [aws/amazon-ecs-agent#162]
Is this planned? v1 has been deprecated and the docker team is strongly recommending that people switch to v2.

**Comment by euank** [comment]
V2 registries should work.
Are you running into issues when trying to use one with ECS?

**Comment by OscarBarrett** [comment]
Ah my mistake - I'm using a private registry with an EIP and I had to create a private hosted zone so that the ECS instances would use the private IP. The error mentioned API error (404) for /v1/_ping so I assumed that it was a compatibility issue between v1 and v2.
