### ISSUE TITLE
Make CFS quota period configurable

### ISSUE THREAD

**Issue by mseiwald** [aws/amazon-ecs-agent#1627]
It seems that the CFS quota period is fixed in ecs agent for the parent cgroup that is created for each task. https://github.com/aws/amazon-ecs-agent/blob/d68e729f73e588982dc2189a1c618c18c47c931b/agent/api/task/task_linux.go#L39

Since the length of this period can have consequences on performance (see [this](https://github.com/kubernetes/kubernetes/issues/51135) and [this](https://gist.github.com/bobrik/2030ff040fad360327a5fab7a09c4ff1)) we would like it to be configurable, e.g. as an argument to ecs-agent.

**Comment by hjacobs** [comment]
Just FYI: we decided to completely disable CFS quota for all Zalando Kubernetes clusters.

**Comment by adnxn** [comment]
closing since merged to `dev` with #1941
