### ISSUE TITLE
ECS task role do not work - unable to bind to port 51679

### ISSUE THREAD

**Issue by brubtsov** [aws/amazon-ecs-agent#1644]
### Summary
I create instance based on Windows Server 1803 and install ECS Agent using ECSTools PS module. Service works OK except the fact that ECS Task roles do not work. The reason is ECS Agent coonot bind to port 51679.

### Description
We experience huge networking problems when we use ECS optimized AMI on our production Windows cluster. I assume this is because AMI is based on Win Server 2016. A lot of networking issues were fixed in Windows Server 1803. So as a workaround I'm trying to create own ECS AMI based on this Windows version.

Here are exact steps that I'm doing to prepare AMI:

1) Create instance based on Windows_Server-1803-English-Core-ContainersLatest
2) Update Docker
`Install-Package -Name docker -ProviderName DockerMsftProvider -RequiredVersion 18.03.1-ee-2 -Update -Force`
3) Install missing HyperV features (without installing full Hyper-V feature command `Add-VMNetworkAdapter -VMNetworkAdapterName 'APIPA' -SwitchName nat -ManagementOS` will fail)
`Enable-WindowsOptionalFeature -online -FeatureName Microsoft-Hyper-V -all`
4) Copy ECSTools PS module to machine from folder 'C:\Program Files\WindowsPowerShell\Modules\ECSTools' from official ECS oprimized AMI
5) `docker pull microsoft/windowsservercore:1803`
6) "Registry fix" to increase number of TCP sockets available to Docker NAT
`New-ItemProperty "HKLM:\SYSTEM\CurrentControlSet\Services\WinNat" -Name "PortChunkSize" -Value 1000 -PropertyType "DWord"`
7) Prepare for AMI creation
`C:\ProgramData\Amazon\EC2-Windows\Launch\Scripts\InitializeInstance.ps1 –Schedule`
8) Create an AMI and launch new instance from that AMI using standard userdata:
```
<powershell>
[Environment]::SetEnvironmentVariable("ECS_ENABLE_CPU_UNBOUNDED_WINDOWS_WORKAROUND", "true", "Machine")
[Environment]::SetEnvironmentVariable("ECS_DISABLE_METRICS", "false", "Machine")
Import-Module ECSTools
Initialize-ECSAgent -Cluster 'Win1803' -EnableTaskIAMRole
</powershell>
```

Instance has joined the cluster. ECS task has started but it's unable to get credentials in order to use ECS task role. According to agent logs it happens because ECS Agent cannot bind to port 51679.
Container that I'm using does 3 things:

1. Prepare task for IAM role using script from here https://docs.aws.amazon.com/AmazonECS/latest/developerguide/windows_task_IAM_roles.html
2. Install AWS CLI
3. Try to download file from S3 bucket

### Expected Behavior
ECS task successfully starts and is able to use ECS task role.

### Observed Behavior
Task log returned error:
```
2018-10-24 18:49:39Error when retrieving credentials from container-role: Error retrieving metadata: Received error when attempting to retrieve ECS metadata: Connect timeout on endpoint URL: "http://169.254.170.2/v2/credentials/d4a422a2-46a4-44d3-a250-a2f75cd52a3b"
Error when retrieving credentials from container-role: Error retrieving metadata: Received error when attempting to retrieve ECS metadata: Connect timeout on endpoint URL: "http://169.254.170.2/v2/credentials/d4a422a2-46a4-44d3-a250-a2f75cd52a3b"
2018-10-24 18:48:2322 169.254.170.2/32 172.29.160.1 
2018-10-24 18:48:2322 169.254.170.2/32 172.29.160.1 
2018-10-24 18:48:23------- ----------------- ------- 
2018-10-24 18:48:23ifIndex DestinationPrefix NextHop 
```
I try to make a call to http://169.254.170.2/v2/credentials/d4a422a2-46a4-44d3-a250-a2f75cd52a3b from inside container and from instance. In both cases I get timeout error.

**Important note:
I managed to get it work. But only on t2.micro instance types.
If I choose any other other instance type - I'm having issues as described here.**
This was tested in different AWS regions and on different accounts.

### Environment Details
Task definition that I'm using:
Task role is assigned. Role has full S3 permissions.
Docker image - microsoft/windowsservercore:1803
Entry point - powershell,-Command
Command:
```
$gateway = (Get-WMIObject -Class Win32_IP4RouteTable | Where { $_.Destination -eq '0.0.0.0' -and $_.Mask -eq '0.0.0.0' } | Sort-Object Metric1 | Select NextHop).NextHop
$ifIndex = (Get-NetAdapter -InterfaceDescription "Hyper-V Virtual Ethernet*" | Sort-Object | Select ifIndex).ifIndex
New-NetRoute -DestinationPrefix 169.254.170.2/32 -InterfaceIndex $ifIndex -NextHop $gateway

Invoke-WebRequest https://s3.amazonaws.com/aws-cli/AWSCLI64PY3.msi -UseBasicParsing -OutFile c:\AWSCLI64.msi ;
Start-Process msiexec -Wait -ArgumentList '/I c:\AWSCLI64.msi /quiet';
$env:Path += ";C:\Program Files\Amazon\AWSCLI\bin"

aws s3 cp s3://my-bucket/Default/app.config app.config
while ($true) { Start-Sleep -Seconds 3600 }
```

### Supporting Log Snippets
Error from ECS Agent log:
_Error running http api: listen tcp :51679: bind: An attempt was made to access a socket in a way forbidden by its access permissions_

**Comment by adnxn** [comment]
>  So as a workaround I'm trying to create own ECS AMI based on this Windows version.

Thanks for experimenting with 1803, it is currently an unsupported platform on ECS. We need to investigate this further, but in the meantime please feel free to add any new information as you are debugging.

> Prepare task for IAM role using script from here https://docs.aws.amazon.com/AmazonECS/latest/developerguide/windows_task_IAM_roles.html

Just to confirm, you're running the bootstrap script on your containers yea?

**Comment by brubtsov** [comment]
> > Prepare task for IAM role using script from here https://docs.aws.amazon.com/AmazonECS/latest/developerguide/windows_task_IAM_roles.html
> 
> Just to confirm, you're running the bootstrap script on your containers yea?
Yes, I run this script. I mentioned that part 'Environment Details' section.

Perhaps problem is because of Hyper-V which makes changes to network interfaces during installation. But without it I cannot initialize ECS agent.

**Comment by sharanyad** [comment]
Closing this issue for now. Please feel free to re-open if more information is needed.

**Comment by zbintliff** [comment]
Is there a reason why ECS agent doesn't more loudly complain or die if this isn't possible? We ran into production issues because this happened but only way of knowing was parsing logs.
