### ISSUE TITLE
ECSAgentConfiguration 'failure' is too loud

### ISSUE THREAD

**Issue by tedder** [aws/amazon-ecs-agent#1647]
### Summary
ECSAgentConfiguration emits a warning on startup that makes it appear *all* of my configuration is invalid.

### Description
`ECSAgentConfiguration` was added to the agent, it comes from cloud-init (I think).

It shows up as a warn-level error:

    2018-10-24T23:23:12Z [WARN] Unable to parse user data: invalid character '#' looking for beginning of value

That seems really alarming! Is my config being ignored? No, it's a red herring. Sure, it's only a warn, but in reality it should be a debug or info for the standard case where there is no ECSAgentConfiguration section.

### Expected Behavior
A subtle message when this is missing, with a little bit of context.

### Observed Behavior
as above.

### Environment Details
Amazon Linux 2, ECS Optimized

### Supporting Log Snippets
as above.

**Comment by adnxn** [comment]
> No, it's a red herring. 

it is! good catch and yea this could be a debug level log.

**Comment by adnxn** [comment]
closing, fix merged.
