### ISSUE TITLE
missing image pull inactivity timeout gives noisy warning

### ISSUE THREAD

**Issue by tedder** [aws/amazon-ecs-agent#1648]
### Summary
Parsing a configuration without a `ECS_IMAGE_PULL_INACTIVITY_TIMEOUT` gives a loud warning.

### Description
`ECS_IMAGE_PULL_INACTIVITY_TIMEOUT` has a default value, but if the config entry isn't in *my* config, a warn-level log is emitted:

    2018-10-24T23:23:12Z [WARN] Invalid value for image pull inactivity timeout duration, will be overridden with the default value: 1m0s. Parsed value: 0s, minimum value: 1m0s.

That seems really alarming! What did I set for that? Did I do it wrong? No, it's a red herring. Sure, it's only a warn, but in reality it should be a debug or info for the standard case where I'm okay with the defaults. Note this doesn't happen with any other defaulted values that I've seen.

### Expected Behavior
A subtle message or no message when the default is used.

### Observed Behavior
as above.

### Environment Details
Amazon Linux 2, ECS Optimized

### Supporting Log Snippets
as above.

**Comment by petderek** [comment]
Thanks! I'll try to get this into the next release.

**Comment by adnxn** [comment]
closing, fix merged.
