### ISSUE TITLE
Unable to delete the cluster - Deletion of CloudFormation stack timed out

### ISSUE THREAD

**Issue by PiedPieper** [aws/amazon-ecs-agent#1657]
### Summary
I am trying to delete an ECS cluster with no success.

### Observed Behavior
Below are images showing the console:
![screen shot 2018-10-29 at 10 29 17 am](https://user-images.githubusercontent.com/30536469/47678080-3fb26280-db97-11e8-9717-1bd9cd5be9d3.png)

![screen shot 2018-10-29 at 11 26 52 am](https://user-images.githubusercontent.com/30536469/47678096-5062d880-db97-11e8-8493-bfc8b669fbaa.png)

**Comment by adnxn** [comment]
> I am trying to delete an ECS cluster with no success.

what part of the delete cluster workflow is failing? 

when you look at the cloud formation stack, it should show you the exact failure in the workflow.

**Comment by PiedPieper** [comment]
@adnxn Can you see the image i posted? This is all that I see. It never progresses past the point of 
"Deleting ECS taks and services ... COMPLETE"
"Deleting cluster resources. This may take a few minutes.."

**Comment by PiedPieper** [comment]
I tried again on another container, it died at "AWS::EC2::InternalGateway" 8 of 10 resources deleted

**Comment by adnxn** [comment]
> Can you see the image i posted? 

yea, though it didn't show detailed information related to cloudformation stack failures. 

> I tried again on another container, it died at "AWS::EC2::InternalGateway" 8 of 10 resources deleted

Hm this and the other errors you mentioned are unrelated to the ecs agent. I suggest reaching out to [aws support center](https://console.aws.amazon.com/support/home?#) to help debug the issue you are seeing.

**Comment by adnxn** [comment]
closing this issue as it's unrelated to the ecs agent.
