### ISSUE TITLE
When will ECS Optimized AMI for Windows Server move to 1803 or 1709 OS builds?

### ISSUE THREAD

**Issue by malcolm-boden** [aws/amazon-ecs-agent#1661]
I am wondering when amazon's ECS Optimized ami will be built on top of a newer windows build? i.e. 1803 or 1709 ? 

There are new features that make docker containers easier to work with in these windows builds.

**Comment by adnxn** [comment]
> I am wondering when amazon's ECS Optimized ami will be built on top of a newer windows build? i.e. 1803 or 1709 ?

1803/1709 are currently unsupported platforms ECS. It is on our roadmap but we don't have a public date for official support yet. In the meantime, you're more than welcome to experiment and provide us with feedback similar to here https://github.com/aws/amazon-ecs-agent/issues/1644

**Comment by adnxn** [comment]
see your 👍 and closing issue for now. please feel free to update the thread with your findings if you do decide the experiment with 1803/1709.

**Comment by red8888** [comment]
This is still not supported? 

I tried to join an 1803 instance to an ECS cluster in the usual way:
```
PS C:\Users\Administrator> Import-Module ECSTools
Import-Module : The specified module 'ECSTools' was not loaded because no valid module file was found in any module
directory.
```

**Comment by aidansteele** [comment]
Now that Windows Server 2019 AMIs are available from Amazon, can we expect to see 2019-based ECS-optimised AMIs?

**Comment by red8888** [comment]
maybe windows ECS support is frozen or being phased out completely. The AMIs still have not been updated to support ECS

**Comment by adnxn** [comment]
> maybe windows ECS support is frozen or being phased out completely

windows ECS support is definitely not being phased out and we're still evaluating the newer windows builds for ECS. The [earlier comment](https://github.com/aws/amazon-ecs-agent/issues/1661#issuecomment-434372804) still stands though, please feel free to experiment and let us know your findings in the meantime.

**Comment by josuearrieta** [comment]
Any update on this? Any possible date for Windows Server 2019 ECS optimized ?

**Comment by adnxn** [comment]
@josuearrieta: we don't have a date for official support yet. we'll update public facing documentation accordingly when we do though.

**Comment by Drewster727** [comment]
hey all, I'm also very interested in running server 2019 with ECS. I have made some attempts to get the ecs agent running on a 2019 containers AMI, but it's not working. Any updates or tips?

**Comment by leftathome** [comment]
Speaking as someone who's running Windows containers on 1709 instances, I'd find it easier to move to ECSTools for bootstrapping the agent if the module's source repo, documentation and releases were as accessible as the ECS agent itself is.

I only even found out this much because instances have stopped registering on my new cluster and poking around this repo led me to realizing my bootstrap's way out of date.  Yikes!

**Comment by dimmy-timmy** [comment]
@Drewster727 Looks like Amazon officially added support for windows 2019 on ECS https://docs.aws.amazon.com/AmazonECS/latest/developerguide/ECS_Windows.html
