### ISSUE TITLE
ECS Fargate failing to fetch container even with a public IP

### ISSUE THREAD

**Issue by MicroTransactionsMatterToo** [aws/amazon-ecs-agent#1680]
### Summary

ECS task running via Fargate is unable to pull an image even when given a public IP

### Description

I've been learning my way around AWS, and had gotten ECS up and running fine. However, upon creating a new cluster to run my task, using the same configuration as had previously worked without issue, ECS now fails to pull the container image, with a `CannotPullContainerError: API error (500): Get https://xxx.dkr.ecr.ap-southeast-2.amazonaws.com/v2/: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)`. It should be noted that the IAM role is configured to allow read access to ECR and the task is assigned a public IP address. 

### Expected Behavior
It starts the task without issue

### Observed Behavior
It sits there for about 3 minutes then fails. Rinse and repeat

### Environment Details

I'm unsure of how to collect these for Fargate

### Supporting Log Snippets

Same as above

**Comment by MicroTransactionsMatterToo** [comment]
Managed to get it working again by modifying the network ACL

**Comment by hdodov** [comment]
In my case, I had to allow inbound traffic from `0.0.0.0/0` in the associated security group.
