### ISSUE TITLE
How does ecs deal with slow starting services

### ISSUE THREAD

**Issue by nexus49** [aws/amazon-ecs-agent#169]
I have services that take a while to start, but i have not seen any documentation on how ecs deals with this use case. When in the process of starting does ecs:

1) register task as running 
    - I assume when docker reports the container as running
2) register task at ELB
    - I assume directly after 1)
3) start to stop other tasks with the prior version
    - I assume in the case of ELBs, after the ELB reports a certain instance as healthy

In the process of initialization what can contribute to the container being stopped, is it in the way that right after 2) the ELB will start health checking and ECS will kill the container if the unhealthy threshold is reached? 

If above is true then this is problematic for slowly starting services, since in general having a low unhealthy threshold is something you may want to have, but on the other side i'd have to increase the unhealthy threshold to prevent the container being killed during startup.

**Comment by nexus49** [comment]
Maybe to add a little background to this question. I am asking this due to a current issue that i am struggling with. 

I have a load balancer setup with a health check (interval 60s, healthy Threshold 6): 
- My expectation would be that ECS would start to drain connections for other tasks after a minimum of 6 minutes after a task had been registered to the ELB. 

But this does not match my observation i see ecs draining connections on another task way earlier than that. 

I apologize if I am missing some understanding on the ELB/ECS integration :-)

Thanks for your clarifications, this is highly appreciated.

**Comment by kiranmeduri** [comment]
Your understanding of ELB <-> ECS integration is correct regarding the healthchecks and task life-cycle. ECS will stop the tasks which are reported as un-healthy by ELB and replace them with new ones. You need to adjust the ELB settings to make sure ELB waits a bit longer in your case and reports healthy. Contract between ECS and ELB is just based on health of instances. In future for ECS service related issues please post in the forums at https://forums.aws.amazon.com/forum.jspa?forumID=187&start=0 for faster response. 

Thanks,
-kiran

**Comment by samuelkarp** [comment]
@nexus49 I'm going to resolve this for now.  Please feel free to reopen this issue if we can help further.
