### ISSUE TITLE
describe-task-definition call drops secrets key from containerDefinitions entries

### ISSUE THREAD

**Issue by ian-axelrod** [aws/amazon-ecs-agent#1694]
### Summary
The `describe-task-definition` API drops container `secrets` keys from its response. The [documentation](https://docs.aws.amazon.com/cli/latest/reference/ecs/describe-task-definition.html#output) suggests this key should be present in the response. 

### Description

Calling `describe-task-definition` (e.g., `aws --region us-east-2 --output json ecs describe-task-definition --task-definition arn:aws:ecs:us-east-2:account-id:task-definition/family:version`) returns a JSON body with `taskDefinition.containerDefinitions` array objects missing their `secrets` key, if they have one. The [documentation](https://docs.aws.amazon.com/cli/latest/reference/ecs/describe-task-definition.html#output) suggests this key should be present in the response.

I have deployment logic that relies on propagating task definition environment variables (`environment` and `secrets`) from one task definition version to the next. This logic no longer works after upgrading to agent 1.22, which is how I discovered the issue.  

### Expected Behavior
`describe-task-definition` returns the response detailed in its documentation, which includes `taskDefinition.containerDefinitions[].secrets` objects.

### Observed Behavior
`describe-task-definition` does not return the response detailed in its documentation: it does not include `taskDefinition.containerDefinitions[].secrets` objects.

### Environment Details
```
ip-192-168-1-161:themuse ianaxelrod$ docker version
Client:
 Version:           18.06.1-ce
 API version:       1.38
 Go version:        go1.10.3
 Git commit:        e68fc7a
 Built:             Tue Aug 21 17:21:31 2018
 OS/Arch:           darwin/amd64
 Experimental:      false
```

### Supporting Log Snippets
None, but happy to provide a video demonstration.

**Comment by ian-axelrod** [comment]
Let me know if this is better suited for https://github.com/aws/aws-cli/issues. I can move it there.

**Comment by yumex93** [comment]
Hi! Can I know which version of aws cli you are using? When I use **aws-cli/1.16.57**, **secrets** is returned.

**Comment by yumex93** [comment]
Make sure you follow the instructions [here](https://docs.aws.amazon.com/cli/latest/userguide/cli-install-macos.html) to upgrade your aws cli. **yum** does not work anymore.

**Comment by ian-axelrod** [comment]
Ah, I was on version 1.16.49. 1.16.57 works. I did not realize the client had to be updated to pull the new information, but it makes a lot of sense that it would need this. Thank you!
