### ISSUE TITLE
ECS Agent Mark Knowstatus as Stopped but container runs in the background

### ISSUE THREAD

**Issue by jaykam** [aws/amazon-ecs-agent#1702]
Hello haikuoliu,

@haikuoliu 

### Summary
ECS Agent mark known status as stopped but contaoner does not get terminated.
It runs the job in the background.

### Observed Behavior
I run the ECS task and after running that ECS agent mark known status from PENDING to RUNNING and after immidiately It mark RUNNING to STOPPED but docker container does not get terminated.

### Expected Behavior

If there is no error then it should not mark known status as STOPPED. If it mark as STOPPED then docker container should get terminate or stop.

**Comment by haikuoliu** [comment]
Hi @jaykam,

Thanks for reporting this and sorry for the delay, can you please send me the agent logs at haikuo at amazon.com to help debug the issue?

Haikuo

**Comment by adnxn** [comment]
@jaykam: closing this issue since we havent heard back, feel free to reopen if you're still blocked.

**Comment by mfortin** [comment]
This sounds related to issue #1708

**Comment by pecigonzalo** [comment]
I still face this issue, seems like the container remains within the timeout of `ECS_CONTAINER_STOP_TIMEOUT`.
I believe it should not report to ECS that its stopped, as otherwise I have services set to `min=0, max=100` that sometimes have 2 instances running, causing issues (lock files, etc)

**Comment by pecigonzalo** [comment]
@adnxn sorry to ping you directly, but could you reopen this?

**Comment by jaykam** [comment]
Hello @haikuoliu 

I'm still facing the same issue and I'm using ecs-agent version 1.24.0 and docker 18.06 CE
