### ISSUE TITLE
1.22 Container Instance Tags issues

### ISSUE THREAD

**Issue by FLavalliere** [aws/amazon-ecs-agent#1704]
### Summary

1.22  and EC2 Propagate instance tags failure

### Description
The Custom tags attributes doesn't seems functionnal anymore starting 1.22. Trying to use the Propagate instance tags using ECS_CONTAINER_INSTANCE_PROPAGATE_TAGS=ec2_instance with Cloudformation with AutoScaling group and propagate tags.  It tries to add the aws: tags which cannot b e done and then, the ECS Agen exit.

Here is the error, since aws:cloudformation:stack-id is on the ec2 instance

2018-11-24T15:17:50Z [ERROR] Unable to register as a container instance with ECS: InvalidParameterException: Tag key must not start with aws:
        status code: 400, request id: 1b7ddaea-effc-11e8-88f4-533d0c7b5b1e

**Comment by petderek** [comment]
Thanks for reaching out. We're looking into this.

**Comment by toredash** [comment]
We were hit by this as well. One strange thing that we noticed that it did not affect t3.small instances, but it did affect t3.medium and c4.xlarge. Didn't spend time doing more testing.

**Comment by haikuoliu** [comment]
Hi all, the Agent 1.23.0 is released and this issue is fixed, I am going to close this issue.

Note that this release is Agent only release, which means you can only get the Agent 1.23.0 by either downloading from s3 bucket or pulling it from DockerHub.

Thanks,
Haikuo

**Comment by haikuoliu** [comment]
Just to be clear, you can get access to the latest Agent from  [a list of S3 buckets](https://docs.aws.amazon.com/AmazonECS/latest/developerguide/ecs-agent-install.html#ecs-agent-install-nonamazonlinux), and from [DockerHub](https://hub.docker.com/r/amazon/amazon-ecs-agent/tags/)
