### ISSUE TITLE
Agent logs use up the disk space

### ISSUE THREAD

**Issue by haikuoliu** [aws/amazon-ecs-agent#1738]
### Summary

Today agent's logs roll based on date, if some customer starts many task in a short period of time, the agent log will probably use up the disk space, so we should consider making agent log roll based on the log size, this is configurable in `seelog`, we may want it to be an agent configuration depends on whether customer are ok with losing some agent logs.

**Comment by haikuoliu** [comment]
currently we have agent logs configured as `maxrolls="24"`, which means the agent log will only be available for 1 day, it's not very convenient for debugging purpose, since we don't have a way to track the old agent logs.

**Comment by jy19** [comment]
Closing for now, we plan to revisit logging configurations in the near future.

**Comment by levigroker** [comment]
How can this be closed? Has the issue been addressed (doesn't appear so). Closed implies there is a fix in place, but closing in *anticipation* of a fix is a new one on me.

**Comment by adnxn** [comment]
@levigroker: you're right, our mistake. reopening this till logging changes are in place.

**Comment by sparrc** [comment]
closing, tracking in #2284
