### ISSUE TITLE
Upgrade Agent Version to 1.4.0 permanently

### ISSUE THREAD

**Issue by jordi-chacon** [aws/amazon-ecs-agent#175]
Hi,

I am an ECS user. My container instance has agent version 1.1.0. I would like to have metrics with CloudWatch so I have manually updated the agent version to 1.4.0 through the AWS console.

The problem is that when I stop the EC2 instance running the ECS cluster and then I create a new EC2 instance and launch the ECS cluster there, the agent version of the container instance is 1.1.0 agian.

How can I use version 1.4.0 permanently?

Thank you

**Comment by aaithal** [comment]
Hi,

Can you please specify if you are using the latest Amazon Linux AMI (The list is available here: http://docs.aws.amazon.com/AmazonECS/latest/developerguide/launch_container_instance.html)? 

Thanks,
Anirudh

**Comment by jordi-chacon** [comment]
Hi,

thank you for the quick response.

I am using AMI ami-ed7c149a, which is not in the list. I will upgrade to the latest in eu-west-1.

I just solved the issue though, by running `yum update -y ecs-init` from within the `userdata.txt`, on EC2 instance startup.

Thank you for your help!
