### ISSUE TITLE
Not all docker plugins are detected

### ISSUE THREAD

**Issue by kshcherban** [aws/amazon-ecs-agent#1824]
### Summary
There're 2 ways of installing docker plugins:
1. Putting socket in `/run/docker/plugins`
1. Through docker plugin api, e.g. `docker plugin install`, `docker plugin enable`

Please check https://docs.docker.com/engine/extend/plugin_api/#plugin-discovery

When the first one is used ECS agent can't find the plugin.
If volume plugin is configured in ECS services, service's startup fails with following error:
```
service example-app was unable to place a task because no container instance met all of its requirements. The closest matching container-instance 9f609ba9-fd39-4047-9c0b-c4dad8a8e7a0 is missing an attribute required by your task. For more information, see the Troubleshooting section.
```
However you can create volume using docker cli.
`docker volume create --driver xfsquota testVolume`

### Expected Behavior
ECS agent will try to use plugin on the instance itself.

#### docker info
```
Containers: 25
 Running: 13
 Paused: 0
 Stopped: 12
Images: 20
Server Version: 18.06.1-ce
Storage Driver: overlay2
 Backing Filesystem: xfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local xfsquota
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 468a545b9edcd5932818eb9de8e72413e616e86e
runc version: 69663f0bd4b60df09991c08812a60108003fa340
init version: fec3683
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.9.0-8-amd64
Operating System: Debian GNU/Linux 9 (stretch)
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 15.22GiB
Name: aws-eu-qa-ecs-apps-2
ID: BYUK:GBYV:372V:ZTAJ:IQPH:SL6X:43IC:KLGY:YRI2:L6PU:PSKE:ITB2
Docker Root Dir: /mnt/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

WARNING: No swap limit support
```
As you can see, plugin `xfsquota` is listed in docker info output but is not picked up by ecs agent.

ECS Agent version is v1.24.0

**Comment by yunhee-l** [comment]
Hello kshcherban,
ECS Agent relies on Docker's plugin discovery ([Scan](https://github.com/moby/moby/blob/master/pkg/plugins/discovery.go#L29)), which implements the plugin discovery you have linked, for detecting V1 plugins. 

However, the plugin you provided in the example command ([xfsquota](https://github.com/cirocosta/xfsvol)) seems to be V2 plugin, where installation/detection are handled by docker. Instructions by the plugin provider only outlines installation through `docker plugin install`. Could you please verify whether this plugin actually conforms to docker's V1 plugin?

**Comment by yunhee-l** [comment]
Could you please verify if your plugin is discoverable without ECS in the middle? I'm assuming yours is V1 plugin, and given that ECS Agent does not have any custom logic around its discovery and rely completely on Docker's own scanning, I do not see this being ECS logic that's preventing plugin discovery.

**Comment by yunhee-l** [comment]
FYI V1 plugins won't show up in `docker plugin ls` in general.

**Comment by kshcherban** [comment]
That what i'm trying to point out. Seems that ECS Agent uses docker plugin scanning to add discovered plugins to capabilities
https://github.com/aws/amazon-ecs-agent/blob/master/agent/dockerclient/dockerapi/docker_client.go#L1218

But if plugin is not found there that doesn't plugin is not installed or not working.

However docker can work with plugins that are not listed with this scan. Please see below:
```
root@debian:~# ls -la /run/docker/plugins/
total 0
drwx------ 3 root root  80 Feb  1 12:28 .
drwx------ 8 root root 180 Feb  1 12:33 ..
drwx------ 3 root root  60 Jan 28 12:37 runtime-root
srw-rw---- 1 root root   0 Feb  1 12:26 xfsquota.sock
root@debian:~# docker plugin ls
ID                  NAME                DESCRIPTION         ENABLED
root@debian:~# docker volume ls
DRIVER              VOLUME NAME
xfsquota            xfs-1
root@debian:~# docker volume create --driver xfsquota --opt size=112M ecs-test
ecs-test
root@debian:~# docker run --rm -v ecs-test:/data -ti debian:jessie df -h /data
Filesystem      Size  Used Avail Use% Mounted on
/dev/vdb1       112M     0  112M   0% /data

Plugin is not listed with `plugin ls` command however `info` command shows it.
```
root@debian:~# docker info | grep -A1 -i plugin
Plugins:
 Volume: local xfsquota
```

I will contact Docker community for clarification about V1 and other plugins and try to open source my plugin code when possible.

**Comment by kshcherban** [comment]
@yunhee-l true, after some help from Docker community and digging project issues i have figured out that there're 2 versions of plugins: V1 and V2.
https://github.com/moby/moby/issues/32591

Can you please advise if ECS agent will ever support V1 plugins? Because it's still supported by docker engine.

**Comment by kshcherban** [comment]
Also please check this comment on V1 and V2:
https://github.com/docker/cli/pull/506#issuecomment-367005408

**Comment by yunhee-l** [comment]
ECS does support both V1 and V2 volume plugins. ECS uses docker's scan function to detect V1 plugins, on top of `docker plugin ls`for V2 plugins. 
What version of Agent are you using?

**Comment by kshcherban** [comment]
ECS Agent version is v1.24.0

**Comment by yunhee-l** [comment]
Could you please enable debug level logging on agent, and send the logs to yhlee _at_ amazon.com?
https://docs.aws.amazon.com/AmazonECS/latest/developerguide/ecs-logs-collector.html

If you could share your plugin too, that'll help us repro and diagnose the issue as well.

**Comment by kshcherban** [comment]
@yunhee-l meanwhile you can test with plugin https://github.com/containers/docker-lvm-plugin
It uses the same installation method.

**Comment by Defozo** [comment]
I run into a similar problem - `cloudstor:aws` plugin wasn't detected but I simply put `service docker restart` just after plugin installation in user-data and now everything works like a charm.

**Comment by yunhee-l** [comment]
I apologize for the delay in investigating this issue due to other priorities, but we are looking into this now. We will update once we find anything.

**Comment by shubham2892** [comment]
@kshcherban Have you tried restarting docker, seems to have solved the issue for @Defozo and is also the recommendation in the documentation. 

If that does not help, can you please share the instructions to build the plugin here. I tried  `https://github.com/containers/docker-lvm-plugin` but make file is broken and has further external dependencies.

**Comment by kshcherban** [comment]
@shubham2892 for [docker-lvm-plugin](https://github.com/containers/docker-lvm-plugin) please use following commands to build:
```
go get
make lvm-plugin-build
```

Once i test issue on clean, new ECS cluster i will provide you with logs and replication steps.

**Comment by shubham2892** [comment]
Send them over to shugy _at_ amazon.com when you have them.

**Comment by kshcherban** [comment]
@shubham2892 i've sent you the logs.
During my testings i discovered that ecs-agent needs to be restarted in order to discover V1 plugins changes. That's why docker restart fix worked.
So the issue now is that ecs-agent doesn't dynamically pick up docker plugin like docker itself.

**Comment by shubham2892** [comment]
@kshcherban Currently plugin needs to be installed before Agent start in order for Agent to detect it. If you look at the [docker docs](https://docs.docker.com/engine/extend/plugin_api/#plugin-lifecycle), their recommendation is also to start plugin before starting Docker, and stop after Docker.

We will also update Amazon ECS docs to convey the same.
