### ISSUE TITLE
ECS agent no longer redirects http://169.254.170.2/$AWS_CONTAINER_CREDENTIALS_RELATIVE_URI

### ISSUE THREAD

**Issue by samuelkarp** [aws/amazon-ecs-agent#1839]
### Summary
The ECS agent makes IAM roles available to tasks at an endpoint defined by a well-known IP and the `AWS_CONTAINER_CREDENTIALS_RELATIVE_URI` environment variable.  In some version after 1.20.0, the ECS agent serving some requests.

### Description
The `AWS_CONTAINER_CREDENTIALS_RELATIVE_URI` is an environment variable defining the relative path where credentials should be queried from 169.254.170.2.  The content of the environment variable always starts with `/` and it is expected that requests are made to `http://169.254.170.2$AWS_CONTAINER_CREDENTIALS_RELATIVE_URI`.  In older versions of the ECS agent, requests to `http://169.254.170.2/$AWS_CONTAINER_CREDENTIALS_RELATIVE_URI` (which contains an extra `/`) would also be served by redirecting them to the correct URL.  This appears to have changed.

### Expected Behavior
Requests to `http://169.254.170.2/$AWS_CONTAINER_CREDENTIALS_RELATIVE_URI` are served or redirected to `http://169.254.170.2$AWS_CONTAINER_CREDENTIALS_RELATIVE_URI`

### Observed Behavior
Requests to `http://169.254.170.2/$AWS_CONTAINER_CREDENTIALS_RELATIVE_URI` result in a 404

**Comment by yunhee-l** [comment]
Investigation by Sharanya: 
did a binary search and found out we broke it in https://github.com/aws/amazon-ecs-agent/releases/tag/v1.21.0 
suspect this “Add v3 task metadata support for awsvpc, host and bridge network mode”

**Comment by bzemms** [comment]
https://stackoverflow.com/questions/54614616/got-404-from-http-169-254-170-2-aws-container-credentials-relative-uri/54618368?noredirect=1#comment96069973_54618368

**Comment by sharanyad** [comment]
this is now fixed with https://github.com/aws/amazon-ecs-agent/releases/tag/v1.25.3
