### ISSUE TITLE
Docker out of memory

### ISSUE THREAD

**Issue by 2ndalpha** [aws/amazon-ecs-agent#184]
My ECS instance ran out of memory and Docker died with
"fatal error: runtime: out of memory"

docker ps
FATA[0000] Cannot connect to the Docker daemon. Is 'docker -d' running on this host?

I can see that "/agent" process and my apps are still running.

Agent Connected: true
Status: ACTIVE
Agent version: 1.4.0
Docker version: 1.6.2

Is it safe to restart docker?

**Comment by euank** [comment]
If Docker is no longer running but the agent process still is, I don't think restarting Docker will re-parent the Agent process or any other container processes that continued running. At the very least you'll want to kill all such processes. I would certainly recommend sending a `SIGTERM` the way of the agent if you're going to continue using this instance.

However, under memory contention, it's possible for programs to misbehave, write corrupted state, etc. There's also a chance other processes were oom-killed before the Docker daemon, meaning the impact could be larger than just Docker/containers.

The safest thing to do would be to discard the instance and launch a new one, but if you want to try and terminate all "orphaned" container processes and restart Docker, it *might* work.

Feel free to re-open if you'd like other input / discussion.
