### ISSUE TITLE
agent does not send prometheus port in RCI 

### ISSUE THREAD

**Issue by sharanyad** [aws/amazon-ecs-agent#1843]
### Summary
Agent sends reserved ports to ECS service through register container instance call . Prometheus port is not added when prometheus metrics collection is enabled. 

### Description
context: 
https://github.com/aws/amazon-ecs-agent/pull/1819

**Comment by fenxiong** [comment]
I think it's added [here](https://github.com/aws/amazon-ecs-agent/blob/master/agent/config/config_unix.go#L86-L91) ?

**Comment by sharanyad** [comment]
thanks @fenxiong 
closing this
