### ISSUE TITLE
ECS agent listens on 0.0.0.0

### ISSUE THREAD

**Issue by nguse** [aws/amazon-ecs-agent#1846]
The ECS Agent seems to listen on 0.0.0.0 for ports 51678 and 51679.

I have limited understanding of all of the usage of these ports, but is it necessary to expose these services to the entire internet? Could they instead listen on 127.0.0.1?

**Comment by yinshiua** [comment]
Thank you for reporting the issue. We are working on a fix.

**Comment by nguse** [comment]
Thank you @yinshiua!

**Comment by nguse** [comment]
@yinshiua Any update on a fix for this?

**Comment by yinshiua** [comment]
@nguse Thanks again for reporting the issue. We have included the fix in our latest ECS agent.
See [link](https://forums.aws.amazon.com/ann.jspa?annID=6629) for more details.
