### ISSUE TITLE
ECS agent should start with `--net=host` for all functional tests

### ISSUE THREAD

**Issue by aaithal** [aws/amazon-ecs-agent#1873]
### Summary/Description

Most of the functional tests start the agent with `bridge` networking mode. This runs contrary to how the agent is actually started in production. We should also get rid of the `ECS_FTEST_FORCE_NET_HOST` env var while we're addressing this.

**Comment by petderek** [comment]
We have no real reason to test on bridge mode anymore, correct?

**Comment by aaithal** [comment]
> We have no real reason to test on bridge mode anymore, correct?

Yeah, I think so (unless there are some conditional tests that require old agent versions).

**Comment by fenxiong** [comment]
done in https://github.com/aws/amazon-ecs-agent/pull/2253
