### ISSUE TITLE
Feature request: incorporate chargeback scripts

### ISSUE THREAD

**Issue by renutz** [aws/amazon-ecs-agent#1877]
### Summary

Incorporate chargeback scripts

### Description

AWS provides a good sample of how to do chargeback - https://aws.amazon.com/blogs/compute/measuring-service-chargeback-in-amazon-ecs/

How about incorporating the metric collection into the agent? We could setup configuration and decide to publish or not the metrics info.

**Comment by samuelkarp** [comment]
Hi @renutz!  The current recommended pattern for collecting chargeback billing information for ECS tasks is to use the [recently-launched tag support](https://aws.amazon.com/about-aws/whats-new/2018/11/amazon-ecs-and-aws-fargate-now-allow-resources-tagging-/).  Check out the documentation on [tagging for billing](https://docs.aws.amazon.com/AmazonECS/latest/developerguide/ecs-using-tags.html#tag-resources-for-billing) and [usage reports with Cost Explorer](https://docs.aws.amazon.com/AmazonECS/latest/developerguide/usage-reports.html).

**Comment by renutz** [comment]
Awesome! I missed that. Feel free to close this issue plz.
