### ISSUE TITLE
Parallel Pull test should be updated

### ISSUE THREAD

**Issue by petderek** [aws/amazon-ecs-agent#1921]
### Summary
Parallel pull test isn't in a great state on Arm. 

* It will sometimes fail with httpd getting oom killed
* Sometimes, the official images we are using will get updated and break (this happened with nginx? the other day).

We should figure out how to make this test deterministic and not rely on dockerhub.

### Supporting Log Snippets
```
{
    ExitCode: 0,
    HealthStatus: "UNKNOWN",
    LastStatus: "STOPPED",
    Name: "httpd",
    NetworkBindings: [],
    NetworkInterfaces: [],
    Reason: "OutOfMemoryError: Container killed due to memory usage"
},
```

**Comment by fenxiong** [comment]
fixed in https://github.com/aws/amazon-ecs-agent/pull/2183
