### ISSUE TITLE
Unskip EI functional test when EI is fully supported

### ISSUE THREAD

**Issue by fenxiong** [aws/amazon-ecs-agent#1924]
### Summary

As per https://github.com/aws/amazon-ecs-agent/pull/1922, currently there's no region where all AZs in it support EI, and there's no deterministic way to say which AZs support it, so the test is skipped to avoid test failures. Creating this issue to keep track of un-skipping it.

**Comment by petderek** [comment]
Do you know what approximate version it will be released in? You could require version > ${release_version} and then override that in your own tests.

**Comment by fenxiong** [comment]
> Do you know what approximate version it will be released in?

I currently don't know an approximate version for this. i can update the test once there's an intended release version.

**Comment by fenxiong** [comment]
closing since functional tests are being deprecated in this repo
