### ISSUE TITLE
How does ecs-agent obtain task & execution roles permissions?

### ISSUE THREAD

**Issue by jedi4ever** [aws/amazon-ecs-agent#1945]
I'm trying to understand how the ecs-agent get the necessary credentials for each of the task/execution roles.

From what I understand, the machine running an ecs cluster only needs a minimal ec2 instance  role *AmazonEC2ContainerServiceforEC2Role* ; this only contains some ecs permissions to register within the cluster/etc..
<https://docs.aws.amazon.com/AmazonECS/latest/developerguide/instance_IAM_role.html>
( fwiw I would improve the docs that  create cluster is not necessary for miminal for convenience and it should limit to a resource of a specific cluster)

Then you have to give the services ec2, ecs,ecs-task permissions to passrole. In all docs I've seen this has resource '*' . This seems scary as it would be able to pass *all* roles to a container. (ones with admin priveleges too)
Theoretically you could limit it to specific roles it could pass.

Still if one would limit it on cluster1 to role1-a and role1-b ; for cluster2 it would have to allow services to passrole role2-a and role2-b. Then what prevents from assuming cluster1 the roles of cluster2?

I do understand how the agent acts a proxy between the containers themselves.
But I fail to understand how the trust/passing of roles is happening inside an ecs-agent in relation to the passrole and how to make it restrictive.

Thanks for clarifying or pointing me in the direction of existing docs.

**Comment by adnxn** [comment]
> Still if one would limit it on cluster1 to role1-a and role1-b ; for cluster2 it would have to allow services to passrole role2-a and role2-b. Then what prevents from assuming cluster1 the roles of cluster2?


im not following your example. to clarify - are you asking about [task roles](https://docs.aws.amazon.com/AmazonECS/latest/developerguide/task-iam-roles.html) to enable granular permissions per task? if so, that link provides more details about how the agent is vending role credentials to the containers.

**Comment by adnxn** [comment]
closing issue for now since no updates.
