### ISSUE TITLE
ECS cluster cannot run tasks in private subnet when using EC2

### ISSUE THREAD

**Issue by mostafafarzane** [aws/amazon-ecs-agent#1979]
### Description
I have a task definition that configured to use awsvpc network mode.
according to [this](https://docs.aws.amazon.com/AmazonECS/latest/developerguide/ecs_run_task_ec2.html):

> Only private subnets are supported for the awsvpc network mode. Because tasks do not receive public IP addresses, a NAT gateway is required for outbound internet access, and inbound internet traffic should be routed through a load balancer.

I set up a NAT gateway in a public subnet(that has internet gateway and EC2 itself resides on) and config route table in the private subnet to send the traffic to NAT gateway. But when I want to create a task that resides in private subnet I get:

> Run tasks failed Reasons : ["ATTRIBUTE"]. Learn more

If I choose the public subnet that the EC2 itself uses, It creates the task. But I cannot access the internet inside of my tasks.
My final goal is to get access to the internet from my tasks in the EC2.

### Environment Details
* The ECS cluster create an EC2 with AMI ID: amzn-ami-2018.03.o-amazon-ecs-optimized (ami-0d2f82a622136a696)
* I have an internet gateway and a NAT gateway in a subnet(Where EC2 is located)
* The rout table in public subnet: 0.0.0.0/0 --> internet_gateway
* The rout table in private subnet: 0.0.0.0/0 --> nat_gateway
* The task definition: 

> {
    "ipcMode": null,
    "executionRoleArn": "arn:aws:iam::783294628224:role/ecsTaskExecutionRole",
    "containerDefinitions": [
        {
            "dnsSearchDomains": null,
            "logConfiguration": {
                "logDriver": "awslogs",
                "options": {
                    "awslogs-group": "/ecs/TEST-Task-Definition",
                    "awslogs-region": "us-west-2",
                    "awslogs-stream-prefix": "ecs"
                }
            },
            "entryPoint": null,
            "portMappings": [
                {
                    "hostPort": 8500,
                    "protocol": "tcp",
                    "containerPort": 8500
                },
                {
                    "hostPort": 8501,
                    "protocol": "tcp",
                    "containerPort": 8501
                }
            ],
            "command": null,
            "linuxParameters": null,
            "cpu": 0,
            "environment": [],
            "resourceRequirements": null,
            "ulimits": null,
            "dnsServers": null,
            "mountPoints": [],
            "workingDirectory": null,
            "secrets": null,
            "dockerSecurityOptions": null,
            "memory": null,
            "memoryReservation": 500,
            "volumesFrom": [],
            "stopTimeout": null,
            "image": "<MY ECR REPOSITORY ADDRESS FOR IMAGE 1>",
            "startTimeout": null,
            "dependsOn": null,
            "disableNetworking": null,
            "interactive": null,
            "healthCheck": null,
            "essential": true,
            "links": null,
            "hostname": null,
            "extraHosts": null,
            "pseudoTerminal": null,
            "user": "root",
            "readonlyRootFilesystem": null,
            "dockerLabels": null,
            "systemControls": null,
            "privileged": true,
            "name": "backend"
        },
        {
            "dnsSearchDomains": null,
            "logConfiguration": {
                "logDriver": "awslogs",
                "options": {
                    "awslogs-group": "/ecs/TEST-Task-Definition",
                    "awslogs-region": "us-west-2",
                    "awslogs-stream-prefix": "ecs"
                }
            },
            "entryPoint": null,
            "portMappings": [
                {
                    "hostPort": 80,
                    "protocol": "tcp",
                    "containerPort": 80
                }
            ],
            "command": null,
            "linuxParameters": null,
            "cpu": 0,
            "environment": [],
            "resourceRequirements": null,
            "ulimits": null,
            "dnsServers": null,
            "mountPoints": [],
            "workingDirectory": null,
            "secrets": null,
            "dockerSecurityOptions": null,
            "memory": null,
            "memoryReservation": 500,
            "volumesFrom": [],
            "stopTimeout": null,
            "image": "<MY ECR REPOSITORY ADDRESS FOR IMAGE 2>",
            "startTimeout": null,
            "dependsOn": null,
            "disableNetworking": null,
            "interactive": null,
            "healthCheck": null,
            "essential": true,
            "links": null,
            "hostname": null,
            "extraHosts": null,
            "pseudoTerminal": null,
            "user": "root",
            "readonlyRootFilesystem": null,
            "dockerLabels": null,
            "systemControls": null,
            "privileged": true,
            "name": "frontend"
        }
    ],
    "memory": null,
    "taskRoleArn": "arn:aws:iam::783294628224:role/ecsTaskExecutionRole",
    "family": "TEST-Task-Definition",
    "pidMode": null,
    "requiresCompatibilities": [
        "EC2"
    ],
    "networkMode": "awsvpc",
    "cpu": null,
    "proxyConfiguration": null,
    "volumes": [],
    "placementConstraints": []
}

**Comment by FernandoMiguel** [comment]
I assume your security group egress is also allowing outbound?

**Comment by mostafafarzane** [comment]
Yes. The security group has HTTP, HTTPS, and SSH inbound and All outbound traffic

**Comment by FernandoMiguel** [comment]
if you want to ssh into the ec2, you need a VPN or jumphost... LB wont probably work with SSH protocol

**Comment by yunhee-l** [comment]
Thank you for reporting - glad you found a fix for your problem. 
I'm going to resolve this as there's no action item from ECS; please feel free to reopen if you have any further questions or concerns.

**Comment by 50bbx** [comment]
@mostafafarzane I have exactly your issue and I am trying to solve as you said, so here is my current setup (which is not working):

- VPC + 1 private subnet + 1 public subnet
- NAT Gateway in the public subnet
- Internet Gateway in the VPC
- EC2 created with ECS-optimized Liunx AMI 2 in the private subnet
- Task in `awsvpc` mode in the private subnet with a security group that is allowing all traffic
- Private subnet has a route table that points to the NAT Gateway (0.0.0.0/0)
- Public subnet has a route table that points to the Internet Gateway (0.0.0.0/0)

I followed [this guide](https://docs.aws.amazon.com/en_pv/vpc/latest/userguide/VPC_Scenario2.html) on how to set up everything.

The only difference I can see is in the task definition: I am using `"ipcMode": "host"` but that's because it is necessary to use Cypress.

Am I doing anything wrong?

**Comment by mostafafarzane** [comment]
@50bbx What is your issue exactly?

**Comment by 50bbx** [comment]
@mostafafarzane my final goal is to get access to the internet inside a task and make http requests work from inside the task

**Comment by twigs67** [comment]
> I finally succeeded to fix my problem. As far as I know, when using `awsvpc` network mode in Task Definition, the tasks(or service) must create in the EC2 subnet. Additionally, if you want your tasks to have access to the internet, you should create a NAT gateway in another subnet which has a default route to Internet Gateway that resides in your VPC. In the task/service/EC2 subnet you have to add a default route to the NAT gateway. The only problem that occurs is that you cannot ssh to your EC2 anymore. If you want to ssh to your EC2, I think you should set up a Load Balancer.

It seems that has been solved. Can anyone shed more light on the correct setup for this? @50bbx @mostafafarzane?

**Comment by Dhruv-Garg79** [comment]
I am stuck at a similar issue.
I am using bridge network mode and I am able to connect if EC2 is in public subnet, but not when it is in private subnet. I already have a NAT gateway as default route for private subnets.

can u guys help @twigs67 @50bbx?

**Comment by harirenumanu** [comment]
> I finally succeeded to fix my problem. As far as I know, when using `awsvpc` network mode in Task Definition, the tasks(or service) must create in the EC2 subnet. Additionally, if you want your tasks to have access to the internet, you should create a NAT gateway in another subnet which has a default route to Internet Gateway that resides in your VPC. In the task/service/EC2 subnet you have to add a default route to the NAT gateway. The only problem that occurs is that you cannot ssh to your EC2 anymore. If you want to ssh to your EC2, I think you should set up a Load Balancer.

I am trying to use endpoints instead of nat gateway is it possible
