### ISSUE TITLE
Discovering host port mapping when host port isn't specified.

### ISSUE THREAD

**Issue by bcwp** [aws/amazon-ecs-agent#198]
If a task definition specifies a containerPort, but no host port, ecs automatically picks a random port on the host and maps it to the specified containerPort. There doesn't seem to be any documented way to discover which port it picked from within the container. This seems like a flaw.

**Comment by euank** [comment]
The `describe-tasks` API call returns a `networkBindings` field specifying container/host ports. Once the container transitions to `RUNNING`, the port assignment should be visible there.

I'll see about getting the documentation here improved.

Thanks for the feedback,
Euan

**Comment by bcwp** [comment]
Hey @euank,

How would you recommend doing running the call from within the container (for registering with service discovery)?

**Comment by euank** [comment]
Unfortunately, there's not a great way to get your dynamic port binding from within the container right now. Having extra information in the environment relates to #3 and that specific item is #151.

A different approach to service registration is to instead have whatever process started the task also wait for it to become available and register it rather than have the container register itself.

**Comment by aaithal** [comment]
Another use-case for #709

**Comment by nick-wellinghoff-sp** [comment]
Is there any update on this?  Is there a better way that has evolved over the last 2 years?

**Comment by richardpen** [comment]
@nick-wellinghoff-sp Thanks for reaching out, our engineer is working on the feature and the PR #913 is almost done. Please track this PR for updates.

Thanks,
Peng

**Comment by samuelkarp** [comment]
This will be supported as part of https://github.com/aws/amazon-ecs-agent/issues/710, which is going out with our next release.

**Comment by samuelkarp** [comment]
We have released [ECS agent v1.15.0](https://github.com/aws/amazon-ecs-agent/releases/tag/v1.15.0), which adds this feature.  Please see [the documentation](http://docs.aws.amazon.com/AmazonECS/latest/developerguide/container-metadata.html) for information on how to use it.

**Comment by miskiw** [comment]
@samuelkarp not sure the ECS v1.15.0 helps in this situation. The "HostPort" value that comes back in the ECS_CONTAINER_METADATA_FILE file is set to "0" (not specified) and not the dynamic port that we are hoping for :-(

**Comment by samuelkarp** [comment]
@miskiw We fixed a few bugs related to that in the [v1.15.2](https://github.com/aws/amazon-ecs-agent/releases/tag/v1.15.2) release.  Can you try that one?

**Comment by miskiw** [comment]
Thanks @samuelkarp ... v1.15.2 does indeed return the dynamic HostPort properly now. Thanks for the quick response... I was just running a slightly older ECS Optimized AMI.
