### ISSUE TITLE
Failed to fetch submodule amazon-vpc-cni-plugins 8b5e552

### ISSUE THREAD

**Issue by itchyny** [aws/amazon-ecs-agent#1981]
### Summary

Commit sha of submodule amazon-vpc-cni-plugins is incorrect.

### Description

go get this module in a clean golang environment fails with the following error.

```
error: no such remote ref 8b5e552209b0009aecf3c60568b5a5041c6342c0
Fetched in submodule path 'amazon-vpc-cni-plugins', but it did not contain 8b5e552209b0009aecf3c60568b5a5041c6342c0. Direct fetching of that commit failed.
package github.com/aws/amazon-ecs-agent: exit status 1
```

### Expected Behavior
I expect go get exits successfully.

### Observed Behavior
go get fails with `Fetched in submodule path 'amazon-vpc-cni-plugins', but it did not contain 8b5e552209b0009aecf3c60568b5a5041c6342c0. Direct fetching of that commit failed.` error.

The commit https://github.com/aws/amazon-vpc-cni-plugins/commit/8b5e552209b0009aecf3c60568b5a5041c6342c0 does not exist in the master branch, while https://github.com/aws/amazon-vpc-cni-plugins/commit/6807d86a894dca8fc011a35c2bb4699de2bb8ed5 looks the correct commit hash.

### Environment Details

- go version go1.12.3 linux/amd64
- macOS 10.14.4
- Docker version 18.09.2, build 6247962

### Supporting Log Snippets

```
 $ docker run -it --rm golang /bin/bash
Unable to find image 'golang:latest' locally
latest: Pulling from library/golang
e79bb959ec00: Pull complete
d4b7902036fe: Pull complete
1b2a72d4e030: Pull complete
d54db43011fd: Pull complete
963c818ebafc: Pull complete
5e4c274d8ea1: Pull complete
8713ed87c86c: Pull complete
Digest: sha256:55f89a93dde69671d902f5c205ff49299cb4dfa3480961773dd8f61696a3aa02
Status: Downloaded newer image for golang:latest

root@93c79f84a444:/go# GO111MODULES=off go get -u github.com/aws/amazon-ecs-agent
# cd /go/src/github.com/aws/amazon-ecs-agent; git submodule update --init --recursive
Submodule 'amazon-ecs-cni-plugins' (https://github.com/aws/amazon-ecs-cni-plugins.git) registered for path 'amazon-ecs-cni-plugins'
Submodule 'amazon-vpc-cni-plugins' (https://github.com/aws/amazon-vpc-cni-plugins.git) registered for path 'amazon-vpc-cni-plugins'
Cloning into '/go/src/github.com/aws/amazon-ecs-agent/amazon-ecs-cni-plugins'...
Cloning into '/go/src/github.com/aws/amazon-ecs-agent/amazon-vpc-cni-plugins'...
error: no such remote ref 8b5e552209b0009aecf3c60568b5a5041c6342c0
Fetched in submodule path 'amazon-vpc-cni-plugins', but it did not contain 8b5e552209b0009aecf3c60568b5a5041c6342c0. Direct fetching of that commit failed.
package github.com/aws/amazon-ecs-agent: exit status 1
root@93c79f84a444:/go#
```

**Comment by itchyny** [comment]
I found the CI log at https://travis-ci.org/aws/amazon-ecs-agent/jobs/512730893 and the commit hash  8b5e552209b0009aecf3c60568b5a5041c6342c0 did exist 13 days ago.
Ping @ofiliz as the author of the latest commit of amazon-vpc-cni-plugins.

**Comment by ofiliz** [comment]
Thanks for reporting. That was my mistake. I restored the amazon-vpc-cni-plugins repo to its original state.

**Comment by itchyny** [comment]
Thank you.
