### ISSUE TITLE
No tag/release for 1.27.0

### ISSUE THREAD

**Issue by bacoboy** [aws/amazon-ecs-agent#1992]
It appears `1.27.0` has been [released to dockerhub](https://hub.docker.com/r/amazon/amazon-ecs-agent/tags), but there is no [tag/release in github](https://github.com/aws/amazon-ecs-agent/releases) (so I didn't get a notification).

Something in the build toolchain broken down.  Please fix for posterity.

**Comment by petderek** [comment]
@bacoboy We have to publish updates in several places before we are finished with a release. Generally, publishing the tag to Github is one of the last things we do since it notifies folks subscribed to our repo.

Sorry for the confusion! I'll close this out once everything is buttoned up.

**Comment by bacoboy** [comment]
Yea, when the AWS console and documentation said my agents were out of date, seemed odd. Still seems if you are at the point that they are deployed in production, the release notes/tag should already be there.  

Might want to reorder the release steps to avoid confusion next time...  it isn't like they are set in stone if they need an adjustment...

Thanks.

**Comment by petderek** [comment]
Our release has been finished: https://github.com/aws/amazon-ecs-agent/releases/tag/v1.27.0
