### ISSUE TITLE
Docker --log-driver=awslogs errors with CloudWatch API sequence tokens

### ISSUE THREAD

**Issue by IPvFletch** [aws/amazon-ecs-agent#200]
Ref: https://github.com/docker/docker/pull/15495
Ref: https://github.com/aws/amazon-ecs-agent/issues/9

I'm using the experimental `awslogs` log-driver for `docker` available in `master`, i.e. `docker-1.9.0-dev` from today's build.

```
ERRO[1839] Failed to put log events                      errorCode=InvalidSequenceTokenException logGroupName=awslogs logStreamName=apps message=The given sequenceToken is invalid. The next expected sequenceToken is: 49540112654804690997104352997714685391863631165190586194 origError=<nil>
INFO[2031] GET /v1.17/version                           
ERRO[2033] Failed to put log events                      errorCode=InvalidSequenceTokenException logGroupName=awslogs logStreamName=apps message=The given sequenceToken is invalid. The next expected sequenceToken is: 49540112654804690997104353009076170244601927144195506002 origError=<nil>
```

There's a bunch of these in my docker daemon output.. They show up when new logs are generated, yet "most, possibly all" of the logs make it to CloudWatch..

Command to run docker daemon:
```
AWS_ACCESS_KEY_ID=REDACTED AWS_SECRET_ACCESS_KEY=REDACTED ./docker-1.9.0-dev daemon --log-driver=awslogs --log-opt awslogs-region=us-east-1 --log-opt awslogs-group=awslogs --log-opt awslogs-stream=apps
```

I'm using ECS to run the containers, but I don't think that matters really.

**Comment by samuelkarp** [comment]
You should not set `--log-opt awslogs-stream=apps` on the daemon.  I have a note in the [documentation](https://github.com/docker/docker/blob/3effe484e6f572298d0c3490517f57391617aa51/docs/reference/logging/awslogs.md) about this:

> Note: Log streams within a given log group should only be used by one container at a time. Using the same log stream for multiple containers concurrently can cause reduced logging performance.

The log stream should be specified per-container, or left unspecified (it will use the container ID).  CloudWatch Logs expects a stream to be from a single source rather than multiple, concurrent sources.  The logging driver will attempt to submit log events (lines) even under this condition (it extracts the next sequence token from the error message), but it will realistically have reduced performance or drop lines (as you've noticed).

**Comment by samuelkarp** [comment]
Oh also: since you mentioned that you're running containers through ECS, you should be able to leave the credentials unspecified as they will be retrieved from the EC2 instance profile you specified when launching the instance.

**Comment by IPvFletch** [comment]
How does it get them from the EC2 instance? You mean the ec2IamRole?

I get the stream comments.. so ideally we want to run these --log-opt per 'run' and not for the daemon?  But, with ECS, there is no way to control the run cmd-line args..  :(

**Comment by samuelkarp** [comment]
Yes, it can get credentials for the IAM roles on EC2: http://docs.aws.amazon.com/AWSEC2/latest/UserGuide/iam-roles-for-amazon-ec2.html.

**Comment by IPvFletch** [comment]
Ok, thanks.

So you are confirming this is designed only to be used with individual streams:container (1:1) mapping and not with the daemon?

**Comment by samuelkarp** [comment]
You can set the other options (`awslogs-region` and `awslogs-group`) on the daemon.  `awslogs-stream` is not a required option; if unspecified (left off the daemon and not specified during `docker run` or through the remote API) the logging driver will use Docker's container ID as the log stream name.  This will create a separate stream per container inside your log group.

**Comment by samuelkarp** [comment]
@IPvFletch, I'm going to close this issue for now.  Please feel free to re-open the issue if you continue to run into problems or just have general questions about the logging driver.

**Comment by IPvFletch** [comment]
No problem, thanks for the clarification on the stream usage per daemon/per run. I think we are in good shape if we want to use this, provided we can separate stream per cid, and group per host. Thanks again for taking the initiative on this, I got something similar working with logstash this morning when I ran into yours, so it's nice to have options!
