### ISSUE TITLE
Agent reports incorrect capabilities on windows

### ISSUE THREAD

**Issue by petderek** [aws/amazon-ecs-agent#2035]
### Summary
Agent running on windows reports capabilities that won't work on windows.

### Description
Following capabilites aren't supported on windows:

ecs.capability.aws-appmesh
ecs.capability.pid-ipc-namespace-sharing
ecs.capability.task-eia

**Comment by petderek** [comment]
We should also double check this:

ecs.capability.docker-plugin.local

Can't remember if docker uses the 'local' plugin or a different code path for windows volumes.

**Comment by yunhee-l** [comment]
Windows does not support Docker plugins, or at least it didn't at the time of Docker Volume Plugin project. Only docker volume supported on Windows is local.

**Comment by petderek** [comment]
> Only docker volume supported on Windows is local
sweet, so thats probably fine to leave in.

**Comment by mssrivas** [comment]
Implemented as part of pull #2070
