### ISSUE TITLE
High density awsvpc meaning

### ISSUE THREAD

**Issue by jyapayne** [aws/amazon-ecs-agent#2047]
### Summary

In the recently released version 1.28.0, you list a feature called "high density awsvpc tasks support". Does this mean that the number of tasks can exceed the number of ENIs now?

**Comment by ellenthsu** [comment]
Hi - this is a project that we are actively working on, please feel free to follow our updates in our roadmap, thanks!
https://github.com/aws/containers-roadmap/issues/7

**Comment by fenxiong** [comment]
FYI please see this comment for details - https://github.com/aws/containers-roadmap/issues/7#issuecomment-493263979. Thanks.
