### ISSUE TITLE
ECS_AVAILABLE_LOGGING_DRIVERS documentation is incorrect

### ISSUE THREAD

**Issue by SleeperSmith** [aws/amazon-ecs-agent#2063]
### Summary
https://github.com/aws/amazon-ecs-agent#on-other-linux-amis-when-awsvpc-networking-mode-is-enabled

value for ECS_AVAILABLE_LOGGING_DRIVERS needs to be single quoted.
^- I was getting invalid value, expected json array in the log.

### Description
--env ECS_AVAILABLE_LOGGING_DRIVERS=["json-file","awslogs","syslog","none"] \
needs to be changed to
--env ECS_AVAILABLE_LOGGING_DRIVERS='["json-file","awslogs","syslog","none"]' \
for me on ubuntu. Note the extra single quote surrounding the value.

### Expected Behavior
When provisioning an ECS Service with awslogs driver, it should provision successfully

### Observed Behavior
When provisioning an ECS Service with awslogs driver, it complains no instance meet required capability.

**Comment by yunhee-l** [comment]
Thank you for reporting this documentation error. We have fixed it in https://github.com/aws/amazon-ecs-agent/pull/2066.

**Comment by yunhee-l** [comment]
PR pushed, and fix is in dev branch: https://github.com/aws/amazon-ecs-agent/tree/dev 
With next release this fix will be merged into master branch. 
Resolving.
