### ISSUE TITLE
ECS problem with cleaning docker images

### ISSUE THREAD

**Issue by ipeacocks** [aws/amazon-ecs-agent#2069]
I would like to turn off automatic removing of old unused images on EC2 ECS instance.
After reading this doc https://docs.aws.amazon.com/en_us/AmazonECS/latest/developerguide/automated_image_cleanup.html I've added to `/etc/ecs/ecs.config`:
```
ECS_DISABLE_IMAGE_CLEANUP=true
```
After that l've restarted ecs-agent service/container:
```
sudo stop ecs
sudo start ecs
```
Seems easy. But no. For some reason ecs-agent still removes images. But why? Is something bad with AWS?

Thanks

**Comment by sychevsky** [comment]
this behavior also reproduced with this ecs config

```
ECS_DISABLE_IMAGE_CLEANUP=true
ECS_ENABLE_UNTRACKED_IMAGE_CLEANUP=false
ECS_NUM_IMAGES_DELETE_PER_CYCLE=0
ECS_LOGLEVEL=info
ECS_IMAGE_MINIMUM_CLEANUP_AGE=1000h
```

> "Version":"Amazon ECS Agent - v1.27.0 (aabe65ee)"

**Comment by yunhee-l** [comment]
Thank you for reporting this issue. We are looking into this issue, but for quicker diagnosis do you mind sending the debug level agent logs to yhlee _at_ amazon _dot_ com please?

**Comment by ipeacocks** [comment]
It was my bad. Actually it was not a ECS problem. Sorry for that.
