### ISSUE TITLE
ECS service stuck in PENDING state

### ISSUE THREAD

**Issue by marceldegraaf** [aws/amazon-ecs-agent#208]
I've defined an ECS service based on [this task definition](https://gist.github.com/marceldegraaf/ab21671ee2c641765b55), but the service never leaves the `PENDING` state.

However, the two Docker containers belonging to the task definitions are running on one of the ECS container instances, and their respective applications are working and are reachable.

The only Event in the Service -> Events tab is:
> service s-registry has started 1 tasks: task e22de19c-ef2d-48e6-a420-f9f997c15231.

Am I missing something in the service definition, or is there a bug in the ECS agent or the upstream ECS scheduler?

**Comment by euank** [comment]
This could be an issue with the Agent. Can you check if there's anything interesting in the Agent's logs? They should be located at `/var/log/ecs/ecs-agent.log*` (or via `docker logs ecs-agent`).

It would also be worth double checking what the Agent thinks that status of the task is (`curl 127.0.0.1:51678/v1/tasks`) and seeing if, after collecting that information, restarting the Agent 'unsticks' it.

Best,
Euan

**Comment by marceldegraaf** [comment]
Hi @euank, thanks for your reply. I'll check both those things tomorrow and report back here with the result. Thanks!

**Comment by marceldegraaf** [comment]
The agent log explained what was wrong: my IAM instance profile was missing the `ecs:SubmitContainerStateChange` and the `ecs:SubmitTaskStateChange` permissions.

After correcting that, both tasks belonging to the task definition are now in a `RUNNING` state.
