### ISSUE TITLE
Volume path normalization breaks Windows named pipes

### ISSUE THREAD

**Issue by plukevdh** [aws/amazon-ecs-agent#2086]
### Summary

Since Docker supports Windows named pipes and AWS [now supports 18.09](https://aws.amazon.com/about-aws/whats-new/2019/06/amazon-ecs-support-windows-server-2019-containers-generally-available/) images for ECS, I would love to be able to use named pipes to avoid running Docker-in-Docker when using Windows. 

### Description

Mounting the `\\.\pipe\docker_engine` works when using the Docker API/CLI in the AWS-provided 18.09 images (which is all I have tested atm). However, I have been unable to create a ECS task that accomplishes the same thing.

I have a task definition for a Windows environment (relevant details only):

```json
{
  "containerDefinitions": [
    {
      "mountPoints": [
        {
          "containerPath": "\\\\.\\pipe\\docker_engine",
          "sourceVolume": "docker_sock"
        }
      ],
    },
  ...
  "volumes": [
    {
      "name": "docker_sock",
      "host": {
        "sourcePath": "\\\\.\\pipe\\docker_enginer"
      },
      "dockerVolumeConfiguration": null
    }
  ]
}
```

Attempting to run a task with the above definition results in an error (see observed behavior below). This is because of the path normalization for volume and mount point paths: https://github.com/aws/amazon-ecs-agent/blob/master/agent/api/task/task_windows.go#L83

A simple example of running `filepath.Clean()` in Windows exhibits this same behavior:

```
package main

import (
	"fmt"
	"path/filepath"
)

func main() {
  raw := "\\\\.\\pipe\\docker_engine"
  clean := filepath.Clean(lower)
  
fmt.Println("Clean: ", clean)
}
```

Prints out `Clean:  \pipe\docker_engine` which is exactly what occurs in the output in the error message below. I'm willing to write tests/code for this, but I'm unsure what the best way to test for this case is without adding significant complexity. 

### Expected Behavior

Task successfully transitions into `RUNNING` state with named pipes successfully mounted from host to container.

### Observed Behavior

The following error occurs when the task attempts to start:

```json
"ApplyingError": {
                "error": "Error response from daemon: invalid volume specification: '\\pipe\\docker_enginer:\\pipe\\docker_engine'",
                "name": "CannotCreateContainerError"
              }
...
```

Note how it mangles the path.

### Environment Details
Windows version: 18.09.4
ECS Agent version: 1.27.0

Docker version:
```
Client: Docker Engine - Enterprise
 Version:           18.09.4
 API version:       1.39
 Go version:        go1.10.8
 Git commit:        c3516c43ef
 Built:             03/27/2019 18:22:15
 OS/Arch:           windows/amd64
 Experimental:      false

Server: Docker Engine - Enterprise
 Engine:
  Version:          18.09.4
  API version:      1.39 (minimum version 1.24)
  Go version:       go1.10.8
  Git commit:       c3516c43ef
  Built:            03/27/2019 18:20:29
  OS/Arch:          windows/amd64
  Experimental:     false
```

This is utilizing the standard AWS AMI: `Windows_Server-2019-English-Full-ECS_Optimized-2019.05.10 (ami-09a6b4fc9786621ef)` (which is the us-west-2 image).

**Comment by yumex93** [comment]
The pr to fix this problem is here: https://github.com/aws/amazon-ecs-agent/pull/2128. Waiting for it to be updated and we will merge the fix.
