### ISSUE TITLE
Error when retrieving credentials from container-role

### ISSUE THREAD

**Issue by alanblake** [aws/amazon-ecs-agent#2126]
### Summary
Error when retrieving credentials from container-role:

### Description
ecs tasks are failing  to run after updating ecs-agent from 1.25.2 -> 1.29

Containers report the following errors.

Error when retrieving credentials from container-role: Error retrieving metadata: Received error when attempting to retrieve ECS metadata: ('Connection aborted.', error(104, 'Connection reset by peer'))

Error when retrieving credentials from container-role: Error retrieving metadata: Received error when attempting to retrieve ECS metadata: ('Connection aborted.', BadStatusLine("''",))

### Environment Details
docker info

Containers: 146
 Running: 2
 Paused: 0
 Stopped: 144
Images: 5
Server Version: 18.06.1-ce
Storage Driver: aufs
 Root Dir: /mnt/docker/aufs
 Backing Filesystem: extfs
 Dirs: 341
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 468a545b9edcd5932818eb9de8e72413e616e86e
runc version: 69663f0bd4b60df09991c08812a60108003fa340
init version: fec3683
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.4.0-154-generic
Operating System: Ubuntu 16.04.6 LTS
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 3.492GiB
Name: ip-
ID: NHRN:IUON:SC7P:YBN7:I2LK:JTVO:STMV:4SXS:CIIX:ALFM:K6UD:7EFM
Docker Root Dir: /mnt/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

WARNING: No swap limit support

curl http://localhost:51678/v1/metadata
{"Cluster":"cluster","ContainerInstanceArn":"arn:aws:ecs:us-east-1::container-instance/fd57a58c-35f4-4a8e-a983-217e7b0b7865","Version":"Amazon ECS Agent - v1.29.0 (a190a73f)"}

**Comment by sharanyad** [comment]
@alanblake sorry you're facing this issue. Could you please send me the ECS agent logs that are DEBUG enabled, when this issue occurred to sharanyd at amazon.com? You can collect logs using the [logs collector](https://docs.aws.amazon.com/AmazonECS/latest/developerguide/ecs-logs-collector.html).

**Comment by yumex93** [comment]
Close the issue for now. Feel free to reopen it when you have the logs ready.

**Comment by Jim61C** [comment]
Hi, I am encountering the same error, would you pls confirm how this has been resolved?
