### ISSUE TITLE
Reevaluate 'create' timeout

### ISSUE THREAD

**Issue by euank** [aws/amazon-ecs-agent#214]
Currently the timeout the Agent enforces for `docker create` is 1 minute.

For the below reasons, we should collect some data and reconsider this timeout.

When under unusually heavy load, Docker's `create` times increase drastically, including well past that timeout. I've also got an issue on their end: https://github.com/docker/docker/issues/15802

It's possible that this timeout could also be brushed against in more normal operation however. [This](https://forums.aws.amazon.com/thread.jspa?messageID=677146) forum post shows an instance of create taking ~70 seconds in normal operation while using an older version of Docker (1.6.2 I think).

Other possible resolutions to this, other than picking a bigger number, include throttling calls to Docker's API. One particularly good approach here could be to observe create times and backoff proportional to their increase, though that won't be trivial to implement.

**Comment by samuelkarp** [comment]
This should have been closed with our [v1.6.0 release](https://github.com/aws/amazon-ecs-agent/releases/tag/v1.6.0).  Closing now.
