### ISSUE TITLE
ECS Service reaches steady state before container healthcheck pass

### ISSUE THREAD

**Issue by mailjunze** [aws/amazon-ecs-agent#2143]
### Summary

ECS Service reaches steady state before container healthcheck pass.  This results in ECS update getting deployed via cloudformation successfully, However, the tasks go into restart loop after container health check fails rendering whole ECS service unstable. 

### Description

when we  perform an update via cloudformation to ECS. Cloudformation waits for "steady state" event to mark the update successful. "Service xxxxxxxx has reached a steady state." I can see the ECS service reaches the steady state and then the health checks fail, Which results cloud-formation deployment successfully but rendering  ECS service unstable. 

### Expected Behavior

ECS Service should reach  steady state after container healthcheck pass
### Observed Behavior
ECS Service reaches steady state before container healthcheck pass

**Comment by shubham2892** [comment]
@mailjunze 

Could you please mail me the following information at shugy at amazon dot com to help debug this issue -- 
1) Which version of Agent and Docker are you running? 
2) How often do you observe this error? 
3) Date/time of when the issue occurred, and ECS agent's configuration and debug level log files following instructions here: https://docs.aws.amazon.com/AmazonECS/latest/developerguide/ecs-logs-collector.html

**Comment by yumex93** [comment]
Haven't got back the requested information. Will close the issue for now. Feel free to reopen it when you have them ready.

**Comment by robertoandrade** [comment]
Is there an easier way to check if the ECS service has reached the "steady" (not "stable") state other than constantly querying the last events and looking for the word "steady" in there?

**Comment by schmohlio** [comment]
we are seeing this issue and it's affecting our services. Is there a way to escalate?
