### ISSUE TITLE
ECS Agent v1.29.1 can not connect to the cluster

### ISSUE THREAD

**Issue by sunshine69** [aws/amazon-ecs-agent#2146]
### Summary

The agent can not connect to the cluster

### Description

Log

2019-07-31T05:00:48Z [ERROR] Unable to register as a container instance with ECS: ClientException: Cluster not found.
	status code: 400, request id: d700ab09-7b4a-4ed3-bdcb-4081a11eea57
2019-07-31T05:00:48Z [ERROR] Error registering: ClientException: Cluster not found.
	status code: 400, request id: d700ab09-7b4a-4ed3-bdcb-4081a11eea57
2019-07-31T05:01:14Z [INFO] Loading configuration
2019-07-31T05:01:14Z [INFO] Image excluded from cleanup: amazon/amazon-ecs-agent:latest
2019-07-31T05:01:14Z [INFO] Image excluded from cleanup: amazon/amazon-ecs-pause:0.1.0
2019-07-31T05:01:14Z [INFO] Amazon ECS agent Version: 1.29.1, Commit: f95f731b
2019-07-31T05:01:14Z [INFO] Creating root ecs cgroup: /ecs
2019-07-31T05:01:14Z [INFO] Creating cgroup /ecs
2019-07-31T05:01:14Z [INFO] Loading state! module="statemanager"
2019-07-31T05:01:14Z [INFO] Event stream ContainerChange start listening...
2019-07-31T05:01:14Z [INFO] Registering Instance with ECS
2019-07-31T05:01:14Z [INFO] Remaining mem: 1991
2019-07-31T05:01:14Z [ERROR] Unable to register as a container instance with ECS: ClientException: Cluster not found.

### Expected Behavior

It can connect the cluster.

### Environment Details

The same ec2 all existing config, if I downgrade to v1.29.0 (pulling the docker image) and then edit the systemd unit file to use it and restart - it can connect to the cluster fine.

**Comment by cocooma** [comment]
What is the docker version of docker is on the ec2 instance? I have the same issue on docker 19.03 but it works on 18.06

**Comment by sunshine69** [comment]
ubuntu@vpc-20-int-errcd-ecs-ecs-10-20-124-162:~$ docker --version
Docker version 19.03.1, build 74b1e89
ubuntu@vpc-20-int-errcd-ecs-ecs-10-20-124-162:~$ 

However not sure what is the compatibility is, or it id docker bug or ecs-agent bug? I am hesitant to downgrade docker if not confirmed that it is docker bug.

**Comment by fenxiong** [comment]
Hi,
It looks like the agent was trying to register to a cluster named "CHANGEME". Are you sure that's intended? Does that cluster exist?

**Comment by sunshine69** [comment]
Hi,

Where do you get the `CHANGEME` name? This cluster does not exists. I read again and again my log snippet and not seeing anything like `CHANGEME` so very curious at the moment.

And the same config as I said (cat /etc/ecs/ecs.config) it looks all right. Just pull down the older version v1.29.0 and run, it works.

**Comment by sunshine69** [comment]
> What is the docker version of docker is on the ec2 instance? I have the same issue on docker 19.03 but it works on 18.09.8~3-0

I just discover that I actually run the dockerd version `5:18.09.6~3-0~ubuntu-bionic`. The version output from the command `docker --version` is the docker cli client which happened to be different.

I need to fix my deployment code to be consistent between the docker d and client, however it shows that the docker server is actually version 18.09.

Thus it might be not docker at all.

**Comment by fenxiong** [comment]
> Hi,
> 
> Where do you get the `CHANGEME` name? This cluster does not exists. I read again and again my log snippet and not seeing anything like `CHANGEME` so very curious at the moment.
> 
> And the same config as I said (cat /etc/ecs/ecs.config) it looks all right. Just pull down the older version v1.29.0 and run, it works.

I saw the name in our service's logs. Can you enable debug level logs (i.e. add ECS_LOGLEVEL=debug to /etc/ecs/ecs.config) and launch an agent with version 1.29.1 again, and if you still have the same error, collect the logs with [ecs-log-collector](https://docs.aws.amazon.com/AmazonECS/latest/developerguide/ecs-logs-collector.html) and send them to fenxiong AT amazon.com? thanks.

**Comment by sunshine69** [comment]
Hi there,

In deed today I recreate the whole things again and spot out that my config has `CHANGEME` in the cluster - not sure why the templating system works with old version and not new but it is my problems.

Adjusting config and restart it seems to work

Sorry to waste your time but it is really strange at my side.

**Comment by sunshine69** [comment]
Hi,

Just for some more information. It seems to be the ecs-agent service startup. At build time we have the service but when we start to launch we adjust the config in the userdata section and the config is right. But the ecs-agent service docker container is already started and using old config somehow.

**Comment by shubham2892** [comment]
@sunshine69 You might need to restart `ecs` service for it to use the new configuration.

**Comment by BarakBD-Globality** [comment]
We just had the same issue - wrong cluster name in ecs config.
Thanks!

**Comment by adampblack** [comment]
Just had this issue on an ec2 instance.

--
Firstly

`docker ps -a`

`docker logs [CONTAINER_ID]`

I got the message
Cannot allocate memory: fork: Unable to fork new process

I stopped the instance, increased the size, started it again.

--
Remove the ECS agent configuration files
`rm -r /var/lib/ecs/data`

`sudo reboot`

--

Deleted the service and created it again.

Works fine now.
