### ISSUE TITLE
Container stuck in PENDING status when dependent on another container which exits without an exit code.

### ISSUE THREAD

**Issue by shubham2892** [aws/amazon-ecs-agent#2152]
### Summary

If we have two containers, A and B, where container B dependsOn on container A to be SUCCESS to run, If container A stops without any exit code then the container B is stuck in pending state even when startTimeout is reached. Ideally, Container B should stop when the startTimeout is reached. 

### Description
In cases where the task has dependencies between the containers, let's say container A depends on container B, if the container B crashes with no exit code, container A will stay as PENDING for hours until the task be killed.

This is the test case used to reproduce the issue:

```json
{

	"containerDefinitions": [

		{

			"name": "container-A",

			"memoryReservation": 128,

			"image": "alpine",

			"essential": false,

			"command": [

				"A=$(cat /dev/urandom)"

			]

		},

		{

			"name": "container-B",

			"memoryReservation": 128,

			"image": "nginx",

			"essential": true,

			"dependsOn": [

				{

					"containerName": "container-A",

					"condition": "SUCCESS"

				}

			]

		}

	],

	"family": "test-dependency",

	"requiresCompatibilities": [

		"EC2"

	]

}
```

Agent Version used - 1.29.1

The container "container-A" will fail because the "command" property is incorrectly defined. In the ECS console, the container (container-A) status will be: STOPPED (CannotStartContainerError: Error response from dae)

The container "container-B" will get stuck PENDING state.

### Expected Behavior
Container B should stop when the startTimeout is reached. 

### Observed Behavior
Container B gets stuck in pending state. 

### Environment Details
Agent Version - 1.29.1

**Comment by joehoyle** [comment]
@shubham2892 did you resolve this?

**Comment by fierlion** [comment]
We're currently looking into this issue -- please follow the updates in [#2350](https://github.com/aws/amazon-ecs-agent/issues/2350) above.

And thank you for the clear steps to repro.  This is very helpful.

**Comment by fierlion** [comment]
a quick note:  I did test your scenario and variations on it.  
using `"command": [ "/bin/bash", "A=$(cat /dev/urandom)"]` I am getting a container exit code of 137, which is handled.  I'm still working to discover a neat way to kill a container and not return an exit code, ie repro.

Also I see that you mention using `startTimeout` -- I'd appreciate steps to repro how you're seeing the dependent container not obey the startTimeout set on it.  The `startTimeout` parameter is meant to be the mechanism for handling these edge cases where a container gets in an unknown state.
