### ISSUE TITLE
Cannot find URL for ECS Service

### ISSUE THREAD

**Issue by ORESoftware** [aws/amazon-ecs-agent#2155]
Not sure where to file this ticket. This is a UI bug / missing feature. Maybe I am confusing EKS with ECS. But in any case, where can I find the URL for the service? There is a load balancer associated with the service, since I create the LB. How come in the UI there is no easy way to find the LB or the URL/public dns for the associated LB?

<kbd>
<img width="1649" alt="Screen Shot 2019-08-06 at 5 02 43 PM" src="https://user-images.githubusercontent.com/11139560/62585165-48457100-b86c-11e9-9bf7-f068fae9de74.png">
</kbd>

----

Please move this ticket to the right repo, as this is certainly the wrong one.

**Comment by shubham2892** [comment]
@ORESoftware I assume this is related to #2157 , closing this too.
