### ISSUE TITLE
How to remove task from service

### ISSUE THREAD

**Issue by ORESoftware** [aws/amazon-ecs-agent#2162]
Sorry to bug you on here but I am coming here out of desperation. I have this question on StackOverlow:

https://stackoverflow.com/questions/57420142/delete-ecs-task-for-old-revision-only-use-new-revision

My workflow is currently a nightmare - in order to create a new task, and stop an existing one, I have to create a new service, which is painstaking. Instead, what I want to do is remove an existing task from a service and add a new task definition, only running the new task definition, not the old one. How can I accomplish this?

**Comment by ORESoftware** [comment]
I can deregister the task X, upon a new release, but what if I want roll-back to that task X?

**Comment by shubham2892** [comment]
@ORESoftware To clarify, you want to register the task again, after deregistering it?

**Comment by ORESoftware** [comment]
Yes, it's possible that we would want to roll-back to that task, we just don't want it currently running on the service

**Comment by FernandoMiguel** [comment]
@ORESoftware you can update the service to run whatever version of the task definition you want.
You can even have multiple services, each using different task definition versions

**Comment by yumex93** [comment]
Yeah. Update service would help you. The [doc](https://docs.aws.amazon.com/AmazonECS/latest/APIReference/API_UpdateService.html) here has more details about what parameters can be passed in for this API.
