### ISSUE TITLE
Upgrade to Docker 1.8.x

### ISSUE THREAD

**Issue by lox** [aws/amazon-ecs-agent#221]
It seems like the amazon-ecs-agent is relying on Docker 1.6.2 (although recommends 1.7.1??). 

Are there any roadblocks to upgrading to a more recent version?

**Comment by samuelkarp** [comment]
Hi @lox, where are you seeing a reliance on Docker 1.6.2?  The Agent should work well with Docker 1.5.0 through Docker 1.7.1.  I'd expect that it will work fine with Docker 1.8.2 as well, but we have not completed testing with that version.

**Comment by lox** [comment]
```
ubuntu@ip-172-31-27-102:~$ journalctl -f -u ecs-agent
-- Logs begin at Wed 2015-10-07 03:32:25 UTC. --
Oct 07 03:48:13 ip-172-31-27-102 systemd[1]: Failed to start Amazon ECS Agent.
Oct 07 03:48:13 ip-172-31-27-102 systemd[1]: Unit ecs-agent.service entered failed state.
Oct 07 03:48:13 ip-172-31-27-102 systemd[1]: ecs-agent.service failed.
Oct 07 03:48:23 ip-172-31-27-102 systemd[1]: ecs-agent.service holdoff time over, scheduling restart.
Oct 07 03:48:23 ip-172-31-27-102 systemd[1]: Starting Amazon ECS Agent...
Oct 07 03:48:23 ip-172-31-27-102 systemd-docker[1644]: 2015/10/07 03:48:23 API error (400): client is too old, minimum supported API version is 1.12, please upgrade your client to a newer version
Oct 07 03:48:23 ip-172-31-27-102 systemd[1]: ecs-agent.service: main process exited, code=exited, status=1/FAILURE

ubuntu@ip-172-31-27-102:~$ docker --version
Docker version 1.8.2, build 0a8c2e3
```

In terms of the dependency, I was just talking about the fact that the docker 1.6.2 libraries are linked against. Trying running it from source now.

**Comment by lox** [comment]
Ugh, apologies, this is a systemd-docker issue. https://github.com/ibuildthecloud/systemd-docker/issues/33
