### ISSUE TITLE
tmpfs in Task Definition doesn't support unlimited/soft limits; denies placement

### ISSUE THREAD

**Issue by diablodale** [aws/amazon-ecs-agent#2226]
### Summary

ECS denies support for `tmpfs` of unbounded size `size: 0`. And questionably uses tmpfs `size` in placement choices. Submitting a task definition to ECS with `tmpfs.size: 0` results in a failure with statuscode=400 and error

```
ClientException: The container has an invalid tmpfs size value specified. It must be a non-zero, non-negative integer.
```

### Description

This ECS limitation forbids usage long supported in Linux and Docker's engine for flexible container creation. This limits ECS container usage and placement.

When a customer wants a hard size *and* for placement to use that hard size, then `size: 400` can be specified. ECS supports this today.

When a customer wants one or _several_ tmpfs volumes on a container, they are forbidden from specifying `size: 0`. Even though this is technically supported by Docker and Linux.

This is all implemented with the typical Linux `tmpfs` filesystem. It supports the `size` mount option. This option specifies the _upper/hard limit_ of data that can be stored. *However*, it does not pre-allocate that hard limit. Instead, the actual memory use by tmpfs is only that consumed by the files stored in the filesystem.

As customers, like me, move to using **read-only** docker containers, it is important to have rich-support for tmpfs. The native tmpfs pooling of memory facilitates this. However, the ECS forbid of this, almost kills such flexible usage since it questionably uses `tmpfs.size` values in placement and at the same time doesn't allow `size: 0`.

### Expected Behavior

No error. And for the containers to be created with listed `tmpfs` filessystems with no bound to those tmpfs sizes.

### Observed Behavior

```
ClientException: The container has an invalid tmpfs size value specified. It must be a non-zero, non-negative integer.
```

### Environment Details

```
Server Version: 18.06.1-ce
Kernel Version: 4.19.72-25.58.amzn2.x86_64
Operating System: Amazon Linux 2
Amazon ECS Agent - v1.31.0 (9715741e)
```

### Related

https://github.com/aws/amazon-ecs-agent/issues/469

**Comment by adnxn** [comment]
>  uses tmpfs.size values in placement and at the same time doesn't allow size: 0.

we do not plan to support the unbounded case because ecs uses this for resource accounting and placement.
