### ISSUE TITLE
FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory

### ISSUE THREAD

**Issue by jayproulx** [aws/amazon-ecs-agent#2231]
### Summary
I'm running a Node.js workload and part way through I'm receiving the following error.

    FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory

### Description

The ECS Task is running in Fargate, I've assigned the process .25 CPU (256 in CloudFormation) and 1024 memory.   

The application runs until the following error occurs (as above):

    FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory

I'm not convinced the rest of the stack trace is of much relevance, mostly complaining that it tried a couple of times to GC and failed and ran OOM.

On first execution, I had allocated 512 memory, ran into this issue, then bumped it up to 1024.  I'm watching the execution in a CloudWatch dashboard, but I'm clearly not seeing an OOM scenario here:

![image](https://user-images.githubusercontent.com/157145/66341560-8f57ed00-e915-11e9-9d4d-02027ddb7bc7.png)

Docker starts the node workload with

    CMD ["node", "./myapp.js"]

I'm considering adding a `--max-old-space-size` argument but it seems unnecessary and I'm wondering if there are some other constraints being imposed here.  This image runs without issue locally.

### Expected Behavior

Shouldn't be running out of memory

### Observed Behavior

Is running out of memory

### Environment Details
Fargate
CPU .25
Memory 1024

**Comment by jayproulx** [comment]
Closing this one, sorry about that, watched the execution of my container with `docker stats` and memory usage spikes significantly during execution and settles back down.

**Comment by ziyaaktas** [comment]
> Closing this one, sorry about that, watched the execution of my container with `docker stats` and memory usage spikes significantly during execution and settles back down.

Did you actually have a fix for this?  Having the same problem.
