### ISSUE TITLE
Fargate unable to pull image from ECR VPC endpoint

### ISSUE THREAD

**Issue by kazeshini178** [aws/amazon-ecs-agent#2235]
### Summary
Image for Fargate task fail to pull from ECR through VPC Endpoint

### Description
Fargate task fail with the following error:
`CannotPullContainerError: Error response from daemon: Get https://XXXXXXXXXXX.dkr.ecr.eu-west-1.amazonaws.com/v2/: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)`

After creating and configuring the following endpoints 
- com.amazonaws.eu-west-1.s3 (Gateway)
- com.amazonaws.eu-west-1.ecr.api (Interface)
- com.amazonaws.eu-west-1.ecr.dkr (Interface)
- com.amazonaws.eu-west-1.logs (Interface)

We are unable to pull images. The bizarre part is after first setup up these endpoint is the images where able to be pulled, though once the task was restarted images failed to pull.

I've for a issues suggesting using a NAT Gateway with a Public IP, but there is also AWS documentation that mentions not needing a NAT when using a VPC Endpoint(s).

Also all Fargate services are running in private subnets.

### Expected Behavior
Images to pull from ECR through VPC Endpoints.

### Observed Behavior
Images fail to pull contentiously, regardless on what policy permissions I add and rules i have on the security group

**Comment by serenata-keith-mifsud** [comment]
Hi @kazeshini178, did you have to create a second VPC to sort your issue, or you managed to have one VPC working with both the AmazonProvidedDNS and the on premises ones?

**Comment by kazeshini178** [comment]
Hi @serenata-keith-mifsud 
We ended up removing the AmazonProvidedDNS from our Options set. It ended up preventing us for communicating back on premise.
We then white-listed the "Public" endpoints that AWS uses for ECR, S3, etc on our Egress VPC.

**Comment by serenata-keith-mifsud** [comment]
Thank you @kazeshini178 for replying. Do you mind explaining what do you mean with white-listing the endpoints? 

We have the 4 endpoints created (S3, ECR & Logs) and mapped the interfaces to our private subnets. However I'm not sure if we need to do something else with these endpoints
