### ISSUE TITLE
ENI trunking is not working for EC2 Instances launched in a shared VPC subnets

### ISSUE THREAD

**Issue by rohanmangal** [aws/amazon-ecs-agent#2236]
### Summary
[ECS ENI trunking](https://docs.aws.amazon.com/AmazonECS/latest/developerguide/container-instance-eni.html) feature is not working for EC2 Instances launched in a [shared VPC subnets](https://docs.aws.amazon.com/vpc/latest/userguide/vpc-sharing.html).

### Description
The instances fail to register to the cluster when launched in a shared VPC and ENI trunking feature being enabled.

### Expected Behavior
ECS Container Instance should get register as expected and Should be able to launch tasks with `awsvpc` network mode.

### Observed Behavior
ECS Container Instance fails to register with REGISTRATION_FAILED.

### Supporting Log Snippets

"statusReason": "Unexpected EC2 error while attempting to Create Network Interface in subnet 'subnet-00112233445566': InvalidParameterValue",

**Comment by gitpenvij** [comment]
As per docs under ' ENI Trunking Considerations ' 
https://docs.aws.amazon.com/AmazonECS/latest/developerguide/container-instance-eni.html

"Amazon EC2 instances in shared subnets are not 
supported. They will fail to register to a cluster if they are used."

**Comment by adnxn** [comment]
closing this issue as this is not supported yet. thanks @gitpenvij.
