### ISSUE TITLE
Daemon services are not properly drained when draining ECS instances

### ISSUE THREAD

**Issue by Roberdvs** [aws/amazon-ecs-agent#2288]
### Summary
Draining ECS instances doesn't drain daemon services gracefully.

### Description
We have some ECS Daemon services with target groups attached. After draining ECS instances we've observed that these services are not being drained first from the target group like the Replica ones.

Oddly enough, they do get gracefully drained when performing a service update or a rolling restart (force redeployment). It only happens when draining the whole ECS instance.

### Expected Behavior
When draining an ECS instance, Daemon Services should be gracefully removed from their target groups

### Observed Behavior
When draining an ECS instance, Daemon Services are stopped before being removed from their target groups

**Comment by Roberdvs** [comment]
I just saw that this is also being discussed over here.
https://github.com/aws/containers-roadmap/issues/128#issuecomment-550263187
So I suppose this can be closed. Sorry for the inconvenience!

**Comment by ellenthsu** [comment]
closing in favor of https://github.com/aws/containers-roadmap/issues/128#issuecomment-550263187
