### ISSUE TITLE
ecs-agent  healthcheck failure - ipv6 ?

### ISSUE THREAD

**Issue by FLavalliere** [aws/amazon-ecs-agent#2303]
### Summary
The ECS-AGENT docker healthcheck is failing due to security / restrictions and other things.
using 1.33 ecs-agent version.

### Description
Somehow in the ecs-agent it doesnt have a proper /etc/hosts to resolve localhost ? 

In the ecs ami v2 it had "localhost4" in the /etc/hosts.

ie: 
127.0.0.1 app-sharedxxx.localdomain app-shared-0250b localhost4 localhost4.localdomain4

Adding localhost to /etc/hosts and restarting ecs-agent seems to fix the issue..

### Expected Behavior
healthcheck should use 127.0.0.1 if it cant use localhost ?

### Observed Behavior

# docker exec -it ecs-agent /agent --healthcheck

2019-12-10T16:54:41Z [WARN] Health check failed with error: Get http://localhost:51678/v1/metadata: dial tcp: lookup localhost on 172.17.0.1:53: no such host

**Comment by suneyz** [comment]
Hi @FLavalliere , thanks for reaching out. Can you help provide the AMI id that you are using and try to launch without modification to default `/etc/hosts`?
> Adding localhost to /etc/hosts and restarting ecs-agent seems to fix the issue.

Looking at the line you provided, it looks like `localhost` might be deleted accidentally.
```
127.0.0.1 app-sharedxxx.localdomain app-shared-0250b localhost4 localhost4.localdomain4
```

I tried with an ECS-optimized AMI with 1.33.0 agent (ami-0fb71e703258ab7eb). And here is the default `/etc/hosts`
```
127.0.0.1   localhost localhost.localdomain localhost4 localhost4.localdomain4                                                               
::1         localhost6 localhost6.localdomain6
```

**Comment by FLavalliere** [comment]
Oh, damn you are right, there is a user-data script that run and altered the hosts file :/

My Apologize....
