### ISSUE TITLE
CannotInspectContainerError: Could not transition to inspecting; timed out after waiting 30s

### ISSUE THREAD

**Issue by albertoa** [aws/amazon-ecs-agent#2312]
### Summary
Running jobs via AWS batch are flagged as failed due to the error inspecting the container upon exit.

### Description
This problem shows up for any job that takes more than a few seconds to execute. For example I can run 'nvidia-smi -L' and it works, other jobs fail.

The jobs run a bash script, looking at its logs everything is successful and can't see any problems. It does exit with a 0.

These jobs are the only thing running on the machines (other than the ECS agent), and they execute one at a time.

### Expected Behavior
Job should succeed

### Observed Behavior
Can't find anything there related. (ie. no heavy usage, no heavy io, plenty of disk space)
I did pass ECS_ENGINE_TASK_CLEANUP_WAIT_DURATION=30m as an environment variable in AWS batch but didn't seem to help. I suppose I would need to put it in /etc/ecs/ecs.config and cut a new AMI?

### Environment Details
These are for GPU jobs (in case it makes a difference)

docker info
Containers: 2
 Running: 2
 Paused: 0
 Stopped: 0
Images: 10
Server Version: 18.06.1-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: nvidia runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 468a545b9edcd5932818eb9de8e72413e616e86e
runc version: 69663f0bd4b60df09991c08812a60108003fa340
init version: fec3683
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.14.146-120.181.amzn2.x86_64
Operating System: Amazon Linux 2
OSType: linux
Architecture: x86_64
CPUs: 8
Total Memory: 30.96GiB
Name: ip-****.us-west-2.compute.internal
ID: ****
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

{"Cluster":"****","ContainerInstanceArn":"arn:aws:ecs:us-west-2:****:container-instance/86c5b188-b462-4870-99e4-4bb66106d2f4","Version":"Amazon ECS Agent - v1.32.1 (4285f58f)"}

df -h
Filesystem      Size  Used Avail Use% Mounted on
/dev/nvme0n1p1  148G   32G  116G  22% /
tmpfs           3.1G     0  3.1G   0% /run/user/1000

### Supporting Log Snippets
I looked at:
https://github.com/aws/amazon-ecs-agent/issues/278
https://github.com/aws/amazon-ecs-agent/issues/309
Can't find anything there related. (ie. no heavy usage, no heavy io, plenty of disk space)

**Comment by albertoa** [comment]
An update on IO. It does indeed happen when there is about 2GB of data written within the container.

Although by the time the container exits there the IO has stopped at least 10 seconds prior (I added a sleep), so the IO should no longer be active.

I've been able to log into the box and run docker inspect on the container at the right time. It can take over 1 minute.

As a workaround is there any way to change the timeout to 5 minutes?

**Comment by fierlion** [comment]
can you give me more detail on your selected EC2 instance type?  I'd like to rule out any limits we might be hitting up against.

**Comment by albertoa** [comment]
g4dn.2xlarge

**Comment by albertoa** [comment]
With the help of a coworker we can affirm that the issue is caused by the docker inspect code taking more than 1 minute. This is seen when the changes within the file system are large upon exit.

A workaround is to do a final file system cleanup within our scripts prior to exiting the container, during which the state of the disk is left close to the original state (ie. upon container entry).

We have now executed several times with 100% success rate by cleaning our tmp directory.

I still think the inspect timeout within the ECS agent should be configurable, but at least we can move forward.

**Comment by fierlion** [comment]
> I still think the inspect timeout within the ECS agent should be configurable

There are several configurable timeouts in the task definition that you might be able to take advantage of -- the healthcheck timeout as well as the container startTimeout and stopTimeout.  
https://docs.aws.amazon.com/AmazonECS/latest/developerguide/task_definition_parameters.html

I'll close this issue for now.  Please re-open if you need further assistance.

**Comment by yololftw** [comment]
@fierlion are these options available for managed AWS batch compute environments?

As I can see there are no options to do this for AWS  batch (the original issue was reported against batch) And I am also hitting the same error

Ill try and follow what @albertoa  mentioned and also update our images to have latest Amazon ECS Container Agent

**Comment by ChaminW** [comment]
Having the same issue in AWS batch. Any workaround for AWS batch?

**Comment by albertoa** [comment]
@ChaminW making sure you delete any files created within the container during its run seems to work reliably in AWS batch.

Although the variables mentioned by @fierlion  do not help this particular issue, the workaround is effective.

If a new variable that actually targets this specific timeout is added to the ecs agent, it would really help. We are already creating our own AMIs based on the AWS base AMIs for batch, so we could add it to the configuration.

**Comment by ChaminW** [comment]
@albertoa Would try by deleting newly created files by batch jobs. Right now I keep them thinking it would clean by docker.

**Comment by ChaminW** [comment]
Anyway it would be great if there is a customizable configuration to set timeout in AWS batch.

**Comment by kurtwheeler** [comment]
The point of some of my jobs is to download files. I can't cleanup after them... Any word on an option for Batch?

**Comment by jeffcarrico** [comment]
> I still think the inspect timeout within the ECS agent should be configurable

+1 for this (and for a way to set the option when using aws batch)

**Comment by Kushal2511** [comment]
> > I still think the inspect timeout within the ECS agent should be configurable
> 
> +1 for this (and for a way to set the option when using aws batch)

Hi Jeff Can you upgrade ecs agent to version 1.54.1. As per release notes now if docker inspect times out then ecs agent uses docker events to get the exit code of the job. This way your job would be marked as successful even if you have docker inspect timeout

**Comment by HariramJ** [comment]
I still face this issue. I am submitting jobs in Batch from a pipelining tool called Nextflow. Batch uses ECS in the backend to run the jobs in containers. However one particular container/task stops everytime with the same error "CannotInspectContainerError: Could not transition to inspecting; timed out after waiting 30s". Any suggestions on how to fix this in AWS Batch?

**Comment by HariramJ** [comment]
Hi Kdesai, thanks for your response. My ecs agent version is 1.55.2. But still the container stops.

**Comment by nick-youngblut** [comment]
@HariramJ did you ever find a solution to this issue? I am encountering the same issue
