### ISSUE TITLE
firelens fails to start due to bad mount config when running ecs-agent in docker

### ISSUE THREAD

**Issue by gregsterin** [aws/amazon-ecs-agent#2323]
### Summary
My firelens startup is failing with
```
Error response from daemon: oci runtime error: container_linux.go:247: starting container process caused "process_linux.go:359: container init caused \"rootfs_linux.go:54: mounting \\\"/nail/run/ecs-agent/data/firelens/0df8c29f-4d9c-427a-bb33-c337f89e1be3/config/fluent.conf\\\" to rootfs \\\"/mnt/docker/overlay2/d7cb784f62520ae1318bcb64216f7b6128ee48f6b82ffcdb34c1074ab210c96d/merged\\\" at \\\"/mnt/docker/overlay2/d7cb784f62520ae1318bcb64216f7b6128ee48f6b82ffcdb34c1074ab210c96d/merged/fluent-bit/etc/fluent-bit.conf\\\" caused \\\"not a directory\\\"\""
: Are you trying to mount a directory onto a file (or vice-versa)? Check if the specified host path exists and is the expected type
```

My ECS agent is running in docker with the following config:
```
ECS_DATADIR=/data
ECS_ENABLE_TASK_IAM_ROLE=true
ECS_ENABLE_TASK_IAM_ROLE_NETWORK_HOST=true
ECS_IMAGE_PULL_BEHAVIOR=prefer-cached
ECS_LOGFILE=/log/ecs-agent.log
ECS_AVAILABLE_LOGGING_DRIVERS=["json-file","awslogs", "fluentd"]
ECS_LOGLEVEL=info
ECS_CLUSTER=jobs
ECS_HOST_DATA_DIR=/nail/run/ecs-agent
```

### Description
My firelens startup is failing with
```
Error response from daemon: oci runtime error: container_linux.go:247: starting container process caused "process_linux.go:359: container init caused \"rootfs_linux.go:54: mounting \\\"/nail/run/ecs-agent/data/firelens/0df8c29f-4d9c-427a-bb33-c337f89e1be3/config/fluent.conf\\\" to rootfs \\\"/mnt/docker/overlay2/d7cb784f62520ae1318bcb64216f7b6128ee48f6b82ffcdb34c1074ab210c96d/merged\\\" at \\\"/mnt/docker/overlay2/d7cb784f62520ae1318bcb64216f7b6128ee48f6b82ffcdb34c1074ab210c96d/merged/fluent-bit/etc/fluent-bit.conf\\\" caused \\\"not a directory\\\"\""
: Are you trying to mount a directory onto a file (or vice-versa)? Check if the specified host path exists and is the expected type
```

My ECS agent is running in docker with the following config:
```
ECS_DATADIR=/data
ECS_ENABLE_TASK_IAM_ROLE=true
ECS_ENABLE_TASK_IAM_ROLE_NETWORK_HOST=true
ECS_IMAGE_PULL_BEHAVIOR=prefer-cached
ECS_LOGFILE=/log/ecs-agent.log
ECS_AVAILABLE_LOGGING_DRIVERS=["json-file","awslogs", "fluentd"]
ECS_LOGLEVEL=info
ECS_CLUSTER=jobs
ECS_HOST_DATA_DIR=/nail/run/ecs-agent
```

Digging through the code, it looks like the ECS_DATADIR is passed into the firelens_unix.go code, and it renders configs into `filepath.Join(filepath.Join(dataDir, "firelens"), taskID)` (https://github.com/aws/amazon-ecs-agent/blob/9715741e15a1b7e2ff7bb663dca43227b8620a43/agent/taskresource/firelens/firelens_unix.go#L117)

However, the mountpaths configured for the container suffix /data/firelens to the ECS_HOST_DATA_DIR - https://github.com/aws/amazon-ecs-agent/blob/master/agent/api/task/task.go#L106

As a result, the fluentbit configs are rendered to ECS_DATADIR/firelens/task_id/... however the container mount is expecting the configs to be in ECS_HOST_DATA_DIR/data/firelens/task_id...

Since ECS_DATADIR should map to ECS_HOST_DATA_DIR (the former is the data path mounted into the container, where the latter is the data path on the host), this results in a missing fluent.conf, and docker will be default create an empty directory. When docker tries to mount this empty directory into the container path (`/fluent-bit/etc/fluent-bit.conf`), it fails because it is trying to merge a directory into what is already a file in the image.

### Expected Behavior
firelens starts ups

### Observed Behavior
```
Error response from daemon: oci runtime error: container_linux.go:247: starting container process caused "process_linux.go:359: container init caused \"rootfs_linux.go:54: mounting \\\"/nail/run/ecs-agent/data/firelens/0df8c29f-4d9c-427a-bb33-c337f89e1be3/config/fluent.conf\\\" to rootfs \\\"/mnt/docker/overlay2/d7cb784f62520ae1318bcb64216f7b6128ee48f6b82ffcdb34c1074ab210c96d/merged\\\" at \\\"/mnt/docker/overlay2/d7cb784f62520ae1318bcb64216f7b6128ee48f6b82ffcdb34c1074ab210c96d/merged/fluent-bit/etc/fluent-bit.conf\\\" caused \\\"not a directory\\\"\""
: Are you trying to mount a directory onto a file (or vice-versa)? Check if the specified host path exists and is the expected type
```

**Comment by fenxiong** [comment]
> As a result, the fluentbit configs are rendered to ECS_DATADIR/firelens/task_id/... however the container mount is expecting the configs to be in ECS_HOST_DATA_DIR/data/firelens/task_id...

This is because the agent container itself is expected to have a bind mount of `ECS_HOST_DATA_DIR:ECS_DATADIR`. When you use the [ecs-init RPM](https://github.com/aws/amazon-ecs-init/) to launch the agent, it will add such a bind mount with the default value of `ECS_HOST_DATA_DIR` and `ECS_DATADIR`. If you want to use different values for these two configs, you will need to launch the agent container via docker with a corresponding bind mount, for example for your case it should be something like (example of a full command can be found in the README of this repo):
```
docker run --name ecs-agent \
--detach=true \
--volume=/nail/run/ecs-agent:/data
...
amazon-ecs-agent:latest
```
Could you trying doing that, or let me know if you already did that and still have the error?

**Comment by gregsterin** [comment]
I see. The documentation did not make this mount relationship clear.

**Comment by fenxiong** [comment]
> I see. The documentation did not make this mount relationship clear.

Yeah, thanks for pointing out. I've updated the README to document this mounting requirement https://github.com/aws/amazon-ecs-agent/pull/2328.
