### ISSUE TITLE
Confirmation on how CPU quotas on tasks work

### ISSUE THREAD

**Issue by agwidarsito** [aws/amazon-ecs-agent#2325]
Hello all,

I just have a quick question I'm hoping someone can help me with. I wasn't sure the best place to ask, but I felt this was a good place as it allows others to hopefully benefit too.

When setting a hard CPU quota on a task, should I not allocate the full number of CPU units available to tasks to ensure some are reserved for the system? Is this best practice? My understanding is that for task-based CPU quotas, they are hard limits (as opposed to container-based CPU limits).

E.g. say I have a total of 1024 CPU units and I want to run a single Docker container. Am I best off setting the limit to, say, 900 so that the container cannot consume the full entirety of the system's compute resources?

Thanks for your help!

**Comment by jy19** [comment]
Not allocating the full number of CPU units available to a task is not necessarily best practice, it depends on if you’re expecting your instance to do other things besides running the task that you allocate CPU to. Here are some resources for additional information: https://docs.aws.amazon.com/AmazonECS/latest/developerguide/task_definition_parameters.html#container_definition_environment (specifically the information under the `cpu` parameter)
https://aws.amazon.com/blogs/containers/how-amazon-ecs-manages-cpu-and-memory-resources/

**Comment by jy19** [comment]
feel free to re-open if you have additional questions!
