### ISSUE TITLE
ECS agent not properly draining connections

### ISSUE THREAD

**Issue by abby-fuller** [aws/amazon-ecs-agent#234]
@euank :

I believe that when reducing the number of tasks in a service the ECS agent is not properly draining connections and removing instances from ELBs prior to sending a SIGTERM to the container that is being shutdown.

Our setup is:

An API service (called deathstar) with a task container that has an nginx proxy and several nodejs processes inside it. The nginx proxy distributes incoming requests to the nodejs processes. If none of the nodejs processes in the container are alive then nginx itself will return a 502 Bad Gateway response.

An ELB (managed by ECS) that distributes incoming requests across multiple deathstar containers on different instances (managed by ECS).

Another service that makes requests to the ELB.

Here is the timeline that I'm seeing:

A Lambda function which we use for autoscaling triggers based on a cloudwatch alarm and lowers the the number of tasks for the deathstar service:

    2015-10-22T21:47:34.454Z  80db0513-7906-11e5-8f29-81fe792d6dc0  The service that triggered this alarm was: deathstar

The Lambda function does an UpdateService call which lowers the desired number of tasks for the service.

The ECS logs show that the ECS agent has responded to the updated desired task count and is draining connections from 1 task and has deregistered 1 instance (corresponding to the task that it is draining) from the ELB:

    2015-10-22 17:47:59 -0400 service deathstar has begun draining connections on 1 tasks.

    2015-10-22 17:47:59 -0400 service deathstar deregistered 1 instances in elb signal-backend-deathstar

    Oct 22 21:48:12 ip-10-0-2-66 docker/b29ba7b6a397[6535]: 2015-10-22T21:48:12Z [INFO] Stopping container module="TaskEngine" task="deathstar_staging-24 arn:aws:ecs:us-east-1:604238712147:task/6a6e421f-e5f5-46f4-b0fa-851da394e4b0, Status: (RUNNING->STOPPED) Containers: [deathstar_staging (RUNNING->STOPPED),]" container="deathstar_staging-airtimemedia/deathstar:449d18dd51b4ce05b37a70fe13bf4628ae4b9f52 (RUNNING->STOPPED) - Exit: 0"

Our application logs (from inside the container) show that our master app process received the SIGTERM that was sent to the container and is shutting down its child processes:

    Oct 22 21:48:12 ip-10-0-2-66 docker/24d47ac58118[6535]: {"name":"deathstar","hostname":"24d47ac58118","pid":9,"level":30,"port":"8003","msg":"Sending shutdown to worker","time":"2015-10-22T21:48:12.682Z","v":0}

Another one of our services gets a 502 error because its request to the deathstar ELB was still routed to the container that was supposed to have been drained and already deregistered from the ELB. This 502 response is being returned from the Nginx process running inside the container, because none of the app processes are available to answer the request (because they are shutting down in response to the SIGTERM signal)

    Oct 22 21:48:15 ip-10-0-0-37 docker/d7474e363e5b[6533]: {"name":"wampa","env":"staging","hostname":"d7474e363e5b","pid":36,"level":50,"body":"<html>\r\n<head><title>502 Bad Gateway</title></head>\r\n<body bgcolor=\"white\">\r\n<center><h1>502 Bad Gateway</h1></center>\r\n<hr><center>nginx/1.8.0</center>\r\n</body>\r\n</html>\r\n","message":"Deathstar returned status code:502","options":{"method":"PUT","uri":"http://signal-deathstar-stage.airtime.com//api/v1/internal/rooms/5626d3e94b7be42000d8edc4/presence","json":true,"body":{"users":[{"_id":"55c26fb9639063b1cc458e6a","enteredAt":1445550495002}]},"auth":{"bearer":"REDACTED"}},"msg":"","time":"2015-10-22T21:48:15.009Z","v":0}

Our app prints a final log line showing that it is about to exit.

    Oct 22 21:48:17 ip-10-0-2-66 docker/24d47ac58118[6535]: {"name":"deathstar","hostname":"24d47ac58118","pid":38,"level":40,"port":8002,"msg":"Worker died","time":"2015-10-22T21:48:17.904Z","v":0}

ECS agent logs a few more state transitions:

    Oct 22 21:48:19 ip-10-0-2-66 docker/b29ba7b6a397[6535]: 2015-10-22T21:48:19Z [INFO] Adding event module="eventhandler" change="ContainerChange: arn:aws:ecs:us-east-1:604238712147:task/6a6e421f-e5f5-46f4-b0fa-851da394e4b0 deathstar_staging -> STOPPED, Exit 0, , Known Sent: RUNNING"

    Oct 22 21:48:19 ip-10-0-2-66 docker/b29ba7b6a397[6535]: 2015-10-22T21:48:19Z [INFO] Sending container change module="eventhandler" event="ContainerChange: arn:aws:ecs:us-east-1:604238712147:task/6a6e421f-e5f5-46f4-b0fa-851da394e4b0 deathstar_staging -> STOPPED, Exit 0, , Known Sent: RUNNING" change="ContainerChange: arn:aws:ecs:us-east-1:604238712147:task/6a6e421f-e5f5-46f4-b0fa-851da394e4b0 deathstar_staging -> STOPPED, Exit 0, , Known Sent: RUNNING"

    Oct 22 21:48:19 ip-10-0-2-66 docker/b29ba7b6a397[6535]: 2015-10-22T21:48:19Z [INFO] Redundant status change; ignoring module="TaskEngine" task="deathstar_staging-24 arn:aws:ecs:us-east-1:604238712147:task/6a6e421f-e5f5-46f4-b0fa-851da394e4b0, Status: (STOPPED->STOPPED) Containers: [deathstar_staging (STOPPED->STOPPED),]" current="STOPPED" change="STOPPED"

    Oct 22 21:48:19 ip-10-0-2-66 docker/b29ba7b6a397[6535]: 2015-10-22T21:48:19Z [INFO] Redundant status change; ignoring module="TaskEngine" task="deathstar_staging-24 arn:aws:ecs:us-east-1:604238712147:task/6a6e421f-e5f5-46f4-b0fa-851da394e4b0, Status: (STOPPED->STOPPED) Containers: [deathstar_staging (STOPPED->STOPPED),]" current="STOPPED" change="STOPPED"

To summarize why I feel this is an issue with ECS I believe that based on what I'm seeing in these logs that ECS is sending our container a SIGTERM prior to fully draining connections, and fully deregistering the instance from the ELB. This is evident because a request somehow is still reaching the container that is being terminated, even AFTER the log line about deregistering the instance from the ELB.

My expectation would be that ECS would wait until the instance was completely removed from the ELB (and it was impossible for the ELB to continue to send requests to the container) before sending a SIGTERM signal to our container.

If this expectation is incorrect then I'd be interested in knowing what your recommended strategy is for a more graceful UpdateService experience. From our deathstar container's perspective it is responding properly to a SIGTERM signal that it receives, by closing its server and shutting down. From the perspective of our other service, it is operating properly by sending a request to an ELB. The fact that the request to the ELB was sent to the container that is shutting/shut down seems like an ECS bug.

@nathanpeck

**Comment by flowhamster** [comment]
+1

**Comment by cassieramen** [comment]
+1

**Comment by jsh2134** [comment]
+1

**Comment by samuelkarp** [comment]
Thank you for reporting the issue you detected with your load balancer in which an ECS task received traffic from your load balancer after the connection draining interval had expired.  We determined this was caused by an edge case which we have fixed.  You should not encounter this behavior from your load balancer in the future.

**Comment by sebastiankirsch** [comment]
@samuelkarp with "in the future" you mean as of now? In all AWS regions?

**Comment by samuelkarp** [comment]
@sebastiankirsch Connection draining should work properly today.  If you're having problems, please open a new issue or post on the [AWS forums](https://forums.aws.amazon.com/forum.jspa?forumID=187).

**Comment by sebastiankirsch** [comment]
Is that tied to a specific version of the ecs-agent?
We're still on 1.7...

**Comment by samuelkarp** [comment]
No, the ECS agent does not control connection draining (nor is it even aware of the load balancer at all).
