### ISSUE TITLE
CannotPullContainerError -- public repo images unavailable.

### ISSUE THREAD

**Issue by carlcrott** [aws/amazon-ecs-agent#2343]
### Summary
CannotPullContainerError 

### Description
Read through the Issues log and found this post from @samuelkarp 
https://github.com/aws/amazon-ecs-agent/issues/422#issuecomment-241915622

1) The documentation linked  ( https://docs.aws.amazon.com/AmazonECS/latest/developerguide/private-auth.html ) is a self-referential hairball. The Tutorial has you criss-crossing through a bunch of AWS services + GUIs to configure a 'private repo' for ultimately a container pull from a public repository.

### Expected Behavior
I should need no authentication to pull from a public docker hub image.  In this instance elasticsearch.

### Observed Behavior

AWS tutorials are a study in page criss-crossing / hoop jumping, complex tutorials.

> STOPPED Reason: CannotPullContainerError: Error response from daemon: pull access denied for elasticsearch/elasticsearch, repository does not exist or may require 'docker login'

Current course of action is to examine why output of 

`docker inspect ecs-agent`

is empty.

**Comment by samuelkarp** [comment]
It looks like the image `elasticsearch/elasticsearch` does not exist in Docker Hub.  See here: https://hub.docker.com/r/elasticsearch/elasticsearch.

The image you are looking for is `elasticsearch`.  You can find it here: https://hub.docker.com/_/elasticsearch/.

**Comment by carlcrott** [comment]
Ok my problem seems to have evaporated after re-pasting the original docker-compose file.

Takeaway:

versions / formatting of compose files are very specific.

I should mention that the URL of the specific elastisearch image breaks the normal (that i've seen) pattern 

### User-uploaded package
URL:
https://hub.docker.com/r/carlcrott/foodtrucks-web
Compose:
  image: carlcrott/foodtrucks-web

### Official package
URL:
https://hub.docker.com/_/elasticsearch/
Compose:
  image: elasticsearch # NOTE: this fails ( CannotPullContainerError: invalid reference format  )
  image: elasticsearch:2.3 # While this with specified version works + composes the cluster

I suppose this is differentiating official hosted packages vrs community made ones and for some reason package versions are required instead of the normal pattern of pulling latest.

But this caused me problems.
