### ISSUE TITLE
ecs-agent is unhealthy

### ISSUE THREAD

**Issue by Shert** [aws/amazon-ecs-agent#2349]
### Summary
ecs-agent is in state unhealty

### Description
we have a 3 nodes cluster and on all nodes the result of a docker ps shows 

"cc61d5053d50        amazon/amazon-ecs-agent:latest                                                                                       "/agent"                 5 minutes ago       Up 5 minutes (unhealthy) "

### Expected Behavior
the ecs-agent is healthy

### Observed Behavior
the ecs-agent is unhealthy

### Environment Details
*docker info
Containers: 5
 Running: 5
 Paused: 0
 Stopped: 0
Images: 12
Server Version: 18.09.9-ce
Storage Driver: devicemapper
 Pool Name: docker-docker--pool
 Pool Blocksize: 524.3kB
 Base Device Size: 10.74GB
 Backing Filesystem: ext4
 Udev Sync Supported: true
 Data Space Used: 2.925GB
 Data Space Total: 44.59GB
 Data Space Available: 41.67GB
 Metadata Space Used: 6.926MB
 Metadata Space Total: 46.14MB
 Metadata Space Available: 39.21MB
 Thin Pool Minimum Free Space: 4.459GB
 Deferred Removal Enabled: true
 Deferred Deletion Enabled: true
 Deferred Deleted Device Count: 0
 Library Version: 1.02.135-RHEL7 (2016-11-16)
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 894b81a4b802e4eb2a91d1ce216b8817763c29fb
runc version: 2b18fe1d885ee5083ef9f0838fee39b62d653e30
init version: fec3683
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.14.158-101.185.amzn1.x86_64
Operating System: Amazon Linux AMI 2018.03
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 7.79GiB
Name: ecs-test-node
ID: 2TOY:4NPM:SEYY:LO3P:TEEX:UPHG:K4HH:2WKZ:PTA5:476K:RM6P:5FAO
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

WARNING: the devicemapper storage-driver is deprecated, and will be removed in a future release.

*df -h
[root@ecs-test-node ~]# df -h
Filesystem      Size  Used Avail Use% Mounted on
/dev/xvda1      7.8G  1.4G  6.3G  18% /
devtmpfs        3.9G  104K  3.9G   1% /dev
tmpfs           3.9G     0  3.9G   0% /dev/shm
/dev/dm-4       9.8G   71M  9.2G   1% /var/lib/docker/devicemapper/mnt/88a2c5f22943db30a5ab8aa02e9838afcca7cc44cc15a20177877a007c93b552
shm              64M  8.0K   64M   1% /var/lib/docker/containers/209a473550eb6173ee4344241554eb94459229fa98b42ff9c9ee01fbeafe6662/mounts/shm
/dev/dm-7       9.8G  699M  8.6G   8% /var/lib/docker/devicemapper/mnt/f700e6f26ee41cdbe13a89ddd4ffd6f4eba99dfa3c3b529b783402e2057edeff
shm              64M     0   64M   0% /var/lib/docker/containers/9c450dffca4c1b8e269483e822d9b5a51778c90469451176c1b2b6d493c8906c/mounts/shm
/dev/dm-5       9.8G  460M  8.8G   5% /var/lib/docker/devicemapper/mnt/88fe1929572248f0ef34ad84980785ebd6fa0bc999777085ff19b6d2c60817de
shm              64M     0   64M   0% /var/lib/docker/containers/5377323c0d851415d2f141776f33d2d6249a93f4ad4290e7ef574e4874bec07a/mounts/shm
/dev/dm-6       9.8G  448M  8.8G   5% /var/lib/docker/devicemapper/mnt/7496e82c5c41c36ade984be3cd8cc7ac95a9890425b23a7d85ba217904333cf2
shm              64M     0   64M   0% /var/lib/docker/containers/b9be626e7afb6f1130534ce7512b4a24b0a181ba666f849672edc10842274bf5/mounts/shm
/dev/dm-3       9.8G   85M  9.2G   1% /var/lib/docker/devicemapper/mnt/bdaab0a16d1f2b26455ecff6746664b0e49c5168587c6d7d547c152d705f8fb2
shm              64M     0   64M   0% /var/lib/docker/containers/cc61d5053d50bff5a4f43b5402448d9611180c68e200d95ab6f51fb7298d800e/mounts/shm

*metadata info
[root@ecs-test-node ~]# curl -s http://localhost:51678/v1/metadata | jq
{
  "Cluster": "mycosta-cluster",
  "ContainerInstanceArn": "arn:aws:ecs:eu-central-1:060432352654:container-instance/9df97e6e-5b73-49c4-9275-845357e7d763",
  "Version": "Amazon ECS Agent - v1.36.1 (f199a183)"
}

### Supporting Log Snippets
I would prefer to give the logs privately

**Comment by petderek** [comment]
> I would prefer to give the logs privately

If the logs have details about the failing health-checks, that would be super helpful on our end. Feel free to email them:

ecs-agent-external at amazon.com

**Comment by Shert** [comment]
I just sent you the logs ,
I would like to point out that even if the agent running is version 1.36.1 , 
the ecs-init package is still 1.35, see following checks : 

```
[root@ecs-test-node tmp]# rpm -qi ecs-init
Name        : ecs-init
Version     : 1.35.0
Release     : 1.amzn1
Architecture: x86_64
Install Date: Sat 01 Feb 2020 06:06:01 AM UTC
Group       : Unspecified
Size        : 71865269
License     : Apache 2.0
Signature   : RSA/SHA256, Tue 14 Jan 2020 10:29:26 PM UTC, Key ID bcb4a85b21c0f39f
Source RPM  : ecs-init-1.35.0-1.amzn1.src.rpm
Build Date  : Thu 12 Dec 2019 07:19:40 PM UTC
Build Host  : koji-pdx-corp-builder-60003.build
Relocations : (not relocatable)
Packager    : Amazon.com, Inc. <http://aws.amazon.com>
Vendor      : Amazon.com
Summary     : Amazon Elastic Container Service initialization application
Description :
ecs-init supports the initialization and supervision of the Amazon ECS
container agent, including configuration of cgroups, iptables, and
required routes among its preparation steps.
```

```
curl -s http://localhost:51678/v1/metadata | jq
{
  "Cluster": "mycosta-cluster",
  "ContainerInstanceArn": "arn:aws:ecs:eu-central-1:060432352654:container-instance/9df97e6e-5b73-49c4-9275-845357e7d763",
  "Version": "Amazon ECS Agent - v1.36.1 (f199a183)"
}
```

hope this helps

M.

**Comment by Shert** [comment]
I'm sending again the logs because the previous collectionwas made with agent version 1.35.0

M.

**Comment by petderek** [comment]
I spent some time (unsuccessfully) trying to repro the issue you are observing. an interesting part of this is that you can run this command successfully: `curl -s http://localhost:51678/v1/metadata | jq`

[This is fundamentally the same thing that agent does](https://github.com/aws/amazon-ecs-agent/blob/master/agent/app/healthcheck.go), albeit from within the context of its container.

 I'm wondering if there's some additional network/docker configuration that would prevent agent from resolving 'localhost' on your instances.

**Comment by Shert** [comment]
Hi,
thank you for your reply , as far as I know there should not be 
any network/docker configuration causing this issue, if you have any 
ideas/suggestions for a check I'm open to do it.

M.

**Comment by markuman** [comment]
We have the same issue.

ecs-agent.log

```
level=warn time=2020-03-31T05:21:42Z msg="Health check failed with error: Get http://localhost:51678/v1/metadata: dial tcp 10.98.6.56:51678: i/o timeout" module=healthcheck.go
level=info time=2020-03-31T05:21:43Z msg="ACS connection closed: EOF" module=acs_handler.go
level=info time=2020-03-31T05:21:43Z msg="ACS Websocket connection closed for a valid reason: EOF" module=acs_handler.go
level=info time=2020-03-31T05:21:43Z msg="Establishing a Websocket connection to https://ecs-a-1.eu-central-1.amazonaws.com/ws?agentHash=78294847&agentVersion=1.37.0&clusterArn=cluster-int&containerInstanceArn=arn%3Aaws%3Aecs%3Aeu-central-1%3A402727047553%3Acontainer-instance%2F0109231f-6bd0-4c73-a46a-5f008a3885fd&dockerVersion=DockerVersion%3A+18.09.9-ce&sendCredentials=false&seqNum=1" module=client.go
```

but from the same host, `http://localhost:51678/v1/metadata` is successful requestable.

```
[ec2-user@ip-10-112-70-108 ~]$ curl -s http://localhost:51678/v1/metadata | jq
{
  "Cluster": "cluster-int",
  "ContainerInstanceArn": "arn:aws:ecs:eu-central-1:402727047553:container-instance/0109231f-6bd0-4c73-a46a-5f008a3885fd",
  "Version": "Amazon ECS Agent - v1.37.0 (78294847)"
}
```

**Comment by markuman** [comment]
Ok, in o.ur case we had an accidental dns entry

**Comment by Shert** [comment]
I came to the same result, even in our case te problem was a bad configuration 
in searvh domains and resolution of localhost.$localdomain , trying the call on
cli didn't query but used /etc/hosts so it worked, but ecs-agent test used the 
resolution stack configured onthe instance and led to the error
Sorry for the extra work for everybody 

M.
