### ISSUE TITLE
When I am trying to update 1.36.2 Agent version, it is throwing NoUpdateAvailableException (Code 400)

### ISSUE THREAD

**Issue by ankila1b2** [aws/amazon-ecs-agent#2355]
I am currently using the latest Linux 2 ECS AMI version on my ECS cluster container instances, also 18.09.9-ce Docker version in us-west-2 region.

**Comment by ankila1b2** [comment]
I am currently using the latest ECS AMI version on my  ECS cluster container instances, also 18.09.9-ce Docker version.

**Comment by yunhee-l** [comment]
We are in the process to finish releasing 1.36.2, AL1 AMI is released fully but AL2 is not yet. Please try again in 24 hours.

**Comment by ankila1b2** [comment]
Ok thanks.

**Comment by petderek** [comment]
You should be good to go now. Please let us know if you are still observing issues.

**Comment by ankila1b2** [comment]
Yes, it is working. Thanks
