### ISSUE TITLE
Send Container Logs in Custom Location to Cloudwatch

### ISSUE THREAD

**Issue by vennemp** [aws/amazon-ecs-agent#2379]
I'm using FARGATE to run a container that writes logs to a custom location (/mnt/logs/app.log), I want to forward these logs to cloudwatch and am not seeing a clear answer on how to do this.  I am seeing references to firelens as the way to go, but I don't see any parameter that says "log file location" or something.

**Comment by shubham2892** [comment]
@vennemp You will be able to send logs to cloudwatch using Firelens. Please refer to this guide on how to setup logs using firelens -- https://docs.aws.amazon.com/AmazonECS/latest/developerguide/using_firelens.html. Essentially you will need to reference the log file location in fluent-bit.conf or fluent.conf whatever you end up using. 

Please let me know if you need any additional information. Thanks.

**Comment by vennemp** [comment]
@shubham2892 thanks!  I’ve seen these articles but I’ve seen nothing that shows an example on how to reference custom log locations.

Alternatively, I know this isn’t best practice but couldn’t we also symlink the log files to stdout?

**Comment by shubham2892** [comment]
> @shubham2892 thanks! I’ve seen these articles but I’ve seen nothing that shows an example on how to reference custom log locations.
The custom log location will be specified in conf(fluent-bit.conf or fluent.conf) file. 

You have to add a section ["tail"](https://docs.fluentd.org/input/tail) to get logs from custom location in conf(fluent-bit.conf or fluent.conf) file. More details about the config file is found here -- https://docs.fluentd.org/configuration/config-file

> 
> Alternatively, I know this isn’t best practice but couldn’t we also symlink the log files to stdout?

I am not sure about this par, will need to give it a try.

**Comment by shubham2892** [comment]
Hope you issue is resolved, closing the issue, please reopen if you need more assistance.

**Comment by mustafa89** [comment]
The Application container only has the option to generate output plugin config for awsfirelensm, where the logs are just sent to the side car fluent-bit container via unix socket. It seems there is absolutely no way to send any custom log file which are not putputed to sdout to CW/KFH.

@shubham2892

**Comment by PettitWesley** [comment]
This is covered here: https://github.com/aws-samples/amazon-ecs-firelens-examples/tree/mainline/examples/fluent-bit/ecs-log-collection
