### ISSUE TITLE
Proxy: Migrate to `gorilla/websocket`'s new proxy support

### ISSUE THREAD

**Issue by euank** [aws/amazon-ecs-agent#239]
Per issue https://github.com/gorilla/websocket/pull/90 and discussion on #23, there's now support for proxies in `gorilla/websocket` (which we already use).

This came shortly after support was implemented in the Agent for the same (#211).
It would make sense to migrate to that upstream code since it makes more sense for it to live there.
This issue is to track that refactor.

**Comment by petderek** [comment]
Fixed with #659

**Comment by euank** [comment]
Thanks @petderek 🎉
