### ISSUE TITLE
Volume won't be deleted

### ISSUE THREAD

**Issue by Jackyen** [aws/amazon-ecs-agent#2403]
### Summary

Volume won't delete by agent.

### Description

When we set the DockerConfiguration scope to **task**
We expect it will be delete when the task end of life.
But it is not.

### Expected Behavior
Volume deleted.

### Environment Details

Docker verion:
 Version:           19.03.8

{"ContainerInstanceArn":"arn:aws:ecs:us-east-1:690060915618:container-instance/1f774f2b-e3da-4249-b5d7-5ecbe3067f9a","Version":"Amazon ECS Agent - v1.37.0 (78294847)"}

**Comment by yunhee-l** [comment]
Thank you for reporting this issue.
Are the volumes marked as shared? For us to investigate further, could you please send the task definition you've used for this task to ecs-agent-external at amazon.com?

**Comment by yunhee-l** [comment]
Also, how long after task stop are you seeing the volume hang around? ECS cleans up task resources after some time (ECS_ENGINE_TASK_CLEANUP_WAIT_DURATION), default 3 hours.

**Comment by Jackyen** [comment]
@yunhee-l  Here is the volume setting
![image](https://user-images.githubusercontent.com/6920747/77670083-a7edb980-6fc0-11ea-8881-2551f2ac7ee2.png)

And I manually change the ECS_ENGINE_TASK_CLEANUP_WAIT_DURATION to the  1m
But I don't see any delete action from the agent log.

**Comment by yunhee-l** [comment]
If the volume is managed by dedicated driver like rexray there may be something on driver side that could block the deletion - is there any rexray log that provides any information? 
If you could send us debug level agent log and task definition to ecs-agent-external at amazon.com we could investigate as well, and see if we can reproduce it.

**Comment by Jackyen** [comment]
Hi

I only got this log:
Apr  6 19:31:01 ip-10-11-56-13 docker: level=warn time=2020-04-06T19:31:01Z msg="Task engine [arn:aws:ecs:us-east-1:690060915618:task/039a7949-42c5-40b5-b527-013c5cab7206]: unable to cleanup resource beta-ecs-vol: Error response from daemon: remove beta-ecs-beta-ecs-vol-f89aa4858391b1dca501: VolumeDriver.Remove: docker-legacy: Remove: beta-ecs-beta-ecs-vol-f89aa4858391b1dca501: failed: error deleting volume" module=docker_task_engine.go

**Comment by fierlion** [comment]
from the AWS ECS-EBS docs:
```
Even though you deleted the task and the service, you still need to clean up the EBS volume that you created. You created this volume and referenced it in the ECS task definition. ECS passed this information along to Docker running on the host, which in turn handed it to REX-Ray (your volume driver), which knew how to attach the EBS volume and map it to the container.

The easiest way to delete this volume is from the EC2 console. In the list of volumes, you should see a volume named rexray-vol that is unattached (state=available). Delete this volume as it is no longer needed.
```
https://aws.amazon.com/blogs/compute/amazon-ecs-and-docker-volume-drivers-amazon-ebs/

**Comment by fierlion** [comment]
There are several resource articles that talk about current best practices around cleaning up EBS volumes.  Here's one that might be helpful.
https://aws.amazon.com/blogs/mt/controlling-your-aws-costs-by-deleting-unused-amazon-ebs-volumes/
You'll need to use the aws sdk, aws cli or aws console to manage the EBS volumes.

**Comment by fierlion** [comment]
Closing.  Please re-open if you have any further questions.
