### ISSUE TITLE
Overriding default environment variables

### ISSUE THREAD

**Issue by mardoz** [aws/amazon-ecs-agent#2412]
### Summary
The ECS agent sets a number of environment variables such as AWS_ACCESS_KEY_ID and appears to have no way of allowing the container creator to override them.

### Description
I'm trying to create an ECS task that contains prometheus with some sidecars that work on service discovery. Specifically I'm having issues with the container that uses https://github.com/teralytics/prometheus-ecs-discovery. I need to set AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY to an account of my choosing but these envrionment variables have already been set inside the container and I appear to have no way to override them.

One workaround would be to add the relevant permissions such as ECS:ListCLusters to the task role (as this is the one ECS is adding variables for) but this means I would make these permissions available to all containers in the task even though they don't need them and I'd also like to modularise a generic implementation of a default ECS service and so I would then end up adding this permission to all ECS services at my organisation.

The other workaround could be to remove the task role from the service as then it appears to not be setting these environment variables. Sadly I do need to include some permissions such as the ability to retreive parameters from SSM.

This would become an issue with any service that uses AWS libraries as the environment variables AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY have the top priority in the standard configuration chain.

I should add that it was AWS support that suggested I raise this here even though I'm not entirely sure this is the right place.

### Expected Behavior
Environment variables set in a container definition override any set by ECS.

### Observed Behavior
Environment variables set by ECS override those set in a container definition.

### Environment Details
Running on Fargate in ECS. Happy to provide more details.

### Supporting Log Snippets
N/A

**Comment by yunhee-l** [comment]
Thank you for reporting this issue.
ECS supports environment variable overrides through Container Override API, see our doc [here]( https://docs.aws.amazon.com/AmazonECS/latest/APIReference/API_ContainerOverride.html). This allows users to specify environment variables that takes higher precedence than ones set through userdata for example. Is this something that's suitable for your usecase?

**Comment by mardoz** [comment]
Thanks for getting back.

It doesn't look like ContainerOverride is available in Terraform, I also don't see any relevant way of setting this in the ECS UI. I guess this is only avilable through the CLI and CloudFormation?

Also, one of the variables, AWS_SECRET_ACCESS_KEY, is a secret and ContainerOverride doesn't support secrets. Is there some other way to override a secret from an SSM parameter?

**Comment by petderek** [comment]
> choosing but these envrionment variables have already been set inside the container and I appear to have no way to override them.

ECS itself shouldn't be setting these environment variables. Agent sets the `AWS_CONTAINER_CREDENTIALS_RELATIVE_URI` which contains a reference to the credentials used by the task role.

In your linked application, its likely that this environment variable takes precedence over the AWS_ACCESS_KEY_ID that you are setting. You may need to modify that application in order to customize that precedence if thats what you desire.

Another approach you could take is to use the [assume role functionality in the linked application.](https://github.com/teralytics/prometheus-ecs-discovery/blob/master/main.go#L611) You would need to give your ECS task role the ability to assume your service discovery role. That way, your container here still has different permissions, but you wouldn't need to hardcode the creds into your application.

**Comment by samuelkarp** [comment]
We do not recommend adding AWS credentials to environment variables in your task definition.  Instead, applications wishing to use credentials belonging to a different account should use the assume role functionality @petderek described.

**Comment by fierlion** [comment]
Closing this issue.  Please re-open if there are further questions.
