### ISSUE TITLE
agent won't start on GPU AMI with a non-GPU instance

### ISSUE THREAD

**Issue by albertoa** [aws/amazon-ecs-agent#2424]
### Summary
ECS agent used to be able to run with an AMI created for GPU instances on instances without a GPU

### Description
Now the ECS agent will refuse to start. The log shows it hangs in an infinite loop within pre-start

This is the log in a c5.4xlarge
head -20 /var/log/ecs/ecs-init.log 
2020-02-28T21:43:15Z [INFO] pre-start
2020-02-28T21:43:15Z [INFO] By using the GPU Optimized AMI, you agree to Nvidia’s End User License Agreement: https://www.nvidia.com/en-us/about-nvidia/eula-agreement/
2020-02-28T21:43:18Z [INFO] start
2020-02-28T21:43:18Z [INFO] No existing agent container to remove.
2020-02-28T21:43:18Z [INFO] Starting Amazon Elastic Container Service Agent
2020-02-28T21:43:30Z [INFO] stop
2020-02-28T21:43:30Z [INFO] Stopping Amazon Elastic Container Service Agent
2020-02-28T21:43:30Z [INFO] Container name: /ecs-agent
2020-02-28T21:43:31Z [INFO] Agent exited with code 0
2020-02-28T21:43:31Z [INFO] post-stop
2020-02-28T21:43:31Z [INFO] Cleaning up the credentials endpoint setup for Amazon Elastic Container Service Agent
2020-04-07T14:48:31Z [INFO] pre-start
2020-04-07T14:48:31Z [INFO] By using the GPU Optimized AMI, you agree to Nvidia’s End User License Agreement: https://www.nvidia.com/en-us/about-nvidia/eula-agreement/
2020-04-07T14:48:31Z [ERROR] Nvidia GPU Manager: setup failed: error initializing nvidia nvml: nvml: Driver Not Loaded
2020-04-07T14:48:31Z [ERROR] Nvidia GPU Manager: setup failed: error initializing nvidia nvml: nvml: Driver Not Loaded
2020-04-07T14:48:41Z [INFO] pre-start
2020-04-07T14:48:41Z [INFO] By using the GPU Optimized AMI, you agree to Nvidia’s End User License Agreement: https://www.nvidia.com/en-us/about-nvidia/eula-agreement/
2020-04-07T14:48:42Z [ERROR] Nvidia GPU Manager: setup failed: error initializing nvidia nvml: nvml: Driver Not Loaded
2020-04-07T14:48:42Z [ERROR] Nvidia GPU Manager: setup failed: error initializing nvidia nvml: nvml: Driver Not Loaded

### Expected Behavior
If a GPU is not found the driver won't start, but ECS agent should start without publishing GPU resources as available (ie. GPU count is 0).

**Comment by sharanyad** [comment]
hi @albertoa thanks for reporting the issue. 
Could you please let us know which AMI ID are you using? 
I tried this with ami-0464654f3257ca8dd - c5.4xl instance, which is the latest ECS GPU AMI and I can't seem to reproduce this issue.

**Comment by albertoa** [comment]
We build custom AMIs on top of the latest (at the time) which we get via:

aws ssm get-parameter --name /aws/service/ecs/optimized-ami/amazon-linux-2/gpu/recommended --region us-west-2 --output json | jq -r '.["Parameter"]["Value"] | fromjson.image_id'`

Unfortunately I don't remember which one it was, but the date this ami was built was: February 28, 2020

Since you are not reproducing the issue and this AMI is over a month old I would say that I need to update it on my end, which I probably should have done first.

I will do so and report the results.

Thanks,
Alberto

**Comment by albertoa** [comment]
Uhmmm. The problem remains for me:

`docker images
REPOSITORY                                                    TAG                 IMAGE ID            CREATED             SIZE
amazon/amazon-ecs-agent                                       latest              e04d1e3e2dd8        5 days ago          65.3MB
amazon/amazon-ecs-pause                                       0.1.0               9e691fb865af        5 days ago          954kB
`
The base image was: ami-0464654f3257ca8dd

This is what we do to the base AMI.

`yum -y update
yum install -y awscli htop iotop iptraf-ng net-tools moreutils tmux

service ecs stop
if [ -f /etc/ecs/ecs.config ]; then
    rm /etc/ecs/ecs.config
fi

REGION=`curl -s http://169.254.169.254/latest/dynamic/instance-identity/document | grep -oP '\"region\"[[:space:]]*:[[:space:]]*\"\K[^\"]+'`
TMP=`aws ecr get-login --registry-ids ******** --region ${REGION} --no-include-email`
$TMP

docker pull ************.dkr.ecr.us-west-2.amazonaws.com/*****

if [ -f /tmp/rc.local ]; then
    sudo cp -pf /tmp/rc.local /etc/rc.local
    sudo chown root: /etc/rc.local
fi

rm -rf /tmp/*
yum clean all
rm -rf /var/cache/yum
`

I will try next with the base AMI and report results, but wanted to show our modifications in case you can see something wrong.

**Comment by sharanyad** [comment]
If there are no GPU devices in the instances, the code path for calling Nvidia NVML APIs will never be hit (but weirdly seems to be happening in your case) 
https://github.com/aws/amazon-ecs-init/blob/d0ee8ae2e02a0e17f1d248b6b85bb1ff808e75d3/ecs-init/gpu/nvidia_gpu_manager.go#L76

The check for GPU devices is done by checking if there are nvidia GPU devices with pattern :

https://github.com/aws/amazon-ecs-init/blob/d0ee8ae2e02a0e17f1d248b6b85bb1ff808e75d3/ecs-init/gpu/nvidia_gpu_manager.go#L49

In your custom AMI, could you please check the output for `ls /dev/nvidia* ` , just to rule it out. 

The userdata doesn't look suspicious to me.

**Comment by albertoa** [comment]
I do see the ctl.

[ec2-user@ip-10-23-6-253 ~]$ ls /dev/nvidi*
/dev/nvidiactl
that may be it.

I'm still trying to check with an unmodified AMI (directly ami-0464654f3257ca8dd) but I've run out of queues. I'll report shortly as I deal with that.

**Comment by albertoa** [comment]
OK. I found the culprit.

1.- I was able to boot into an unmodified AMI with a new queue.
2.- No /dev/nvidia* there.
3.- I forgot to copy/paste the /etc/rc.local that we place into the modified AMI. So I started executing it line by line into the instance.

```
`which nvidia-smi`
if [ $? -eq 0 ]; then
	nvidia-persistenced
	nvidia-smi --auto-boost-default=0
	TMP=`nvidia-smi --query-gpu=gpu_name --format=csv | tail -1`
	echo $TMP
	if [[ $TMP == "Tesla V100-"* ]]; then
		nvidia-smi -ac 877,1530
	elif [[ $TMP == "Tesla M60" ]]; then
		nvidia-smi -ac 2505,1177
	elif [[ $TMP == "Tesla K80" ]]; then
		nvidia-smi -ac 2505,875
	elif [[ $TMP == "Tesla T4" ]]; then
		nvidia-smi -ac 5001,1590
	else
		echo "Unknown GPU. Not setting clocks"
	fi
fi
```

since obviously nvidia-smi is present the if statement is worthless on this case (I'll fix that on my end)
executing:
nvidia-smi --auto-boost-default=0
is what creates the device and caused the problem.

Thank you for your help. I would not have found the problem otherwise. 

I can take care of it on our end using the same check you use in the ECS code.
