### ISSUE TITLE
[Feature Request] ECS_IMAGE

### ISSUE THREAD

**Issue by insane-dreamer** [aws/amazon-ecs-agent#2428]

**Comment by ubhattacharjya** [comment]
Hi @insane-dreamer,

Kindly provide some details for your request.

Is this issue a duplicate of https://github.com/aws/amazon-ecs-agent/issues/2429

**Comment by insane-dreamer** [comment]
Sorry, I'm not sure how this got posted; was a draft of the issue #2429
