### ISSUE TITLE
Upgrade docker version to 19.03

### ISSUE THREAD

**Issue by truppert-mdsol** [aws/amazon-ecs-agent#2431]
### Summary
This has been requested on the containers-roadmap, but has not received a response. https://github.com/aws/containers-roadmap/issues/761

This has also been brought up with our AWS Representative.  He suggested I open a ticket here.

### Description
The specific reason we need this is because of a bug in docker 18 that has been fixed in docker 19.03.  This is the bug I'm referring to: https://github.com/moby/moby/issues/39916

We have experienced this bug first hand in ECS and need the fix for it.

**Comment by fierlion** [comment]
We are actively working on this update.

**Comment by truppert-mdsol** [comment]
@fierlion Thanks for the update.  Is there any timeline for this?  I was told "within the next year" by our Rep.  That's too broad of a time frame for us to plan effectively whether we should wait or work around this.  I would very much appreciate a better estimate if you have one.

**Comment by fierlion** [comment]
https://docs.aws.amazon.com/AmazonECS/latest/developerguide/ecs-ami-versions.html
The latest ECS-optiimized AMIs were released today with Docker version 19.03.6-ce.

Please re-open if you have further questions.
