### ISSUE TITLE
Container swap configuration not being applied

### ISSUE THREAD

**Issue by gberdugo** [aws/amazon-ecs-agent#2434]
### Summary
The swap configuration specified in task-definition.json file is not being applied to my container.

### Description
I'm using the ecs-agent v1.39.0 with the Amazon ECS-optimized Amazon Linux 2 AMI for my application.

My host machine is configured with 8GB as swap
![image](https://user-images.githubusercontent.com/3018412/79989092-d490d600-8485-11ea-9e16-01b7e978cb86.png)
and I'm using the following task-definition.json to deploy my application
![image](https://user-images.githubusercontent.com/3018412/79989520-5680ff00-8486-11ea-84b2-007b0a3ec2b7.png)

As far as I know, the maxSwap parameter should be translated to the --memory-swap parameter in the docker run command, but when I run a ```docker inspect``` in my container, the output says that the MemorySwap configuration is 0.
![image](https://user-images.githubusercontent.com/3018412/79990100-05253f80-8487-11ea-95b3-a5db335b0cc4.png)

So, I don't know if this configuration is being applied or not.

### Expected Behavior
The MemorySwap information present in the output of the command ```docker inspect``` should be the specified in the container task definition.

### Observed Behavior
The MemorySwap is always zero regardless the configuration.

### Environment Details

```docker info```
![image](https://user-images.githubusercontent.com/3018412/79991808-18d1a580-8489-11ea-85df-e8f22a5af19e.png)

**Comment by fierlion** [comment]
Taking a look now--

**Comment by fierlion** [comment]
https://docs.aws.amazon.com/AmazonECS/latest/developerguide/container-swap.html
```
The Amazon ECS-optimized AMIs do not have swap enabled by default. You must enable swap on the instance to use this feature. 
```
Have you enabled swap on the instance?

**Comment by fierlion** [comment]
```
If the maxSwap and swappiness container definition parameters are omitted from a task definition, each container will have a default swappiness value of 60 and the total swap usage will be limited to two times the memory reservation of the container.
```
I'd also be interested to see if you can modify the `swappiness` to a non-default value (ie not 60) in your taskdef and check if it is translated correctly.

**Comment by gberdugo** [comment]
> > My host machine is configured with 8GB as swap
> 
> Have you enabled swap on the instance following these guidelines -- ?
> 
> ```
> The Amazon ECS-optimized AMIs do not have swap enabled by default. You must enable swap on the instance to use this feature. 
> ```
> 
> https://docs.aws.amazon.com/AmazonECS/latest/developerguide/container-swap.html

Yes, I followed the second link (https://aws.amazon.com/premiumsupport/knowledge-center/ec2-memory-swap-file/) to enable de swap.



> ```
> If the maxSwap and swappiness container definition parameters are omitted from a task definition, each container will have a default swappiness value of 60 and the total swap usage will be limited to two times the memory reservation of the container.
> ```
> 
> I'd also be interested to see if you can modify the `swappiness` to a non-default value (ie not 60) in your taskdef and check if it is translated correctly.

I increased the swappiness to 75 in the task definition file and it worked
![image](https://user-images.githubusercontent.com/3018412/80211916-f36da480-860c-11ea-8256-7e3385166848.png)

**Comment by fierlion** [comment]
Am having some difficulty replicating the issue.
I'm using the ecs-agent v1.39.0 with the Amazon ECS-optimized Amazon Linux 2 AMI.
I followed the same instructions above to set up my swap space (except I went to the source link from redhat at the bottom of the page https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/5/html/deployment_guide/s1-swap-adding#s2-swap-creating-file)

I configured a c5.large with 2GB swap
To be sure all is working, I tested eating up some of my memory:
first I set swap to be chatty:
`sudo swapon --all --verbose`
I then ran `top` and in separate session on the instance ran `echo {1..1000000000}` to eat up memory:
```
top - 23:44:30 up 11 min,  1 user,  load average: 0.60, 0.21, 0.09
Tasks:  90 total,   1 running,  55 sleeping,   0 stopped,   0 zombie
%Cpu(s):  0.0 us,  0.2 sy,  0.0 ni, 99.7 id,  0.2 wa,  0.0 hi,  0.0 si,  0.0 st
KiB Mem :  3793612 total,  3595744 free,    81848 used,   116020 buff/cache
KiB Swap:  2097148 total,  1819584 free,   277564 used.  3534912 avail Mem
```
confident that I have swap configured, I pulled out a simple taskdef with a `busybox sleep 600` command and added some swap config:
```
    "linuxParameters": {
        "maxSwap": 1024,
        "swappiness": 75
    },
```
from the `docker inspect` of my running container instance:
```
    "MemoryReservation": 0,
    "MemorySwap": 1388314624,
    "MemorySwappiness": 75,
```
I see what I am expecting to see here.

**Comment by fierlion** [comment]
I'll need your help to repro what you're seeing.  Can you walk me through the exact steps you took to set up swap on the instance?  
I'd also appreciate as much detail in the rest of your ecs setup to try to replicate this issue on my end, as a more basic setup seems sound (just based on my experimentation).

**Comment by gberdugo** [comment]
I created another EC2 machine from scratch to make sure that my testing environment was clean.

So I've selected a t3a.nano instance with Amazon ECS-optimized Amazon Linux 2 AMI and kept almost everything with their default parameters during the EC2 creation wizard.

The only changes I made were: selected the 'ecsInstanceRole' as IAM role and put the following script (to add the EC2 machine to my ECS cluster) under User data:
```
#!/bin/bash
echo ECS_CLUSTER=bytebureau >> /etc/ecs/ecs.config
```

After that I ssh'ed to this machine, updated the system via ```sudo yum update``` and  configured the swap following the redhat link that you provided.

The output of the ```free``` command says that the swap was enabled:
![image](https://user-images.githubusercontent.com/3018412/80524783-8c325600-8966-11ea-9da8-6f3bb1607ed8.png)

After that I tried to reproduce your test first creating a taskdefinition as following:
```
aws ecs register-task-definition --family sleep360 --container-definitions "[{\"name\":\"sleep\",\"image\":\"busybox\",\"cpu\":10,\"command\":[\"sleep\",\"360\"],\"memory\":10,\"essential\":true,\"linuxParameters\":{\"maxSwap\":1024,\"swappiness\":75}}]" --placement-constraints "[{\"expression\":\"ec2InstanceId == i-07a2aa46567bbc2fc\",\"type\":\"memberOf\"}]"
```
And then running a task:
```
aws ecs run-task --cluster bytebureau --task-definition sleep360:1 --count 1
```
This procedure worked. The container running busybox was created with the correct swap information.
So I followed the same procedure but with my image...first I created the taskdef:
```
aws ecs register-task-definition --family bytebureau-frontend-test --network-mode host --placement-constraints "[{\"expression\":\"ec2InstanceId == i-07a2aa46567bbc2fc\",\"type\":\"memberOf\"}]" --container-definitions "[{\"name\": \"web\",\"image\": \"370999586507.dkr.ecr.us-east-1.amazonaws.com/bytebureau-frontend:master-latest\",\"memoryReservation\": 128,\"linuxParameters\":{\"maxSwap\":1024,\"swappiness\":75},\"portMappings\": [{\"hostPort\": 80,\"containerPort\": 80,\"protocol\": \"tcp\"}],\"command\": [\"nginx\"],\"essential\": true,\"workingDirectory\": \"/app\",\"healthCheck\": {\"command\": [\"CMD-SHELL\",\"curl -f http://localhost:80/health-check || exit 1\"]}}]"
```
Then I created the task:
```
aws ecs run-task --cluster bytebureau --task-definition bytebureau-frontend-test:2 --count 1
```

But this time It did not work...the container was created only with the memory swappiness configuration and no memory swap
```
"MemoryReservation": 134217728,
"MemorySwap": 0,
"MemorySwappiness": 75
```

After some other tests, I discovered that when I register a taskdef without the memory configuration, the maxSwap configuration is ignored and the container is created with MemorySwap: 0.
In my case, I was only specifying the memoryReservation.

The only question left is: Is this an expected behaviour? Because the ECS documentation says neither the memory attribute nor the memoryReservation are required.

Thanks for the help!

**Comment by fierlion** [comment]
That was a perfect walkthrough!  Thank you!

This is expected behavior.
a quick quote from the docker docs about this:
```
--memory-swap is a modifier flag that only has meaning if --memory is also set. Using swap allows the container to write excess memory requirements to disk when the container has exhausted all the RAM that is available to it.  
```
https://docs.docker.com/config/containers/resource_constraints/#--memory-swap-details

I think this is why you're seeing the memorySwap configuration ignored.
Let me know if you have further questions.

**Comment by gberdugo** [comment]
I see now...I will adjust my taskdefs to use the memory configuration

Thanks a lot for your help and sorry any inconvenience!

**Comment by Kidist-Abraham** [comment]
@fierlion Shouldn't it be working if I only specify memory on the task definition but not on the container definition?
