### ISSUE TITLE
anyway to send raw task definition to ecs-agent

### ISSUE THREAD

**Issue by wallnerryan** [aws/amazon-ecs-agent#244]
Looking for a way to send a raw task definition to the ECS Agent rest API to test something out locally on an upgraded custom agent.

e.g. Can we post to ```127.0.0.1:51678/v1/tasks```?

**Comment by euank** [comment]
Right now there's not a great way to do so.
We wouldn't be opposed to a mechanism to do so for testing, but don't have any solution to this handy.
If you've got any ideas or want to contribute something like this, I'd be happy to discuss that further.

There's an additional bit of complexity here: the actual information that ends up being passed to the Agent is not just a task definition, but rather a [Task](https://github.com/aws/amazon-ecs-agent/blob/v1.6.0/agent/acs/model/ecsacs/api.go#L530) struct that has already been transformed somewhat from the original task definition.

For unit testing, there is a [mock websocket server](https://github.com/aws/amazon-ecs-agent/blob/v1.6.0/agent/acs/client/acs_client_test.go#L172), but I think you're asking for something more powerful.

Best,
Euan

**Comment by wallnerryan** [comment]
@euank thanks for your response. Yes, something more powerful indeed. I have been looking at what I would take to get volumeDriver minimally working. To do this, I was hoping not to have to make changes to CLI portions that parse JSON/compose files and would say it is unsupported. I can unit test changes, but real world testing would be nice via a more powerful mechanism.

**Comment by samuelkarp** [comment]
@wallnerryan I'm going to close this for now, but we're happy to continue discussing this if you're still looking for help here.
