### ISSUE TITLE
Update Locked Issue w/ Links to Correct Info

### ISSUE THREAD

**Issue by ambsw-technology** [aws/amazon-ecs-agent#2440]
#1128 is an old (circa 2018) issue related to ECR access.  It still ranks highly in searches.  With the [introduction of ECR PrivateLink](https://www.infoq.com/news/2019/02/aws-privatelink-ecr-ecs/) in Feb of 2019, the information in this issue is now out-of-date.  Can a collaborator add a post with the link to this announcement and to the more informative VPC Endpoint Guides:

 - ECS https://docs.aws.amazon.com/AmazonECS/latest/developerguide/vpc-endpoints.html
 - ECR https://docs.aws.amazon.com/AmazonECR/latest/userguide/vpc-endpoints.html

**Comment by ellenthsu** [comment]
The old issue has been updated with the relevant information, thank you for bringing this to our attention
