### ISSUE TITLE
ECS Windows task stays in PENDING indefinitely when kernel versions don't match

### ISSUE THREAD

**Issue by nonspecialist** [aws/amazon-ecs-agent#2466]
### Summary
When ECS agent reports `[CannotPullContainerError] a Windows version 10.0.18363-based image is incompatible with a 10.0.17763 host` the ECS Task remains in PENDING indefinitely. The task should probably go into STOPPED and propagate the error, similar to other CannotPullContainerErrors

### Description
When using Windows ECS hosts with `isolation-mode=process` (the default), the windows kernel version must match the version of the kernel that the Docker image was built against. For example, a windows 1809 EC2 instance cannot pull or run a Docker image built on a 1909 base.

When attempting to run a 1909-base container on an 1809 worker, the ECS task is scheduled onto an available instance, and goes into the PENDING state but never progresses.

The ECS Agent log from `c:\programdata\Amazon\ECS\log\ecs-agent.log` shows lines similar to:

```
level=warn time=2020-06-01T06:24:49Z msg="DockerGoClient: Error while pulling image docker-repo.example.com/service:1.0.0: a Windows version 10.0.18363-based image is incompatible with a 10.0.17763 host" module=docker_client.go
level=error time=2020-06-01T06:24:49Z msg="DockerGoClient: failed to pull image docker-repo.example.com/service:1.0.0: [CannotPullContainerError] a Windows version 10.0.18363-based image is incompatible with a 10.0.17763 host"
 module=docker_client.go
```

This will never succeed, and the task should not remain in PENDING

### Expected Behavior
Windows tasks where kernel version of Docker image does not match ECS instance host should rapidly enter STOPPED state, instead of remaining in PENDING forever.

### Observed Behavior
Tasks remain in PENDING forever

### Environment Details
* AMI (in `ap-southeast-2`): `ami-0de1f2a7d042bccbc` (Windows_Server-2019-English-Core-ECS_Optimized-2020.05.14)
* ECS Agent version: 1.39.0
* docker info:
```
Client:
 Debug Mode: false
 Plugins:
WARNING: Plugin "C:\\Program Files\\Docker\\cli-plugins\\docker-cluster.exe" is not valid: failed to fetch metadata: exit status 1

Server:
 Containers: 19
  Running: 2
  Paused: 0
  Stopped: 17
 Images: 3
 Server Version: 19.03.5
 Storage Driver: windowsfilter
  Windows:
 Logging Driver: json-file
 Plugins:
  Volume: local
  Network: ics internal l2bridge l2tunnel nat null overlay private transparent
  Log: awslogs etwlogs fluentd gcplogs gelf json-file local logentries splunk syslog
 Swarm: inactive
 Default Isolation: process
 Kernel Version: 10.0 17763 (17763.1.amd64fre.rs5_release.180914-1434)
 Operating System: Windows Server 2019 Datacenter Version 1809 (OS Build 17763.1217)
 OSType: windows
 Architecture: x86_64
 CPUs: 4
 Total Memory: 15.71GiB
 Name: EC2AMAZ-397VAEQ
 ID: 3DSH:2HDP:2EJ7:N2EA:SFPS:E2U4:KFSZ:AFOZ:Y5IP:UJIE:QXDF:5UUJ
 Docker Root Dir: C:\ProgramData\docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

**Comment by mythri-garaga** [comment]
Can you please provide the following information? You can send these details to ecs-agent-external@amazon.com
- ARNs of tasks that are stuck in PENDING 
- Debug level logs from relevant time when tasks were affected
