### ISSUE TITLE
Errors will happen when upgrading the libraries

### ISSUE THREAD

**Issue by KateGo520** [aws/amazon-ecs-agent#2488]
## An error will happen when upgrading libraries _containerd/cgroups_, _prometheus/client_golang_ :

For example----
### github.com/containerd/cgroups  
-Latest Version: Master branch，latest commit 80c669f   (Latest commit 80c669f 10 days ago)
-Where did you use it: 
https://github.com/aws/amazon-ecs-agent/search?q=containerd%2Fcgroups&unscoped_q=containerd%2Fcgroups 
-Detail: 
>[github.com/containerd/cgroups/go.mod](https://github.com/containerd/cgroups/blob/master/go.mod#L7)
```
module github.com/containerd/cgroups
go 1.13
require (
	github.com/coreos/go-systemd/v22 v22.0.0
	github.com/cpuguy83/go-md2man/v2 v2.0.0 // indirect
	github.com/godbus/dbus/v5 v5.0.3
	…
) 
```
>[github.com/containerd/cgroups/systemd.go](https://github.com/containerd/cgroups/blob/master/systemd.go#L25)
```
package cgroups
import (
	systemdDbus "github.com/coreos/go-systemd/v22/dbus"
	"github.com/godbus/dbus/v5"
	…
) 
```
This problem was introduced since **_containerd/cgroups commit 06e7180 on 21 Dec 2019 _** . If you try to upgrade  **containerd/cgroups** to commit `06e7180` on 21 Dec 2019 and **above**, you will get an error--- **_no package exists at "github.com/coreos/go-systemd/v22" and "github.com/godbus/dbus/v5"_**

Similar issues can also happen when upgrading libraries [**_prometheus/client_golang_**](https://github.com/prometheus/client_golang/blob/v1.6.0/go.mod#L5) .

## I investigated the libraries' (**containerd/cgroups**, **prometheus/client_golang**) release information and found the root cause of this issue is that---- 
1.	These dependencies all added [Go modules](https://github.com/golang/go/wiki/Modules) in the recent versions.

2.	They all comply with the specification of "Releasing Modules for v2 or higher" available in the Modules documentation. Quoting the specification:
> A package that has migrated to Go Modules _must_ include the major version in the import path to reference any v2+ modules. For example,  Repo github.com/my/module migrated to Modules on version v3.x.y.  Then this repo should declare its module path with MAJOR version suffix "/v3"  (e.g., module `github.com/my/module/v3`), and its downstream project should use `"github.com/my/module/v3/mypkg"` to import this repo’s package.

3.	This "github.com/my/module/v3/mypkg" is not the `physical path`. So earlier versions of Go (including those that don't have minimal module awareness) plus all tooling (like dep, glide, govendor, etc) don't have `minimal module awareness` as of now and therefore don't handle import paths correctly See [golang/dep#1962](https://github.com/golang/dep/issues/1962), [golang/dep#2139](https://github.com/golang/dep/issues/2139).
> Note: creating a new branch is not required. If instead you have been previously releasing on master and would prefer to tag v3.0.0 on master, that is a viable option. (However, be aware that introducing an incompatible API change in master can cause issues for non-modules users who issue a go get -u given the go tool is not aware of semver prior to Go 1.11 or when module mode is not enabled in Go 1.11+).
> Pre-existing dependency management solutions such as dep currently can have problems consuming a v2+ module created in this way. See for example dep#1962.
https://github.com/golang/go/wiki/Modules#releasing-modules-v2-or-higher

### 1. Migrate to Go Modules.
Go Modules is the general trend of ecosystem, If you want a better upgrade package experience, migrating to Go Modules is a good choice.

### 2. Keep using the dependency manage tool (like dep, glide, govendor, etc).

Because the import paths have different meanings between the projects adopting module mechanism and the non-module mechanism. 

* https://github.com/golang/go/wiki/Modules#semantic-import-versioning
* https://golang.org/cmd/go/#hdr-Module_compatibility_and_semantic_versioning
* https://github.com/golang/go/wiki/Modules#releasing-modules-v2-or-higher

If you prefer to use the dependencies manage tool (like dep, glide, govendor, etc), a textbook example provided by repo `github.com/moby/moby` can prevent this type of issues.
https://github.com/moby/moby/blob/master/VENDORING.md
https://github.com/moby/moby/blob/master/vendor.conf
In the vendor directory, `github.com/moby/moby` adds the **/vN** subdirectory in the corresponding dependencies.
**This will help more downstream modules to work well with your package, otherwise they will be stuck in github.com/coreos/go-systemd v21 , github.com/cespare/xxhash v1.1.0, github.com/godbus/dbus v4.1.0 .**

Do you plan to upgrade the libraries in near future?
Hope this issue report can help you ^_^
Thank you very much for your attention.
Best regards,
Kate

**Comment by KateGo520** [comment]
@fenxiong  @sparrc  Could you help me review this issue? Thx :p

**Comment by KateGo520** [comment]
@sparrc  @mssrivas    Could you help me review this issue? Thx :p

**Comment by petderek** [comment]
Thanks for bringing this to our attention. We're aware of this and I've opened #2490 to ensure we're tracking this publicly. 

Is there something you're trying to do with agent that's being blocked by our migration?

**Comment by KateGo520** [comment]
@petderek Thank very much for your reply. This report is a warm prompt for you to prevent or combat this issue. Just let you know the problem if you upgrade this dependency in near future.

I feel happy to see that this report can help you :p
Thanks again.
Kate

**Comment by yunhee-l** [comment]
We are working on this, and tracking via https://github.com/aws/amazon-ecs-agent/issues/2490. I am going to resolve this as duplicate, please feel free to add any concerns/questions on the tracking issue.
