### ISSUE TITLE
"dnsServers" and "dnsSearchDomains" not updating dns

### ISSUE THREAD

**Issue by kyriesent** [aws/amazon-ecs-agent#249]
Hi,

I'm trying to get my containers to run against a custom dns server, but it doesn't seem to be working.

I've looked over the conf a bunch of times and it doesn't seem to be working correctly.

I've included my Dockerrun.aws.json for reference.

```
{
  "AWSEBDockerrunVersion": 2,
  "containerDefinitions": [
    {
      "name": "skills_map",
      "image": "seelio/skills-map:34716a798e9c51392995525ca1f54d7274b65dc5",
      "dnsServers": [
        "11.0.0.71",
        "8.8.8.8"
      ],
      "dnsSearchDomains": [
        "service.consul"
      ],
      "memory": 128,
      "essential": true
    },
    {
      "name": "skills_map_web_ui",
      "image": "seelio/skills-map-web-ui:34716a798e9c51392995525ca1f54d7274b65dc5",
      "dnsServers": [
        "11.0.0.71",
        "8.8.8.8"
      ],
      "dnsSearchDomains": [
        "service.consul"
      ],
      "memory": 128,
      "essential": true
    }
  ]
}
```

Running `docker inspect` on the resulting container says that there are no Dns or DnsSearch options set, and this is what's in /etc/resolv.conf

```
; generated by /sbin/dhclient-script
search ec2.internal
nameserver 11.0.0.2
```

Thanks!

**Comment by sebest** [comment]
I can confirm that this feature does not seem to work with agent version 1.6 on Elasticbeanstalk with the latest image.

**Comment by samuelkarp** [comment]
@kyriesent @sebest My colleagues have informed me that `dnsServers` and `dnsSearchDomains` should work with AWS Elastic Beanstalk now.
