### ISSUE TITLE
Use go modules and go 1.14/1.15

### ISSUE THREAD

**Issue by petderek** [aws/amazon-ecs-agent#2490]
### Summary

Its 2020, time to update to go modules! We should update our build system to use the latest Go version available in AL2 as well.

### Expected Behavior
I can update my dependencies and `go build` easily without installing a 3rd party dependency manager. :muscle: 

### Observed Behavior
I have to install a 3rd party dependency manager. :frowning_face: 

### Environment Details

This should be tested:
- in travis
- in codebuild
- on a mac
- on a linux machine
- on/off amazon's corp

**Comment by yunhee-l** [comment]
work in progress: https://github.com/aws/amazon-ecs-agent/pull/2493

**Comment by petderek** [comment]
[1.15 was just released](https://blog.golang.org/go1.15), meaning 1.13 is [no longer supported](https://golang.org/doc/devel/release.html#policy).

**Comment by mythri-garaga** [comment]
Updated to Go 1.15 in #2660

**Comment by fierlion** [comment]
I'm currently testing this:
in github action (in place of travis)
in codebuild
on a mac
on a linux machine
on/off amazon's corp

**Comment by fierlion** [comment]
on a fresh ec2 instance I ran:
```
sudo yum -y install gcc git aws-cli wget rpm-build
GOVERSION="1.15"
GOLANG_TAR="go${GOVERSION}.linux-amd64.tar.gz"
wget -O /tmp/${GOLANG_TAR} https://storage.googleapis.com/golang/${GOLANG_TAR}
sudo tar -C /usr/local -xzf /tmp/${GOLANG_TAR}
mkdir -p ~/go/bin
mkdir -p ~/go/src
```
I added the following to my .bash_profile:
```
export GOROOT=/usr/local/go
export GOPATH=$HOME/go
export GOBIN=$GOPATH/bin
export PATH=$PATH:$GOROOT/bin:$GOBIN
```
then I ran:
```
source ~/.bash_profile
go get github.com/aws/amazon-ecs-agent && cd ~/go/src/github.com/aws/amazon-ecs-agent
go build -installsuffix cgo -a -ldflags ' -s' -o out/amazon-ecs-agent ./agent/
```
and a new agent was built.

I also tested on mac with the same golang setup -- downloaded go 1.15.7 (latest)
```
source ~/.bash_profile
go get github.com/aws/amazon-ecs-agent && cd ~/go/src/github.com/aws/amazon-ecs-agent
go build -installsuffix cgo -a -ldflags ' -s' -o out/amazon-ecs-agent ./agent/
```
also tested with codebuild and github actions.

**Comment by fierlion** [comment]
note this is currently blocked by issues related to versioning as it relates to go modules.

**Comment by fierlion** [comment]
Closing for now.  This is not on our roadmap.
