### ISSUE TITLE
ECS Agent Support for SecretBinary values

### ISSUE THREAD

**Issue by parikshitataws** [aws/amazon-ecs-agent#2509]
### Summary

Currently ECS agent injects blank value in container if Secret value is "SecretBinary" 

### Description

Create binary secret value like this and try to use in task definition to inject valueFrom secret ARN created as below : 

aws secretsmanager create-secret --name <secret-name> --secret-string <secret-value>

### Expected Behavior
ECS agent should inject get  binary value and inject in the container. it should complain about "SecretBinary" if not supported.

If this is not going to be supported feature then should have covered in public documentation. 

### Observed Behavior
Currently ECS agent injects blank value because current implementation only supports "SecretString", 

https://github.com/aws/amazon-ecs-agent/blob/782948476da6d995ad33c6a04130f8172820af27/agent/asm/asm.go#L100

**Comment by cyastella** [comment]
Thanks for submitting this issue, we will look into this.

**Comment by petderek** [comment]
This isn't something we will be able to support with our current strategy where we make secrets available as environment variables. Environment variables not going to be compatible with binary data.

Our [documentation](https://docs.aws.amazon.com/AmazonECS/latest/developerguide/specifying-sensitive-data-secrets.html)  includes: 

> Only secrets that store text data, which are secrets created with the SecretString parameter of the CreateSecret API, are supported. Secrets that store binary data, which are secrets created with the SecretBinary parameter of the CreateSecret API are not supported. 

Could you specify which doc/guide you are following that needs to be amended? That's definitely something we can fix quickly.

**Comment by parikshitataws** [comment]
Above documentation update should address this request. We can close this issue.

**Comment by jakub-bochenski** [comment]
> This isn't something we will be able to support with our current strategy where we make secrets available as environment variables. Environment variables not going to be compatible with binary data.

JSON doesn't support binary data either, yet AWS API provides the binary data encoded in base64. 
Why can't ECS do the same?
