### ISSUE TITLE
Amazon ECS Optimized Image to enable Docker logs for Application monitoring

### ISSUE THREAD

**Issue by kodeeshm** [aws/amazon-ecs-agent#2515]
### Summary
Docker logs to be enabled on Amazon ECS optimized windows core agents to figure out why containers getting drained with 'exit 0'

### Description

Hello Team,
We are using the latest Windows_Server-2019-English-Core-ECS_Optimized-2020.06.11 (ami-0fdbc44c621e81a27) which does not gives us any opportunity to look out application related issues inside the docker containers.

The containers getting killed with 'essential container in task exited' and 'Exit  0' from the Details tab

docker logs <container_id> returns blank
It would be helpful if there are other workarounds to figure what containers goes through when they are getting drained. We have already looked at event logs and ecs-agent logs that shows only about what ECS functionality is doing.

### Expected Behavior
docker logs <container_id> to return application log from containers

### Observed Behavior
docker logs <container_id> returns blank

**Comment by cyastella** [comment]
Thanks for submitting this, we will look at it.

**Comment by kodeeshm** [comment]
Hi Guys,
Does Cloudwatch log drivers support with Windows latest AMI images ?
Windows_Server-2019-English-Core-ECS_Optimized-2020.06.11

If so, Would it work if I simply enable logconfiguration in container definition ?
Or
Do I have to do anything else like adding logdriver installation in the EC2-User data ?

**Comment by ubhattacharjya** [comment]
Hi @kodeeshm ,

You can configure awslogs (AWS cloudwatch log driver) in your windows ECS task definition which will show you container application logs.
Ref: https://docs.aws.amazon.com/AmazonECS/latest/developerguide/using_awslogs.html

This functionality is supported in both linux and windows.

If you are facing problems configuring awslogs, kindly reach out to us at ecs-agent-external@amazon.com with debug level ecs agent logs.

Utsa

**Comment by ubhattacharjya** [comment]
Hi @kodeeshm ,

I am closing this issue. Kindly reopen this issue if you are facing problems.

Regards,
Utsa

**Comment by kodeeshm** [comment]
Thanks for your response!
