### ISSUE TITLE
Publish region-specific ECR public repos for ecs-agent image

### ISSUE THREAD

**Issue by jhmartin** [aws/amazon-ecs-agent#2526]
### Summary
Launching ecs-agent out of Dockerhub relies on Dockerhub availability, for which most ECS users will not have a support relationship.  Publish the ECS agent in all of the region-specific ECR repositories in the same way as https://github.com/aws/aws-for-fluent-bit. 

### Description
AWS has the infrastructure to host the ECS Agent image on per-region ECR repositories. This should be done to remove the requirement that Dockerhub be available to launch new nodes. This is particularly important in an autoscaling scenario.  AWS customers have a commercial relationship with AWS so can reasonably expect support for the availability of ECR, not so much with Dockerhub.

https://github.com/aws/aws-for-fluent-bit already does something similar.

**Comment by yunhee-l** [comment]
Thank you for submitting this. Since this is a feature request, I have moved it to our roadmap repo, linked above, to be tracked. Resolving this.
