### ISSUE TITLE
WorkingDirectory regexp is not sufficient (should allow all unix paths)

### ISSUE THREAD

**Issue by cultureulterior** [aws/amazon-ecs-agent#254]
`# sudo docker run -it  -w /etc/console-setup ubuntu /bin/bash` works

`# aws --region eu-west-1 ecs register-task-definition --family test  --cli-input-json  file://bar.json` doesn't work.

````json
{
  "containerDefinitions": [
    {
      "name": "sleep",
      "image": "ubuntu",
      "cpu": 10,
      "workingDirectory":"/etc/console-setup",
      "command": [
        "/bin/sleep",
        "360"
      ],
      "memory": 10,
      "essential": true
    }
  ],
  "family": "sleep 360"
}
````

Aws::ECS::Errors::ClientException: workingDirectory contains invalid characters, does not match pattern ^[/a-zA-Z0-9.]*$

**Comment by dquiles-handy** [comment]
+1

**Comment by samuelkarp** [comment]
@cultureulterior Thank you for reporting this issue.  We've fixed the validation and a working directory with a dash should no longer cause an error.
