### ISSUE TITLE
ignore docker exec commands

### ISSUE THREAD

**Issue by skippy** [aws/amazon-ecs-agent#257]
can you add `exec_start` to the list of docker commands to ignore?

https://github.com/aws/amazon-ecs-agent/blob/master/agent/engine/docker_container_engine.go#L579

also, that log statement should really be a debug cmd; I'm getting a flood of these msgs in the logs because I use `docker exec` to do a healthcheck within a docker container.

**Comment by euank** [comment]
#256 includes both of the changes you suggest. I'd expect the next release to include it and thus resolve this.

Thanks for the information and apologies for the logspam,
Euan

**Comment by skippy** [comment]
np!  thanks for the update!
