### ISSUE TITLE
Mounting EFS results in "context deadline exceeded"

### ISSUE THREAD

**Issue by twigs67** [aws/amazon-ecs-agent#2570]
Hello,

I'm attempting to use EFS with ECS. I have created the instance with a launch template that already mounts EFS to the EC2 instance via user data. 

When creating the task definition, I set the mount type to EFS with the root path set to "mnt/efs" (where it's mounted on the the EC2 instance). However, each time I get the error:

```
Error response from daemon: create ecs-simple-server-16-configs-faf8bc8696dee78e3e00: Post http://%2Frun%2Fdocker%2Fplugins%2Famazon-ecs-volume-plugin.sock/VolumeDriver.Create: context deadline exceeded
```

I'm wondering what this means? I couldn't find any information on this error. 

Thanks

**Comment by petderek** [comment]
Hey ,

Sorry you're seeing this error. In my experience, this typically means that there is a security group mismatch between the EFS mount target and the EC2 instance (or Task ENI if using awsvpc mode). Double check those settings.

If you still see issues, check out the ecs agent log and also the contents of `/var/log/ecs/ecs-volume-plugin.log`. You can send those logs, and your task definition to ecs-agent-external@amazon.com and we can help diagnose.

> I set the mount type to EFS with the root path set to "mnt/efs" (where it's mounted on the the EC2 instance)

The root path is the path that gets mounted inside the EFS filesystem. You don't need to pre-mount EFS on the EC2 instance, ECS manages the mounting for you when using `efsVolumeConfiguration`.  You can likely leave that parameter blank.

**Comment by twigs67** [comment]
@petderek thanks or responding. You were right, it turned out to be security group mismatch. I appreciate the timely response.
