### ISSUE TITLE
License path returns 500 error

### ISSUE THREAD

**Issue by bacoboy** [aws/amazon-ecs-agent#2604]
If you query the ecs agent on port 51678 you get a list of available commands:

```
$ curl localhost:51678/
{"AvailableCommands":["/v1/metadata","/v1/tasks","/license"]}
```

If you query the license path you get a 500 internal server error rather than a valid response:

```
$ curl -v localhost:51678/license
*   Trying 127.0.0.1...
* TCP_NODELAY set
* Connected to localhost (127.0.0.1) port 51678 (#0)
> GET /license HTTP/1.1
> Host: localhost:51678
> User-Agent: curl/7.58.0
> Accept: */*
>
< HTTP/1.1 500 Internal Server Error
< Date: Wed, 02 Sep 2020 16:57:08 GMT
< Content-Length: 0
<
* Connection #0 to host localhost left intact
```

[Looking at the code](https://github.com/aws/amazon-ecs-agent/blob/e483a922586c248e886404d4aa6ac395b5407e28/agent/handlers/v1/license_handler.go#L26-L34) it appears to be bombing out on this function -- either because `GetText` returns an error or possibly elsewhere:
```
// LicenseHandler creates response for '/license' API.
func LicenseHandler(w http.ResponseWriter, h *http.Request) {
	text, err := licenseProvider.GetText()
	if err != nil {
		w.WriteHeader(http.StatusInternalServerError)
	} else {
		w.Write([]byte(text))
	}
}
```

My expectation is that this returns a valid 200 `json` response like the other paths: `/v1/metadata` for instance:

```
$ curl -v localhost:51678/v1/metadata
*   Trying 127.0.0.1...
* TCP_NODELAY set
* Connected to localhost (127.0.0.1) port 51678 (#0)
> GET /v1/metadata HTTP/1.1
> Host: localhost:51678
> User-Agent: curl/7.58.0
> Accept: */*
>
< HTTP/1.1 200 OK
< Content-Type: application/json
< Date: Wed, 02 Sep 2020 17:04:55 GMT
< Content-Length: 188
<
* Connection #0 to host localhost left intact
{"Cluster":"my-cluster-rocks","ContainerInstanceArn":"arn:aws:ecs:us-east-1:123456789012:container-instance/11111111-2222-3333-4444-55555555","Version":"Amazon ECS Agent - v1.44.1 (1f05fbf0)"}
```

**Comment by fierlion** [comment]
On a new AL2 ECS-Optimized AMI with 1.44.3 Agent I am able to run
`curl localhost:51678/license | less`
and it returns:
```
Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
...
```
Can you give me some more detail on what your environment looks like?  
Are you using an ECS-Optimized AMI?  If so, which one?
What is your host network configuration?

**Comment by bacoboy** [comment]
We are using an ubuntu custom AMI, not the ECS-Optimized AMI as documented [here](https://docs.aws.amazon.com/AmazonECS/latest/developerguide/launch_container_instance.html).

The ECS agent is pre-baked into the AMI rather than using the auto-upgrading dockerized version.
Is the license text baked into the docker container rather than the app?

**Comment by fierlion** [comment]
thanks for the environment details.

> The ECS agent is pre-baked into the AMI rather than using the auto-upgrading dockerized version.
Is the license text baked into the docker container rather than the app?

I'm going to try to repro what happens with the license text in this non-containerized scenario.

As a side-note, I'd be curious to know if you see any other discrepancies when running ecs-agent directly at host level rather than inside a container with ecs-init.

Are you using Ubuntu's default init system (upstart) to manage the ecs-agent process directly?

**Comment by samuelkarp** [comment]
> Is the license text baked into the docker container rather than the app?

Yes, see [here](https://github.com/aws/amazon-ecs-agent/blob/33b647b81e3597600585eed883017c22f3c2b916/scripts/dockerfiles/Dockerfile.release#L19).

**Comment by fierlion** [comment]
There's your answer.
Thanks @samuelkarp
As you mentioned, we officially support ECS Agent in the documented context, running in a container and overseen by ecs-init (https://github.com/aws/amazon-ecs-init)
If you need the license for your purposes, it is distributed as part of this ecs-agent repository: https://github.com/aws/amazon-ecs-agent/blob/master/LICENSE
given the above dockerfile's placement, it is referenced here:
https://github.com/aws/amazon-ecs-agent/blob/master/agent/utils/license.go#L27-L29

Please let me/us know if you have questions.

**Comment by bacoboy** [comment]
Yup.  Looks like I'm missing the 3 license files when I create my AMI.  I'll have to think about how I want to install those given the relative paths used to find them -- I'm certainly not gonna stick them in `/usr/bin` along with `/usr/bin/ecsagent` so I'll need to think on that 🤔 

Regarding how well it works outside of the container, I can tell you it has been just fine for the last 4 years we've had it production this way.  We did it this way 'cause we are trying to practice immutable infrastructure and having one of the EC2 services self-updating like the ECS agent does is contrary to that goal.  If we make ANY change to the server, it is a new image.  In this way we can always roll back to a know good type.  So when the introspection bug #2603 was introduced in 1.44.2 and our ASG health check against `HTTP:51678/v1/metadata`, the new servers were rejected as "unhealthy" and we continued to run on the existing 1.44.1 servers.

After all, we go thru the trouble of stamping out known stacks of code in Docker containers, why should we treat the EC2 boxes any differently? (not looking for a flame war - yes daily security patches are the exception).

In order to run the agent in this way we use cloud-init to lay down a `/etc/ecs/ecs.conf` configuration file (per the docs) using your favorite templating tool (such as [confd](https://github.com/kelseyhightower/confd)).  We bake in the version of docker we want on the box using [packer](https://www.packer.io/) -- along with everything else (that includes the `ecsagent` binary and the iptable rules) and our systemd file (ubuntu for us) looks like this:

```
[Unit]
Description=Amazon ECS Agent
After=docker.service

[Service]
EnvironmentFile=-/etc/ecs/ecs.conf
ExecStart=/usr/bin/amazon-ecs-agent
Restart=always
RestartSec=30s
Type=simple
NotifyAccess=all

[Install]
WantedBy=multi-user.target

```

`ecs-init` is NOT used at all.  Most of what you do at boot time with that tool, we do at packer build time -- leaving only the cluster name as the only piece of boot-time configuration -- again, all other decisions on configuration of ecs, docker, etc. were made ahead of time in the AMI building stage.

Since we are vigilant about replacing servers often and upgrading/patching to latest as much as we can, this works for us.  YMMV.

Hope this helps.  I guess we can close this as an error in my packaging.  Still would have preferred to have the license baked into the static binary, but understand why it is the way it is.

Thanks for the clarification!

**Comment by samuelkarp** [comment]
@bacoboy [Bottlerocket](https://aws.amazon.com/bottlerocket) also runs the ECS agent outside a container, directly managed by systemd.  We applied a patch to change a number of the filesystem paths where the agent expects to find things, including the license files.  You can see that patch [here](https://github.com/bottlerocket-os/bottlerocket/blob/f06359dc218f8fd45e2b926b813e78836fc515ab/packages/ecs-agent/0001-bottlerocket-default-filesystem-locations.patch).  You may also be interested in our [unit file](https://github.com/bottlerocket-os/bottlerocket/blob/f06359dc218f8fd45e2b926b813e78836fc515ab/packages/ecs-agent/ecs.service) which has a couple of things I'd recommend, including making sure to set `ECS_CHECKPOINT=true` and `RestartPreventExitStatus=5`.

**Comment by fierlion** [comment]
@bacoboy thank you for you rundown of how you're using the host-level ECS Agent.  

> If we make ANY change to the server, it is a new image. In this way we can always roll back to a know good type.

It's great to see an example of how exercising immutable infrastructure lets you avoid down time by allowing the option to roll back to a known healthy image.
I plan on bringing up some of what you've mentioned here in our team discussions.

Again, thank you for letting all of us know how you're making these patterns work.
