### ISSUE TITLE
Task stopped even though container correctly handles OOM

### ISSUE THREAD

**Issue by alexmac** [aws/amazon-ecs-agent#261]
I'm able to repro a bug where a container encounters an OOM but handles it gracefully and stays running, however ECS appears to treat the OOM event from docker as indicating that the container is now stopped even though it is still running.

I'm running docker 1.9.0 (git hash 1eb2921) and ECS agent 1.6.0 on the latest Amazon linux EC2 image.

Here are the clues that lead me to the conclusion mentioned above:

1) Shortly after the OOM I see a call to "GET /v1.22/events?since=1449207659&until=1449207679" in the docker log. Running this manually with curl shows my postgres container encountered the oom state:

{"status":"oom","id":"d47dd049d534851e6124cc3d08e8527ebc47da649872e11c1fedd51765d4dc5b","from":"repos.fbn.internal/webdb:minimal","time":1449207679,"timeNano":1449207679758147177}

2) At the same time I see the ECS agent log claim that my container has gone from running->stopped, and then starts to issue STOP requests to all the other essential containers in the task:

2015-12-04T05:41:19Z [INFO] Adding event module="eventhandler" change="ContainerChange: arn:aws:ecs:us-west-2:699897246896:task/a93712d2-0aa9-4491-94ed-f65c5ec21aab WebDB -> STOPPED, Exit 0, , Ports [{5432 9300 0.0.0.0 0}], Known Sent: RUNNING"

3) if I run "docker ps" in another console I see my postgres container running just fine, but the logs do show that one of the postgres child processes died and was re-spawned (note: the container was not re-run, there is no restart policy on it, and if I docker inspect it I see it is still running, with a RestartCount of 0)

**Comment by samuelkarp** [comment]
OOM is [currently treated as stopped](https://github.com/aws/amazon-ecs-agent/blob/34235e3b02eae6ff2248094654947c9167feae85/agent/engine/docker_container_engine.go#L558-L561).

The [Docker event state diagram](https://docs.docker.com/engine/reference/api/images/event_state.png) indicates that an OOM leads to the container dying, but it's certainly possible that we're handling this incorrectly.

If you can share a minimal reproduction of this problem with me, I'd be very interested in looking at it.

**Comment by samuelkarp** [comment]
@alexmac Thanks for reporting!  This does look like a bug in the Agent due to a misunderstanding of when Docker emits an OOM event.

**Comment by alexmac** [comment]
Ahh yes - https://github.com/docker/docker/issues/18433

**Comment by alexmac** [comment]
So I assume there are two possible fixes without requiring a newer version of docker:
1 - ECS should send a stop when it sees an OOM message just to be sure stale containers aren't left running
2 - After seeing an oom status for a container ECS should also check the actual status of the container to see if it is still running.

Can you give me an idea of what fix you are thinking of implementing and how important fixing this is relative to all the other work you no doubt have :)

Anything I can do to help just let me know, but I've not written a line of GO yet so I might not be able to give you a PR for this

**Comment by samuelkarp** [comment]
@alexmac, @euank just wrote a PR for this, which I'm starting to review now.

**Comment by alexmac** [comment]
Awesome, thanks! :beers:

**Comment by jbergknoff** [comment]
@alexmac you say you have "a container encounters an OOM but handles it gracefully and stays running". I'm interested in doing the same, but not finding much information on it. How do you manage it, e.g. Is there a signal sent to the process? Thanks.

**Comment by alexmac** [comment]
@jbergknoff I think I misread the logs - it was a docker exec command that failed with an OOM, the main process running in the docker container was unaffected. But you can write code that handles OOM - being run inside docker makes no difference to how you would do this

**Comment by raitalharehman** [comment]
i am deploying react app in development mode and facing 
error log
>The build failed because the process exited too early. This probably means the system ran out of memory or someone called `kill -9` on the process.
