### ISSUE TITLE
Update aws-sdk-go vendor package

### ISSUE THREAD

**Issue by singholt** [aws/amazon-ecs-agent#2621]
### Summary

The amazon-ecs-agent uses a vendor package for aws-sdk-go versioned [```1.27.0```](https://github.com/aws/amazon-ecs-agent/blob/master/agent/Gopkg.lock#L69) whereas the latest available version is [```1.34.19```](https://github.com/aws/aws-sdk-go/blob/master/CHANGELOG.md)

### Description

One of the diff that I could find is that in [```unmarshall.go``` ](https://github.com/aws/aws-sdk-go/blob/master/private/protocol/unmarshal.go), ```ResponseMetadata``` struct is missing in the agent's [current](https://github.com/aws/amazon-ecs-agent/blob/master/agent/vendor/github.com/aws/aws-sdk-go/private/protocol/unmarshal.go) version of aws-sdk-go package.

```
type ResponseMetadata struct {
	StatusCode int
	RequestID  string
} 
```

**Comment by fierlion** [comment]
https://github.com/aws/amazon-ecs-agent/pull/2627 <- pull request opened.  
We'll need to succeed all the unit/integ/functional tests.

**Comment by fierlion** [comment]
https://github.com/aws/amazon-ecs-init/blob/master/ecs-init/Gopkg.toml <- also need to update ecs-init aws-sdk-go

**Comment by fierlion** [comment]
note several tests are failing even with the 1.32.3 bump.  I'll need to troubleshoot these.  This might not make the next immediate release.

**Comment by singholt** [comment]
I was able to unblock myself by running ```dep ensure``` against the existing 1.27.0 version. closing this issue.
