### ISSUE TITLE
ENI Trunking is not working

### ISSUE THREAD

**Issue by atyutyunnik** [aws/amazon-ecs-agent#2669]
I have just the same issue as https://github.com/aws/amazon-ecs-agent/issues/2448 but I cannot re-open it, hence a new one. This is what I do:
```
aws ecs put-account-setting-default \
>       --name awsvpcTrunking \
>       --value enabled \
>       --region us-east-1
{
    "setting": {
        "name": "awsvpcTrunking",
        "value": "enabled",
        "principalArn": "arn:aws:iam::123456789012:root"
    }
}
```

but I am still getting that "resource:ENI" error on c5large

```
aws ecs list-account-settings
{
    "settings": []
}
```
and
```
aws ecs  list-attributes --target-type container-instance  --region us-east-1
{
    "attributes": []
}
```

**Comment by mssrivas** [comment]
Thank you for contacting us. could you please send us the agent logs and your task definition to ecs-agent-external@ please? Which version of agent are you using and which AMI ID?

**Comment by atyutyunnik** [comment]
> Thank you for contacting us. could you please send us the agent logs and your task definition to ecs-agent-external@ please? Which version of agent are you using and which AMI ID?

Agent version: 1.45.0
AMI: ami-032a827d612b78a50 
AMI location: amazon/amzn2-ami-ecs-hvm-2.0.20200928-x86_64-ebs

:/ Confused about the recipient:  ecs-agent-external@ ? Is this supposed to be an email address?

**Comment by mssrivas** [comment]
Thankyou for pointing. out. Fixed the email. Can you also try running 
aws ecs list-account-settings --effective-settings and aws ecs  list-attributes --target-type container-instance  --region us-east-1 --attribute-name ecs.awsvpc-trunk-id --cluster <ClusterName>

**Comment by atyutyunnik** [comment]
aws ecs list-account-settings --effective-settings --region us-east-1
```
{
    "settings": [
        {
            "name": "awsvpcTrunking",
            "value": "enabled",
            "principalArn": "arn:aws:iam::123456789012:root"
        },
        {
            "name": "containerInsights",
            "value": "disabled",
            "principalArn": "arn:aws:iam::123456789012:user/spinnaker-automation"
        },
        {
            "name": "containerInstanceLongArnFormat",
            "value": "disabled",
            "principalArn": "arn:aws:iam::123456789012:user/spinnaker-automation"
        },
        {
            "name": "serviceLongArnFormat",
            "value": "disabled",
            "principalArn": "arn:aws:iam::123456789012:user/spinnaker-automation"
        },
        {
            "name": "taskLongArnFormat",
            "value": "disabled",
            "principalArn": "arn:aws:iam::123456789012:user/spinnaker-automation"
        }
    ]
}
```



aws ecs list-attributes --target-type container-instance --region us-east-1 --attribute-name ecs.awsvpc-trunk-id --cluster compute-stage-ecs-cluster
```
{
    "attributes": [
        {
            "name": "ecs.awsvpc-trunk-id",
            "value": "24c650a0-9eb9-4ab7-b7d4-0f2068cf01c5",
            "targetId": "arn:aws:ecs:us-east-1:123456789012:container-instance/68813d26-52a3-472e-9b49-16f51f750f0b"
        }
    ]
}
```

**Comment by mssrivas** [comment]
Do we know how many tasks are running currently? Is this error while tryin to start a new task or starting any task? Reiterating could you please send us the agent logs and your task definition to ecs-agent-external@amazon.com? A C5 large instance can have 10 tasks per instance with ENI enabled. This also mentioned here - https://docs.aws.amazon.com/AmazonECS/latest/developerguide/container-instance-eni.html

**Comment by atyutyunnik** [comment]
> Do we know how many tasks are running currently? Is this error while tryin to start a new task or starting any task? Reiterating could you please send us the agent logs and your task definition to [ecs-agent-external@amazon.com](mailto:ecs-agent-external@amazon.com)? A C5 large instance can have 10 tasks per instance with ENI enabled. This also mentioned here - https://docs.aws.amazon.com/AmazonECS/latest/developerguide/container-instance-eni.html

Yes, I expected 10 tasks per instanced but that RESOURCE:ENI showed up when more than 3 tasks attempted to run. However, I verified deployment today and it works now. Have you fixed it already? Or how long does it take for awsvpcTrunking to get enabled? The settings command still show empty:
```
aws ecs list-account-settings
{
    "settings": []
}
```

**Comment by mssrivas** [comment]
the command seems incomplete. As mentioned here - https://awscli.amazonaws.com/v2/documentation/api/latest/reference/ecs/list-account-settings.html
about the  '--effective-settings | --no-effective-settings (boolean)'
Specifies whether to return the effective settings. If true , the account settings for the root user or the default setting for the principalArn are returned. If false , the account settings for the principalArn are returned if they are set. Otherwise, no account settings are returned.
