### ISSUE TITLE
Intermittent socket hang

### ISSUE THREAD

**Issue by jbergknoff** [aws/amazon-ecs-agent#268]
I suspect this is a bug in Docker, but since I have only reproduced it in ECS, I figured I would get feedback here first.

I have an intermittent issue where a socket with an established connection will stop functioning. Specifically, I have a long-running containerized process which communicates with a redis server. At some point, it will send a command to the redis server and not receive a response. After approximately 930 seconds (this seems to be consistent), the socket times out and closes. The way I've been able to reproduce this behavior is to have a bunch of tasks stopping and starting alongside that long-running container, though I don't know if that actually causes it or if it's just incidental.

Here is a minimal test case that reproduces the issue:

* a redis server accessible from ECS (though I don't think this is specific to redis; it's just an easy example)
* an ECS task definition `hello-world`, running the `hello-world` image, allocated 64 MB memory
* an ECS service running the `hello-world` task definition
* run my simple script which makes blocking calls to redis in an infinite loop (https://hub.docker.com/r/jbergknoff/ecs_socket_hang/ and https://github.com/jbergknoff/ecs_socket_hang). The easiest way to run it is to SSH to an ECS container host and execute:

    ```javascript
    $ docker run -it --rm jbergknoff/ecs_socket_hang <redis host>
    ```

    replacing `redis host` by the hostname where redis is accessible.

If you have the `hello-world` service turned off (desired count set to 0), `ecs_socket_hang` will run indefinitely, printing a line to stdout every time it talks to redis (every 100ms). If you scale up `hello-world` to a desired count of 20, you should see within a minute that the `ecs_socket_hang` output has stalled. Scaling back down does not resolve the issue.

Some additional notes:

* If you `docker exec` into the stalled container, the container is fine and even its networking is fine. You can, for instance, telnet to the redis server successfully. `netstat` shows some data stuck in the TCP send queue.
* If you run the `ecs_socket_hang` script with `--net=host` (instead of the default `--net=bridge`), the script does not stall.
* If you run the script outside of docker, the script does not stall.
* I manually upgraded an ECS container host to Docker 1.9.1 and the issue is still present there.
* I'm not clear on where the 930 second socket timeout comes from.

I would appreciate any thoughts, tips or suggestions on how to resolve this issue or debug it further.

**Comment by euank** [comment]
This sounds somewhat similar to a docker issue I ran into a while ago.

I observed that a `docker stop` sometimes caused a loss of networking across all containers on the host. I only saw this issue when using the 4.1 kernel; on the 3.14 kernel it didn't occur.

I tracked my issue down to https://github.com/docker/docker/issues/14908 / https://github.com/docker/docker/issues/14148. Applying the workaround referenced in https://github.com/docker/docker/issues/11407#issuecomment-120172459 did work, which made me fairly confident that was the issue I was seeing.

Want to check if that's the same issue you're seeing? If your network issues correlate closely with `docker stop`s and the workaround linked prevents it, then that's probably it.

Also, which AMI are you seeing this on and which kernel version?

Best,
Euan

**Comment by jbergknoff** [comment]
Thanks @euank for the comprehensive response. I will research those issues and try the workaround tomorrow, and then I'll report back.

AMI is `amzn-ami-2015.09.b-amazon-ecs-optimized` (`ami-ddc7b6b7`)

Kernel is
```bash
$ uname -r
4.1.10-17.31.amzn1.x86_64
```

**Comment by jbergknoff** [comment]
The workaround seems to have resolved the issue. Thanks!
