### ISSUE TITLE
ECS takes hours to synchronize with requested service update

### ISSUE THREAD

**Issue by djenriquez** [aws/amazon-ecs-agent#271]
Hello,

Is anyone aware of any issues with ECS not synchronizing with the service definition until hours later?

We had a service definition updated to use a new task def and desired count, but did not see those actual changes take affect until 2-3 hours later according to the event history in ECS console. 

I say 2-3 hours because we have the same service in us-west-2, us-east-1, and eu-west-1. In us-east-1, the change took affect about 2 hours later. Us-west-2 took 1 hour and 45 minutes, eu-west-1 took 1 hour 30 minutes. When the changes started, some took even more hours to finalize.

I was confident that re-updating the service definition would have "kicked" ecs to update, but instead I figured I'd wait and see how long it would take for it to do it itself. Surprisingly, it was hours later.

Service update was made at ~11:10PM.

US-West-2 (almost 5 hours until desired state was reached)
```
17239049-f7ce-425c-8ba2-8b53cf103550
2015-12-17 03:58:42 -0800
service zoo-quiz has reached a steady state.
04274f82-2f2e-47b2-9f59-1df2e90a9550
2015-12-17 03:58:30 -0800
service zoo-quiz has started 1 tasks: task 8af97763-f280-4633-8edd-abd3b363a4b8.
87b6f19f-7754-4905-8c5e-b1c52d94c979
2015-12-17 01:47:28 -0800
service zoo-quiz has reached a steady state.
bd3d3fc8-9e83-4722-803f-b64bd4bf5334
2015-12-17 01:46:45 -0800
service zoo-quiz stopped 1 running tasks.
c061bbe4-d738-4545-b5aa-1cb41b682b37
2015-12-17 01:46:04 -0800
service zoo-quiz has started 2 tasks: task 60128b18-caed-4595-9b90-291dcefb857b task 43a3e6e2-c468-4425-b746-581a63554444.
2695ce79-51d6-4c15-b438-bdc31bfbff93
2015-12-17 01:45:51 -0800
service zoo-quiz stopped 2 running tasks.
faa53a97-074f-421f-8c6b-fbb8e8cfc1bc
2015-12-17 01:45:10 -0800
service zoo-quiz has started 4 tasks: task 6ff11491-b285-4fb7-b6cb-a110ffb4fb3a task 74856b65-dfd5-41d4-ab08-4eb8feac3f18 task 501b8821-1e51-49b9-922f-825fe0ffd21b task 51bc08b3-63dd-475b-bbec-380d630bcb0b.
```

US-East-1 (2 hours)
```
768be04d-b4f0-4f31-b0be-7a2832f775ad
2015-12-17 01:02:40 -0800
service zoo-quiz has reached a steady state.
9b401534-2605-49fa-8ee3-4bbae4e50752
2015-12-17 01:01:56 -0800
service zoo-quiz stopped 1 running tasks.
16cb40aa-547d-407d-9c7b-103fe9c085bf
2015-12-17 01:01:14 -0800
service zoo-quiz has started 1 tasks: task 5b84474f-90f1-49cd-8947-db5e292df1ab.
b36032be-f072-464e-b17c-9355ade0acca
2015-12-17 01:01:04 -0800
service zoo-quiz stopped 3 running tasks.
7114d70d-3707-4be8-be89-c95b93bbd54d
2015-12-17 01:00:51 -0800
service zoo-quiz has started 3 tasks: task 78da88da-f6b3-4729-95a4-4cb2d510c57c task 480db5b5-99a7-4058-9334-8e5f51d22ba7 task 9892be4a-3dd3-4797-a140-1c631262c84b.
```

EU-West-1 (3 1/2 hours)
```
e3e43902-7c66-4d0d-b1c9-4050afcd76e0
2015-12-17 02:33:35 -0800
service zoo-quiz has reached a steady state.
9b8fd84a-2517-4f1e-b6ef-73dbbdd5d2ce
2015-12-17 02:33:24 -0800
service zoo-quiz stopped 1 running tasks.
b82e1a81-1cf8-4fae-89b7-77ac5688876c
2015-12-17 02:33:13 -0800
service zoo-quiz has started 1 tasks: task 485669b0-fbba-40b6-9c47-117740a6f731.
d1afc18e-7f07-48ec-b305-b797c2e8a424
2015-12-17 01:33:45 -0800
service zoo-quiz has started 1 tasks: task 6660fdbd-e070-4cbf-a57b-1c72b93608a4.
adb1844f-9d77-4fb4-8fe7-8520c0805d89
2015-12-17 01:33:02 -0800
service zoo-quiz has started 4 tasks: task 74aad805-2f15-4f28-a87d-21a75c06314d task 725e3dfc-2f38-41c2-9e3e-c2ce8986c0d2 task e98f00a0-04cf-4b37-87c0-1fe75d4c5985 task fa92251b-cacc-4309-8d24-db102807f6f9.
```

Any ideas?

Thanks.

**Comment by samuelkarp** [comment]
Hi djenriquez@,

We were able to trace one of the tasks you mentioned (8af97763-f280-4633-8edd-abd3b363a4b8) and correlate with request logs.  What it looks like to us is that you might be calling UpdateService for a service in one AWS account, but actually looking at the events for a similarly-named service in a different AWS account.  Specifically, we see a request to UpdateService for a service named zoo-quiz around the time you mention which completed within 3 minutes and a subsequent, later call to UpdateService for a service named zoo-quiz in a separate AWS account around the time that you're seeing in the event log.  Can you verify that you're using the same account to both update the service and look at the events?

Thanks,
Sam

**Comment by djenriquez** [comment]
Hi @samuelkarp,

We have zoo-quiz running in our dev, test and production environments, but this was definitely the correct account. Here is a screenshot from last night from having to explain to our CTO why the service wasnt auto-deploying :sweat_smile: 

Service is set to run zoo-quiz:29, but as you can see, zoo-quiz:28 was running until about 1:45 AM PST.

![screen shot 2015-12-16 at 10 52 21 pm](https://cloud.githubusercontent.com/assets/4636740/11889867/85d73a66-a502-11e5-89c0-c5727a966f16.jpg)

**Comment by djenriquez** [comment]
@samuelkarp I'm looking at the event history more and it looks like I may have prematurely stated hours.  The screenshot I took had a timestamp and that helped me track down the event history further:

The screenshot was taken at 10:52:21PM, which shows these logs.
```
84eecd3b-1906-472e-ab70-8bf1e4d62307
2015-12-16 22:54:19 -0800
service zoo-quiz has reached a steady state.
f8edfd64-e274-4be4-b1d5-431edfd0a9e7
2015-12-16 22:54:07 -0800
service zoo-quiz has started 1 tasks: task f8c8f323-b557-4a2b-9548-32c150cdf487.
6ec51633-9a94-4a65-8384-abec2690e613
2015-12-16 22:53:27 -0800
service zoo-quiz stopped 1 running tasks.
```
Looks like if I had been patient for another minute, it would have executed. That being said, this still took an unusually long time to kick in. Looking through history, the commit was made at 10:39PM. Looking at our CICD pipeline, it took 5 minutes and 29 seconds to build and make the call to ECS to update the service definition. So at 10:45PM, this service definition was already called to make a change, however that logs show that it didn't start until 10:54:07, almost 10 minutes later.

10 minutes still seems like a long time, no?

**Comment by samuelkarp** [comment]
@djenriquez Can you provide me with the ARN for the service?

**Comment by djenriquez** [comment]
@samuelkarp, could i send it to you in an email?

**Comment by samuelkarp** [comment]
@djenriquez Send it to skarp at amazon.com

I'm going to close this issue and we can continue by email since this is related specifically to your resources.

**Comment by rohit756** [comment]
Hi

I am facing similar issue
when i try to launch a task, status of task is in pending state from a while, and event log shows this messages

72cd49ee-4d88-4a52-a4c5-d3b2239e5ee9
2018-07-16 09:22:16 -0500
service carealign-admin is unable to consistently start tasks successfully. For more information, see the Troubleshooting section.
623f1fb0-ad3e-4a73-91cf-eb8052b7cc68
2018-07-16 09:09:45 -0500
service carealign-admin has started 1 tasks: task 1a4459fa-2bba-482b-a63e-1189b4363da7.
c16038f2-c8e0-49e1-9f7d-05e4128768cd
2018-07-16 08:59:24 -0500
service carealign-admin is unable to consistently start tasks successfully. For more information, see the Troubleshooting section.
a795ff7e-5174-4bcb-9eeb-7fe3976eaffe
2018-07-16 08:46:16 -0500
service carealign-admin has started 1 tasks: task a333ed7d-a2fb-4397-8c62-dd1c2be80153.
9ff516e5-bd4e-470c-a081-fdcc111497af
2018-07-16 08:35:53 -0500
service carealign-admin is unable to consistently start tasks successfully. For more information, see the Troubleshooting section.


any idea @djenriquez  

Thanks
