### ISSUE TITLE
Question: Is there any issue running 1.9 Docker host

### ISSUE THREAD

**Issue by tbenade** [aws/amazon-ecs-agent#272]
Hi,

Documentation says 1.7 preferred, wanted to know if there were any known issues running 1.9+

Thanks
Terry

**Comment by samuelkarp** [comment]
Hi @tbenade,

There's a known bug with Agent versions prior to 1.7.0 and Docker 1.9, see https://github.com/aws/amazon-ecs-agent/issues/261 for details.  Other than that, the concerns with Docker 1.9 are primarily around performance; https://github.com/docker/docker/issues/18314 is the upstream bug report and I just wrote https://github.com/aws/amazon-ecs-agent/issues/238#issuecomment-165593139 detailing some of the options to mitigate performance issues when using the Amazon Linux AMI or ECS-optimized AMI.

Sam

**Comment by tbenade** [comment]
thanks

**Comment by samuelkarp** [comment]
Docker 1.9.1 is now available in the latest [ECS-optimized AMI](http://docs.aws.amazon.com/AmazonECS/latest/developerguide/container_agent_versions.html).
