### ISSUE TITLE
Awsfirelens isn't a valid log_driver on ECS_AVAILABLE_LOGGING_DRIVERS variable?

### ISSUE THREAD

**Issue by LeonardoDG2084** [aws/amazon-ecs-agent#2736]
### Summary
Awsfirelens isn't a value valid on ECS_AVAILABLE_LOGGING_DRIVERS?

### Description
Recently we adding on some tasks the awsfirelens and we experienced a issue when add "awsfirelens" value on ECS_AVAILABLE_LOGGING_DRIVERS variable on user-data. When we add this value the ecs-agent crashes and the EC2 doesn't ingress on ECS cluster.

### Expected Behavior
I expect when adding "awsfirelens" value on  ECS_AVAILABLE_LOGGING_DRIVERS variable this log_driver is permited to tasks to use.

### Observed Behavior
When add "awsfirelens" value the ECS agent hangs and the new EC2 doesn't ingress on ECS cluster

### Environment Details
ECS-Agent 1.47.0 version
-->

**Comment by fenxiong** [comment]
Hi,
The awsfirelens log driver is something the agent supports internally by default, so there's no need to add it in the `ECS_AVAILABLE_LOGGING_DRIVERS ` config (and actually isn't a valid value for it), and you should be able to use the feature mentioned in https://docs.aws.amazon.com/AmazonECS/latest/developerguide/using_firelens.html without adding it . Let us know if that works. Thanks.

**Comment by LeonardoDG2084** [comment]
I'm using this functionality, but the main objective of  ECS_AVAILABLE_LOGGING_DRIVERS variable isn't whitelist of permited log_driver? So the awsfirelens should be included as value like, splunk, etc.. using the same criteria.  

Variable doc
https://docs.aws.amazon.com/AmazonECS/latest/developerguide/ecs-agent-config.html

**Comment by ubhattacharjya** [comment]
Hi,

https://github.com/aws/amazon-ecs-agent/pull/2766 is released with ECS agent version 1.50.0. Kindly update your container instances to this version to use this feature.

Closing this issue. Kindly reopen if you are still facing this issue.

Thanks,
Utsa
