### ISSUE TITLE
Delay in sns message

### ISSUE THREAD

**Issue by an-sush** [aws/amazon-ecs-agent#2744]
### Summary
There seems to be a delay between when new ECS agent is [published ](https://github.com/aws/amazon-ecs-agent/releases)vs when the ECS [sns notification](https://docs.aws.amazon.com/AmazonECS/latest/developerguide/ECS-AMI-SubscribeTopic.html) is sent and AWS [Documentation ](https://docs.aws.amazon.com/AmazonECS/latest/developerguide/ecs-ami-versions.html#ecs-ami-versions-linux)is updated

### Description
A more recent example is for the release [1.48.1](https://github.com/aws/amazon-ecs-agent/releases/tag/v1.48.1) went live but even after 17 hours, the [documentation ](https://docs.aws.amazon.com/AmazonECS/latest/developerguide/ecs-ami-versions.html#ecs-ami-versions-linux) is not updated and SNS [messages ](https://docs.aws.amazon.com/AmazonECS/latest/developerguide/ECS-AMI-SubscribeTopic.html)have not been sent.

This is also [highlighted ](https://github.com/aws/amazon-ecs-agent/issues/2738#issuecomment-734385511)in one of the previous issue 

### Expected Behavior
Github release, AWS Documentation and SNS message should be updated in near real time.

### Observed Behavior
There is a significant delay between GH release and AWS Documentation / SNS messages.
For teams which rely on this SNS to trigger custom AMI pipeline, this delay is a concern.

### Environment Details

N/A

### Supporting Log Snippets

N/A

**Comment by sharanyad** [comment]
SNS notifications should have been sent out for this. Closing this issue.
