### ISSUE TITLE
Environment variables added in process target

### ISSUE THREAD

**Issue by richardgavel** [aws/amazon-ecs-agent#2745]
I am running a Windows container running IIS, the ASP.NET code inside is unable to get AWS credentials and the exception suggests it's trying to get it from EC2 instance metadata.

I think this is because since the code is running inside IIS, it's running inside a different process space. Therefore, the codewill not see the AWS_CONTAINER_CREDENTIALS_RELATIVE_URI environment variable. It would be nice if the agent added the variable in machine AND process contexts so I don't have to promote it manually.

**Comment by vsiddharth** [comment]
ECS Windows has support for Task IAM Roles. Please refer https://docs.aws.amazon.com/AmazonECS/latest/developerguide/windows_task_IAM_roles.html for additional information.

**Comment by angelcar** [comment]
Closing since documentation has been referenced. Please feel free to re-open if needed.
