### ISSUE TITLE
Rolling restart of ECS service?

### ISSUE THREAD

**Issue by ejholmes** [aws/amazon-ecs-agent#275]
This is more of a feature request for ECS itself than for the agent. Sometimes it's desirable to perform a graceful rolling restart of all of the tasks running in a service. Right now, the only method to do that is to take the current task definition, duplicate it as a new version, then update the service with that. While this works ok, it would be nice if the ECS api provided an API for restarting a service.

**Comment by samuelkarp** [comment]
Thanks for the suggestion!  I've recorded a feature request for this that we can evaluate; please note that customer feedback definitely helps us understand what to prioritize.  Since this issue is not directly related to the Agent, I'll be closing it here.

**Comment by shinzui** [comment]
@samuelkarp where did you record it and is it publicly visible? I am trying to figure out the best way to do a rolling restart and the information will be useful.

**Comment by samuelkarp** [comment]
@shinzui I recorded this to our internal backlog, which is not publicly visible unfortunately.  What @ejholmes mentioned as the workaround is still what you can do today.

**Comment by shinzui** [comment]
@samuelkarp that would be very cumbersome to do because I am managing my infrastructure through terraform.

**Comment by ernestm** [comment]
+1 we need this too, I am even now logging into a crapload of ECS servers to manually roll our containers...

**Comment by anandlahoti** [comment]
**+1** currently we are also creating new version of task def with same task def just to restart the ECS service.

**Comment by danieldevere1** [comment]
This appears to be fixed with the "Force new deployment" checkbox in the Update service page of the AWS console.
