### ISSUE TITLE
Anonymous docker pulls decrement dockerhub rate limit

### ISSUE THREAD

**Issue by tthyer** [aws/amazon-ecs-agent#2769]
### Summary
It appears that the ECS agent pulls before every run, causing the dockerhub rate limit to decrement for anonymous users.

### Description
I am currently using [infrastructure](https://github.com/aws-samples/aws-genomics-workflows/) developed by AWS Genomics for running a bioinformatics workflow engine called Cromwell. This infrastructure leverages AWS Batch to run tasks in a workflow, which in turn uses ECS for compute. The current workflow we're developing began to fail recently when dockerhub turned on rate limiting. After doing some research and testing, I've discovered that the limit is decremented with every `docker pull`, regardless of whether the image is already in the local cache. However, `docker run` is safe to use with its default pull option, as that will only trigger a pull and decrement the rate if the image is not in the local cache.

In researching why our workflow was failing with ECS, starting at [this line](https://github.com/aws/amazon-ecs-agent/blob/6b10efac6ed5ab2af9254fc660e2131543b9c85e/agent/engine/docker_task_engine.go#L869) in your source code, it appears that the agent always pulls before a run. If I'm reading that correctly, please consider this a feature request: I would like the agent to check the local cache prior to attempting a pull (use equivalent of `docker run`).

**Comment by fenxiong** [comment]
Hi,
Regarding this feature request -
>  I would like the agent to check the local cache prior to attempting a pull

The agent does support this via an environment variable `ECS_IMAGE_PULL_BEHAVIOR` (documented in the README of this repo and also [here](https://docs.aws.amazon.com/AmazonECS/latest/developerguide/ecs-agent-config.html):
```
If prefer-cached is specified, the image is pulled remotely if there is no cached image. Otherwise, the cached image on the instance is used. Automated image cleanup is disabled for the container to ensure that the cached image is not removed.
```
So if you set ECS_IMAGE_PULL_BEHAVIOR to prefer-cached, the agent will inspect the image first, and will only try to pull when it can't find the image locally. This environment variable can be set in a similar manner as how ECS_CLUSTER is set (https://docs.aws.amazon.com/batch/latest/userguide/compute_environments.html). I'm wondering does that satisfy your need?

**Comment by tthyer** [comment]
Thank you @fenxiong for replying so promptly! I will give this a try.

**Comment by shubham2892** [comment]
Please reopen the issue if you need more help, closing it for now.

**Comment by tthyer** [comment]
To follow up, I did change the environment variable to `prefer-cached`, and have run a workflow to test that this is going to work for me. Thanks again for your help!
