### ISSUE TITLE
ECS Tasks fail to start even when Fluentd is running

### ISSUE THREAD

**Issue by maggiedeuitch** [aws/amazon-ecs-agent#2792]
### Summary
Tasks using fluentd logging driver fail to start even when Fluentd Aggregator task is running.
Receiving ```CannotStartContainerError: Error response from daemon: failed to initialize logging driver: dial unix /var/run/fluent.sock: connect: no such file or directory```

### Description
We are running ECS tasks with the following log configuration:
```
 "logConfiguration": {
        "logDriver": "fluentd",
        "options": {
          "fluentd-address": "unix:///var/run/fluent.sock"
        }
```
Fluentd Aggregator is already running as a Daemon service. When new tasks are started upon updating a service, the first few tasks fail to start with the following error, but eventually succeed:
```
CannotStartContainerError: Error response from daemon: failed to initialize logging driver: dial unix /var/run/fluent.sock: connect: no such file or directory
```
Why wouldn't a new task be able to connect to an existing Fluentd task? Does an existing task block a new one? We run multi-task on the same EC2 instance sometimes. Will that break?

### Expected Behavior
Tasks start up without error connecting to fluent socket when Fluentd is running

### Observed Behavior
Tasks fail with `CannotStartContainerError: Error response from daemon: failed to initialize logging driver: dial unix /var/run/fluent.sock: connect: no such file or directory` even when Fluentd is running.

### Environment Details
ECS Agent: 1.42.0
Docker: 19.03.6-ce
We are also using Shippable to deploy, but this happens when using the AWS console too.

**Comment by fierlion** [comment]
> When new tasks are started upon updating a service, the first few tasks fail to start with the following error, but eventually succeed

Just to clarify so I can better work to repro this issue, you're updating your service and new tasks launched are not immediately connecting to `/var/run/fluent.sock` but eventually the tasks do connect, is this correct?

> We run multi-task on the same EC2 instance sometimes.

By this, do you mean that you run multiple separate tasks on a single EC2 instance, with all of the tasks' fluentd output flowing to the single aggregator daemon on that same EC2 instance?

**Comment by shubham2892** [comment]
Closing this issue for now, please reopen with the info requested. Thank you.
