### ISSUE TITLE
how to add --shm-size option when using customize docker image for codebuild? 

### ISSUE THREAD

**Issue by talhajilal1** [aws/amazon-ecs-agent#2794]

**Comment by ubhattacharjya** [comment]
Hi @talhajilal1 ,

If you are using ECS, you can mention sharedMemorySize under linuxParameters in task definiton. (Ref: https://docs.aws.amazon.com/AmazonECS/latest/developerguide/task_definition_parameters.html#container_definition_linuxparameters)

Kindly let us know if you still face any issues.

Regards,
Utsa

**Comment by ubhattacharjya** [comment]
Hi @talhajilal1 ,

I am closing this issue. Kindly reopen if the above way does not work for you.

Thank you,
Utsa

**Comment by talhajilal1** [comment]
The information you have provided for ecs cluster not for codebuild
