### ISSUE TITLE
cgroups.ErrCgroupDeleted warning message might not be logged as expected

### ISSUE THREAD

**Issue by choyky** [aws/amazon-ecs-agent#2796]
### Summary
The warning message "Cgroup at %s has already been removed: %v" might not be logged as expected
[1] https://github.com/aws/amazon-ecs-agent/blob/master/agent/taskresource/cgroup/cgroup.go#L298

### Description
From above [1], warning message "Cgroup at %s has already been removed: %v" should be logged when cgroups.ErrCgroupDeleted occurs.

However, when error is returned from ```cgroup.control.Remove(cgroup.cgroupRoot)```[2], err would probably contain other messages, which causes the if statement in [1], i.e. ```if err == cgroups.ErrCgroupDeleted``` to fail matching the error.

[2] https://github.com/aws/amazon-ecs-agent/blob/v1.37.0/agent/taskresource/cgroup/control/cgroup_controller_linux.go#L68

### Expected Behavior
The warning message "Cgroup at %s has already been removed: %v" is logged when cgroups.ErrCgroupDeleted occurs.

### Observed Behavior
The warning message "Cgroup at %s has already been removed: %v" was not logged when cgroups.ErrCgroupDeleted occurs.

### Environment Details
Only relevant to the ecs-agent implementation.

### Supporting Log Snippets
Please let me know if log is necessary for investigation.

**Comment by fierlion** [comment]
I'm looking into this now.  

If you have steps to repro, it would be helpful.
When you say "might not be logged as expected", does that imply that the issue was intermittent in your testing?

**Comment by choyky** [comment]
Thanks!
Unfortunately I do not have the exact steps to reproduce, but it happened during reboots, perhaps because ecs-agent tried to clean up resources when they were deleted during reboot.
In my case, I never see the warning message "Cgroup at %s has already been removed: %v" in my logs.
I said "might not be logged as expected" because I am not sure whether there are cases when it actually works.

**Comment by fierlion** [comment]
I'm particularly interested to know if you see any of the other cgroups error messages in your logs https://github.com/containerd/cgroups/blob/0b889c03f102012f1d93a97ddd3ef71cd6f4f510/errors.go#L25-L31.
> was not logged when cgroups.ErrCgroupDeleted occurs

to confirm, you _do_ see the message "cgroups: cgroup deleted" in your logs?  Is this how you know cgroups.ErrCgroupDeleted has occurred? https://github.com/containerd/cgroups/blob/0b889c03f102012f1d93a97ddd3ef71cd6f4f510/errors.go#L30

I'm looking now to determine what the full set of possible errors is for `err := cgroup.control.Remove(cgroup.cgroupRoot)`

**Comment by choyky** [comment]
> to confirm, you _do_ see the message "cgroups: cgroup deleted" in your logs? Is this how you know cgroups.ErrCgroupDeleted has occurred? https://github.com/containerd/cgroups/blob/0b889c03f102012f1d93a97ddd3ef71cd6f4f510/errors.go#L30

Yes, I see "cgroups: cgroup deleted" in part of the log.

**Comment by fierlion** [comment]
I merged the fix into our dev branch.  This should go out with the next major Agent release.
Thank you for bringing this up!
