### ISSUE TITLE
Respect container/task health status when scaling the service on fargate

### ISSUE THREAD

**Issue by shashanktomar** [aws/amazon-ecs-agent#2804]
### Summary
This is to reopen issue https://github.com/aws/amazon-ecs-agent/issues/1298. If after a deployment, the new container is unhealthy, fargate still stops the old healthy container and starts routing traffic to the new one. 

### Description
As fargate do not respect container health checks before routing the traffic to new containers, the downtime happens during deployments if new containers are unhealthy. This is discussed in detail [here](https://github.com/aws/amazon-ecs-agent/issues/1298#issuecomment-639007866). This is a broken service discovery implementation.

**Comment by fierlion** [comment]
@shashanktomar thanks for bringing this to our attention.  
I'm looking into the latest comments on the related issue https://github.com/aws/amazon-ecs-agent/issues/1298
If you have more specific details to add to that issue as it relates to your use case, please comment there so we can keep continuity.

**Comment by fierlion** [comment]
@shashanktomar I'm closing this in favor of https://github.com/aws/amazon-ecs-agent/issues/1298
Please review latest comments there.  Once we are able to repro, we can re-open that issue.

**Comment by shashanktomar** [comment]
@fierlion I opened this because #1298 is closed.
