### ISSUE TITLE
[Feature request]: Proxy Settings to container automatically

### ISSUE THREAD

**Issue by nataizya** [aws/amazon-ecs-agent#2809]
### Summary

It is currently not possible to automatically pass proxy settings to containers as described in docker documentation (using docker 19.03.1) [here](https://docs.docker.com/network/proxy/#configure-the-docker-client):

`In Docker 17.07 and higher, you can configure the Docker client to pass proxy information to containers automatically.`

### Description

Currently have to pass proxy environment variables to the container through the task definition.

If the container is started manually (after setting proxy settings in ~/.docker/config.json), the proxy environment variables are set in the container as expected. However, tasks started via ECS, don't get these proxy environment variables populated automatically without passing them through the task definition.

### Environment Details

Docekr 19.03.1
ECS Agent 1.50

**Comment by shubham2892** [comment]
Hi @nataizya, I see you have already opened a request here -- [https://github.com/aws/containers-roadmap/issues/1266](https://github.com/aws/containers-roadmap/issues/1266). Please track the issue there.
