### ISSUE TITLE
ECS task instance in sa-east-1 is not receiving an internal DNS address

### ISSUE THREAD

**Issue by jfbueno** [aws/amazon-ecs-agent#2839]
### Summary

It looks like that ECS tasks launched in sa-east-1 doesn't receive an internal DNS address.

### Description

I'm trying to get the container's private IP address using this .NET code 

```csharp
Dns.GetHostEntry(Dns.GetHostName()).AddressList;
```
and it works well if my task is running in **us-east-1**, but when I deploy the same container into a task in **sa-east-1** it ends up throwing this exception

> System.Net.Internals.SocketExceptionFactory+ExtendedSocketException (00000005, 0xFFFDFFFF): Name or service not known

I did a little digging and printed the environment variables for each task instance and noted that in the us-east-1 task the hostname is something like `ip-10-0-4-168.ec2.internal`, but in the sa-east-1 its more like a UUID (ie. `a8378554feab4fd7b82e5530dddd6bf1-2515387555`).

I think that this can be the real problem, but I couldn't find out what's causing this.

The two VPC's looks to have the same DHCP options.

### Expected Behavior
[According to this documentation](https://docs.aws.amazon.com/vpc/latest/userguide/vpc-dns.html), the task should have an internal DNS address in the form "ip-private-ipv4-address.region.compute.internal".

### Observed Behavior

The task doesn't have an internal DNS address.

**Comment by shubham2892** [comment]
Hi @jfbueno , thank you for reporting this, I will try to repro this on my end in sa-east-1 region. Can you tell me which Agent version and which AMI you are using for running these tasks?

**Comment by shubham2892** [comment]
@jfbueno I tried running an awsvpc task in us-east-1 and sa-east-1. Hostname for task in us-east-1 was `ip-10-0-0-240.ec2.internal` and hostname for task in sa-east-1 was `ip-10-0-0-173.sa-east-1.compute.internal`. I am using `amzn2-ami-ecs-hvm-2.0.20210331-x86_64-ebs` AMI in both the regions. Can you help us with the repro steps for the issue?

**Comment by jfbueno** [comment]
@shubham2892 Sorry about the delayed response. I'll try to create a new repro environment this weekend and send you this info. 

I'm just not sure if I know where to find the AMI version, can you help me with that?

**Comment by chienhanlin** [comment]
Hello @jfbueno Please run `curl http://169.254.169.254/latest/meta-data/ami-id`  to get the `{ami-id}` from the running instance metadata, and use `aws ec2 describe-images --region {region} --image-ids {ami-id} `to get the image name. 

Example:
```
[user@ip]$ curl http://169.254.169.254/latest/meta-data/ami-id
ami-00780848600d687b6

[user@ip]$ aws ec2 describe-images --region us-west-2 --image-ids ami-00780848600d687b6
{
    "Images": [
        {
            "VirtualizationType": "hvm", 
            "Description": "Amazon Linux AMI 2.0.20210413 x86_64 ECS HVM GP2", 
            "PlatformDetails": "Linux/UNIX", 
            ...
           "Name": "amzn2-ami-ecs-hvm-2.0.20210413-x86_64-ebs"
    ]
}
```
* More info and Instance metadata categories can be found in AWS Documentation [Retrieve instance metadata](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/instancedata-data-retrieval.html). 
* AWS CLI Command Reference for [ec2 describe-images](https://docs.aws.amazon.com/cli/latest/reference/ec2/describe-images.html).
  
It would be very helpful if you could send us steps to repro this issue. The email list is ecs-agent-external@amazon.com. Thanks.

**Comment by ubhattacharjya** [comment]
Hi @jfbueno ,

Since you are using Fargate with platform version 1.4.0, kindly create a support ticket with AWS Fargate.

Ref: https://docs.aws.amazon.com/awssupport/latest/user/case-management.html#creating-a-support-case

**Comment by ubhattacharjya** [comment]
I will close this issue. Kindly reopen if you have any further questions
