### ISSUE TITLE
[BUG] Networking stack prematurely dies for awsvpc tasks on 1.50.3

### ISSUE THREAD

**Issue by joshuabaird** [aws/amazon-ecs-agent#2841]
### Summary
See AWS Case #8162212971 for more information and logs.  Posting here for posterity.

In v1.50.3 of the ECS agent, we began to see a large number of network/DNS related errors when containers were being shut down (as a result of autoscaling or when an ECS container instance was put into draining).  This resulted in various issues across our applications.

### Description
It looks like the "pause" container behavior was recently changed here:  https://github.com/aws/amazon-ecs-agent/compare/v1.50.2...v1.50.3

I'm not exactly sure what is happening, but it seems like the "pause" container may be getting killed (or affecting network connectivity for the actual application container) before the application container.

Rolling back to 1.50.0 made all errors stop in our environment.  

### Expected Behavior
Containers shut down gracefully without their network stack dying prematurely.

### Observed Behavior
As the container shuts down, it loses network connectivity before it dies (either via SIGTERM or SIGKILL) resulting in connectivity/DNS related errors and other errors across our stack as a result of unclean disconnections.

### Environment Details
v1.50.3 of the ECS agent on Amazon Linux 2 (ECS Optimized AMI) using awsvpc tasks.

### Supporting Log Snippets
See AWS #8162212971 for logs and more info.

**Comment by shubham2892** [comment]
Hi @joshuabaird, this has been fixed in Agent version 1.51.0 released today. Please reopen if you see the issue still happening.
