### ISSUE TITLE
Too Many FD Error

### ISSUE THREAD

**Issue by zbintliff** [aws/amazon-ecs-agent#2845]
### Summary
We recently upgraded our ECS Agents to v1.50.0 and noticed ecs agents becoming unhealthy. I think it may be an IPv6 issue (we don't have it enabled). But basically once it goes unhealthy it gets the following error (for both IPv6 and IPv4
```
2021/03/15 06:16:36 http: Accept error: accept tcp 127.0.0.1:51679: accept4: too many open files; retrying in 1s
2021/03/15 06:16:37 http: Accept error: accept tcp [::]:51678: accept4: too many open files; retrying in 1s
2021/03/15 06:16:37 http: Accept error: accept tcp 127.0.0.1:51679: accept4: too many open files; retrying in 1s
2021/03/15 06:16:38 http: Accept error: accept tcp 127.0.0.1:51679: accept4: too many open files; retrying in 1s
```

When doing inspection it does appear that the ecs agent is truly taking all 65k fds in the container.

Here is docker health chck:
```
"Health": {
                "Status": "unhealthy",
                "FailingStreak": 26908,
                "Log": [
                    {
                        "Start": "2021-03-23T16:53:56.700508894Z",
                        "End": "2021-03-23T16:54:21.959958268Z",
                        "ExitCode": 1,
                        "Output": "{\"level\": \"error\", \"time\": \"2021-03-23T16:54:21Z\", \"msg\": \"health check [HEAD http://localhost:51678/v1/metadata] failed with error: Head \\\"http://localhost:51678/v1/metadata\\\": context deadline exceeded (Client.Timeout
exceeded while awaiting headers)\", \"module\": \"healthcheck.go\"}\n"
```

On the host we run this command :
```
ps -opid= -ax | xargs -L 1 -I{} -- bash -c 'echo -n "{} ";lsof -p {} 2>/dev/null | wc -l' | sort -n -k2
```
And we see that the `ecs-agent` container has exactly 65k open files.

Restarting the ecs agent resolves the issue.

### Observed Behavior
This is leaving the ECS agent running but unhealthy. Old deployments are not being cleaned up and the older versions of containers are causing issues.

### Environment Details

```
"Version": "Amazon ECS Agent - v1.50.0 (90ccb1d4)"
```

**Comment by fenxiong** [comment]
Hi @zbintliff,
Could you run the [ecs log collector](https://docs.aws.amazon.com/AmazonECS/latest/developerguide/ecs-logs-collector.html) on the instance when the issue happens, and send the collected logs to ecs-agent-external@amazon.com? that could help us look into the issue. Thanks!

**Comment by zbintliff** [comment]
We usually kill the nodes. Will run it next time we run into it ( like I said usually 1 or two a week ). We only pass error logs to our downstream log provider so its silent then spam the fd alert.

**Comment by shubham2892** [comment]
Closing the issue for now, @zbintliff feel free to reopen when you get a chance to collect the logs. Thank you.
