### ISSUE TITLE
how to set node system-reserved=memory

### ISSUE THREAD

**Issue by LuLiMingAmos** [aws/amazon-ecs-agent#2853]

**Comment by LuLiMingAmos** [comment]
how to set node system-reserved=memory

**Comment by fierlion** [comment]
I would like to help, but we'll need more detail.

Can you clarify what you mean by "node" -- do you mean Container Instance (the underlying host)?  

ECS is different from EKS (Elastic Kubernetes Service) which has the concept of nodes
also available in kubernetes: 
`Kubelet Flag: --kube-reserved=[memory=100Mi]`
https://kubernetes.io/docs/tasks/administer-cluster/reserve-compute-resources/
Is this what you're asking about?  

Are you using EKS or ECS?

**Comment by LuLiMingAmos** [comment]
> `Kubelet Flag: --kube-reserved=[memory=100Mi]`

thank you very much ,it is just which I am finding.Even though I have found it myselft,thank you all the same.

**Comment by fierlion** [comment]
This flag is Kubernetes-specific.

This is the ECS Agent repo (ECS is not Kubernetes).  
I'll close this issue.  Please re-open if there's more required input available:
```
Summary
Description
Expected Behavior
Observed Behavior
Environment Details
Supporting Log Snippets
```
