### ISSUE TITLE
ECS Agent log files are not consumable by syslog

### ISSUE THREAD

**Issue by aaithal** [aws/amazon-ecs-agent#287]
As per comments in #116, syslog cannot be used to capture log output and neither can it be used to  process the agent log files.

**Comment by jhovell** [comment]
+1

**Comment by anryko** [comment]
why reinvent logrotate...

**Comment by pulkkla-nc** [comment]
Is there any recent activity around this issue or has it been put on the roadmap for fixing?

**Comment by sparrc** [comment]
closing, tracking in #2284
