### ISSUE TITLE
iptables configuration should explicitly permit access to agent task metadata port

### ISSUE THREAD

**Issue by otterley** [aws/amazon-ecs-agent#2877]
### Summary

If the instance on which the ECS Agent is installed has an iptables configuration such that the default `INPUT` chain rule is `DROP` instead of `ACCEPT`, containers will be unable to access the ECS task metadata endpoint.

### Description

Customized AMIs such as the CSI Hardened Amazon Linux 2 image are often chosen by customers to meet enhanced security and compliance requirements. This image has a slightly different out-of-the-box iptables configuration than our standard AL2 image. In particular, the default `INPUT` iptables chain rule is to `DROP` packets instead of `ACCEPT` them. 

Here is the default `INPUT` chain configuration on a stock AL2 AMI, after the ECS agent has been installed:

```
Chain INPUT (policy ACCEPT 4664 packets, 1084K bytes)
 pkts bytes target     prot opt in     out     source               destination         
    0     0 DROP       tcp  --  eth0   *       0.0.0.0/0            0.0.0.0/0            tcp dpt:51678
    0     0 DROP       all  --  *      *      !127.0.0.0/8          127.0.0.0/8          ! ctstate RELATED,ESTABLISHED,DNAT
```

And here is the default `INPUT` chain configuration on a CIS-hardened AL2 AMI, also after the ECS agent has been installed:

```
Chain INPUT (policy DROP 0 packets, 0 bytes)
 pkts bytes target     prot opt in     out     source               destination         
    0     0 DROP       tcp  --  eth0   *       0.0.0.0/0            0.0.0.0/0            tcp dpt:51678
    0     0 DROP       all  --  *      *      !127.0.0.0/8          127.0.0.0/8          ! ctstate RELATED,ESTABLISHED,DNAT
   10  2410 ACCEPT     all  --  lo     *       0.0.0.0/0            0.0.0.0/0           
    0     0 DROP       all  --  *      *       127.0.0.0/8          0.0.0.0/0           
 3578  771K ACCEPT     tcp  --  *      *       0.0.0.0/0            0.0.0.0/0            state ESTABLISHED
  587 58179 ACCEPT     udp  --  *      *       0.0.0.0/0            0.0.0.0/0            state ESTABLISHED
    0     0 ACCEPT     icmp --  *      *       0.0.0.0/0            0.0.0.0/0            state ESTABLISHED
  111  5780 ACCEPT     tcp  --  *      *       0.0.0.0/0            0.0.0.0/0            tcp dpt:22 state NEW
    0     0 ACCEPT     udp  --  *      *       0.0.0.0/0            0.0.0.0/0            udp dpt:68 state NEW
    0     0 ACCEPT     udp  --  *      *       0.0.0.0/0            0.0.0.0/0            udp dpt:123 state NEW
    0     0 ACCEPT     udp  --  *      *       0.0.0.0/0            0.0.0.0/0            udp dpt:323 state NEW
```

You'll notice more rules configured for the CIS-hardened AMI, along with a default policy of `DROP`.

Containers scheduled by ECS onto the CIS-hardened instance are unable to access their task metadata service:

```
root@5a3f826ef907:/build# curl $ECS_CONTAINER_METADATA_URI_V4/task
curl: (7) Failed to connect to 169.254.170.2 port 80: Connection timed out
```

### Suggested fix

Fixing this issue looks to be relatively straightforward. If the ECS agent (or ecs-init) explicitly adds an `-j ACCEPT` rule to the `INPUT` iptables chain that permits access to the ECS Agent port, it works fine. Here is an example rule:

```
iptables -A INPUT -i docker0 -d 127.0.0.0/8 -p tcp -m tcp --dport 51679 -j ACCEPT
```

**Note**: the above fix was tested to make bridge mode networking work. Further investigation is needed for awsvpc mode.

**Comment by shubham2892** [comment]
@otterley Thank for reporting this. Looking into this.

**Comment by otterley** [comment]
To enable task metadata service access for tasks using awsvpc network mode, the following iptables rule is also required:

```
-A INPUT -i ecs-bridge -d 127.0.0.0/8 -p tcp -m tcp --dport 51679 -j ACCEPT
```

**Comment by shubham2892** [comment]
Hello @otterley, We will be updating our documentation to update that CIS-hardened AL2 AMI will require these additional iptables rules.

**Comment by yehudacohen** [comment]
Wanted to verify that this worked for us. Thanks for the fix!

**Comment by ellenthsu** [comment]
please reopen if you encounter any other issues.

**Comment by AlonAvrahami** [comment]
Hi @ellenthsu Thanks a lot for your help!
Is it possible to add this to the ECS agent documentation? (https://docs.aws.amazon.com/AmazonECS/latest/developerguide/ecs-agent-install.html#ecs-agent-install-nonamazonlinux)

It's unclear why the metadata url is not accessible from the containers (after setting up the ecs-agent according to the documentation) , and it took me some time to identify the root cause.
i think it's a common problem, and if it's possible to add it the documentation it will be very helpful!
