### ISSUE TITLE
Make dynamic port assignment information visible to running containers

### ISSUE THREAD

**Issue by sfussenegger** [aws/amazon-ecs-agent#288]
I think it would be useful to expose some `docker inspect` information through the [introspection API](http://docs.aws.amazon.com/AmazonECS/latest/developerguide/ecs-agent-introspection.html), most notably the port mappings (`Ports`).

Additionally, local an public IPs and hostnames would be nice to have too, but they are available through [EC2 instance metadata](http://docs.aws.amazon.com/AWSEC2/latest/UserGuide/ec2-instance-metadata.html) anyway.

My current use case is a service that registers itself at a service registry. Currently, there is no easy way to know the public port unless it is static.

**Comment by joepjoosten** [comment]
+1

**Comment by thanandorn** [comment]
:+1:

**Comment by hwatts** [comment]
+1

**Comment by AjitDas** [comment]
Much needed one and critical for many docker application which wants to register as part of docker container ( application ) start up. For example hazelcast docker applications need to register publicAddress with HOST:PORT so that it can allow other members in hazelcast cluster to be able to connect to each other.

**Comment by mhurne** [comment]
This would be convenient to be sure; in the meantime, we are using the combination of what's available in the agent introspection API currently and the ECS and EC2 APIs to "connect the dots" to get the container instance IP and the host port that ECS dynamically mapped to the container port we're interested in. Our use-case is Hazelcast (like @AjitDas from the sounds of it).

**Comment by samuelkarp** [comment]
Accessing metadata (including port information) from within the container is going to be supported through https://github.com/aws/amazon-ecs-agent/issues/710, which will go out with our next release.

**Comment by samuelkarp** [comment]
We have released [ECS agent v1.15.0](https://github.com/aws/amazon-ecs-agent/releases/tag/v1.15.0), which adds this feature.  Please see [the documentation](http://docs.aws.amazon.com/AmazonECS/latest/developerguide/container-metadata.html) for information on how to use it.
