### ISSUE TITLE
Filter introspection API tasks by client IP

### ISSUE THREAD

**Issue by sfussenegger** [aws/amazon-ecs-agent#289]
This would be a nice feature that would allow introspection of a container from within the container itself without having to know any details. This would be much like the [EC2 instance metadata](http://docs.aws.amazon.com/AWSEC2/latest/UserGuide/ec2-instance-metadata.html) service.

This call could look like this to match the current call:

```
curl http://ecs-agent:51678/v1/tasks?dockerid=this
```

This would be especially valuable combined with #288 so a container could easily find it's public ports

There would be the need for a link to the `ecs-agent` container to enable this

**Comment by joepjoosten** [comment]
+1

**Comment by mrwilby** [comment]
+1

**Comment by AjitDas** [comment]
introspection APIs works only after docker container status is running i.e. by that time docker container expected to have already started, it would be better if we can get hostPort mapping inside the container during start up so that application can use it as part of start up.

**Comment by mhurne** [comment]
FWIW, you can access the introspection API from within a container at http://172.17.0.1:51678/. I'm honestly not sure whether that IP is subject to variation or change, but it seems to be what works out-of-the-box. You can get the short ID of the container you're in via the HOSTNAME environment variable (or in Java, via a call to `InetAddress.getLocalHost().getHostName()`, and you can use that to identify the container you're in when reading the output of http://172.17.0.1:51678/v1/tasks...

**Comment by adnxn** [comment]
closing this issue since this functionality is captured by the [container metadata file](https://docs.aws.amazon.com/AmazonECS/latest/developerguide/container-metadata.html) feature. feel free to reopen and update issue if you need.
