### ISSUE TITLE
pin the ecs-agent version rather then use amazon/amazon-ecs-agent:latest in the Amazon ECS-optimized Amazon Linux's

### ISSUE THREAD

**Issue by danbf** [aws/amazon-ecs-agent#2896]
### Summary
Currently the ecs-agent that is loaded in the Amazon ECS-optimized Amazon Linux 2 AMI that we run load `amazon/amazon-ecs-agent:latest` rather then a pinned version of the ecs-agent as implied by https://docs.aws.amazon.com/AmazonECS/latest/developerguide/ecs-agent-versions.html .  

### Description
Currently the ecs-agent that is loaded in the Amazon ECS-optimized Amazon Linux 2 AMI that we run load `amazon/amazon-ecs-agent:latest` rather then a pinned version of the ecs-agent as implied by https://docs.aws.amazon.com/AmazonECS/latest/developerguide/ecs-agent-versions.html .  

For example we have an ecs node built off `ami-09edd32d9b0990d49`/`amzn2-ami-ecs-hvm-2.0.20200402-x86_64-ebs`. the chart on https://docs.aws.amazon.com/AmazonECS/latest/developerguide/ecs-agent-versions.html says it should have ecs-agent version `1.39.0`.  Looking at the AWS console, it shows the instance running `1.44.3` which was `latest` when this the AMI we are running was customized by packer and stored. https://hub.docker.com/layers/amazon/amazon-ecs-agent/v1.44.3/images/sha256-07a4494fb67b8dbc95e80859d4d0230ea90a30d92c148dd5d0b232d20f0024e0?context=explore .  

```
docker ps | grep [a]gent
21cac436573b        amazon/amazon-ecs-agent:latest   "/agent"            4 minutes ago       Up 4 minutes (healthy)                       ecs-agent
```

This is somewhat of a repeat of https://github.com/aws/containers-roadmap/issues/1401 but I can't log it to the Amazon ECS-optimized Amazon Linux since it's not public

### Expected Behavior
`ecs-agent` versions should track the chart provided in https://docs.aws.amazon.com/AmazonECS/latest/developerguide/ecs-agent-versions.html

### Observed Behavior
`ecs-agent` versions that actually run are based on the latest at node deploy time or the time a derivative AMI was created with a tool like packer.

### Environment Details
```
docker ps | grep [a]gent
21cac436573b        amazon/amazon-ecs-agent:latest   "/agent"            4 minutes ago       Up 4 minutes (healthy)                       ecs-agent
```

**Comment by danbf** [comment]
i suspect the issue is that https://github.com/aws/amazon-ecs-init/blob/master/ecs-init/config/common.go#L32-L33 `AgentImageName` is not specified in when the AMI installs the `amazon-ecs-init` rpm.

**Comment by angelcar** [comment]
Hi, thanks for reaching out. 
Are you by any chance pulling `amazon/amazon-ecs-agent:latest` from Docker hub during your AMI customization process? If so, that could explain what you are observing. 

ECS init itself does not pull `amazon/amazon-ecs-agent:latest` from a repository, rather, it downloads the official tar file published as part of ECS release process. The version pulled should be pinned, as you can see in the [download process](https://github.com/aws/amazon-ecs-init/blob/5f7f9336bc3c5314206aefd212e9ebbfc3bdab60/ecs-init/cache/cache.go#L220), which uses the baked-in version defined [here](https://github.com/aws/amazon-ecs-init/blob/master/ecs-init/config/common.go#L49). When the agent is first downloaded, the tar is cached in `/var/cache/ecs`, which should contain the file: `ecs-agent-v1.39.0.tar` (could you verify this?).

So, as long as the newer image is not pulled from Docker hub, or the agent is not explicitly updated (e.g. by clicking the console's Update agent button), the version should remain pinned.

**Comment by danbf** [comment]
we are not pulling down the ecs-agent but relying on the one in the `Amazon ECS-optimized Amazon Linux 2 AMI` like `ami-07fde2ae86109a2af`

**Comment by angelcar** [comment]
I see. Another question, are you executing `yum update` as part of your Packer AMI customization? This command also updates the agent to the latest version. If you could share more details about your customization process it would help.

**Comment by danbf** [comment]
don't run a `yum update`  just these, and we don't packer up new AMI's.  just use the `Amazon ECS-optimized Amazon Linux 2 AMI`, tweak it a bit via the user-data script and the register it with the ECS cluster.

```
# install packages needed for npre and awsamazon-linux-extras install -y epelyum install -y unzip-6.0-21.amzn2.x86_64 ntpdate-4.2.6p5-29.amzn2.0.2.x86_64 ntp-4.2.6p5-29.amzn2.0.2.x86_64 \  awscli-1.18.147-1.amzn2.0.1.noarch jq-1.5-1.amzn2.0.2.x86_64 bc-1.06.95-13.amzn2.0.2.x86_64 \  xinetd-2.3.15-13.amzn2.0.2.x86_64 nagios-4.4.5-7.el7.x86_64 nrpe-4.0.3-6.el7.x86_64 \  nagios-plugins-all-2.3.3-2.el7.x86_64 nagios-plugins-nrpe-4.0.3-2.el7.x86_64 \  aws-cfn-bootstrap-2.0-6.amzn2.noarch words-3.0-22.amzn2.noarch
```

**Comment by danbf** [comment]
net result is this is running:

```
docker ps | grep [a]mazon-ecs-agent
b9c320c84607        amazon/amazon-ecs-agent:latest                                                                                                                "/agent"                 3 days ago          Up 3 days (healthy)                                                                     ecs-agent
```

**Comment by angelcar** [comment]
One clarification: `amazon/amazon-ecs-agent:latest` is always going to show up in `docker ps` regardless of the agent version.

By default, `amazon/amazon-ecs-agent:latest` image should be loaded from the tar file referenced above, to get more insight, can you do `ls -l /var/cache/ecs/`, what version do you see there?

**Comment by danbf** [comment]
this is the majority of the user-data script:

```
#!/bin/bash

set -e
set -o pipefail

until [ -n "$${NAME_FULL}" ]; do
  INSTANCE_ID=$(curl --silent http://169.254.169.254/latest/meta-data/instance-id)
  AVAILABILITY_ZONE=$(curl --silent http://169.254.169.254/latest/meta-data/placement/availability-zone)
  REGION=$(echo $${AVAILABILITY_ZONE} | grep -Eo '[a-z]{2}-[a-z]+-[0-9]{1}')
  ZONE_LETTER=$(echo $${AVAILABILITY_ZONE} | sed 's/\(^.*\)\(.$\)/\2/g')
  NAME_FULL="${base_host_name}-$(random_word $${ZONE_LETTER})-$(random_word)"
done

aws ec2 create-tags --region $${REGION} --resources $${INSTANCE_ID} --tags "Key=Name,Value=$${NAME_FULL}"
classes=$(echo ${classes} | tr "," "\n")

...

hostname "$${NAME_FULL}"
echo "$${NAME_FULL}" >/etc/hostname
echo "127.0.0.1 $${NAME_FULL}" >>/etc/hosts

# sanity check
if [ "$(hostname)" != "$${NAME_FULL}" ]; then
  echo "fatal: '$(hostname)' != '$${NAME_FULL}'"
  exit 1
fi

ntpdate -u pool.ntp.org
service ntpd restart
service rsyslog restart
service datadog-agent restart
/ecs_bootstrap.sh "${cluster}"

cfn-signal --exit-code 0 --stack "${stackname}" --resource "RigClusterAsg" --region "$${REGION}"
```

**Comment by danbf** [comment]
i'm seeing this:

```
[root@rig-prod-ecs-felt-cares ~]# ls -l /var/cache/ecs/
total 65440
lrwxrwxrwx 1 root root       21 Oct  6  2020 ecs-agent.tar -> ecs-agent-v1.44.3.tar
-rw-r--r-- 1 root root 67003392 Sep  2  2020 ecs-agent-v1.44.3.tar
-rw-r--r-- 1 root root        1 Oct  6  2020 state
```
the aws console shows: 

<img width="1274" alt="Screen Shot 2021-06-14 at 3 40 58 PM" src="https://user-images.githubusercontent.com/5041307/121949879-ff438b00-cd26-11eb-8e1c-f19d3f2a6918.png">

but i built this from `source_ami=ami-09edd32d9b0990d49` which is amzn2-ami-ecs-hvm-2.0.20200402-x86_64-ebs but https://docs.aws.amazon.com/AmazonECS/latest/developerguide/ecs-agent-versions.html says it should be version `1.39.0`

**Comment by danbf** [comment]
here it is from our current ecs nodes that just uses the AMI directly with no packing involved:

```
#!/bin/bash -xe

# load breakglass keys
echo "${breakglass_ssh_keys}" >> /home/ec2-user/.ssh/authorized_keys

# install packages needed for npre and aws
amazon-linux-extras install -y epel
yum install -y unzip-6.0-21.amzn2.x86_64 ntpdate-4.2.6p5-29.amzn2.0.2.x86_64 ntp-4.2.6p5-29.amzn2.0.2.x86_64 \
  awscli-1.18.147-1.amzn2.0.1.noarch jq-1.5-1.amzn2.0.2.x86_64 bc-1.06.95-13.amzn2.0.2.x86_64 \
  xinetd-2.3.15-13.amzn2.0.2.x86_64 nagios-4.4.5-7.el7.x86_64 nrpe-4.0.3-6.el7.x86_64 \
  nagios-plugins-all-2.3.3-2.el7.x86_64 nagios-plugins-nrpe-4.0.3-2.el7.x86_64 \
  aws-cfn-bootstrap-2.0-6.amzn2.noarch words-3.0-22.amzn2.noarch

# setup nrpe config
echo "log_facility=daemon" > /etc/nagios/nrpe.cfg
echo "pid_file=/var/run/nagios/nrpe.pid" >> /etc/nagios/nrpe.cfg
echo "server_port=5666" >> /etc/nagios/nrpe.cfg
echo "nrpe_user=nagios" >> /etc/nagios/nrpe.cfg
echo "nrpe_group=nagios" >> /etc/nagios/nrpe.cfg
echo "allowed_hosts=127.0.0.1" >> /etc/nagios/nrpe.cfg
echo "dont_blame_nrpe=0" >> /etc/nagios/nrpe.cfg
echo "allow_bash_command_substitution=0" >> /etc/nagios/nrpe.cfg
echo "debug=0" >> /etc/nagios/nrpe.cfg
echo "command_timeout=60" >> /etc/nagios/nrpe.cfg
echo "connection_timeout=300" >> /etc/nagios/nrpe.cfg
echo "command[check_load]=/usr/lib64/nagios/plugins/check_load -r -w 20,15,10 -c 30,25,20" >> /etc/nagios/nrpe.cfg
echo "command[check_cpu]=/usr/lib64/nagios/plugins/check_cpu -w 80 -c 95" >> /etc/nagios/nrpe.cfg
echo "command[check_disk]=/usr/lib64/nagios/plugins/check_disk -w 30% -c 20% /" >> /etc/nagios/nrpe.cfg
echo "command[check_swap]=/usr/lib64/nagios/plugins/check_swap -w 20 -c 10" >> /etc/nagios/nrpe.cfg
echo "command[check_docker_proc]=/usr/lib64/nagios/plugins/check_procs -C dockerd -c 1:" >> /etc/nagios/nrpe.cfg
echo "command[check_ecs_agent_proc]=/usr/lib64/nagios/plugins/check_http -I 127.0.0.1 -p 51678 -u /v1/metadata" >> /etc/nagios/nrpe.cfg
echo "command[check_dd_agent_proc]=/usr/lib64/nagios/plugins/check_procs -u root -C agent -c 2:2" >> /etc/nagios/nrpe.cfg
echo "command[check_ntp_time]=/usr/lib64/nagios/plugins/check_ntp_time -H localhost" >> /etc/nagios/nrpe.cfg
echo "command[check_memory]=/usr/lib64/nagios/plugins/check_mem -w 80 -c 95" >> /etc/nagios/nrpe.cfg
echo "include_dir=/etc/nrpe.d/" >> /etc/nagios/nrpe.cfg

mkdir -p /etc/nrpe.d/

# register nrpe with xinetd
echo "# default: on" > /etc/xinetd.d/nrpe
echo "# description: NRPE (Nagios Remote Plugin Executor)" >> /etc/xinetd.d/nrpe
echo "service nrpe" >> /etc/xinetd.d/nrpe
echo "{" >> /etc/xinetd.d/nrpe
echo "    flags           = REUSE" >> /etc/xinetd.d/nrpe
echo "    socket_type     = stream" >> /etc/xinetd.d/nrpe
echo "    port            = 5666" >> /etc/xinetd.d/nrpe
echo "    wait            = no" >> /etc/xinetd.d/nrpe
echo "    user            = nagios" >> /etc/xinetd.d/nrpe
echo "    group           = nagios" >> /etc/xinetd.d/nrpe
echo "    server          = /usr/sbin/nrpe" >> /etc/xinetd.d/nrpe
echo "    server_args     = -c /etc/nagios/nrpe.cfg --inetd" >> /etc/xinetd.d/nrpe
echo "    log_on_failure  += USERID" >> /etc/xinetd.d/nrpe
echo "    disable         = no" >> /etc/xinetd.d/nrpe
echo "    only_from       = 127.0.0.1 172.16.0.0/12" >> /etc/xinetd.d/nrpe
echo "}" >> /etc/xinetd.d/nrpe

echo "nrpe		5666/tcp			# Nagios Remote Plugin Executor" >> /etc/services

systemctl restart xinetd

# add nrpe added checks
echo ${check_cpu} | base64 -d > /tmp/check_cpu.zip && unzip -p /tmp/check_cpu.zip > /usr/lib64/nagios/plugins/check_cpu
chmod 755 /usr/lib64/nagios/plugins/check_cpu
echo ${check_mem} | base64 -d > /tmp/check_mem.zip && unzip -p /tmp/check_mem.zip > /usr/lib64/nagios/plugins/check_mem
chmod 755 /usr/lib64/nagios/plugins/check_mem

# setup pretty host naming
INSTANCE_ID=$(curl --silent http://169.254.169.254/latest/meta-data/instance-id)
AVAILABILITY_ZONE=$(curl --silent http://169.254.169.254/latest/meta-data/placement/availability-zone)
REGION=$(echo $${AVAILABILITY_ZONE} | grep -Eo '[a-z]{2}-[a-z]+-[0-9]{1}')
NAME_FULL="${base_host_name}-$(shuf -n1 /usr/share/dict/words | sed -e 's/\(.*\)/\L\1/' | sed -e 's/\./-/g')-$(shuf -n1 /usr/share/dict/words | sed -e 's/\(.*\)/\L\1/' | sed -e 's/\./-/g')"

echo "$${NAME_FULL}" >/etc/hostname
echo "127.0.0.1 $${NAME_FULL}" >>/etc/hosts
hostname "$${NAME_FULL}"

# sanity check
if [ "$(hostname)" != "$${NAME_FULL}" ]; then
  echo "fatal: '$(hostname)' != '$${NAME_FULL}'"
  exit 1
fi

# setup a ecs registration script which needs to fork off as the ecs-agent is not started till
# after this script is completed.
echo ECS_CLUSTER=${cluster} >> /etc/ecs/ecs.config

classes=$(echo ${classes} | tr "," "\n")

echo "#!/bin/bash -xe" >> ~/ecs-chg-register.sh
echo "# Wait for the ECS service to be responsive" >> ~/ecs-chg-register.sh
echo "until curl -s http://localhost:51678/v1/metadata" >> ~/ecs-chg-register.sh
echo "do" >> ~/ecs-chg-register.sh
echo "  sleep 1" >> ~/ecs-chg-register.sh
echo "done" >> ~/ecs-chg-register.sh
echo "aws --region=$${REGION} ecs put-attributes --cluster=${cluster} \\" >> ~/ecs-chg-register.sh
echo "  --attributes name=rig.class.\$(echo ${classes} | tr ',' ' ' | awk '// {print $1}'),value=true,targetId=\$(curl -s http://localhost:51678/v1/metadata | jq -r .ContainerInstanceArn),targetType=container-instance" >> ~/ecs-chg-register.sh
chmod 755 ~/ecs-chg-register.sh
# fork it in the background where it will wait until http://localhost:51678/v1/metadata exists which signals
# the ecs-agent is up and registered to the ecs cluster
~/ecs-chg-register.sh &

# setup pretty host tagging
aws ec2 create-tags --region $${REGION} --resources $${INSTANCE_ID} --tags "Key=Name,Value=$${NAME_FULL}" "Key=rig.class,Value=$${classes}"

echo "DAEMON_MAXFILES=1048576" > /etc/sysconfig/docker
echo "OPTIONS='--default-ulimit nofile=1024:4096 --log-driver json-file --log-opt max-size=10m --log-opt max-file=5'" >> /etc/sysconfig/docker
echo "DAEMON_PIDFILE_TIMEOUT=10" >> /etc/sysconfig/docker
systemctl restart docker

# gc docker images and containers
echo "docker image prune -a -f --filter 'until=3600s' 2>&1 | logger -t 'docker-prune'" > /etc/cron.daily/docker-gc
echo "docker container prune -f --filter 'until=3600s' 2>&1 | logger -t 'docker-prune'" >> /etc/cron.daily/docker-gc
echo "docker volume ls -qf dangling=true | xargs -r docker volume rm 2>&1 | logger -t 'docker-volume-cleanup'" >> /etc/cron.daily/docker-gc
chmod 755 /etc/cron.daily/docker-gc

# to prevent loss of container logs during restarts or network issues,
# the last log line collected for each container in this directory is stored on the host
# from https://docs.datadoghq.com/agent/docker/log/?tab=containerinstallation
mkdir -p /opt/datadog-agent/run

# configure ntp
ntpdate -u pool.ntp.org
systemctl restart ntpd

# signal cloudformation that we are up and happy
/opt/aws/bin/cfn-signal --exit-code $? --stack "${stackname}" --resource "RigClusterAsg" --region "$${REGION}"
```

**Comment by angelcar** [comment]
I just started a nee instance using `amzn2-ami-ecs-hvm-2.0.20200402-x86_64-ebs`. Here's what I see:

```bash
ls -l /var/cache/ecs
total 63796
lrwxrwxrwx 1 root root       21 Apr  3  2020 ecs-agent.tar -> ecs-agent-v1.39.0.tar
-rw-r--r-- 1 root root 65321472 Apr  3  2020 ecs-agent-v1.39.0.tar
-rw-r--r-- 1 root root        1 Jun 14 19:58 state
```

As you can see in my screenshot, the versions look correct, so something must have updated the agent in your AMI. 

![Screen Shot 2021-06-14 at 1 11 40 PM](https://user-images.githubusercontent.com/41758686/121953156-1166fe80-cd12-11eb-898a-d5010e5a9492.png)

I noticed that in your screenshot above, both ecs agent AND docker are updated. Docker should be `18.09.9-ce`, but your screenshot says `19.06.6-ce`. This reinforces the theory that perhaps `yum update` or similar was executed.

**Comment by danbf** [comment]
that might be possible for the `amzn2-ami-ecs-hvm-2.0.20200402-x86_64-ebs` instance since we also run some ansible.  

i'm mostly concerned about the current one and that it not update, but be pinned instead.  i'll try to run the newer user-data script  https://github.com/aws/amazon-ecs-agent/issues/2896#issuecomment-860955002 up against the `amzn2-ami-ecs-hvm-2.0.20200402-x86_64-ebs` ami an see what i wind up with.  

I would be happy to be wrong here and have it pinned in the AMI.

**Comment by angelcar** [comment]
Ok, I am closing this for now as I cannot repro the issue. A new instance was launched with `amzn2-ami-ecs-hvm-2.0.20200402-x86_64-ebs` and it displays the correct versions as per the documentation. The version is pinned to the AMI, as long as no explicit agent update is performed.

If you are able to repro and still believe this is a bug in the ECS Agent, please feel free to reopen this issue.

**Comment by danbf** [comment]
<img width="1176" alt="Screen Shot 2021-06-14 at 4 33 15 PM" src="https://user-images.githubusercontent.com/5041307/121955700-45e8b380-cd2e-11eb-9f7c-838a31152d56.png">
sorry about all the noise.  running our ansible-less user-data script https://github.com/aws/amazon-ecs-agent/issues/2896#issuecomment-860955002 does indeed show the pinned version as does the `ls`

```
 ls -l /var/cache/ecs/
total 63796
lrwxrwxrwx 1 root root       21 Apr  3  2020 ecs-agent.tar -> ecs-agent-v1.39.0.tar
-rw-r--r-- 1 root root 65321472 Apr  3  2020 ecs-agent-v1.39.0.tar
-rw-r--r-- 1 root root        1 Jun 14 20:32 state
```

**Comment by danbf** [comment]
i found the devil.  our packer script was doing a `yum update` rather than a `yum makecache`.  we didn't catch it since we have been a debian shop and were used to doing `apt-get update`'s all the time when installing packages.
