### ISSUE TITLE
Clarification on offline orchestration

### ISSUE THREAD

**Issue by stekern** [aws/amazon-ecs-agent#2916]
### Summary

I am looking for some clarifications on how the ECS agent behaves in an offline setting (e.g., due to a network outage), and to what extent any local orchestration is being done in such a scenario, but I have not been able to find any documentation on this.

### Description

As an example, if I am running the ECS agent on an EC2 instance and a network outage occurs that prohibits any network traffic, is there any offline and local orchestration of the currently running containers on the instance? In such an offline state, if a running container suddenly exists due to an application failure, will the ECS agent spin up a new one? Or is there no orchestration being performed without a network connection to the ECS endpoints?

**Comment by yinyic** [comment]
Hi @stekern , thank you for your inquiry!

ECS Agent currently does not have an "offline" mode, and neither does it initiates an attempt to resurrect a failed Task. Agent gets instructions to spin up/down containers solely from ECS Control Plane, which requires network connection. 

Please let us know if that helps answer your question.

**Comment by fierlion** [comment]
I'm looking at the changes made for ECS-Anywhere https://aws.amazon.com/blogs/containers/introducing-amazon-ecs-anywhere/ to see if there's anything there that might apply to your questions.

offline/local orchestration
ECS Agent restarting an exiting container

**Comment by fierlion** [comment]
I didn't find anything specifically applicable in our ecs-anywhere implementation.  

If you have specific feature requests related to the "offline mode", please open an issue in https://github.com/aws/containers-roadmap.
