### ISSUE TITLE
GraphQL Task Metadata Endpoint

### ISSUE THREAD

**Issue by SeaverDahlgren** [aws/amazon-ecs-agent#2921]
# Summary
The TMDE currently implements multiple REST endpoints, which lead to issues with both error-handling, potential latency problems, and backwards-compatibility as the metadata changes over time. These issues can be solved by implementing a new GraphQL endpoint, which allows EC2 containers to request only the information that they need. This query system will allow for both, a lot more flexibility and rigor when clients request metadata.

# Description
## Error Responses

The TMDE relies on the APIs to retrieve the network and tags fields, namely `“Networks”`,  `"ContainerInstanceTags"`, and `"TaskTags"` . When there are errors invoking these APIs, the TMDE will not be able to access these fields, leading to request errors. With current TMDE implementation, customers do not receive an error response from their request. This imprecise error response leads to a nondeterministic error handling response as seen in this ticket (https://github.com/aws/amazon-ecs-agent/issues/2728). In the example ticket, if a request for  `"TaskTags"` was made to the TMDE, the response was successful response despite there being an ECS API communication error that prevented the retrieval of the tags. In this instance the successful response occurred due to the successful retrieval of `"ContainerInstanceTags"`. In some cases, however, the customer may want the entire response to fail. There is not an ideal way to respond to all cases.

GraphQL offers a built in `"errors"` field (http://spec.graphql.org/draft/#sec-Errors) in the response. This field contains a list of errors whereby each error has a message key that points to a description of the error that occurred. If a field cannot be resolved, GraphQL creates a partial response with the raised field errors. In the above ticket, the resulting response would include all of the available metadata along with a field error indicating that the `"TaskTags"` field had an ECS API error. Furthermore, the customer can now parse the error field and respond accordingly.

```
{
    "data": {
        "containerByName": {
            "KnownStatus": "RUNNING"
            "DockerID": null
    },
    "errors": [
        {
            "message": "unable to get docker ID from v3 endpoint ID: 1bad2e54-c179-426b-9941-35fa3c7f5618",
            "locations": [
                {
                    "line": 4,
                    "column": 5
                }
            ],
            "path": [
                "containerByName", "DockerID"
            ]
        }
    ]
}  
```

## Memory and Latency

When customers request data from the endpoint, the response includes fields that may not be necessary. This can lead to memory and latency issues as the number of requests increases. Using GraphQL, customers are able to specify exactly what data they need, which also makes parsing easier. The following is an example query that only returns two desired container parameters, `knownstatus` and `dockerid`.

Query 
```
{
    containerByName(dockerName: "curl") {
        knownstatus
        dockerid
    }
}
```
Response
```
{
    "data": {
        "containerByName": {
            "KnownStatus": "RUNNING"
            "DockerID": "ea32192c8553fbff06c9340478a2ff089b2bb5646fb718b4ee206641c9086d66"
        }
    }
}
```

## Backwards Compatibility/Removing Endpoint Redundancies
In order to not break customer code, multiple versions and paths of TMDE have been created to provide slightly modified metadata responses. For example, the `/task` and `/taskWithTags` paths of the version 4 yield identical results, aside from the presence of task and container tags. With a GraphQL endpoint, the customer can simply specify exactly what metadata they want to avoid creating additional endpoints. Note that customers can also opt to use the version 4 endpoint as the metadata in the version 4 endpoint will update in parallel with the new GraphQl endpoint.

## Introspection and Self-Documentation
There currently is documentation (https://docs.aws.amazon.com/AmazonECS/latest/developerguide/task-metadata-endpoint-v4.html) for each endpoint of the TMDE. The current documentation does not appear to be extensive as there additional endpoints (https://github.com/SeaverDahlgren/amazon-ecs-agent/blob/fddb17a1bc49ae8865dc9b0f87894901661dc65a/agent/handlers/task_server_setup.go#L150-L152) with no documentation. Introspection is a key feature of GraphQL, which allows the client to easily find the available queries directly from a query to the GraphQL schema. GraphQL implements this through an additional field `__type` and the subfield, `fields`. To utilize this feature, the following request can be made:

Query 
```
{
  __type(name: "Query") {
    name
    fields {
      name
    }
  }
}
```
Response
```
{
  "data": {
    "__type": {
      "name": "Query",
      "fields": [
        {
          "name": "ContainerMetadata"
        },
        {
          "name": "ContainerStats",
        },
        {
          "name": "TaskMetadata",
        }
      ]
    }
  }
}
```

In the example above, the field entries (i.e. `"ContainerMetadata"`, `"ContainerStats"`, and `"TaskMetadata"`) are the names of potential root queries for the client. Note that the name fields are arbitrary, but the root query is traditionally named `“Query”` or `“RootQuery”`. This additional GraphQL feature can improve the ease of use by providing a simple way to discern what queries and fields are supported by the endpoint.

**Comment by mssrivas** [comment]
Closing this till it is ready for release.
