### ISSUE TITLE
`storage_stats` is empty

### ISSUE THREAD

**Issue by ahmed-mez** [aws/amazon-ecs-agent#2935]
### Summary
Empty `storage_stats` field in the stats payload returned by the ECS Task Metadata API.

### Description
Tried curling the the `stats` endpoints on the V2, V3 and V4 APIs, all of them return an empty `storage_stats` field. Even the examples documented [here](https://docs.aws.amazon.com/AmazonECS/latest/developerguide/task-metadata-endpoint-v4.html) are showing empty `storage_stats`. Is this expected?

Note: Unlike the [documented example](https://docs.aws.amazon.com/AmazonECS/latest/developerguide/task-metadata-endpoint-v4.html), I **can** see the values for `blkio_stats` in my task's stats payload.

### Expected Behavior
`storage_stats` not empty.

### Observed Behavior

```json
    "blkio_stats": {
        "io_service_bytes_recursive": [
            {
                "major": 202,
                "minor": 26368,
                "op": "Read",
                "value": 8192
            },
            {
                "major": 202,
                "minor": 26368,
                "op": "Write",
                "value": 2199552
            },
            {
                "major": 202,
                "minor": 26368,
                "op": "Sync",
                "value": 8192
            },
            {
                "major": 202,
                "minor": 26368,
                "op": "Async",
                "value": 2199552
            },
            {
                "major": 202,
                "minor": 26368,
                "op": "Total",
                "value": 2207744
            }
        ],
        "io_serviced_recursive": [
            {
                "major": 202,
                "minor": 26368,
                "op": "Read",
                "value": 2
            },
            {
                "major": 202,
                "minor": 26368,
                "op": "Write",
                "value": 24
            },
            {
                "major": 202,
                "minor": 26368,
                "op": "Sync",
                "value": 2
            },
            {
                "major": 202,
                "minor": 26368,
                "op": "Async",
                "value": 24
            },
            {
                "major": 202,
                "minor": 26368,
                "op": "Total",
                "value": 26
            }
        ],
        "io_queue_recursive": [],
        "io_service_time_recursive": [],
        "io_wait_time_recursive": [],
        "io_merged_recursive": [],
        "io_time_recursive": [],
        "sectors_recursive": []
    },
...
    "storage_stats": {},
```

### Environment Details

ECS Fargate 1.4.0

**Comment by sharanyad** [comment]
Sorry you're facing this issue @ahmed-mez! 
I'm following up with Fargate team about this issue. I shall update here once they get back.

Thanks,
Sharanya

**Comment by ahmed-mez** [comment]
Thank you Sharanya!

**Comment by ubhattacharjya** [comment]
Hi @ahmed-mez ,

Since you are using Fargate with platform version 1.4.0, kindly create a support ticket with AWS Fargate for better assistance.

Ref: https://docs.aws.amazon.com/awssupport/latest/user/case-management.html#creating-a-support-case

I will close this ticket. Kindly reopen if you have further questions.

Thanks,
Utsa

**Comment by shihtiy-tw** [comment]
Hi, @ahmed-mez 

Regarding your questions that why there is no metrics for `storage_stats ` from ECS task metadata while `blkio_stats` has metrics, it may not be related to Fargate or not but which platform you use, Linux or Windows.

## Explanation

As ECS agent get the metrics from docker [ContainerStats](https://docs.docker.com/engine/api/v1.30/#operation/ContainerStats) API, we can further check the metrics from moby repository.

From the following code, we can see that `storage_stats` is for Windows and `blkio_stats` is for Linux.

https://github.com/moby/moby/blob/7b9275c0da707b030e62c96b679a976f31f929d3/api/types/stats.go

```go
// Linux specific stats, not populated on Windows.
PidsStats  PidsStats  `json:"pids_stats,omitempty"`
BlkioStats BlkioStats `json:"blkio_stats,omitempty"`

// Windows specific stats, not populated on Linux.
NumProcs     uint32       `json:"num_procs"`
StorageStats StorageStats `json:"storage_stats,omitempty"`
```

https://github.com/moby/moby/blob/7b9275c0da707b030e62c96b679a976f31f929d3/api/types/stats.go

```go
// StorageStats is the disk I/O stats for read/write on Windows.
type StorageStats struct {
	ReadCountNormalized  uint64 `json:"read_count_normalized,omitempty"`
	ReadSizeBytes        uint64 `json:"read_size_bytes,omitempty"`
	WriteCountNormalized uint64 `json:"write_count_normalized,omitempty"`
	WriteSizeBytes       uint64 `json:"write_size_bytes,omitempty"`
}
```

## Labs

I can also get `storage_stats` from an ECS task running on Windows:

```
# on windows
Invoke-WebRequest -uri "http://169.254.170.2/v4/2239d0bc-e1b9-48e0-9d03-f44a30935f9f/stats" -UseBasicParsing | Select-Object -Expand Content

{
  "read": "2022-03-03T15:06:37.9523371Z",
  "preread": "2022-03-03T15:06:36.9398213Z",
  "pids_stats": {},
  "blkio_stats": {
    "io_service_bytes_recursive": null,
    "io_serviced_recursive": null,
    "io_queue_recursive": null,
    "io_service _time_recursive": null,
    "io_wait_time_recursive": null,
    "io_merged_recursive": null,
    "io_time_recursive": null,
    "sectors_recursive": null
  },
  "num_procs": 4,
  "storage_stats": {
    "read_count_normalized": 46167,
    "read_size_bytes": 32.0026112,
    "write_count_normalized": 2982,
    "write_size_bytes": 22934016
  },
...
...
```

We can also see that `storage_stats ` has metrics in the test stats for windows
https://github.com/aws/amazon-ecs-agent/blob/225bc3a556bd2d1759ab27b23f54e7e68086c9f0/agent/stats/windows_test_stats.json

## Summary

Please confirm that check that if your task is running on Linux or Windows. If the task is running on Linux and no `storage_stats ` metrics, I believe it is expected based on the comment in docker repository. Please try running task on windows as well and see if there is any `storage_stats` metrics.
