### ISSUE TITLE
Get health check host header in ECS_CONTAINER_METADATA_URI_V4 response (bridge mode) 

### ISSUE THREAD

**Issue by steverecio** [aws/amazon-ecs-agent#2936]
I have a set of containers in ECS and I need get the IP address used in the health check to add to my allowed hosts setting on my server. When I query ECS_CONTAINER_METADATA_URI_V4, I get the following in the NETWORKS section:

```
{
   "Networks":[
      {
         "IPv4Addresses":[
            "172.17.0.5"
         ],
         "NetworkMode":"bridge"
      }
   ]
}
```

However, the health checks have the following footprint:

`10.0.11.204 - - [06/Jul/2021:15:57:36 +0000] "GET / HTTP/1.1" 200 5034 "-" "ELB-HealthChecker/2.0"`

How can I get the `10.0.11.204` IP address dynamically in my containers so that the health checks will pass?

I'm using ECS agent version 1.50.0

**Comment by fierlion** [comment]
"4. To get the IP address of the container, use the docker inspect command:
```
$ IPADDR=$(docker inspect --format='{{.NetworkSettings.IPAddress}}' aabbccddeeff)
```
Note: The IP address of the container is saved to IPADDR. This will return an IP if using the BRIDGE network mode. If you use the AWSVPC or HOST network mode, then use the task IP assigned to the task ENI or host that the task is exposed through."

https://aws.amazon.com/premiumsupport/knowledge-center/troubleshoot-unhealthy-checks-ecs/

**Comment by steverecio** [comment]
Is there a reason this isn't available when querying `ECS_CONTAINER_METADATA_URI_V4`?

**Comment by steverecio** [comment]
Also, this returns the same IP address as the Networks section in the ECS_CONTAINER_METADATA_URI_V4 response. But the health check always uses the actual ec2 instance internal IP as the host header so my service rejects the health check. I need to be able to get the ec2 instance internal IP address dynamically inside my service since the health checker doesn't allow me to specify the host header to pass in.

**Comment by steverecio** [comment]
In case anyone runs into this in the future: https://mozilla.github.io/meao/2018/02/27/django-k8s-elb-health-checks/
