### ISSUE TITLE
SSM Parameter ARN parsing for windows credentialspec options fails under certain conditions

### ISSUE THREAD

**Issue by rue-nsilverman** [aws/amazon-ecs-agent#2943]
### Summary
When passing an SSM parameter ARN to the the `credentialspec` option of a task definition running on windows, retrieving the SSM parameter will fail if the SSM parameter is in a path other than `/`.

### Description
When specifying an SSM parameter ARN for the `credentialspec` option inside a task definition, [the documentation](https://docs.aws.amazon.com/AmazonECS/latest/developerguide/windows-gmsa.html) makes reference to filling in a `parameter_name`. Given the current way the ARN is parsed and passed to the AWS SDK, specifying a parameter that is in a path below `/` (example `/foo/gmsa_creds`), the ECS agent will fail to retrieve the SSM parameter. This is because the way the SSM ARN is parsed, its passed through a `filepath.Base()` function, rendering the example SSM parameter as `gmsa_creds`. This will cause the SDK to raise an `AccessDeniedException` because that parameter doesn't exist at the `/` path.

Using an SSM parameter ARN whose parameter name is `/gmsa_creds`, does behave as expected.

### Expected Behavior
specifying an SSM ARN for the `credentialspec` option on windows like
```
credentialspec:arn:aws:ssm:us-west-2:123456789012:parameter/subpath/test
```
should correctly retrieve the value of the SSM parameter at `/subpath/test`

### Observed Behavior
When specifying an SSM ARN that's anything other than at the `/` path, you will receive an `AccessDeniedException` and the container task will stop returning that exception to the ECS console under the stopped task details. This will always happen unless you also happen to have an SSM parameter at the root path.

For example, if you had an SSM parameter at `/subpath/test` and didn't also have that same parameter at `/test`, it would fail. If you duplicate the parameter to the `/test` path, it will succeed, and the ECS agent logs will log the fact that the parameter was retrieved.

I have also confirmed that this is not an IAM role issue as the role my task is using has the `arn:aws:iam::aws:policy/AmazonSSMFullAccess` policy attached.

### Environment Details
AMI ID ami-0499ce56124b91fc8 (Windows_Server-2019-English-Full-ECS_Optimized-2021.06.11)
Agent version 1.53.0
Docker version 20.10.5

### Supporting Log Snippets
An example error returned to the AWS ECS task details page (with redacted sensitive ARN info) is:
```
AccessDeniedException: User: arn:aws:sts::ACCOUNT_ID:assumed-role/ROLE_NAME/TASK_ID is not authorized to perform: ssm:GetParameters on resource: arn:aws:ssm:us-east-1:ACCOUNT_ID:parameter/gmsatest status code: 400, request id: REQUEST_ID
```

The task definition this container tried to launch with contains this snippet for the `credentialspec` options:
```
"dockerSecurityOptions": [
  "credentialspec:arn:aws:ssm:us-east-1:ACCOUNT_ID:parameter/test/gmsatest"
],
```

**Comment by vsiddharth** [comment]
Thanks a lot for bringing this to our attention @rue-nsilverman. 
We are looking into this and will keep this issue updated.

**Comment by rue-nsilverman** [comment]
No problem @vsiddharth! Not sure if you saw but I also submitted a PR with a proposed solution https://github.com/aws/amazon-ecs-agent/pull/2944

**Comment by vsiddharth** [comment]
@rue-nsilverman We could fix this issue by introducing a hierarchy to the local `credential-spec` file alongside volume paths. 

Currently `credential-specs` are modeled as a task resource and all of them are created together. When this task-resource is created, we could plumb the task\container details down to this resource and introduce a hierarchy similar to `CredSpecRoot\task\container\credspec` and wire this to the container appropriately.

**Comment by jterry75** [comment]
@vsiddharth - This has been resolved now right? Can we close this.
