### ISSUE TITLE
Hi Team,

### ISSUE THREAD

**Issue by Inugan** [aws/amazon-ecs-agent#2954]
Hi Team,
I have been facing the same error. I was hosting the Sonarqube on ECS FARGATE 1.4.0

**Status reason | CannotStartContainerError: ResourceInitializationError: failed to create new container runtime task: OCI runtime create failed: container_linux.go:**370**: starting container process caused: exec: "/opt/sonarqube/bin/run.sh": stat /opt/sonarqube/bin/run.sh...no such file or direct...**
While, in my dockerfile everything is in place.. And also the absolute path is also correct. 

This error is getting triggered while integrating ECS Fargate with EFS.

Without EFS, the cluster is working like a charm. Please help..

_Originally posted by @Inugan in https://github.com/aws/amazon-ecs-agent/issues/2442#issuecomment-879908093_

**Comment by sharanyad** [comment]
Sorry you're facing this issue @Inugan!
I'm following up with Fargate team about this issue. I shall update here once they get back.

Thanks,
Sharanya

**Comment by sharanyad** [comment]
@Inugan Could you please provide us the task ID which has this failure? You could also send it to ecs-agent-external (at) amazon.com

**Comment by ubhattacharjya** [comment]
Hi @Inugan ,

Since you are using Fargate with platform version 1.4.0, kindly create a support ticket with AWS Fargate.

Ref: https://docs.aws.amazon.com/awssupport/latest/user/case-management.html#creating-a-support-case

I will close this ticket. Kindly reopen if you have further questions.

Thanks,
Utsa

**Comment by VillageGimp** [comment]
Hi @ubhattacharjya I am also facing the same problem, what is the resolution? I have set everthing right like opening up 2049 in egress etc to connect to EFS. All the security groups are open. Still facing this issue. Kindly advice
