### ISSUE TITLE
The logs permissions

### ISSUE THREAD

**Issue by amandolo** [aws/amazon-ecs-agent#3028]
### Summary

The log files permissions are not configurable

### Description

We are hardening our AWS AMIs  following CIS Amazon Linux 2 Benchmark v2.0.0 rules.
We are unable to remediate at the rule **"4.2.4 Ensure permissions on all logfiles are configured"**.

To be compliant to this rule we have to remove wx for groups and rwx for other/world from all our log files in `/var/log/`.

The ECS Agent (its log files on `/var/log/ecs/` folder) is the only application we are unable to configure to create (and rotate) log files with our custom permissions.

We see in [this documentation](https://docs.aws.amazon.com/AmazonECS/latest/developerguide/logs.html
), lots of other options to configure the agent but not to change log files permissions.

Do you have a quick solution to this issue or do you plan to add this possible configuration?

**Comment by mythri-garaga** [comment]
@amandolo Thank you for filing this. We will take a look into this and get back.

**Comment by sharanyad** [comment]
@amandolo Could you please explain a bit on what this means? 
```
The ECS Agent (its log files on /var/log/ecs/ folder) is the only application we are unable to configure to create (and rotate) log files with our custom permissions.
```
What custom permissions were configured on your end?

**Comment by amandolo** [comment]
Hi @sharanyad, I'm sorry for the delay in my response.
I confirm what @chasen-bettinger has explained.

The CIS control checks that all log files in `/var/log/` have the permission of 0740, but the ecs-agent rotates the log files using 0644 permissions.

I read the relative bug in Seelog, it isn't resolved yet.
Do you have any proposal to resolve this issue?

**Comment by chasen-bettinger** [comment]
@amandolo I made a cronjob that runs every minute to set the permissions on the logs. It runs this command: `find /var/log -type f -exec chmod g-wx,o-rwx {} +`. Best I can do for now.

Would be great if this library migrated to a different logging library or Seelog became more customizable.

**Comment by angelcar** [comment]
As previously mentioned, seelog doesn't allow file permission customization. We will consider changing the logging library in the future in order to address this issue. In the meantime, it seems the proposed work around  (cron job) is the best way forward. 

Apologies inconvenience.

**Comment by hgmiguel** [comment]
I'm still having this issue. Are these changes in the roadmap?
