### ISSUE TITLE
Errors processing /v2/credentials 

### ISSUE THREAD

**Issue by giorgiocerruti** [aws/amazon-ecs-agent#3038]
### Summary

Looking at the agent log we found this request pèrocess get 400 error as a response 

`

### Description

```
level=info time=2021-09-22T16:33:35Z msg="Processing credential request, credentialType=TaskApplication taskARN=arn:aws:ecs:eu-west-1:615847981820:task/prod-worker/8ee79724637f46d5ad9dc8fe9ef8e3fe" module
=credentials_handler.go                                                                                                                                                                                     2021-09-22T16:33:35Z 200 172.17.0.151:47066 "/v2/credentials" "Zend_Http_Client" arn:aws:ecs:eu-west-1:615847981820:task/prod-worker/8ee79724637f46d5ad9dc8fe9ef8e3fe GetCredentials 2 prod-worker arn:aws:e
cs:eu-west-1:615847981820:container-instance/prod-worker/10abe8e5f47b47c38f3f5f3e232422fd                                                                                                                   level=error time=2021-09-22T16:33:35Z msg="HTTP response status code is '400', request type is: task metadata, and response in JSON is \"Unable to get task arn from request: unable to associate '172.17.0.
151' with task\"" module=helpers.go                 
```
It probably trying to retrieve IAM role from anywhere but it's really hard to say tp me.

### Expected Behavior
The request should returns 200

**Comment by sharanyad** [comment]
@giorgiocerruti  
Sorry you are observing these errors in agent logs. 
A quick glance at the error message especially `\"Unable to get task arn from request: unable to associate '172.17.0.151' with task\"" module=helpers.go` indicates that ECS agent thinks the credentials request potentially came from outside the task's containers. 
Could you share more information on what happens when these errors occur? Is your task functioning as expected or not? 
if not, is this the task `arn:aws:ecs:eu-west-1:615847981820:task/prod-worker/8ee79724637f46d5ad9dc8fe9ef8e3fe` that has issues obtaining credentials?

**Comment by giorgiocerruti** [comment]
Hi @sharanyad,

I discover that issue during my investigation on phantom containers - we named the issue like this :D. 
When we release a new docker image we found a lot of task definitions in a pending state and never achieve the `RUNNING` state.
SSH into the underline EC2 instances we found a lot of containers with no image name but a sha and they could not be stopped even manually.
The agent loses communication with those containers as well I believe.
As soon as I kill those containers manually (docker kill), the new containers are started by the agent.

We set up the task definitions with 10 containers for each TD and using the `latest` tag. The `stopTimeout` parameter has been set to 3600 seconds as the application can take that amount of time to gracefully shout down.

That being said, I've started to look into this reading the agent's logs and suddenly found the issue reported above

Idk if both issues are related to each other but I believe the `400` error must be fixed.

Please let me know if you need more info from me.

Giorgio

**Comment by sharanyad** [comment]
Seems like there could be multiple issues here. 
it is possible that containers are still running, but according to agent they are stopped, and hence the credential error logs.

> I feel like the SIGKILL is never throw after the SIGSTOP, in this case, would be throw after 3600 seconds 

There is a possibility that Docker sends SIGKILL but the container does not get killed. Having docker logs from the instance will help to confirm this. This seems inline with what is mentioned above:
>SSH into the underline EC2 instances we found a lot of containers with no image name but a sha and they could not be stopped even manually. 

To assist better with this, kindly request you to open a support case with AWS. 

Thanks,
Sharanya

**Comment by giorgiocerruti** [comment]
Hi @sharanyad ,
Thanks for the reply. 

The 400 errors come frome refreshed instance so non container stopped or unreached by the agent. 
I just what to know why the client reports 400 to fix the issue, unfortunately the agent log is too poor of information for understanding what is going on there.

About the other error, we are going to ask support as you suggested. 

Thank you

Giorgio
