### ISSUE TITLE
Support for Splunk logging driver

### ISSUE THREAD

**Issue by djenriquez** [aws/amazon-ecs-agent#304]
Docker 1.10 was released today, along with it, the splunk logging driver: https://github.com/docker/docker/pull/16488

Requesting support for this driver through ECS.

**Comment by glennblock** [comment]
:+1:

**Comment by zingbats** [comment]
+1

**Comment by mattcallanan** [comment]
+1

**Comment by ChrisRut** [comment]
+1

**Comment by csmithd** [comment]
+1

**Comment by wr0ngway** [comment]
Will this work now that latest the agent supports docker 1.11 ( https://aws.amazon.com/about-aws/whats-new/2016/05/amazon-ec2-container-service-supports-docker-1-11/ ) ?  Or does support need to be added into task definition api?

**Comment by mchene** [comment]
@wr0ngway it will require the following PR to be certified by Amazon ECS, https://github.com/aws/amazon-ecs-agent/pull/407.  You can test it now if you would like.

**Comment by samuelkarp** [comment]
We've merged #441, so this will be in the next release.

**Comment by glennblock** [comment]
Yay!

**Comment by aaithal** [comment]
This should be fixed in the [latest version of the agent](https://github.com/aws/amazon-ecs-agent/releases/tag/v1.11.0) released today.
