### ISSUE TITLE
invalid charactor '\x00'

### ISSUE THREAD

**Issue by tngus3722** [aws/amazon-ecs-agent#3098]
### Summary
ECS agent throws Error log endless about parsing

### Description

hello

using ECS in my project, APM warning about CPU utilization

the situation configured ECS agent throw exception log endlessly
for example 
![image](https://user-images.githubusercontent.com/32263898/143970341-ca426e7c-a77f-49b5-8a42-a7537b0fb64d.png)

and ubuntu /var/log/message
![image](https://user-images.githubusercontent.com/32263898/143970446-455463ff-9cf3-49b9-a50a-c7d0628cc193.png)

it consume CPU resource steadily

i have no idea why ECS agent out of order and can not found solution

i just update & restart ecs agent, the problem is closed 

why ecs agnet logging like above?

### Environment Details
![image](https://user-images.githubusercontent.com/32263898/143969988-f2f7a50e-3b7e-4003-8795-1663ff9ced3d.png)

**Comment by mythri-garaga** [comment]
Hi @tngus3722, these error logs seems to be coming from dockerd. Could you please describe how this is related to ECS Agent?

Thank you

**Comment by chienhanlin** [comment]
Hello @tngus3722 , 
Could you please share following information with us?
* Docker version
* ECS Agent version
* ECS Agent logs ([Amazon ECS Log File Locations](https://docs.aws.amazon.com/AmazonECS/latest/developerguide/logs.html)) 
* Describe how this is related to ECS Agent as @mythri-garaga suggested
* A sample log-file with the \x00
* Is this error coming from a certain container? or all containers?
  
A similar issue is reported to the docker/for-linux repo [Error grabbing logs: invalid character '\x00' looking for beginning of value #140](https://github.com/docker/for-linux/issues/140).

**Comment by fenxiong** [comment]
Closing the issue due to inactivity. as @chienhanlin pointed out, it seems to be related to this docker issue https://github.com/docker/for-linux/issues/140 instead of something specific to ecs agent, so i would suggest following up on the docker issue for this
