### ISSUE TITLE
Agent seems to stop dispatching after thousands of jobs

### ISSUE THREAD

**Issue by rayh** [aws/amazon-ecs-agent#31]
Sorry, this is a bit anecdotal, but I've seen this a few times.  After a couple of thousand short-lived jobs, the agent just seems to stop - no log output, no job dispatching, etc.

If I try and force stop and restart the agent, I get:

```bash
[ec2-user@ip-10-1-3-220 ~]$ sudo docker logs 1e2bf6f75398
t=2015-03-16T10:18:22+0000 lvl=crit msg="Error loading previously saved state" module=main err="Could not unmarshal state; incomplete save. There was no task for docker id 19408a2fba970833ac535a0b41cb22fe718b827fa8c23f6cf05e95048fd9ab6f"
```

Although the agent does actually come back up and start processing again.

**Comment by rayh** [comment]
Sorry, that lvl=crit error was not actually fatal, the agent does actually come up after that - So restarting does eventually restart job processing

**Comment by euank** [comment]
I think the above-merged commit will fix the issue that caused the second error there. If you run into that second one again I'd be interested in knowing.

The first issue is a deadlock and has not yet been fixed. I was able to reproduce it and am working on getting it fixed. I'll comment here again once I think I've got it.

Thanks for reporting both these issues! Good catch on both of them.

**Comment by euank** [comment]
Apologies this took so long to fix, it turned out to be a deeper-rooted issue than I expected.
With the release of the v1.1.0 agent, however, I think this should be resolved.

Thanks for reporting the issue and please let me know if you encounter further issues.

Best,
Euan
