### ISSUE TITLE
ECS Agent v1.59.0 - Windows Server - Intermittent failure to register instance into ECS Cluster

### ISSUE THREAD

**Issue by rafaelpissolatto** [aws/amazon-ecs-agent#3130]
### Summary
Intermittent failure to register/start ECS Agent (ASG - windows) - in some instances it works normally, others not.

### Description
We're using the same AMI, ASG and ECS Cluster (same refresh instance some EC2 works others don't)
[ecs-agent.log](https://github.com/aws/amazon-ecs-agent/files/8073673/ecs-agent.log)

```
level=critical time=2022-02-15T17:54:51Z msg="Terminal exit code received from agent.  Windows SCM will not restart the AmazonECS service." module=agent_windows.go
```

```
level=debug time=2022-02-15T17:54:46Z msg="Inspecting pause container image: amazon/amazon-ecs-pause:0.1.0" module=load.go
level=critical time=2022-02-15T17:54:51Z msg="Terminal exit code received from agent.  Windows SCM will not restart the AmazonECS service." module=agent_windows.go
level=error time=2022-02-15T17:54:51Z msg="Exiting 0" module=agent_windows.go
level=info time=2022-02-15T17:54:51Z msg="Stopping Windows service" module=agent_windows.go
level=info time=2022-02-15T17:54:51Z msg="Bye Bye! Exiting with 0" module=agent_windows.go
```

### Environment Details
```shell
[Instance not working]
PS C:\Temp> docker info
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  app: Docker Application (Docker Inc., v0.8.0)
  registry: Manage Docker registries (Docker Inc., 0.1.0)
WARNING: Plugin "C:\\Program Files\\Docker\\cli-plugins\\docker-cluster.exe" is not valid: failed to fetch metadata: exit status 1

Server:
 Containers: 0
  Running: 0
  Paused: 0
  Stopped: 0
 Images: 3
 Server Version: 20.10.7
 Storage Driver: windowsfilter
  Windows:
 Logging Driver: json-file
 Plugins:
  Volume: local
  Network: ics internal l2bridge l2tunnel nat null overlay private transparent
  Log: awslogs etwlogs fluentd gcplogs gelf json-file local logentries splunk syslog
 Swarm: inactive
 Default Isolation: process
 Kernel Version: 10.0 17763 (17763.1.amd64fre.rs5_release.180914-1434)
 Operating System: Windows Server 2019 Datacenter Version 1809 (OS Build 17763.2366)
 OSType: windows
 Architecture: x86_64
 CPUs: 4
 Total Memory: 15.62GiB
 Name: EC2AMAZ-KMT2JJU
 ID: CPPD:3ONI:R44G:ZOHZ:3LIK:AI3B:GEMC:IS6U:MUQG:UO7N:SEZM:KHJP
 Docker Root Dir: C:\ProgramData\docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

```shell
[Instance working fine]
PS C:\Temp> docker info
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  app: Docker Application (Docker Inc., v0.8.0)
  registry: Manage Docker registries (Docker Inc., 0.1.0)
WARNING: Plugin "C:\\Program Files\\Docker\\cli-plugins\\docker-cluster.exe" is not valid: failed to fetch metadata: exit status 1

Server:
 Containers: 6
  Running: 4
  Paused: 0
  Stopped: 2
 Images: 7
 Server Version: 20.10.7
 Storage Driver: windowsfilter
  Windows:
 Logging Driver: json-file
 Plugins:
  Volume: local
  Network: ics internal l2bridge l2tunnel nat null overlay private transparent
  Log: awslogs etwlogs fluentd gcplogs gelf json-file local logentries splunk syslog
 Swarm: inactive
 Default Isolation: process
 Kernel Version: 10.0 17763 (17763.1.amd64fre.rs5_release.180914-1434)
 Operating System: Windows Server 2019 Datacenter Version 1809 (OS Build 17763.2366)
 OSType: windows
 Architecture: x86_64
 CPUs: 4
 Total Memory: 15.62GiB
 Name: EC2AMAZ-BG5OB4S
 ID: CPPD:3ONI:R44G:ZOHZ:3LIK:AI3B:GEMC:IS6U:MUQG:UO7N:SEZM:KHJP
 Docker Root Dir: C:\ProgramData\docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

### Supporting Log Snippets
```
[Instance not working]
level=info time=2022-02-15T17:54:41Z msg="Successfully got ECS instance credentials from provider: EC2RoleProvider" module=instancecreds.go
level=info time=2022-02-15T17:54:41Z msg="Loading configuration" module=agent.go
level=debug time=2022-02-15T17:54:41Z msg="Environment variable empty: ECS_TASK_METADATA_RPS_LIMIT" module=parse.go
level=debug time=2022-02-15T17:54:41Z msg="Environment variable empty: ECS_ENGINE_TASK_CLEANUP_WAIT_DURATION_JITTER" module=parse.go
level=debug time=2022-02-15T17:54:41Z msg="Environment variable empty: ECS_CONTAINER_STOP_TIMEOUT" module=parse.go
level=debug time=2022-02-15T17:54:41Z msg="Environment variable empty: ECS_CONTAINER_START_TIMEOUT" module=parse.go
level=debug time=2022-02-15T17:54:41Z msg="Environment variable empty: ECS_CONTAINER_CREATE_TIMEOUT" module=parse.go
level=debug time=2022-02-15T17:54:41Z msg="Environment variable empty: ECS_IMAGE_PULL_INACTIVITY_TIMEOUT" module=parse.go
level=debug time=2022-02-15T17:54:41Z msg="Environment variable empty: ECS_IMAGE_PULL_TIMEOUT" module=parse.go
level=debug time=2022-02-15T17:54:41Z msg="Environment variable empty: ECS_IMAGE_MINIMUM_CLEANUP_AGE" module=parse.go
level=debug time=2022-02-15T17:54:41Z msg="Environment variable empty: NON_ECS_IMAGE_MINIMUM_CLEANUP_AGE" module=parse.go
level=debug time=2022-02-15T17:54:41Z msg="Environment variable empty: " module=parse.go
level=debug time=2022-02-15T17:54:41Z msg="Environment variable empty: ECS_POLLING_METRICS_WAIT_DURATION" module=parse.go
level=debug time=2022-02-15T17:54:41Z msg="Environment variable empty: ECS_CGROUP_CPU_PERIOD" module=parse.go
level=error time=2022-02-15T17:54:41Z msg="Unable to determine valid domain join: <nil>" module=parse_windows.go
level=error time=2022-02-15T17:54:46Z msg="Unable to determine valid domain join: <nil>" module=parse_windows.go
level=debug time=2022-02-15T17:54:46Z msg="Non-json user data, skip merging into agent config: invalid character '<' looking for beginning of value" module=config.go
level=info time=2022-02-15T17:54:46Z msg="Amazon ECS agent Version: 1.59.0, Commit: ed81f6b4" module=agent.go
level=debug time=2022-02-15T17:54:46Z msg="Loaded config: Cluster: qa-taxdocs-cluster-windows-ecs,  Region: us-east-1,  DataDir: C:\\ProgramData\\Amazon\\ECS\\data, Checkpoint: {1}, AuthType: , UpdatesEnabled: {0}, DisableMetrics: {0}, PollMetrics: {3}, PollingMetricsWaitDuration: 10s, ReservedMem: 256, TaskCleanupWaitDuration: 30m0s, DockerStopTimeout: 30s, ContainerStartTimeout: 8m0s, ContainerCreateTimeout: 4m0s, DependentContainersPullUpfront: {2}, TaskCPUMemLimit: {2}, ShouldExcludeIPv6PortBinding: {1}, " module=agent.go
level=info time=2022-02-15T17:54:46Z msg="Successfully got ECS instance credentials from provider: EC2RoleProvider" module=instancecreds.go
level=info time=2022-02-15T17:54:46Z msg="Unable to get Docker client for version 1.17: version detection using MinAPIVersion: unsupported version: 1.17" module=sdkclientfactory.go
level=info time=2022-02-15T17:54:46Z msg="Unable to get Docker client for version 1.18: version detection using MinAPIVersion: unsupported version: 1.18" module=sdkclientfactory.go
level=info time=2022-02-15T17:54:46Z msg="Unable to get Docker client for version 1.19: version detection using MinAPIVersion: unsupported version: 1.19" module=sdkclientfactory.go
level=info time=2022-02-15T17:54:46Z msg="Unable to get Docker client for version 1.20: version detection using MinAPIVersion: unsupported version: 1.20" module=sdkclientfactory.go
level=info time=2022-02-15T17:54:46Z msg="Unable to get Docker client for version 1.21: version detection using MinAPIVersion: unsupported version: 1.21" module=sdkclientfactory.go
level=info time=2022-02-15T17:54:46Z msg="Unable to get Docker client for version 1.22: version detection using MinAPIVersion: unsupported version: 1.22" module=sdkclientfactory.go
level=info time=2022-02-15T17:54:46Z msg="Unable to get Docker client for version 1.23: version detection using MinAPIVersion: unsupported version: 1.23" module=sdkclientfactory.go
level=info time=2022-02-15T17:54:46Z msg="Successfully got ECS instance credentials from provider: EC2RoleProvider" module=instancecreds.go
level=info time=2022-02-15T17:54:46Z msg="Starting Windows service" module=agent_windows.go
level=info time=2022-02-15T17:54:46Z msg="Image excluded from cleanup: amazon/amazon-ecs-pause:0.1.0" module=docker_image_manager.go
level=info time=2022-02-15T17:54:46Z msg="Image excluded from cleanup: amazon/amazon-ecs-pause:0.1.0" module=docker_image_manager.go
level=info time=2022-02-15T17:54:46Z msg="Image excluded from cleanup: amazon/amazon-ecs-agent:latest" module=docker_image_manager.go
level=info time=2022-02-15T17:54:46Z msg="Event stream ContainerChange start listening..." module=eventstream.go
level=info time=2022-02-15T17:54:46Z msg="Loading state!" module=state_manager.go
level=debug time=2022-02-15T17:54:46Z msg="Inspecting pause container image: amazon/amazon-ecs-pause:0.1.0" module=load.go
level=critical time=2022-02-15T17:54:51Z msg="Terminal exit code received from agent.  Windows SCM will not restart the AmazonECS service." module=agent_windows.go
level=error time=2022-02-15T17:54:51Z msg="Exiting 0" module=agent_windows.go
level=info time=2022-02-15T17:54:51Z msg="Stopping Windows service" module=agent_windows.go
level=info time=2022-02-15T17:54:51Z msg="Bye Bye! Exiting with 0" module=agent_windows.go
```

```
[Instance working fine]
evel=info time=2022-02-15T18:16:39Z msg="Successfully got ECS instance credentials from provider: EC2RoleProvider" module=instancecreds.go
level=info time=2022-02-15T18:16:39Z msg="Loading configuration" module=agent.go
level=debug time=2022-02-15T18:16:39Z msg="Environment variable empty: ECS_TASK_METADATA_RPS_LIMIT" module=parse.go
level=debug time=2022-02-15T18:16:39Z msg="Environment variable empty: ECS_ENGINE_TASK_CLEANUP_WAIT_DURATION_JITTER" module=parse.go
level=debug time=2022-02-15T18:16:39Z msg="Environment variable empty: ECS_CONTAINER_STOP_TIMEOUT" module=parse.go
level=debug time=2022-02-15T18:16:39Z msg="Environment variable empty: ECS_CONTAINER_START_TIMEOUT" module=parse.go
level=debug time=2022-02-15T18:16:39Z msg="Environment variable empty: ECS_CONTAINER_CREATE_TIMEOUT" module=parse.go
level=debug time=2022-02-15T18:16:39Z msg="Environment variable empty: ECS_IMAGE_PULL_INACTIVITY_TIMEOUT" module=parse.go
level=debug time=2022-02-15T18:16:39Z msg="Environment variable empty: ECS_IMAGE_PULL_TIMEOUT" module=parse.go
level=debug time=2022-02-15T18:16:39Z msg="Environment variable empty: ECS_IMAGE_MINIMUM_CLEANUP_AGE" module=parse.go
level=debug time=2022-02-15T18:16:39Z msg="Environment variable empty: NON_ECS_IMAGE_MINIMUM_CLEANUP_AGE" module=parse.go
level=debug time=2022-02-15T18:16:39Z msg="Environment variable empty: " module=parse.go
level=debug time=2022-02-15T18:16:39Z msg="Environment variable empty: ECS_POLLING_METRICS_WAIT_DURATION" module=parse.go
level=debug time=2022-02-15T18:16:39Z msg="Environment variable empty: ECS_CGROUP_CPU_PERIOD" module=parse.go
level=error time=2022-02-15T18:16:39Z msg="Unable to determine valid domain join: <nil>" module=parse_windows.go
level=error time=2022-02-15T18:16:44Z msg="Unable to determine valid domain join: <nil>" module=parse_windows.go
level=debug time=2022-02-15T18:16:44Z msg="Non-json user data, skip merging into agent config: invalid character '<' looking for beginning of value" module=config.go
level=info time=2022-02-15T18:16:44Z msg="Amazon ECS agent Version: 1.59.0, Commit: ed81f6b4" module=agent.go
level=debug time=2022-02-15T18:16:44Z msg="Loaded config: Cluster: qa-taxdocs-cluster-windows-ecs,  Region: us-east-1,  DataDir: C:\\ProgramData\\Amazon\\ECS\\data, Checkpoint: {1}, AuthType: , UpdatesEnabled: {0}, DisableMetrics: {0}, PollMetrics: {3}, PollingMetricsWaitDuration: 10s, ReservedMem: 256, TaskCleanupWaitDuration: 30m0s, DockerStopTimeout: 30s, ContainerStartTimeout: 8m0s, ContainerCreateTimeout: 4m0s, DependentContainersPullUpfront: {2}, TaskCPUMemLimit: {2}, ShouldExcludeIPv6PortBinding: {1}, " module=agent.go
level=info time=2022-02-15T18:16:44Z msg="Successfully got ECS instance credentials from provider: EC2RoleProvider" module=instancecreds.go
level=info time=2022-02-15T18:16:44Z msg="Unable to get Docker client for version 1.17: version detection using MinAPIVersion: unsupported version: 1.17" module=sdkclientfactory.go
level=info time=2022-02-15T18:16:44Z msg="Unable to get Docker client for version 1.18: version detection using MinAPIVersion: unsupported version: 1.18" module=sdkclientfactory.go
level=info time=2022-02-15T18:16:44Z msg="Unable to get Docker client for version 1.19: version detection using MinAPIVersion: unsupported version: 1.19" module=sdkclientfactory.go
level=info time=2022-02-15T18:16:44Z msg="Unable to get Docker client for version 1.20: version detection using MinAPIVersion: unsupported version: 1.20" module=sdkclientfactory.go
level=info time=2022-02-15T18:16:44Z msg="Unable to get Docker client for version 1.21: version detection using MinAPIVersion: unsupported version: 1.21" module=sdkclientfactory.go
level=info time=2022-02-15T18:16:44Z msg="Unable to get Docker client for version 1.22: version detection using MinAPIVersion: unsupported version: 1.22" module=sdkclientfactory.go
level=info time=2022-02-15T18:16:44Z msg="Unable to get Docker client for version 1.23: version detection using MinAPIVersion: unsupported version: 1.23" module=sdkclientfactory.go
level=info time=2022-02-15T18:16:44Z msg="Successfully got ECS instance credentials from provider: EC2RoleProvider" module=instancecreds.go
level=info time=2022-02-15T18:16:44Z msg="Starting Windows service" module=agent_windows.go
level=info time=2022-02-15T18:16:44Z msg="Image excluded from cleanup: amazon/amazon-ecs-pause:0.1.0" module=docker_image_manager.go
level=info time=2022-02-15T18:16:44Z msg="Image excluded from cleanup: amazon/amazon-ecs-pause:0.1.0" module=docker_image_manager.go
level=info time=2022-02-15T18:16:44Z msg="Image excluded from cleanup: amazon/amazon-ecs-agent:latest" module=docker_image_manager.go
level=info time=2022-02-15T18:16:44Z msg="Event stream ContainerChange start listening..." module=eventstream.go
level=info time=2022-02-15T18:16:44Z msg="Restored cluster 'qa-taxdocs-cluster-windows-ecs'" module=agent.go
level=debug time=2022-02-15T18:16:44Z msg="Inspecting pause container image: amazon/amazon-ecs-pause:0.1.0" module=load.go
level=info time=2022-02-15T18:16:49Z msg="Restored from checkpoint file. I am running as 'arn:aws:ecs:us-east-1:835409498431:container-instance/qa-taxdocs-cluster-windows-ecs/4a3e667cd64f4ed8bb5f29c9cff5d2d0' in cluster 'qa-taxdocs-cluster-windows-ecs'" module=agent.go
level=debug time=2022-02-15T18:16:49Z msg="operating system family is: WINDOWS_SERVER_2019_CORE" module=os_family_windows.go
level=info time=2022-02-15T18:16:49Z msg="Remaining mem: 15743" module=client.go
level=info time=2022-02-15T18:16:49Z msg="Registered container instance with cluster!" module=client.go
level=debug time=2022-02-15T18:16:49Z msg="Doctor healthchecks set up properly." module=agent.go
```

**Comment by vsiddharth** [comment]
Thanks a lot for reporting this. Could you please provide us with additional details like `user-data`, `instance-type`, etc.. 
Are you using the Amazon ECS Optimized Windows AMIs?

**Comment by rafaelpissolatto** [comment]
User_Data:
```powershell
[...]
[Environment]::SetEnvironmentVariable("ECS_CLUSTER", "${CLUSTER}", [System.EnvironmentVariableTarget]::Machine)
[Environment]::SetEnvironmentVariable("ECS_RESERVED_MEMORY", "256", [System.EnvironmentVariableTarget]::Machine)
[Environment]::SetEnvironmentVariable("ECS_ENABLE_CPU_UNBOUNDED_WINDOWS_WORKAROUND", "True", [System.EnvironmentVariableTarget]::Machine)
[Environment]::SetEnvironmentVariable("ECS_ENGINE_TASK_CLEANUP_WAIT_DURATION", "30m", [System.EnvironmentVariableTarget]::Machine)
[Environment]::SetEnvironmentVariable("ECS_DISABLE_IMAGE_CLEANUP", "False", [System.EnvironmentVariableTarget]::Machine)
[Environment]::SetEnvironmentVariable("ECS_IMAGE_CLEANUP_INTERVAL", "20m", [System.EnvironmentVariableTarget]::Machine)
[Environment]::SetEnvironmentVariable("ECS_AVAILABLE_LOGGING_DRIVERS", "[`"awsfirelens`",`"awslogs`",`"fluentd`",`"gelf`",`"json-file`",`"journald`",`"splunk`",`"logentries`",`"syslog`"]", [System.EnvironmentVariableTarget]::Machine)
[Environment]::SetEnvironmentVariable("ECS_ENABLE_AWSLOGS_EXECUTIONROLE_OVERRIDE", "True", [System.EnvironmentVariableTarget]::Machine)


Import-Module ECSTools
Remove-Item -Recurse C:\ProgramData\Amazon\ECS\Cache
Initialize-ECSAgent -Cluster "${CLUSTER}" -EnableTaskIAMRole -LoggingDrivers '["awsfirelens","awslogs","fluentd","gelf","json-file","journald","splunk","logentries","syslog","none"]'
```

Instance type used: m5a.xlarge or t3a.xlarge (the same intermittent situation for both)
AMI:  Windows_Server-2019-English-Core-ECS_Optimized (with additional and internal packages for monitoring and things like that)

**Comment by jterry75** [comment]
@rafaelpissolatto - Thank you for the additional information. I am looking into this.

**Comment by rafaelpissolatto** [comment]
As additional info, I've seen in the _ECSTools_ log the following error message:

From ECSTools (ecs-logs-collector.ps1 -RunMode debug)
`[ERROR]:C:\Program Files\Amazon\ECS\managed-agents\execute-command\bin\3.1.941.0\ssm-cli.exe not found`

Or during user_data setup (after Initialize-ECSAgent xxxxxx):
`[...]
[INFO] Initializing ECS agent on Cluster [dev-xxxxxxxxxxx-cluster-windows-ecs]
2022-03-08T20:21:51Z - [INFO]:Runtime is already installed.
2022-03-08T20:22:06Z - [INFO]:Docker version 20.10.9, build 591094d
False
2022-03-08T20:22:06Z - [INFO]:Configuring agent environment variables... complete
2022-03-08T20:22:06Z - [INFO]:Version was specified.
2022-03-08T20:22:06Z - [INFO]:Cached Agent Version: v1.59.0
2022-03-08T20:22:08Z - [INFO]:Download hash confirmed. Agent downloaded: C:\ProgramData\Amazon\ECS\cache\ecs-agent-windows-latest.zip
2022-03-08T20:22:14Z - [INFO]:Extracted ECS Download: C:\Program Files\Amazon\ECS\amazon-ecs-agent.exe

Status      :
Name        :
DisplayName :



    Directory: C:\Program Files\Amazon\ECS\managed-agents\execute-command\bin


Mode                LastWriteTime         Length Name
----                -------------         ------ ----
d-----         3/8/2022   5:22 PM                3.1.941.0


    Directory: C:\Program Files\Amazon\ECS\managed-agents\execute-command


Mode                LastWriteTime         Length Name
----                -------------         ------ ----
d-----         3/8/2022   5:22 PM                config
Get-ChildItem : Could not find item C:\Program Files\Amazon\SSM\ssm-cli.exe.
At C:\Program Files\WindowsPowerShell\Modules\ECSTools\ECSTools.psm1:2063 char:5
+     Get-ChildItem -Path "$Script:SSMBinPath\*.exe" | Copy-Item -Desti ...
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (C:\Program Files\Amazon\SSM\ssm-cli.exe:String) [Get-ChildItem],
IOException
    + FullyQualifiedErrorId : ItemNotFound,Microsoft.PowerShell.Commands.GetChildItemCommand
Get-ChildItem : Could not find item C:\Program Files\Amazon\SSM\ssm-cli.exe.
At C:\Program Files\WindowsPowerShell\Modules\ECSTools\ECSTools.psm1:2063 char:5
+     Get-ChildItem -Path "$Script:SSMBinPath\*.exe" | Copy-Item -Desti ...
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (C:\Program Files\Amazon\SSM\ssm-cli.exe:String) [Get-ChildItem], IOExce
   ption
    + FullyQualifiedErrorId : ItemNotFound,Microsoft.PowerShell.Commands.GetChildItemCommand

Get-ChildItem : Could not find item C:\Program Files\Amazon\SSM\ssm-document-worker.exe.
At C:\Program Files\WindowsPowerShell\Modules\ECSTools\ECSTools.psm1:2063 char:5
+     Get-ChildItem -Path "$Script:SSMBinPath\*.exe" | Copy-Item -Desti ...
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (C:\Program File...ment-worker.exe:String) [Get-ChildItem], IOException
    + FullyQualifiedErrorId : ItemNotFound,Microsoft.PowerShell.Commands.GetChildItemCommand
Get-ChildItem : Could not find item C:\Program Files\Amazon\SSM\ssm-document-worker.exe.
At C:\Program Files\WindowsPowerShell\Modules\ECSTools\ECSTools.psm1:2063 char:5
+     Get-ChildItem -Path "$Script:SSMBinPath\*.exe" | Copy-Item -Desti ...
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (C:\Program File...ment-worker.exe:String) [Get-ChildItem], IOException
    + FullyQualifiedErrorId : ItemNotFound,Microsoft.PowerShell.Commands.GetChildItemCommand

Get-ChildItem : Could not find item C:\Program Files\Amazon\SSM\ssm-session-logger.exe.
At C:\Program Files\WindowsPowerShell\Modules\ECSTools\ECSTools.psm1:2063 char:5
+     Get-ChildItem -Path "$Script:SSMBinPath\*.exe" | Copy-Item -Desti ...
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (C:\Program File...sion-logger.exe:String) [Get-ChildItem], IOException
    + FullyQualifiedErrorId : ItemNotFound,Microsoft.PowerShell.Commands.GetChildItemCommand
Get-ChildItem : Could not find item C:\Program Files\Amazon\SSM\ssm-session-logger.exe.
At C:\Program Files\WindowsPowerShell\Modules\ECSTools\ECSTools.psm1:2063 char:5
+     Get-ChildItem -Path "$Script:SSMBinPath\*.exe" | Copy-Item -Desti ...
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (C:\Program File...sion-logger.exe:String) [Get-ChildItem], IOException
    + FullyQualifiedErrorId : ItemNotFound,Microsoft.PowerShell.Commands.GetChildItemCommand

Get-ChildItem : Could not find item C:\Program Files\Amazon\SSM\ssm-session-worker.exe.
At C:\Program Files\WindowsPowerShell\Modules\ECSTools\ECSTools.psm1:2063 char:5
+     Get-ChildItem -Path "$Script:SSMBinPath\*.exe" | Copy-Item -Desti ...
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (C:\Program File...sion-worker.exe:String) [Get-ChildItem], IOException
    + FullyQualifiedErrorId : ItemNotFound,Microsoft.PowerShell.Commands.GetChildItemCommand
Get-ChildItem : Could not find item C:\Program Files\Amazon\SSM\ssm-session-worker.exe.
At C:\Program Files\WindowsPowerShell\Modules\ECSTools\ECSTools.psm1:2063 char:5
+     Get-ChildItem -Path "$Script:SSMBinPath\*.exe" | Copy-Item -Desti ...
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (C:\Program File...sion-worker.exe:String) [Get-ChildItem], IOException
    + FullyQualifiedErrorId : ItemNotFound,Microsoft.PowerShell.Commands.GetChildItemCommand

2022-03-08T20:22:20Z - [ERROR]:C:\Program Files\Amazon\ECS\managed-agents\execute-command\bin\3.1.941.0\ssm-cli.exe not found
PS>TerminatingError(): "C:\Program Files\Amazon\ECS\managed-agents\execute-command\bin\3.1.941.0\ssm-cli.exe not found"
>> TerminatingError(): "C:\Program Files\Amazon\ECS\managed-agents\execute-command\bin\3.1.941.0\ssm-cli.exe not found"
>> TerminatingError(): "C:\Program Files\Amazon\ECS\managed-agents\execute-command\bin\3.1.941.0\ssm-cli.exe not found"
>> TerminatingError(): "C:\Program Files\Amazon\ECS\managed-agents\execute-command\bin\3.1.941.0\ssm-cli.exe not found"
>> TerminatingError(): "C:\Program Files\Amazon\ECS\managed-agents\execute-command\bin\3.1.941.0\ssm-cli.exe not found"
>> TerminatingError(): "C:\Program Files\Amazon\ECS\managed-agents\execute-command\bin\3.1.941.0\ssm-cli.exe not found"
>> TerminatingError(): "C:\Program Files\Amazon\ECS\managed-agents\execute-command\bin\3.1.941.0\ssm-cli.exe not found"
C:\Program Files\Amazon\ECS\managed-agents\execute-command\bin\3.1.941.0\ssm-cli.exe not found
C:\Program Files\Amazon\ECS\managed-agents\execute-command\bin\3.1.941.0\ssm-cli.exe not found
At C:\Program Files\WindowsPowerShell\Modules\ECSTools\ECSTools.psm1:83 char:5
+     Throw $Message
+     ~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (C:\Program File...i.exe not found:String) [], RuntimeException
    + FullyQualifiedErrorId : C:\Program Files\Amazon\ECS\managed-agents\execute-command\bin\3.1.941.0\ssm-cli.exe not
    found

PS>$global:?
False
**********************
Windows PowerShell transcript end`

**Comment by rawahars** [comment]
@rafaelpissolatto Thanks for providing additional details in this issue.

As per my understanding, the SSM agent installed on `Windows_Server-2019-English-Core-ECS_Optimized-2022.02.10` Windows AMIs is `3.1.338.0`. However, as per the logs above, the SSM agent version is `3.1.941.0` on the instance.

Did your scripts reinstall the SSM agent or is it a custom install of SSM agent?

**Comment by rafaelpissolatto** [comment]
@rawahars , to prepare the instance, we have a SSM's install based on `https://docs.aws.amazon.com/systems-manager/latest/userguide/sysman-install-win.html` before the Initialize-ECSAgent step, but I figured it was installed in a different location (not in `C:\Program Files\Amazon\ECS\managed-agents\`, I'm not sure)

**Comment by mahmah2** [comment]
@rawahars How we can disable the step that reinstalls the SSM Agent ?

**Comment by rawahars** [comment]
@mahmah2 This was an issue with the older AMIs last year. On the latest ECS Optimized Windows AMIs, this should not be a problem at all. Can you try using the latest ones or build your own via EC2 Image builder?

Ref finding latest AMIs: https://docs.aws.amazon.com/AmazonECS/latest/developerguide/retrieve-ecs-optimized_windows_AMI.html
Ref Building the AMIs: https://docs.aws.amazon.com/AmazonECS/latest/developerguide/windows-custom-ami.html
