### ISSUE TITLE
Containers/tasks started by ecs-agent sometimes have no network connectivity

### ISSUE THREAD

**Issue by milosivanovic** [aws/amazon-ecs-agent#3131]
### Summary
Containers/tasks started by ecs-agent in awsvpc, host or bridge mode sometimes do not have any network connectivity. The "sometimes" is segmented by the actual ECS instance host launch, not by re-running the task on an existing host. Once an instance is booted and is known to be "bad" (i.e. that the containers started by ecs-agent fail to have network connectivity), then none of the containers started by ecs-agent will EVER have network connectivity regardless of the network mode set in the ECS console.

### Details
I have been using ecs-agent in a custom ubuntu AMI successfully for over 6 months. The existing ECS instances that run on this custom AMI continue to function flawlessly. Recently, I needed to upgrade the memory on these ECS instances, so I launched a new ECS instance from the same launch template used to launch the currently-running ECS instances, and only updated the instance type to be one that has more memory.

After doing so, and seeing the new ECS instance show up in the ECS Instances tab in the ECS console UI, I set the old instance to DRAINING status. ECS began to start tasks on the new ECS instance, but the health check failed and those tasks were stopped shortly after with the error "Connection timed out." Investigating this connection/health check issue further found that containers/tasks on the new ECS instance, which has the same AMI as the currently-working instances, do not have any network connectivity whatsoever. The host instance itself DOES have network connectivity - just its ECS containers do not. These task containers have no connectivity whatsoever, even to the default route in `ip route`.

AWS Premium Support was brought in to investigate this issue further, and even after hours/days of very meticulous debugging, the issue could not be directly identified and appeared to be random, but strangely not completely random. It is worth noting that this issue only happens when a new instance is started; old instances whose tasks/containers were able to successfully start and have network connectivity continue to have network connectivity without issue. This bug only happens when adding new instances to a cluster (whether intended to replace old ones or not.)

**This issue seems to be directly related to ecs-agent because it only happens if tasks are started using the AWS system (ECS console UI, API (terraform), etc.) If a container is started directly with `docker run`, it has fully working network connectivity.** Proof below:

Container started directly with `docker run` using the bridge network - has network connectivity:
```
root@ip-172-28-2-165:~# docker run -it --net bridge nicolaka/netshoot bash
bash-5.1# curl https://8.8.8.8
<HTML><HEAD><meta http-equiv="content-type" content="text/html;charset=utf-8">
<TITLE>302 Moved</TITLE></HEAD><BODY>
<H1>302 Moved</H1>
The document has moved
<A HREF="https://dns.google/">here</A>.
</BODY></HTML>
```

Container started directly with `docker run` using the host network - has network connectivity:
```
root@ip-172-28-2-165:~# docker run -it --net host nicolaka/netshoot bash
bash-5.1# curl https://8.8.8.8
<HTML><HEAD><meta http-equiv="content-type" content="text/html;charset=utf-8">
<TITLE>302 Moved</TITLE></HEAD><BODY>
<H1>302 Moved</H1>
The document has moved
<A HREF="https://dns.google/">here</A>.
</BODY></HTML>
```

Whereas the task started by ECS itself in the UI, `ecs-passport-task-dev-troubleshooting-3-passport-container-dcfbfae0aef7f8be0a00`, has NO network connectivity:
```
root@ip-172-28-2-165:~# docker ps
CONTAINER ID   IMAGE                            COMMAND            CREATED          STATUS                    PORTS     NAMES
883cf7be6826   nicolaka/netshoot                "sleep infinity"   28 minutes ago   Up 28 minutes                       ecs-passport-task-dev-troubleshooting-3-passport-container-dcfbfae0aef7f8be0a00
b2c8e6a2cea7   amazon/amazon-ecs-pause:0.1.0    "/pause"           28 minutes ago   Up 28 minutes                       ecs-passport-task-dev-troubleshooting-3-internalecspause-c8cac1a6abe39a925700
f758dc73e046   amazon/amazon-ecs-agent:latest   "/agent"           39 minutes ago   Up 29 minutes (healthy)             ecs-agent
root@ip-172-28-2-165:~# docker exec -it 883cf7be6826 bash
bash-5.1# curl https://8.8.8.8
curl: (7) Failed to connect to 8.8.8.8 port 443 after 3062 ms: Host is unreachable
```

And it is not able to reach its default gateway either:
```
root@ip-172-28-2-165:~# docker exec -it 883cf7be6826 bash
bash-5.1# ip route
default via 172.28.2.1 dev eth0
169.254.170.2 via 169.254.172.1 dev ecs-eth0
169.254.172.1 via 169.254.172.1 dev ecs-eth0
172.28.2.0/24 dev eth0 proto kernel scope link src 172.28.2.38
bash-5.1# ping 172.28.2.1
PING 172.28.2.1 (172.28.2.1) 56(84) bytes of data.
From 172.28.2.38 icmp_seq=1 Destination Host Unreachable
From 172.28.2.38 icmp_seq=2 Destination Host Unreachable
From 172.28.2.38 icmp_seq=3 Destination Host Unreachable
^C
--- 172.28.2.1 ping statistics ---
4 packets transmitted, 0 received, +3 errors, 100% packet loss, time 3059ms
pipe 4
```
The task in ECS was tested in awsvpc mode, host mode and bridge mode, with the same outcome.

### Environment Details
```
root@ip-172-28-2-165:~# docker info
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  app: Docker App (Docker Inc., v0.9.1-beta3)
  buildx: Docker Buildx (Docker Inc., v0.7.1-docker)
  scan: Docker Scan (Docker Inc., v0.12.0)

Server:
 Containers: 14
  Running: 3
  Paused: 0
  Stopped: 11
 Images: 6
 Server Version: 20.10.12
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runtime.v1.linux runc io.containerd.runc.v2
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 7b11cfaabd73bb80907dd23182b9347b4245eb5d
 runc version: v1.0.2-0-g52b36a2
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: default
 Kernel Version: 5.11.0-1028-aws
 Operating System: Ubuntu 20.04.3 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 8
 Total Memory: 15.18GiB
 Name: ip-172-28-2-165
 ID: SVPI:E5UY:6YKL:2752:BLCG:NDPO:Z6U5:4VM5:24PW:KZBZ:AR6X:IGFC
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

```
"Cluster":"dev-cluster","ContainerInstanceArn":"arn:aws:ecs:ap-southeast-1:<redacted>:container-instance/dev-cluster/914f6592ac4a4d05877955b1ea82e6e9","Version":"Amazon ECS Agent - v1.59.0 (ed81f6b4)"}
```

```
root@ip-172-28-2-165:~# df -h
Filesystem      Size  Used Avail Use% Mounted on
/dev/root        62G  3.4G   59G   6% /
devtmpfs        7.6G     0  7.6G   0% /dev
tmpfs           7.6G     0  7.6G   0% /dev/shm
tmpfs           1.6G  1.1M  1.6G   1% /run
tmpfs           5.0M     0  5.0M   0% /run/lock
tmpfs           7.6G     0  7.6G   0% /sys/fs/cgroup
/dev/loop0       34M   34M     0 100% /snap/amazon-ssm-agent/3552
/dev/loop1       56M   56M     0 100% /snap/core18/1997
/dev/loop3       56M   56M     0 100% /snap/core18/2284
/dev/loop2       71M   71M     0 100% /snap/lxd/19647
/dev/loop5       68M   68M     0 100% /snap/lxd/21835
/dev/loop6       25M   25M     0 100% /snap/amazon-ssm-agent/4046
/dev/loop4       33M   33M     0 100% /snap/snapd/11588
/dev/loop7       62M   62M     0 100% /snap/core20/1328
/dev/loop8       44M   44M     0 100% /snap/snapd/14549
overlay          62G  3.4G   59G   6% /var/lib/docker/overlay2/9cf9482449d61dcfa06b0db804d3a3d2e5e4df26c99e839726937d7a3084bde6/merged
tmpfs           1.6G     0  1.6G   0% /run/user/1000
overlay          62G  3.4G   59G   6% /var/lib/docker/overlay2/150bf0fd3af204c5d3e9b4fe71d107cd9a12bc7bc410965d6961236e0837daef/merged
shm              64M     0   64M   0% /var/lib/docker/containers/b2c8e6a2cea7f1aae4db0c2caad08f762f6a2ecca6b25b3ac4f43b228dcfc66d/mounts/shm
overlay          62G  3.4G   59G   6% /var/lib/docker/overlay2/9a5897a9e08540f88910ff07829f58bd807ab5c1837c0c370203ddfb7c593025/merged
shm              64M     0   64M   0% /var/lib/docker/containers/883cf7be6826a784b1c66e2e9dc62ee4ab76e5fd219eb02fe784456184501205/mounts/shm
```

**Comment by angelcar** [comment]
Hi @milosivanovic, thanks for reporting this.

Could you run the [amazon-ecs-logs-collector](https://github.com/aws/amazon-ecs-logs-collector) in a couple of the instances that have the issue, and send them to ﻿﻿ecs-agent-external@amazon.com?

In addition, to try to narrow down the issue, could you try to repro using an Amazon Linux 2 AMI? This will help us see if the issue could be something related to Ubuntu or if it happens regardless of the OS.

Also, what instance types are you using? does the issue occur in one particular type?

**Comment by cparik** [comment]
@angelcar - 
Issue is not seen in AL2 AMI. 
The issue doesn't seem to be related or limited to a specific instance type based on our testing, however, the issue was originally seen on instance typ `c5.2xlarge`.

**Comment by abhimang** [comment]
I am also facing the same issue, any update on this. looking for solution

**Comment by mssrivas** [comment]
Do you have any specific reason to not use AL2? Migrate to AL2 is highly suggested since AL1 is only receiving patches for critical CVEs, and latest ECS Agent versions are not supported.

**Comment by fierlion** [comment]
To anyone facing this issue with Amazon Linux, please work to upgrade to AL2 and confirm that the issue is not present.

https://aws.amazon.com/blogs/aws/update-on-amazon-linux-ami-end-of-life

Just to reiterate what @mssrivas mentioned above.  We are not actively supporting the deprecated OS, only releasing patches for critical vulnerabilities.

Closing -- please re-open if you discover similar issues with AL2 or above.

**Comment by lukepritchard-homstar** [comment]
This issue is also present in Amazon Linux 2. What information do you further require to investigate this?
