### ISSUE TITLE
Unable to join external instance to ecs cluster

### ISSUE THREAD

**Issue by RobDarbyAngstrom** [aws/amazon-ecs-agent#3133]
### Summary
External Nodes are unable to join an ECS cluster since upgrading to ecs agent 1.59.0

I have numerous instances running 1.58.0 from last month which joined with no issues - they are in the same network so nothing has changed on the network configuration side.

### Description
Our servers are Running RHEL Server 7.9 and Docker 20.10.12, I have also observed this behavior with Docker 20.10.10 

ECS Agent restarts several times for many hours - nodes do seem to eventually register to the ecs cluster but we also see the below log entry from ECS agent when it fails.

`level=info time=2022-02-18T11:24:46Z msg="Successfully got instance credentials from file /rotatingcreds/credentials. Provider: RotatingSharedCredentialsProvider. Access Key ID XXXX42MX" module=rotating_shared_credentials_provider.go
level=info time=2022-02-18T11:24:46Z msg="Successfully got ECS instance credentials from provider: RotatingSharedCredentialsProvider" module=instancecreds.go
level=info time=2022-02-18T11:24:46Z msg="Loading configuration" module=agent.go
level=warn time=2022-02-18T11:24:46Z msg="Unable to fetch user data: blackholed" module=config.go
level=info time=2022-02-18T11:24:46Z msg="Amazon ECS agent Version: 1.59.0, Commit: ed81f6b4" module=agent.go
level=info time=2022-02-18T11:24:46Z msg="Running in external mode." module=agent.go
level=info time=2022-02-18T11:24:46Z msg="Successfully got ECS instance credentials from provider: RotatingSharedCredentialsProvider" module=instancecreds.go
level=info time=2022-02-18T11:24:46Z msg="Successfully got ECS instance credentials from provider: RotatingSharedCredentialsProvider" module=instancecreds.go
level=info time=2022-02-18T11:24:46Z msg="Image excluded from cleanup: amazon/amazon-ecs-pause:0.1.0" module=docker_image_manager.go
level=info time=2022-02-18T11:24:46Z msg="Image excluded from cleanup: amazon/amazon-ecs-pause:0.1.0" module=docker_image_manager.go
level=info time=2022-02-18T11:24:46Z msg="Image excluded from cleanup: amazon/amazon-ecs-agent:latest" module=docker_image_manager.go
level=info time=2022-02-18T11:24:46Z msg="Creating root ecs cgroup: /ecs" module=init_linux.go
level=info time=2022-02-18T11:24:46Z msg="Creating cgroup /ecs" module=cgroup_controller_linux.go
level=info time=2022-02-18T11:24:46Z msg="Event stream ContainerChange start listening..." module=eventstream.go
level=info time=2022-02-18T11:24:46Z msg="Loading state!" module=state_manager.go
level=info time=2022-02-18T11:24:46Z msg="Registering Instance with ECS" module=agent.go
level=info time=2022-02-18T11:24:46Z msg="Fetching Instance ID Document has been disabled" module=client.go
level=info time=2022-02-18T11:24:46Z msg="Remaining mem: 128353" module=client.go
level=error time=2022-02-18T11:25:06Z msg="Unable to register as a container instance with ECS: RequestError: send request failed\ncaused by: Post \"https://ecs.eu-west-2.amazonaws.com/\": context deadline exceeded" module=client.go
level=error time=2022-02-18T11:25:06Z msg="Error registering: RequestError: send request failed\ncaused by: Post \"https://ecs.eu-west-2.amazonaws.com/\": context deadline exceeded" module=agent.go`

there seems to be no clear pattern as to when they will eventually register to the cluster - but we can see them pinging using the SSM agent as soon as we attempt to join a cluster.

**Comment by rewanthtammana** [comment]
@RobDarbyAngstrom  How did you fix it?
