### ISSUE TITLE
docker ps command hang

### ISSUE THREAD

**Issue by hridyeshpant** [aws/amazon-ecs-agent#315]
Hi @samuelkarp 
one of  ECS instance  started hanging when running docker ps command.
we got same issue when we 

moved to amzn-ami-2015.09.d-amazon-ecs-optimized AMI and finally rollback to amzn-ami-2015.09.c-amazon-ecs-optimized.
but seems amzn-ami-2015.09.c-amazon-ecs-optimized also giving same issue now.

IMAGE : amzn-ami-2015.09.c-amazon-ecs-optimized
issue : running docker ps command hang

top - 06:25:29 up 9 days, 15 min,  3 users,  load average: 0.13, 0.17, 0.22
Tasks: 252 total,   1 running, 251 sleeping,   0 stopped,   0 zombie
Cpu(s):  1.2%us,  0.1%sy,  0.0%ni, 98.6%id,  0.0%wa,  0.0%hi,  0.0%si,  0.0%st
Mem:  30871392k total, 18639196k used, 12232196k free,   768708k buffers
Swap:        0k total,        0k used,        0k free, 13476696k cached

free -m
             total       used       free     shared    buffers     cached
Mem:         30147      18203      11943          0        750      13161
-/+ buffers/cache:       4291      25856
Swap:            0          0          0

vmstat -s
     30871392  total memory
     18635860  used memory
     13366228  active memory
      4282160  inactive memory
     12235532  free memory
       768888  buffer memory
     13471276  swap cache
            0  total swap
            0  used swap
            0  free swap
     32476646 non-nice user cpu ticks
         1538 nice user cpu ticks
     37910674 system cpu ticks
   1169278443 idle cpu ticks
      2209692 IO-wait cpu ticks
         1767 IRQ cpu ticks
       199125 softirq cpu ticks
       248840 stolen cpu ticks
   6706077546 pages paged in
    483007840 pages paged out
            0 pages swapped in
            0 pages swapped out
   2182560729 interrupts
     69339519 CPU context switches
   1454998199 boot time
      6270932 forks

i am attaching all ecs agent and docker log . Please advise us as this is causing our production deployment and need to do lots of manual work to remove faulty instance each time.
i am attaching all log including strace docker ps command, and you can look which state it is hanging.
Let me know if you need any other info.

**Comment by kevinoriordan** [comment]
We are also seeing this issue.

Running AMI amzn-ami-2015.09.e-amazon-ecs-optimized

**Comment by jbergknoff** [comment]
I have also been seeing this, running amzn-ami-2015.09.e-amazon-ecs-optimized (ami-cb2305a1).

**Comment by munhitsu** [comment]
same here and it seems to trigger ECS timeout i.e. #278

**Comment by munhitsu** [comment]
Interestingly I've had an outdated ECS optimized ami, and moving to latest: 2015.09.g solved the problem.
`docker ps` still occasionally takes longer but it's not triggering task shut down as described in #309

**Comment by aaithal** [comment]
@hridyeshpant Could you please verify if you are seeing this issue with the latest 2015.09.g  ECS Optimized AMI?

**Comment by samuelkarp** [comment]
@jbergknoff @hridyeshpant Are you still seeing this problem with the 2015.09.g ECS-optimized AMI?

**Comment by jbergknoff** [comment]
@samuelkarp I haven't seen the issue since upgrading.

**Comment by hridyeshpant** [comment]
@samuelkarp no after moving in .g , we are not seeing docker ps hang issue.
Thanks for fixing .

**Comment by juanrhenals** [comment]
Thanks @jbergknoff @hridyeshpant ! 

Closing this issue.

**Comment by jbergknoff** [comment]
I'm seeing this again on the 2015.09.g AMI. Maybe related: a task on the same instance is failing to start with `CannotPullContainerError: dial unix /var/run/docker.sock: too many open files`

**Comment by mjaverto** [comment]
@samuelkarp We're seeing the same thing on amzn-ami-2016.03.b-amazon-ecs-optimized (ami-a1fa1acc)

Would you suggest changing to amzn-ami-2015.09.g-amazon-ecs-optimized - ami-33b48a59 ?

**Comment by samuelkarp** [comment]
@mjaverto Can you open a new issue?  When you do so, please include:

* Output from `sudo pvs; sudo vgs; sudo pvs`
* Output from `docker info`
* A description of what you're running (e.g., lots of short-lived containers, a few long-lived containers, many containers linked together, containers sharing volumes, etc)

I'd also recommend that you take a look at the CloudWatch metrics for the EBS volumes attached to your instance(s); we've definitely seen Docker performance suffer if disk I/O starts to take a long time.  Note that by default the ECS-optimized AMI comes with [gp2 volumes](http://docs.aws.amazon.com/AWSEC2/latest/UserGuide/EBSVolumeTypes.html#EBSVolumeTypes_gp2), which have credit-based performance characteristics.  A good discussion on I/O characteristics is available in the [EBS documentation](http://docs.aws.amazon.com/AWSEC2/latest/UserGuide/ebs-io-characteristics.html).

**Comment by mjaverto** [comment]
@samuelkarp will do, thank for the info, I'll be back with more.

**Comment by mjaverto** [comment]
@samuelkarp just to update this issue, it was 100% I/O, no need to send stats.

For anyone else reading this, check out the EC2 > Volumes > Monitoring > Avg Queue length metric. For us it was like 30-40 when < 1 is ideal.

**Comment by samuelkarp** [comment]
@mjaverto Thanks for confirming!

**Comment by xialingxiao** [comment]
We are seeing this problem with "amzn-ami-2016.09.f-amazon-ecs-optimized [ami-ec2be583]". Is anyone else experiencing this?

**Comment by evelan** [comment]
Yup... i can't do anything

**Comment by oliverhr** [comment]
Here too any docker command hangs, after update:

```
docker-1.12.6-1.17.amzn1.x86_64               Sat 11 Feb 2017 05:54:37 PM UTC
kernel-4.4.44-39.55.amzn1.x86_64              Fri 10 Feb 2017 09:14:06 PM UTC
libxcb-1.11-2.21.amzn1.x86_64                 Fri 10 Feb 2017 09:14:05 PM UTC
krb5-devel-1.14.1-27.41.amzn1.x86_64          Fri 10 Feb 2017 09:14:05 PM UTC
kernel-tools-4.4.44-39.55.amzn1.x86_64        Fri 10 Feb 2017 09:14:05 PM UTC
glibc-devel-2.17-157.169.amzn1.x86_64         Fri 10 Feb 2017 09:14:05 PM UTC
libkadm5-1.14.1-27.41.amzn1.x86_64            Fri 10 Feb 2017 09:14:04 PM UTC
krb5-libs-1.14.1-27.41.amzn1.x86_64           Fri 10 Feb 2017 09:14:04 PM UTC
kernel-headers-4.4.44-39.55.amzn1.x86_64      Fri 10 Feb 2017 09:14:04 PM UTC
glibc-headers-2.17-157.169.amzn1.x86_64       Fri 10 Feb 2017 09:14:04 PM UTC
glibc-common-2.17-157.169.amzn1.x86_64        Fri 10 Feb 2017 09:14:01 PM UTC
glibc-2.17-157.169.amzn1.x86_64               Fri 10 Feb 2017 09:13:55 PM UTC
```

**Comment by nrcxcia** [comment]
I am seeing this issue again please re-open

**Comment by samuelkarp** [comment]
If you are currently experiencing problems, please open a new issue with information on what you're experiencing.

I am locking this issue.
