### ISSUE TITLE
Issue with mapping host folder to a container

### ISSUE THREAD

**Issue by bushev** [aws/amazon-ecs-agent#3160]
### Summary
Hello,

I'm using ECS with EC2 instances on Ubuntu 20.04. Sometimes (in 10% cases) Docker volume does not work as expected.

```
const params: RegisterTaskDefinitionCommandInput = {
  containerDefinitions: [
      {
       mountPoints: [
          {
            containerPath: '/var/run/sockets',
            sourceVolume: 'sockets'
          }
        ],
       // ...
      }
      // ...
  ],
   volumes: [
    {
        name: 'sockets',
        host: {
          sourcePath: `/etc/nginx/sockets/uXXXXX`
        }
      }
  ]
  // ...
}
```

When I'm inspecting the `/var/run/sockets` folder I get the following results:

`ls -lha /run` (good, expected)

```
...
drwxr-xr-x 2 root root 4.0K Mar 28 20:41 sockets
...
```

`ls -lha /run/sockets` (good, expected)

```
total 4.0K
drwxr-xr-x 2 root root 4.0K Mar 28 20:41 .
drwxr-xr-x 1 root root   21 Mar 28 20:41 ..
```

----

`ls -lha /run` (bad, directory without size and hard links)

```
...
drwxr-xr-x 0 root root   0 Mar 28 21:03 sockets
...
```

`ls -lha /run/sockets` (bad, expected at least `.` and `..`)

```
total 0
```

So, I suspect that sometimes for some reason the directory is mapped incorrectly. Could you advice please?

### Environment Details
```
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  app: Docker App (Docker Inc., v0.9.1-beta3)
  buildx: Docker Buildx (Docker Inc., v0.8.1-docker)
  scan: Docker Scan (Docker Inc., v0.12.0)

Server:
 Containers: 16
  Running: 16
  Paused: 0
  Stopped: 0
 Images: 8
 Server Version: 20.10.14
 Storage Driver: overlay2
  Backing Filesystem: xfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay soxy-driver
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 3df54a852345ae127d1fa3092b95168e4a88e2f8
 runc version: v1.0.3-0-gf46b6ba
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: default
 Kernel Version: 5.13.0-1019-aws
 Operating System: Ubuntu 20.04.3 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 2
 Total Memory: 3.627GiB
 Name: ip-172-31-30-142
 ID: C4WU:Y4OU:R4WR:EZGU:H6NH:QRVI:IKAG:LZSC:V2UR:U5L2:62JX:KXOA
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

![image](https://user-images.githubusercontent.com/7535766/161047050-e7d7d3c1-9347-4c6d-bb0b-5f278277a753.png)

UPD: Also, the directory `/etc/nginx/sockets` is mounted to a Nginx container using a volumes statement `/etc/nginx/sockets/:/var/run/sockets/:rw`. And that's so weird, but at the midnight, the Nginx container loses the ability to access directories with sockets for users. Restarting of Nginx container halps to resolve this issue (with Nginx) temporary.

**Comment by prateekchaudhry** [comment]
Hi @bushev, thank you for reaching out. Could you also get us debug logs by running [amazon-ecs-logs-collector](https://github.com/aws/amazon-ecs-logs-collector) on an instance with affected tasks? You could email them to ecs-agent-external@amazon.com

If possible to check, could you verify if you see this issue with AL2 AMIs?

**Comment by mssrivas** [comment]
No response in the last 3 months. Closing.
