### ISSUE TITLE
Windows Tasks refuse to start after a while - "CannotPullContainerError: error during connect: In the default daemon configuration on Windows, the docker client must be run with elevated privileges"

### ISSUE THREAD

**Issue by nakos937** [aws/amazon-ecs-agent#3165]
### Summary

My Windows ECS-based services refuse to start after a while, and I have to manually restart Docker and ECS Agent services on the container instances to make them run again. I restart these from Session Manager and that helps. 

### Expected Behavior
My containers run without interruption.

### Observed Behavior
Error:
CannotPullContainerError: error during connect: In the default daemon configuration on Windows, the docker client must be run with elevated privileges

### Environment Details
Windows 20222 Server Full ECS-optimized
Docker service with 1024MB RAM assigned.
t3a.small machine.

**Comment by jterry75** [comment]
@nakos937 - Is this 100% repro? After you restart the Docker service does it work for some time and then fail again? When Docker is running as a service has the permission been changed? What permission is it running under in service control?

**Comment by jterry75** [comment]
@nakos937 - Since I have not heard back from you I will be closing the issue. Please reopen if still need additional guidance or help.
