### ISSUE TITLE
New ECS Tasks don't allow ECS Exec, despite the option being enabled on ECS Service

### ISSUE THREAD

**Issue by mkielar** [aws/amazon-ecs-agent#3166]
### Summary
When an ECS Task fails container helthchecks, and gets replaced, the new ECS Task does not allow ECS Exec, despite the option being enabled on the service. This is reproducible on all of our ECS Fargate Tasks.

### Description

Consider following scenario:

1. We have an ECS Service running 2 tasks. The ECS Exec is enabled on the Service, and I'm able to open an `sh` session with it.
2. While being in the `sh` session in one of the tasks, I cause the task to fail (e.g. I cause the container to stop passing container healthchecks)
3. ECS sees that the container no longer passes healthchecks, and stops the container with "Task failed container healthchecks" Reason presented in ECS Console.
4. ECS spawns a new ECS Task for that service, to fulfil the `DesiredCount`.

### Expected Behavior
I expect all the tasks spawned by ECS Fargate to allow for ECS Exec.

### Observed Behavior
That new ECS Task, started by ECS in step 4, doesn't have ECS Exec enabled, and, when I try to connect it fails with:

> An error occurred (InvalidParameterException) when calling the ExecuteCommand operation: The execute command failed because execute command was not enabled when the task was run or the execute command agent isn’t running. Wait and try again or run a new task with execute command enabled and try again.

This is reproducible on any of our services on four different AWS Accounts.

### Environment Details
```
Fargate version: 1.4
```

### Supporting Log Snippets
N/A

**Comment by MrChrisRodriguez** [comment]
@mkielar which mechanism are you using to enable ECS Exec on the service?

**Comment by mkielar** [comment]
Hi @MrChrisRodriguez, sorry for the late response.
We're using `terraform` and we simply specify the required IAM permissions and set the `enable_execute_command` attribute to `true`, that's it. This worked for most of the cases, and then didn't for some.

I've reported that as a Support Ticket on our AWS Account, and have been told that there was an internal issue identified where some of the containers did not have the ExecuteCommand Agent in RUNNING status. And that the fix was to be delivered beginning of May 2022.

Looks like the fix has actually been delivered because for around a week I couldn't spot a single ECS Tasks which I would have troubles connecting to using ECS Exec. 

I think this can be closed now.
