### ISSUE TITLE
Error starting privileged container: "There are no more loopback devices available."

### ISSUE THREAD

**Issue by fabfuel** [aws/amazon-ecs-agent#317]
I try to run a task with one Jenkins master container and 2 slave (Jenkins Swarm) containers. The slaves run `privileged` to be able to run "docker in docker".

Sometimes one of the slave containers dies immediately after the start, sometimes both or none of them starts up.

This is the error message from `docker logs`
```
time="2016-02-22T12:34:36.307172081Z" level=info msg="API listen on /var/run/docker.sock"
time="2016-02-22T12:34:36.354962573Z" level=warning msg="Udev sync is not supported. This will lead to unexpected behavior, data loss and errors. For more information, see https://docs.docker.com/reference/commandline/daemon/#daemon-storage-driver-option"
time="2016-02-22T12:34:36.380955630Z" level=error msg="There are no more loopback devices available."
time="2016-02-22T12:34:36.381062717Z" level=fatal msg="Error starting daemon: error initializing graphdriver: loopback mounting failed"
   Failed to start docker (did you use --privileged when running this container?)
```
I'm not able to reproduce it reliably. If I restart the task, sometimes it works, sometimes it does't.

Any advice? 

Thanks
Fabian

**Comment by kiranmeduri** [comment]
Before I try to reproduce on my side, can you confirm if the steps mentioned [here](https://github.com/jpetazzo/dind/issues/19) are helpful? 

Thanks,
-kiran

**Comment by fabfuel** [comment]
Hi @kiranmeduri, today I could reproduce it on another environment, so it looks like it has nothing to do with the AWS ECS agent.
