### ISSUE TITLE
ECS_ENGINE_TASK_CLEANUP_WAIT_DURATION : Discrepancy between the Developer Guide and README.md

### ISSUE THREAD

**Issue by zcahill** [aws/amazon-ecs-agent#318]
There is a discrepancy in relation to the ECS_ENGINE_TASK_CLEANUP_WAIT_DURATION parameter between the Developer Guide (http://docs.aws.amazon.com/AmazonECS/latest/developerguide/ecs-agent-config.html) and the README.md found within the GitHub repository...

Initially, when needing use of this option, I followed the Guide which states the parameter name ECS_ENGINE_CLEANUP_WAIT_DURATION along with 'Valid time units being "ns", "us" (or "µs"), "ms", "s", "m", and "h".' Using this name with a '1s' value (for immediate clean-up), I could not get the feature to work? 

After a while of debugging, checking ecs-agent logs for errors (none was found), I finally came across the GitHub repository and noticed the slight difference between the parameter names. In addition, there was another salient bit of information "If set to less than 1 minute, the value will be ignored" which also contradicts the guide. 

Once the name and minimum value was updated, the 'cleanup' started working as expected! In summary it would be wise to update the Developer Guide, preferably also adding suitable error messages if parameter names are invalid or values are wrong (more so 'ignored') to stop hours of head-scratching...

**Comment by samuelkarp** [comment]
@zcahill Thanks for reporting this.  We've updated the documentation and this error should be fixed now.

**Comment by zcahill** [comment]
Hi @samuelkarp 

I'm only being pedantic, but I would probably update the "Example Values" column from:
> (Valid time units are "ns", "us" (or "µs"), "ms", "s", "m", and "h".)

to

> (Valid time units are "m", and "h".)

considering the minimum value is currently 1m.
