### ISSUE TITLE
Licensing

### ISSUE THREAD

**Issue by agh** [aws/amazon-ecs-agent#32]
https://github.com/aws/amazon-ecs-agent/blob/master/agent/agent.go#L1-L3

It _seems_ a little unusual to see 'All Rights Reserved' as well as the Apache 2.0 boilerplate in the header of all the files which were released. I'm curious what effect it has upon consumers of the code, and anything contributed back to the project via Pull Request or similar.

This ambiguity has come up with other projects recently, see -

https://github.com/GoogleWebComponents/google-sheets/issues/12

IANAL. Any clarification which you can supply would be much appreciated!

**Comment by hyandell** [comment]
Hi Alex,

Looking at the GoogleWebComponents issue, I believe that's for the situation in which an Apache 2.0 licensed project contains files that only say "All rights reserved. ". I've double checked ecs-agent, and I can't see any files that fit that pattern.

If you do find any files that say All rights reserved, but don't have an Apache 2.0 license header, please let us know as we may not have intended to publish that file on GitHub.

Thanks,

Hen

**Comment by agh** [comment]
Hi Hen,

That wasn't quite my point; you are correct that the HTML files just say "All Rights Reserved".

What my question was - in the case of files where *both statements are made* what is the legal impact? To my "I am not a lawyer" eye, it seems like stating that 'All Rights Reserved' conflicts with the later statement it is Apache 2.0 licensed because by applying that license, you are giving people rights to deal in and modify/use the software.

It seems really rare to see both statements, in the same project or file, hence my confusion and curiosity.

Sorry if this question was unclear when originally submitted. Please let me know if it remains unclear.

Thanks,
 -Alex

**Comment by hyandell** [comment]
Obviously, as I'm not a lawyer, and additionally not your lawyer, I can't give you legal advice about "What's the legal impact" for your project or use case.

But, I can clarify a few items:

* Is it common to put All Rights Reserved, before subsequently granting rights?
* Searching GitHub: For large corporations it appears to be common.

* Does it mean the software isn't under Apache License 2.0?
* We fully intend that the terms of the Apache License 2.0 apply to this software.

Apologies that I can’t provide legal advice, but hopefully this helps :)
