### ISSUE TITLE
missing parameters

### ISSUE THREAD

**Issue by onceupon** [aws/amazon-ecs-agent#3207]
### Summary
some parameters description are missing in README.md

### Description
The following parameters appear in [the Amazon ECS developer guide](https://docs.aws.amazon.com/AmazonECS/latest/developerguide/ecs-agent-config.html) but are missing here:
`ECS_ALLOW_OFFHOST_INTROSPECTION_ACCESS`
`ECS_ENABLE_GPU_SUPPORT`
`ECS_OFFHOST_INTROSPECTION_INTERFACE_NAME`
`ECS_SKIP_LOCALHOST_TRAFFIC_FILTER`
`HTTP_PROXY`
`NO_PROXY`

I wonder what are the reason for that, thanks

**Comment by angelcar** [comment]
Thanks for bringing this to our attention. I'll update this issue when said parameters are documented.
