### ISSUE TITLE
Stop Truncating the output for Task Failures

### ISSUE THREAD

**Issue by mssrivas** [aws/amazon-ecs-agent#3217]
Tell us about your request
What do you want us to build?

Which service(s) is this request for?
ECS EC2

Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?
Currently Tasks that fail with long reasons, get their outputs truncated, which limits debugging on failures.

Example:

CannotPullContainerError: containerd: pull command failed: time="2020-XX-XXTXX:XX:XXZ" level=info msg="apply failure, attempting cleanup" error="failed to extract layer sha256:XXXXXXXX: context ca...
The output is truncated after "Context ca" which we assume is Context Canceled.

There are more examples but currently not at hand

Are you currently working around this issue?
Not possible to workaround

Additional context
no context

Attachments
If you think you might have additional information that you'd like to include via an attachment, please do - we'll take a look. (Remember to remove any personally-identifiable information.)

**Comment by mssrivas** [comment]
https://github.com/aws/containers-roadmap/issues/1133

**Comment by chienhanlin** [comment]
A PR to fix Task level has been reviewed. Please take a look on  https://github.com/aws/amazon-ecs-agent/pull/3229 for more details.

**Comment by mssrivas** [comment]
Released as part of ECS Agent version [1.61.2](https://github.com/aws/amazon-ecs-agent/milestone/108)
