### ISSUE TITLE
Time taken by service to restart tasks

### ISSUE THREAD

**Issue by jbergknoff** [aws/amazon-ecs-agent#322]
I need to run a short-lived process repeatedly (e.g. a process that pulls from a queue, executes a job, dies). I have been doing this with an ECS service, which I understand is probably not an intended use case, but it does work. However, once my short-lived process dies, there is a delay of 10-30 seconds before the next short-lived process is started.

As an example, I've created an ECS service where the task definition runs the official `hello-world` Docker image. That image will just print a message and then die. Here's the event log from the ECS web UI:

Event Id | Event Time | Message
--- | --- | ---
5b61b45f-919c-44a0-8cff-bc39e8ee06b6 | 2016-02-25 10:40:31 -0600 | service hello-world has started 1 tasks: task 6f6a732a-7925-4730-abe2-927885e26a4f.
9083f83d-36d8-4daa-aed8-ad0259c65cf5 | 2016-02-25 10:40:10 -0600 | service hello-world has started 1 tasks: task 285e9e67-edc8-4e1f-843a-ecb4aecb7bc6.
3063c0fe-bb02-47ea-b26d-50b69e9645a8 | 2016-02-25 10:39:57 -0600 | service hello-world has started 1 tasks: task 2f0b45a6-3ba1-43a3-9358-3cab8a9aaf76.
2187dfad-39d9-4f5c-a35a-36c38e1ff9ac | 2016-02-25 10:39:34 -0600 | service hello-world has started 1 tasks: task 6bdcaf90-0a07-4262-ad7c-38c45e8afe41.
0e990942-90a5-4487-92a5-b2eb2e0fb6dc | 2016-02-25 10:39:19 -0600 | service hello-world has started 1 tasks: task f32aa609-c59c-4219-8fac-f295610ca38e.

Why doesn't the replacement container start sooner? Is this behavior configurable in any way? Is there a better approach to running this sort of workload?

Thanks for your help.

**Comment by aaithal** [comment]
Sample response:

@jbergknoff, as stated in the [documentation](http://docs.aws.amazon.com/AmazonECS/latest/developerguide/scheduling_tasks.html), the ECS service scheduler is best suited for long running stateless applications, although you can certainly schedule shorter running tasks using it if you choose. ECS does not provide configurations or customizations for the duration between deployments. You can also experiment with writing a custom scheduler to achieve really low latencies. [Here](https://github.com/awslabs/ecs-mesos-scheduler-driver) is an example of such a scheduler. You could also try [AWS Lambda](https://aws.amazon.com/lambda/details/) for shorter lived applications.

**Comment by samuelkarp** [comment]
@jbergknoff I'm going to close this issue for now.  Please feel free to re-open this issue or open a new issue for any further questions.
