### ISSUE TITLE
Having "Failed to create CoreCLR, HRESULT: 0x80004005" errors after changing "readonlyRootFilesystem" to "true"

### ISSUE THREAD

**Issue by MederD** [aws/amazon-ecs-agent#3299]
### Summary
Having "Failed to create CoreCLR, HRESULT: 0x80004005" errors after changing "readonlyRootFilesystem" to "true". 

### Description
Having "Failed to create CoreCLR, HRESULT: 0x80004005" errors after changing "readonlyRootFilesystem" to "true"

### Expected Behavior
ECS tasks up and running.

### Observed Behavior
ECS tasks failing.

**Comment by rawahars** [comment]
Hi @MederD, 

Can you please update this issue with your use case, the summary of what you are trying out, the failure scenario, expected behaviour and any other relevant details pertaining to this issue?

We can then promptly look into the failure mode. Thanks!

**Comment by MederD** [comment]
Hi,
According tho this https://docs.aws.amazon.com/config/latest/developerguide/ecs-containers-readonly-access.html
I changed task definition files for some applications. Then, I had the above error. 
Application runs on custom docker image based on dotnet

**Comment by Realmonia** [comment]
@MederD  Can you please provide what platform you are running ECS Agent on and what's the ECS Agent version you are seeing the problem?

It would be better if you can also attach related logs of this failure.

**Comment by MederD** [comment]
Running on fargate, platform version 1.4.0.
Logs show nothing, but:
```
Failed to create CoreCLR, HRESULT: 0x80004005
```

**Comment by Realmonia** [comment]
Thanks for the info. Fargate no longer uses the same Agent as EC2 ECS starting from PV 1.4, therefore we can't provide much help in this case. Please use AWS support to get help regarding Fargate issues. Thanks!

**Comment by h5aaimtron** [comment]
@MederD I believe this may be a .NET issue in that versions below .NET 8 require some form of write access to the filesystem. I have a .NET 8 app that doesn't have this issue, but every single .NET 6 one does.
