### ISSUE TITLE
Docker 1.9.2 availability 

### ISSUE THREAD

**Issue by chenliu0831** [aws/amazon-ecs-agent#330]
Hey,

Just curious when will Docker 1.9.2 will be available in the AMI. We are suffering from the docker bug [#14203](https://github.com/docker/docker/issues/14203) which seems to be fixed in 1.9.2. While there are workarounds it'll be nice if we don't need to patch anything. Thanks.

**Comment by kiranmeduri** [comment]
Thank you for reporting the issue. While we don't discuss details of our roadmap, we really appreciate your feedback. We will include this in our priorities for upcoming releases.

-kiran

**Comment by MaikuMori** [comment]
Just wanted to add that a lot of issues are caused by docker/docker#12606. So upgrading to 1.10+ would be preferred. I understand it's not so straightforward upgrade but I take planned downtime/problems over random downtime/problems anytime.

**Comment by mcheshier-switch** [comment]
Another +1 for upgrading the docker version on the base AMI - would be much more convenient for use in Spot Fleet.

**Comment by chazu** [comment]
We are encountering this issue in our production environment as well, a fix would be a boon to our engineering team =D

**Comment by richardpen** [comment]
We have released Docker 1.11.1 last week in the new AMI (2016.03.c).

**Comment by chenliu0831** [comment]
Awesome ! thanks. @richardpen
