### ISSUE TITLE
Update new service while keeping old task running

### ISSUE THREAD

**Issue by phbissiwu** [aws/amazon-ecs-agent#3330]
### Summary

Hello, I would like to ask is there a way to update the ecs service which will create a new task while keeping the old task also running without terminating it?

**Comment by Realmonia** [comment]
Hi @phbissiwu, 

Currently ECS Control Plane has no control on which task to terminate when update happens, and therefore I don't believe what you are asking is available now.

There is an issue in container roadmap https://github.com/aws/containers-roadmap/issues/125 that might be related to the feature you are asking for.

Please feel free to reopen if there are further information you need!
