### ISSUE TITLE
Better reporting about OOMed containers.

### ISSUE THREAD

**Issue by MaikuMori** [aws/amazon-ecs-agent#334]
Currently if container gets OOM killed due to hitting the memory limit the UI just says that the container exited. It's possible to detect that the container ran out of memory using `docker inspect`.

I think such situation should be shown in the events/task info.

Also in my case the container initially didn't get killed, but just got stuck not responding on ports. But it got killed as soon as I tried to start `bash` inside the container for debugging. Then by using `docker inspect` I was able to find out the actual reason of crash. Simple in retrospect, but took me couple days to find especially since only on some deployments the container hit the memory limit.

**Comment by samuelkarp** [comment]
Which version of Docker are you using?  There have been some problems with [unreliability of the OOM status flag](https://github.com/docker/docker/issues/18510) (especially in Docker 1.9.x), which is what the Agent reads in order to report exit reasons.

**Comment by MaikuMori** [comment]
I'm using the last ECS optimized image which has docker `1.9.1`. So the reporting actually checks that flag, but in my case docker just didn't set it properly?

**Comment by samuelkarp** [comment]
Correct, we read the flag [here](https://github.com/aws/amazon-ecs-agent/blob/v1.8.1/agent/engine/docker_container_engine.go#L533-L535).

**Comment by MaikuMori** [comment]
I'll close it since it's clearly an issue upstream. Thanks.
