### ISSUE TITLE
General question on releases

### ISSUE THREAD

**Issue by dentonbalto** [aws/amazon-ecs-agent#3352]
I've been following this repo for a few weeks in anticipation of new agents being prepared to patch some vulnerabilities. However, I haven't seen 1.62.1 or 1.62.2 available in my account's ECS console yet nor mentioned here: https://docs.aws.amazon.com/AmazonECS/latest/developerguide/ecs-agent-versions.html

What is the best way for knowing when these agents are readily available so I can update my clusters? TIA

**Comment by fierlion** [comment]
Hi @dentonbalto 
The best way to always locate the most up-to-date ECS Optimized AMI is to retrieve the latest AMI IDs from [SSM Parameter Store](https://docs.aws.amazon.com/AmazonECS/latest/developerguide/retrieve-ecs-optimized_AMI.html).  We publish these as we release the new AMIs.  (You might want to go check that right now.)
Leveraging these SSM parameters will allow you to automate your workflow to launch Container Instances with the most up-to-date AMI.

Note that there was no AMI released with 1.62.1 -- we rolled forward with 1.62.2 immediately.

For example 
```
% aws ssm get-parameters \
    --names "/aws/service/ecs/optimized-ami/amazon-linux-2/recommended/image_id" \
    --region us-west-2 \
    --query 'Parameters[].Value'
[
    "ami-069acfe015e16939a"
]
```
I can then call `describe-images` to find the ami name:
```
% aws ec2 describe-images --image-ids ami-069acfe015e16939a \
    --region us-west-2 \
    --query 'Images[].Name'
[
    "amzn2-ami-ecs-hvm-2.0.20220822-x86_64-ebs"
]
```

Closing -- please re-open if you have further questions.
