### ISSUE TITLE
Container using AWSVPC networking will not start.

### ISSUE THREAD

**Issue by kentsaunders** [aws/amazon-ecs-agent#3368]
### Summary
Container using AWSVPC networking will not start.

### Description
The ECS log indicates a MAC address problem when starting the "amazon/amazon-ecs-pause:0.1.0" container:

"[ECSCNI] Namespace setup failed due to error: add network failed: invalid MAC address. Retry count is 4." module=plugin_windows.go
"Unable to configure pause container namespace" task="4f64c7820dc14a2f86cdd646ab4e9e3e" error="add network failed: invalid MAC address"

I can manually start the container from the command line using a NAT interface.  The interface does get added to the host during the provisioning of the container.  The interface that is added to the host does have a MAC address that matches what is reported in the ECS logs.

2 Servers were created using AMI-0c4aa4dbdd97d1a55.  1 server is in us-gov-west-1a and the other is in 1b.  A container from the same ECS Task starts on the 1a server but not 1b.  1b has worked in the past with AWSVPC networking.  I have tried to deregister the ECS instance, Removing the db and initializing the agent again with these commands:

del C:\ProgramData\Amazon\ECS\cache\ecs-agent-windows-latest.zip
del C:\ProgramData\Amazon\ECS\cache\ecs-agent-windows-latest.zip.*
del C:\ProgramData\Amazon\ECS\data\agent.db
Initialize-ECSAgent -Cluster Test-Cluster -EnableTaskIAMRole -LoggingDrivers '["json-file","awslogs"]' -EnableTaskENI

The ECS agent is updated to 1.62.2 (from 1.61.1) during this process.

I would rather not provision a new ECS optimized instance since the configuration required for compliance would take a significant amount of time to implement.

**Comment by rawahars** [comment]
Hi @kentsaunders, Is this issue still impacting your workloads?

If this is still applicable, then can you please help us with understand more about this issue. Primarily, we want to understand from the logs few things-
- ENI MAC which was sent from ACS. This would be present in agent logs.
- CNI configuration from agent logs
- The CNI plugin invocation logs which would provide the information about what was the actual values when the CNI was invoked.
