### ISSUE TITLE
ECS agent "loses touch" with the containers of the task and can't stop them.

### ISSUE THREAD

**Issue by tallavi** [aws/amazon-ecs-agent#339]
Hi,

It seems to be happening sporadically after a task has been running for some time, usually more than 24h. I already enabled debug level on ecs log, but I'm not seeing any errors or anything strange in there. Should I post the entire thing?

I use the command line to stop a task I started (from the command line also), and it just doesn't stop the containers. It eventually gives up on trying to stop the task and gives up with this:

> INFO[0293] Describe ECS container status                 container=aaaaaaa/xxxx desiredStatus=STOPPED lastStatus=PENDING taskDefinition=ecscompose-xxx-yyyy:3
> .....
> 
> FATA[0610] Timeout waiting for ECS tasks' status to match desired
>

Notice that the lines before the error, the last status is pending, which I think is related to the issue. Somehow the task gone from running, to pending, it might be related to the problem. The web console shows the task under the stopped tab with the status "PENDING (Task stopped by user)".

When this scenario happens, it affects all running tasks in that instance, not one specific task.

When it happens, the only way I found to fix the instance is by running:

> sudo stop ecs
> sudo service docker restart
> sudo start ecs

and then starting up all the tasks again.... Extremely annoying.

Since it happens to me every now and then, I can provide more information as needed.

Thanks.

**Comment by samuelkarp** [comment]
Hi @tallavi,

Can you provide the following information to help us troubleshoot?
* The `agentConnected` value when you call DescribeContainerInstances for that instance
* Docker version
* ECS Agent version
* Output of `docker info`
* Anything relevant in the ECS Agent logs (located at `/var/log/ecs`)
* Anything relevant in the Docker daemon log (located at `/var/log/docker`)
* Output of `docker inspect <container>` where `<container>` is the container that appears to be stuck

Thanks,
Sam

**Comment by tallavi** [comment]
Just happened on a second machine....

The agent shows that it's connected (in the ecs web console).

It's a bit different this time (I guess there are several variations to the issue):

1) I did a "ecs-cli compose service" (I may have forgotten to mention that I use compose files and not standard task definition files). Since the compose file has changed. 

I got:

NFO[0001] Updated the ECS service with a new task definition. Old containers will be stopped automatically, and replaced with new ones  desiredCount=1 serviceName=ecscompose-service-prod-web taskDefinition=ecscompose-prod-web:22

And then it was done, but haven't done anything. I know it didn't really update, since I removed a container from the compose file, but it's still running.

2) So I did "ecs-cli compose service stop". It "stopped" the task, but the containers are still running.

INFO[0000] Updated ECS service successfully              desiredCount=0 serviceName=ecscompose-service-prod-web
INFO[0000] Describe ECS Service status                   desiredCount=0 runningCount=1 serviceName=ecscompose-service-prod-web
INFO[0031] Describe ECS Service status                   desiredCount=0 runningCount=0 serviceName=ecscompose-service-prod-web
INFO[0046] ECS Service has reached a stable state        desiredCount=0 runningCount=0 serviceName=ecscompose-service-prod-web

3) I did "ecs-cli compose service" but now it's stuck:

Starting service...
INFO[0000] Using ECS task definition                     TaskDefinition=ecscompose-prod-web:23
INFO[0001] Updated the ECS service with a new task definition. Old containers will be stopped automatically, and replaced with new ones  desiredCount=1 serviceName=ecscompose-service-prod-web taskDefinition=ecscompose-prod-web:23
INFO[0001] Describe ECS Service status                   desiredCount=1 runningCount=0 serviceName=ecscompose-service-prod-web
INFO[0032] Describe ECS Service status                   desiredCount=1 runningCount=0 serviceName=ecscompose-service-prod-web
INFO[0062] Describe ECS Service status                   desiredCount=1 runningCount=0 serviceName=ecscompose-service-prod-web
INFO[0093] Describe ECS Service status                   desiredCount=1 runningCount=0 serviceName=ecscompose-service-prod-web

Until it will fail on a time out.

The original containers from the stopped task are still running.


Docker log doesn't have anything, so I guess what I wrote before is irrelevant.

**Comment by tallavi** [comment]
Attached is the entire ecs-agent.log file from the past hour. I hope it doesn't contain any sensitive information.

[ecs-agent.log.2016-03-11-19.txt](https://github.com/aws/amazon-ecs-agent/files/169856/ecs-agent.log.2016-03-11-19.txt)

**Comment by samuelkarp** [comment]
> Agent version 1.8.0

Can you try upgrading to [1.8.1](https://github.com/aws/amazon-ecs-agent/releases/tag/v1.8.1)?  1.8.0 has a known deadlock problem that we resolved in 1.8.1.

**Comment by tallavi** [comment]
Ok, updated one machine. I'll keep an eye out for the issue. Thanks!

**Comment by samuelkarp** [comment]
@tallavi Did upgrading to 1.8.1 fix this problem for you?

**Comment by tallavi** [comment]
@samuelkarp I'm pretty sure it did! Haven't happened even once since, and I did allot of stopping and starting, both with and without a service! I'm pretty sure that was it.

**Comment by samuelkarp** [comment]
Thanks for confirming.  I'm going to close this now; feel free to reopen or open a new issue if you continue to have problems.

**Comment by wprater** [comment]
Im having this same issue with `1.14.3`
