### ISSUE TITLE
ecs agent stopping task

### ISSUE THREAD

**Issue by hridyeshpant** [aws/amazon-ecs-agent#341]
We are running cadvisor as ECS task, but ecs agent is stopping the running task after some time.
But if run ecs manually in the box , things are working fine.
We are using amzn-ami-2015.09.g-amazon-ecs-optimized AMI

**ecs agent log** =>
Status: (RUNNING->RUNNING) Containers: [cadvisor (RUNNING->RUNNING),]"
ecs-agent.log.2016-03-15-04:2016-03-15T04:00:05Z [DEBUG] Submitted container state change module="eventhandler" event="ContainerChange: arn:aws:ecs:us-west-2:408096535527:task/22ffc0c4-9798-4867-bb8a-7e3bdab2c191 cadvisor -> RUNNING, Ports [{8080 8080 0.0.0.0 0}], Known Sent: RUNNING"
ecs-agent.log.2016-03-15-04:2016-03-15T04:00:11Z [DEBUG] sending payload module="tcs client" payload="{"type":"PublishMetricsRequest","message":{"metadata":{"cluster":"hpant","containerInstance":"arn:aws:ecs:us-west-2:408096535527:container-instance/d913fbee-861b-4e7f-bd27-458ad3a45965","fin":true,"idle":false,"messageId":"0dd0dede-0d62-4a60-8e53-5957f6359898"},"taskMetrics":[{"containerMetrics":[{"cpuStatsSet":{"max":1.5978411436080933,"min":0,"sampleCount":12,"sum":6.078124076128006},"memoryStatsSet":{"max":20,"min":0,"sampleCount":13,"sum":186}}],"taskArn":"arn:aws:ecs:us-west-2:408096535527:task/22ffc0c4-9798-4867-bb8a-7e3bdab2c191","taskDefinitionFamily":"cadvisor","taskDefinitionVersion":"15"}],"timestamp":1458014411}}"
ecs-agent.log.2016-03-15-04:2016-03-15T04:00:22Z [DEBUG] Updating task module="api client" task="cadvisor:15 arn:aws:ecs:us-west-2:408096535527:task/22ffc0c4-9798-4867-bb8a-7e3bdab2c191, Status: (RUNNING->RUNNING) Containers: [cadvisor (STOPPED->RUNNING),]"
ecs-agent.log.2016-03-15-04:2016-03-15T04:00:22Z [DEBUG] Earliest status is STOPPED module="api client" task="cadvisor:15 arn:aws:ecs:us-west-2:408096535527:task/22ffc0c4-9798-4867-bb8a-7e3bdab2c191, Status: (RUNNING->RUNNING) Containers: [cadvisor (STOPPED->RUNNING),]"
ecs-agent.log.2016-03-15-04:2016-03-15T04:00:22Z [DEBUG] Updating task module="api client" task="cadvisor:15 arn:aws:ecs:us-west-2:408096535527:task/22ffc0c4-9798-4867-bb8a-7e3bdab2c191, Status: (STOPPED->RUNNING) Containers: [cadvisor (STOPPED->RUNNING),]"
ecs-agent.log.2016-03-15-04:2016-03-15T04:00:22Z [DEBUG] Updating task desired status to stopped module="api client" task="cadvisor:15 arn:aws:ecs:us-west-2:408096535527:task/22ffc0c4-9798-4867-bb8a-7e3bdab2c191, Status: (STOPPED->RUNNING) Containers: [cadvisor (STOPPED->RUNNING),]" container="cadvisor"
ecs-agent.log.2016-03-15-04:2016-03-15T04:00:22Z [DEBUG] Container change event module="TaskEngine" event="{TaskArn:arn:aws:ecs:us-west-2:408096535527:task/22ffc0c4-9798-4867-bb8a-7e3bdab2c191 ContainerName:cadvisor Status:STOPPED Reason: ExitCode:<nil> PortBindings:[{ContainerPort:8080 HostPort:8080 BindIp:0.0.0.0 Protocol:0}] SentStatus:RUNNING}"
ecs-agent.log.2016-03-15-04:2016-03-15T04:00:22Z [INFO] Adding event module="eventhandler" change="ContainerChange: arn:aws:ecs:us-west-2:408096535527:task/22ffc0c4-9798-4867-bb8a-7e3bdab2c191 cadvisor -> STOPPED, Ports [{8080 8080 0.0.0.0 0}], Known Sent: RUNNING"
ecs-agent.log.2016-03-15-04:2016-03-15T04:00:22Z [DEBUG] New event module="eventhandler" change="ContainerChange: arn:aws:ecs:us-west-2:408096535527:task/22ffc0c4-9798-4867-bb8a-7e3bdab2c191 cadvisor -> STOPPED, Ports [{8080 8080 0.0.0.0 0}], Known Sent: RUNNING"
ecs-agent.log.2016-03-15-04:2016-03-15T04:00:22Z [DEBUG] Container change event passed on module="TaskEngine" event="{TaskArn:arn:aws:ecs:us-west-2:408096535527:task/22ffc0c4-9798-4867-bb8a-7e3bdab2c191 ContainerName:cadvisor Status:STOPPED Reason: ExitCode:<nil> PortBindings:[{ContainerPort:8080 HostPort:8080 BindIp:0.0.0.0 Protocol:0}] SentStatus:RUNNING}"
ecs-agent.log.2016-03-15-04:2016-03-15T04:00:22Z [DEBUG]Task has reached stopped. We're just waiting and removing containers now module="TaskEngine" task="cadvisor:15 arn:aws:ecs:us-west-2:408096535527:task/22ffc0c4-9798-4867-bb8a-7e3bdab2c191, Status: (STOPPED->STOPPED) Containers: [cadvisor (STOPPED->STOPPED),]"
ecs-agent.log.2016-03-15-04:2016-03-15T04:00:22Z [DEBUG] Waiting for event for task module="TaskEngine" task="cadvisor:15 arn:aws:ecs:us-west-2:408096535527:task/22ffc0c4-9798-4867-bb8a-7e3bdab2c191, Status: (STOPPED->STOPPED) Containers: [cadvisor (STOPPED->STOPPED),]"
ecs-agent.log.2016-03-15-04:2016-03-15T04:00:22Z [INFO] Sending container change module="eventhandler" event="ContainerChange: arn:aws:ecs:us-west-2:408096535527:task/22ffc0c4-9798-4867-bb8a-7e3bdab2c191 cadvisor -> STOPPED, Ports [{8080 8080 0.0.0.0 0}], Known Sent: RUNNING" change="ContainerChange: arn:aws:ecs:us-west-2:408096535527:task/22ffc0c4-9798-4867-bb8a-7e3bdab2c191 cadvisor -> STOPPED, Ports [{8080 8080 0.0.0.0 0}], Known Sent: RUNNING"
ecs-agent.log.2016-03-15-04:2016-03-15T04:00:22Z [DEBUG] Submitted container state change module="eventhandler" event="ContainerChange: arn:aws:ecs:us-west-2:408096535527:task/22ffc0c4-9798-4867-bb8a-7e3bdab2c191 cadvisor -> STOPPED, Ports [{8080 8080 0.0.0.0 0}], Known Sent: STOPPED"
ecs-agent.log.2016-03-15-04:2016-03-15T04:00:22Z [DEBUG] Removed the last element, no longer sending module="eventhandler" event="ContainerChange: arn:aws:ecs:us-west-2:408096535527:task/22ffc0c4-9798-4867-bb8a-7e3bdab2c191 cadvisor -> STOPPED, Ports [{8080 8080 0.0.0.0 0}], Known Sent: STOPPED"
ecs-init.log.2016-03-15-04:2016-03-15T04:00:21Z [INFO] Container name: /ecs-cadvisor-15-cadvisor-d0c8aad7cbb287e45a00

**cadvisor container log :**
docker logs b0b050984cbf
I0315 04:00:06.159743 1 storagedriver.go:45] Caching stats in memory for 2m0s
I0315 04:00:06.160688 1 manager.go:168] cAdvisor running in container: "/docker/b0b050984cbf5631e7fae9d5522c5635a9d1bed34e41a25621fb6ac70dd39453"
W0315 04:00:09.609535 1 fs.go:161] Could not get Docker devicemapper device: exit status 1
I0315 04:00:09.609597 1 fs.go:109] Filesystem partitions: map[/dev/mapper/docker-202:1-263199-b0b050984cbf5631e7fae9d5522c5635a9d1bed34e41a25621fb6ac70dd39453:{mountpoint:/ major:253 minor:4 fsType: blockSize:0} /dev/xvda1:{mountpoint:/rootfs major:202 minor:1 fsType: blockSize:0} /dev/mapper/docker-202:1-263199-001a0590b8964d1212f40a42bc01f00a29f9c96f3993c65173a0d8098cd5db1a:{mountpoint:/rootfs/var/lib/docker/devicemapper/mnt/001a0590b8964d1212f40a42bc01f00a29f9c96f3993c65173a0d8098cd5db1a major:253 minor:3 fsType: blockSize:0}]
I0315 04:00:09.620413 1 machine.go:50] Couldn't collect info from any of the files in "/rootfs/etc/machine-id,/var/lib/dbus/machine-id"
I0315 04:00:09.620462 1 manager.go:205] Machine: {NumCores:2 CpuFrequency:2494044 MemoryCapacity:4147183616 MachineID: SystemUUID:EC22FA34-7E03-F450-C138-48396FFF0C9E BootID:692e2f1f-10da-463e-93ed-2eb34219370e Filesystems:[{Device:/dev/mapper/docker-202:1-263199-b0b050984cbf5631e7fae9d5522c5635a9d1bed34e41a25621fb6ac70dd39453 Capacity:107319656448 Type:vfs Inodes:104855552} {Device:/dev/xvda1 Capacity:8318783488 Type:vfs Inodes:524288} {Device:/dev/mapper/docker-202:1-263199-001a0590b8964d1212f40a42bc01f00a29f9c96f3993c65173a0d8098cd5db1a Capacity:107319656448 Type:vfs Inodes:104855552}] DiskMap:map[253:0:{Name:dm-0 Major:253 Minor:0 Size:25165824 Scheduler:none} 253:2:{Name:dm-2 Major:253 Minor:2 Size:78156660736 Scheduler:none} 253:3:{Name:dm-3 Major:253 Minor:3 Size:107374182400 Scheduler:none} 253:4:{Name:dm-4 Major:253 Minor:4 Size:107374182400 Scheduler:none} 202:0:{Name:xvda Major:202 Minor:0 Size:8589934592 Scheduler:noop} 253:1:{Name:dm-1 Major:253 Minor:1 Size:78156660736 Scheduler:none} 253:5:{Name:dm-5 Major:253 Minor:5 Size:107374182400 Scheduler:none} 202:26368:{Name:xvdcz Major:202 Minor:26368 Size:23622320128 Scheduler:noop} 202:6144:{Name:xvdy Major:202 Minor:6144 Size:68719476736 Scheduler:noop}] NetworkDevices:[{Name:eth0 MacAddress:02:42:ac:11:00:03 Speed:10000 Mtu:9001}] Topology:[{Id:0 Memory:4147183616 Cores:[{Id:0 Threads:[0] Caches:[{Size:32768 Type:Data Level:1} {Size:32768 Type:Instruction Level:1} {Size:262144 Type:Unified Level:2}]} {Id:1 Threads:[1] Caches:[{Size:32768 Type:Data Level:1} {Size:32768 Type:Instruction Level:1} {Size:262144 Type:Unified Level:2}]}] Caches:[{Size:26214400 Type:Unified Level:3}]}] CloudProvider:AWS InstanceType:t2.medium InstanceID:i-762d06ac}
I0315 04:00:09.622049 1 manager.go:211] Version: {KernelVersion:4.1.17-22.30.amzn1.x86_64 ContainerOsVersion:Alpine Linux v3.2 DockerVersion:1.9.1 CadvisorVersion:0.22.0 CadvisorRevision:e39fb02}
I0315 04:00:09.765357 1 factory.go:233] Registering Docker factory
I0315 04:00:09.768693 1 factory.go:97] Registering Raw factory
I0315 04:00:10.217739 1 manager.go:1039] Started watching for new ooms in manager
W0315 04:00:10.218809 1 manager.go:279] Could not configure a source for OOM detection, disabling OOM events: exec: "journalctl": executable file not found in $PATH
I0315 04:00:10.219235 1 manager.go:292] Starting recovery of all containers
I0315 04:00:10.254453 1 manager.go:297] Recovery completed
I0315 04:00:10.261723 1 cadvisor.go:106] Starting cAdvisor version: 0.22.0-e39fb02 on port 8080
I0315 04:00:18.346892 1 manager.go:1029] Exiting thread watching subcontainers
I0315 04:00:18.346963 1 manager.go:362] Exiting global housekeeping thread
I0315 04:00:18.346982 1 cadvisor.go:140] Exiting given signal: terminated

could someone please suggest what is happening here?

**Comment by samuelkarp** [comment]
The logs don't seem to indicate that the ECS Agent is actually killing the task.  If you look at the timestamps in the logs you provided, you'll see that cAdvisor is exiting at `04:00:18` and that the ECS Agent detects the exit at `04:00:22`.  Given the lack of ECS Agent logs between `04:00:11` and `04:00:22`, it doesn't look like the ECS Agent is actually performing any action during that time.

**Comment by samuelkarp** [comment]
@hridyeshpant Were you able to check on this?

**Comment by samuelkarp** [comment]
@hridyeshpant I'm going to close this issue for now since we haven't heard back from you.  Please feel free to re-open the issue when you're able to look at my suggestions.

**Comment by hridyeshpant** [comment]
@samuelkarp sure . i finally moved these ecs task part of cron job script in each ECS instance.
