### ISSUE TITLE
ECS Agent loses its mind when ELB deregisters instance

### ISSUE THREAD

**Issue by pedros007** [aws/amazon-ecs-agent#342]
I have a service behind an ELB running in ECS.  It seems the ECS Agent gets in a funny state when an ELB health check fails.  I've seen this happen a couple of times recently and here's what seems to happen:

* ELB health check fails.  
* ECS console reports my service has  `Desired tasks: 1`, `Running tasks: 0`.  The console shows one task for this service has a `Last status: PENDING`, `Desired status: RUNNING`.
* The ECS Instance in the console shows `Agent Connected: true`. 
* When I ssh to my ECS instance, `docker ps` shows the container in question is still running:

        59ba53b5fdf5        pedros007/matsel         "rails server puma -b"    22 hours ago        Up 22 hours         0.0.0.0:3000->3000/tcp        ecs-MaterialSelectorUi-staging-web-1-web-90e9b0f08eeb92a97e00
I'm confused why the container is still running, but ECS thinks it is not. 

* Events for my service look like:

| Event id | Event Time | Message |
| ---------|------------|---------|
| 067cc5c7-eab6-4da9-9adc-3f4e783d934b | 2016-03-15 10:54:14 -0600 | service staging-material-selector-services-WebAppService-TV0JG9IU7BZT has started 1 tasks: task 47fd105b-1c9f-45cc-88c2-1b1e7f61e378. |
| d28efa30-6c67-40aa-a635-14ca16e116c2 | 2016-03-15 10:54:14 -0600 | service staging-material-selector-services-WebAppService-TV0JG9IU7BZT deregistered 1 instances in elb staging-webapp-elb |
| f0d3f678-a5a5-46ee-bf68-549759336672 | 2016-03-15 10:54:04 -0600 | service staging-material-selector-services-WebAppService-TV0JG9IU7BZT stopped 1 running tasks. |
| 81087ad3-a87a-4c44-9696-688460c3091b | 2016-03-15 10:54:04 -0600 | service staging-material-selector-services-WebAppService-TV0JG9IU7BZT deregistered 1 instances in elb staging-webapp-elb |
| 14899884-35d9-4c68-93b5-dc44135298e3 | 2016-03-15 10:54:04 -0600 | service staging-material-selector-services-WebAppService-TV0JG9IU7BZT registered 1 instances in elb staging-webapp-elb |
| bd49ca1f-7b45-4af9-b16c-ce3c5ac88e85 | 2016-03-15 10:54:04 -0600 | service staging-material-selector-services-WebAppService-TV0JG9IU7BZT (instance i-d9e4911e) is unhealthy in elb staging-webapp-elb due to (reason Instance has failedat least the UnhealthyThreshold number of health checks consecutively.) |

* `docker logs` for the ECS Agent reports:

        2016-03-15T16:48:37Z [WARN] Error getting cpu stats module="stats" err="No data in the queue" container="&{DockerID:6bd5e610e888ba58d4a3fcb62be88a02b817d55369c033773c6a6d5a51b83a2b}"
        2016-03-15T16:48:37Z [WARN] Error getting cpu stats module="stats" err="No data in the queue" container="&{DockerID:59ba53b5fdf5a030b38347f8012efc1a2f6ef4510a1e727351f25e0fa9933b38}"
        2016-03-15T16:48:37Z [WARN] Error getting cpu stats module="stats" err="No data in the queue" container="&{DockerID:d2c4db248cb7cc6b32e8ec1fbae126999e0b18baccf942cf5ec2b8f1799a0eab}"
        2016-03-15T16:48:37Z [WARN] Error getting cpu stats module="stats" err="No data in the queue" container="&{DockerID:3f020402a143183f9c621a86e1a8f0151527566c5e3c2e02a96c98979cf6ce5c}"
        2016-03-15T16:48:37Z [WARN] Error getting cpu stats module="stats" err="No data in the queue" container="&{DockerID:b032e6050fccc6440903e523d805174e5eaa613e56bf4621d1172a058c2f1f12}"
        2016-03-15T16:48:37Z [WARN] Error getting instance metrics module="tcs client" err="No task metrics to report"
        2016-03-15T17:02:51Z [INFO] Creating poll dialer module="ws client" host="ecs-a-1.us-west-2.amazonaws.com"

I can get things running again by running `docker restart ecs_agent_container_id` on the ECS instance.  Why do I need to restart the agent to get things running again?

I am using the ECS-optimized AMI 2015.09.f with agent version 1.8.0 and docker version 1.9.1

	"AWSRegionToAMI": {
            "ap-northeast-1": { "AMIID": "ami-18d8de76" },
            "ap-southeast-1": { "AMIID": "ami-9f60aefc" },
            "ap-southeast-2": { "AMIID": "ami-75a38416" },
            "eu-west-1": { "AMIID": "ami-76e95b05" },
            "eu-central-1": { "AMIID": "ami-96b6adfa" },
            "us-east-1": { "AMIID": "ami-43043329" },
            "us-west-1": { "AMIID": "ami-a77b0ac7" },
            "us-west-2": { "AMIID": "ami-02a24162" }
	}

**Comment by samuelkarp** [comment]
> agent version 1.8.0

Can you try upgrading to [1.8.1](https://github.com/aws/amazon-ecs-agent/releases/tag/v1.8.1)?    There's a known deadlock condition in 1.8.0 that you might be hitting.

**Comment by pedros007** [comment]
Is that in [ECS Optimized AMI 2015.09.g](https://aws.amazon.com/marketplace/pp/B00U6QTYI2)?  Also, is there a table of all the AMI ID for 2015.09.g for every region?  It's always a bit of a hassle finding the right value for my CloudFormation template.

**Comment by samuelkarp** [comment]
Yes.  We maintain a table of the [latest AMI IDs](http://docs.aws.amazon.com/AmazonECS/latest/developerguide/ecs-optimized_AMI.html) and [versions](http://docs.aws.amazon.com/AmazonECS/latest/developerguide/container_agent_versions.html) in our documentation.

**Comment by pedros007** [comment]
Thanks.  I'll give it a try and re-open if the problem continues.
