### ISSUE TITLE
Environment variable file behavior doesn't match documentation

### ISSUE THREAD

**Issue by ltm** [aws/amazon-ecs-agent#3429]
### Summary

According to the documentation of [environment variable files](https://docs.aws.amazon.com/AmazonECS/latest/developerguide/taskdef-envfiles.html#taskdef-envfiles-considerations) ECS is using the same syntax as [Docker Compose](https://docs.docker.com/compose/env-file/). However, in practice ECS uses a simpler syntax.

### Description

The Docker Compose environment file syntax allows quoted values, inline comments, shell escape sequences, etc. and relies on a [fork](https://github.com/compose-spec/compose-go/tree/master/dotenv) of [godotenv](https://github.com/joho/godotenv) to [parse](https://github.com/compose-spec/compose-go/blob/517cf49833c044cb7670e4b2429871c19b1b28a8/cli/options.go#L208-L260) environment files.

The ECS agent simply [splits lines](https://github.com/aws/amazon-ecs-agent/blob/67240c17711c0d0a5c7b1d37882dc565880bff38/agent/taskresource/envFiles/envfile.go#L552-L588) in the environment file into key-value pairs.

### Expected Behavior
An environment file containing `VAR="some\nvalue"` should set the environment variable `VAR` to:
```
some
value
```

### Observed Behavior
An environment file containing `VAR="some\nvalue"` sets the environment variable `VAR` to:
```
"some\nvalue"
```

**Comment by rushim1** [comment]
Shall I replace the split logic with compose fork and raise a pr? @ubhattacharjya

**Comment by Realmonia** [comment]
Please feel free to do so if you have bandwidth. We will help with the PR. @rushim1

**Comment by Realmonia** [comment]
Hi, after discussing @rushim1 's PR with team, following docker compose's spec conflicts with some of the current AWS documentation, and the behavior you mentioned does match the AWS doc. Considering it is a potential breaking change, we choose to not do it as of now. If you see an important use case, please raise this in https://github.com/aws/containers-roadmap to get help from our product team. Thanks!

**Comment by ltm** [comment]
@Realmonia The documentation I linked to in the description still claims that ECS uses the Docker Compose syntax (via the link in the following paragraph):

> Each line in an environment file must contain an environment variable in VARIABLE=VALUE format. Spaces or quotation marks are included as part of the values. Lines beginning with # are treated as comments and are ignored. **For more information about the environment variable file syntax, see [Declare default environment variables in file](https://docs.docker.com/compose/env-file/).**

One important use case is allowing PEM certificates to be injected via environment variables, e.g.

```
CERTIFICATE="-----BEGIN CERTIFICATE-----\nMII...\n-----END CERTIFICATE-----\n"
```

I've opened aws/containers-roadmap#2073 as requested.
