### ISSUE TITLE
Running ECS with userns-remap

### ISSUE THREAD

**Issue by phod** [aws/amazon-ecs-agent#343]
Hello,

I am attempting to run Docker 1.10 on ECS. The Docker image is using, as one of its options, "--userns-remap=default". When ECS tries to run the image, I get the following error: 

`Code: System error
Message: stat /var/run/docker/execdriver/native: permission denied`

I suspect the userns-remap may be causing issues, as the ECS container can no longer run as root without upsetting docker.

Are there any plans to support this in the future? Is there a workaround that anyone knows of?

Cheers.

**Comment by samuelkarp** [comment]
@phod I haven't tested the daemon option `--userns-remap=default` yet.  Are you having trouble running the ECS Agent itself, or trouble running containers with ECS?

**Comment by phod** [comment]
The issue is with running the ECS agent itself. Starting the ECS docker image failed before we could start any other Docker containers.

**Comment by samuelkarp** [comment]
Can you include the complete log line?

The ECS Agent does need to be able to read `/var/lib/docker/execdriver/native` on the host in order for the CloudWatch metrics feature to work.

**Comment by phod** [comment]
Sorry for the delay.

The logs from the ECS Agent are:
```
Timestamp: 2016-03-15 04:28:35.989840538 +0000 UTC
Code: System error
Message: stat /var/run/docker/execdriver/native: permission denied
Frames:
---
0: setupRootfs
Package: github.com/opencontainers/runc/libcontainer
File: rootfs_linux.go@40
---
1: Init
Package: github.com/opencontainers/runc/libcontainer.(*linuxStandardInit)
File: standard_init_linux.go@57
---
2: StartInitialization
Package: github.com/opencontainers/runc/libcontainer.(*LinuxFactory)
File: factory_linux.go@240
---
3: initializer
Package: github.com/docker/docker/daemon/execdriver/native
File: init.go@35
---
4: Init
Package: github.com/docker/docker/pkg/reexec
File: reexec.go@26
---
5: main
Package: main
File: docker.go@18
---
6: main
Package: runtime
File: proc.go@111
---
7: goexit
Package: runtime
File: asm_amd64.s@1721
```

**Comment by samuelkarp** [comment]
@phod Those logs look like they're actually coming from `runc` (used by Docker).  My guess of what's going on here is that using `--userns-remap=default` is remapping the `root` user inside the agent container to be a different user on the host, which no longer has access to the host resources needed by the agent (`/var/run/docker.sock` and `/var/run/docker/execdriver/native`, among others).  Phil Estes, who wrote much of the userns implementation, has a [blog post](https://integratedcode.us/2016/04/08/user-namespaces-sharing-the-docker-unix-socket/) covering some options for sharing the Docker socket to a container process, however this does not help with accessing `/var/run/docker/execdriver/native`.  If you're willing to do without the CloudWatch metrics feature, you can remove the mount to `/var/run/docker/execdriver/native`, set `ECS_DISABLE_METRICS` to `true`, and try following Phil's instructions for a `socat` proxy.

**Comment by samuelkarp** [comment]
@phod We've recently changed the mechanism we use to collect metrics for CloudWatch, so mounting `/var/run/docker/execdriver/native` is no longer necessary.  However, the agent does still need access to `/var/run/docker.sock` in order to interact with the Docker daemon.  Did you have any success following the instructions from the blog post I linked?

**Comment by samuelkarp** [comment]
@phod We haven't heard back from you in a while, so I'm going to close this issue for now.  Please feel free to reopen it if you get a chance to try my suggestions.
