### ISSUE TITLE
[Windows] Volume mounts on windows host are configuring the destination path for windows containers only

### ISSUE THREAD

**Issue by wvidana** [aws/amazon-ecs-agent#3454]
### Summary

Volume mounts on windows host are configuring the destination path for windows containers only, even when running docker on linux mode (for linux containers).

### Description

In my task definition, the destination path is set like `/data` with a forward slash (linux), but on the container it looks like `\\data`. My asumption is that the ECS agent assumes that since it is running in a Windows host, the resulted paths need to be converted to windows path for windows containers, but when running a linux container that path is not set correctly.

The `ContainerDefinitions.MountPoints` section from the task definition looks like this:
```yaml
MountPoints:
 - ContainerPath: "/data"
   SourceVolume: data
   ReadOnly: false
```

The container, which runs from a linux image, while on linux mode, but on a Windows host, has the `Mounts` section looking like this (extracted from `docker container inspect`):
```json
"Mounts": [
  {
    "Type": "volume",
    "Name": "data",
    "Source": "/var/lib/docker/volumes/data/_data",
    "Destination": "\\data",
    "Driver": "local",
    "Mode": "z",
    "RW": true,
    "Propagation": ""
  }
]
```

### Expected Behavior
The volume should be mounted on `/data` in the running container, but instead it is mounted as `'\data'`.

### Observed Behavior
My containers are failing because their workdirectory is set to `/data`, and they are expecting some files to be there, from the volume mount, but they are not there since those are mounted on a different folder, `'\data'`.

If I run manually the same container with `docker run --volume data:/data -it 1q2w3e4r bash`, the volume gets mounted correctly to `/data`. The problems seems to be with the ECS agent running the container.

### Environment Details

* `df -h` in a running container placed as an ECS task:
  * since the `WORKDIR` in the Dockerfile is set to `/data` the session starts at that folder, but it is blank since the volume mount was done on `\data` by the ECS agent.
```
root@9196399d919c:/data# df -h
Filesystem      Size  Used Avail Use% Mounted on
overlay          59G  1.4G   55G   3% /
tmpfs            64M     0   64M   0% /dev
tmpfs           991M     0  991M   0% /sys/fs/cgroup
/dev/sda1        59G  1.4G   55G   3% /\data
shm              64M     0   64M   0% /dev/shm
tmpfs           991M     0  991M   0% /proc/acpi
tmpfs           991M     0  991M   0% /sys/firmware
```

### Supporting Log Snippets

Non relevant.

**Comment by wvidana** [comment]
It looks like the problem is that since the agent is compiled in Windows, the resulting binary uses `\` as the `Separator`, which replaces any occurrences with slash `/` when invoking `filepath.Clean` https://pkg.go.dev/path/filepath#Clean

This method is invoked with the `utils.GetCanonicalPath` function
https://github.com/aws/amazon-ecs-agent/blob/33276765a881d717aaf802af0831e2c3e37c99d0/agent/utils/utils_windows.go#L27-L40

And the `utils.GetCanonicalPath` function is invoked on `api/task`
https://github.com/aws/amazon-ecs-agent/blob/33276765a881d717aaf802af0831e2c3e37c99d0/agent/api/task/task_windows.go#L63-L89

The `task_windows.go` script is enforcing all paths, container included, to be converted to Windows format, even if the container is a linux task. It does take, on line 86, the original `mountPoint.ContainerPath` from the task and convert them.

### Workaround
I've manually altered line 86 to just use the original path, mirroring what `utils_linux.go` for `GetCanonicalPath` and it actually worked!

```go
container.MountPoints[i].ContainerPath = mountPoint.ContainerPath
```
After editing that line, I've build the agent with `scripts/build_agent.ps1` and replace the binary in `C:/ProgramFiles/Amazon/ECS`. For that i've previously stopped the agent and removed the configs with `Remove-Item -Recurse -Force $env:ProgramData\Amazon\ECS\data\*`

**Comment by jterry75** [comment]
I'm confused what you are trying to do here. ECS does not formally support Linux containers on Windows. Is that what you are trying to do here?

**Comment by wvidana** [comment]
Yes @jterry75 , I was trying to run Linux tasks on a Windows host, but the docs were not very clear on if it was possible or not, I now realize it is not

**Comment by jterry75** [comment]
Sorry missed this. Np thanks for clarifying
