### ISSUE TITLE
`nvidia-driver-version` ECS attribute should be a key/value attribute

### ISSUE THREAD

**Issue by risdenk** [aws/amazon-ecs-agent#3492]
### Summary
The `nvidia-driver-version` ECS attribute is added as a name only attribute, which doesn't allow advanced filtering with https://docs.aws.amazon.com/AmazonECS/latest/developerguide/cluster-query-language.html The filtering only happens on the attribute value and since the driver version is in the attribute name it is very limiting.

### Description
The `nvidia-driver-version` ECS attribute is added as a name only attribute, which doesn't allow advanced filtering with https://docs.aws.amazon.com/AmazonECS/latest/developerguide/cluster-query-language.html The filtering only happens on the attribute value and since the driver version is in the attribute name it is very limiting.

Example attribute value from ECS agent:
`attribute:ecs.capability.nvidia-driver-version.470.57.02`

This is implemented here: https://github.com/aws/amazon-ecs-agent/blame/master/agent/app/agent_capability_unix.go#L106

This doesn't match other ECS attributes like CNI version which puts the version in the key/value attribute instead of name only. reference: https://github.com/aws/amazon-ecs-agent/blame/master/agent/app/agent_capability_unix.go#L130

This name only attribute behavior exists from the first PR this was introduced in here: https://github.com/aws/amazon-ecs-agent/pull/1676

### Expected Behavior
`attribute:ecs.capability.nvidia-driver-version` = `470.57.02`

### Observed Behavior
`attribute:ecs.capability.nvidia-driver-version.470.57.02`

**Comment by Realmonia** [comment]
Hi @risdenk ,

Thanks for report! I added this to our backlog. I will post an update here when status is updated.

**Comment by SreeeS** [comment]
Hello @risdenk  can you please update the name from `nvidia-driver-version` to `gpu-driver-version` based on the PR https://github.com/aws/amazon-ecs-agent/pull/3493#discussion_r1123732603

**Comment by risdenk** [comment]
no. AWS can make that change.

**Comment by risdenk** [comment]
https://github.com/aws/amazon-ecs-agent/pull/3493#issuecomment-1515361531

**Comment by SreeeS** [comment]
Made this change in a new PR.
https://github.com/aws/amazon-ecs-agent/pull/3836
