### ISSUE TITLE
Ability to set custom session name for task role

### ISSUE THREAD

**Issue by ddeniro24** [aws/amazon-ecs-agent#3498]
### Summary
_This request was submitted on behalf of a customer_
Cx wants to set a session name for the assumed task role in order to better track user actions on containers via CloudTrail.

### Which service(s) is this request for?
ECS

### Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?
The ability to set a session name for the assumed task role in order to better track user actions on containers via CloudTrail. Currently, tasks assume the task role and the session ID is the task ID. This makes it difficult to track CloudTrail Api calls on a user basis.

### Are you currently working around this issue?
Yes. Created a trust policy that explicitly allows the role to assume itself. User will then access the container and assume the task role specifying the RoleSessionName (manual/doesn't scale well). 

### Additional context
N/A

### Attachments
N/A

**Comment by Realmonia** [comment]
Hi @ddeniro24 , this seems to be a feature request. Can you raise this in https://github.com/aws/containers-roadmap/issues? Thanks.
