### ISSUE TITLE
ecs-agent deletes ecs-service-connect-agent:interface-v1 when ECS_ENABLE_UNTRACKED_IMAGE_CLEANUP=true

### ISSUE THREAD

**Issue by andrewradamis-paay** [aws/amazon-ecs-agent#3520]
### Summary

If `ECS_ENABLED_UNTRACKED_IMAGE_CLEANUP` is set to `true`, the ecs-agent will remove the `ecs-service-connect-agent:interface-v1` image and tasks enabled for Service Connect will fail to start.

### Description

If `ECS_ENABLED_UNTRACKED_IMAGE_CLEANUP` is set to `true`, the ecs-agent will remove the `ecs-service-connect-agent:interface-v1` image and tasks enabled for Service Connect will fail to start.
Adding `ECS_EXCLUDE_UNTRACKED_IMAGE=ecs-service-connect-agent:interface-v1` to `ecs.config` is a work-around for the issue.
I'm not familar with the ecs-agent codebase, but I'm guessing it just needs to be added to https://github.com/aws/amazon-ecs-agent/blob/41e8e6a78391f65b17070ffe086876e63387d5bb/agent/engine/docker_image_manager.go#L102-L106.

### Expected Behavior
Don't delete `ecs-service-connect-agent:interface-v1`

### Observed Behavior
ecs-agent deleted `ecs-service-connect-agent:interface-v1` then failed to start a Service Connect Task with error `CannotCreateContainerError: Error response from daemon: No such image: ecs-service-connect-agent:interface-v1`.

### Environment Details
Using `ami-028cbf4835af1ad6f (amzn2-ami-ecs-hvm-2.0.20221207-x86_64-ebs)`

**Comment by ubhattacharjya** [comment]
Hi @andrewradamis-paay,

Thank you for reporting the issue. We will provide an update on this soon.

Utsa

**Comment by mythri-garaga** [comment]
Fixed in [1.68.0](https://github.com/aws/amazon-ecs-agent/pull/3528) release.
