### ISSUE TITLE
User regexp is not sufficient (does not include valid username characters)

### ISSUE THREAD

**Issue by curtisz** [aws/amazon-ecs-agent#353]
This works:
```sh
docker run -it --name="foo" --user="www-data" ubuntu /bin/bash
```

This does not work:
```js
{
  "containerDefinitions": [
    {
      "name": "sleep",
      "image": "ubuntu",
      "cpu": 10,
      "workingDirectory":"/etc/console-setup",
      "user": "www-data",
      "command": [
        "/bin/sleep",
        "360"
      ],
      "memory": 10,
      "essential": true
    }
  ],
  "family": "sleep 360"
}
```

(Output):
```sh
A client error (ClientException) occurred when calling the RegisterTaskDefinition operation: user contains invalid characters, does not match pattern ^([a-z_][a-z0-9_]{0,30})$
```

Possible solution in regular expression (usernames can contain one or more hyphens but cannot start with a hyphen):
```sh
^([a-z_][-a-z0-9_]{0,30})$
```

Unfortunately, judging by [the other, eerily similar issue](https://github.com/aws/amazon-ecs-agent/issues/254), this won't be fixed until long after the sound of cracking whips behind me has reached a crescendo. I will have to implement an ugly kludge to make this work for me today. My only hope is that someday my sacrifice will benefit those that come after me.

**Comment by aaithal** [comment]
@curtisz thanks for reporting this. We have followed this up internally and it should be fixed now. I was able to register a task definition using the container definition that you provided. I'm closing this issue for now. Feel free to reopen this if you experience this issue again.
