### ISSUE TITLE
Clear guidance on suitable Docker versions per ECS Agent version

### ISSUE THREAD

**Issue by ianneub** [aws/amazon-ecs-agent#359]
Hello,

Maybe I am missing this, but it seems like it would be great to have documented somewhere (preferably right in README) a table depicting the recommended/tested versions of Docker per ECS Agent version.

For example, currently I am running ECS Agent 1.7.1, using Docker 1.9.1. I'd like to update to ECS Agent 1.8.1, but I have no idea if I should or need to also upgrade Docker to a more recent version.

Thanks!

**Comment by ianneub** [comment]
I found the information here:
http://docs.aws.amazon.com/AmazonECS/latest/developerguide/container_agent_versions.html

Maybe we could put a link to this doc in the README?

**Comment by samuelkarp** [comment]
Hi @ianneub,

ECS should work with any Docker version >= 1.5.0.  The table you've found represents the versions and configurations that we've found to work well.  We do already have a link to [this page](http://docs.aws.amazon.com/AmazonECS/latest/developerguide/ECS_agent.html) in the README (in the Usage section), which has detailed information about running the ECS agent.  I'd be interested to know if you have suggestions on making this more clear.

Sam

**Comment by ianneub** [comment]
Thanks @samuelkarp . The existing link to the docs is fine. Not sure why I didn't notice it before.
