### ISSUE TITLE
ECS Anywhere install fails from EC2 instance with an IAM role.

### ISSUE THREAD

**Issue by maishsk** [aws/amazon-ecs-agent#3604]
### Description

I am registering an EC2 instance as and External Instance into my ECS cluster (to simulate an on-prem instance)
Deployed Amazon Linux 2 (t3.small) in a region.
I generate the registration commands to register an external instance to cluster. My ecsAnywhereInstanceRole role is set up according to the documentation. I SSH into the instance and run the commands that I copied from the console

`ecs-agent` and `ecs-init` install correctly, but instance will not register to the cluster.
The IAM role attached to the instance is the managed AdminstratorAccess Policy.

### Expected Behavior
I would expect the installation to succeed, because the role that is running the command, should have full permissions on the account and the `activation-id` and `activation-code` are being supplied through the install script.

### Observed Behavior
The installation fails with an error in the log
`The identity document and identity document signature were not valid`

from `/var/log/ecs/ecs-agent.log`
```
level=info time=2023-03-06T12:47:21Z msg="Successfully got ECS instance credentials from provider: EC2RoleProvider" module=instancecreds_linux.go
level=info time=2023-03-06T12:47:21Z msg="Starting Amazon ECS Agent" version="1.69.0" commit="b32ab075"
level=info time=2023-03-06T12:47:21Z msg="Loading configuration"
level=error time=2023-03-06T12:47:21Z msg="CREDENTIALS_FETCHER_HOST_DIR not found, err: stat /var/credentials-fetcher/socket/credentials_fetcher.sock: no such file or directory" module=parse_linux.go
level=warn time=2023-03-06T12:47:21Z msg="Unable to fetch user data: blackholed" module=config.go
level=error time=2023-03-06T12:47:21Z msg="CREDENTIALS_FETCHER_HOST_DIR not found, err: stat /var/credentials-fetcher/socket/credentials_fetcher.sock: no such file or directory" module=parse_linux.go
level=info time=2023-03-06T12:47:21Z msg="ECS Agent is running in external mode."
level=info time=2023-03-06T12:47:21Z msg="Successfully got ECS instance credentials from provider: EC2RoleProvider" module=instancecreds_linux.go
level=info time=2023-03-06T12:47:21Z msg="Successfully got ECS instance credentials from provider: EC2RoleProvider" module=instancecreds_linux.go
level=info time=2023-03-06T12:47:21Z msg="Image excluded from cleanup" image="amazon/amazon-ecs-pause:0.1.0"
level=info time=2023-03-06T12:47:21Z msg="Image excluded from cleanup" image="amazon/amazon-ecs-pause:0.1.0"
level=info time=2023-03-06T12:47:21Z msg="Image excluded from cleanup" image="amazon/amazon-ecs-agent:latest"
level=info time=2023-03-06T12:47:21Z msg="Loading state!" module=state_manager.go
level=info time=2023-03-06T12:47:21Z msg="Event stream ContainerChange start listening..." module=eventstream.go
level=warn time=2023-03-06T12:47:21Z msg="Not able to get EC2 Instance ID from IMDS, using EC2 Instance ID from saved state: ''" module=agent.go
level=warn time=2023-03-06T12:47:22Z msg="AppNet agent container tarball unavailable: /managed-agents/serviceconnect/ecs-service-connect-agent.interface-v1.tar" error="stat /managed-agents/serviceconnect/ecs-service-connect-agent.interface-v1.tar: no such file or directory"
level=warn time=2023-03-06T12:47:22Z msg="ServiceConnect Capability: No service connect capabilities were found for Appnet version:" image=""
level=info time=2023-03-06T12:47:22Z msg="Registering Instance with ECS"
level=info time=2023-03-06T12:47:22Z msg="Fetching Instance ID Document has been disabled" module=client.go
level=info time=2023-03-06T12:47:22Z msg="Remaining mem: 1971" module=client.go
level=error time=2023-03-06T12:47:22Z msg="Unable to register as a container instance with ECS: InvalidParameterException: The identity document and identity document signature were not valid." module=client.go
level=error time=2023-03-06T12:47:22Z msg="Error registering container instance" error="InvalidParameterException: The identity document and identity document signature were not valid."
level=critical time=2023-03-06T12:47:22Z msg="Instance registration attempt with an invalid parameter" error="InvalidParameterException: The identity document and identity document signature were not valid."
```

It seems that even though I am providing the correct `activation-id` and `activation-code` they are being ignored and the registration of the instance into the ECS cluster is failing. 

### Environment Details
Amazon Linux 2 EC2 instance.

**Comment by chienhanlin** [comment]
Hello @maishsk, thanks for opening this issue. 
To let ECS Agent successfully register the external instance, the instance should not have a per-configured instance credential chain. This consideration is also shared with customers in the public doc [here](https://docs.aws.amazon.com/AmazonECS/latest/developerguide/ecs-anywhere.html#ecs-anywhere-considerations). 

Did we use the `ecsAnywhereInstanceRole` or any other IAM role to launch the EC2 instance? If yes, please try launching a new EC2 instance without any IAM instance profile, and run the installation script again. Thanks.

**Comment by SreeeS** [comment]
Hello @maishsk , following up on this. Did you try launching a new EC2 instance without any IAM instance profile, and run the installation script again as mentioned above?

**Comment by maishsk** [comment]
Without an IAM profile this works fine

**Comment by YashdalfTheGray** [comment]
Closing since we've resolved the concern.
