### ISSUE TITLE
Task Metadata V4 can return Cluster Name OR Cluster ARN: can I predict which I will get?

### ISSUE THREAD

**Issue by PettitWesley** [aws/amazon-ecs-agent#3649]
Docs: https://docs.aws.amazon.com/AmazonECS/latest/developerguide/task-metadata-endpoint-v4.html

> Cluster
The Amazon Resource Name (ARN) or short name of the Amazon ECS cluster to which the task belongs.

Why is it OR? How do I know which one will be returned in my task? 

Is there a way I can predict it? Or do I need to write code that always checks if the response is name or ARN?

Thanks for the help!

**Comment by SreeeS** [comment]
Hi @PettitWesley 
We used to accept both `clusterArn` and `cluster` in the `/var/ecs/ecs.config` and would read whichever value was provided and echo that in the response. Accepting `clusterArn` is deprecated so we just use the `short name of ECS cluster` now. I'm working on getting the docs updated.
Thank you!
