### ISSUE TITLE
Sometimes the device mapper is stuck in an infinite “mount/remount” loop

### ISSUE THREAD

**Issue by michipili** [aws/amazon-ecs-agent#367]
We have about 50 systems running the ecs-agent to deploy software with docker. Unfortunately they work quite unreliably, and it is not rare to see some of these systems stuck in an infinite mount/remount loop. We opened up a ticket at docker itself but as we never observed this phenomenon on systems using docker where the releases are performed by in-house software, we cannot rule out the possibility that the ecs-agent has some responsibility in the phenomenon.

You will find the details here here: https://github.com/docker/docker/issues/20401 and especially in this comment https://github.com/docker/docker/issues/20401#issuecomment-207364546

Please get in touch with me if you need any additional information on these systems.

**Comment by samuelkarp** [comment]
@michipili Can you tell us a bit more about your environment?  Are you running the ECS-optimized AMI?  If so, which version?  Have you changed any options on the Docker daemon?

From a quick read-through, it sounds like you might be running into https://github.com/docker/docker/issues/20707.  We've just released a new version of the ECS-optimized AMI (2016.03.a) that switches away from XFS for this reason.

**Comment by michipili** [comment]
We are running the the ECS-optimized AMI `amzn-ami-2015.09.g-amazon-ecs-optimized` (ami-33b48a59). Docker configuration is essentially untouched (but debug flag on some instances).

While some symptoms are indeed similar (docker commands, incl. docker ps, hanging forever or for an absurdly long time) and the problem seems also caused by a dysfunction in the XFS subsystem, however the detailed logs are distinct and our disks are not full at all:

```
df -h
Filesystem      Size  Used Avail Use% Mounted on
/dev/xvda1       30G  4.0G   26G  14% /
…
```

I will update our systems to the new ECS-optimized AMI.

**Comment by samuelkarp** [comment]
@michipili Please let us know if you continue to run into problems with the new AMI.

As an aside, `df -h` won't show you the size taken by the second volume at `/dev/xvdcz` since it's not mounted.  Instead, you'll need to use some LVM commands to see the actual space allocation.  This is documented in our [developer guide](http://docs.aws.amazon.com/AmazonECS/latest/developerguide/ecs-optimized_AMI.html).

**Comment by michipili** [comment]
@samuelkarp Thanks for pointing that. We did a few deployments already and they went fine, which a good sign since the failure rate was high enough to regularly pop-off every 2 deployments. Let us give a grace time of one week to this ticket, if nothing shows up it we can probably close it.

**Comment by samuelkarp** [comment]
@michipili Has the new AMI been working well?

**Comment by michipili** [comment]
We did not test thoroughly by now, but this will happen at the beginning of the week. :)

**Comment by tecnobrat** [comment]
@samuelkarp are you sure you switched away from xfs?

I see this still on the new AMI

`/usr/bin/docker daemon --storage-driver devicemapper --storage-opt dm.fs=xfs --storage-opt dm.thinpooldev=/dev/mapper/docker-docker--pool --storage-opt dm.use_deferred_removal=true --storage-opt dm.use_deferred_deletion=true`

Note: `--storage-opt dm.fs=xfs`

**Comment by samuelkarp** [comment]
@tecnobrat Are you using 2016.03.a?  You should see the following:

```
$ cat /etc/sysconfig/docker-storage-setup
# Edit this file to override any configuration options specified in
# /usr/lib/docker-storage-setup/docker-storage-setup.
#
# For more details refer to "man docker-storage-setup"
DEVS=/dev/xvdcz
VG=docker
DATA_SIZE=99%FREE
AUTO_EXTEND_POOL=yes
LV_ERROR_WHEN_FULL=yes
EXTRA_DOCKER_STORAGE_OPTIONS="--storage-opt dm.fs=ext4"
$ docker info
Containers: 12
Images: 10
Server Version: 1.9.1
Storage Driver: devicemapper
 Pool Name: docker-docker--pool
 Pool Blocksize: 524.3 kB
 Base Device Size: 107.4 GB
 Backing Filesystem: ext4
 Data file: 
 Metadata file: 
 Data Space Used: 1.94 GB
 Data Space Total: 23.35 GB
 Data Space Available: 21.41 GB
 Metadata Space Used: 868.4 kB
 Metadata Space Total: 25.17 MB
 Metadata Space Available: 24.3 MB
 Udev Sync Supported: true
 Deferred Removal Enabled: true
 Deferred Deletion Enabled: true
 Deferred Deleted Device Count: 0
 Library Version: 1.02.93-RHEL7 (2015-01-28)
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 4.4.5-15.26.amzn1.x86_64
Operating System: Amazon Linux AMI 2016.03
CPUs: 1
Total Memory: 995.5 MiB
Name: ip-172-31-42-26
ID: BFLE:G4B2:J3KA:2A2T:YRWU:U6UA:FOJY:UPAK:BOMS:WZIU:2FAD:BM3W
```

**Comment by tecnobrat** [comment]
We are running on beanstalk, stack: `64bit Amazon Linux 2016.03 v2.1.0 running Multi-container Docker 1.9.1 (Generic)`

From the EC2 console I see:

`AMI ID: aws-elasticbeanstalk-amzn-2016.03.0.x86_64-ecs-hvm-201603311132 (ami-a8bab1c2)`

```
[ec2-user@ip-172-17-51-18 ~]$ cat /etc/sysconfig/docker-storage-setup
# Edit this file to override any configuration options specified in
# /usr/lib/docker-storage-setup/docker-storage-setup.
#
# For more details refer to "man docker-storage-setup"
DEVS=/dev/xvdcz
VG=docker
```

```
[ec2-user@ip-172-17-51-18 ~]$ sudo docker info
Containers: 2
Images: 29
Server Version: 1.9.1
Storage Driver: devicemapper
 Pool Name: docker-docker--pool
 Pool Blocksize: 524.3 kB
 Base Device Size: 107.4 GB
 Backing Filesystem: xfs
 Data file:
 Metadata file:
 Data Space Used: 1.518 GB
 Data Space Total: 5.142 GB
 Data Space Available: 3.624 GB
 Metadata Space Used: 639 kB
 Metadata Space Total: 16.78 MB
 Metadata Space Available: 16.14 MB
 Udev Sync Supported: true
 Deferred Removal Enabled: true
 Deferred Deletion Enabled: true
 Deferred Deleted Device Count: 0
 Library Version: 1.02.93-RHEL7 (2015-01-28)
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 4.4.5-15.26.amzn1.x86_64
Operating System: Amazon Linux AMI 2016.03
CPUs: 1
Total Memory: 995.5 MiB
Name: ip-172-17-51-18
ID: 3ZWR:2M7P:QCQL:D2OD:4B4J:BW7Q:ZDSJ:2Z5A:QKBR:K6C2:OBVL:ZGE6
```

**Comment by tecnobrat** [comment]
I'm guessing this isn't using the new ECS AMI then?  Seems odd as its updated the same time, I just made an assumption ...

**Comment by samuelkarp** [comment]
@tecnobrat Yes, the Beanstalk AMIs are different from the ECS-optimized AMI.

**Comment by samuelkarp** [comment]
@michipili Has the new AMI been working well?

**Comment by tecnobrat** [comment]
@samuelkarp considering ElasticBeanstalk with Multi-Container Docker uses ECS, it runs into the same issues. Is there plans to update that as well then?  I'm surprised that in this case they are not kept in sync.

**Comment by samuelkarp** [comment]
@tecnobrat We're in regular contact with the Elastic Beanstalk team but I can't speak for them.  I'd recommend posting on the [Elastic Beanstalk forum](https://forums.aws.amazon.com/forum.jspa?forumID=86).

**Comment by aaithal** [comment]
@tecnobrat @michipili Closing this issue for now. Please let us know if you run into this again.

**Comment by michipili** [comment]
@aaithal Everything seems to work fine by now, thank you!

**Comment by kinghajj** [comment]
I believe we're experiencing this issue, both in the v2.1.1/1.9.1 and v2.1.3/1.11.1. An excerpt from /var/log/messages:

Jun 27 19:26:14 ip-172-31-8-253 kernel: [  212.627128] XFS (dm-4): Mounting V4 Filesystem
Jun 27 19:26:19 ip-172-31-8-253 kernel: [  217.118656] XFS (dm-4): Ending clean mount
Jun 27 19:26:19 ip-172-31-8-253 kernel: [  217.615173] XFS (dm-4): Unmounting Filesystem
Jun 27 19:26:22 ip-172-31-8-253 kernel: [  220.117755] XFS (dm-4): Mounting V4 Filesystem
Jun 27 19:26:26 ip-172-31-8-253 kernel: [  224.678900] XFS (dm-4): Ending clean mount
Jun 27 19:26:27 ip-172-31-8-253 kernel: [  225.194698] XFS (dm-4): Unmounting Filesystem
Jun 27 19:26:30 ip-172-31-8-253 kernel: [  228.202185] XFS (dm-4): Mounting V4 Filesystem
Jun 27 19:26:34 ip-172-31-8-253 kernel: [  232.773255] XFS (dm-4): Ending clean mount
Jun 27 19:29:00 ip-172-31-8-253 kernel: [  378.823892] XFS (dm-4): Unmounting Filesystem
Jun 27 19:29:02 ip-172-31-8-253 kernel: [  380.191755] XFS (dm-4): Mounting V4 Filesystem

**Comment by anosulchik** [comment]
https://github.com/docker/docker/issues/20401#issuecomment-231337800
