### ISSUE TITLE
Tasks are not retained long enough in the ECS history

### ISSUE THREAD

**Issue by ryanwalls** [aws/amazon-ecs-agent#368]
I don't know of a better place to put bugs like this, but "stopped tasks" in the amazon ECS UI does not show tasks that are more than just a few minutes old (don't know the exact time.) 

When I query the ecs api using `ListTasks`, it returns nothing as well.  

What is the retainment period for tasks?  For debugging purposes I feel at least 30 days would be reasonable.

**Comment by samuelkarp** [comment]
By default, [ListTasks](http://docs.aws.amazon.com/AmazonECS/latest/APIReference/API_ListTasks.html) will only show `RUNNING` tasks.  However, you can pass a `desiredStatus` of `STOPPED` to see stopped tasks.  `STOPPED` tasks are removed after some time (but are retained longer than just a few minutes).

Note that the best place to report issues or feature requests related to ECS as a whole and not just the agent are the [AWS Forums](https://forums.aws.amazon.com/forum.jspa?forumID=187) or [AWS Support](https://aws.amazon.com/premiumsupport/).

**Comment by ryanwalls** [comment]
@samuelkarp Even with specifying "stopped" we cannot see a task that is 15 hours old.  

So whatever the retainment period is, is too short for our purposes.

**Comment by ryanwalls** [comment]
@samuelkarp Think that retaining stopped tasks longer is something that could be put on the roadmap?

**Comment by samuelkarp** [comment]
@ryanwalls I can record this as a feature request.  If you have any additional details on your use case, that can certainly help us prioritize.

In the meantime, there are a few places you can get additional debugging information:
* The agent reports state to ECS by calling the `SubmitContainerStateChange` and `SubmitTaskStateChange` APIs, which are recorded in [AWS CloudTrail](https://aws.amazon.com/cloudtrail/).
* On the instance, the agent logs record information about why tasks stopped, including the exit code.  You may need to enable debug logging to get full details.
* By default, containers are preserved on the instance for 3 hours after they exit (either exiting on their own or being stopped by the agent).  This behavior can be tuned by adjusting the `ECS_ENGINE_TASK_CLEANUP_WAIT_DURATION` environment variable.

**Comment by ryanwalls** [comment]
We use ECS along with auto-scaling, so our servers are rarely around for very long, which means the agents aren't around long either.  So we lose a lot of data when the task history goes away.

We use `--log-driver=syslog` when running the agent container.  Will it send debug logs to stdout (and therefore to syslog)?

**Comment by samuelkarp** [comment]
If you set `ECS_LOGLEVEL=debug`, yes.

**Comment by juanrhenals** [comment]
@ryanwalls Let us know if there's anything else we can help you with on this issue, otherwise I'll go ahead and close this issue in a few days.

**Comment by ryanwalls** [comment]
@juanrhenals I still would like to have it as a feature request.  Would rather not close until it is implemented, but that's up to you guys.

**Comment by samuelkarp** [comment]
@ryanwalls Today we announced that ECS sends state changes to CloudWatch Events, which you can use to keep track of tasks that are interesting to you. For more information please see [the documentation](http://docs.aws.amazon.com/AmazonECS/latest/developerguide/cloudwatch_event_stream.html).

**Comment by fjromerom** [comment]
In case you come across this issue, we have implemented the following solution to store ECS stopped tasks in CloudWatch Logs.

https://github.com/aws-samples/amazon-ecs-stopped-tasks-cwlogs
