### ISSUE TITLE
"Managed task at steady state" is overly verbose

### ISSUE THREAD

**Issue by jaffee** [aws/amazon-ecs-agent#3704]
### Summary
Our logs are getting spammed with "Managed task at steady state" messages (at INFO level) which aren't useful.

### Description
Seems reasonable to remove this message. As far as I can tell, it's called in an infinite loop which is monitoring the task, so it would be expected to be pretty chatty. This gets expensive depending on how you store your logs.

**Comment by ubhattacharjya** [comment]
Hi @jaffee ,

https://github.com/aws/amazon-ecs-agent/pull/3713 has been merged. This will go out with the next agent release.

I am closing the issue. Please reopen if you have further issues.

Thanks,
Utsa

**Comment by jaffee** [comment]
thank you!
