### ISSUE TITLE
Support awslogs in logDriver field

### ISSUE THREAD

**Issue by jhefner** [aws/amazon-ecs-agent#372]
Since docker went through the trouble of natively supporting awslogs, it would be great if aws supported this option as well. Since the --log-driver is a free-form text field, it may even make sense to support any input there and rely on the user to provide a valid value.

**Comment by samuelkarp** [comment]
@jhefner Thanks for opening this issue!  We're aware of the awslogs driver (I wrote it) and are planning to support it (see https://github.com/aws/amazon-ecs-agent/pull/366).  We're tracking the feature request in https://github.com/aws/amazon-ecs-agent/issues/9, so I'm going to close this as a duplicate.

**Comment by jhefner** [comment]
Thanks! Sorry about that. I searched the issues for duplicates but forgot to search the pull requests.
