### ISSUE TITLE
README is lying about ECS_LOGFILE setting debug

### ISSUE THREAD

**Issue by pcarrier** [aws/amazon-ecs-agent#373]
> If set, logs at debug level (regardless of ECS_LOGLEVEL) will be written to that file.

```
ubuntu@ip-10-0-1-78:/var/log/ecs$ cut -d' ' -f2 *|sort|uniq -c|sort -nr
   8741 [INFO]
   1839 [WARN]
ubuntu@ip-10-0-1-78:/var/log/ecs$ grep LOG /etc/ecs.env
ECS_LOGFILE=/var/log/ecs/ecs-agent.log
```

**Comment by samuelkarp** [comment]
Good catch!  We'll get that fixed.

**Comment by samuelkarp** [comment]
The README is updated in our `dev` branch and will be updated in `master` as part of our next release.  Thanks for catching the documentation error!

**Comment by samuelkarp** [comment]
Released.
