### ISSUE TITLE
Scheduling tasks is failing with simple "AGENT" reason on 1.8.1

### ISSUE THREAD

**Issue by ryanwalls** [aws/amazon-ecs-agent#375]
When trying to schedule a task on my cluster using the api, get a response of:

```
{"Failures":[{"Arn":"arn:aws:ecs:us-west-2:763396238289:container-instance/eab7ed01-13fa-4280-a8f9-f5e48855e13e","Reason":"AGENT"}],"Tasks":[]}
```

I have no idea of the cause.  The agent was in the process of starting a different task when it gave this error when scheduling a 2nd task.

**Comment by samuelkarp** [comment]
From the [troubleshooting guide](http://docs.aws.amazon.com/AmazonECS/latest/developerguide/troubleshooting.html#api_failures_messages):

> `AGENT` (container instance ID)
>
>    The container instance that you attempted to launch a task onto has an agent which is currently disconnected. In order to prevent extended wait times for task placement, the request was rejected.

Is the agent currently marked as connected?

**Comment by ryanwalls** [comment]
Thanks for the quick reply.  At the time the agent gave that error, I had just scheduled a task and as far as I could tell it was still connected.  It was still putting out agent logs about running/stopping containers.  

Unfortunately, the instance has since been auto-scaled in so I can't verify it is still connected.  Will keep an eye on it and report back if I see more occurrences.  In the mean time we are just adding some retry logic to our task scheduling.

**Comment by samuelkarp** [comment]
@ryanwalls Sure, glad to help.  I'm going to close this for now, since it's expected that `RunTask` or `StartTask` will return an `AGENT` failure reason when the agent is disconnected.  If you end up seeing something different, please feel free to reopen this issue.
