### ISSUE TITLE
awslogs driver support

### ISSUE THREAD

**Issue by jhovell** [aws/amazon-ecs-agent#379]
Would like to be able to use the awslogs Docker logging driver to stream logs directly to AWS Cloudwatch Logs. Also required is being able to use variables in log stream and log group names such that individual image types can be directed to their own log groups, for example to make it easier to stream cloudwatch log events to another service like Elasticsearch Service.

It seems like this would rely on implementing this Docker issue https://github.com/docker/docker/issues/17747
or creating a separate AWS implementation outside of Docker.

Closed issue from this repo regarding graylog but with other awslogs driver discussion 
https://github.com/aws/amazon-ecs-agent/issues/238

Related closed Docker issue requiring upgrade to Docker 1.10 
https://github.com/docker/docker/issues/20358

Support forum thread:
https://forums.aws.amazon.com/thread.jspa?threadID=219551

Very convoluted heavyweight AWS blog solution, what I'm trying to avoid having to do:
https://blogs.aws.amazon.com/application-management/post/TxFRDMTMILAA8X/Send-ECS-Container-Logs-to-CloudWatch-Logs-for-Centralized-Monitoring

**Comment by samuelkarp** [comment]
@jhovell Thanks for opening this issue!  We are planning to support the awslogs log driver (see https://github.com/aws/amazon-ecs-agent/pull/366).  We're tracking this feature request in https://github.com/aws/amazon-ecs-agent/issues/9, so I'm going to close this as a duplicate.

**Comment by jhovell** [comment]
thanks @samuelkarp . So to summarize it sounds like ECS Agent will support the awslogs driver (maybe in the next agent release?) but the other underlying issues regarding the Docker awslogs driver or concerns about using ECS task IDs instead of container IDs remain open. Possibly this is the best workaround until then https://github.com/Signiant/logspout-ecs

**Comment by rsltrifork** [comment]
Looks like AWS added ECS support for awslogs just recently: http://docs.aws.amazon.com/AmazonECS/latest/developerguide/using_awslogs.html
