### ISSUE TITLE
Question: Memory swap values when no swap space is configured

### ISSUE THREAD

**Issue by chenliu0831** [aws/amazon-ecs-agent#382]
We are trying to investigate a performance problem and would like to rule out the possibility of swapping. On the latest AMI, a `docker inspect` gives me the following of the host config:
```
"HostConfig": {
        "Binds": [
            "/var/shared_bodylabs_static_cache:/bodylabs/bodylabs_static_cache"
        ],
        "ContainerIDFile": "",
        "LxcConf": null,
        "Memory": 15773728768,
        "MemoryReservation": 0,
        "MemorySwap": 31547457536,
        "KernelMemory": 0,
        "CpuShares": 8192,
        "CpuPeriod": 0,
        "CpusetCpus": "",
        "CpusetMems": "",
        "CpuQuota": 0,
        "BlkioWeight": 0,
        "OomKillDisable": false,
```

We didn't set up any swap space in the host instance and `free -m` also doesn't show up any swap space. Is those configs just a limit or there's actually allocation under the hood? Thanks.

P.S. it doesn't seem an `OOM` inside the container will actually crash the container, is that the expected behavior?

**Comment by chenliu0831** [comment]
@samuelkarp Would you mind shed some light? Thanks.

**Comment by samuelkarp** [comment]
Hi @chenliu0831,

My apologies for the delayed reply; I was out of the office for a few days with no access to a computer.

If there is no swap set in the host, the value you see for `MemorySwap` should have no effect.

ECS does not configure swap limits today.  The swap limit you see is a result of the default behavior from Docker when setting normal user memory constraints.  From the [Docker run reference](https://docs.docker.com/engine/reference/run/#user-memory-constraints):

> We set memory limit only, this means the processes in the container can use 300M memory and 300M swap memory, by default, the total virtual memory size (--memory-swap) will be set as double of memory, in this case, memory + swap would be 2*300M, so processes can use 300M swap memory as well.

Please let us know if you have any more questions.

Thanks,
Sam

**Comment by chenliu0831** [comment]
@samuelkarp Awesome. Don't worry at all. Thanks a lot!
