### ISSUE TITLE
[Question] Support for custom CNI plugins

### ISSUE THREAD

**Issue by Ganeshrockz** [aws/amazon-ecs-agent#3831]
### Summary

I skimmed through the code and couldn't find an extensible way to add custom 3rd party CNI plugins. I wanted to experiment creating a CNI plugin that applies some IPtable rules to the network. To do so, I don't want to run containers with increased privileges (Not sure if FARGATE supports such a mode) and hence looking for a CNI that does it in a native fashion. Are there plans in the roadmap to support the same similar to how k8s does it?

**Comment by Realmonia** [comment]
Hi @Ganeshrockz , thanks for the question. I took a glance at the containers-roadmap's issue list and didn't find a similar issue in the roadmap now. Please feel free to add your inquiries in https://github.com/aws/containers-roadmap/issues

I think if your need is only adding IPtable rules, you can potentially have a workaround by editing related code in amazon-ecs-cni-plugins (or potentially amazon-vpc-cni-plugins). Beside, you are also able to modify `ECS_CNI_PLUGINS_PATH` environment variable to configure to use a different CNI.

Please feel free to reopen if you have more questions or see problems when trying with above suggestions.
