### ISSUE TITLE
CgroupError: Agent could not create task's platform resources

### ISSUE THREAD

**Issue by ankitpictory** [aws/amazon-ecs-agent#3834]
### Summary

getting error "CgroupError: Agent could not create task's platform resources" on external instances 
### Description

we are running ecs tasks on external instances (OS --->Ubuntu20.04 LTS) using ecs anywhere agent. Our external instances fleet consists of on premise servers, GCP and Azure vms. We have been running the service without any issue since April its lately around 10 days back we started to get this "CgroupError: Agent could not create task's platform resources" error intermittently. We have raised an issue as well on premium support with case id "13389256011"

### Supporting Log Snippets

collect-mi-0554c722b1eb82099-202307270036.tgz

**Comment by mythri-garaga** [comment]
Hi, 

Could you please verify if the memory cgroup is enabled on Ubuntu20.04 LTS?  Also please provide the Task definition used.

Docker uses memory cgroups to set memory limit so if memory cgroup is disabled, the agent will fail to start the task due to unable to enforce memory limit.

**Comment by singholt** [comment]
closing, please re-open if you have an update for us.
