### ISSUE TITLE
Deployment doesn't cover all tasks.

### ISSUE THREAD

**Issue by zablowoj** [aws/amazon-ecs-agent#3838]
### Summary
Deployment doesn't cover all tasks.

### Description
ECS Cluster with EC2 provider.
I have 1 service with 8 tasks. After pushing new deployment via cli (aws-cli ver 2.7.35) not all tasks are refreshed.

ECS agent version: 1.74.1 and 1.72.0

Infra config:
1 node c6a.2xlarge - 4 tasks
4 nodes t3a.medium - 1 task each

**Comment by Realmonia** [comment]
Hi @zablowoj, this seems to be an ecs control plane issue. Please reach out to aws support for help.
