### ISSUE TITLE
Bring back task accounting changes?

### ISSUE THREAD

**Issue by ankon** [aws/amazon-ecs-agent#3925]
### Summary

There was a blog post announcing changes to the way the ECS agents schedules tasks (https://github.com/aws/containers-roadmap/issues/325, https://aws.amazon.com/blogs/containers/improvements-to-amazon-ecs-task-launch-behavior-when-tasks-have-prolonged-shutdown/), but the changes got reverted from what I can see (https://github.com/aws/amazon-ecs-agent/pull/3781), without much external communication. What is the plan forward for these?

**Comment by prateekchaudhry** [comment]
Hi @ankon, thank you for checking out this issue. The task scheduling changes were merged back with #3819 with bug fixes, and all ECS Agent versions >=1.74.1 have the benefit of this feature. Let us know if you have more questions related to this.

**Comment by ankon** [comment]
Thanks a lot for answering and linking the PR!
