### ISSUE TITLE
ubuntu container not starting with bash command

### ISSUE THREAD

**Issue by RahulMahale** [aws/amazon-ecs-agent#402]
I have a ecs-cluster running with following docker version
```
$ docker info
Containers: 9
Images: 11
Server Version: 1.9.1
Storage Driver: devicemapper
 Pool Name: docker-docker--pool
 Pool Blocksize: 524.3 kB
 Base Device Size: 107.4 GB
 Backing Filesystem: xfs
 Data file: 
 Metadata file: 
 Data Space Used: 461.9 MB
 Data Space Total: 9.437 GB
 Data Space Available: 8.975 GB
 Metadata Space Used: 393.2 kB
 Metadata Space Total: 25.17 MB
 Metadata Space Available: 24.77 MB
 Udev Sync Supported: true
 Deferred Removal Enabled: true
 Deferred Deletion Enabled: true
 Deferred Deleted Device Count: 0
 Library Version: 1.02.93-RHEL7 (2015-01-28)
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 4.1.13-19.31.amzn1.x86_64
Operating System: Amazon Linux AMI 2015.09
CPUs: 2
Total Memory: 7.308 GiB
Name: ip-172-31-37-158
ID: NRMT:Y7IU:XV6B:PHUC:W2II:4S2D:74FL:RDKO:FLQT:CB2X:BXND:JTQH

```

I have a basic task definition to launch the ubuntu container in ubuntu1.json

```
$ cat ~/test/ubuntu1.json 
{
  "containerDefinitions": [
    {
      "name": "cl",
      "image": "ubuntu:14.04",
      "cpu": 1024,
      "entryPoint": [
      "sh",
"-c"],
      "command": ["/bin/bash"],
      "memory": 1000,
      "essential": true
    }
  ],
  "family": "ubuntu1"

```

When I run this task definition the container isn't running and I can see it in Exited state.

```
$ docker ps -a
CONTAINER ID        IMAGE                            COMMAND                  CREATED             STATUS                      PORTS                        NAMES
6ae37e3326c4        ubuntu:14.04                     "/bin/bash"              24 minutes ago      Exited (0) 24 minutes ago                                ecs-ubuntu1-14-cl-d08fb1a589a682cb3900

```
Also it wont start when I use `docker start 6ae37e3326c4`
But the same container runs when I use the command 
```while true; do echo Hello World; sleep 1; done ``` in task-definition 

What is wrong with bash command ? though  it works with docker CLI with same image as

``` 
 $ docker run -it ubuntu:14.04 /bin/bash
root@d4dc7ec800b5:/# 
```

Why I am not able to do the same with ECS task-definition ?

Thanks in advance!

**Comment by gugahoi** [comment]
I dont think this is an ecs agent bug. Essentially `/bin/bash` is not a long running command and it will exit right after it is called unless you have access to docker's `-i -t` flags (https://docs.docker.com/engine/reference/run/) and in ECS you don't and should't.

**Comment by RahulMahale** [comment]
@gugahoi Thanks for the information, What should be the workaround to start the ubuntu container with `/bin/bash` command with ecs task-definition ?

**Comment by gugahoi** [comment]
Probably none as you should not run a container with `/bin/bash` - this container wont be doing anything other than staying idle which defeats the purpose of a docker cluster. What is your goal with this?

**Comment by RahulMahale** [comment]
Oh ok.
My goal is to just launch a ecs container with the SSH access, Once I have SSH access my Ansible scripts will deploy my rails app on it.

**Comment by gugahoi** [comment]
I think that approach is still defeating the purpose of a cluster - you are just substituting a server with ssh with a container with ssh, what is the benefit here? In any case, if you still want to follow this approach maybe check out this article: https://docs.docker.com/engine/examples/running_ssh_service/

Otherwise why don't you just create a docker image with your rails app and simply deploy the image in ecs?

**Comment by RahulMahale** [comment]
@gugahoi Now I am getting the picture clear, 
So to dockerize a app, you mean I will be running separate ruby, redis, nginx container ? 
What is the best tutorial or use case to convert my EC2 infra into ECS ?

Components of our Infrastructure .
-  ELB pointing to some domain.
-  ELB connected to web instance running rails app private subnet
- Background instance in private subnet running sidekiq and redis.
- Postgres RDS

How can I run above infra in ECS ?
Yeah test_sshd is working fine for now. But I will surely like to avoid this and dockerize the app

**Comment by cbbarclay** [comment]
You'll want to create a Dockerfile that encapsulates your app -- see step 3 http://docs.aws.amazon.com/AmazonECS/latest/developerguide/docker-basics.html#docker_hub_create_upload

Then you can create a task definition that references that Docker image and run it as a service behind a load balancer. See 
http://docs.aws.amazon.com/AmazonECS/latest/developerguide/ecs_services.html

You might want to use Elasticache Redis and RDS Postgres :)

**Comment by samuelkarp** [comment]
Thanks @gugahoi and @cbbarclay for jumping in here.  @RahulMahale, it sounds like your questions have been answered, so I'm going to close this issue.  Please feel free to open a new issue if you have additional questions.
