### ISSUE TITLE
native execdriver is hardcoded

### ISSUE THREAD

**Issue by pcarrier** [aws/amazon-ecs-agent#405]
In `agent/stats/container.go`:

```
	DockerExecDriverPath = "execdriver/native"
```

This stopped being true with Docker 1.11.0.

**Comment by samuelkarp** [comment]
Yep.  We've stopped depending on this with #400, which will be part of our next release.  In the meantime, our recommendation for enabling CloudWatch metrics with Docker 1.11 is [here](https://github.com/aws/amazon-ecs-agent/issues/387#issuecomment-215506004).

**Comment by pcarrier** [comment]
Closing as dup.
