### ISSUE TITLE
ECS_AGENT_CONFIG_FILE_PATH differs from documentation on version 1.9.0

### ISSUE THREAD

**Issue by apazzolini** [aws/amazon-ecs-agent#409]
If I run `docker inspect` on my amazon-ecs-agent container, i see this in the result:

```
"ECS_AGENT_CONFIG_FILE_PATH=/etc/ecs/ecs.config.json"
```

This differs from the `/etc/ecs/ecs.config` that is all over the documentation on the internet. Furthermore, this changes both the names and behavior of certain variables.

For example, instead of being able to specify `ECS_ENGINE_TASK_CLEANUP_WAIT_DURATION=48h`, I had to put the following in `ecs.config.json` to get it to pick up:

```
{
    "TaskCleanupWaitDuration": 172800000000000
}
```

I didn't see an easy way to change the config file path to the non-JSON version as the docker container is launched by the `/usr/libexec/amazon-ecs-init` process.

**Comment by samuelkarp** [comment]
Hi @apazzolini,

Thanks for opening the issue here.  On the ECS-optimized AMI, there are actually two separate config files.  The first, at `/etc/ecs/ecs.config.json` is passed in to the agent and is a JSON-formatted file.  The second, at `/etc/ecs/ecs.config` is actually [read by `ecs-init`](https://github.com/aws/amazon-ecs-init/blob/v1.9.0-1/ecs-init/docker/docker.go#L168-L186) and passed to the agent directly as environment variables.  You should be able to use either file.

Please let us know if you have any problems with configuration.

Sam

**Comment by apazzolini** [comment]
Hi Sam,

I attempted the `/etc/ecs/ecs.config` file first, but could not get it to read anything from there. The logs in `/var/log/ecs/ecs-agent.log.xxxx` read the following:

```
Invalid value for task cleanup duration, will be overridden to 3h0m0s module="config" parsed value="0" minimum threshold="1m0s"
```

regardless of what was in `/etc/ecs/ecs.config`, such as: 

```
ECS_ENGINE_TASK_CLEANUP_WAIT_DURATION=48h
```

I'm not a Go expert, but from the code you linked, it appears to be loading the file identified by `AgentConfigFile`, which from inspecting the agent container resolves to the `.json` path. 

I'm happy to perform any troubleshooting steps to help debug.

Thanks!

**Comment by samuelkarp** [comment]
Can you look at `docker inspect ecs-agent` and look at the environment variables in `Env`?  You should see an entry for `ECS_ENGINE_TASK_CLEANUP_WAIT_DURATION=48h`.

**Comment by samuelkarp** [comment]
For example, here's what I see:

```json
        "Env": [
            "ECS_LOGFILE=/log/ecs-agent.log",
            "ECS_DATADIR=/data",
            "ECS_UPDATES_ENABLED=true",
            "ECS_AVAILABLE_LOGGING_DRIVERS=[\"json-file\",\"syslog\",\"awslogs\"]",
            "ECS_AGENT_CONFIG_FILE_PATH=/etc/ecs/ecs.config.json",
            "ECS_UPDATE_DOWNLOAD_DIR=/var/cache/ecs",
            "ECS_ENGINE_TASK_CLEANUP_WAIT_DURATION=48h",
            "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
        ],
```

**Comment by apazzolini** [comment]
```
[ec2-user@ip-10-0-102-11 ecs]$ docker restart ecs-agent
ecs-agent

[ec2-user@ip-10-0-102-11 ecs]$ ls -l /etc/ecs
total 8
-rw-r--r-- 1 root root 42 May 17 16:26 ecs.config
-rw-r--r-- 1 root root 51 May 17 15:17 ecs.config.json

[ec2-user@ip-10-0-102-11 ecs]$ cat /etc/ecs/ecs.config
ECS_ENGINE_TASK_CLEANUP_WAIT_DURATION=48h

[ec2-user@ip-10-0-102-11 ecs]$ docker inspect ecs-agent | grep ECS_
            "ECS_LOGFILE=/log/ecs-agent.log",
            "ECS_DATADIR=/data",
            "ECS_UPDATES_ENABLED=true",
            "ECS_AVAILABLE_LOGGING_DRIVERS=[\"json-file\",\"syslog\",\"awslogs\"]",
            "ECS_AGENT_CONFIG_FILE_PATH=/etc/ecs/ecs.config.json",
            "ECS_UPDATE_DOWNLOAD_DIR=/var/cache/ecs",

[ec2-user@ip-10-0-102-11 ecs]$ curl http://localhost:51678/v1/metadata
{
  "Cluster":"default",
  "ContainerInstanceArn":"arn:aws:ecs:us-east-1:xxx:container-instance/xxx",
  "Version":"Amazon ECS Agent - v1.9.0 (0931217)"
}
```

**Comment by samuelkarp** [comment]
Ah, I think that's the problem.  `docker restart` won't cause new configuration to be picked up.  Instead, you'll want to run `sudo stop ecs; sudo start ecs`.

**Comment by apazzolini** [comment]
Ah I see, so it loads the configuration when it's creating the container, not when the container starts up!

Restarting the ecs service worked, I can see the environment variable in the Docker container and the logs at startup don't have the WARN log message.

Thanks Sam!
