### ISSUE TITLE
Update not supported on ARM architecture

### ISSUE THREAD

**Issue by andreialecu** [aws/amazon-ecs-agent#4099]
### Summary

For a while, we haven't been able to update the ecs-agent when using ARM runners. I'm pretty sure this used to work.

### Description

Within the AWS ECS console via the web, if I try to update the agent on containers, it fails with:

```
Container agent could not be updated for instance i-03.....
Update not supported on Arm architecture.
```

### Expected Behavior

Agent should update.

### Observed Behavior

Update is prevented

![CleanShot 2024-02-23 at 12 27 39@2x](https://github.com/aws/amazon-ecs-agent/assets/697707/26fc9fd0-8aa7-4668-a857-f46335c21c7d)

**Comment by prateekchaudhry** [comment]
Hi @andreialecu , thanks for reaching out. ECS Console is using **UpdateContainerAgent API** to update ECS agent on connected instances. This API does not support arm architecture currently - See [docs](https://docs.aws.amazon.com/AmazonECS/latest/APIReference/API_UpdateContainerAgent.html)

Please follow this related open request and vote for more visibility here - https://github.com/aws/containers-roadmap/issues/1158

You can get updated agent on arm through other recommended methods here - https://docs.aws.amazon.com/AmazonECS/latest/developerguide/agent-update-ecs-ami.html

You may also manually update the agent - https://docs.aws.amazon.com/AmazonECS/latest/developerguide/manually_update_agent.html
