### ISSUE TITLE
DockerTimeoutError: Could not transition to pullBegin; timed out after waiting 5m0s

### ISSUE THREAD

**Issue by davidkelley** [aws/amazon-ecs-agent#410]
I'm hoping that you could shed some light onto what is happening here, whether it be a bug or simply a mistake on my part, but either way it'd be great to get some help with this issue.

The setup for our cluster is:
* Running (well trying to) on `ami-a1fa1acc`.
* _Our live environment is currently running `ami-e2b1f988`._
* 20-40 `c4.xlarge` instances running inside a private subnet.
* A working cluster has around ~300 running tasks
* Private subnet has NAT Gateway setup correctly and confirmed working.
* Private repositories are stored on Docker Hub
* Authentication for the ECS Agent is setup [via the official docs](http://docs.aws.amazon.com/AmazonECS/latest/developerguide/private-auth.html)
* Setup for each agent is:
```
#!/bin/bash
yum install -y aws-cli
aws s3 cp s3://.../ecs/ecs.config /etc/ecs/ecs.config
echo ECS_CLUSTER=xxx >> /etc/ecs/ecs.config
service docker start
start ec
```

When we attempt to move onto a more recent AMI (Docker > 1.7.0) our logs show this error. This appears for all our private (and occasionally public) repositories. All the pending tasks fail and even after waiting a considerably long period of time, no tasks transition to running.
```
DockerTimeoutError: Could not transition to pullBegin; timed out after waiting 5m0s
```

This happens when we have 0 instances active, but 91 task definitions in the cluster. As instances register themselves onto the cluster, a resource exhausting amount of tasks are scheduled onto each instance. Might this be the problem or is it something else?

**Comment by aaithal** [comment]
@davidkelley could you please verify if you're able to pull images outside of the agent by manually ssh'ing to the instance that uses the `ami-e2b1f988`? That would help us in root-causing this issue. Also, could you please share docker logs (`/var/log/docker`) when this happens?

**Comment by davidkelley** [comment]
@aaithal sorry for the slow response. I will spend some time on this tomorrow morning and hopefully get back to you with more information.

**Comment by davidkelley** [comment]
@aaithal we have managed to resolve this issue. I have documented our solution below incase any others stumble upon on the issue via Google.

Any `docker pull` command was timing out with the following error, causing the ECS Agent to throw the error documented in this issue.

```
Error response from daemon: error parsing HTTP 408 response body: invalid character '<' looking for beginning of value: "<html><body><h1>408 Request Time-out</h1>\nYour browser didn't send a complete request in time.\n</body></html>\n\n"
```

Inspecting the network devices via `ifconfig` we saw that the `docker0` device was running with an MTU of 1500, whilst `eth0` was running with an MTU of `9001`. After running the following commands, `docker pull` works immediately.

```
sudo ifconfig eth0 mtu 1500
sudo service docker restart
```

**Comment by aaithal** [comment]
@davidkelley thanks for providing these details. I'm curious about what led you to think that this was an issue with the configuration of the network device. I can see that all my Instances have this mismatch in MTU between `eth0` and `docker0` and I haven't run into such issues. On a related note, does the problem go away when you reverse the setup (i.e. Have both docker0 and eth0 mtu set to 9001)?

**Comment by samuelkarp** [comment]
@davidkelley Are you still experiencing problems here?

**Comment by lougreenwood** [comment]
I just came across this issue and the MTU fix seems to have worked for me too...
