### ISSUE TITLE
Access to task id within container

### ISSUE THREAD

**Issue by jbergknoff** [aws/amazon-ecs-agent#411]
It's difficult to trace the log output of a container back to the ECS task which generated it.

I see an ECS-assigned task id, which is different from an ECS-assigned container id, which is different from a Docker-assigned container id. As far as I know, the Docker container id is the only one of those three accessible from within the container (truncated, as the hostname). However, the ECS web console is only searchable by ECS task id.

One approach might be to have the ECS agent inject environment variables identifying the task (similar to the labels the agent already sets) and possibly the container instance. Then a container could print these details in exceptional cases, making it easy to track down the task for debugging purposes.

I'd love to hear other thoughts on making this connection between a log stream aggregated elsewhere (e.g. Papertrail) and the ECS task generating the logs. Thanks.

**Comment by samuelkarp** [comment]
This looks like a duplicate of #258.

**Comment by jbergknoff** [comment]
You're right, thanks.
