### ISSUE TITLE
Add support for custom ECS-Agent and ECS-Telemetry Endpoints

### ISSUE THREAD

**Issue by jakauppila** [aws/amazon-ecs-agent#4117]
### Summary
Add the ability to define custom ECS-Agent and ECS-Telemetry endpoints for external instances that need to talk to the ECS control plane

### Description
Referencing the Networking with ECS Anywhere segment from the [ECS documentation](https://docs.aws.amazon.com/AmazonECS/latest/developerguide/ecs-anywhere.html), the ECS agent requires access to specific domains for operational functionality. Currently, ECS_BACKEND_HOST can be set to a custom ECS endpoint, which we utilize for directing traffic through a VPC endpoint in our setup for ECS Anywhere external instances. However, this capability doesn't extend to setting custom endpoints for the agent or telemetry services. The existing workaround involves modifying on-prem DNS to reroute queries, as detailed in [this AWS blog](https://aws.amazon.com/blogs/containers/how-to-establish-private-connectivity-with-ecs-anywhere/). Implementing such a workaround is feasible but requires considerable effort and time, otherwise, we could utilize a proxy to manage the traffic routing.

Introducing options to specify custom endpoints directly would significantly streamline configuration
- ECS_AGENT_ENDPOINT
- ECS_TELEMETRY_ENDPOINT

**Comment by hozkaya2000** [comment]
Hello @jakauppila,

Thank you for your explanation on this feature request. We suggest you follow these the "Community Request" issue template [here](https://github.com/aws/containers-roadmap/issues/new?assignees=&labels=Proposed&projects=&template=community-request-.md&title=%5Bservice%5D+%5Brequest%5D%3A+describe+request+here) in the containers-roadmap repository. This is ECS's expected method for feature requests.

Thank you!
