### ISSUE TITLE
awslogs-stream option not supported by the awslogs driver

### ISSUE THREAD

**Issue by AntoineBro** [aws/amazon-ecs-agent#418]
Task definitions cannot use the  awslogs-stream option when using the awslogs driver : 
  `Log driver awslogs disallows options: awslogs-stream`

The ability to configure the logstream name was mentioned several times already ( https://github.com/aws/amazon-ecs-agent/pull/251, https://github.com/aws/amazon-ecs-agent/issues/200 , https://github.com/aws/amazon-ecs-agent/issues/379 ) but I could not find an open issue capturing this need. 

It would be great to be able to use string interpolation to customize logstream names while still guaranteeing their uniqueness  inside a Loggroup.

eg something like 
 ```
 "logConfiguration": {
        "logDriver": "awslogs",
        "options": {
          "awslogs-group": "loggroup",
          "awslogs-region": "us-east-1",
          "awslogs-stream": "logstream-docker-webapp-{CONTAINER_ID}",
        }
      }
```

This probably also relates to  https://github.com/docker/docker/issues/17747

**Comment by FrederikNygaardSvendsen** [comment]
I would love to see support for this as well

**Comment by MrStaind** [comment]
+1

**Comment by ievgeniiVlasyuk** [comment]
+1
https://docs.docker.com/engine/admin/logging/awslogs/ says it should support but no luck.

**Comment by apictogram** [comment]
+1, been waiting for this every since I stopped waiting for awslogs support

**Comment by bamdadd** [comment]
I'm also waiting for this for a long time. Its extremely hard to read the logs with randomly assigned steam names

**Comment by forwardinc** [comment]
+1

**Comment by danland** [comment]
+1 

This seems like a crazy oversight, in a multi container setup with everything going the same group (as is logical,) it's impossible to decipher what's what without having to log into the instance to figure out the container IDs first.

**Comment by jacekszubert** [comment]
+1

**Comment by Ogrodniczek** [comment]
+1

**Comment by grn-bogo** [comment]
+1

**Comment by StyleT** [comment]
+1

**Comment by ReeSilva** [comment]
+1

**Comment by anshrma** [comment]
+1

**Comment by zgolus** [comment]
+1

**Comment by kiranmeduri** [comment]
Today we launched support for awslogs-stream-prefix, which lets you name your log stream that includes the taskID so that it's easy to go from a task to the log stream and from the log stream to the task. See the documentation for more information. http://docs.aws.amazon.com/AmazonECS/latest/developerguide/using_awslogs.html

**Comment by bollig** [comment]
Does the prefix support variables like "{{.ImageID}}/{{.ID}}"? I'd like to get the ECS instance ID in the prefix as well.

**Comment by cmukai-cisco** [comment]
When I do this developers tell me it is difficult to search the logs. They would rather see all the streams in one place. Is it possible to support both awslogs_stream and awslogs_stream_prefix?

**Comment by getspooky** [comment]
Jut replace `awslogs-stream` by `awslogs-stream-prefix`.
