### ISSUE TITLE
Run Security Updates without failing long-running tasks

### ISSUE THREAD

**Issue by mshober** [aws/amazon-ecs-agent#4210]
I have an ECS cluster that runs long-running batch jobs. Because of how long these tasks run, it makes it difficult to replace instances with [the latest ECS Optimized AMIs](https://github.com/aws/amazon-ecs-ami/releases) as they become available.

I have previously attempted to use AWS Patch Manager to patch my instances, but that resulted in failures of my running tasks due to Patch Manager upgrading and restarting docker, which I commented about in another issue here: https://github.com/aws/amazon-ecs-agent/issues/3853#issuecomment-1683101114. 

I would instead like to run `dnf upgrade` on a scheduled basis and exclude all packages that restart services responsible for running ECS tasks. So far I have:
```
dnf upgrade  --security --exclude=docker --exclude=containerd
```

Are there any other packages that should be excluded to prevent failing of running tasks during dnf updates?

**Comment by amogh09** [comment]
Hi @mshober . `runc` is another core dependency for running tasks so I suggest you exclude it as well. That should be all.

**Comment by amogh09** [comment]
Please reopen if you have any further questions.
