### ISSUE TITLE
Expiring Private Registry Credentials

### ISSUE THREAD

**Issue by yeungda-rea** [aws/amazon-ecs-agent#423]
We have a private registry. It is authenticated using time limited credentials. How can we use the ECS agent with our private registry?

When reading the docs about [private registries](http://docs.aws.amazon.com/AmazonECS/latest/developerguide/private-auth.html), I see that:

> The Amazon ECS-optimized AMI scans the /etc/ecs/ecs.config file for these variables when the container instance launches, and each time the service is started (with the sudo start ecs command). AMIs that are not Amazon ECS-optimized should store these environment variables in a file and pass them with the --env-file path_to_env_file option to the docker run command that starts the container agent.

[dockerauth.go](https://github.com/aws/amazon-ecs-agent/blob/master/agent/engine/dockerauth/dockerauth.go#L93) confirms what the docs say.

It sounds like the life cycle of credentials is coupled to the life cycle of the ecs agent. Does this design mean that when our credentials expire, we must restart the ecs agent, with fresh credentials? When we talk about doing this, collegues get nervous. We would prefer not to restart the agent for this reason (unless someone can assure us that is it fine to do so).

Would you be open to supporting another way to source credentials, other than environment variables? What about a file path, or potentially even an s3 object?

In principal, if the ecs agent could read credentials from a file or from an S3 object whenever it performed an operation on the docker engine API, it would be possible for _something else_ to ensure the tokens were fresh.

We have solved a similar problem for containers running the official docker client that require access to our private registry. In this case we run a sidecar container that periodically fetches a fresh token and generates `~/.docker/.config.json`, and writes it to a volume. This volume is shared with another container that runs a docker client.

We could do something similar to this for the ecs agent too, if it were able to read the docker client's config format. I have noticed that `go-dockerclient` is able to read authentication data from `~/.docker` in [go-dockerclient/auth.go](https://github.com/fsouza/go-dockerclient/blob/master/auth.go).

**Comment by samuelkarp** [comment]
Hi @yeungda-rea,

Yes, the documentation is correct that the credentials are only read as the agent starts.  I'm really curious to find out a bit more about what you're doing with expiring credentials; the only registry implementation I'm aware of right now that does this is [EC2 Container Registry](http://aws.amazon.com/ecr/), and we built [specific support](https://github.com/aws/amazon-ecs-agent/blob/v1.10.0/agent/engine/dockerauth/ecr.go) for ECR in the agent.  I think the other two issues related to this are probably https://github.com/aws/amazon-ecs-agent/issues/28 (which deals with credentials in the task definition and doesn't sound like it would address your problem) and https://github.com/aws/amazon-ecs-agent/issues/141 (which deals with pulling images directly from S3 without a registry).

Can you explain a bit about what your requirements look like?  Are your credentials scoped to a particular repository or the whole registry?  How frequently do they expire?  Is there some way to generate the credentials or are you retrieving them through some mechanism where you exchange an existing long-lived credential for a short-lived token?  Would you want the credentials to be available to pull images for any task launched through ECS on the instance or are you looking to scope to specific tasks/task definitions?

I think reading credentials from a file or an S3 object might be a reasonable approach, but I'd like to run it by some people internally before I can say that's a direction we'd go.  Leveraging go-dockerclient to do this might also be reasonable, though we'd need to ensure that the credential file were properly bind-mounted into the agent container.

Sam

**Comment by yeungda-rea** [comment]
Hi @samuelkarp,

We wanted a registry that is accessible:

A) from any AWS account;
B) by people and machines;
C) without using high value credentials (that docker stores in plain text on disk); 
D) without using long lived credentials

We built a system that distributes expiring credentials to authorized IAM roles using S3. It works this way:

1. A person or machine first obtains IAM credentials 
2. The IAM credentials are used to obtain fresh docker registry credentials 
3. The docker registry credentials are used to obtain docker images
 
Our credentials contain a token, which is cryptographically signed by our token authority. It is a matter of policy as to when they expire (typically hours), how they are scoped, and what actions are allowed. Credentials cannot be generated by users.

It seems reasonable to use the same credentials for any task launched by the ECS agent on the EC2 instance.

**Comment by kiranmeduri** [comment]
Hi @yeungda-rea,

We understand your use-case and it makes complete sense. However to be robust, we need to make sure all the components which take part in container launch flow be available and reliable. As per your proposal we need to build a mechanism whereby agent can make sure that a new component which refreshes the credentials is working as expected. Today there is no clean way for ecs-agent to do this. Only solution we have is to mimic the way ecs-agent integrates with EC2 Container Registry (essentially fork ecs-agent). 

Out of curiosity, all the requirements you mentioned are currently supported by EC2 Container Registry (as @samuelkarp pointed out). Any reason ECR is not a solution for you? 

Thanks,
Kiran

**Comment by yeungda-rea** [comment]
@kiranmeduri: Thanks for taking the time to look into this issue.

In addition to those authentication requirements, we also require a private docker registry in `ap-southeast-2`. We have been running our own since late last year, and this seems to be the best option for us at present, but we continue to monitor ECR's available regions with interest. Even when ECR becomes available to us in a form we want to use, I expect there will be some period time when we want to support both. By raising this issue, I am simply trying to remove blockers for adoption of ECS in our organization.

Let me summarize our options so far:

**The environment variable provider**: We have established that these are inappropriate for credentials which have a shorter lifespan than the ECS agent's process.

**The ECR credential provider**: this seems to be the gold standard for robustness in the container launch flow, but obviously not appropriate for our Private Registry.

**A File credential provider**: I think you're suggesting that the agent would need a mechanism to verify the tokens are being refreshed so it can be robust. As with the environment variable provider, I expect that the validity of the credentials are the responsibility of whomever is providing them to the agent. The agent doesn't need to know that credentials expire, just that they are in a file. On robutsness, I feel more secure knowing that the token can be cached on the file system. The ECR implementation seems to require that the token service is always available at container launch time, even if the agent had recently retrieved a token that was still valid. It is correct that anything refreshing a token would have to be made robust too, but that would be _my_ responsibility.

**An S3 credential provider**: Same goes for the file credential provider idea.

**A custom credential provider in a fork**: Whereby we maintain a fork of the ecs-agent, with a patch that implements our custom credential provider. Would you be open to supporting a stable interface for custom credential providers? I would feel more comfortable maintaining a fork if this were so.

I also thought of another way:

**Something like the docker client's credential store**: The docker client for example now supports [credential store interface](https://docs.docker.com/engine/reference/commandline/login/#credentials-store). You are probably aware of it since someone at AWS made the [ECR credential helper](https://github.com/awslabs/amazon-ecr-credential-helper). In terms of integration, this is probably easier because the authentication helper would be decoupled from the ECS agent binary. Instead, we could maintain a docker image that is based on the ECS agent's image, but adds a binary that just does the custom authentication for our private registry.

Do you think any of these options would be viable?

**Comment by samuelkarp** [comment]
@yeungda-rea ECR is now available in ap-southeast-2 (see the [launch announcement](https://aws.amazon.com/about-aws/whats-new/2016/08/amazon-ec2-container-registry-region-expansion/)).

If you're still interested in building a different solution, I think the most reasonable approach might be building a credential provider that conforms to the Docker client's credential store interface and either invoking a binary in the same image or invoking a binary stored in a separate Docker container.

**Comment by samuelkarp** [comment]
I'm going to close this for now.  Feel free to re-open it if you'd like to continue discussion on an approach here.
