### ISSUE TITLE
Excessive memory usage on docker 1.11

### ISSUE THREAD

**Issue by chenliu0831** [aws/amazon-ecs-agent#424]
Just curious, does anyone notice a excessive memory usage of `containerd-shim`? In our case, we are testing the latest AMI and before any real task is running the memory usage already climb to close to 10G. Inspect from `top` reveals a couple of process on  `containerd-shim` each consumed ~200M memory. Our container is pretty huge (~2G) but those memory footprint looks suspicious.

Looks like this could be related to an open issue of https://github.com/docker/docker/issues/21737

**Comment by samuelkarp** [comment]
@chenliu0831 Yes, this looks like https://github.com/docker/docker/issues/21737.  I'm going to close this in favor of that issue as we're tracking that one.
