### ISSUE TITLE
README: Link missing for more information about the ECS_ENABLE_GPU_SUPPORT environment variable

### ISSUE THREAD

**Issue by chriswachira** [aws/amazon-ecs-agent#4311]
### Summary
Link to AWS docs is missing for more information about the `ECS_ENABLE_GPU_SUPPORT` environment variable.

### Description
In the README file, the description for the `ECS_ENABLE_GPU_SUPPORT` environment variable is incomplete ending with "For more information" without providing the link to the AWS documentation.

I will be raising a Pull Request to include the link to the documentation.

**Comment by singholt** [comment]
Thanks for reporting this and your contribution!

**Comment by singholt** [comment]
merged #4313
