### ISSUE TITLE
Allow to input device flag in the task definition

### ISSUE THREAD

**Issue by jamborta** [aws/amazon-ecs-agent#433]
It would be great if the device flag can be specified in the task definition. For me it is needed to map the hosts GPU devices to docker. If someone knows a workaround, that would also be a great help.

**Comment by kiranmeduri** [comment]
Thank you for your input. We will take this as a feature request and look into ways on providing support for GPUs, also other devices. 

-kiran

**Comment by jamborta** [comment]
thanks @kiranmeduri 
is this something you'd consider in the near future? I will have to look into alternative solutions if not.

**Comment by bfolkens** [comment]
@kiranmeduri we need this rather quickly too - if I spent time on a push request would it be considered?

**Comment by mittomen** [comment]
@kiranmeduri We planned to use gpu accelerated clusters but without this feature the ecs-agent is not capable for such a job. Is there any progress on that?

**Comment by davidvuong** [comment]
Any updates on this?

**Comment by chenliu0831** [comment]
Is this being actively worked on? If not I'm interested in contributing (related to #656 which I believe should be reopened)

**Comment by bploetz** [comment]
Any update on this?

**Comment by samuelkarp** [comment]
You can now [specify devices to add to your containers in your task definition](https://aws.amazon.com/about-aws/whats-new/2017/11/amazon-ecs-adds-support-for-docker-device-and-init-flags-in-container-task-definitions/).  You can add these new options in the AWS Console now, and they'll be available in the AWS CLI and SDKs soon.
