### ISSUE TITLE
Update amazon-ecs-cni-plugins to 2024.09.0

### ISSUE THREAD

**Issue by ginglis13** [aws/amazon-ecs-agent#4435]
`amazon-ecs-cni-plugins` has a newer release, `2024.09.0`: https://github.com/aws/amazon-ecs-cni-plugins/blob/master/VERSION

The `amazon-ecs-agent` currently tests against `2020.09.0`: https://github.com/aws/amazon-ecs-agent/blob/a08050481d214746d5e2c6f73ad360c69f63cd95/agent/ecscni/plugin_test.go#L31-L32

**Comment by danehlim** [comment]
Hi @ginglis13, thank you for raising this! 

A pull request to update the newest amazon-ecs-cni-plugins release has been merged to `dev` branch and will be subsequently merged to `master` branch and go out in the next ECS Agent / ECS Init release.
