### ISSUE TITLE
Exposing host's hostname and image id

### ISSUE THREAD

**Issue by kaihendry** [aws/amazon-ecs-agent#456]
Maybe I'm missing something, but I find it useful to know which image (image id) I am running from the Web application itself.

Similarly I would like to know what EC2 instance it's running upon, just to get a better idea what the load balancer is doing.

I don't quite understand how to expose those environment variables. I'm thinking the agent should just do it. Or should I look elsewhere?

https://count.dabase.com/ is my env test running on ECS in Singapore.

**Comment by juanrhenals** [comment]
Hello @kaihendry, 
> Maybe I'm missing something, but I find it useful to know which image (image id) I am running from the Web application itself.

Can you explain a little bit more about your use case and what you would be using the image id for?

> Similarly I would like to know what EC2 instance it's running upon, just to get a better idea what the load balancer is doing.

In regards to the EC2 _instance-id_, this is not exposed as an environment variable within the host (or container for that matter), it is exposed though the Instance Metadata Service. This can be accessed from any container on the host; you can read more about the available Instance Metadata Categories [here](http://docs.aws.amazon.com/AWSEC2/latest/UserGuide/ec2-instance-metadata.html#instancedata-data-categories).

> I don't quite understand how to expose those environment variables. I'm thinking the agent should just do it. Or should I look elsewhere?

Currently, we do not support setting these values into environment variables. That said, you are free to set them manually using the values from the Instance Metadata Service.

**Comment by kaihendry** [comment]
Knowing the image id or digest rather will help us know exactly what container the Instance is running. This is helpful to know from the Website whilst doing deployments for example.

**Comment by kiranmeduri** [comment]
IIUC in general there is a use-case for exposing some of the static details from `docker inspect` to the container. I would record this as a feature request which we do not support today. Whether it is environment variable or some other access mechanism is yet to be decided. Thanks for bringing this up.

**Comment by aaithal** [comment]
@kaihendry I'm closing this as it's now being tracked in #710. We will update that issue as we have more updates. Please feel free to update that issue if you have more comments. Thanks!
