### ISSUE TITLE
Docker crashes, Agent disconnects

### ISSUE THREAD

**Issue by plorent** [aws/amazon-ecs-agent#457]
Two ECS instances in our development environment are showing an agent disconnect. On both instances Docker crashed. The issue seems to be related to daily automated and manual deployments.

`sudo cat /var/lib/ecs/data/ecs_agent_data.json | jq '.Data.TaskEngine.Tasks[].Containers[].Name' | wc -l `

renders 216 and 163 as a result where we are expecting something like 7.
We are using AMI 2016.03.d

Relevant System and Agent logs are attached.

The Agent cannot be restarted and the only thing we can do is kill the instances. Which I will do and then set the log level to debug.

[ecs-agent-log.txt](https://github.com/aws/amazon-ecs-agent/files/377696/ecs-agent-log.txt)
[system-log.txt](https://github.com/aws/amazon-ecs-agent/files/377710/system-log.txt)

**Comment by plorent** [comment]
It appears that this is related to a container not starting properly. The service keeps trying to start the container. As a result the number of tasks in ecs_agent_data.json increase. At a certain point the Docker daemon stops accepting connections.
Fixing the problem with the container not starting properly, fixes the issue.

**Comment by aaithal** [comment]
Hi @plorent, I'm glad that you were able to resolve this issue by fixing the issue with the container. I'm closing this issue as the ECS Agent appears to be working correctly in this scenario. Feel free to create a new issue if you continue running into the problem Thanks!
