### ISSUE TITLE
Remove container on exiting

### ISSUE THREAD

**Issue by alexwen** [aws/amazon-ecs-agent#460]
The docker run command has an option to remove a container on exiting:

```
--rm                          Automatically remove the container when it exits
```

It would be nice if this option could be surfaced through the task definition to allow us to remove more ephemeral tasks immediately upon completion, as opposed to waiting for a duration to pass.

**Comment by aaithal** [comment]
Hi @alexwen, we wanted customers to be able to debug their containers if anything went wrong with them. Hence, we decided to support a time-based container removal configuration. The time-based configuration of `ECS_ENGINE_TASK_CLEANUP_WAIT_DURATION` can be set to as low as `1m` on the container instance. Please let us know if that helps with your use-case. If not, could you please provide more information about your use-case? That helps us in prioritizing the feature work. 

Thanks,
Anirudh

**Comment by alexwen** [comment]
Hi Anirudh,

Thanks for the response. We are using our ECS cluster for builds, which can use quite a bit of space. We did end up shortening our cleanup wait duration to 10 minutes to hopefully not be affected in the future but I thought it would be nice, as perhaps an option, when creating the task  if we could specify that this specific container should be removed on completion.

Additionally, is there any way available space could be taken into consideration by the agent when scheduling? Our ECS instance was at 100% usage on our principal volume and docker had become unresponsive to commands. In this case the only way I was able to recover the instance, without access to docker to manually remove the containers, was to completely replace it in our cluster.

Thanks!
Alex

**Comment by aaithal** [comment]
Hi @alexwen, thanks for providing those details. As per my previous post, I think you can work around `docker run --rm` by setting the `ECS_ENGINE_TASK_CLEANUP_WAIT_DURATION` to a low value like `1m`, which should result in faster container cleanup than the default setting.
 
> Additionally, is there any way available space could be taken into consideration by the agent when scheduling? Our ECS instance was at 100% usage on our principal volume and docker had become unresponsive to commands. In this case the only way I was able to recover the instance, without access to docker to manually remove the containers, was to completely replace it in our cluster.
 
We are looking at ways where the ECS Agent can report its health to ECS. ECS would then be able to make the placement decision based on Agent health. Among other things, free disk space available on the instance would definitely be taken into consideration for determining the health of the Container Instance. Unfortunately, we do not have a timeline for this yet. We'll keep you posted.
 
Thanks,
Anirudh

**Comment by alexwen** [comment]
Thank you Anirudh! I look forward to improved checks for agent health.

**Comment by aaithal** [comment]
Closing in favor of #483
