### ISSUE TITLE
ECS agent does not clean up images

### ISSUE THREAD

**Issue by davidsiaw** [aws/amazon-ecs-agent#463]
I routinely add revisions to deploy new versions of my application to ECS. One day it failed with the following status: 

```
Status reason	CannotPullContainer
Error: write /var/lib/docker/tmp/GetImageBlob501781855: no space left on device
```

When I logged on to the container, sure enough, none of the images were deleted:

```
[root@ip-10-0-3-162 ec2-user]# docker images
REPOSITORY                TAG                     IMAGE ID            CREATED             SIZE
x/webapp            df263ed31743-20160728   2a93dccb13d9        About an hour ago   1.413 GB
x/webapp            d5e9f688f866-20160727   f16913761056        24 hours ago        1.412 GB
x/webapp            fdae780bf92c-20160722   1b092d0a44d4        6 days ago          1.413 GB
x/webapp            5ddbb462c48f-20160719   f3a403985c14        9 days ago          1.413 GB
x/webapp            9ff4ead40c03-20160715   df76f770c41b        13 days ago         1.412 GB
x/webapp            e61dafb5543f-20160715   df76f770c41b        13 days ago         1.412 GB
x/webapp            a71dd9a72111-20160714   8c5611231690        13 days ago         1.412 GB
x/webapp            f313b3b4087b-20160713   c3c5e8bbc7b7        2 weeks ago         1.456 GB
x/amazon-ecs-agent   latest                  d51cf3065cef        9 weeks ago         9.317 MB
```

The ECS agent should strive to delete images and containers it does not need, otherwise the machine simply fails to deploy for no good reason and any operations on the machine become unresponsive.

**Comment by aaithal** [comment]
@davidsiaw Cleaning up of stopped containers is already handled by the ECS Agent. Please refer to the [documentation](http://docs.aws.amazon.com/AmazonECS/latest/developerguide/ecs-agent-config.html) for configuring this via `ECS_ENGINE_TASK_CLEANUP_WAIT_DURATION`. Image clean up is being tracked as a feature request here: #118. The proposal for the same can be found in the [thread](https://github.com/aws/amazon-ecs-agent/issues/118#issuecomment-233065083) as well. I'm closing this in favor of that. Feel free to comment on the original issue if you have any further feedback.

Thanks,
Anirudh
