### ISSUE TITLE
Request: Support for tmpfs parameter when launching containers

### ISSUE THREAD

**Issue by CameronGo** [aws/amazon-ecs-agent#469]
There is now support in the docker engine for a tmpfs flag that mounts a tmpfs file system into the running container.  I believe this was added with docker v1.10.0.  I would very much like to use this as a mechanism to store config secrets (such as PGP keys, DB passwords, etc...)  I do not see a way currently to pass this option in to the ECS TaskDefinition.  The syntax for the docker run command with this parameter looks like this:

```
docker run -ti --tmpfs /secrets:rw,noexec,nosuid,size=100m ubuntu:14.04 bash

```

**Comment by ceharris** [comment]
While the use of tmpfs mounts for secrets is also interesting, our main use case for this feature would be to allow containers running under ECS to more easily run in read-only mode; e.g. by mounting `tmpfs` filesystems on `/tmp`, `/var/run`, etc.

**Comment by Overbryd** [comment]
This would be highly appreciated!

I would like to run some containers **read only** and use **--tmpfs** to give them some read/write space they can use (it is ephermal data anyways). This would **substantially** lower the pressure on EBS io.

+1

**Comment by raygunsix** [comment]
+1

**Comment by rhuddleston** [comment]
+1 I would also like to run read only and need this to move forward with that

**Comment by cyrilchampier** [comment]
+1, nice to have

**Comment by ceharris** [comment]
Running containers with a read-only root filesystem is now part of the CIS benchmark, and thus it won't be long before organizations start insisting on having this Docker functionality when running on ECS.

**Comment by philenz** [comment]
+1 such a simple and effective security option to use read-only with tmpfs

**Comment by osiegmar** [comment]
+1

**Comment by nomnux** [comment]
+1

**Comment by Prendo93** [comment]
+1

**Comment by seren** [comment]
This would be useful for us as well

**Comment by jhmartin** [comment]
A specific use case for this is the storage of the [Varnish VSM file](https://varnish-cache.org/docs/trunk/reference/vsm.html), where Varnish is very sensitive to slowdowns in writes to this temporary file. Mounting this directory into tmpfs would insulate it against EBS latencies.

**Comment by piotrbulinski** [comment]
In some cases, it's sufficient with using /dev/shm (which is tmpfs and has 64M by default).

**Comment by jhmartin** [comment]
@piotrbulinski I looked at that, but unfortunately my Varnish VSM file is about 80MB.

**Comment by piotrbulinski** [comment]
@jhmartin indeed, in some cases it will not be enough. Unfortunately for you the --shm-size is not supported either (#787)...

**Comment by coen-hyde** [comment]
I don't like being just another +1 but this is essential for running readonly containers

**Comment by sdesalas** [comment]
FYI @jhmartin You can increase the size of `/dev/shm` if there is enough memory allocated to the container.

https://www.cyberciti.biz/tips/what-is-devshm-and-its-practical-usage.html

**Comment by kerryjj** [comment]
+1 to being able to use tmpfs in ecs and elasticbeanstalk

**Comment by bryjawink** [comment]
+1

**Comment by bruceharrison1984** [comment]
+1

**Comment by Htarlov** [comment]
+1

**Comment by jayaskren** [comment]
+1

**Comment by adam-arredondo** [comment]
+1

**Comment by asieira** [comment]
+1

**Comment by asieira** [comment]
Actually, `--tmpfs` [doesn't allow you to set options](https://docs.docker.com/engine/admin/volumes/tmpfs/). Ideally, we should be able to specify the tmpfs size and default file mode as per `--mount type=tmpfs`.

**Comment by gavinmh** [comment]
+1

**Comment by Stavanger75** [comment]
+1

**Comment by wangdrew** [comment]
+1

**Comment by robertbeal** [comment]
+1

**Comment by t0sche** [comment]
Would love to see this in ECS since it is supported in docker_containers

**Comment by samuelkarp** [comment]
A proposal for the implementation of tmpfs is available in https://github.com/aws/amazon-ecs-agent/pull/1149.

**Comment by aaithal** [comment]
Hello everyone, we announced support for `tmpfs` parameter in your task definition [today](https://aws.amazon.com/about-aws/whats-new/2018/03/amazon-ecs-adds-support-for-shm-size-and-tmpfs-parameters/)! Please refer to our [documentation](https://docs.aws.amazon.com/AmazonECS/latest/developerguide/task_definition_parameters.html#container_definition_linuxparameters) for more details. 

Closing this issue for now. Please let us know if you have any follow up comments/questions regarding this.

**Comment by jorrit** [comment]
I would like to comment that the docs should be updated to state that the unit for shmsize/tmpfs.Size is MB.

**Comment by sharanyad** [comment]
@jorrit Thanks for reporting. The [docs](https://docs.aws.amazon.com/AmazonECS/latest/APIReference/API_LinuxParameters.html) are updated now.

**Comment by jorrit** [comment]
Wonderful, thanks!
