### ISSUE TITLE
--pid=host support

### ISSUE THREAD

**Issue by marinusd** [aws/amazon-ecs-agent#473]
Related:  #185 

**Use case:**  
Resque workers identify themselves with a string made up of  ${hostname}:${pid}
This id string allows resque's management utility to present groups of workers-by-hostname, as well as selecting individual workers. The resque worker id is not externally configurable. 

When an ECS Service starts >1 resque workers (defined in a Task, obviously), there are two possibilities:
1.  The Task Definition specifies a container hostname, or
2.  The Task Definition does not specify a container hostname.

If 1., then all the containers have the same hostname, and (by virtue of starting as identical tasks) the same PID. Thus the resque worker id string is identical for all running tasks. This defeats the resque management utility's ability to select an individual worker, plus other undesirable effects.

If 2., then the containers get unique hostnames, and so the resque workers id strings are unique. But this defeats the resque management utility's ability to present groups of workers-by-hostname.

Supporting the _--pid=host_  Docker run option (to use the host's PID namespace vs. the container's PID namespace) will help restore the resque management utility's abilities.

**Comment by errordeveloper** [comment]
We need for Weave Scope. Another use-case would be Kubernetes on ECS. _(cc @bchav)

**Comment by bchav** [comment]
@errordeveloper: https://aws.amazon.com/about-aws/whats-new/2016/08/amazon-ec2-container-service-now-supports-networking-modes-and-memory-reservation/

**Comment by veqryn** [comment]
Another use case is infrastructure monitoring

**Comment by reedflinch** [comment]
@veqryn 👍 , would love to use this to implement Sysdig in ECS task definitions

**Comment by panga** [comment]
+1

**Comment by xrwang** [comment]
+1, this would be great to use for infrastructure monitoring

**Comment by lodotek** [comment]
+1

**Comment by bjbishop** [comment]
👍 @veqryn We really need this for installing Sysdig in ECS as well

**Comment by MarvGilb** [comment]
+1, for infrastructure monitoring like new relic.
[#502](https://github.com/aws/amazon-ecs-agent/issues/502) lists the parameter that ECS is missing.

**Comment by i-ghost** [comment]
This would be very useful to run the [Stackify](https://support.stackify.com/hc/en-us/articles/115000715203-Docker-Support) agent with! 👍

**Comment by joekiller** [comment]
Supporting this would allow datadog to use its psutil features like in https://github.com/DataDog/dd-agent/issues/2923

**Comment by PaulLiang1** [comment]
Almost two years. Another reason to ditch ECS.

**Comment by buybackoff** [comment]
Any update/ETA on this? Without this option I cannot use safely LMDB on instance storage from multiple containers from ECS. https://twitter.com/buybackoff/status/1013503236857368576

**Comment by nunofernandes** [comment]
+1
I would like to have a icinga/nagios running inside a container and lots of monitoring checks do need the proc namespace to be accessible..

**Comment by MoLow** [comment]
+++!

**Comment by MoLow** [comment]
The same as network mode is fine for my use case

**Comment by joekiller** [comment]
Task based toggle is likely sufficient but container based may be
necessary.

It depends on the agent's purpose. If the agent needs to talk over network
to processes in a task, ie query nginx stats, it needs networking to link
via task definition and pid=host for the agent container but I wouldn't
want the setting for the my whole task.

Contrarily, when using an agent to monitor tasks in an ubiquitous
environmental where that agent in the task will reconfigure on the fly
based on what else is running on that container host. The agent would
likely be its own task where the toggle on the task would be sufficient.

So if I had to pick one, container based toggle.

**Comment by xose** [comment]
Another vote for container-level setting, even though a task-level setting would also be "enough" for my current use case:

* All other security/isolation settings are configurable per-container (except networking)
* Least privilege: this is a setting you may not want all containers in a task to share.
* Simplicity: it's an advanced, rarely used setting for very specific use cases, unlike the settings that are now available at the task level (networking, memory, cpu). It would complicate the UI unnecessarily for most people.

**Comment by i-ghost** [comment]
Per-container would be ideal, but I can live with task level as a compromise.

**Comment by xose** [comment]
That looks like a good middle ground, it works for my use case. Just a couple questions:

* Which container's namespace will be joined when using `pid="task"`? That is, which container from a task definition will have a process with PID 1?
* Will there be a third option to keep the current behaviour of each container in a task having its own isolated PID namespace? Or will `pid="task"` become the default?

**Comment by arminc** [comment]
I like the proposed solution but had the same questions as @xose. 
If I understand correctly not setting the "pid=" option would mean the current behaviour while we get the option to set it with the two purposed solutions to change the default behaviour?  

Because loosing the isolation when you deploy a task witch has a primary container and a simpel side-car container where now the side-car container can access way to much information from the primary container would not be a good thing.

**Comment by sharanyad** [comment]
Thanks for your comments.
If the pid field is not set, it defaults to the current behavior where each container gets its own PID namespace. 
In the case of `pid=task`, are there use cases where you want a particular container to have PID=1?
There are two options that we are considering: 
- Have an internal empty container and run all the task’s containers in the internal container’s namespace.
- Run any one container in the task initially and start the remaining containers in the first container’s namespace. If there are “links” and “volumesFrom” dependencies, those will be taken into consideration while choosing the base container for the pid namespace.

**Comment by joekiller** [comment]
If I had to choose, both of course 😄  Run an empty container and launch with consideration to links and volumes. perhaps otherwise just launch in order of the the container definitions.

**Comment by wmitsuda** [comment]
This is needed to run prometheus node_exporter on ECS, for example: https://github.com/prometheus/node_exporter#using-docker

**Comment by boynux** [comment]
+1

**Comment by cnelson** [comment]
+1

**Comment by ashmastaflash** [comment]
+1

**Comment by charlieoleary** [comment]
Support was added for `--pid` with the release of 1.22.0! 🎉 It appears that adding `"pidMode": "host"` to your container definition will enable the functionality.

**Comment by ashmastaflash** [comment]
Thanks @charlieoleary, that's great news!

**Comment by linkar-ec2** [comment]
Hi all,

Closing this issue.
Amazon ECS now supports an `pidMode` (as well as `ipcMode`) option as a parameter for ECS Task Definitions. You can now add `host` or `task` as `pidMode` options. Please see the latest [announcement](https://aws.amazon.com/about-aws/whats-new/2018/10/amazon-ecs-now-allows-two-additional-docker-flags-/) and the AWS [Docs](https://docs.aws.amazon.com/AmazonECS/latest/developerguide/task_definition_parameters.html#other_task_definition_params) for more information. Please reach out to us for any questions/comments/clarifications.

Thanks,
Kar Shin
