### ISSUE TITLE
Option to select multiple log-configuration

### ISSUE THREAD

**Issue by soumyasmruti** [aws/amazon-ecs-agent#480]
There should be an option to add multiple log configuration in Task Definition. For ex., I should be able to select both 'json-file' and 'awslogs' in my log configuration.

**Comment by samuelkarp** [comment]
@soumyasmruti This behavior isn't supported by Docker; each container has exactly one logging driver.  What problem are you trying to solve by using multiple logging drivers?

**Comment by soumyasmruti** [comment]
The problem is I am sending logs to cloudwatch but I also want to access it via docker logs which supports json-file format. Any idea how is it possible?

**Comment by samuelkarp** [comment]
`docker logs` is not supported by the `awslogs` logging driver today, but that's a reasonable feature request.  Today, an easy way to view/follow the logs in CloudWatch Logs is to use the [CloudWatch Logs CLI Plugin](https://blogs.aws.amazon.com/application-management/post/Tx2TS68UQ3HUVAH/Monitor-Website-Latency-using-CloudWatch-Logs-CLI-Plugin), which will let you run something like `aws logs pull --follow --log-group $LOG_GROUP --log-stream-name $LOG_STREAM_NAME` (note that the log stream name is the Docker container ID by default).

**Comment by blaines** [comment]
@samuelkarp oh that's a useful tip. Perhaps it can be published somewhere more visible!

**Comment by samuelkarp** [comment]
I'm going to close this since this is not supported by Docker.  If this feature gets added to Docker we can look at adding support for it in ECS as well.
