### ISSUE TITLE
Support RestartPolicy

### ISSUE THREAD

**Issue by hasimo** [aws/amazon-ecs-agent#493]
I would like to run a specific container on every container instance.
[ECS Document](http://docs.aws.amazon.com/AmazonECS/latest/developerguide/start_task_at_launch.html) recommend me to use `start-task` API because .
But when the task stopped , It has never come back. 
I would like to restart and keep running it.
Currently Docker has `RestartPolicy` to restart a container.
It would be good to support docker's `RestartPolicy`

**Comment by samuelkarp** [comment]
@hasimo You can restart failed tasks in your cluster by using [services](http://docs.aws.amazon.com/AmazonECS/latest/developerguide/ecs_services.html).  If you're looking to run a task per-instance in your cluster, https://github.com/aws/amazon-ecs-agent/issues/159 captures that feature request.
