### ISSUE TITLE
Cannot update service after changing container name in task definition

### ISSUE THREAD

**Issue by matl33t** [aws/amazon-ecs-agent#497]
Ran into a problem where I couldn't update a service with a new task definition revision that had changed the name of a container. I'm assuming the service needed to do some bookkeeping on tasks running the older revision, but no longer could find their containers since it was trying to look for the new container name.

The solution was to just recreate the service with the new task definition revision, but it wasn't ideal.

**Comment by samuelkarp** [comment]
@matl33t Did your service have a load balancer configured?  ECS uses the container name in the load balancer configuration to determine which container needs to be bound to the load balancer.  See [the documentation](http://docs.aws.amazon.com/AmazonECS/latest/developerguide/service-load-balancing.html):

> After you create a service, the target group ARN or load balancer name, container name, and container port specified in the service definition are immutable. You cannot add, remove, or change the load balancer configuration of an existing service. If you update the task definition for the service, the container name and container port that were specified when the service was created must remain in the task definition.

**Comment by matl33t** [comment]
Thanks for the quick response, @samuelkarp! We did have an ELB configured for that service so that seems to have been the problem.
