### ISSUE TITLE
rebalance running service tasks across instances

### ISSUE THREAD

**Issue by pahud** [aws/amazon-ecs-agent#503]
Hello,

If I have single ECS instance running a service with desired number of tasks set to '2', registering themselves to ALB, it works fine.  But when I add additional ECS instance to this cluster, the running 2 tasks in steady state will not "re-balance" the service across the existing two instances.

For HA reason I'd create a feature request to have ecs-agent rebalance them in this relative scenario.

thanks

**Comment by CpuID** [comment]
Related: https://github.com/aws/amazon-ecs-agent/issues/225

**Comment by samuelkarp** [comment]
Thanks! #225 is already tracking the rebalance feature request, so I'm closing this as a duplicate.
