### ISSUE TITLE
Access ECS repository from external account

### ISSUE THREAD

**Issue by politrons** [aws/amazon-ecs-agent#508]
I´m using ECS repository for two accounts, one for non_prod another for prod. The repo is part of the non_prod account

The problem that I found is, even giving access from the non_prod account repository to the prod account, the prod account cannot pull the docker image. And complains that the docker image does not exist.

Still I can access to the repository, but not pull the image since the prod account think, that does not exist

Obviously the image exist since it´s used in the non_prod environment. Also I compare the ~/.docker/config.json credentials and are the same to connect to the ECS repo that I have on the non_prod account.

I even try the temporally dangerous give all access in the repo and still nothing. I can even pull from my local computer but still the other account nothing!. It´s able to push but not to pull

 Any idea what´s wrong here?

Regards.

**Comment by samuelkarp** [comment]
@politrons Are you using ECS too or just ECR?

Documentation on sharing a repository with another account is [here](http://docs.aws.amazon.com/AmazonECR/latest/userguide/RepositoryPolicyExamples.html#IAM_allow_other_accounts).  When you pull from the second account, you'll need to run [`aws ecr get-login --registry-ids $FIRST_ACCOUNT_AWS_ACCOUNT_ID`](http://docs.aws.amazon.com/AmazonECR/latest/userguide/ECR_AWSCLI.html#AWSCLI_get-login) to get the credentials Docker needs.

If you're using ECS, the ECS agent should take care of getting the necessary credentials for you.

**Comment by samuelkarp** [comment]
@politrons I'm closing this since we haven't heard from you in a while.  Please feel free to re-open if you have further questions.
