### ISSUE TITLE
Enable credentials endpoint for ecs task role?

### ISSUE THREAD

**Issue by jamesongithub** [aws/amazon-ecs-agent#511]
Seem to be having problems with getting credentials from ecs-agent within the container. The route doesn't seem to be available.
```
curl 169.254.170.2:80/v1/credentials?id=38efbb6f-7511-4ab5-9047-0fe02c619f49
{"AvailableCommands":["/v1/metadata","/v1/tasks","/license"]}
```

```
curl 169.254.170.2/v1/metadata 
{"Cluster":"sandbox-ecs","ContainerInstanceArn":"arn:aws:ecs:us-east-1:REDACATED:container-instance/0acd679c-fa32-41f9-be28-440dd07d32f7","Version":"Amazon ECS Agent - v1.12.1 (d5e8c51)"}
```

ecs-agent env
```
            "Env": [
                "ECS_DISABLE_PRIVILEGED=true",
                "ECS_ENGINE_TASK_CLEANUP_WAIT_DURATION=1m",
                "ECS_DISABLE_METRICS=false",
                "ECS_APPARMOR_CAPABLE=true",
                "ECS_DOCKER_GRAPHPATH=REDACTED",
                "ECS_CLUSTER=REDACTED",
                "ECS_ENABLE_TASK_IAM_ROLE_NETWORK_HOST=true",
                "ECS_AVAILABLE_LOGGING_DRIVERS=REDACTED,
                "ECS_ENABLE_TASK_IAM_ROLE=true",
                "ECS_DATADIR=/data",
                "ECS_LOGFILE=/log/ecs-agent.log",
                "ECS_LOG_LEVEL=debug",
                "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
            ],
```

Is there anything else needed to enable ecs iam roles for ecs agent?

**Comment by jamesongithub** [comment]
Btw, is there anyway to add custom fields to the credentials payload?

**Comment by samuelkarp** [comment]
@jamesongithub Are you using the ECS-optimized AMI or did you manually install the ECS agent?  It looks like the `iptables` rules might be set up somewhat wrong on your instance (looks like they're forwarding to 51678 instead of 51679).

**Comment by jamesongithub** [comment]
This is on ubuntu. Actually I thought the instructions was incorrect [here](http://docs.aws.amazon.com/AmazonECS/latest/developerguide/task-iam-roles.html) so used 51678 like from the [README](https://github.com/aws/amazon-ecs-agent#on-other-amis.). I actually have nothing listening on 51679, so it wasn't working.

**Comment by samuelkarp** [comment]
The agent should be listening on 51679 as well; that's the credential endpoint.  I'll make a note to update the README; the most up-to-date instructions on launching the agent on Ubuntu are in [our documentation](http://docs.aws.amazon.com/AmazonECS/latest/developerguide/ecs-agent-install.html).

**Comment by jamesongithub** [comment]
Ah, that makes sense. Thanks for the quick response. Anyway to add custom fields to the creds response btw?

**Comment by samuelkarp** [comment]
No, the credential endpoint only returns credentials.  What kinds of custom things are you looking for it to return?

**Comment by jamesongithub** [comment]
Other secrets that we would like to pass instead of having them show up as envs in the aws ecs console.

**Comment by samuelkarp** [comment]
@jamesongithub That sounds pretty similar to https://github.com/aws/amazon-ecs-agent/issues/328.  @aaithal's suggestion on that issue is a good approach.

I've also opened https://github.com/aws/amazon-ecs-agent/pull/512 to update the README.  Thanks for catching the errors!

**Comment by jamesongithub** [comment]
yup. thanks!

**Comment by hltbra** [comment]
@samuelkarp, @aaithal: I am having the same issue and I have logs. Should I open a ticket? I'd appreciate if you can help me debug this, but I don't want to leave my broken container error'ing out for much longer. My work email is hugo at yipitdata.com

I am running the latest agent (ECS-optimized AMI ami-04351e12).

Thanks

**Comment by aaithal** [comment]
@hltbra I'm sorry that you're running into this issue. Please create a new github issue or a support case via the AWS Developer Support program. Thanks!

**Comment by hltbra** [comment]
@aaithal: cool. I created an AWS Support ticket with logs from my application and the ECS agent (case ID 4260162261).
