### ISSUE TITLE
Request: Surface Agent Disconnect in a friendly manner

### ISSUE THREAD

**Issue by miketheman** [aws/amazon-ecs-agent#520]
Hello!

Y'all probably have a faster line to CloudWatch than I do. :)

What I'm looking for is a mechanism by which to detect that an ECS Container Instance has gone to `false` - i.e. `agentConnected: False` in some manner that is presented by CloudWatch metrics/alarms.

This creates the likely scenario that the instance in an unhealthy state, and without some automated way to detect the problem, we end up doing some manual inspections and terminating instances for ASG to replace.

If someone else has already solved this, I'd love to hear about it.

**Comment by kiranmeduri** [comment]
Thanks for the feedback, we will track this as a feature request.

**Comment by thehydroimpulse** [comment]
@miketheman We currently have a service that periodically pulls from the ECS API and sends metrics about the agent to Datadog.

<img width="993" alt="screenshot 2016-09-19 16 21 23" src="https://cloud.githubusercontent.com/assets/565790/18652176/296fb8c2-7e85-11e6-9b53-ab8915a05a23.png">

We use Datadog to trigger alerts whenever an agent has disconnected.

**Comment by miketheman** [comment]
@thehydroimpulse Would you be able to share such a service?

**Comment by aaithal** [comment]
@miketheman We recently announced the ECS Event Stream support for CloudWatch Events, which you can use to keep track of container instance states that are interesting for yo, including ECS Agent connects and disconnects. Closing this issue for now. Please feel free to reopen, create a new one if you want to discuss this more. For more information please see [the documentation](http://docs.aws.amazon.com/AmazonECS/latest/developerguide/cloudwatch_event_stream.html).

**Comment by miketheman** [comment]
@aaithal Thanks! I would still really love to see what @thehydroimpulse came up with.
