### ISSUE TITLE
Can't authenticate with Docker Hub

### ISSUE THREAD

**Issue by jeprojects** [aws/amazon-ecs-agent#53]
I am getting this error in the ecs agent log:

t=2015-04-17T06:11:53+0000 lvl=eror msg="Unrecognized AuthType type" module="docker auth" type="dockercfg\r"

Here is my ecs.config

ECS_ENGINE_AUTH_TYPE=dockercfg
ECS_ENGINE_AUTH_DATA={"https://index.docker.io/v1/":{"auth":"xxxx","email":"xxx@xxx.com"}}

Running this AMI: amzn-ami-2015.03.a-amazon-ecs-optimized (ami-ecd5e884)

**Comment by euank** [comment]
The '\r' in that message makes it sound like you have windows-style line endings (CRLF) in your config file. Mind running `tr -d "\r" < ecs.config > ecs.config` or re-creating the file in an editor that doesn't add \r characters and then running `sudo stop ecs && sudo start ecs` to reload the config?

**Comment by jeprojects** [comment]
That worked! Thanks!

**Comment by euank** [comment]
Glad that worked!
In the hopes to avoid such confusion in the future, I created a pull-request to trim whitespace from that value (see #54)
Best,
Euan
