### ISSUE TITLE
Token missing in AWS_CONTAINER_CREDENTIALS_RELATIVE_URI

### ISSUE THREAD

**Issue by jamesongithub** [aws/amazon-ecs-agent#531]
The payload seems to be missing the Token property from as shown here:

http://docs.aws.amazon.com/AmazonECS/latest/developerguide/task-iam-roles.html

```
curl 169.254.170.2$AWS_CONTAINER_CREDENTIALS_RELATIVE_URI
{"RoleArn":"arn:aws:iam::REDACTED:role/REDACTED","AccessKeyId":"REDACTED","SecretAccessKey":"REDACTED","Expiration":"2016-09-16T08:05:02Z"}
```

Are we missing additional configuration?

```
docker v1.12.1
ecs-agent v1.12.1
```

Token seems to be need for the aws node sdk.

```
    "originalError": {
      "message": "Response data is not in valid format",
      "code": "ECSCredentialsProviderFailure",
      "time": "2016-09-16T02:03:15.555Z"
    }
```

**Comment by aaithal** [comment]
@jamesongithub It doesn't seem like you're missing any configuration here. I just launched a new task on Agent v1.12.1 and verified that the `Token` field is present in the response from the credentials endpoint:

```
curl --silent 169.254.170.2$AWS_CONTAINER_CREDENTIALS_RELATIVE_URI | jq -r '.'
{
  "RoleArn": "arn:aws:iam:: REDACTED:role/REDACTED",
  "AccessKeyId": "REDACTED",
  "SecretAccessKey": "REDACTED",
  "Token": "REDACTED",
  "Expiration": "2016-09-16T21:18:29Z"
}

$ curl --silent localhost:51678/v1/metadata | jq -r '.'
{
  "Cluster": "REDACTED",
  "ContainerInstanceArn": "arn:aws:ecs:us-west-2:REDACTED:container-instance/REDACTED",
  "Version": "Amazon ECS Agent - v1.12.1 (d5e8c51)"
}
```

We'd need some additional information to diagnose what's going wrong on your instance. I'd also strongly recommend that you engage us via AWS Support as this relates to AWS Credentials. It'd be great if you could provide the following information as well when you do that:

1. Container Instance Arn
2. Cluster Arn/Name
3. ECS Agent Logs
4. Frequency of the issue (How often are you seeing this error)

Feel free to also email these details to aithal at amazon dot com.

Thanks,
Anirudh

**Comment by jamesongithub** [comment]
Hi @aaithal,

I think ecs task roles don't work with inline polices for at least the node sdk. The cli's seem to be working. They both seem to be working with managed policies, though. Is that the case? Seems strange.

**Comment by richardpen** [comment]
@jamesongithub Can you briefly tell us what happened when you use the node sdk with task iam credentials that has inline policy attached? As I did some test, seems it works, the program will work if I attach the inline policy below to the task iam role, and it won't work if I remove the inline policy from the iam role:

Here is the program I used to test(run.js):
```
var AWS = require('aws-sdk');

AWS.config.update({region: 'us-west-1'});

var ecs = new AWS.ECS();
var params = {
};
ecs.listClusters(params, function(err, data) {
	if (err) console.log(err, err.stack);
	else console.log(data);
});
```

The task iam role policy I used:
```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Sid": "",
            "Action": [
                "ecs:ListClusters"
            ],
            "Effect": "Allow",
            "Resource": "*"
        }
    ]
}
```

The task definition I used: 
```
{
    "family": "iamrole-test",
    "taskRoleArn": "arn:aws:iam::xxxxxxxx:role/test-iam",
    "containerDefinitions": [{
        "memory": 100,
        "cpu": 100,
        "name": "container-with-iamrole",
        "image": "xxxxxxx",
        "command": ["nodejs", "/run.js"]
    }]
}

```

**Comment by kiranmeduri** [comment]
Also make sure that appropriate trust-relationship is setup when using IAM roles with ECS tasks. More on it here http://docs.aws.amazon.com/AmazonECS/latest/developerguide/task_IAM_role.html

-kiran

**Comment by jamesongithub** [comment]
Hi,

Thanks. After further debugging, it looks like the error is on our end. Thanks! Both inline and manged policies work now.
