### ISSUE TITLE
mail is not working from docker

### ISSUE THREAD

**Issue by mkaja** [aws/amazon-ecs-agent#533]
error sending mail: failed to send data [smtp: invalid response code received from server (code: 554, response: message rejected: email address is not verified. the following identities failed the check in region us-west-2

we have a wiki in a docker running inside ec2 and and when we reset passwd from wiki its saying above error

**Comment by OscarBarrett** [comment]
This is not an ECS issue. When using Amazon SES in any context, you need to verify both the domain and the email address that you want to send from. In addition you need to make sure your configuration uses the correct region.

If your account is still in the SES sandbox, then you will also need to verify the email address of every recipient that you wish to send to.

See https://docs.aws.amazon.com/ses/latest/DeveloperGuide/verify-email-addresses.html

**Comment by mkaja** [comment]
thanks Oscar- I verified my email address in us-east region .. i checked the postfix config also ..from command line i can send email from the container to my outlook. but when we reset passwd on wiki(web page) - we are getting above error.

do i need to verify domain also like our comp example.com ?

**Comment by mkaja** [comment]
/etc/postfix/main.cf
# is /etc/mailname.
#myorigin = /etc/mailname

smtpd_banner = $myhostname ESMTP $mail_name (Ubuntu)
biff = no

# appending .domain is the MUA's job.
append_dot_mydomain = no

# Uncomment the next line to generate "delayed mail" warnings
#delay_warning_time = 4h

readme_directory = no

# TLS parameters
smtpd_tls_cert_file=/etc/ssl/certs/ssl-cert-snakeoil.pem
smtpd_tls_key_file=/etc/ssl/private/ssl-cert-snakeoil.key
smtpd_use_tls=yes
smtpd_tls_session_cache_database = btree:${data_directory}/smtpd_scache
smtp_tls_session_cache_database = btree:${data_directory}/smtp_scache

# See /usr/share/doc/postfix/TLS_README.gz in the postfix-doc package for
# information on enabling SSL in the smtp client.

smtpd_relay_restrictions = permit_mynetworks permit_sasl_authenticated defer_unauth_destination
myhostname = container-id
alias_maps = hash:/etc/aliases
alias_database = hash:/etc/aliases
mydestination = container-id, localhost.localdomain, , localhost
#relayhost =
mynetworks = 127.0.0.0/8 [::ffff:127.0.0.0]/104 [::1]/128
mailbox_size_limit = 0
recipient_delimiter = +
#inet_interfaces = all
inet_interfaces = localhost
inet_protocols = all

relayhost = [email-smtp.us-east-1.amazonaws.com]:25
smtp_sasl_auth_enable = yes
smtp_sasl_security_options = noanonymous
smtp_sasl_password_maps = hash:/etc/postfix/sasl_passwd
smtp_use_tls = yes
smtp_tls_security_level = encrypt

**Comment by OscarBarrett** [comment]
>from command line i can send email from the container to my outlook. but when we reset passwd on wiki(web page) - we are getting above error.

It sounds like your FROM email and your own email address (outlook) has been verified, but that the recipient for the password reset email is not. 

If that is the case, you can manually verify the recipients for these password reset emails. But I would recommend moving out of the sandbox so that you don't need to verify recipients. https://docs.aws.amazon.com/ses/latest/DeveloperGuide/request-production-access.html

The two links that I have provided should contain enough information to help you resolve this issue.
