### ISSUE TITLE
Run task failed

### ISSUE THREAD

**Issue by DorrinPk** [aws/amazon-ecs-agent#535]
When I run my task with `syslog` or `awslogs` as logging options, I don't get any errors and it works just fine. 

But when I change it to 'flunetd', I get : `Run task failed. Reasons : ["ATTRIBUTE"]`

I'm using the ECS AMI and the docker version is `1.11.2`

**Comment by aaithal** [comment]
@DorrinPk The `fluentd` logging driver is not enabled by default on the ECS AMI. You'd have to [configure it via `userdata`](https://github.com/aws/amazon-ecs-agent/issues/454#issuecomment-232812017) if launching a new instance or manually login to the instance and [edit the ECS Agent Config File and restart the Agent](http://docs.aws.amazon.com/AmazonECS/latest/developerguide/ecs-agent-config.html) so that the Agent registers itself with this capability.

**Comment by DorrinPk** [comment]
I still get the same error after manually updating my userdata and updating the agents from the console. 

I thought the point of using the drop down and choosing fluentd is to not have to play around with userdata. I don't have to edit the userdata for syslog or awslogs?

**Comment by aaithal** [comment]
@DorrinPk can you please paste the userdata string that you're using? 

> I thought the point of using the drop down and choosing fluentd is to not have to play around with userdata. I don't have to edit the userdata for syslog or awslogs?

When you create the task definition, you add constraints on the task, one which is needing `fluentd` logging driver. By default, if using the ECS Optimized AMI, the [ECS Agent is registered with `json-file`, `syslog` and `awslogs`](https://github.com/aws/amazon-ecs-init/blob/d7982479b966474e9820871617bad00ce56dc850/ecs-init/docker/docker.go#L146) logging drivers. We have had other feature requests (#454) for enabling other logging drivers by default. We are still [debating about how to approach that issue](https://github.com/aws/amazon-ecs-agent/issues/454#issuecomment-248339851).

**Comment by DorrinPk** [comment]
@aaithal : the userdata is : `ECS_AVAILABLE_LOGGING_DRIVERS='["awslogs","fluentd"]'` 

and I am using the ECS AMI.

**Comment by DorrinPk** [comment]
@aaithal : I also see this in my event logs: 

`service xxxx was unable to place a task because no container instance met all of its requirements. The closest matching container-instance xxxxxxxxx is missing an attribute required by your task. For more information, see the Troubleshooting section.`

**Comment by aaithal** [comment]
@DorrinPk can you please paste the relevant part of your user-data script (including the `#!/bin/bash` directive and the part where you are overriding the `ecs.config` file)? You can also email the container instance arn/ec2 instance id and the region where you're launching this to aithal at amazon dot com. I suspect there's an issue in creating the config file that's leading to this. Here are the steps that I followed to register my container instance with `fluentd` logging driver:

 * Launch an ECS Instance with user-data:
```
#!/bin/bash
echo ECS_LOGLEVEL=debug >> /etc/ecs/ecs.config
echo ECS_AVAILABLE_LOGGING_DRIVERS='["awslogs","fluentd"]' >> /etc/ecs/ecs.config
```

 * Login to the instance and verify that the `ecs.config` file is properly configured:
```
$ cat /etc/ecs/ecs.config
ECS_LOGLEVEL=debug
ECS_AVAILABLE_LOGGING_DRIVERS=["awslogs","fluentd"]
```

 * Describe the instance to verify that it's been registered with the `fluentd` capability:
```
$ aws ecs describe-container-instances --container-instance xxx --query 'containerInstances[0].attributes'
[
    {
        "name": "com.amazonaws.ecs.capability.privileged-container"
    },
    {
        "name": "com.amazonaws.ecs.capability.docker-remote-api.1.17"
    },
    {
        "name": "com.amazonaws.ecs.capability.docker-remote-api.1.18"
    },
    {
        "name": "com.amazonaws.ecs.capability.docker-remote-api.1.19"
    },
    {
        "name": "com.amazonaws.ecs.capability.docker-remote-api.1.20"
    },
    {
        "name": "com.amazonaws.ecs.capability.docker-remote-api.1.21"
    },
    {
        "name": "com.amazonaws.ecs.capability.docker-remote-api.1.22"
    },
    {
        "name": "com.amazonaws.ecs.capability.logging-driver.awslogs"
    },
    {
        "name": "com.amazonaws.ecs.capability.logging-driver.fluentd"
    },
    {
        "name": "com.amazonaws.ecs.capability.ecr-auth"
    },
    {
        "name": "com.amazonaws.ecs.capability.task-iam-role"
    },
    {
        "name": "com.amazonaws.ecs.capability.task-iam-role-network-host"
    }
]
```

**Comment by DorrinPk** [comment]
Yes, once the fluentd driver is specified in ecs config and the fluentd is installed as a service, it works.
