### ISSUE TITLE
Failure from trying to pull during a already-full disk

### ISSUE THREAD

**Issue by miketheman** [aws/amazon-ecs-agent#536]
We recently had an issue where the deployment of a new image triggered the behavior of filling the `DOCKER_TMPDIR` location and exhausting all root disk space.

An example instance's root drive filling up:
![image](https://cloud.githubusercontent.com/assets/529516/18688178/2e2615ec-7f51-11e6-942a-28c22ca6a8df.png)

<details>

``` shellsession
Last login: Wed Sep  7 18:50:24 2016 from ip-bastion-host.ec2.internal

   __|  __|  __|
   _|  (   \__ \   Amazon ECS-Optimized Amazon Linux AMI 2016.03.h
 ____|\___|____/

For documentation visit, http://aws.amazon.com/documentation/ecs
4 package(s) needed for security, out of 5 available
Run "sudo yum update" to apply all updates.
[ec2-user@ip-10-my-ip-address ~]$ uname -a
Linux ip-10-my-ip-address 4.4.16-27.56.amzn1.x86_64 #1 SMP Fri Aug 12 23:25:10 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
[ec2-user@ip-10-my-ip-address ~]$ df -h
Filesystem      Size  Used Avail Use% Mounted on
/dev/xvda1      7.8G  7.8G     0 100% /
devtmpfs        7.9G   88K  7.9G   1% /dev
tmpfs           7.9G     0  7.9G   0% /dev/shm
[ec2-user@ip-10-my-ip-address ~]$ docker version
Client:
 Version:      1.11.2
 API version:  1.23
 Go version:   go1.5.3
 Git commit:   b9f10c9/1.11.2
 Built:
 OS/Arch:      linux/amd64

Server:
 Version:      1.11.2
 API version:  1.23
 Go version:   go1.5.3
 Git commit:   b9f10c9/1.11.2
 Built:
 OS/Arch:      linux/amd64
[ec2-user@ip-10-my-ip-address ~]$ sudo du -sh /var/lib/docker/tmp/
6.3G    /var/lib/docker/tmp/
[ec2-user@ip-10-my-ip-address ~]$ sudo ls -lh /var/lib/docker/tmp/ | head -n 5
total 6.3G
-rw------- 1 root root 20M Sep 19 21:11 GetImageBlob001689579
-rw------- 1 root root 20M Sep 19 21:31 GetImageBlob001718338
-rw------- 1 root root 20M Sep 19 21:50 GetImageBlob003316514
-rw------- 1 root root 20M Sep 19 21:23 GetImageBlob003594682

/var/log/messages:
Sep 19 22:30:52 ip-10-my-ip-address lvm[2490]: Insufficient free space: 1114 extents needed, but only 51 available
Sep 19 22:30:52 ip-10-my-ip-address lvm[2490]: Failed to extend thin docker-docker--pool.
Sep 19 22:31:02 ip-10-my-ip-address lvm[2490]: Thin docker-docker--pool is now 90% full.

/var/log/ecs/ecs-agent.log:
CannotPullContainerError: failed to register layer: devmapper: Thin Pool has 4446 free data blocks which is less than minimum required 4454 free data blocks. Create more free space in thin pool or use dm.min_free_space option to change behavior
```

</details>
We had since terminated the instances, and I missed collecting the output of `vgs` - if this is critical, please let me know - we will likely hit this within 3 weeks (our deploy velocity is the trigger here).

We are aware that this is likely due to us not cleaning up after ourselves periodically (an oft-requested feature, ref #118, #499), but maintain that the behavior of filling up the temporary directory, and effectively killing the host is not the right solution.

We will try to be proactive in monitoring the Volume Group's size in the future as well as implement a stopgap until a cleanup feature is released.

I don't know if the failure condition of filling up `DOCKER_TMPDIR` is a limitation of Docker, or of how the ECS Agent reacts to a full-disk situation, but either lead to a **Sad Day**, where the instance health isn't actually marked as unhealthy, so ASG won't replace it for us.

If you need any further diagnosis information, please let me know and I'll try to provide what I can.

**Comment by aaithal** [comment]
@miketheman thanks for reporting this. Unfortunately, the ECS Agent does not keep track of this information on the instance today and you'd have to setup custom Cloudwatch alarms to trigger ASG activities when utilization breaches a threshold.

However, we are working on the [automated image cleanup PR](https://github.com/aws/amazon-ecs-agent/pull/499), which should help solve some of the issues here. We are also tracking another feature request in #483, of accounting for free disk space available on the instance.

I'll add a reference to this use-case for both of those issues. 

Thanks,
Anirudh

**Comment by miketheman** [comment]
Hi @aaithal !

I'm sorry if I wasn't very clear with the problem.

I understand that we didn't clean up the space, and that we don't have a great way to monitor that right now.

The problem I was trying to surface is that the agent behavior under these conditions is a faulty one - filling up the root disk device in `DOCKER_TMPDIR` instead of failing, stopping trying to pull, emit some event - is **really bad** behavior.

Is that any clearer?

**Comment by samuelkarp** [comment]
@miketheman Thanks, that explanation definitely helps.  A few things I noticed:

* The error that you're actually seeing is relating to extending the devicemapper thin pool.  The thin pool is on the second block device, attached at `/dev/xvdcz`, rather than the root device.  While it does appear that `DOCKER_TMPDIR` might be an issue given that your root device is full, that might be unrelated (or only partially related) to the thin pool error you see.
* As @aaithal mentioned, we were working on automated image cleanup, which launched as part of version 1.13.0.  Since the error in your logs is related to thin pool size, image cleanup will likely help you avoid filling up the thin pool.  Can you try 1.13.1 (the latest version today) and see if this helps improve the situation?

Also to answer one of your questions:

> I don't know if the failure condition of filling up `DOCKER_TMPDIR` is a limitation of Docker, or of how the ECS Agent reacts to a full-disk situation [...]

`DOCKER_TMPDIR` is part of how Docker pulls images and is not specifically related to ECS.  If I had to guess at what happened here, your thin pool ran out of space, then Docker couldn't move data from `DOCKER_TMPDIR` to the thin pool and eventually ran of space on your root volume as well as it continued attempting to pull layers.

**Comment by miketheman** [comment]
Hi @samuelkarp ! Thanks for your detailed follow up.

My point is that if the ecs-agent is the actor triggering a `docker pull`, and the TMPDIR is full and cannot move it to the thin pool, at some point it should stop trying to pull in a known failed state.

**Comment by samuelkarp** [comment]
@miketheman It sounds like this is no longer an issue for you right now (hopefully the image cleanup feature is helping) so I'll go head and close this now.

> My point is that if the ecs-agent is the actor triggering a `docker pull`, and the TMPDIR is full and cannot move it to the thin pool, at some point it should stop trying to pull in a known failed state.

Yes, I think that's sensible.  We're using https://github.com/aws/amazon-ecs-agent/issues/483 to track enhancements around accounting for free disk space on the instances and how ECS should behave when that happens.  I've added a note from our discussion here to make sure we account for this situation when we start addressing that area.
