### ISSUE TITLE
Mailing List for new releases

### ISSUE THREAD

**Issue by jamesongithub** [aws/amazon-ecs-agent#538]
Is there a mailing list to subscribe for new release?

**Comment by aaithal** [comment]
@jamesongithub we don't have an official mailing list for publishing new releases. Github notifications for the project could be a mechanism for doing that.

**Comment by samuelkarp** [comment]
@jamesongithub @aaithal GitHub provides an Atom feed of releases: https://github.com/aws/amazon-ecs-agent/releases.atom

**Comment by aaithal** [comment]
@jamesongithub Closing this for now. Feel free to reach out to us if you have any other questions/comments.

Thanks,
Anirudh

**Comment by jamesongithub** [comment]
thx
