### ISSUE TITLE
Won't get image from dockerhub (when using a private repo)

### ISSUE THREAD

**Issue by jeprojects** [aws/amazon-ecs-agent#55]
Authentication seems to happen ok (no error in the logs)

But when it goes to get the image, it can't find it.

time="2015-04-17T08:30:54Z" level="info" msg="+job pull(xx/xx, latest)"
time="2015-04-17T08:30:54Z" level="info" msg="+job resolve_repository(xx/xx)"
time="2015-04-17T08:30:54Z" level="info" msg="-job resolve_repository(xx/xx) = OK (0)"
Error: image xx/xx:latest not found
time="2015-04-17T08:30:55Z" level="info" msg="-job pull(xx/xx, latest) = ERR (1)"

If I set the repo to public, it gets the image fine and the docker is deployed.

**Comment by euank** [comment]
The docker daemon doesn't log anything related to authentication I believe, so those logs won't have anything interesting. I need more information on the issue you're hitting since I'm unable to reproduce this.

Can you verify the agent logs do not contain anything from the 'docker auth' module (grepping that string might be helpful)? Can you also check for anything else at 'EROR' level?
Can you `docker inspect` the agent's container and verify the two environment variables look correct in that output?

**Comment by jeprojects** [comment]
The only error in the ecs log is:

t=2015-04-17T08:45:02+0000 lvl=eror msg="Error getting message from acs" module="acs client" err=EOF stack="[github.com/aws/amazon-ecs-agent/agent/acs/client/acs_client.go:178 github.com/aws/amazon-ecs-agent/agent/acs/handler/acs_handler.go:68

The is nothing about auth either.

docker inspect reproduces the same error in the docker log file as the one posted here.

When i run "docker run -d -p 4001:4444 xxx/xxx manually I get his error:

Unable to find image 'xxx/xxx:latest' locally
Pulling repository xxx/xxx
FATA[0000] Error: image xxx/xxx:latest not found

Which to me would say it isn't authenticating?

**Comment by jeprojects** [comment]
Here is the ecs.config on the EC2 ECS instance (/etc/ecs/ecs.config):

ECS_ENGINE_AUTH_TYPE=docker
ECS_ENGINE_AUTH_DATA={"https://index.docker.io/v1":{"username":"xxx","password":"xxx","email":"xxx"}}

**Comment by wgorder** [comment]
I am having issues getting it to pull from a private repo as well.  I am getting this though:
```
lvl=eror msg="Error decoding auth configuration" module="docker auth" err="The Auth config file is empty" type=dockercfg host=https://index.docker.io/v1/
```

Also I am using the dockercfg mode of authentication.

**Comment by jeprojects** [comment]
Ok I got it working.

AWS I suggest you correct the documentation at this URL:

http://docs.aws.amazon.com/AmazonECS/latest/developerguide/private-auth.html

Here:
ECS_ENGINE_AUTH_TYPE=docker
ECS_ENGINE_AUTH_DATA={"https://index.docker.io/v1/user":{"username":"my_name","password":"my_password","email":"email@example.com"}}

It should be:

ECS_ENGINE_AUTH_TYPE=docker
ECS_ENGINE_AUTH_DATA={"https://index.docker.io/v1/":{"username":"my_name","password":"my_password","email":"email@example.com"}}

(The docker.io url was wrong, you need to remove the user)

**Comment by euank** [comment]
@jeprojects Glad you got it working. I'll pass that information about the docs along. Thanks!

@wgorder That (admittedly confusing) error means that your auth value was probably not recognized as valid json. If you `docker inspect` the agent, does its value appear correct?

**Comment by wgorder** [comment]
@euank   There was indeed malformed JSON so thanks!  It is working now.  I see that part of the code base was used from elsewhere but damn that error is cryptic :)  I suppose I should become more familiar with GO so I can make some sense of all of this.

**Comment by euank** [comment]
@wgorder glad you got it working. If you look at the `dev` branch, you'll see that the code you refer to (reused from Docker's codebase) has already been replaced and the error message should be a little clearer at least.

**Comment by rvangundy** [comment]
I'm running in to this issue and seeing the following entry in the log:

```time="2015-06-18T21:11:58Z" level="error" msg="Error from V2 registry: Authentication is required."```

I'm also able to manually log in using ```docker login``` and pull private images. I've performed ```docker inspect``` and see the following environment variables set:

```
        "Env": [
            "ECS_ENGINE_AUTH_TYPE=docker",
            "ECS_ENGINE_AUTH_DATA={\"https://index.docker.io/v1/\":{\"username\":\"XXX\",\"password\":\"XXX\",\"email\":\"XXX\"}}",
            "ECS_CLUSTER=bouncex-ecs",
            "ECS_LOGFILE=/log/ecs-agent.log",
            "ECS_DATADIR=/data",
            "ECS_AGENT_CONFIG_FILE_PATH=/etc/ecs/ecs.config.json",
            "ECS_UPDATE_DOWNLOAD_DIR=/var/cache/ecs",
            "ECS_UPDATES_ENABLED=true",
            "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
        ],
```

I've also attempted using the dockercfg type to no avail. Any ideas?

**Comment by euank** [comment]
@rvangundy That's the error I get if my password is incorrect. My workign Env looks just like yours. It's worth double checking that your password doesn't contain a quote mark, as that would need to be escaped, and that the agent logs don't indicate an error parsing that json (should be an ERROR level log line if so).
Per the discussion above, the '/user' endpoint isn't what you want, but that wasn't set in the original one in any case.
Sorry I don't have any other ideas based on the information you've given.

**Comment by rvangundy** [comment]
Yeah I don't have anything funny in my password, and I tried using the dockercfg method with the JSON copied directly in... my key does have a couple ='s but that shouldn't be an issue? This is a tough one to debug, I've tried everything.

**Comment by winniwinter** [comment]
Hey, I had also some problems authentication with my privat repo on docker hub. What finally worked was doing it like that in the ecs.config:

ECS_ENGINE_AUTH_TYPE=dockercfg
ECS_ENGINE_AUTH_DATA={"auths":{"https://index.docker.io/v1/":{"auth":"xxxxxx=","email":"xxxx@xxxx"}}


Within the documentation the config is described definitly wrong.

**Comment by jmstone617** [comment]
@rvangundy Did you ever get this resolved? I'm running into the same issue and, as far as I can tell, the ENV variables are being set correctly.

**Comment by chriskinsman** [comment]
@jmstone617 Seeing same issue?  Any luck resolving?

**Comment by jmstone617** [comment]
I ended up using dockercfg and putting 'http://' in front of the endpoint (i.e. `http://quay.io` instead of just `quay.io`). Also, make sure you're using the full path to your image. For instance, I'm using Quay.io, so the image needs to be `quay.io/user/image` -- it doesn't get interpreted from the URL in `dockercfg` or anything

**Comment by dustinmoris** [comment]
Hi, did something change since the issue got closed? Seems like it doesn't work for several people including myself today.

I have done everything as documented and reported here but no luck so far. When I SSH into the ecs instance I can confirm that the ecs.config has the correct env vars (auth type docker) and that the docker container has loaded them as well by running docker inspect.

The weird thing is, when I manually login using docker login command then the task still fails with the same error (image not found). However, when I manually run docker pull then it works fine.

Any ideas?

**Comment by jmstone617** [comment]
Where are your images hosted? What version of Docker are you using?

**Comment by jdahlin** [comment]
Since this is the first hit on google for the "Error: image xx/xx:latest not found", I should mention that I solved this by properly naming /etc/ecs/ecs.config file (/etc/ecs/ecsconfig won't work, obviously)

**Comment by hassankhan87** [comment]
where is the location of this path /etc/ecs/ecs.config  in windows , means how to configure it in windows so i can use private repositories
