### ISSUE TITLE
Possible to un-reserve port 22?

### ISSUE THREAD

**Issue by jclark-dot-org** [aws/amazon-ecs-agent#551]
According to [the docs](http://docs.aws.amazon.com/AmazonECS/latest/APIReference/API_PortMapping.html#API_PortMapping_Contents), ECS reserves ports 22 (SSH), 2375 and 2376 (Docker), and 51678 (ECS Agent), and it appears emperically that 51679 has been added.  Is there any way to change port 22?

I have a Node.js app that presents an SFTP server on port 9001; files that are `put` to the server are parsed and the data is uploaded to another service on the fly.  I can run this in a Docker image on my machine with port 9001 mapped to host port 22, but I can't get the image to run on ECS; I'm seeing `service sfsftp_test_service was unable to place a task because no container instance met all of its requirements. The closest matching container-instance XXX is already using a port required by your task`.  I've already updated my EC2 to run SSHD on port 9022 and enabled this port in my Security Group; this works and I can now SSH to 9022 but not 22.  So SSH is not longer on port 22, but ECS doesn't recognize the fact.  Any way to change the ECS Agent config?

If the question isn't clear, I've posted lots more detail in [this StackExchange post](http://stackoverflow.com/questions/39899449/problems-trying-to-run-a-custom-sftp-service-on-port-22-on-amazon-ecs).

**Comment by richardpen** [comment]
@jclark-dot-org The port 22 is reserved by ECS Agent by default. So the agent won't accept tasks that use this port, but ECS Agent do provide an environment variable `ECS_RESERVED_PORTS` which you can use to unreserve the 22 port. If you are using ECS Optimized AMI, you can override it by putting the line into `/etc/ecs/ecs.config`, and then restart the agent by `sudo stop ecs` and `sudo start ecs`.
```
ECS_RESERVED_PORTS=[2375, 2376, 51678]
```
Please see the [README file](https://github.com/aws/amazon-ecs-agent/blob/master/README.md) for details of this environment variable.
