### ISSUE TITLE
No --log-opt splunk-format=json on ECS?

### ISSUE THREAD

**Issue by alvarow** [aws/amazon-ecs-agent#563]
No **--log-opt splunk-format=json** on ECS ?
Seems for a few months now, the Splunk log driver gives the ability for the log driver to pass container json logs as part of the json message to Splunk, not inline, which makes parsing easy on Splunk.

Any roadmap on when can we benefit for such a feature? Pretty hard to work with spath when I have nicely formatted json log messages but the Docker daemon not able to send them.

Here's a sample log message sent to Splunk:
`{"line":"{\"time\":\"2016-10-19T00:19:14.269Z\",\"level\":\"debug\",\"message\":\"Redis server is ready\",\"data\":{}}","source":"stderr","tag":"c50311069654"}`

Splunk only indexes the 3 main blocks: **_line_**, **_source_** and **_tag_**

https://github.com/splunk/docker/blob/c37529249554c1bdc53c0ada525e8d662ea07098/docs/admin/logging/splunk.md#message-formats

Thanks

**Comment by kiranmeduri** [comment]
ECS task-definitions support **log-opt splunk-format**. However to make use of it instance need to be running **Docker 1.12** which is not yet available on ECS Optimized AMI. I will mark this as a feature request. Thanks

**Comment by aripringle** [comment]
I think the milestone for the splunk-format parameter is actually Docker 1.13: https://github.com/docker/docker/pull/24652

**Comment by samuelkarp** [comment]
Looks like we've missed closing this, but Docker 17.03.1 is now available in the ECS-optimized AMI and has support for the `splunk-format=json` option.
