### ISSUE TITLE
Service scale in logic

### ISSUE THREAD

**Issue by pizzamon** [aws/amazon-ecs-agent#569]
Hi, 

Not sure where to place this but I wasn't able to find any documentation regarding the decision making when the scheduler decides which task to stop during a service scale in. I found the documentation for task placement logic but couldn't see anything for task removal. Wondering if this is something that can be shared with us.

Thanks!

**Comment by aaithal** [comment]
Hi @pizzamon, we have fixed this in our docs. Thanks for bringing this to our attention!
