### ISSUE TITLE
Auto-cleanup needs a "never delete XYZ" image setting

### ISSUE THREAD

**Issue by tehlers320** [aws/amazon-ecs-agent#571]
when using ECS for jenkins slaves you may pull down a slave that is ~1GB in size. These slaves spin-up/spin-down only as needed by the jenkins master. It would be a good feature to have a "dont delete list" To avoid having to wait for this re-pull on every job.

**Comment by adnxn** [comment]
closing issue, since this should be covered by the agent option `ECS_EXCLUDE_UNTRACKED_IMAGE`. Comma separated list of imageName:tag of images that should not be deleted by the ECS agent if ECS_ENABLE_UNTRACKED_IMAGE_CLEANUP is enabled.
