### ISSUE TITLE
Agent doesn't SubmitTaskStateChange if the instance is stopped or terminated

### ISSUE THREAD

**Issue by dinvlad** [aws/amazon-ecs-agent#573]
I'm writing a custom ECS scheduler and would like to keep track of which tasks have stopped and for what reason.

To accomplish that, my current implementation relies on "long polling" of an SQS event queue that is fed with `SubmitTaskStateChange` events issued by the ECS agent (if I understand it correctly). While that works well for tasks that have finished by themselves or intentionally through `StopTask`, the ECS agent doesn't seem to call `SubmitTaskStateChange` when an ECS instance is stopped or terminated for some reason.

As a result, in addition to subscribing to `SubmitTaskStateChange` events in CloudTrail, I also have to subscribe to EC2 `stopped` and `terminated` events for all registered instances, and then "manually" call `ListTasks` for  instances reported in these events. Although that seems like a good workaround for the time being, it still adds to the overall complexity of such setup, and also may not catch the events due to an _abrupt_ shutdown.

Another workaround would be to poll `ListTasks` for an entire cluster in a loop. While that could work for a small number of tasks, doing so for thousands of them is both inefficient and goes against the event-driven programming model, in my opinion.

I'm wondering if there's a better way to do that currently, or if the ECS agent can be improved to explicitly call `SubmitTaskStateChange` before terminating (or better still, that would be eventually done by the ECS itself, please see below). Right now, agent's status appears to be _directly polled by the ECS_, instead of relying on a RESTful API, which seems to go against the API-driven philosophy (although one could argue that this is just a 'private detail' of the implementation).

I also understand that if the instance is _abruptly_ shutdown for some reason, "direct polling" by the ECS would be the only way to tell if the agent (and these tasks) have stopped. In that case, it would be great if the ECS itself would ultimately call `SubmitTaskStateChange`, such that users would only need to subscribe to this particular event.

I'm not sure if this repo is the right place for such request, and would appreciate any feedback on this topic!

**Comment by cbbarclay** [comment]
Thank you for the feedback. We will update this issue when we have a proposal for your use case.

**Comment by cbbarclay** [comment]
Today we announced that ECS sends state changes to CloudWatch Events. For more information please see [the documentation](http://docs.aws.amazon.com/AmazonECS/latest/developerguide/cloudwatch_event_stream.html).
