### ISSUE TITLE
Guidance for custom AMI creation

### ISSUE THREAD

**Issue by mattcallanan** [aws/amazon-ecs-agent#575]
(Cc. @aaithal per offline discussion)

One of the difficult things to understand when we create a custom AMI based on the ECS-optimized AMI is the startup/configuration lifecycle of the following:
- docker-storage-setup
- Docker deamon
- ecs-init
- ecs-agent docker container

We've seen a great recommendation recently to use multi-part cloud-init cloud-boothook recently on https://github.com/aws/amazon-ecs-agent/issues/549#issuecomment-251517887 to address "it may not be safe to restart docker in your normal user data(at which time docker may not have finished initializing)". 

The way I see it, there are 3 initialization cycles to consider:
1. Launch instance from ECS-optimized AMI 
2. Configure instance and bake a new custom AMI
3. Launch instance from custom AMI and join ECS cluster

Within those 3 initialization cycles, we have a number of activities to consider. 

It would be great to see guidance clarifying the following:

For the ECS-optimized AMI:
- when does docker-storage-setup run?
- when does docker deamon start?
- when does ecs-init start?
- when does ecs-agent start?

Also, when building our own custom AMI on top of the ECS-optimized AMI:
- when is it safe to write custom configuration to /etc/sysconfig/docker|docker-storage|docker-storage-setup?
- when is it safe to run docker-storage-setup? what is the recommended way to run docker-storage-setup?
- when is it safe to restart docker? what is the recommended way to restart the docker daemon?
- when is it safe to restart ecs-init? what is the recommended way to restart ecs-init?
- when is it safe to restart ecs agent container? what is the recommended way to restart ecs agent container?

Also, what should be done at custom AMI bake-time vs custom AMI launch-time (particularly considering the potential to dynamically size EBS volumes at launch time)?

Thanks!

**Comment by richardpen** [comment]
@mattcallanan Currently there is no document available for these information you were interested, possibly we will have one day. I hope it will solve your concerns by answering your following question, please let us know if you have any question in the future.

> For the ECS-optimized AMI:
when does docker-storage-setup run?

Early in the boot process as a `cloud-init` `bootcmd`. `bootcmd`s run before user-data executes. 
 
> when does docker deamon start?
 
After most of the `cloud-init` configuration (including `bootcmd`s), but before user-data. 
 
> when does ecs-init start?

After all the runlevel 3 scripts in the sysvinit compatibility component of Upstart have run (including the Docker daemon and user-data). 
 
> when does ecs-agent start?
As soon as possible after ecs-init starts.
 
> Also, when building our own custom AMI on top of the ECS-optimized AMI:
when is it safe to write custom configuration to /etc/sysconfig/docker|docker-storage|docker-storage-setup?

As per the answer above, the order of these files are used during booting are like:
*    docker-storage-setup will read the configuration info in file `/etc/sysconfig/docker`  and update file `/etc/sysconfig/docker-storage`.
*    docker daemon will start using the configuration in `/etc/sysconfig/docker-storage` to setup the device mapper.
*    User scripts are executed
*    Ecs init start and it will start ecs agent
So it’s safe to do:
*    modify `/etc/sysconfig/docker` before docker daemon start.
*    modify `/etc/sysconfig/docker-storage` before after docker-storage-setup is executed.
*    modify `/etc/sysconfig/docker-storage-setup` before docker-storage-setup is executed.
cloud-init does not merge `bootcmd`s by default, so you can override the existing `bootcmd` that invokes `docker-storage-setup` to perform your modifications first.
 
> when is it safe to run docker-storage-setup? what is the recommended way to run docker-storage-setup?

Before docker daemon start. This script should be executed during boot in `cloud-init` or `bootcmd` before docker start.
 
> when is it safe to restart docker? what is the recommended way to restart the docker daemon?
when docker finished initializing, which can be checked by running docker command like:`docker ps`.

The recommended way to restart docker is: `service docker stop` and `service docker start`.
 
> when is it safe to restart ecs-init? what is the recommended way to restart ecs-init?

It should be safe to restart ecs-init after the docker start by `sudo stop ecs` and `sudo start ecs`.
 
> when is it safe to restart ecs agent container? what is the recommended way to restart ecs agent container?

Same as above.
 
> Also, what should be done at custom AMI bake-time vs custom AMI launch-time (particularly considering the potential to dynamically size EBS volumes at launch time)?

docker-storage-setup typically runs at boot so it can deal with a dynamically-sized EBS volume at launch time.  If you're creating a custom AMI and want to preserve this behavior, you'll want to exclude the /dev/xvdcz snapshot from your new AMI (use a blank EBS volume for /dev/xvdcz instead) and docker-storage-setup should be able to initialize that volume at first boot.
 
Thanks

**Comment by mattcallanan** [comment]
Thanks @richardpen for this info... great to see it written down in detail.

**Comment by youssefNM** [comment]
i have a question "what is the benefit of using a custom AMI based on ECS-optimized AMI?"

**Comment by nmeyerhans** [comment]
@youssefNM, you may wish to create a custom AMI in order to ease integration of instances into your environment. For example, you may wish to pre-install additional agents for use by your monitoring or configuration management systems. You could also perform such customizations at boot time using cloud-init and/or cfn-init. A custom AMI could be seen as an optimization of such a process.

The ECS Optimized AMI is effectively a derivative of the standard Amazon Linux AMI to customize it for use in an ECS cluster. You may wish to further derive from our AMI to customize it for your specific environment.

**Comment by samuelkarp** [comment]
@mattcallanan I'm going to close this for now since @richardpen answered your questions.  Please feel free to re-open this if you have additional questions on this topic.
