### ISSUE TITLE
Cut a new release?

### ISSUE THREAD

**Issue by mlafeldt** [aws/amazon-ecs-agent#576]
Hey,

Would it be possible to release a new ecs-agent version that contains the metrics fix in https://github.com/aws/amazon-ecs-agent/pull/556 ?

This is still blocking us from upgrading to a newer CoreOS release and I guess other users are affected as well.

Thanks,
-Mathias

**Comment by richardpen** [comment]
@mlafeldt Thanks for reaching out to us, as the code has been merged, it should be available soon in our next release. Unfortunately we don't have a timeline now, will let you know as soon as we release the new version. Also if you'd like to use a pre-released version, please send me your account id at: penyin (at) amazon.com, thanks.

**Comment by mlafeldt** [comment]
I see. To be honest, I don't understand how this is related to our AWS account, as we simply install the ecs-agent binary on our CoreOS cluster machines.

I guess we're forced to build a new version ourselves in case there won't be a new release in the next couple of weeks.

**Comment by richardpen** [comment]
@mlafeldt Sorry if I'm not clear in the previous response. By "pre-released" version, that means it won't be available publicly and you won't be able to get it from docker hub as you get the official one. There are some extra steps needed to run the pre-released version in your instance. So we need your account id and give you the permission to the pre-released version, also we will send you the steps to use it.

thanks,
Peng

**Comment by mlafeldt** [comment]
@richardpen I tested the pre-release version you sent us and I'm happy to share that it actually fixes the problem with the CPU metrics for us, see https://github.com/coreos/bugs/issues/1605#issuecomment-259150464 😄

**Comment by richardpen** [comment]
@mlafeldt We have released [v1.13.1](https://github.com/aws/amazon-ecs-agent/releases/tag/v1.13.1) today. Now you can access to the latest ecs-agent from the docker hub.
