### ISSUE TITLE
Hide instance role credentials from tasks that use a task role

### ISSUE THREAD

**Issue by dinvlad** [aws/amazon-ecs-agent#578]
As it stands now, specifying a role for a task still doesn't isolate it from accessing the instance role credentials (https://docs.aws.amazon.com/AmazonECS/latest/developerguide/instance_IAM_role.html).

Are there plans to provide an option to enable that kind of isolation? It seems that even the restricted set of permissions provided by AmazonEC2ContainerServiceforEC2Role could be abused, if not for elevation then as a kind of a DoS attack that de-registers instances, submits incorrect task state changes etc.

Or are there already any ways to further prevent or minimize such abuse, without completely blocking the metadata service (e.g. I'd still like to use task roles, just without instance role permissions).

**Comment by richardpen** [comment]
@dinvlad Access to EC2 metadata (which includes the instance's IAM role) is provided for backward compatibility. We will clarify that tasks can access the EC2 metadata through the bridge network in the [documentation](http://docs.aws.amazon.com/AmazonECS/latest/developerguide/task-iam-roles.html#task_im_roles_benefits). We recommend keeping the EC2 instance's role to the minimal set of policies required for the instance to perform actions with the ECS service. 

Access to the Instance’s role can be blocked for containers running on the docker0 bridge using the netfilter rule: 
```
sudo /sbin/iptables --insert FORWARD 1 --in-interface docker+ --destination 169.254.169.254/32 --jump DROP 
```
However, please note that: 
1. You’d also be blocking access to other Instance Metadata that applications in your containers might need (Example: AWS Region, AZ etc) 
2. Containers launched with ‘--net=host’ would still be able to access Instance’s role credentials.

**Comment by dinvlad** [comment]
Thank you. Does that mean that even with the netfilter rule enabled for containers on the bridge network, they will still be able to access their own (task-role) credentials?

**Comment by richardpen** [comment]
@dinvlad Yes, the netfilter rule will just block the instance metadata service [endpoint](http://docs.aws.amazon.com/AWSEC2/latest/UserGuide/ec2-instance-metadata.html#instancedata-user-data-retrieval). The container can still get the credentials from ecs-agent with different [endpoint](http://docs.aws.amazon.com/AmazonECS/latest/developerguide/task-iam-roles.html).

**Comment by dinvlad** [comment]
Ok, great! In that case I think we can close this issue. Perhaps it's worth updating the docs.

**Comment by richardpen** [comment]
@dinvlad Closing the for now, we will update the document. Feel free to reopen it if you have any concern in the future.
