### ISSUE TITLE
Bind the agent's port to something other than 80

### ISSUE THREAD

**Issue by c3mb0** [aws/amazon-ecs-agent#585]
I'm trying to launch a container that binds to port 80 and uses host as its networking mode, however it fails immediately since the agent is also doing the same. It is possible to ssh into the instance and relaunch the agent in bridge mode, however this becomes problematic with auto-scaling. Would it be possible to move the agent to another port?

**Comment by samuelkarp** [comment]
@c3mb0 The ECS agent doesn't bind to port 80.  Can you tell us where that's happening for you?

**Comment by samuelkarp** [comment]
@c3mb0 I'm going to close this since we haven't heard back from you.  Please feel free to re-open it if you're able to take a look at what's happening.
