### ISSUE TITLE
Question: which docker version are you supporting?

### ISSUE THREAD

**Issue by jeekajoo** [aws/amazon-ecs-agent#586]
Hi,

I'd like to know which docker version you are supporting and testing ecs-agent with?
For example, do you support docker 1.9.1 and for how long will it be the case?

Thanks

**Comment by richardpen** [comment]
@jeekajoo We don't test agent with every docker version, we just test the agent with specific docker version which has the performance, fix, feature that our customers are needed. The version we tested are:
```
1.5.0, 1.6.0, 1.6.2, 1.7.1, 1.9.1, 1.11.1, 1.11.2
```
As docker and agent are both trying to keep backward compatible with its predecessor, so even the docker 1.5.0 for example should work with the latest agent version, but there may be some feature or fix not available like: [awslogs](https://docs.docker.com/engine/admin/logging/awslogs/).

You can find the docker version and the corresponding agent version that the agent are test with [here](https://github.com/aws/amazon-ecs-init/releases). We recommend customer to use the latest agent version(v1.13.0) with the docker version(1.11.2) agent tested with, which is easier to get by using [ECS Optimized AMI](http://docs.aws.amazon.com/AmazonECS/latest/developerguide/ecs-optimized_AMI.html).

Thanks.

**Comment by jeekajoo** [comment]
Thanks.
