### ISSUE TITLE
[Question] How to convert rkt images to docker images?

### ISSUE THREAD

**Issue by jason-riddle** [aws/amazon-ecs-agent#587]
Is this possible? I couldn't find any documentation in regards to this.

**Comment by richardpen** [comment]
@jason-riddle We don't deal with rkt images, and we don't know how it will work. You may get the answer in the [coreos/rkt](https://github.com/coreos/rkt) repo.

**Comment by jason-riddle** [comment]
Oops. Posted this in the wrong repo.
