### ISSUE TITLE
Can't Get Hostname/IP Where Task Is Running

### ISSUE THREAD

**Issue by jeprojects** [aws/amazon-ecs-agent#59]
I have tried most of the resources from this page: http://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/ECS.html#listContainerInstances-property

And I can get the automatically generated port for my application running on docker, but I can't get the IP/AWS host on where it is running (the individual ec2 instance in the cluster)

I just get this information: { bindIP: '0.0.0.0', containerPort: 4444, hostPort: 49166 }

**Comment by euank** [comment]
The `containerInstance` objects returned from `describeContainerInstances` have an 'ec2InstanceId` property. You can then use the EC2 APIs to determine the IP of that EC2 instance.

**Comment by euank** [comment]
Per my comment above, you should be able to discover the IP of a task. This is also more of an API question than an Agent question and might fit better in the forums.

If you have further questions/issues we'd be happy to help.
