### ISSUE TITLE
ecs-agent needs to reopen docker.sock on docker restart

### ISSUE THREAD

**Issue by rhuddleston** [aws/amazon-ecs-agent#591]
We have ""live-restore": true" in our docker daemon.json configuration file. This allows us to restart docker without restarting all the containers it's running to change docker configuration etc.

With ecs-agent though it seems  it must keep the old docker.sock file open as after the docker restart it no longer recognized when a service exits until I restart ecs-agent and it reopens the docker.sock.

Steps to reproduce:

• ensure ecs-agent is working correctly, try to kill off running tasks and notice ecs immediately rescedules the tasks to run again on an ecs node. 
• add live-restore to /etc/docker/daemon.json:
{
  "live-restore": true
}
• sudo /bin/kill -SIGHUP $(pidof dockerd)
• sudo service docker restart
• try again to  kill off running tasks. Notice ecs-agent does not recogzixe that task/container exited and ecs still thinks the process is executing. It will stay in this state until ecs-agent is restarts.

Please ensure ecs-agent recognizes changed to docker.sock and reopens it when it changes. I tested this with two other programs that also use docker.sock file (e.g. registrator) and verified it works correctly through a docker restart without issue

**Comment by richardpen** [comment]
@rhuddleston Thanks for your reporting. Currently ecs agent doesn't have a mechnism to reopen docker socket if the previous connection is closed which happened when docker restart.

The docker live-restore feature is supported in docker 1.12.0, while ECS currently only support docker 1.11.2. I'll mark this as a feature request. Currently you can get around this by restart the ecs-agent container.

Thanks,
Peng

**Comment by markuman** [comment]
When talking about high-availability, than this is a must have feature.

**Comment by adnxn** [comment]
closing, released with version [v1.32.1](https://github.com/aws/amazon-ecs-agent/releases/tag/v1.32.1)
