### ISSUE TITLE
ECS Agent behind proxy disconnects and reconnects after a while

### ISSUE THREAD

**Issue by RudolfVonKrugstein** [aws/amazon-ecs-agent#598]
We have an ECS instance running behind a proxy (so ECS Agent has to connect through a proxy).

At startup, eveyrhing works. Than from time to time this message pops up in the logs:

```
[INFO] Error from acs; backing off, err: unexpected EOF
```

Afterwards the agent is disconnected.

Than, after a while, this message pops up:

```
2016-11-16T13:01:13Z [DEBUG] Connecting to TCS endpoint https://ecs-t-1.eu-central-1.amazonaws.com/
2016-11-16T13:01:13Z [INFO] Creating poll dialer, proxy: <my-proxy>
2016-11-16T13:01:13Z [DEBUG] TCS client starting websocket poll loop
```

Now, unfortunately the time between the disconnect and reconnect is to long for this not to be a problem.

I am using agent version 1.13.0

**Comment by aidansteele** [comment]
We are seeing the same issue. Not sure it's a connectivity issue as I seem to be able to maintain SSH sessions (tunneled through HTTPS!) through the proxy for hours.

**Comment by samuelkarp** [comment]
@RudolfVonKrugstein @aidansteele Can you describe a bit more about what's occurring?  How frequently you're seeing disconnection, how long it takes to reconnect, etc?  The agent uses a websocket for communication with ECS and there can be idle periods over the connection; it's possible that the proxy is seeing the connection is idle and timing it out (we've seen that at least one time here: https://github.com/aws/amazon-ecs-agent/issues/553#issuecomment-263784277).

**Comment by samuelkarp** [comment]
@RudolfVonKrugstein @aidansteele We haven't heard from you in a while so I'm going to close this issue.  Please feel free to re-open this issue if you're able to provide more information.
