### ISSUE TITLE
Confirm task is "RUNNING" for N seconds before reporting back to AWS

### ISSUE THREAD

**Issue by stuartornum** [aws/amazon-ecs-agent#599]
We often have containers that fail to startup properly. For example, it may be a Java app that does quite a lot of configuration and may take 15 to 20 seconds to be truly running.

However, Docker see the container running for 10 seconds or so and the ecs-agent reports back to AWS to update the task status to "RUNNING".

It would be great if we could specify a minimum amount of time the Docker container has to be "RUNNING", before reporting back to AWS ECS.

**Comment by cbbarclay** [comment]
Thank you for the feedback. Today you can use [Elastic Load Balancing health checks](http://docs.aws.amazon.com/AmazonECS/latest/developerguide/service-load-balancing.html) to accomplish this. We are also tracking [Docker health checks](https://github.com/aws/amazon-ecs-agent/issues/534) in a separate issue.
