### ISSUE TITLE
Unable to set ECS_RESERVED_PORTS

### ISSUE THREAD

**Issue by johanmeiring** [aws/amazon-ecs-agent#602]
Hi there,

I'm trying to run the ecs-agent on an Ubuntu 16.04 instance running Docker 1.12.  The agent starts up and registers itself with ECS, and I can run containers on it through the ECS service, but the ECS_RESERVED_PORTS environment variable that I'm setting appears to be ignored.  I have tried the following:

1. Running:
```
sudo docker run --name ecs-agent \
--detach=true \
--restart=on-failure:10 \
--volume=/var/run/docker.sock:/var/run/docker.sock \
--volume=/var/log/ecs/:/log \
--volume=/var/lib/ecs/data:/data \
--net=host \
--env=ECS_LOGFILE=/log/ecs-agent.log \
--env=ECS_LOGLEVEL=info \
--env=ECS_DATADIR=/data \
--env=ECS_CLUSTER=TestCluster \
--env=ECS_ENABLE_TASK_IAM_ROLE=true \
--env=ECS_ENABLE_TASK_IAM_ROLE_NETWORK_HOST=true \
--env=ECS_RESERVED_PORTS="[22, 80, 2375, 2376, 51678]" \
amazon/amazon-ecs-agent:latest
```

2. Creating `/etc/ecs/ecs.config` with contents `ECS_RESERVED_PORTS=[22, 80, 2375, 2376, 51678]`, and running:
```
sudo docker run --name ecs-agent \
--detach=true \
--restart=on-failure:10 \
--volume=/var/run/docker.sock:/var/run/docker.sock \
--volume=/var/log/ecs/:/log \
--volume=/var/lib/ecs/data:/data \
--net=host \
--env-file=/etc/ecs/ecs.config  \
--env=ECS_LOGFILE=/log/ecs-agent.log \
--env=ECS_LOGLEVEL=info \
--env=ECS_DATADIR=/data \
--env=ECS_CLUSTER=TestCluster \
--env=ECS_ENABLE_TASK_IAM_ROLE=true \
--env=ECS_ENABLE_TASK_IAM_ROLE_NETWORK_HOST=true \
amazon/amazon-ecs-agent:latest
```

Neither of the above result in tasks with a containerPort:hostPort config of 80:80 from not being started.  However, when adding `echo 'ECS_RESERVED_PORTS=[22, 80, 2375, 2376, 51678]' >> /etc/ecs/ecs.config` to user data for an instance running the Amazon ECS-Optimized AMI, everything works as expected (i.e. tasks with containerPort:hostPort config of 80:80 are not started).

Have I missed something or done something incorrectly?  I've followed basically everything in https://github.com/aws/amazon-ecs-agent/blob/efe53c6e3bc87c2a652c5d79773df6ee93b664bc/README.md.

**Comment by nmeyerhans** [comment]
Hi Johan. I haven't been able to reproduce the behavior you're describing. I've tried by launching a new Ubuntu 16.04 instance and installing docker from the Ubuntu repositories:

    ubuntu@ip-172-31-6-164:~$ ec2metadata --ami-id
    ami-a9d276c9
    ubuntu@ip-172-31-6-164:~$ uptime
     18:43:17 up 26 min,  1 user,  load average: 0.00, 0.00, 0.00
    ubuntu@ip-172-31-6-164:~$ lsb_release -a
    No LSB modules are available.
    Distributor ID: Ubuntu
    Description:    Ubuntu 16.04.1 LTS
    Release:        16.04
    Codename:       xenial
    ubuntu@ip-172-31-6-164:~$ dpkg -s docker.io | grep Version
    Version: 1.12.1-0ubuntu13~16.04.1

From there I have pulled the latest ECS agent container (amazon/amazon-ecs-agent:latest) and run it in both scenarios you describe. In both cases, the environment has been set in the container and a service using one of the reserved ports is unable to launch:

    ubuntu@ip-172-31-6-164:~$ docker run --name ecs-agent     --detach=true     --restart=on-failure:10     --volume=/var/run/docker.sock:/var/run/docker.sock     --volume=/var/log/ecs:/log     --volume=/var/lib/ecs/data:/data     --net=host     --env-file=/etc/ecs/ecs.config     --env=ECS_LOGFILE=/log/ecs-agent.log     --env=ECS_DATADIR=/data/     --env=ECS_ENABLE_TASK_IAM_ROLE=true     --env=ECS_ENABLE_TASK_IAM_ROLE_NETWORK_HOST=true  --env=ECS_RESERVED_PORTS="[22, 80, 8080, 8888]"   amazon/amazon-ecs-agent:latest
    1afc2f223f844c3b2d4ac58343b00615cdf1e11e38caed23c48389c043529261
    ubuntu@ip-172-31-6-164:~$ docker inspect 1afc2f223f844c3b2d4ac58343b00615cdf1e11e38caed23c48389c043529261 | jq '.[0]["Config"]["Env"]'
    [
      "ECS_CLUSTER=default",
      "ECS_LOGFILE=/log/ecs-agent.log",
      "ECS_DATADIR=/data/",
      "ECS_ENABLE_TASK_IAM_ROLE=true",
      "ECS_ENABLE_TASK_IAM_ROLE_NETWORK_HOST=true",
      "ECS_RESERVED_PORTS=[22, 80, 8080, 8888]",
      "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
    ]

Can you confirm with a similar `docker inspect` command that `ECS_RESERVED_PORTS` is actually getting set in your container?

**Comment by nmeyerhans** [comment]
Another detail that I hadn't considered, which may be the problem in your case, is that the list of reserved ports is only recorded the first time a given instance is registered with the service. If you initially ran the agent with a list of reserved ports that didn't include port 80, then subsequently restarted of the agent with a different reserved ports list, the changes to the list would not have had any effect.

Can you re-run your tests on a fresh instance?

**Comment by johanmeiring** [comment]
@nmeyerhans Your assumption was spot-on, I did indeed perform many subsequent restarts and stop + rm + run of the agent.  Rerunning everything on a fresh instance, with the "correct" port config setup from the start, worked perfectly as expected.  Many thanks for pointing me in the right direction :-)
