### ISSUE TITLE
Unable to use uppercase & underscore on dockerLabels for 'RegisterTaskDefinition' calls

### ISSUE THREAD

**Issue by piteur** [aws/amazon-ecs-agent#603]
Hi there !

Not sure if my issue is on the correct place, but I'll give a try :)

I'm currently working on the ECS sdk, and I encountered a behavior that seems wrong to me.
Without surprise, the behavior is the same on the AWS Console.

We can't add docker labels with uppercase or underscore characters, because the validation pattern is **` ^[a-z0-9-.]+$`**

Which is allowed by docker itself. You are able to run this:
```console
docker run -l SERVICE_TAGS="name=my-container-name,domain-name=amazon.fr" -d -p 80 my/awesome:image
```

Here is the error returner when I do a `RegisterTaskDefinition` request.
```console
ClientException: Docker label key SERVICE_NAME contains invalid characters, does not match pattern ^[a-z0-9-.]+$
status code: 400,
request id: <request id>
```

And my request looks like this: (I removed useless data & anonymized it):
```json
"ContainerDefinitions": [{
    "DockerLabels": {
        "SERVICE_TAGS": "name=my-container-name,domain-name=amazon.fr",
    },
    "Environment": [{
        "Name": "key",
        "Value": "value"
    }],
    "Essential": true,
    "Image": "my/awesome:image",
    "MemoryReservation": 64,
    "Name": "my-container-name",
    "PortMappings": [{
        "ContainerPort": 80,
        "Protocol": "tcp"
    }],
    "Family": "my-family-name",
    "NetworkMode": "bridge"
}]
```

The request works fine when I remove the `DockerLabels` entry. And works fine when I use key name like `service.name`.

So:
 - is there any reason this pattern don't accept uppercase & underscore ?
 - how to fix it ?
 - does somebody already have this issue and I didn't find the thread ?

Thanks ! :)

**Comment by aaithal** [comment]
@piteur Thanks a lot for reporting this. We are working on a fix for this. I'll update the issue when we have something more to share.

**Comment by pilgrim2go** [comment]
This issue is really important to us since we're relying on Docker labels when using Traefik.
Something like
`      - "traefik.frontend.rule=HostRegexp:{subdomain:([^.]+)+}.example.com;PathPrefix:/batcher"`

Hope it's soon to be fixed

**Comment by piteur** [comment]
@pilgrim2go - hi there :)

I believe you're using another software to do the discovery / registration to Traefik. On some tools, you can use environment variables instead of docker labels, which doesn't have any validation pattern.
It's not the ideal one (since you inject docker context information **into** the container), but it works.

Please see this [AWS - ECS forum thread](https://forums.aws.amazon.com/thread.jspa?threadID=243383&tstart=25) if you want to push a little bit amazon for a resolution

**Comment by aaithal** [comment]
Hi All,

We have deployed a fix for this in ECS and you shouldn't be seeing these validation errors anymore. Closing this issue for now. Feel free to reopen/create a new one if you have more questions/comments. Thanks!
