### ISSUE TITLE
ECS cluster overlay network

### ISSUE THREAD

**Issue by omus** [aws/amazon-ecs-agent#607]
It would be nice if ECS supported [multi-host networking](https://docs.docker.com/engine/userguide/networking/get-started-overlay/). The way I imagine this working is that all ECS container instances within the same cluster would share an overlay named "cluster". Task definitions could then specify the network mode "cluster" to use it.

**Comment by CpuID** [comment]
Related: https://github.com/aws/amazon-ecs-agent/issues/437

**Comment by samuelkarp** [comment]
Thanks @CpuID, closing as a duplicate of https://github.com/aws/amazon-ecs-agent/issues/437.  @omus Thanks for the suggestion!
