### ISSUE TITLE
Container links are not supported on Windows

### ISSUE THREAD

**Issue by jamsajones** [aws/amazon-ecs-agent#610]
Although ECS still supports the concept of container links the feature is now considered legacy in Docker and was not implemented in Docker on Windows ( See [dockerlinks](https://docs.docker.com/engine/userguide/networking/default_network/dockerlinks/) for more info on legacy links).

Agent will need to provide a generic solution (an opaque replacement) for the task def field for links on both Linux and Windows in the near future.

**Comment by samuelkarp** [comment]
Related: https://github.com/aws/amazon-ecs-agent/issues/437.

**Comment by aaithal** [comment]
Since container links are not supported in windows containers at all, I'm closing this for now.
