### ISSUE TITLE
CPU shares do not work the same

### ISSUE THREAD

**Issue by jamsajones** [aws/amazon-ecs-agent#611]
It has been our observation that CPU shares do work the same with the Windows Agent. Specifying 1024 does not result in the behavior expected where all of the CPU is allocated to the a single container.

**Comment by samuelkarp** [comment]
On Linux, CPU shares are a proportional weight against the total amount in all the cgroups on the system (i.e., if there were 200 CPU shares in total and a particular cgroup had 2, it would have 1% of the CPU as a floor during CPU contention).  In ECS, we've chosen to use 1024 as the scaling unit; we register 1024 CPU units per CPU core detected on the instance, which enables you to have a known proportion of the total CPU shares when creating your task definition.  We need to verify whether the Docker "CPU shares" field ends up behaving the same (with respect to proportional weighting) or differently on Windows and adjust accordingly.

**Comment by samuelkarp** [comment]
Docker 1.13.0 introduced a new `--cpus` parameter that is meant to allocate a number of CPUs and is documented as working on both Windows and Linux.  While we may not want to switch to that on Linux (since it implies `--cpu-period` and `--cpu-quota`) it might be a path forward for Windows.

**Comment by samuelkarp** [comment]
We've released version 1.16.0 of the ECS agent and a new ECS-optimized Windows AMI that supports CPU limits.  Please note that CPU specified in the task definition is enforced as a hard limit on Windows and bursting is not supported.  See the [updated documentation](http://docs.aws.amazon.com/AmazonECS/latest/developerguide/ECS_Windows_getting_started.html) for instructions to get started using the new AMI.
