### ISSUE TITLE
Directories (data, logs) not automatically created; agent fails to start.

### ISSUE THREAD

**Issue by jamsajones** [aws/amazon-ecs-agent#613]
The directories needed for Windows Agent to be able to run are not created on start-up. This causes agent to fail to start.  

Currently ecs agent provides the [amazon-ecs-agent.ps1](https://github.com/aws/amazon-ecs-agent/blob/master/misc/windows-deploy/amazon-ecs-agent.ps1) script to accomplish this task. Some or all of this functionality needs to be moved into Windows Agent start-up.

**Comment by aaithal** [comment]
Resolving this as `ECSTools` ps module takes care of this with the Windows GA support. See [Getting Started with Windows Containers](https://docs.aws.amazon.com/AmazonECS/latest/developerguide/ECS_Windows_getting_started.html) for details
