### ISSUE TITLE
Windows Networking Modes Not supported

### ISSUE THREAD

**Issue by jamsajones** [aws/amazon-ecs-agent#615]
Windows Agent does not support all of the unique networking modes for Windows. Currently the only mode that is supported is NAT (as the default when no mode is passed). Other networking modes, most specifically transparent networks, do not work with the networking that setup that is done for Windows Agent and cause EC2 networking to break, rendering the instance unavailable.

**Comment by foragerr** [comment]
Given that NAT mode has [known performance issues](https://github.com/moby/moby/issues/34355) it would be nice to add support for the other modes.

**Comment by adnxn** [comment]
@foragerr Thanks for your feedback. We're currently working with Microsoft to improve NAT performance issues. We're also exploring ways to support other network modes, although we don't have a definitive timeline right now.

**Comment by ellenthsu** [comment]
At this time, we do not have plans to support alternative Windows network modes outside of NAT.
