### ISSUE TITLE
Disconnected ecs-agents

### ISSUE THREAD

**Issue by djenriquez** [aws/amazon-ecs-agent#618]
We've had issues in the past with ecs-agents disconnecting and then remaining disconnected. To resolve, we created a service that checks if agents are disconnected. If they are, and they remain disconnected for 5 minutes, we terminate the instance and let it be replaced. 

With the newer versions of ECS (1.13.0), we're still seeing activity from our internal agent, meaning ecs-agents are still disconnecting and staying disconnected for > 5 minutes. We have ~50 ECS hosts and see about 20 events daily.

Should we continue to terminate these boxes in these events? Do ecs-agents attempt to reconnect on their own now? Is there a known reason why ecs-agents disconnect?

**Comment by ibirman** [comment]
We are continuing to see this with 1.13.1 as well

**Comment by samuelkarp** [comment]
@djenriquez @ibirman The ECS agent disconnects and reconnects as a normal part of its function.  However, seeing an agent stay disconnected for > 5m is something we'd like to look at.  Do you have logs from when this is occurring?  If you're not comfortable posting those publicly, can you send them to me at skarp at amazon.com?

**Comment by WheresWardy** [comment]
@samuelkarp I believe we may also be seeing this problem since moving to 1.13.1 where agents disconnect fairly frequently (we've seen an 8-node ECS cluster drop 4 nodes in about 48 hours) and never reappear, with lots of messages in the ecs-agent log along the lines of `(RUNNING->RUNNING) to RUNNING, but already RUNNING`, `Error from acs; backing off, err: InvalidInstanceException: Instance 9bd3b382-af70-45c6-ac6a-b684a2bc0482 is invalid` and `Error from tcs; backing offerrwebsocket: close 1008 InvalidContainerInstance: Missing container instance arn`. I'll email you an entire ecs-agent log for analysis if it helps.

**Comment by samuelkarp** [comment]
@WheresWardy Thanks for sending the log.  I'm on vacation today so I've asked my teammate to take a look while I'm out.  However, really quickly: the `InvalidInstanceException` and `InvalidContainerInstance` messages likely indicate that `DeregisterContainerInstance` was called for that instance.  Once an instance is deregistered, it can no longer connect to ECS and is no lnoger part of your cluster.  Did someone or something call `DeregisterContainerInstance`?

**Comment by WheresWardy** [comment]
@samuelkarp There shouldn't be anything calling that no, we do have very many automated things that are controlling ECS, just an ASG that we scale manually to put nodes in the cluster, but I'll go through anything that could be calling it once I'm back in the office after the holidays. Thanks for the seasonal help!

**Comment by WheresWardy** [comment]
@samuelkarp I'm still investigating, but I believe this may be an errant script unregistering ECS agents from our cluster when it's not supposed to, so don't believe it's related to the ECS agent at this time.

**Comment by djenriquez** [comment]
Sam sorry for the delay, holidays + a new job put me in a position where I won't have logs for a while. I'll update this issue if I encounter the problem at my new gig 👍

**Comment by aaithal** [comment]
@djenriquez @WheresWardy I'm closing this for now. Will reopen if we get new logs or new occurrences of the same.
