### ISSUE TITLE
Add blue/green deployment delays/healthchecks

### ISSUE THREAD

**Issue by djenriquez** [aws/amazon-ecs-agent#619]
There are some containers that are not available immediately after start. Because of this, ECS blue/green deploys can actually cause a service to become unavailable if, after a deployment, blue is taken out of service before green is actually available.

Are there plans for adding time delays for deployments so that blue will be kept in service `time` amount before it is removed? Or better yet, are there plans to introduce health-checking at the service level such that blue will remain until green passes the health check?

**Comment by samuelkarp** [comment]
@djenriquez The easiest way to do this today is to use an ALB.  ECS listens to ELB/ALB health checks and will ensure that newly launched tasks become healthy before stopping enough tasks to drop your service below the minimum healthy percent.

I'm going to close this in favor of https://github.com/aws/amazon-ecs-agent/issues/534, which is about health checking using Docker's health check feature.

**Comment by djenriquez** [comment]
Works for me! Thanks @samuelkarp.
