### ISSUE TITLE
Unable to take container logs using ["json-file","awslogs"]

### ISSUE THREAD

**Issue by rajasekaran07** [aws/amazon-ecs-agent#624]
Hi Team,

I have configured ECS Agent on my Ubuntu 16.04 EC2 instance and I have created my ECS cluster("ecstest").
**I can send my system logs to cloudwatch logs by running below command.**

sudo python ./awslogs-agent-setup.py --region us-east-1

**I am seeing WARNING in my ecs logs:**

2016-12-08T11:01:02Z [WARN] Invalid format for "ECS_AVAILABLE_LOGGING_DRIVERS" environment variable; expected a JSON array like ["json-file","syslog"]. err invalid character 'j' looking for beginning of value
2016-12-08T11:13:03Z [WARN] Error getting cpu stats, err: No data in the queue, container: 9c76a71b10dd3c3c14eb63c9abf6b119c7dd96ff7004636aa74a9b9fd80c424c
2016-12-08T11:13:03Z [WARN] Error getting instance metrics: No task metrics to report
2016-12-08T11:40:03Z [WARN] Error getting cpu stats, err: No data in the queue, container: 9c76a71b10dd3c3c14eb63c9abf6b119c7dd96ff7004636aa74a9b9fd80c424c
2016-12-08T11:40:03Z [WARN] Error getting instance metrics: No task metrics to report
2016-12-08T11:59:03Z [WARN] Error getting cpu stats, err: No data in the queue, container: 9c76a71b10dd3c3c14eb63c9abf6b119c7dd96ff7004636aa74a9b9fd80c424c
2016-12-08T11:59:03Z [WARN] Error getting instance metrics: No task metrics to report

I am **unable to start my container with awslogs driver** in my task definition.

I used the below command to start my ecs-agent.

sudo docker run -d --name ecs-agent \
--detach=true \
--restart=on-failure:10 \
--volume=/var/run/docker.sock:/var/run/docker.sock \
--volume=/var/log/ecs/:/log:z \
--volume=/var/lib/ecs/data:/data:z \
--net=host \
--env=ECS_LOGFILE=/log/ecs-agent.log \
--env=ECS_LOGLEVEL=info \
--env=ECS_DATADIR=/data \
--env=ECS_CLUSTER= ecstest \
--env=ECS_ENABLE_TASK_IAM_ROLE=true \
--env=ECS_ENABLE_TASK_IAM_ROLE_NETWORK_HOST=true \
--env=ECS_AVAILABLE_LOGGING_DRIVERS=["json-file","awslogs"] \
amazon/amazon-ecs-agent:latest

**PFB the JSON file after i tried to run my task definition**

{
  "requiresAttributes": [
    {
      "value": null,
      "name": "com.amazonaws.ecs.capability.docker-remote-api.1.18",
      "targetId": null,
      "targetType": null
    },
    {
      "value": null,
      "name": "com.amazonaws.ecs.capability.logging-driver.awslogs",
      "targetId": null,
      "targetType": null
    },
    {
      "value": null,
      "name": "com.amazonaws.ecs.capability.docker-remote-api.1.19",
      "targetId": null,
      "targetType": null
    }
  ],
  "taskDefinitionArn": "arn:aws:ecs:us-east-1:855158544446:task-definition/mytestecs:4",
  "networkMode": "host",
  "status": "ACTIVE",
  "revision": 4,
  "taskRoleArn": null,
  "containerDefinitions": [
    {
      "volumesFrom": [],
      "memory": 100,
      "extraHosts": null,
      "dnsServers": null,
      "disableNetworking": null,
      "dnsSearchDomains": null,
      "portMappings": [
        {
          "hostPort": 8090,
          "containerPort": 8090,
          "protocol": "tcp"
        }
      ],
      "hostname": null,
      "essential": true,
      "entryPoint": null,
      "mountPoints": [],
      "name": "pythonapp",
      "ulimits": null,
      "dockerSecurityOptions": null,
      "environment": [],
      "links": null,
      "workingDirectory": null,
      "readonlyRootFilesystem": null,
      "image": "training/webapp",
      "command": null,
      "user": null,
      "dockerLabels": null,
      "logConfiguration": {
        "logDriver": "awslogs",
        "options": {
          "awslogs-group": "ecstestlogs",
          "awslogs-region": "us-east-1"
        }
      },
      "cpu": 25,
      "privileged": null,
      "memoryReservation": null
    }
  ],
  "placementConstraints": [],
  "volumes": [],
  "family": "mytestecs"
}

**My Task definition:**

{
    "networkMode": "host",
    "taskRoleArn": null,
    "containerDefinitions": [
        {
            "volumesFrom": [],
            "memory": 100,
            "extraHosts": null,
            "dnsServers": null,
            "disableNetworking": null,
            "dnsSearchDomains": null,
            "portMappings": [
                {
                    "hostPort": 8090,
                    "containerPort": 8090,
                    "protocol": "tcp"
                }
            ],
            "hostname": null,
            "essential": true,
            "entryPoint": null,
            "mountPoints": [],
            "name": "pythonapp",
            "ulimits": null,
            "dockerSecurityOptions": null,
            "environment": [],
            "links": null,
            "workingDirectory": null,
            "readonlyRootFilesystem": null,
            "image": "training/webapp",
            "command": null,
            "user": null,
            "dockerLabels": null,
            "logConfiguration": {
                "logDriver": "awslogs",
                "options": {
                    "awslogs-group": "ecstestlogs",
                    "awslogs-region": "us-east-1"
                }
            },
            "cpu": 25,
            "privileged": null,
            "memoryReservation": null
        }
    ],
    "volumes": [],
    "family": "mytestecs"
}

PFB my instances details in my ecs cluster:

![image](https://cloud.githubusercontent.com/assets/19193992/21009465/ba470730-bd6c-11e6-9840-4822f30ab867.png)

Kindly suggest how to proceed further.

Regards,
Raja

**Comment by rajasekaran07** [comment]
I am getting below response while running my task.

Run tasks failed
Reasons : ["ATTRIBUTE"]

Regards,
Raja

**Comment by pawbur** [comment]
Hi,

You need to escape quotation marks in --env=ECS_AVAILABLE_LOGGING_DRIVERS=["json-file","awslogs"] 

try starting ecs agent with:

sudo docker run -d --name ecs-agent
--detach=true
--restart=on-failure:10
--volume=/var/run/docker.sock:/var/run/docker.sock
--volume=/var/log/ecs/:/log:z
--volume=/var/lib/ecs/data:/data:z
--net=host
--env=ECS_LOGFILE=/log/ecs-agent.log
--env=ECS_LOGLEVEL=info
--env=ECS_DATADIR=/data
--env=ECS_CLUSTER= ecstest
--env=ECS_ENABLE_TASK_IAM_ROLE=true
--env=ECS_ENABLE_TASK_IAM_ROLE_NETWORK_HOST=true
--env=ECS_AVAILABLE_LOGGING_DRIVERS=[\"json-file\",\"awslogs\"]
amazon/amazon-ecs-agent:latest

**Comment by rajasekaran07** [comment]
@pawbur 

No this is not working.. 

sudo docker run -d --name ecs-agent \
--detach=true \
--restart=on-failure:10 \
--volume=/var/run/docker.sock:/var/run/docker.sock \
--volume=/var/log/ecs/:/log:z \
--volume=/var/lib/ecs/data:/data:z \
--net=host \
--env=ECS_LOGFILE=/log/ecs-agent.log \
--env=ECS_LOGLEVEL=info \
--env=ECS_DATADIR=/data \
--env=ECS_CLUSTER= ecstest \
--env=ECS_ENABLE_TASK_IAM_ROLE=true \
--env=ECS_ENABLE_TASK_IAM_ROLE_NETWORK_HOST=true \
--env=ECS_AVAILABLE_LOGGING_DRIVERS=["json-file","awslogs"] \
amazon/amazon-ecs-agent:latest

Regards,
Raja

**Comment by pawbur** [comment]
Hi,

Note the backslash in `--env=ECS_AVAILABLE_LOGGING_DRIVERS=[\"json-file\",\"awslogs\"]`

**Comment by rajasekaran07** [comment]
@pawbur ,

Thank you.. Its working now...

**Comment by aaithal** [comment]
@pawbur Thanks for your help with this. @rajasekaran07 since this is working now, I'm going to close this issue. Feel free to reopen/create another issue if you run into anything else. Thanks!

**Comment by rajasekaran07** [comment]
@aaithal @pawbur thanks for your help this is working fine.

**Comment by rajasekaran07** [comment]
@pawbur @aaithal , 

awslog driver is working properly I would like to know what changes are required to use gelf log driver.

Regards,
Raja

**Comment by rajasekaran07** [comment]
I was updated /etc/ecs/ecs.config file for gelf driver.

ECS_CLUSTER=mychecklog
ECS_AVAILABLE_LOGGING_DRIVERS=["json-file","syslog","fluentd","gelf","awslogs"]

I was updated this by passing user data in Cloud formation template.

Regards,
Raja
