### ISSUE TITLE
Unable to retrieve python custom logs in AWS Cloudwatch 

### ISSUE THREAD

**Issue by rajasekaran07** [aws/amazon-ecs-agent#629]
Hi Team,

I am running sample python app in my ECS task definition and I had configured awslog driver in my task definition. But, It is taking general logs it doesnt take my custom log print values.

app.py

import os
import logging
from flask import Flask
logging.basicConfig(filename='example.log',level=logging.DEBUG)
logging.debug('This message should go to the log file')
app = Flask(__name__)

@app.route('/')
def hello():
    provider = str(os.environ.get('PROVIDER', 'Treselle'))
    return 'Hello '+provider+'!'

if __name__ == '__main__':
    # Bind to PORT if defined, otherwise default to 5000.
    port = int(os.environ.get('PORT', 5000))
    app.run(host='0.0.0.0', port=port)

while running this application I didnt get my logs for each and every request. I got only GET logs in my CloudWatch logs. I didnt get my custom print logs in my cloudwatch log group.

![image](https://cloud.githubusercontent.com/assets/19193992/21039968/d218950e-be07-11e6-9977-3f8305e3097b.png)

I have tested same in my local my logs are printed after I stopped my container. Kindly suggest what changes need to be done to get my custom logs in cloudwatch log group.

 * Running on http://0.0.0.0:5000/ (Press CTRL+C to quit)
192.168.0.185 - - [09/Dec/2016 06:14:47] "GET / HTTP/1.1" 200 -
192.168.0.185 - - [09/Dec/2016 06:14:47] "GET /favicon.ico HTTP/1.1" 404 -
192.168.0.185 - - [09/Dec/2016 06:14:49] "GET / HTTP/1.1" 200 -
192.168.0.185 - - [09/Dec/2016 06:14:49] "GET / HTTP/1.1" 200 -
192.168.0.185 - - [09/Dec/2016 06:14:49] "GET / HTTP/1.1" 200 -
192.168.0.185 - - [09/Dec/2016 06:14:50] "GET / HTTP/1.1" 200 -
192.168.0.185 - - [09/Dec/2016 06:14:50] "GET / HTTP/1.1" 200 -
192.168.0.185 - - [09/Dec/2016 06:14:50] "GET / HTTP/1.1" 200 -
192.168.0.185 - - [09/Dec/2016 06:14:50] "GET / HTTP/1.1" 200 -
192.168.0.185 - - [09/Dec/2016 06:14:50] "GET / HTTP/1.1" 200 -
192.168.0.185 - - [09/Dec/2016 06:14:50] "GET / HTTP/1.1" 200 -
192.168.0.185 - - [09/Dec/2016 06:14:51] "GET / HTTP/1.1" 200 -
192.168.0.185 - - [09/Dec/2016 06:14:51] "GET / HTTP/1.1" 200 -
192.168.0.185 - - [09/Dec/2016 06:14:51] "GET / HTTP/1.1" 200 -
^Ctest file to check1
test file to check1
test file to check1
test file to check1
test file to check1
test file to check1
test file to check1
test file to check1
test file to check1
test file to check1
test file to check1
test file to check1
test file to check1

Regards,
Raja

**Comment by samuelkarp** [comment]
The `awslogs` driver is like the other Docker logging drivers in that it only captures messages sent to stdout/stderr instead of files.  The line you have as 'This message should go to the log file' is only going to a file, so it won't be captured by the logging driver.  I'm not sure where your 'test file to check1' lines are coming from (I don't see them in the source you provided) or what is causing them to be emitted after you press `^C`.  Note that pressing `^C` is different from how tasks are stopped in ECS; `^C` sends a `SIGINT` signal, whereas stopping a task in ECS is akin to running `docker stop` and sends a `SIGTERM` signal.

**Comment by samuelkarp** [comment]
@rajasekaran07 I'm going to close this for now, feel free to re-open if you have more questions about how logging works.
