### ISSUE TITLE
Is there any default ubuntu AMI is available to setup add in ECS cluster

### ISSUE THREAD

**Issue by rajasekaran07** [aws/amazon-ecs-agent#631]
Hello,

We are running all our applications in ubuntu 16.04 hence we are trying to use ubuntu as our ECS container instance.
Is there any default ubuntu AMI is available to setup add in ECS cluster??
How to install ecs agent apart from container installation. any apt-get service or custom service name available??

Regards,
Raja

**Comment by samuelkarp** [comment]
Installation instructions for Ubuntu are located [in our documentation](http://docs.aws.amazon.com/AmazonECS/latest/developerguide/ecs-agent-install.html).

**Comment by rajasekaran07** [comment]
@samuelkarp thanks for the information I already tried this one. But still I am trying to implement via AMIs. 

After I created ECS Cluster I have changed ami value in my CloudFormation template as "ami-a4dff4b3".

![image](https://cloud.githubusercontent.com/assets/19193992/21213565/44b2c26c-c2bb-11e6-8378-6828fbafc4ce.png)

![image](https://cloud.githubusercontent.com/assets/19193992/21213589/8f7c4bce-c2bb-11e6-9f7b-7a3ab1401df0.png)

My update event logs:

![image](https://cloud.githubusercontent.com/assets/19193992/21213629/e8255554-c2bb-11e6-849a-14afbad3bc4a.png)


This new ami is Ubuntu base machine. After I updated in CloudForamtion the changes are reflected in ECS Cluster but In EC2 console page it is showing as old ami id it was not updated. Please let me know how to update this changes.

ECS Cluster Resources with new AMI id:

![image](https://cloud.githubusercontent.com/assets/19193992/21213687/2b1380ca-c2bc-11e6-99fa-fea700d35db4.png)

My EC2 Console page is not reflecting the update.

![image](https://cloud.githubusercontent.com/assets/19193992/21213712/53fd5858-c2bc-11e6-82be-b0a69ea9fed7.png)

Please let me know if there any other steps need to be done.

Regards,
Raja
