### ISSUE TITLE
/var/lib/docker get filled up and ecs agent hangs

### ISSUE THREAD

**Issue by simplesteph** [aws/amazon-ecs-agent#632]
Hi,

Somehow, my disk filled up with docker containers and is now 100% full.  My docker images are pretty small
```
[ec2-user@ip- ~]$ df -h
Filesystem      Size  Used Avail Use% Mounted on
/dev/xvda1      7.8G  7.8G     0 100% /
devtmpfs        992M  108K  992M   1% /dev
tmpfs          1002M     0 1002M   0% /dev/shm
/dev/xvdh        50G  7.3G   40G  16% /mnt
```

A quick command shows that the `/var/lib/docker` directory is full.
```
[ec2-user@ip- ~]$ sudo du -sh /var/lib/docker/
7.1G	/var/lib/docker/
```

Two questions
1) Can ecs-agent clean up some of that folder?
2) How can we make the ec2 instance fail health checks? 

The reason I'm asking is that the instance is completely worthless, `docker ps` hangs indefinitely, the status of my task remains in `PENDING` in the aws console, etc etc

**Comment by samuelkarp** [comment]
Images, containers, container data layers, container logs, and volumes all contribute to disk space consumption.  If you're running many containers quickly, using many different images, writing a lot of data, or writing a lot of logs that can all contribute.  If you're running the ECS-optimized AMI, the most likely culprit of space consumption on the root volume would be container logs and volumes.

> Can ecs-agent clean up some of that folder?

The ECS agent performs cleanup of images, containers, container data layers, container logs, and volumes.  By default, containers (and their associated resources like data layers, logs, and volumes) are cleaned up 3 hours after the container exist and images are cleaned up on an hourly basis choosing candidate images based on least recently used.  If you're running into space issues, these defaults may not be appropriate for your use-case and you might want to tweak them.  You can find the parameters to tune these in [our README](https://github.com/aws/amazon-ecs-agent/blob/master/README.md).

> How can we make the ec2 instance fail health checks?

We're tracking this feature request in https://github.com/aws/amazon-ecs-agent/issues/483.

**Comment by simplesteph** [comment]
You're right thanks
Looking forward to seeing the health checks fail in our instances when this happens, that's a must have

**Comment by samuelkarp** [comment]
Thanks!  Going to close this in favor of #483 since that's already tracking the feature request.
