### ISSUE TITLE
Ubuntu AMI is not reflecting after updated CloudFormation Stack

### ISSUE THREAD

**Issue by rajasekaran07** [aws/amazon-ecs-agent#635]
Hello,

After I created ECS Cluster I have changed ami value in my CloudFormation template as "ami-a4dff4b3".

![image](https://cloud.githubusercontent.com/assets/19193992/21213773/b2eca224-c2bc-11e6-9085-5dbceca29ddf.png)

![image](https://cloud.githubusercontent.com/assets/19193992/21213781/bdf1eb3e-c2bc-11e6-8698-9938a0b77d8c.png)

My update event logs:

![image](https://cloud.githubusercontent.com/assets/19193992/21213788/c7a63784-c2bc-11e6-82a0-e4eca24fa9ea.png)

This new ami is Ubuntu base machine. After I updated in CloudForamtion the changes are reflected in ECS Cluster but In EC2 console page it is showing as old ami id it was not updated. Please let me know how to update this changes.

ECS Cluster Resources with new AMI id:

![Uploading image.png…]()

My EC2 Console page is not reflecting the update.

![image](https://cloud.githubusercontent.com/assets/19193992/21213763/a55cec68-c2bc-11e6-8042-606e14770471.png)

Please let me know if there any other steps need to be done.

Regards,
Raja

**Comment by samuelkarp** [comment]
When you update the AMI in the `AWS::AutoScaling::LaunchConfiguration` of a CloudFormation stack, it updates the configuration but does not affect your running instances.  See the note below from [the documentation](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-as-launchconfig.html):

> Important
> 
> When you update a property of the LaunchConfiguration resource, AWS CloudFormation deletes that resource and creates a new launch configuration with the updated properties and a new name. This update action does not deploy any change across the running Amazon EC2 instances in the auto scaling group. In other words, an update simply replaces the LaunchConfiguration so that when the auto scaling group launches new instances, they will get the updated configuration, but existing instances continue to run with the configuration that they were originally launched with. This works the same way as if you made similar changes manually to an auto scaling group.

If you terminate the existing instance that is currently running, your auto scaling group will launch a new instance from the new AMI.

**Comment by rajasekaran07** [comment]
@samuelkarp Thanks for your input. The new instances are launched basd on new configuration.

Regards,
Raja

**Comment by samuelkarp** [comment]
Glad it's working.  For general questions related to AWS, the [AWS Forums](https://forums.aws.amazon.com/index.jspa) are a great place to find help (there are service-specific forums, including [ECS](https://forums.aws.amazon.com/forum.jspa?forumID=187), [EC2](https://forums.aws.amazon.com/forum.jspa?forumID=30), and [CloudFormation](https://forums.aws.amazon.com/forum.jspa?forumID=92)).

**Comment by rajasekaran07** [comment]
@samuelkarp I am unable to post new topic in aws forums which you mentioned above.

Your account is not ready for posting messages yet. Please try again later. 

Regards,
Raja

**Comment by samuelkarp** [comment]
@rajasekaran07 It sounds like there might have been something temporarily affecting your ability to post in the forums.  You should go ahead and try again, since it is now later.
