### ISSUE TITLE
Why amazon prefers acs container instance in CentOS why-not Ubuntu

### ISSUE THREAD

**Issue by rajasekaran07** [aws/amazon-ecs-agent#637]
Hi Team,
It is a kind question. I am also aware Centos is more security compared to Ubuntu. But, I am lokking for more information why amazon prefers acs container instance as CentOS base image why-not Ubuntu.

Regards,
Raja

**Comment by samuelkarp** [comment]
The ECS-optimized AMI is based on the Amazon Linux AMI, not CentOS.  We use the Amazon Linux AMI as our base as we maintain a close relationship with the Amazon Linux team.  Amazon Linux is designed to provide a stable, secure, and high performance execution environment for applications running on Amazon EC2.  For more questions about Amazon Linux, please post in the [Amazon Linux forum](https://forums.aws.amazon.com/forum.jspa?forumID=228).
