### ISSUE TITLE
Which restart policy is followed in AWS official ecs container instance - ami-6df8fe7a

### ISSUE THREAD

**Issue by rajasekaran07** [aws/amazon-ecs-agent#638]
Hi Team,

It is kind question.

Which restart policy is followed in AWS official ecs instance ami ami-6df8fe7a or is there any script written to start ecs-agent while booting instance.

Regards,
Raja

**Comment by samuelkarp** [comment]
The ECS-optimized AMI uses [ecs-init](https://github.com/aws/amazon-ecs-init) to start the ECS agent on boot.  ecs-init is available for Amazon Linux and for SUSE (though the version available for SUSE is fairly old).  There is a [pull request](https://github.com/aws/amazon-ecs-init/pull/72) to package it for Ubuntu, but we have not tested this and do not know that it will work.

Our current recommended approach to running ECS is [documented here](http://docs.aws.amazon.com/AmazonECS/latest/developerguide/ecs-agent-install.html).
