### ISSUE TITLE
Can we use all the properties of logstatsh filtering in AWS CloudWatch logs for ECS containers

### ISSUE THREAD

**Issue by rajasekaran07** [aws/amazon-ecs-agent#641]
Hello Team,

We are running our applications on ECS and we are trying to do our best for container log management. Also we are using AWS ElasticSearch for logging. My question is can we use all properties of logstash in AWS CloudWatch logs like custom filtering while parsing logs to ES... 

Note: I am unable to post my question in Forums so I pasted here.
Regards,
Raja

**Comment by samuelkarp** [comment]
The best place to ask about AWS Elasticsearch Service is the [AWS Elasticsearch Service forum](https://forums.aws.amazon.com/forum.jspa?forumID=200).  If you're having trouble posting to the forum, please reach out to [AWS customer service](https://aws.amazon.com/contact-us/) for an account-related issue.
