### ISSUE TITLE
what is percent in ECS service autoscaling policy

### ISSUE THREAD

**Issue by rajasekaran07** [aws/amazon-ecs-agent#644]
Hi team,

My gentle question on ECS service based auto scaling policy. I would like to know what is percent on  ECS service autoscaling polic. PFB..

![image](https://cloud.githubusercontent.com/assets/19193992/21426648/0d21fd8e-c876-11e6-845d-02b92d9c61a5.png)

Regards,
Raja

**Comment by nmeyerhans** [comment]
Percent allows the service to be scaled relative to its current size. For example, if your service is running 4 tasks, and you have a scaling policy to add 50% capacity when your alarm fires, two additional tasks will be created, giving a total of 6 running tasks. If the alarm fires again, then 3 new tasks are added.

**Comment by rajasekaran07** [comment]
@nmeyerhans thanks for your response. I also seen this info in some other blog but forgot to mention here.
