### ISSUE TITLE
My Service autoscale is not adding task while alarm triggered

### ISSUE THREAD

**Issue by rajasekaran07** [aws/amazon-ecs-agent#645]
Hi Team,

I have configured CPU Scaling policy in my service autoscaling. In my configuration when CPU utilization goes 10% it will add one more task. But, It is not working PFB my event logs.

![image](https://cloud.githubusercontent.com/assets/19193992/21448709/90d538c2-c90b-11e6-8694-bac07641eca7.png)

![image](https://cloud.githubusercontent.com/assets/19193992/21448699/6e3d88b4-c90b-11e6-8fcc-8e33d6634ef3.png)

**Please note that I am running one ECS Container instance. I would like to know whether we can run only one task per container instance or we can run more than one task per container instance?

If we can run more tasks per container port conflict will occur how to fix this issue.**

Kindly someone suggest how to fix this issue.

Regards,
Raja

**Comment by nmeyerhans** [comment]
Hi @rajasekaran07. I believe that my answer to #646 should help get you past the issue of port contention and allow your service to autoscale on a single instance, so I'm going to close this issue. Please feel free to reach out if you run in to further problems.
