### ISSUE TITLE
My ECS Service not taking updated task definition

### ISSUE THREAD

**Issue by rajasekaran07** [aws/amazon-ecs-agent#648]
Hi Team,

I have updated my ECS task definition and service in AWS cli, but my service is not taking updated task definition. It is still running with old task definition.

Steps I followed.

sed -e "s;%BUILD_NUMBER%;${BUILD_NUMBER};g" mytestnode.json > mytestnode-v_${BUILD_NUMBER}.json
aws ecs register-task-definition --family mytestnode --cli-input-json file://mytestnode-v_${BUILD_NUMBER}.json

TASK_REVISION=`aws ecs describe-task-definition --task-definition mytestnode | egrep "revision" | tr "/" " " | awk '{print $2}' | sed 's/"$//'`
DESIRED_COUNT=`aws ecs describe-services --cluster mytestnode --services my-test-node-service | egrep "desiredCount" | head -1 | awk '{print $2}' | sed 's/,$//'`

aws ecs update-service --cluster mytestnode --service ${SERVICE_NAME} --task-definition ${TASK_FAMILY}:${TASK_REVISION} --desired-count ${DESIRED_COUNT}

Note: My service was updated with new task definition but running task is containing old one. Kindly suggest how to fix this issue.

Also I would like to know while updating service will it kill old task and run new task based on updated task definition or we need to kill old task manually?

Regards,
Raja

**Comment by rajasekaran07** [comment]
I did this adding one more free container instance. 
Ref: https://blog.codeship.com/easy-blue-green-deployments-on-amazon-ec2-container-service/

Regards,
Raja

**Comment by mtoigo** [comment]
Great article and this really helped me better understand ECS deployments!
