### ISSUE TITLE
How blue green deployment possible in AWS ECS

### ISSUE THREAD

**Issue by rajasekaran07** [aws/amazon-ecs-agent#650]
Hi Team,

We are trying to build our dev environment with AWS ECS. We already configured Jenkins CICD pipeline with ECS by following https://aws.amazon.com/blogs/devops/set-up-a-build-pipeline-with-jenkins-and-amazon-ecs/ and we are trying to do the same with blue green deployment. When I am running blue and green as two service in one cluster there will be a problem to route incoming traffic to new service.

Kindly someone suggest how to do ELB cutover with one service to another service. (I need to stop traffic to blue service and route the traffic to green service.)

![image](https://cloud.githubusercontent.com/assets/19193992/21536869/7f36a1f8-cdae-11e6-81c4-8bd9ce96dccd.png)

Regards,
Raja

**Comment by ryansch** [comment]
We use two completely different ECS clusters and weighted DNS records in Route53 to enforce the cutover.  Do note that you'll have to run the 'old' cluster at reduced capacity for ~24 hours due to misbehaving DNS clients.

**Comment by maartenvanderhoef** [comment]
@rajasekaran07 Please take a look here : https://github.com/silinternational/ecs-deploy . Codeship has a nice article on it: https://blog.codeship.com/easy-blue-green-deployments-on-amazon-ec2-container-service/ . It is a bit outdated as the use of an ALB with its dynamic port mapping is the way to go now.

**Comment by ryansch** [comment]
I misunderstood.  Sorry we don't blue/green individual services.

**Comment by rajasekaran07** [comment]
@richardpen @maartenvanderhoef Thanks for your input. I had implemented this with two ECS Service with Shared ELB.

Regards,
Raja
