### ISSUE TITLE
How to trigger ECS agent actions through API?

### ISSUE THREAD

**Issue by simplesteph** [aws/amazon-ecs-agent#653]
Hi,

When I look at 
http://boto3.readthedocs.io/en/latest/reference/services/ecs.html#ECS.Client.stop_task

It says it will issue a docker stop with a 30 seconds timeout. I have configured the `ECS_CONTAINER_STOP_TIMEOUT` of the ecs agent to 10m, but apparently this won't be taken into account. Is there a way for me to trigger the ECS agent "stop task" using an API so I the environment variables get taken into account?

Thanks!

**Comment by samuelkarp** [comment]
@simplesteph The `StopTask` API uses the timeout specified in `ECS_CONTAINER_STOP_TIMEOUT`.  We'll get the documentation updated to reflect that (looks like we missed updating the documentation when we added the environment variable).

Are you running into problems using the environment variable or just looking to confirm the behavior?

**Comment by simplesteph** [comment]
Hi I was looking into the behaviour and it wasn't specified. Thanks for
updating the documentation that helps clarifying it !

I think the only issue I'd be running into is that if I issue a docker stop
within the instance it won't take the variable into account ? I think
that's docker related ?

**Comment by samuelkarp** [comment]
Correct, manually issuing `docker stop` is independent of any settings you have on the ECS agent.  To specify a timeout for `docker stop`, you can use the `--time` argument with a number of seconds (see `docker help stop` for details).

**Comment by simplesteph** [comment]
That's what I figured ... Would have been great if defaults were set as the
purpose of the ecs agent and docker are quite close. I don't think the ecs
agent could also set any defaults for docker could it ?

**Comment by samuelkarp** [comment]
We don't modify the behavior of the Docker daemon or Docker CLI; we'd prefer that it match the behavior you'd experience in your development environment.

Thanks for opening this and letting us know our docs were out of date!  Since it sounds like you just wanted that clarified and are not currently experiencing any issues, I'm going to close this.  Please feel free to open new issues if you experience any problems.

**Comment by simplesteph** [comment]
@samuelkarp 
Sorry to follow up, maybe it's not a bug or I'm not doing things right, but it seems that when I terminate the instance using the API, the shutdown command doesn't seem to respect the timeout as dictated by the ecs-agent. Therefore my tasks don't have the time to finish properly. Do you have a workaround for this or is it a bug?

**Comment by simplesteph** [comment]
Actually it should be addressed by https://github.com/docker/docker/pull/23036 and https://github.com/docker/docker/pull/22566. Hopefully AWS will be quick to update to docker 1.13 when it's released... I see we're still at 1.11
