### ISSUE TITLE
Failed switching account for pushing docker image.

### ISSUE THREAD

**Issue by XidongHuang** [aws/amazon-ecs-agent#654]
Hi, I have a question here.
At the beginning I use ECS in one account and it works find. But after I change another aws account and try to push my images from my desktop, the default user still the old one:

`denied: User: arn:aws:iam::xxxxxxxx:yyy/zzz is not authorized to perform:ecr:InitiateLayerUpload on resource: arn:aws:ecr:us-west-2:iiiiiiiii:ooooo/ppppp`

I had tried to change access key in `~/.aws/config` and `~/.aws/credentials` as my new account access key, also set the new role permission to be `AmazonEC2ContainerRegistryFullAccess` and `AdministratorAccess`.
So I think it just need me to switch use configuration some where, please give me some hints.
Thank you so much.

**Comment by nmeyerhans** [comment]
Hi @XidongHuang. It is likely that you need to call `aws ecr get-login` again under the new account, and then run the `docker login` command that is printed. See [the documentation](http://docs.aws.amazon.com/AmazonECR/latest/userguide/Registries.html#registry_auth) for more info.

**Comment by XidongHuang** [comment]
Hi @nmeyerhans, thanks for replying. Yeah, I did tried to do ```aws ecr get-login```  to get account name, password and login to the new account, however, when I tried to push the docker images, it shown:

```denied: User: arn:aws:iam::xxxxxxxx:yyy/zzz is not authorized to perform:ecr:InitiateLayerUpload on resource: arn:aws:ecr:us-west-2:iiiiiiiii:ooooo/ppppp```

I guess there is a default file about the AWS user information in my desktop, I should change that to get the real account switching.

Do you have any ideas for changeing/switching user's information locally? Otherwise I think I have to use another "clean" computer to try to pack my program and push.

**Comment by richardpen** [comment]
@XidongHuang I simply did the same thing without problem, did you retag the image with the new account registry before push? If you change to another account, you need first tag the image with the new account registry. If that is still a problem, could you tell us the steps you did?

Thanks

**Comment by XidongHuang** [comment]
Hi @richardpen , thanks for response. Yes, I followed the push comments that aws guided me, including change the image tag.
So you are using two different aws accounts in a same system? I am using same ssh key for two account, I don't know is it the reason why it does't work.

**Comment by richardpen** [comment]
@XidongHuang Yes, within the same system and here is the steps I did:
```
# Push to the first account
docker pull ubuntu
eval $(aws ecr --profile accout_1 get-login --region us-west-2)
docker tag ubuntu:latest account_1.dir.ecr.us-west-2.amazonaws.com/ubuntu:xxx
docker push account_1.dir.ecr.us-west-2.amazonaws.com/ubuntu:xxx

# push to the second account 
eval $(aws ecr --profile accout_2 get-login --region us-west-2)
docker tag ubuntu:latest account_2.dir.ecr.us-west-2.amazonaws.com/ubuntu:xxx
docker push account_2.dir.ecr.us-west-2.amazonaws.com/ubuntu:xxx
```

**Comment by XidongHuang** [comment]
@richardpen , I did not use ```profile account_name``` before, but how can I find the ```profile account_name```, because I just type my account name(those arn numbers) and it says the ```config profile (xxx) could not be found```

**Comment by richardpen** [comment]
@XidongHuang Please refer the to aws cli setup documentation [here](http://docs.aws.amazon.com/cli/latest/userguide/cli-chap-getting-started.html#cli-multiple-profiles), you can set the credentials for multiple account with the profiles.

**Comment by XidongHuang** [comment]
sorry @richardpen , 

I configured the ```credentials```, added another account with a "profile_name", and I did ```aws ecr --profile profile_name --region us-west-2``` , ```docker login xxxxx(url)``` and tried to do ```docker push xxxx(url)```, then it said:
 ```denied: Your Authorization Token has expired. Please run 'aws ecr get-login' to fetch a new one```, 
so I tried again and even change access key, but it still keep throwing that error....

**Comment by XidongHuang** [comment]
Thanks @richardpen ! I figured it out!
I found the ```authourization token```  in ```~/.docker/config``` was not changed no matter I login so many times. So I deleted the old one, and just followed your process, so I can login and push now, thanks for your patient!

**Comment by apwickrama** [comment]
Had the same issue on Windows 10. Fixed by re-installing AWS CLI.

**Comment by ruwanindika** [comment]
I ran in to the same issue described in  commented on Dec 30, 2016.

It was caused by having multiple aws cli profiles (https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-profiles.html)


arn:aws:iam::xxxxxxxx:yyy/zzz is not authorized  -->  This is the default aws cli account/profile 

resource: arn:aws:ecr:us-west-2:iiiiiiiii:ooooo/ppppp --> this is the second account/profile you are trying to upload files to


adding the --profile option to this initial command of getting credentials fixed the issue 

--> aws ecr get-login-password --region xx-xxx-1 | docker login --username AWS --password-stdin .....

add --profile 

--> aws --profile <my-profile> ecr get-login-password --region xx-xxxx-1    |   docker login --username AWS --password-stdin  ..............

**Comment by virtualbeck** [comment]
Here's a gist I wrote to migrate n number of tagged AWS ECR images across accounts:
[https://gist.github.com/virtualbeck/a635ef6701991f2087384eab7edbb18b](https://gist.github.com/virtualbeck/a635ef6701991f2087384eab7edbb18b)
