### ISSUE TITLE
EC2 Windows Instances for ECS do not register with cluster

### ISSUE THREAD

**Issue by HassanAhmadKhan** [aws/amazon-ecs-agent#660]
I am following this aws article to register ec2 instance with cluster but its not registering, 
http://docs.aws.amazon.com/AmazonECS/latest/developerguide/ECS_Windows_getting_started.html
I am new to ec2 ecs may be doing some mistake but I tried both powershell scripts (mention in this repository and mention in the article) in user data.

**Comment by samuelkarp** [comment]
@HassanAhmadKhan What errors are you seeing when you try to run a Windows instance?  For basic troubleshooting, please provide the following information:

* The AMI ID you launched (you need the "Microsoft Windows Server 2016 Base with Containers" AMI, not the "Microsoft Windows Server 2016 Base" AMI)
* What permissions you granted in the instance profile (you'll need all the permissions [listed here](http://docs.aws.amazon.com/AmazonECS/latest/developerguide/ecs_managed_policies.html#AmazonEC2ContainerServiceforEC2Role))
* The contents of the user data execution log (located at `C:\ProgramData\Amazon\EC2-Windows\Launch\Log\UserdataExecution.log`)
* The contents of the powershell script responsible for starting the ECS agent (located at `C:\ProgramData\Amazon\ECS\log\win-agent-init.log`
* The contents of the ECS agent log (located at `C:\ProgramData\Amazon\ECS\log\ecs-agent.log.*`

**Comment by ejkani** [comment]
It could seem like the "user-data.ps1" script is different than the one you add to "Advanced/User-Data" when creating the instance. So if your Cluster is named something different than "windows", it won't be registered in the cluster. But there seems to be more bugs in how this is set up now, e.g. the aws-agent occupying port 80.

**Comment by samuelkarp** [comment]
@ejkani If you're experiencing problems with Windows, can you answer the same questions that I asked @HassanAhmadKhan above?

> It could seem like the "user-data.ps1" script is different than the one you add to "Advanced/User-Data" when creating the instance.

`user-data.ps1` is an example of what you can add to "Advanced/User-Data" when creating the instance.

>  So if your Cluster is named something different than "windows", it won't be registered in the cluster.

Yes, you should customize the name of the cluster if you want something different.  This is called out in [the documentation](http://docs.aws.amazon.com/AmazonECS/latest/developerguide/ECS_Windows_getting_started.html#launch_windows_container_instance) (see item 10 under Step 2).

> But there seems to be more bugs in how this is set up now, e.g. the aws-agent occupying port 80.

This is a known limitation of using IAM roles for tasks on Windows.  Please see [the documentation](http://docs.aws.amazon.com/AmazonECS/latest/developerguide/windows_task_IAM_roles.html).

**Comment by samuelkarp** [comment]
@HassanAhmadKhan @ejkani We haven't heard back from you in a few days, so I'm going to close this for now.  If you do have the opportunity to answer my questions I'm happy to help.
