### ISSUE TITLE
Intermittent unit-test failure: TestBatchContainerHappyPath()

### ISSUE THREAD

**Issue by liwenwu-amazon** [aws/amazon-ecs-agent#662]
On Windows Platform, unit-test sometimes fails on TestBatchContainerHappyPath() testcase.

Here is the output of failure:
--- FAIL: TestBatchContainerHappyPath (0.01s)
                controller.go:113: no matching expected call: *engine.MockDockerClient.DescribeContainer([containerId])

**Comment by aaithal** [comment]
Should be fixed with #703
