### ISSUE TITLE
ECS Optimized AMI Version does not comply with the documentation

### ISSUE THREAD

**Issue by freedomofkeima** [aws/amazon-ecs-agent#664]
Hi,

Just recently, Docker releases a [security advisory](https://www.twistlock.com/2017/01/11/docker-1-12-6-security-advisory/), which creates [AWS Security Advisory](https://alas.aws.amazon.com/ALAS-2017-783.html) several hours ago.

In the [AWS documentation](http://docs.aws.amazon.com/AmazonECS/latest/developerguide/container_agent_versions.html#ecs-optimized-ami-agent-versions) , each optimized AMI has a specific version of Docker version and `ecs-init` version.

Just now, I tried to launch a new instance with Docker version of `1.11.2` and it suddenly breaks since Docker `1.12.*` removes several existing syntaxes (such as: `--fluentd-tag`). After a bit of investigation, `/etc/cloud/cloud.cfg` contains `repo_upgrade: security`, which enforces dependencies update to `1.12.6`.

Since it's a security problem, I know I should update as fast as possible to the latest one. However, I couldn't launch new instances in the ASG which is also a problem in production. Is there any recommendation to prevent this issue from occurring in the future? And also, I think it's good to write it somewhere in the documentation.

Thank you.

**Comment by richardpen** [comment]
@freedomofkeima We are sorry to hear that the security update impacted your environment. Amazon Linux, on which the ECS Optimized AMI is based, applies security updates automatically on the boot of AMI as described in the [documentation](https://aws.amazon.com/amazon-linux-ami/faqs/#auto_update). This results in an instance based on a previous AMI to have Docker 1.12.6 installed. You can disable the automatic security update by adding following the instruction to your user data [here](https://aws.amazon.com/amazon-linux-ami/faqs/#auto_update):
```
#cloud-config
repo_upgrade: none
 
runcmd:
- [ sh, -c, echo "exclude=docker*" >> /etc/yum.conf ]
```
If you have other user data, please following the instruction [here](http://cloudinit.readthedocs.io/en/latest/topics/format.html) to create Mime multipart archive like this:
```
Content-Type: multipart/mixed; boundary="===============BOUNDARY=="
MIME-Version: 1.0
--===============BOUNDARY==
MIME-Version: 1.0
Content-Type: text/x-shellscript; charset="us-ascii"
Content-Transfer-Encoding: 7bit
Content-Disposition: attachment; filename="standard_userdata.txt"
#!/bin/bash
echo "normal user data script part"
 
--===============BOUNDARY==
MIME-Version: 1.0
Content-Type: text/cloud-config; charset="us-ascii"
Content-Transfer-Encoding: 7bit
Content-Disposition: attachment; filename="cloud-config"
#cloud-config
repo_upgrade: none
 
runcmd:
- [ sh, -c, echo "exclude=docker*" >> /etc/yum.conf ]
--===============BOUNDARY==--
```
 
Thanks,
Richard

**Comment by freedomofkeima** [comment]
@richardpen Thank you for your response and the documentation reference. I have confirmed that the Mime multipart archive could solve this problem. 🍻

**Comment by xrwang** [comment]
@richardpen This was really helpful !
