### ISSUE TITLE
Add `--userns=host` to ECS init/ECS agent default configuration

### ISSUE THREAD

**Issue by mixja** [aws/amazon-ecs-agent#668]
Currently if you enable user namespaces (which is possible with the AWS Community AMI), the ECS agent with the ECS init default configuration will not start with the following error:

`Cannot share the host's network namespace when user namespaces are enabled`

To overcome this you can add the `--userns=host` argument to the Docker run options - note this argument works regardless of whether user namespaces is enabled or not, so is considered a "safe" configuration option.

I have tested running the ECS agent manually with this option added and ECS agent works as expected.  However of course if I reboot the container instance or restart ECS agent using:

`sudo stop ecs`
`sudo start ecs`

Then the ECS agent fails to start. 

Please add this argument to the default ECS agent configuration options to allow ECS agent to work out of the box with user namespaces enabled.

**Comment by richardpen** [comment]
@mixja thanks for letting us know this issue, I have added a feature request for `ecs-init`, please track aws/amazon-ecs-init/issues/76 for update.

thanks,
Richard
