### ISSUE TITLE
Privileged mode support

### ISSUE THREAD

**Issue by johnae** [aws/amazon-ecs-agent#68]
It seems this isn't supported today. I would really like this for running things like vpn:s and such that may need to modify iptables etc.

Is this on the roadmap?

**Comment by cbbarclay** [comment]
Thank you for the input; the features we build are influenced by customer feedback. I cannot commit to a date but we will update this issue with changes to status.

**Comment by johnae** [comment]
My use case is mostly for development. These days I develop from within a docker container so I have all these dependencies like db:s and such in their own containers running on one host, finally I have my dev container to which I connect and do all development - it's all remote. I use a vpn container so I can connect to whatever things I run on there without opening them up to the world. This is also why #2 is important to me since I use mosh to connect rather than ssh.

I have this idea that it'd be nice to just do it all directly on EC2 instead of some server with another hosting provider. This way I could also autoscale this thing so it's not running at night when I'm not working anyway.

**Comment by oharaandrew314** [comment]
Privileged mode is also required to mount EBS volumes.  Since ECS doesn't yet have EBS volume integration, mounting volumes with a helper docker image would have been the next logical solution.

**Comment by austin881** [comment]
I can't mount without `--privileged`. Is this going to make it into ECS anytime soon?

**Comment by bpascard** [comment]
+1

**Comment by liamdon** [comment]
+1

**Comment by kpsmith** [comment]
:+1:

**Comment by damnhandy** [comment]
:+1:  Primary use cases:

* Being using a Docker container to build other containers. If you're using Jekins in a Docker container as part of your CI process to build containers, then the Jenkins container needs to run with `--privileged`
* Running UI processes such as Chrome with tools like Selenium

**Comment by broegner** [comment]
+1

**Comment by x110dc** [comment]
+1 to be able to do all sorts of things, like mounting EBS volumes

**Comment by diemonster** [comment]
+1, mounting EBS volumes, running VPN containers that need to use iptables

**Comment by bcwp** [comment]
+1, mounting EBS volumes.

**Comment by rtrauntvein** [comment]
+1

**Comment by jfeala** [comment]
+1 for mounting EBS volumes or any NFS share

**Comment by sshillo** [comment]
+1

**Comment by davidbitton** [comment]
+1 for mounting GlusterFS volumes. W/O elastic file system working in us-east-1, I need to mount GlusterFS shares; an operation that requires --privileged. Thanks!

**Comment by melaraj2** [comment]
+1 For mounting sshfs volumes in the containers.

**Comment by Molodensky** [comment]
+1

**Comment by owahlen** [comment]
+1

**Comment by bcwp** [comment]
Am I correct in assuming this is coming soon (tm) based off this commit: https://github.com/aws/amazon-ecs-agent/pull/192
Specifically, support for com.amazonaws.ecs.capability.privileged-container?

@samuelkarp :)

**Comment by willsmth** [comment]
+1

**Comment by Jerredr** [comment]
+1

**Comment by samuelkarp** [comment]
Hi @bcwp, yes it is something we are working on - no dates yet though.

**Comment by lightxu** [comment]
+1, Without this we can not mount either EBS or NFS...

**Comment by chaserelock** [comment]
+1

**Comment by simonluijk** [comment]
Please stop with these +1s. I am sure there are others like me that have subscribed to this issue to keep up to date with the process and know when it is complete. Samuel has said that they are working on it, just no dates yet. Your +1s are only spamming everyone.

**Comment by heri16** [comment]
+1 as it is taking too long to implement a simple command flag.

**Comment by samuelkarp** [comment]
Privileged is now available in ECS using the 1.5.0 version of the Agent.  You should now be able to specify whether a container should be privileged in your task definitions in the ECS console.

**Comment by heri16** [comment]
Wow, you guys implemented privileged mode but didn't provide add-cap and drop-cap flags. Please reconsider this poor security decision.

**Comment by liucc52** [comment]
Privileged will cause security problems, I am wondering how your guys resolve it in ecs

**Comment by sithmal** [comment]
Is this available now?
