### ISSUE TITLE
Log format issues

### ISSUE THREAD

**Issue by nmeyerhans** [aws/amazon-ecs-agent#683]
It appears that `agent/tcs/handler.go` underwent an incomplete conversion to seelog in commit c742a29b. This results in some of the logs that it generates being formatted incorrectly. For example:

   2017-01-27T18:39:21Z [INFO] Error from tcs; backing offerrunexpected EOF

generated by line 79:
   log.Info("Error from tcs; backing off", "err", tcsError)

**Comment by samuelkarp** [comment]
[Released](https://github.com/aws/amazon-ecs-agent/releases/tag/v1.14.1)
