### ISSUE TITLE
ECS agents gets updated to latest on new instances

### ISSUE THREAD

**Issue by jamborta** [aws/amazon-ecs-agent#684]
Hi, 

I have been using amzn-ami-2016.03.b-amazon-ecs-optimized (ami-a28476c2) instance which ships with ECS agent v1.9.0 and docker v1.9.1. Just noticed today, that new EC2 instances registered to any ECS cluster get automatically updated to the latest ECS agent and docker, even if it is using the same AMI. 

Is this a feature or a bug? 

If it's a feature it's very inconvenient, as our application is currently not compatible with docker 1.10 or over, I am unable to start a new instance using the correct docker version.

**Comment by jishi** [comment]
EC2 hosts apply the latest security patches on boot, this is done even on the ECS optimized AMI. The Docker upgrade is considered a security patch, that is probably why you are seeing this. 

I guess you would have to try and make your own AMI and remove the security patching at boot, but to me that sounds like a bad idea...

**Comment by aaithal** [comment]
@jamborta, @jishi  is correct. Because of the upgrade being marked as critical to security, your instance got auto-upgraded with docker version 1.12.6. Please see #664 for how to mitigate this. Closing this for now. Feel free to reopen or create a new issue if you need more help. Thanks!
