### ISSUE TITLE
Don't consider other revisions when placing tasks during rollout

### ISSUE THREAD

**Issue by jishi** [aws/amazon-ecs-agent#685]
Not sure if this is agent related, or if this has to do with the service scheduler (thus belong somewhere else), but please inform me where I should direct this question if this is not the appropriate place.

Similar to #225, we run into the issue that during deployment, even with spread on availability zone the remaining task might end up on the same host. 

My conclusion is that it also considers tasks that are scheduled for removal when placing new tasks, meaning taskdefinitions from another revision. This seems wrong to me. 

Consider that you have the following spread (each ECS host is in it's own availability zone):

```
ECS host A:
  taskdefinitionX:1
  taskdefinitionY:1

ECS host B: 
  taskdefinitionX:1
  taskdefinitionY:1

ECS host C:
  -- no tasks
```

Now, when rolling out a new revision of taskdefinitionX, it will consider spread(availability-zone), but since it already has old tasks in AZ A and B, it places two new ones in AZ C (because of resource spread rules):

```
ECS host A:
  taskdefinitionX:1
  taskdefinitionY:1

ECS host B: 
  taskdefinitionX:1
  taskdefinitionY:1

ECS host C:
  taskdefinitionX:2
  taskdefinitionX:2
```

Now, after draining connections on the old tasks, it will subsequently kill the tasks on host A and B:

```
ECS host A:
  taskdefinitionY:1

ECS host B: 
  taskdefinitionY:1

ECS host C:
  taskdefinitionX:2
  taskdefinitionX:2
```

Thus, no longer fulfilling the spread(availability-zone) strategy. 

Now, if it we're to disregard taskdefinitions of older revisions when evaluating the spread, it would be fine. For now, I workaround this by allowing 50%/150% capacity during rollout, but that slows down the rollout process (especially when having a long drain timeout on the ALB target group).

**Comment by jishi** [comment]
Using 50%/150% doesn't seem to fix it completely, it still occasionally end up with 2 tasks on the same machine (oddly enough).

Something else must be broken in terms pf placement strategy.

**Comment by richardpen** [comment]
@jishi Thanks for reporting this, we have identified this is an issue in our backend service. We'll let you know when we have an update.

Thanks,
Richard

**Comment by cabbruzzese** [comment]
@jishi, We've recently deployed a fix that should address this issue. Please reach out to us if you have any further questions or comments on this. Closing issue for now.

**Comment by jishi** [comment]
@cabbruzzese We start to seem the same behavior once again since a couple of weeks ago. Tasks ending up on the same container after deployment even do we enforce spread on AZ on the service. 

Could it be that this issue has been re-introduced?
