### ISSUE TITLE
docker containers should be destroyed when stopped

### ISSUE THREAD

**Issue by radenui** [aws/amazon-ecs-agent#69]
Hi, 

No cleanup is done when the container is stopped or fails: after a couple of minutes, I have up to dozens of failed containers.
Is there a way to reproduce the docker -rm option?

Thanks

**Comment by euank** [comment]
Cleanup, including removal of created containers, is done after a task has been in the 'stopped' state for 3 hours. There isn't currently a way to specify for them to be removed instantly on failure as the rm flag does.

Does that help, or would you still like to see an option for `rm` or configurable cleanup timeout?

**Comment by radenui** [comment]
@euank Ok, thanks, I didn't notice that cleanup. How does it work in the case of services (where the task is theoretically never stopped...)?
And Yes, Maybe a configurable cleanup timeout would be a good thing to have.

Thanks

**Comment by euank** [comment]
Services do not restart the same tasks (a stopped task is terminal; it cannot be restarted), but rather launches new copies of the task when one stops. The copies that exited or failed will be cleaned up after the 3 hour grace period.

If a single instantiated task is long-running and never stops, it will never be cleaned up.

I've created a feature request issue to try and capture your suggestion (#70). Please feel free to ask if you have further questions or give feedback on that issue.

Best,
Euan

**Comment by radenui** [comment]
OK, got it. Thanks!

**Comment by josepharceneaux** [comment]
@euank Can you please confirm the scenario where a service is updated with a new task definition containing an newer image - will the older image be stopped and removed in 3 hours? Thanks.

**Comment by aaithal** [comment]
@josepharceneaux In the scenario that you mentioned, ECS Agent will clean up the stopped container (clean up time can be configured using the `ECS_ENGINE_TASK_CLEANUP_WAIT_DURATION` variable). However, it does not clean up the image that is used to create the container. Image removal is being tracked as a feature request in #118.
