### ISSUE TITLE
Provide metadata to containers

### ISSUE THREAD

**Issue by richardpen** [aws/amazon-ecs-agent#710]
Adding a feature that metadata(container ID, ports, etc) of container can be acquired from within the container.

Related issue #288 and #456.

**Comment by nhmaha** [comment]
+1

**Comment by jtoberon** [comment]
This is addressed in #981.

**Comment by samuelkarp** [comment]
We have released [ECS agent v1.15.0](https://github.com/aws/amazon-ecs-agent/releases/tag/v1.15.0), which adds this feature.  Please see [the documentation](http://docs.aws.amazon.com/AmazonECS/latest/developerguide/container-metadata.html) for information on how to use it.
