### ISSUE TITLE
oci runtime error

### ISSUE THREAD

**Issue by hridyeshpant** [aws/amazon-ecs-agent#712]
i am using AWS console UI to create task def and  added following volumes (name:source path)
1. properties    /root/edda.properties 
2. root             /

and added mount path from Task Definition from UI like below
 "mountPoints": [
        {
          "containerPath": "/tomcat/webapps/ROOT/WEB-INF/classes/app.properties",
          "sourceVolume": "properties",
          "readOnly": null
        }
      ]

and 
"volumes": [
    {
      "host": {
        "sourcePath": "/root/edda.properties"
      },
      "name": "properties"
    },
    {
      "host": {
        "sourcePath": "/"
      },
      "name": "root"
    }
  ],

After running this task_definition, i am getting below error? Am i missing something here ?

```Status reason	CannotStartContainerError: API error (500): invalid header field value "oci runtime error: container_linux.go:247: starting container process caused \"process_linux.go:359: container init caused \\\"rootfs_linux.go:53: mounting \\\\\\\"/root/app.properti```

ecs-agent version : 1.14.0
docker version : 1.12.6 
AMI version : 3.76-2016.09.d

**Comment by nmeyerhans** [comment]
Hi @hridyeshpant. I don't see anything obviously wrong with the task definition fragment you've posted, but I've got a couple of questions:
1. It appears that the docker API error that you provided is truncated. If that's the case, can you provide the complete error?
2. It appears that you're not actually mounting your "root" volume anywhere. Is that the case? Is the behavior any different if you don't define that volume in your task definition?

**Comment by aaithal** [comment]
Hi @hridyeshpant, we haven't heard back from you regarding this for a while. I'm closing this issue for now. Please let us know when you have more information to share with us as per the previous post. Thanks!
