### ISSUE TITLE
Have ECS agent set instance attributes on startup

### ISSUE THREAD

**Issue by kwizzn** [aws/amazon-ecs-agent#713]
I would like the ECS agent to add an instance attribute during startup. My user script sets up the following `/etc/ecs/ecs.config`:

```
ECS_CLUSTER=doodlestory
ECS_INSTANCE_ATTRIBUTES={"purpose":"elasticsearch"}
```

The agent starts correctly and `docker inspect` contains the env:

```
            ...
            "Env": [
                ...
                "ECS_INSTANCE_ATTRIBUTES={\"purpose\":\"elasticsearch\"}",
                ...
            ],
            ...
```

The attribute doesn't get set, however. Ideas greatly appreciated.

**Comment by vsiddharth** [comment]
`ECS_INSTANCE_ATTRIBUTES` are set upon initial registration only

You could additionally check:
* Docker logs to check for any errors
* You could use the [DescribeContainerInstances](http://docs.aws.amazon.com/AmazonECS/latest/APIReference/API_DescribeContainerInstances.html) API and check the response for the attributes

**Comment by nmeyerhans** [comment]
@vsiddharth @kwizzn The ecs agent log would be the more relevant place to look. Should be /var/log/ecs/ecs-agent-*

If there's nothing obvious there, increasing the logging verbosity to "debug" by adding `ECS_LOGLEVEL=debug` to `/etc/ecs/ecs.config` may shed some light on what's going on.

I'll also reiterate what @vsiddharth pointed out, agent attributes are only registered on initial registration. Once the agent has been registered, you can use the [putAttributes](http://docs.aws.amazon.com/AmazonECS/latest/APIReference/API_PutAttributes.html) API call to add additional attributes.

**Comment by kwizzn** [comment]
"initial registration only" was the key, @vsiddharth. As the docs state: "Certain innocuous environment variables [...] can be passed to the container instance *at launch time*". Hope this will help other people as well.

Thank you, guys! :)
