### ISSUE TITLE
Unable to Start Task due to CannotPullContainerError

### ISSUE THREAD

**Issue by shsu** [aws/amazon-ecs-agent#719]
I'm encountering `CannotPullContainerError: Could not reach any registry endpoint` due to hub.docker.com being down. The image we are trying to start is already on the server. (`docker images`) 

Should ecs-agent fallback to local images if available?

**Comment by samuelkarp** [comment]
If the image is already cached, the ECS agent does fall back to that cached image.  Did you see something else happen?

**Comment by shsu** [comment]
Hi @samuelkarp it shows `Essential container in task exited` `error code 0` and reattempts again.

**Comment by shsu** [comment]
Odd, it worked now after scaling the service down then back up.

**Comment by samuelkarp** [comment]
@shsu If there is an exit code, it means that a container did actually run.  If the ECS agent was not able to pull and no image was cached, there would be no exit code.
