### ISSUE TITLE
Volume Cleanup interval

### ISSUE THREAD

**Issue by bastianb** [aws/amazon-ecs-agent#726]
Hello,
It would be nice to have a volume cleanup env var as well.

**Comment by samuelkarp** [comment]
Hi @bastianb, can you provide a bit more detail on what you're looking for in volume cleanup?  Right now, the ECS agent will clean up the volumes along with the containers that used those volumes.

**Comment by bastianb** [comment]
Hi, sure,
I am running docker1.13.1 on centos7 with amazon-ecs-agent:v1.14.0

When I start a service that fails to start containers, it seems that a bunch of containers and volumes are left over, filling the disk rapidly till it gets full and machine unusable. Containers that fail do not get removed immediately nor in a short amount of time, and so do the volumes attached to them.

It would be nice to have either a parameter from ecs-cli to allow a X amount of retries before stopping trying to scale up failing services.
Or make the ecs-agent clean as well those containers/volumes with a configurable threshold
like ECS_IMAGE_MINIMUM_CLEANUP_AGE but for volumes and containers

**Comment by aaithal** [comment]
Hi @bastianb, thank you for providing these details. Just to elaborate @samuelkarp's comment, ECS Agent has a parameter using which you can tune the task clean up duration, which should also clean up volumes and containers associated with the task called `ECS_ENGINE_TASK_CLEANUP_WAIT_DURATION`. The default value is set to `3m` and you can tune it to a value that's less than that. You can read about it in our [README](https://github.com/aws/amazon-ecs-agent/blob/master/README.md#environment-variables) as well. 

However, we recently discovered an issue where containers in "CREATED" state would not be cleaned up properly under certain conditions. We are tracking this in #721. If this is what you were running into as well, it would be really helpful if you could provide ECS Agent logs from your instance. The logs can be gathered using https://github.com/awslabs/ecs-logs-collector. Please send them to aithal at amazon dot com if you do not want to share it publicly. 

I'm resolving this issue for now as we can use #721 to track this.
