### ISSUE TITLE
ECS_INSTANCE_ATTRIBUTES documentation is incorrect

### ISSUE THREAD

**Issue by joshgarnett** [aws/amazon-ecs-agent#727]
ECS_INSTANCE_ATTRIBUTES need to specified as a json object not a json array of objects. The following fails with the error: "Invalid format for ECS_INSTANCE_ATTRIBUTES. Expected a json hash"

```
ECS_INSTANCE_ATTRIBUTES=[{"environment":"dev"}, {"type":"web"}]
```

The correct format is:

```
ECS_INSTANCE_ATTRIBUTES={"environment":"dev", "type":"web"}
```

**Comment by joshgarnett** [comment]
This is wrong in the README.md not at http://docs.aws.amazon.com/AmazonECS/latest/developerguide/ecs-agent-config.html

**Comment by petderek** [comment]
Hi @joshgarnett 

Thanks for reaching out to us. We have fixed this in the in the dev branch, and merging to master is [pending this PR](https://github.com/aws/amazon-ecs-agent/pull/723). Sorry for any confusion this may have caused.
