### ISSUE TITLE
Readme: Add hints about datadir/checkpointing

### ISSUE THREAD

**Issue by seiffert** [aws/amazon-ecs-agent#73]
Hi, 

I've noticed that you can't run the agent reliably/resiliently with the described docker run statement as it is missing a configuration for a persistent datadir. As far as I can see configuring this is necessary if you want a container instance to survive ECS Agent restarts as every new instance of the agent will look for an existing configuration and create a new container instance id if it can't be found. Please correct me if this is wrong.
I would suggest adding a section to the readme (I could create a PR) that explains the usage with checkpointing and the datadir. Also, I'd like to clarify the 'default values' of ECS_DATADIR (it states to be /data/, however checkpointing is only enabled when you explicitly pass ECS_DATADIR).

Cheers,
  Paul

**Comment by euank** [comment]
Your understanding is correct.
I agree that the documentation around that needs improvement. If you want to have a go at it, I'd be happy to look at a PR, though we'd also be happy to do it ourselves. Just let us know if you're going to work on it so we don't step on each other's toes.

Thanks,
Euan

**Comment by seiffert** [comment]
I'll create a PR in a couple of minutes!

**Comment by euank** [comment]
I believe the above-referenced readme improvements should address this issue. If there're remaining concerns, feel free to re-open.
