### ISSUE TITLE
Support Docker API 1.26+ (and Docker CE/EE)

### ISSUE THREAD

**Issue by jharley** [aws/amazon-ecs-agent#733]
With the recent announcement from Docker Inc., `docker-engine`'s days are likely numbered.

`ecs-agent` should likely support API v1.26+ and have support for Docker CE/EE ASAP.

**Comment by samuelkarp** [comment]
@jharley Thanks for opening this.

To clarify something: Docker CE/EE do not remove support for old API versions and the ECS agent should continue to work properly with new versions of Docker.

Is there something specific you're looking for in the 1.26+ API in ECS, or are you just looking for confirmation that ECS will continue to work?

**Comment by jharley** [comment]
I reported this after accidentally updating our ECS AMI to Docker CE 17.03 and having ecs-agent failing to register because it could not communicate with dockerd.  I believe this was ecs-agent 1.14, however.  Should this be resolved in 1.14.1?

**Comment by samuelkarp** [comment]
@jharley Can you provide logs of what was failing?  Nothing related to Docker CE changed between 1.14.0 and 1.14.1; 1.14.0 should also work with Docker CE.

**Comment by andyt10** [comment]
I too came across this issue when updating AMIs. The containers that didn't have the docker API requirement worked, but those with com.amazonaws.ecs.capability.docker-remote-api would not place, talking of 'missing attributes'.

**Comment by jhaynes** [comment]
@andyt10 and/or @jharley can you provide the output of `docker info` and `docker version` as well as the container instance arn and any relevant logs? If you're not comfortable posting that information here, please feel free to email me at `jushay@amazon.com`

**Comment by samuelkarp** [comment]
@jharley @andyt10 Are you able to provide logs and the information that @jhaynes requested?

**Comment by jharley** [comment]
Sorry for the delay: I'll try to get this tomorrow. 👍

**Comment by jharley** [comment]
As of ecs-agent 1.14.2 Docker CE is working fine: I'm not 100% certain what has changed, but this is a resolved issue. Thanks for the diligence :+1:
