### ISSUE TITLE
Update docker-storage-setup on AWS ECS AMI

### ISSUE THREAD

**Issue by blaines** [aws/amazon-ecs-agent#741]
Sorry wasn't sure where to put something more AMI specific. I just want to put this on your radar.

https://github.com/projectatomic/container-storage-setup/issues/235

Using an `i3` instance, it's coming online just fine with no apparent error but the docker volume group is not being created. In my case, this leads to the instance root volume becoming full very quickly. Having dug in the cloud-init logs, I found this message: `ERROR: Partition specification unsupported at this time.` due to a bug in how they identify devices from partitions.

**Comment by samuelkarp** [comment]
Thanks for letting us know.  We're watching your bug report with container-storage-setup now.

**Comment by dmitry-livchak** [comment]
Dear AWS, do you think may be addressed soon? It looks like ECS is missing out a lot while not being able to utilise NVMe disks of I3 instance types.

**Comment by samuelkarp** [comment]
https://github.com/projectatomic/container-storage-setup/pull/234 was merged.  We'll need to get a new version of docker-storage-setup/container-storage-setup prepared for Amazon Linux.

**Comment by samuelkarp** [comment]
Apologies for not closing this sooner, but `docker-storage-setup-0.6.0-1.16.giteb688d4.amzn1.noarch` was released in the 2017.03.f release of the ECS-optimized AMI.  I'm going to close this for now as it should be resolved, but feel free to re-open if you continue to experience issues.
