### ISSUE TITLE
Docker run flags aren't available

### ISSUE THREAD

**Issue by Spareo** [aws/amazon-ecs-agent#754]
We have containerized a legacy application which requires the `-it` flags from docker run to keep the container alive. I can not for the life of me find out how to replicate this feature in AWS ECS tasks. If this already exists, please point me towards the documentation.

**Comment by richardpen** [comment]
@Spareo Thanks for reaching out, currently the `-ti` option isn't supported on ECS. There is already  a feature request #462 that should handle your use case. I'm closing this for now, please track #462 for any updates, thanks.

**Comment by samuelkarp** [comment]
@Spareo A bit more detail here: the `-i` flag is short for `--interactive`; ECS today does not expose any interactivity with containers.  The `-t` flag is short for `--tty` and allocates a pseudo-TTY; ECS does not support allocating a pseudo-TTY today.  It's probably worth figuring out if your legacy application depends on interactivity or just on the pseudo-TTY.

**Comment by Spareo** [comment]
I actually got it working earlier this morning. After researching some more about TTY I was able to get a poweshell script to start the executable correctly such that it allowed the container to stay alive. 

The container is running a c# app that launches a legacy app. The c# basically kicks of a polling mechanism on a separate thread but uses Console.ReadLine() to stay running. 

I was able to launch the process from the poweshell script using ProcessStartInfo to redirect just the standard INPUT. I tried every other option before it occurred to me just redirect the input and they all resulted in the process exiting immediately.

**Comment by samuelkarp** [comment]
> I actually got it working earlier this morning.

Awesome, glad to hear it!

> poweshell

I assume this is on Windows using our [beta](http://docs.aws.amazon.com/AmazonECS/latest/developerguide/ECS_Windows.html)?  Please feel free to let us know if you run into any other problems; we're keeping track of Windows-specific issues [here](https://github.com/aws/amazon-ecs-agent/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aopen%20label%3Awindows).

**Comment by Spareo** [comment]
Ok will do, it has been running fine since I got the container to stay alive. Going to try to get the autocaling stuff setup tomorrow. Thanks again!

**Comment by revmischa** [comment]
@richardpen You say track #462 for updates but it's been closed. Please reconsider adding support for PTTY allocation of containers. All it takes is one flag!
