### ISSUE TITLE
intermittent integ-test failure: TestImageWithSameNameAndDifferentID

### ISSUE THREAD

**Issue by adnxn** [aws/amazon-ecs-agent#759]
on windows, this test fails on panic with timeout error. see [logs](https://gist.github.com/adnxn/033baee38691139964f443867c478af1) for more information. i suspect there is a race condition between [verifyTaskIsStopped](https://github.com/aws/amazon-ecs-agent/blob/467c3d772d55e02ad618e4901afed1da1173496e/agent/engine/engine_integ_test.go#L253) and [verifyTaskIsRunning](https://github.com/aws/amazon-ecs-agent/blob/467c3d772d55e02ad618e4901afed1da1173496e/agent/engine/engine_integ_test.go#L232) being invoked in the [TestImageWithSameNameAndDifferentID](https://github.com/aws/amazon-ecs-agent/blob/467c3d772d55e02ad618e4901afed1da1173496e/agent/engine/docker_image_manager_integ_test.go#L279) test.

**Comment by samuelkarp** [comment]
Released in [v1.14.2](https://github.com/aws/amazon-ecs-agent/releases/tag/v1.14.2).
