### ISSUE TITLE
Core OS Cleanup not working

### ISSUE THREAD

**Issue by optimisticanshul** [aws/amazon-ecs-agent#762]
On Container Linux by CoreOS stable (1298.7.0) ECS_ENGINE_TASK_CLEANUP_WAIT_DURATION isn't working ECS agent isn't cleaning up old docker containers.

**Comment by richardpen** [comment]
@optimisticanshul Thanks for reporting this to us, normally ECS Agent will clean up the containers of the task after the task has been stopped for some time set by `ECS_ENGINE_TASK_CLEANUP_WAIT_DURATION`, see [documentation](http://docs.aws.amazon.com/AmazonECS/latest/developerguide/automated_image_cleanup.html) for details. If the container isn't cleaned up after the duration, there may be either agent didn't call `docker rm` to remove the container or the `docker rm` failed.

Could you provide us the container id that isn't cleaned up, the Docker log collected by `journalctl -u docker.service` and ECS Agent logs located in the log directory specified by `--volume=/var/log/ecs:/log` when you start thee ECS Agent. Please send to me at penyin (at) amazon.com if you don't want to share publicly.

Thanks,
Richard

**Comment by optimisticanshul** [comment]
@richardpen Thank you for quick response i will send you all the logs from ```optimisitcanshul@gmail.com```
Actually sorry for misreporting it's deleting old stopped containers.

**Comment by cabbruzzese** [comment]
@optimisticanshul Thanks for the update. Are you still experiencing this issue?

**Comment by optimisticanshul** [comment]
@cabbruzzese Yes my issue still persists.

**Comment by optimisticanshul** [comment]
Let me know what info you guys need to solve i am willing to provide all the logs.

**Comment by cabbruzzese** [comment]
@optimisticanshul, sorry about the confusion. Just to clarify, are you seeing containers that belong to a Task that has been stopped, but those containers are not being cleaned up after the timeout defined in ECS_ENGINE_TASK_CLEANUP_WAIT_DURATION? If that is the case, are those containers in an exited state?

Can you provide the version of the ECS agent that you are using? These [Instructions](http://docs.aws.amazon.com/AmazonECS/latest/developerguide/ecs-agent-update.html#checking_agent_version) will help you find the agent version.

It would be helpful to see the agent logs. Information on retrieving the instructions can be found in the following [documentation](http://docs.aws.amazon.com/AmazonECS/latest/developerguide/troubleshooting.html#logs). Or you can collect them using the [ECS Logs Collector](http://docs.aws.amazon.com/AmazonECS/latest/developerguide/troubleshooting.html#ecs-logs-collector).

The docker version (sudo docker version) and output of docker info (sudo docker info) would also help. 

If you are not comfortable posting it publicly on GitHub, you can email it directly to me at abbrcale at amazon.com.

**Comment by optimisticanshul** [comment]
Guys i am aware of ECS using it from last 1+ production workload of 100+ services so i am aware of it how it works and that's why i raised this issue on CoreOS it's not working as expected but on AMAZON AMI it's working.

**Comment by aaithal** [comment]
Hi @optimisticanshul,

Apologies for the delayed follow-up here. I tried running an ECS Task on a 
CoreOS instance to try and reproduce the issue that you seem to be running into.

IIUC, ECS Agent's cleanup functionality is not working for you on your CoreOS 
instance. However, I was unable to reproduce this on my setup and as you can 
see from the logs, both the container and the image got cleaned up when the task
stopped.

Here's my work log:
1. Register a CoreOS instance to my ECS cluster. On the instance, you can see 
the ECS Agent running. Please note that this Agent is configured to do image 
clean-up every 10 minutes, on images that are 10 minutes old. It's also 
configured to clean up stopped containers 10 minutes after they are stopped:
```bash
core@ip-172-31-47-65 ~ $ cat ecs.config
ECS_CLUSTER=gh762
ECS_LOGFILE=/log/ecs-agent.log
ECS_DATADIR=/data
ECS_LOGLEVEL=debug
ECS_ENGINE_TASK_CLEANUP_WAIT_DURATION=10m
ECS_IMAGE_CLEANUP_INTERVAL=10m
ECS_IMAGE_MINIMUM_CLEANUP_AGE=10m

core@ip-172-31-47-65 ~ $ docker run --name ecs-agent -d \
 --volume=/var/run/docker.sock:/var/run/docker.sock \
 --volume=/home/core/ecs:/log --volume=/home/core/ecs/data:/data --net host \
 --env-file ecs.config amazon/amazon-ecs-agent:latest

core@ip-172-31-47-65 ~ $ date
Tue May  2 18:11:28 UTC 2017
core@ip-172-31-47-65 ~ $ docker images
REPOSITORY                TAG                 IMAGE ID            CREATED             SIZE
amazon/amazon-ecs-agent   latest              33e15d7cd0ca        7 weeks ago         8.33 MB

core@ip-172-31-47-65 ~ $ docker ps
CONTAINER ID        IMAGE                            COMMAND             CREATED              STATUS              PORTS               NAMES
7acabaea10fc        amazon/amazon-ecs-agent:latest   "/agent"            About a minute ago   Up About a minute                       ecs-agent
```

2. Start a task on this instance and wait for it to actually run on the 
instance:
```bash
core@ip-172-31-47-65 ~ $ date
Tue May  2 18:13:30 UTC 2017
core@ip-172-31-47-65 ~ $ docker ps
CONTAINER ID        IMAGE                            COMMAND                  CREATED             STATUS              PORTS               NAMES
4a078eca5a1e        nginx                            "nginx -g 'daemon off"   19 seconds ago      Up 18 seconds       80/tcp              ecs-nginx-1-nginx-928befcd9fe8bcc5ab01
7acabaea10fc        amazon/amazon-ecs-agent:latest   "/agent"                 3 minutes ago       Up 3 minutes                            ecs-agent
```

3. Stop the task. Here's the `describe-tasks` output from my console:
```
{
    "failures": [],
    "tasks": [
        {
            "taskArn": "arn:aws:ecs:us-west-2:XXX:task/YYY",
            "group": "family:nginx",
            "overrides": {
                "containerOverrides": [
                    {
                        "name": "nginx"
                    }
                ]
            },
            "lastStatus": "STOPPED",
            "containerInstanceArn": "arn:aws:ecs:us-west-2:XXX:container-instance/XXX",
            "createdAt": 1493748786.493,
            "version": 6,
            "clusterArn": "arn:aws:ecs:us-west-2:746413922013:cluster/AAA",
            "startedAt": 1493748794.562,
            "desiredStatus": "STOPPED",
            "stoppedReason": "Task stopped by user",
            "taskDefinitionArn": "arn:aws:ecs:us-west-2:XXX:task-definition/nginx:1",
            "containers": [
                {
                    "containerArn": "arn:aws:ecs:us-west-2:XXX:container/BBB",
                    "taskArn": "arn:aws:ecs:us-west-2:746413922013:task/YYY",
                    "name": "nginx",
                    "networkBindings": [],
                    "lastStatus": "STOPPED",
                    "exitCode": 0
                }
            ],
            "stoppedAt": 1493748839.817
        }
    ]
}
```

4. On the instance, ensure that the `nginx` container is stopped as well (you 
can also see that the image is still cached on the disk):
```bash
core@ip-172-31-47-65 ~ $ date
Tue May  2 18:15:39 UTC 2017

core@ip-172-31-47-65 ~ $ docker ps -a
CONTAINER ID        IMAGE                            COMMAND                  CREATED             STATUS                          PORTS               NAMES
4a078eca5a1e        nginx                            "nginx -g 'daemon off"   2 minutes ago       Exited (0) About a minute ago                       ecs-nginx-1-nginx-928befcd9fe8bcc5ab01
7acabaea10fc        amazon/amazon-ecs-agent:latest   "/agent"                 5 minutes ago       Up 5 minutes                                        ecs-agent

core@ip-172-31-47-65 ~ $ docker images
REPOSITORY                TAG                 IMAGE ID            CREATED             SIZE
nginx                     latest              46102226f2fd        7 days ago          109.4 MB
amazon/amazon-ecs-agent   latest              33e15d7cd0ca        7 weeks ago         8.33 MB

core@ip-172-31-47-65 ~ $ sudo cat ecs/data/ecs_agent_data.json  | jq -r '.Data.TaskEngine.ImageStates'
[
  {
    "Image": {
      "ImageID": "sha256:46102226f2fd547f5bbabfcd3dac62cd0d3b7cc33a37a40dae38e088fbb70a38",
      "Names": [
        "nginx"
      ],
      "Size": 109365007
    },
    "PulledAt": "2017-05-02T18:13:14.316153695Z",
    "LastUsedAt": "2017-05-02T18:13:14.316154719Z"
  }
]
```

5. Image gets cleaned up after the cleanup duration. Here are the ECS Agent 
logs and docker commands on the host that prove that the image and container 
were cleaned up:
```
$ grep -ri image ecs/ | grep INFO
grep: ecs/data/ecs_agent_data.json: Permission denied
ecs/ecs-agent.log.2017-05-02-18:2017-05-02T18:13:14Z [INFO] Adding image name- nginx to Image state- sha256:46102226f2fd547f5bbabfcd3dac62cd0d3b7cc33a37a40dae38e088fbb70a38
ecs/ecs-agent.log.2017-05-02-18:2017-05-02T18:13:14Z [INFO] Updating container reference nginx in Image State - sha256:46102226f2fd547f5bbabfcd3dac62cd0d3b7cc33a37a40dae38e088fbb70a38
ecs/ecs-agent.log.2017-05-02-18:2017-05-02T18:20:32Z [INFO] No eligible images for deletion for this cleanup cycle
ecs/ecs-agent.log.2017-05-02-18:2017-05-02T18:20:32Z [INFO] End of eligible images for deletion
ecs/ecs-agent.log.2017-05-02-18:2017-05-02T18:23:59Z [INFO] Removing Container Reference: nginx from Image State- sha256:46102226f2fd547f5bbabfcd3dac62cd0d3b7cc33a37a40dae38e088fbb70a38
ecs/ecs-agent.log.2017-05-02-18:2017-05-02T18:30:32Z [INFO] Candidate image for deletion: &{Image:0xc420379dd0 Containers:[] PulledAt:2017-05-02 18:13:14.316153695 +0000 UTC LastUsedAt:2017-05-02 18:23:59.797518714 +0000 UTC updateLock:{w:{state:0 sema:0} writerSem:0 readerSem:0 readerCount:0 readerWait:0}}
ecs/ecs-agent.log.2017-05-02-18:2017-05-02T18:30:32Z [INFO] Found 1 eligible images for deletion
ecs/ecs-agent.log.2017-05-02-18:2017-05-02T18:30:32Z [INFO] Removing Image: nginx
ecs/ecs-agent.log.2017-05-02-18:2017-05-02T18:30:32Z [INFO] Image removed: nginx
ecs/ecs-agent.log.2017-05-02-18:2017-05-02T18:30:32Z [INFO] Removing Image State: sha256:46102226f2fd547f5bbabfcd3dac62cd0d3b7cc33a37a40dae38e088fbb70a38 from Image Manager
ecs/ecs-agent.log.2017-05-02-18:2017-05-02T18:30:32Z [INFO] No eligible images for deletion for this cleanup cycle
ecs/ecs-agent.log.2017-05-02-18:2017-05-02T18:30:32Z [INFO] End of eligible images for deletion
ecs/ecs-agent.log.2017-05-02-18:2017-05-02T18:40:32Z [INFO] No eligible images for deletion for this cleanup cycle
ecs/ecs-agent.log.2017-05-02-18:2017-05-02T18:40:32Z [INFO] End of eligible images for deletion
ecs/ecs-agent.log.2017-05-02-18:2017-05-02T18:50:32Z [INFO] No eligible images for deletion for this cleanup cycle
ecs/ecs-agent.log.2017-05-02-18:2017-05-02T18:50:32Z [INFO] End of eligible images for deletion

core@ip-172-31-47-65 ~ $ date
Tue May  2 18:31:02 UTC 2017

core@ip-172-31-47-65 ~ $ docker images
REPOSITORY                TAG                 IMAGE ID            CREATED             SIZE
amazon/amazon-ecs-agent   latest              33e15d7cd0ca        7 weeks ago         8.33 MB
```

Could it be the case that you need to configure the values for the cleanup 
configuration variables properly (`ECS_ENGINE_TASK_CLEANUP_WAIT_DURATION`, 
`ECS_IMAGE_CLEANUP_INTERVAL` and `ECS_IMAGE_MINIMUM_CLEANUP_AGE` all of which 
have higher durations set by default) and that's why the results are not 
matching your expectations? If you have ECS Agent logs from the instance where 
you're seeing these issues, please share them with us as well. You can send 
them to aithal at amazon dot com if you don't want to share them publicly.

Thanks,
Anirudh

**Comment by samuelkarp** [comment]
@optimisticanshul Are you still running into problems here?  If so, can you answer @aaithal's questions?

**Comment by samuelkarp** [comment]
@optimisticanshul We haven't heard back from you in a while, so I'm going to close this issue for now.  If you have a chance to answer @aaithal's questions, we'd be happy to re-open the issue and continue investigation.
