### ISSUE TITLE
Persistent Data Volume pointing to /dev/xvdcz EBS Volume

### ISSUE THREAD

**Issue by pocman** [aws/amazon-ecs-agent#766]
Hi,

I would like to know how to use the second EBS volume `/dev/xvdcz` as [persistent storage](https://docs.aws.amazon.com/AmazonECS/latest/developerguide/using_data_volumes.html).

Reading [launch_container_instance](http://docs.aws.amazon.com/AmazonECS/latest/developerguide/launch_container_instance.html), I understand that _two volumes are configured. The Root volume is for the operating system's use, and the second Amazon EBS volume (attached to /dev/xvdcz) is for Docker's use._

I would like to know how I can define my task such that the host sourcePath point to the volume attached to `/dev/xvdcz` (200Go) and not to the Root Volume (8Go).

```
  "volumes": [
    {
      "host": {
        "sourcePath": "/data"
      },
      "name": "data"
    }
  ],
```

```
[ec2-user@ip-172-31-19-170 /]$ docker info
Containers: 1
 Running: 1
 Paused: 0
 Stopped: 0
Images: 1
Server Version: 1.12.6
Storage Driver: devicemapper
 Pool Name: docker-docker--pool
 Pool Blocksize: 524.3 kB
 Base Device Size: 10.74 GB
 Backing Filesystem: ext4
 Data file: 
 Metadata file: 
 Data Space Used: 335.5 MB
 Data Space Total: 212.4 GB
 Data Space Available: 212 GB
 Metadata Space Used: 241.7 kB
 Metadata Space Total: 218.1 MB
 Metadata Space Available: 217.9 MB
 Thin Pool Minimum Free Space: 21.24 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: true
 Deferred Deletion Enabled: true
 Deferred Deleted Device Count: 0
 Library Version: 1.02.93-RHEL7 (2015-01-28)
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: null host bridge overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options:
Kernel Version: 4.4.51-40.58.amzn1.x86_64
Operating System: Amazon Linux AMI 2016.09
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 14.94 GiB
Name: ip-172-31-19-170
ID: AJ56:WEJM:YWZZ:PNMB:PWRJ:ZIVU:IN6P:E6V7:A4DE:RRFS:OJ7E:KTQH
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Insecure Registries:
 127.0.0.0/8
```

**Comment by samuelkarp** [comment]
Hi @pocman,

`/dev/xvdcz` is used for Docker's layer storage (images and container write layers), not for volumes.  If you want to use a separate EBS volume for your on-disk application storage, you can attach another EBS volume to your instance.  Note that you'll need to restart Docker after mounting that new volume on the host for Docker to be able to see it.

Sam

**Comment by Pluies** [comment]
For future reference (and because I was so confused!): the answer above is true only for some versions of the ECS-optimised AMI, and it's _very much not true_ for the newer Amazon Linux 2-based ECS-optimised AMIs!

All the details are on the official documentation: https://docs.aws.amazon.com/AmazonECS/latest/developerguide/ecs-ami-storage-config.html
