### ISSUE TITLE
Feature Request: Support Logentries Log Driver

### ISSUE THREAD

**Issue by grothja** [aws/amazon-ecs-agent#768]
Once Docker 1.13+ is supported, it would be great if [Logentries](https://docs.docker.com/engine/admin/logging/logentries) was added as an approved driver.

**Comment by opsline-radek** [comment]
I just created a PR for this: https://github.com/aws/amazon-ecs-agent/pull/870

**Comment by adnxn** [comment]
#870 has already been merged. @opsline-radek thanks for the pr! =]
