### ISSUE TITLE
ecs-agent doesn't report the actual memory remaining on an instance

### ISSUE THREAD

**Issue by jharley** [aws/amazon-ecs-agent#769]
I currently have an ECS instance reporting 2870MB of available memory in the ECS dashboard, but `free -m` on the host is showing 277MB.  The tasks being placed in this cluster do have min and max memory values set, but this sort of incorrect reporting is occasionally crashing instances.

**Comment by cabbruzzese** [comment]
Thanks for reporting this, we have identified this is an issue in our backend service. We'll let you know when we have an update.

**Comment by jharley** [comment]
Any update on this?  We're having instances die on a daily basis as a result of this bug.

**Comment by aaithal** [comment]
Hi @jharley, there was some confusion on what this issue was about and it was wrongly marked as a bug. To give you more context, the metrics that we surface in Cloudwatch for ECS are all percentages and we don't emit raw `MB` values. So, unless I misunderstand what you're saying, you're probably referring to is the [`remainingResources`](http://docs.aws.amazon.com/AmazonECS/latest/APIReference/API_ContainerInstance.html)  field from [`DescribeContainerInstances`](http://docs.aws.amazon.com/AmazonECS/latest/APIReference/API_DescribeContainerInstances.html) API in the console. ECS doesn't keep a track of processes that are being executed outside the knowledge of the ECS Agent. If you want to ensure that you have some memory on the instance set aside for such processes, you can use the `ECS_RESERVED_MEMORY` configuration variable to set to it a value that makes sense to you, which will ensure that you have enough head room to run processes outside the context of ECS.  Please refer to our [documentation](http://docs.aws.amazon.com/AmazonECS/latest/developerguide/bootstrap_container_instance.html) for more details on how to set such configuration variables. Again, we apologize for the confusion here. Please let us know if these steps help resolve your use-case.

Thanks,
Anirudh

**Comment by jharley** [comment]
I was referring to the ECS Cluster dashboard and not CloudWatch.  The 'ECS Instances' tab of the Cluster dashboard shows CPU and memory available on the instances in the cluster.  I assumed that these values are they used by the ECS scheduler to determine where to place containers.

If that is a case, because the metrics don't reflect the actual resource availability on the instances themselves, containers are being launched on hosts without the memory available and the instances are dying.

I've just had this happen again today during a rolling upgrade.  It seems to me the job of the scheduler (and the agent by extension) is to know the actual resource levels in the cluster (these boxes have `ECS_RESERVED_MEMORY` set, but not to 50% of the instance's memory which would seem to be the only way to make this work, and be a waste of resources at the same time).

A box in one of my cluster's is currently reporting 3.7GB of RAM available on the ECS dashboard, but `free -m` on the box is showing 1.5GB.  If I were to launch a container with a 2GB memory footprint right now, that instance would die if selected by the scheduler.

**Comment by aaithal** [comment]
>I was referring to the ECS Cluster dashboard and not CloudWatch. The 'ECS Instances' tab of the Cluster dashboard shows CPU and memory available on the instances in the cluster. 

Got it, thanks. That aligns with my explanation form the earlier post. To elaborate on what I said earlier, when the ECS Agent registers a container instance, it collects the system information about how much memory is associated with the host (not utilization, just the instance memory size) and subtracts `ECS_RESERVED_MEMORY` and registers the instance with ECS. For example, if you've launched a `c4.large` instance and set `ECS_RESERVED_MEMORY` to `250MiB`, the ECS Agent registers the instance with `3.5GiB` memory. 

The resource accounting from this point, is always done wrt to what's reserved on the instance based on the tasks that are scheduled on the instance. For example, a single-container task definition, which has defined the `memory` parameter as `500 MB` reduces the available memory on this instance to `3 GB`. Note that the container might actually be using only `100 MB` out of the available `500 MB`, but the scheduler still considers the reservation and not the utilization. 

This behavior somewhat differs when the container registers itself with the `memoryReservation` parameter. The `memory` parameter imposes a ceiling limit on how much memory can be used by a container as any breach of the same results in it getting OOM killed. However, `memoryReservation` doesn't impose any such penalty. If in the above example, the container was registered with `memoryReservation` set to `500 MB` and this was the only container running on the host, it could burst very close to `3.75 GB` and still not get killed. Here, the `500 MB` is only being used to make a placement decision. The important thing to note here is that ECS scheduler only considers the reservations when making placement decisions and not actual usage. 

Can you please confirm if you've used `memoryReservation` in your task definition as that would explain the behavior that you're seeing? If you want hard limits on how much memory a container has to use, please consider using the `memory` parameter instead.

**Comment by jharley** [comment]
All of our tasks set `memory` and `memoryReservation`: the difference is about a gigabyte.  Perhaps they should be set to the same value?

I understand how `ECS_RESERVED_MEMORY` works: we set it (as I mention above) on all of our machines to 512MiB.  It seems "wrong" to set this to 30% of instance memory or something, but maybe the is the safer thing to do.

`The important thing to note here is that ECS scheduler only considers the reservations when making placement decisions and not actual usage.`

Why does the agent not take the state of the instance into account, the data is readily available in the kernel and would provide far better, and safer, placement?

If ECS doesn't actually know the state of our instances and is throwing work at them, then we can't trust it to make safe and informed decisions.

**Comment by aaithal** [comment]
> All of our tasks set memory and memoryReservation: the difference is about a gigabyte. Perhaps they should be set to the same value?

As per the `memoryReservation`[proposal](https://github.com/aws/amazon-ecs-agent/issues/155#issuecomment-232227172):

- For container definitions with `memoryReservation`, we use `memoryReservation` as the placement constraint in place of the `memory` field

This is essentially what you're running into as `memoryReservation` doesn't impose a hard limit like `memory` does, thus providing a mechanism for customers to oversubscribe memory on a container instance. 

If you do want to impose hard memory limits and do not want to oversubscribe the memory in this manner, you can switch to using just `memory` in your task definition. This is mostly what I meant earlier when I said reservations being considered for placement. There are also other considerations that are relevant and are documented in the proposal linked above when using `memoryReservation`.

**Comment by samuelkarp** [comment]
@jharley It looks like @aaithal answered the question that you had, so I'll go ahead and close this issue now.  If you have additional questions, please feel free to comment here or to open a new issue.
