### ISSUE TITLE
Filter tasks returned by introspection API by short container ID

### ISSUE THREAD

**Issue by mhurne** [aws/amazon-ecs-agent#770]
It'd be convenient to be able to provide a _short_ container ID when using the `dockerid` query param with the `/tasks` endpoint of the agent introspection API. Currently, it seems only full container IDs are supported.

When accessing the introspection API from within a container to get information about that container, we are hitting the `/tasks` endpoint and finding the relevant task where the `DockerId` starts with the value of the container's `HOSTNAME`. The `HOSTNAME` is the _short_ container ID. If we could provide the value of the `HOSTNAME` as the `dockerid` we wouldn't need to sift through all of the tasks running on the container instance.

**Comment by samuelkarp** [comment]
Released in [v1.14.2](https://github.com/aws/amazon-ecs-agent/releases/tag/v1.14.2).

**Comment by mhurne** [comment]
@samuelkarp Do you know if there's an updated Amazon ECS-Optimized AMI available that includes agent version v1.14.2 yet? Is it in amzn-ami-2016.09.g-amazon-ecs-optimized, which is the latest according to http://docs.aws.amazon.com/AmazonECS/latest/developerguide/ecs-optimized_AMI_launch_latest.html?

**Comment by vsiddharth** [comment]
@mhurne We do have an updated AMI with agent version v1.14.2 but we discovered a deadlock #833 which was addressed with #836 and we plan to publish new AMIs as soon as possible.
