### ISSUE TITLE
can a single ec2 instance host multiple agents/container instances?

### ISSUE THREAD

**Issue by mkleint** [aws/amazon-ecs-agent#782]
We've got an error in our codebase that hints at AWS ECS returning 2 ECS container Instances for a single EC2 instance through the AWS API. We use the java aws library at version 1.11.42.

in our code we list all container instances in the cluster in question and we describe them, we put all these ContainerInstance objects in a list and then convert them to map where e2instanceId is the key and ContainerInstance is the value:

```java
Map<String, ContainerInstance> containerInstances = getClusterContainerInstances(cluster).stream().collect(Collectors.toMap(ContainerInstance::getEc2InstanceId, Function.identity()));
```

(the entire code in attachment) [code.txt](https://github.com/aws/amazon-ecs-agent/files/960343/code.txt)

This code kept failing earlier today with:

```java
Runtime Exception java.lang.IllegalStateException: Duplicate key {ContainerInstanceArn: arn:aws:ecs:us-east-1:081862267333:container-instance/d547ad1d-ad29-4ea2-841c-3b07a7c636fa,Ec2InstanceId: i-0fd4ff089700a0857,VersionInfo: {AgentVersion: 1.14.1,AgentHash: 467c3d7,DockerVersion: DockerVersion: 1.12.6},RemainingResources: [{Name: CPU,Type: INTEGER,DoubleValue: 0.0,LongValue: 0,IntegerValue: 40960,StringSetValue: []}, {Name: MEMORY,Type: INTEGER,DoubleValue: 0.0,LongValue: 0,IntegerValue: 161059,StringSetValue: []}, {Name: PORTS,Type: STRINGSET,DoubleValue: 0.0,LongValue: 0,IntegerValue: 0,StringSetValue: [22, 2376, 2375, 51678, 51679]}, {Name: PORTS_UDP,Type: STRINGSET,DoubleValue: 0.0,LongValue: 0,IntegerValue: 0,StringSetValue: []}],RegisteredResources: [{Name: CPU,Type: INTEGER,DoubleValue: 0.0,LongValue: 0,IntegerValue: 40960,StringSetValue: []}, {Name: MEMORY,Type: INTEGER,DoubleValue: 0.0,LongValue: 0,IntegerValue: 161059,StringSetValue: []}, {Name: PORTS,Type: STRINGSET,DoubleValue: 0.0,LongValue: 0,IntegerValue: 0,StringSetValue: [22, 2376, 2375, 51678, 51679]}, {Name: PORTS_UDP,Type: STRINGSET,DoubleValue: 0.0,LongValue: 0,IntegerValue: 0,StringSetValue: []}],Status: ACTIVE,AgentConnected: true,RunningTasksCount: 0,PendingTasksCount: 0,Attributes: [\{Name: ecs.availability-zone,Value: us-east-1d}, \{Name: com.amazonaws.ecs.capability.logging-driver.syslog,}, \{Name: ecs.instance-type,Value: m4.10xlarge}, \{Name: ecs.ami-id,Value: ami-275ffe31}, \{Name: com.amazonaws.ecs.capability.task-iam-role-network-host,}, \{Name: com.amazonaws.ecs.capability.logging-driver.awslogs,}, \{Name: com.amazonaws.ecs.capability.privileged-container,}, \{Name: com.amazonaws.ecs.capability.docker-remote-api.1.17,}, \{Name: com.amazonaws.ecs.capability.docker-remote-api.1.18,}, \{Name: com.amazonaws.ecs.capability.docker-remote-api.1.19,}, \{Name: com.amazonaws.ecs.capability.ecr-auth,}, \{Name: com.amazonaws.ecs.capability.docker-remote-api.1.20,}, \{Name: ecs.os-type,Value: linux}, \{Name: com.amazonaws.ecs.capability.docker-remote-api.1.21,}, \{Name: com.amazonaws.ecs.capability.docker-remote-api.1.22,}, \{Name: com.amazonaws.ecs.capability.logging-driver.fluentd,}, \{Name: com.amazonaws.ecs.capability.docker-remote-api.1.23,}, \{Name: com.amazonaws.ecs.capability.task-iam-role,}]} at 
java.util.stream.Collectors.lambda$throwingMerger$0(Collectors.java:133) at 
java.util.HashMap.merge(HashMap.java:1253) at 
java.util.stream.Collectors.lambda$toMap$58(Collectors.java:1320) at 
java.util.stream.ReduceOps$3ReducingSink.accept(ReduceOps.java:169) at 
java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1374) at 
java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481) at 
java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471) at 
java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708) at 
java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) at 
java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499) at 
com.atlassian.buildeng.ecs.scheduling.CyclingECSScheduler.loadHosts(CyclingECSScheduler.java:230) at 
...........
```
that hints at 2 ContainerInstances with the same ec2instanceId.  I could not find arn:aws:ecs:us-east-1:081862267333:container-instance/d547ad1d-ad29-4ea2-841c-3b07a7c636fa in the UI at all, I've seen another Container instance with 'disconnected agent' there that I killed manually (ec2 instance termination) from UI and things went to normal there. 

is this actually allowed/supported state for ECS? shouldn't there be a 1:1 mapping between the EC2 instance and constainer instances?

**Comment by aaithal** [comment]
Hi @mkleint, theoretically, it is possible for an EC2 Instance ID to be mapped to multiple ECS Container Instance IDs. Here are a couple of examples:
1. Let's say that you want to migrate your instance from cluster `A` to cluster `B`. In that scenario, you'll drain the instance, stop the Agent, update its config and reregister it to the new cluster
2. Agent is unable to persist the ECS Container Instance ARN and gets restarted. In this scenario, Agent reregisters itself as it has no way of knowing that it has already registered itself and has an ID associated with it

I dug into the ECS Container Instance ARN for which you saw these errors. It does seem like duplicate records were generated for the same cluster, EC2 Instance ID register requests in our backend records. We're taking a look at why this is the case and will let you know when we have more information.

It would also be useful and will help us rule out certain possibilities if you could share the ECS Init and Agent Log files for the instance `arn:aws:ecs:us-east-1:081862267333:container-instance/d547ad1d-ad29-4ea2-841c-3b07a7c636fa`. You can use [ECS Logs Collector](http://docs.aws.amazon.com/AmazonECS/latest/developerguide/troubleshooting.html#ecs-logs-collector) and share the artifact with us by emailing them to aithal at amazon dot com.

Thanks,
Anirudh

**Comment by mkleint** [comment]
unfortunately I don't have any logs.  We generally automatically start and stop hundreds of instances a day and in this particular case, I've manually killed the instance in out of office hours just to unblock the cluster for a team in different timezone. Due to that exception the entire cluster was not working.

**Comment by aaithal** [comment]
@mkleint, that's fine. An update here is that the `RegisterContianerInstance()` API is not idempotent and as I explained in an earlier post, there are scenarios in which a multiple ECS Container Instance ARNs can be mapped to a single EC2 Instance ID. In this particular scenario, it was a retry that happened because of a timeout that led to this scenario. We are tracking making `RegisterContianerInstance()` API idempotent internally and that should alleviate some of this behavior. As a short-term measure, you can combine the Instance ID and `agentConnected` field to add instances to your map, but idempotent `RegisterContianerInstance()` is the proper way to resolve this issue. I'll create a new feature request issue for that. Please let us know if you have any more questions or comments.

**Comment by mkleint** [comment]
thanks a lot for your fast reply.

the minor problem with relying on agentConnected property is that it keeps on flaking even for healthy agents. multiple times a day we get an event when a describe request claims it's disconnected and the one immediate after it says it's fine again. We do have code in place that kills instances with consistently disconnected agents (in our setup it usually means the docker daemon has crashed)

**Comment by aaithal** [comment]
Yeah, that is a valid concern. As I said earlier, #784 is the right way to resolve such issues. The `agentConnected` will not have false negatives, which is more critical when you're trying to determine EC2 Instance IDs currently active in your cluster (as subsequent reconciliation will eventually catch disconnected instances once they connect back), which is why I suggested that as a possible mitigation. Again, we apologize for the issues that you're running into. It's difficult to get that right without adding idempotency of some sort to `RegisterContianerInstance`.

**Comment by jhaynes** [comment]
Since we're tracking this in #784 I'm going to close this issue. Feel free to add to that issue as needed.
