### ISSUE TITLE
Add support for `--shm-size` `docker run` flag

### ISSUE THREAD

**Issue by aaithal** [aws/amazon-ecs-agent#787]
Has [7 +1s](https://github.com/aws/amazon-ecs-agent/issues/502#issuecomment-245119957) and the following mentions:
* [502](https://github.com/aws/amazon-ecs-agent/issues/502#issuecomment-264976915)
* [655](https://github.com/aws/amazon-ecs-agent/issues/655#issuecomment-279770935)

**Comment by sdeprez** [comment]
Hi ,

Any ETA for this feature? Or any workaround for it in the meantime?

Basically, I need to run some version of Chromium headless inside containers, and that requires more than the default 64M of shared memory so at the moment it's simply impossible to run it.

Thanks,

**Comment by csvan** [comment]
+1, also running Chromium inside ECS here. Next to impossible with default shm size.

**Comment by linuxfreakus** [comment]
+1, ditto on headless chromium.

**Comment by matthew-cox** [comment]
+1, I would really prefer support for this option vs implementing the possible work arounds

**Comment by trstephen** [comment]
+1, headless chromium is a shrinking violet with default 64mb shm

**Comment by AlexMarchini** [comment]
+1, also stuck until this is implemented.

**Comment by mkleint** [comment]
we are also waiting for the Amazon ECS AMi to contain latest docker daemon to at least be able to change the default size of shm to be bigger than 64M

**Comment by alinpa** [comment]
+1, I am waiting to see this feature implemented.

**Comment by zackarychapple** [comment]
Any update on when this will be a reality? We are running into issues on this as well.

**Comment by tobypinder** [comment]
@alinpa we use

```
"Volumes": [
    {
      "HostDirectory": "/dev/shm",
      "ContainerDirectory": "/dev/shm"
    }
  ],
```

in the `Dockerrun.aws.json` to effectively hand the guest container the host's `shm`. I am unclear of any side effects here but it appears to work well for our single container environment. I'm not an expert but you and others here may find this a suitable workaround and we haven't noticed any issues arising from this yet.

**Comment by aatreya** [comment]
Anyone interested in this for use with Chrome/Chromium may also want to star / comment on these bugs:
https://bugs.chromium.org/p/chromium/issues/detail?id=715363
https://bugs.chromium.org/p/chromium/issues/detail?id=736452

**Comment by zackarychapple** [comment]
This article is amazing. https://medium.com/@marco.luethy/running-headless-chrome-on-aws-lambda-fa82ad33a9eb

**Comment by linuxfreakus** [comment]
Yes, its pretty cool, but if you're having SHM issues already with chromium, they are likely to continue with lambda.  You *can* force it to run in that environment, but when I tried, it didn't work for our purposes.  Very crashy.

**Comment by linuxfreakus** [comment]
FWIW, we currently hack it by granting elevated privileges and remounting /dev/shm on container boot.  Not optimal, especially if you have strong security requirements, but one of the only ways to safely make it happen from a memory allocation standpoint if you use more than one container.  Other than that, you have to give up ECS and roll your own.

**Comment by paulrutter** [comment]
+1
See https://github.com/cyrus-and/chrome-remote-interface#why-my-program-stalls-or-behave-unexpectedly-if-i-run-chrome-in-a-docker-container

**Comment by mrzacarias** [comment]
+1

**Comment by mrzacarias** [comment]
I'm trying to use Google Puppeteer on ECS and I'm having this problem. I'm using Fargate as well, so there's no way to use the privileged mode hack...

Do you have an ETA for that? That's keeping me and my team away of using cool stuff like ECS...

**Comment by mkleint** [comment]
FYI on latest Amazon ECS AMIs (or any AMI with docker 17.06+) it's possible to increase the size of /dev/shm by passing --default-shm-size 256M to the docker daemon on startup.

**Comment by mrzacarias** [comment]
That are great news! I couldn't find the documentation about this option, do you have any source explaining how to use this?

**Comment by stephen** [comment]
From reading the latest in https://bugs.chromium.org/p/chromium/issues/detail?id=736452#c56, it looks like this issue is fixed in Chrome >= 64.0.3281.0 with a `--disable-dev-shm-usage` flag.

**Comment by mkleint** [comment]
@mrzacarias https://github.com/moby/moby/pull/29692 https://docs.docker.com/enterprise/17.06/

**Comment by sharanyad** [comment]
A proposal for the implementation of shmsize is available in https://github.com/aws/amazon-ecs-agent/pull/1149.

**Comment by aaithal** [comment]
Hello everyone, we announced support for `shm-size` parameter in your task definition [today](https://aws.amazon.com/about-aws/whats-new/2018/03/amazon-ecs-adds-support-for-shm-size-and-tmpfs-parameters/)! Please refer to our [documentation](https://docs.aws.amazon.com/AmazonECS/latest/developerguide/task_definition_parameters.html#container_definition_linuxparameters) for more details. 

Closing this issue for now. Please let us know if you have any follow up comments/questions regarding this.

**Comment by robertorocha3** [comment]
@aaithal have you added this option to cloudformation? I don't see it in here:
https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-ecs-taskdefinition-linuxparameters.html
If not, do you have a recommended workaround for this?
