### ISSUE TITLE
Support `--ipc` `docker run` flag

### ISSUE THREAD

**Issue by aaithal** [aws/amazon-ecs-agent#788]
From [502](https://github.com/aws/amazon-ecs-agent/issues/502#issuecomment-268517430):
> Support for the --ipc option would be much useful.
>
> In some cases IPC helps services running multiples tasks on the same host that need to work together communicating with each other with much less overhead than network.

**Comment by pankajv82** [comment]
Any target date to add this feature?

**Comment by gurumaia** [comment]
+1

**Comment by obolobova** [comment]
+1
Any news?

**Comment by alexwal** [comment]
Is there a workaround for `--ipc="host"`?

**Comment by sharanyad** [comment]
Hi everyone,
Thank you for your feedback. We are currently exploring options to address this feature. In particular, we are assessing whether the ipc option should be configured at the task level (for all containers) or separately for each container. Do you have use-cases where you need to set `ipc="host"` for only a subset of containers in the task? For comparison, currently the network mode is configured at the task level for simplicity.

**Comment by schnappi17** [comment]
How to set --ipc=containerB:name for a containerA?

**Comment by linkar-ec2** [comment]
Hi all,

Closing this issue.
Amazon ECS now supports an `ipcMode` (as well as `pidMode`) option as a parameter for ECS Task Definitions. You can now add `host`, `task`, or `none` as `ipcMode` options. Please see the latest [announcement](https://aws.amazon.com/about-aws/whats-new/2018/10/amazon-ecs-now-allows-two-additional-docker-flags-/) and the AWS [Docs](https://docs.aws.amazon.com/AmazonECS/latest/developerguide/task_definition_parameters.html#other_task_definition_params) for more information. Please reach out to us for any questions/comments/clarifications.

Thanks,
Kar Shin
