### ISSUE TITLE
eventhandler: possible bottleneck, hardcoded upper bound

### ISSUE THREAD

**Issue by adnxn** [aws/amazon-ecs-agent#797]
the eventhandler has a hardcoded upper bound ```const concurrentEventCalls = 3``` for the maximum number of tasks that can concurrently submit events to backend. this was called out in this [comment](https://github.com/aws/amazon-ecs-agent/pull/763#discussion_r112825524) and needs to be investigated further. 

see: https://github.com/aws/amazon-ecs-agent/blob/3631cb9de33a569d16e7a19d77105beeef8160c2/agent/eventhandler/task_handler.go#L37

**Comment by yunhee-l** [comment]
Agent | Task-per-instance | Instances | Tasks | P0 | P50 | P90 | P99 | P100 | Mean | Placement-success-rate | Launch-success-rate
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
V1.22.0 | 100 | 8 | 800 | 1.02 | 6.16 | 65.83 | 207.24 | 286.33 | 22.61 | 100% | 99.54%
concurrentEventCalls = 5 | 100 | 8 | 800 | 1.07 | 5.93 | 26.25 | 113.01 | 198.12 | 13.51 | 100% | 99.77%
concurrentEventCalls = 10 | 100 | 8 | 800 | 1.11 | 4.04 | 6.07 | 8.48 | 14.47 | 4.18 | 100% | 99.86%
V1.22.0 | 50 | 8 | 400 | 1.16 | 4.81 | 8.02 | 12.16 | 15.41 | 5.16 | 100% | 99.88%
concurrentEventCalls = 5 | 50 | 8 | 400 | 1.01 | 3.80 | 6.10 | 9.02 | 10.67 | 3.97 | 100% | 99.65%
concurrentEventCalls = 10 | 50 | 8 | 400 | 0.88 | 3.43 | 5.14 | 7.06 | 9.53 | 3.50 | 100% | 99.90%
V1.22.0 | 5 | 8 | 40 | 0.84 | 3.28 | 15.96 | 22.97 | 23.70 | 4.79 | 100% | 100%
concurrentEventCalls = 5 | 5 | 8 | 40 | 0.88 | 3.43 | 4.97 | 7.42 | 8.29 | 3.37 | 100% | 100%
concurrentEventCalls = 10 | 5 | 8 | 40 | 0.83 | 3.02 | 4.43 | 5.69 | 5.98 | 2.99 | 100% | 100%

**Comment by yunhee-l** [comment]
merged, resolving.
