### ISSUE TITLE
eventhandler: fix leak, items are never removed from map

### ISSUE THREAD

**Issue by adnxn** [aws/amazon-ecs-agent#798]
the eventhandler does not ever remove items from its map of taskArn:*eventsList. this was called out in the following [comment](https://github.com/aws/amazon-ecs-agent/pull/763#discussion_r112825483).

**Comment by richardpen** [comment]
Also we probably need to remove legacy code related to `SubmitContainerStateChange` api.

**Comment by adnxn** [comment]
closing issue, fixed in #967.
