### ISSUE TITLE
Server eventually runs out of disk space after running a LOT of containers

### ISSUE THREAD

**Issue by rayh** [aws/amazon-ecs-agent#8]
Although the tasks finish, the containers seem to be kept around.  Could the agent clear these periodically, or only keep the last n containers?

**Comment by euank** [comment]
That issue is something that commit 6b28fe13698d3dc600a24ac868bd85593a43f6f8 should fix. It removes containers for tasks that have been stopped for over 3 hours.

This change should be part of our next agent release.

**Comment by jbruni** [comment]
I'm not sure if I understood...

Let's say I have a [minecraft server running as a task](https://registry.hub.docker.com/u/itzg/minecraft-server/). And for some reason (eg. out of RAM), the server stops. In fact, this is exactly what recently really happened w/ me experimenting docker at a t2.micro instance! :-) Suppose my son was there building something in the server world (before the server stopped)... And then comes the GC and wipes it out!? What will I tell him? "Son... the garbage collector removed the container... your construction... our world has been deleted..." :-)

Of course, this is a single scenario upon many many many others I can imagine of how awful the effects of a stopped container being removed could be.

In the Minecraft case, I added 1GB of swap RAM to the t2.micro instance and now the Minecraft server does not stop itself anymore.

I think the usage of containers are unpredictable. We know they should be used as "processors" while data should be out of them in "volumes"... While they *should* it does not mean they *will* be used that way. Of course, there can be stopped containers with non-discardable data on them. Easily.

The container removal should be configurable per task (boolean), or perhaps there should have a "global" setting to choose the GC period: 3 hours, 3 weeks, never, 10 minutes - it totally depends of the nature of the task.

Or maybe I have misunderstood something...?

**Comment by samuelkarp** [comment]
@jbruni Thanks for the feedback!  I have captured your suggestion as a feature request as we continue implementing new features and prioritize our roadmap.

Sam

**Comment by euank** [comment]
The currently released agent now removes the containers of tasks that have been terminal for 3 hours. Please update by running our new preview ami (currently ami-801544e8) or updating your agent via [Dockerhub](https://registry.hub.docker.com/u/amazon/amazon-ecs-agent/) or our [init script](http://docs.aws.amazon.com/AmazonECS/latest/developerguide/ECS_agent.html#ecs-agent-update).

@jbruni This feature will not remove a container that was not launched via ECS. If you are using ECS, you should use [volumes](http://docs.aws.amazon.com/AmazonECS/latest/developerguide/task_defintions.html#using_data_volumes) to persist data, as you describe. In the ECS world, once a task is terminal the containers are no longer usable so it doesn't make sense to store them forever. An important part of making a task for ECS is to consider any data needs.

I understand your concerns, but they are a seperate issue from this one. Please feel free to open a new issue for this if you would like to discuss it further.

Best,
Euan
