### ISSUE TITLE
Upgrade docker version

### ISSUE THREAD

**Issue by sergiofigueras** [aws/amazon-ecs-agent#806]
Hello guys,

After a long struggle, it seems that our ECS ec2 instances are suffering from that Docker issue: https://github.com/moby/moby/issues/31885

Could you guys determine when a new Amazon ECS-Optimized AMI will be released with another docker version? For now, we will try to downgrade our instances due that bug.

**Comment by jhaynes** [comment]
Hi @sergiofigueras. We would love to help resolve your issue. However, the issue you linked to is for a Docker CS package which isn't packaged for Amazon Linux. 

Could you explain what symptoms you're running into and provide the output of `docker info`, `docker version` as well as the AMI ID?

**Comment by sergiofigueras** [comment]
Hello @jhaynes , thanks for your fast reply.

We're using latest AMI version. Here you can find some logs:

https://gist.github.com/sergiofigueras/661b318516559ba22ecec02f91050c35

**Comment by samuelkarp** [comment]
@sergiofigueras Do you have the logs from the Docker daemon?  You should be able to find them in `/var/log/docker`.

**Comment by songgao** [comment]
We had a similar issue: all docker commands hang; docker container process also hangs, but ECS shows task as healthy.

We noticed that the container instance in question runs Agent Version 1.14.1, and docker version 1.12.6. We also have a bunch of other containers running docker version 1.12.6, but with Agent Version 1.14.0 and they haven't had any similar issue. So it might be related to the agent. But this is too little data to conclude that.

We killed the instance to let ECS schedule the task to another one. It hasn't hang since then. If it happens again, I'll try to get logs from `/var/log/docker`.

**Comment by sergiofigueras** [comment]
@samuelkarp , we had several issues running on ECS. This one suddenly disappeared. But I must say that as a huge client, we're *very disappointed* with Docker / ECS. It presented us *several* different issues. We're buying technical support from AWS for now on. I'll try to update things as we've news.

**Comment by samuelkarp** [comment]
@songgao Can you provide logs from a container instance where you're seeing this problem?  It'd be useful to see the Docker daemon logs (`/var/log/docker`) as well as the ECS agent logs (`/var/log/ecs/*`).  If you're not comfortable posting these logs publicly, you can email them to me at skarp at amazon.com.

@sergiofigueras I'm sorry to hear that you've had issues using ECS.  We're happy to help you with all of the ones you've mentioned, though if you need faster response [AWS Premium Support](https://aws.amazon.com/premiumsupport/) is a good option.

Which soft limit did you change?  Are you talking about the memory soft limit (`memoryReservation`)?  If you have a specific task definition that seems to be triggering this issue, I would really appreciate seeing it.  If you're not comfortable posting it publicly, you can email it to me at skarp at amazon.com.

**Comment by songgao** [comment]
@samuelkarp We terminated the instance, so no logs any more. Sorry! If it happens again I'll make sure I get those logs.

**Comment by jzila** [comment]
[I work with @songgao]
Just adding extra context for our repro, not sure if it's relevant:
```
[ec2-user@ip-10-0-5-211 ~]$ service docker status
/etc/init.d/docker: line 35: ulimit: open files: cannot modify limit: Operation not permitted
docker (pid  2681) is running...
```

**Comment by samuelkarp** [comment]
@songgao @jzila Thanks!

@jzila Looks like our init script isn't checking whether it's running as root when you run `status` before modifying the `ulimit`.  The line you're seeing there is harmless; when run as root (which is the normal user for executing the init script), the `ulimit` does get modified properly.

**Comment by cjbottaro** [comment]
I'm also wanting an updated Docker version, namely for some changes to how Dockerfiles are processed (we use ECS as a build system).

**Comment by songgao** [comment]
@samuelkarp We just had another one; sent you an email with the logs. Hope it helps. Thanks!

**Comment by samuelkarp** [comment]
@songgao Thanks, I'll take a look!

**Comment by samuelkarp** [comment]
@songgao It's unclear if a new Docker version will resolve the issue you're seeing, but we have Docker 17.03.1-ce available today in the 2017.03.a ECS-optimized AMI and in the Amazon Linux yum repository.  Can you test this new version and see if it resolves it?

**Comment by jzila** [comment]
We can upgrade to it, but because it's an unpredictable event, we have no way of knowing if it worked.

**Comment by samuelkarp** [comment]
@songgao @jzila We haven't heard from you in a while, so I'm going to close this.  If you continue to run into problems, please let us know.
