### ISSUE TITLE
Proxy support on windows agent

### ISSUE THREAD

**Issue by jumiker** [aws/amazon-ecs-agent#808]
It does not appear that the Windows agent supports a proxy. IHAC that requires a proxy to get out to the public ECS control plane while restricting where it can go Internet egress.

**Comment by samuelkarp** [comment]
@jumiker While I haven't actually tested that yet, there is no Linux-specific code in the codepath involving proxies.  Can you share what you've tried and the errors that you're seeing?

**Comment by jumiker** [comment]
I tried setting the environment variables referenced in the AWS documentation as well as setting Windows system and IE proxies to see if it would pick them up from there. If this does work adding a bit of documentation on how to do it would be appreciated.

**Comment by samuelkarp** [comment]
Can you try applying this diff to [the user-data](https://github.com/aws/amazon-ecs-agent/blob/master/misc/windows-deploy/user-data.ps1)?  You'll want to put your actual proxy configuration in there too.

```diff
diff --git a/user-data.ps1 b/user-data.ps1
index ba04597..400cf6a 100644
--- a/user-data.ps1
+++ b/user-data.ps1
@@ -5,7 +5,9 @@
 [Environment]::SetEnvironmentVariable("ECS_CLUSTER", "windows", "Machine")
 [Environment]::SetEnvironmentVariable("ECS_ENABLE_TASK_IAM_ROLE", "false", "Machine")
+$proxy = "http://proxy.mydomain:port"
+[Environment]::SetEnvironmentVariable("HTTP_PROXY", $proxy, "Machine")
+[Environment]::SetEnvironmentVariable("NO_PROXY", "169.254.169.254,169.254.170.2,\\.\pipe\docker_engine", "Machine")
 $agentVersion = 'v1.14.1'
 $agentZipUri = "https://s3.amazonaws.com/amazon-ecs-agent/ecs-agent-windows-$agentVersion.zip"
 $agentZipMD5Uri = "$agentZipUri.md5"
 ```

You may also need to [restart Docker](https://docs.microsoft.com/en-us/virtualization/windowscontainers/manage-docker/configure-docker-daemon#proxy-configuration) so that pulls can go through your proxy as well.

**Comment by jumiker** [comment]
That worked - thank you. Maybe also update the docs with that?

**Comment by samuelkarp** [comment]
@jumiker Great!  Yep, we'll get the docs updated as well.

**Comment by aidansteele** [comment]
@samuelkarp FWIW, I couldn't find these details in the docs. The [Windows guide](https://docs.aws.amazon.com/AmazonECS/latest/developerguide/ECS_Windows_getting_started.html) actually has a link to the Linux HTTP proxy configuration and it's not immediately obvious that the same env vars are usable on Windows.

(Thanks for the great work on this project btw)

**Comment by samuelkarp** [comment]
While I still haven't actually tested this :slightly_frowning_face:, the same environment variables should work for Windows as well.  You'll want to either set those environment variables prior to starting the ECS agent and Docker or restart both of them to make sure they take effect.  If you embed this in your user-data, it might look something like this:

```powershell
<powershell>
Import-Module ECSTools

$proxy = "http://proxy.mydomain:port"
[Environment]::SetEnvironmentVariable("HTTP_PROXY", $proxy, "Machine")
[Environment]::SetEnvironmentVariable("NO_PROXY", "169.254.169.254,169.254.170.2,\\.\pipe\docker_engine", "Machine")

Restart-Service Docker
Initialize-ECSAgent -Cluster MyCluster
</powershell>
```

If you get a chance to test this and it works, you'd be welcome to [open a pull request to our documentation](https://github.com/awsdocs/amazon-ecs-developer-guide).

**Comment by nrdlngr** [comment]
I finally got around to testing this and I've verified that it works. I'll get this into the docs soon (likely this week). I'll update this issue when the content is live.
