### ISSUE TITLE
Windows ScheduledJob does not start on reboot until RDP

### ISSUE THREAD

**Issue by samuelkarp** [aws/amazon-ecs-agent#809]
On a Windows reboot, the ScheduledJob that starts the ECS agent does not run until an RDP session is started.

**Comment by twehner** [comment]
Manually editing the task in Task Scheduler after it has been created and explicitly setting the run-as user password (by unchecking the "Do not store password" checkbox") will fix this problem.  So, perhaps it is related to session-0 isolation.

**Comment by nrcxcia** [comment]
I was able to work around this issue by replacing some of the userdata powershell as follows:

Remove the following lines:

`          $script =  "cd '$ecsExeDir'; .\amazon-ecs-agent.ps1"
          $repeat = (New-TimeSpan -Minutes 1)
          $jobpath = $env:LOCALAPPDATA + "\Microsoft\Windows\PowerShell\ScheduledJobs\$jobname\ScheduledJobDefinition.xml"
          if($(Test-Path -Path $jobpath)) {
          echo "Job definition already present"
          exit 0
          }
          $scriptblock = [scriptblock]::Create("$script")
          $trigger = New-JobTrigger -At (Get-Date).Date -RepeatIndefinitely -RepetitionInterval $repeat -Once
          $options = New-ScheduledJobOption -RunElevated -ContinueIfGoingOnBattery -StartIfOnBattery
          Register-ScheduledJob -Name $jobname -ScriptBlock $scriptblock -Trigger $trigger -ScheduledJobOption $options -RunNow
          Add-JobTrigger -Name $jobname -Trigger (New-JobTrigger -AtStartup -RandomDelay 00:1:00)
          echo $scriptblock >> c:\windows\temp\log1.txt
          echo $trigger >> c:\windows\temp\log1.txt
          echo $options >> c:\windows\temp\log1.txt`


Add the following:

`schtasks.exe /CREATE /SC MINUTE /MO 1 /TN "$jobname" /RU SYSTEM /RL HIGHEST /TR "cmd.exe /c 'cd %ProgramFiles%\Amazon\ECS & %windir%\system32\windowspowershell\v1.0\Powershell.exe -file .\amazon-ecs-agent.ps1'" /F`

**Comment by samuelkarp** [comment]
This will be fixed by https://github.com/aws/amazon-ecs-agent/pull/1070.  We're moving from a scheduled job to a service.

**Comment by samuelkarp** [comment]
We've released version 1.16.0 of the ECS agent and a new ECS-optimized Windows AMI that installs the ECS agent as a Windows service instead of a scheduled job.  Please see the [updated documentation](http://docs.aws.amazon.com/AmazonECS/latest/developerguide/ECS_Windows_getting_started.html) for instructions to get started using the new AMI.
