### ISSUE TITLE
Proposal: Add the task id as a label on the container.

### ISSUE THREAD

**Issue by ejholmes** [aws/amazon-ecs-agent#82]
Right now, I have a Hekad plugin that takes docker logs in via the [Docker Log Input](https://hekad.readthedocs.org/en/latest/config/inputs/docker_log.html). What I'd ultimately like to do, is take the container id, query the docker daemon for the container config, and extract some labels for use as the syslog `programname` and `pid` fields, so log lines end up looking something like:

```
<timestamp> <host> <app> web.<task uuid> - msg
```

The first step to make this possible, would be to have the ecs agent add an [`com.amazonaws.ecs.task`](https://docs.docker.com/userguide/labels-custom-metadata/) label when creating the container. The end goal would hopefully be to have ECS support docker labels natively within task definitions so that I can add labels like `app=foo`, `process_type=web`.

Thoughts?

**Comment by ejholmes** [comment]
As an example for the first step of this of adding the task arn/uuid as a label, this is what I was thinking of: https://github.com/aws/amazon-ecs-agent/compare/master...remind101:task-label?expand=1.

**Comment by samuelkarp** [comment]
I think this looks like a great idea and would be very happy to see a pull request!  Please note that any pull requests will be accepted under the Apache 2.0 license.

I think the following three labels would make sense to be automatically applied:
* `com.amazonaws.ecs.task-arn`
* `com.amazonaws.ecs.task-definition-arn`
* `com.amazonaws.ecs.container-name`

With respect to your question about supporting labels within task definitions, can you expand a bit on your use case here?  Is your primary use-case just logging metadata?  Are you looking to make scheduling decisions or IAM policies based on these?

**Comment by ejholmes** [comment]
> With respect to your question about supporting labels within task definitions, can you expand a bit on your use case here?

Sure! For my use case, it would only serve as logging metadata (for consumption by logspout/heka). Specifically, I'd like to set some labels on the container when it's run `com.<place>.app-name`, `com.<place>.process-type`, then I would have the labels extracted and added as structured data in syslog messages generated by logspout and shuttled off to sumo/papertrail for aggregation. Having the labels added to the log messages will make it significantly easier to query logs.

For this particular use case, the labels couldn't be added within the Dockerfile via the `LABEL` directive because the image could be used within multiple ecs services with a different `process-type` and `app-name`  labels.

> I think this looks like a great idea and would be very happy to see a pull request!

On it :).

**Comment by samuelkarp** [comment]
Released with [v1.2.0](https://github.com/aws/amazon-ecs-agent/releases/tag/v1.2.0).

**Comment by ejholmes** [comment]
:metal:
