### ISSUE TITLE
intermittent windows unit-test failure: TestSteadyStatePoll

### ISSUE THREAD

**Issue by adnxn** [aws/amazon-ecs-agent#820]
this test fails intermittently on windows and lives in [agent/engine/docker_task_engine_test.go](https://github.com/aws/amazon-ecs-agent/blob/dev/agent/engine/docker_task_engine_test.go). see [test logs and stack trace](https://gist.github.com/adnxn/808e066503cb7091fa882983e3943852) for more info. 

repro: on t2.micro windows instance, in ```agent/engine```,
 run ```go test . -run TestSteadyStatePoll -count 1000```

**Comment by adnxn** [comment]
this can be reproduced on Linux as well with the repro steps above. =[

**Comment by richardpen** [comment]
Released in [v1.14.4](https://github.com/aws/amazon-ecs-agent/releases/tag/v1.14.4)
