### ISSUE TITLE
Inconsistent behavior when setting ECS_CLUSTER

### ISSUE THREAD

**Issue by jason-riddle** [aws/amazon-ecs-agent#826]
If `ECS_CLUSTER` is set to `default` and the `default` cluster doesn't exist, it will be created. However, if `ECS_CLUSTER` is set to anything else other than `default`, the agent logs the following.

```
2017-06-01T14:29:35Z [INFO] Registering Instance with ECS
2017-06-01T14:29:35Z [ERROR] Could not register: ClientException: Cluster not found.
        status code: 400, request id: XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
2017-06-01T14:29:35Z [ERROR] Error registering: ClientException: Cluster not found.
        status code: 400, request id: XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
```

Is this the correct, expected behavior?

**Comment by samuelkarp** [comment]
Hi @jason-riddle,

The behavior for `ECS_CLUSTER` is as follows:

* If `ECS_CLUSTER` is undefined, the value `default` is assumed
* If `ECS_CLUSTER` is undefined and registration fails, the ECS agent attempts to create the `default` cluster
* If `ECS_CLUSTER` is defined, the ECS agent will attempt to register into the defined cluster but will not attempt to create the defined cluster it registration fails

The intent here is to make it easy to get started on ECS by having the `default` cluster get created automatically, but also to prevent an accidental typo in configuring `ECS_CLUSTER` from unintentionally creating a new cluster.

Does this answer your question?

Thanks,
Sam

**Comment by jason-riddle** [comment]
Can this be documented somewhere? It didn't take much time to figure this out, but it could clear up some confusion in the future if someone runs across this issue again.

**Comment by samuelkarp** [comment]
Yep!  I thought there was some, but I'm having trouble finding it at the moment.  I've asked our documentation writer to add some information like this to our developer guide.

If you'd like to add a bit more text on this to our README, we'd be happy for that contribution as well.

**Comment by jcr240** [comment]
same problem as above. So please edit the doc for clearing up confusion
