### ISSUE TITLE
IP Table rules cleared on failed ECS service - ECS agent keeps running

### ISSUE THREAD

**Issue by djenriquez** [aws/amazon-ecs-agent#827]
# Summary
We have seen on multiple instances an issue where the ECS agent appears to be failing, but then restarting on its own. Thats great, however, when it fails, the ECS service responsible for the IP Table rules seems to clear out the rules needed for Task IAM Roles.

When the container comes back up, the ECS service is still down and so the instance stays registered in ECS, says agents can run Task IAM Roles, but the path is gone.

We detected the problem by noticing a trend of ECS agents running vs created: 
```
dca4a8c8a987        amazon/amazon-ecs-agent:latest                          "/agent"                 2 weeks ago         Up 24 hours                                  ecs-agent
```
Then on that box, we attempt to run `stop ecs` which fails with the following:
```
root@[ip-10-6-11-23] /home/ec2-user#>stop ecs
stop: Unknown instance: 
root@[ip-10-6-11-23] /home/ec2-user#>iptables -t nat -L
Chain PREROUTING (policy ACCEPT)
target     prot opt source               destination         
DOCKER     all  --  anywhere             anywhere             ADDRTYPE match dst-type LOCAL
Chain INPUT (policy ACCEPT)
target     prot opt source               destination         
Chain OUTPUT (policy ACCEPT)
target     prot opt source               destination         
DOCKER     all  --  anywhere            !loopback/8           ADDRTYPE match dst-type LOCAL
Chain POSTROUTING (policy ACCEPT)
target     prot opt source               destination         
MASQUERADE  all  --  ip-172-17-0-0.ec2.internal/16  anywhere            
MASQUERADE  tcp  --  ip-172-17-0-2.ec2.internal  ip-172-17-0-2.ec2.internal  tcp dpt:cslistener
MASQUERADE  tcp  --  ip-172-17-0-4.ec2.internal  ip-172-17-0-4.ec2.internal  tcp dpt:esmagent
Chain DOCKER (2 references)
target     prot opt source               destination         
RETURN     all  --  anywhere             anywhere            
DNAT       tcp  --  anywhere             anywhere             tcp dpt:cslistener to:172.17.0.2:9000
DNAT       tcp  --  anywhere             anywhere             tcp dpt:esmagent to:172.17.0.4:5601
```
As you can see above, no IP Table rules.

If I run `start ecs` the rules come back:
```
root@[ip-10-6-11-23] /home/ec2-user#>start ecs
ecs start/running, process 2810
root@[ip-10-6-11-23] /home/ec2-user#>iptables -t nat -L
Chain PREROUTING (policy ACCEPT)
target     prot opt source               destination         
DOCKER     all  --  anywhere             anywhere             ADDRTYPE match dst-type LOCAL
DNAT       tcp  --  anywhere             169.254.170.2        tcp dpt:http to:127.0.0.1:51679
Chain INPUT (policy ACCEPT)
target     prot opt source               destination         
Chain OUTPUT (policy ACCEPT)
target     prot opt source               destination         
DOCKER     all  --  anywhere            !loopback/8           ADDRTYPE match dst-type LOCAL
REDIRECT   tcp  --  anywhere             169.254.170.2        tcp dpt:http redir ports 51679
Chain POSTROUTING (policy ACCEPT)
target     prot opt source               destination         
MASQUERADE  all  --  ip-172-17-0-0.ec2.internal/16  anywhere            
MASQUERADE  tcp  --  ip-172-17-0-2.ec2.internal  ip-172-17-0-2.ec2.internal  tcp dpt:cslistener
MASQUERADE  tcp  --  ip-172-17-0-4.ec2.internal  ip-172-17-0-4.ec2.internal  tcp dpt:esmagent
Chain DOCKER (2 references)
target     prot opt source               destination         
RETURN     all  --  anywhere             anywhere            
DNAT       tcp  --  anywhere             anywhere             tcp dpt:cslistener to:172.17.0.2:9000
DNAT       tcp  --  anywhere             anywhere             tcp dpt:esmagent to:172.17.0.4:5601
```
Then as proof that stopping the ECS service removes the routes, I run `stop ecs`:
```
root@[ip-10-6-11-23] /home/ec2-user#>stop ecs
ecs stop/waiting
root@[ip-10-6-11-23] /home/ec2-user#>iptables -t nat -L
Chain PREROUTING (policy ACCEPT)
target     prot opt source               destination         
DOCKER     all  --  anywhere             anywhere             ADDRTYPE match dst-type LOCAL
Chain INPUT (policy ACCEPT)
target     prot opt source               destination         
Chain OUTPUT (policy ACCEPT)
target     prot opt source               destination         
DOCKER     all  --  anywhere            !loopback/8           ADDRTYPE match dst-type LOCAL
Chain POSTROUTING (policy ACCEPT)
target     prot opt source               destination         
MASQUERADE  all  --  ip-172-17-0-0.ec2.internal/16  anywhere            
MASQUERADE  tcp  --  ip-172-17-0-2.ec2.internal  ip-172-17-0-2.ec2.internal  tcp dpt:cslistener
MASQUERADE  tcp  --  ip-172-17-0-4.ec2.internal  ip-172-17-0-4.ec2.internal  tcp dpt:esmagent
Chain DOCKER (2 references)
target     prot opt source               destination         
RETURN     all  --  anywhere             anywhere            
DNAT       tcp  --  anywhere             anywhere             tcp dpt:cslistener to:172.17.0.2:9000
DNAT       tcp  --  anywhere             anywhere             tcp dpt:esmagent to:172.17.0.4:5601
```

This is a very problematic thing to discover/troubleshoot and can bring down services in ECS that depend on IAM Task Roles without any warning.

# Meta
Linux Distribution: Amazon Linux 2017.03.0, AMI based on ami-c58c1dd3 (us-east-1)
Docker Version: Docker version 1.12.6, build 7392c3b/1.12.6
ECS Agent Version: v1.14.1
ECS Init: 
```
Installed Packages
Name        : ecs-init
Arch        : x86_64
Version     : 1.14.1
Release     : 1.amzn1
Size        : 7.5 M
Repo        : installed
From repo   : amzn-main
Summary     : Amazon EC2 Container Service initialization application
License     : Apache 2.0
Description : ecs-init is a service which may be run to register an EC2 instance as an Amazon
            : ECS Container Instance.
```

**Comment by samuelkarp** [comment]
> We have seen on multiple instances an issue where the ECS agent appears to be failing, but then restarting on its own. Thats great, however, when it fails, the ECS service responsible for the IP Table rules seems to clear out the rules needed for Task IAM Roles.

ecs-init is responsible both for restarting the ECS agent and for managing the iptables rules.  When the agent is restarted, the rules should come back.  Are you seeing something different happen?  If so, the relevant logs would be in `/var/log/ecs/ecs-init*`.

**Comment by djenriquez** [comment]
@samuelkarp that incredibly fast response time is unheard of 🎉 

There are a ton of logs in here, anything in particular I can grep? Or should I zip them up and send over to you?

**Comment by samuelkarp** [comment]
Typically there wouldn't be a ton of logs emitted by ecs-init unless something is causing the agent to restart frequently.  Can you zip them and send them to me at skarp at amazon.com?  It'd also be good to see if there's anything in the agent logs that are indicating why it's dying.

**Comment by djenriquez** [comment]
Ah yes, ecs-init logs are small, but I'm going to send you everything anyways, stay tuned.

**Comment by nmeyerhans** [comment]
Hi @djenriquez. The behavior you're describing, in which the credentials endpoint is removed when the ecs services (init and agent) are stopped, is expected. `sudo stop ecs` stops both ecs-init and ecs-agent, the latter of which is responsible for responding to credentials requests, so the iptables entry should not be left in place.

What I'm particularly interested in is the scenario from the first set of output you provided, in which it appears that the ecs-agent container is running, but the ecs-init process isn't. (That is, when you ran `stop ecs` you received `stop: Unknown instance` from upstart.) Was the agent container on that instance actually started by ecs-init? Or was ecs-init terminated outside of upstart? (e.g. with `kill`) Or did init die for some other reason? In those cases, I could see the iptables rule being deleted while agent is still running.

**Comment by aaithal** [comment]
@djenriquez i'm closing this since we haven't heard from you regarding this issue for a while. Feel free to create a new issue or update this if you have any follow ups/questions. Thanks!
