### ISSUE TITLE
Unable to do blue/green deployment 

### ISSUE THREAD

**Issue by luposlip** [aws/amazon-ecs-agent#843]
Hi!

Usually I update my containers simply by uploading a new taskdef, then update the server from the previous to the newest version. Then usually the new version of the container spins up, and when it's up the old one is stopped automatically.

That is NOT the case anymore. Now the new container briefly gets PENDING, then it disappears again from the task list.

Looking into the container log, the following is found:

```
CannotStartContainerError: API error (500): driver failed programming external connectivity on endpoint ecs-NAME-OMITTED-94958e9asdfasdf4900 (f1800b5f1a909asdfasdfb0a7c89acb72asdfasdf98f97e6965asdfasdf): Bind for 0.0.0.0:80 failed
```

I haven't changed anything in my infrastructure.

Right now, the only way I can update my service, is to stop the currently running tasks (setting number of tasks to 0), and then spinning up the new by (re-) setting it to i.e. 1.

I'm using agent 1.14.2, and docker 17.03.1-ce.

Anyone knows what's going on (sorry if this is NOT the place to ask these kind of questions)?

Best,
Henrik

**Comment by charlieoleary** [comment]
Can you share a sanitized version of your task definition? It sounds like you either have your network mode set to `host` or you're binding the container to a specific host port, meaning you can only have one task per service per host due to port limitations.

**Comment by luposlip** [comment]
I think the issue might have been related to ECS agent version 1.14.2. I see now that there is a new version 1.14.3.
One of my EC2 hosts were in sort of a locked situation where it couldn't stop an older running container. Not even manually with `docker INSTANCEID stop`.

After updating to 1.14.3 and an instance restart, it seems to work again!
