### ISSUE TITLE
ECS Task Stopped before docker stopped 

### ISSUE THREAD

**Issue by Alonreznik** [aws/amazon-ecs-agent#849]
Hello!
We're facing a strange issue.
We're having handling of the SIGTERM and SIGINT in our code which make our process continue running when a stop task is getting into the container. However, it looks like the process is running and shutting itself down (as expected) but the task in the  ECS got stopped status long time before it really happened in the container.

We've configured our ECS_CONTAINER_STOP_TIMEOUT in the ecs-agent to 12h. 

Thanks

Alon

**Comment by vsiddharth** [comment]
@Alonreznik Could you please send us the logs for investigation ?
You can use the [ecs-logs-collector](https://github.com/awslabs/ecs-logs-collector) to obtain  relevant logs. 

You could then send it to `sidvin at amazon.com`

**Comment by adnxn** [comment]
since we haven't heard back from you, we're going to close this issue now. please let us know if you encounter this again. thank you.
