### ISSUE TITLE
Segment Fault

### ISSUE THREAD

**Issue by nimboya** [aws/amazon-ecs-agent#851]
I am using an apline image to run my python script on ECS and i consistently get this "Segment Fault" problem and the container restart.

This happens consistently thereby rendering the service almost useless

**Comment by nmeyerhans** [comment]
Hi @nimboya. Can you provide logs showing the segfault? From your description, it sounds like it's something inside the container (possibly Alpine's python interpreter?) that's crashing. Logs will help us further diagnose what's going wrong.

Please feel free to post the logs here, or if you'd rather not post your logs on a public issue you can send them to me via email at nmeyerha at amazon.com.

**Comment by nimboya** [comment]
Sorry. It was fixed by the engineer, it was a code python code issue
