### ISSUE TITLE
Wrong link in email notification for releases

### ISSUE THREAD

**Issue by evanstachowiak** [aws/amazon-ecs-agent#856]
Hi,

I hope this isn't too pedantic, but the link for releases that gets sent out in the notification emails leads to a 404. The correct link is missing a "v".

For example the last email had this link:
https://github.com/aws/amazon-ecs-agent/releases/tag/1.14.3

but the correct link is:
https://github.com/aws/amazon-ecs-agent/releases/tag/v1.14.3

**Comment by samuelkarp** [comment]
Thanks for reporting! We'll get this fixed for the next time we send notification emails.
