### ISSUE TITLE
ECS agent start fails on instance created from snapshotted AMI

### ISSUE THREAD

**Issue by aaithal** [aws/amazon-ecs-agent#858]
Repro steps: 
1. Launch instance with Amazon Linux and ecsInstanceRole in default ECS cluster 
2. Install ecs-init package 
3. Start ecs, and let agent register 
4. Create AMI from instance 
5. Launch instance from new AMI and ecsInstanceRole, but new cluster
6. Instance doesn't register

**Comment by nithinvenugopal** [comment]
When is this getting released? I think this is similar to the #887 issue I just raised

**Comment by richardpen** [comment]
@nithinvenugopal we have released this in [v1.14.4](https://github.com/aws/amazon-ecs-agent/releases/tag/v1.14.4).
