### ISSUE TITLE
ECS agent doesn't reset task state when instance id is modified

### ISSUE THREAD

**Issue by aaithal** [aws/amazon-ecs-agent#859]
Repro steps: 
1. Launch instance with Amazon Linux and ecsInstanceRole in default ECS cluster 
2. Install ecs-init package 
3. Start ecs, and let agent register 
4. Run a task
5. Stop ecs
6. Modify the ec2 instance id in the state file
7. Start ecs
8. Inspect the state file/introspection API to illustrate that task ID from previous instance id is persisted in the state file

**Comment by richardpen** [comment]
Released in [v1.14.4](https://github.com/aws/amazon-ecs-agent/releases/tag/v1.14.4)
