### ISSUE TITLE
stuck deployments

### ISSUE THREAD

**Issue by optimisticanshul** [aws/amazon-ecs-agent#880]
<img width="1061" alt="screen shot 2017-07-11 at 10 40 56 pm" src="https://user-images.githubusercontent.com/4547169/28080570-16ac22b4-668a-11e7-8c14-7854a88cf39c.png">

Deployment is kind of stuck old version still running from last two days.

**Comment by adnxn** [comment]
Hi @optimisticanshul. I'm afraid I'm going to need to redirect you to [AWS Support](https://aws.amazon.com/premiumsupport) for your issues with service deployments. They will be your best option for handling issues related to deployments.
