### ISSUE TITLE
Ability to write structured logs in JSON

### ISSUE THREAD

**Issue by dcosson** [aws/amazon-ecs-agent#881]
It would be great if the ECS agent logs and audit logs could write structured JSON log lines that could be more easily aggregated and queried to see what the agent is doing.

All of our docker tasks/services log structured logs to a central aggregator, and it could be useful to send the ECS agent logs to the same place and be able to query on different fields (for example, number of requests for credentials in the audit log broken down by container id, or number of tasks that entered state STARTED per host. Querying on string messages is not as nice as having structured logs.

**Comment by adnxn** [comment]
Hey @dcosson, thank you for voicing your use case and need for structured logging in the agent. Also note that the audit logs do maintain a specific formatted output as described in the [troubleshooting](http://docs.aws.amazon.com/AmazonECS/latest/developerguide/logs.html#task_iam_roles-logs) section of the ECS docs.

**Comment by vchan2002** [comment]
+1 on this.... I'm building out ECS so that it includs logspout, which allows it to send out logs that goes to STDOUT to logstash to slice and dice and into elasticsearch.  If the logs are in json format, it can slice and dice all the fields into elasticsearch without any extra effort of parsing.

**Comment by sparrc** [comment]
closing, tracking in #2284
