### ISSUE TITLE
Agent introspection on Windows

### ISSUE THREAD

**Issue by jicowan** [aws/amazon-ecs-agent#883]
The ECS agent for Windows doesn't seem to support agent introspection.  When I curl http://localhost:51678/v1/metadata, I get the following: 
curl : Unable to connect to the remote server
At line:1 char:1
+ curl http://localhost:51678/v1/metadata
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-WebRequest], WebException
    + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeWebRequestCommand

**Comment by samuelkarp** [comment]
@jicowan Are you attempting to do this from the host or from inside a container?  Windows should support the introspection API.

**Comment by jicowan** [comment]
I am attempting to do this from the Windows container instance.  The container instance was missing the ECS instance profile.  After assigning a role to the instance, it started working.  Thanks.
