### ISSUE TITLE
CPUSet/MemSet

### ISSUE THREAD

**Issue by MaerF0x0** [aws/amazon-ecs-agent#884]
In order to improve performance of ECS clusters, it'd be good for the agent to automatically assign 
`--cpuset-cpus=""`  on behalf of containers.  
A smart default could be to assign upto Ceiling(CPUShares/1024) CPUs, distributing tasks evenly across the cpus.

**Comment by adnxn** [comment]
Hey @MaerF0x0 - Not all containers in ECS Tasks are bound to the core size (which is 1024 as of today) and we leave the decision of cpu placement to the kernel. If there is a single container running on the instance, it would be able to consume all cores today if needed and the CPU scheduling parameters are only effective when there's contention on the host's CPU resources. With the default cpuset-cpus model, a task with a single container would be restricted to a single core and would result in a scenario that could detrimental to cluster performance.

Can you please elaborate how is this affecting your use case today?

**Comment by adnxn** [comment]
I'm closing this issue for now since we haven't heard back. Feel free to reopen or comment if you have some more information about your specific use case. Thanks !

**Comment by sudhirj** [comment]
@adnxn Would be useful to restrict placement to only cluster instances that actually have that many cores. For instance, I have a diverse cluster, but I want some containers (with services that require heavy parallel processing to run within SLAs) to run only on the instances that have 8 (for example) or more cores.

**Comment by eightnoteight** [comment]
@adnxn 
I think it is good to have cpuset-cpus model wherever cpushares are in the multiple of 1024, this has multiple use cases like less cpu throttling, optimised allocations when using big instances containing multiple numa sockets etc,..
