### ISSUE TITLE
ecs_agent_data.json does not reflect the correct value from ECS_CLUSTER

### ISSUE THREAD

**Issue by nithinvenugopal** [aws/amazon-ecs-agent#887]
I have ecs.config baked in the AMI with no ECS_CLUSTER key/value in it. When I launch a batch job, agent is intelligent enough to place the correct cluster name in the ECS_CLUSTER but if I open ecs_agent_data.json, it still has cluster as default.
Even if I delete ecs_agent_data.json from cloud-init, it still assigns to default cluster

So every time I launch a new batch job, this instance gets assigned to default cluster even though ecs.config has correct value.

**Comment by adnxn** [comment]
hey @nithinvenugopal - to clarify a few things

> I have ecs.config baked in the AMI with no ECS_CLUSTER key/value in it

does your AMI have a baked in ecs_agent_data.json as well? it is possible the agent is restoring stale state and joining the default cluster. 

> Even if I delete ecs_agent_data.json from cloud-init, it still assigns to default cluster

are you able to verify that cloud-init is deleting the ecs_agent_data.json from cloud-init logs?

> So every time I launch a new batch job, this instance gets assigned to default cluster even though ecs.config has correct value.

i'm curious to see what the agent logs say at agent start up. would you be able to post them here? feel free to redact any sensitive information. thanks.

**Comment by richardpen** [comment]
@nithinvenugopal Based on your comments in #858, I'm closing this for now, feel free to reopen if you still have question.
