### ISSUE TITLE
Delay transition to "Running" state for container

### ISSUE THREAD

**Issue by EugeniuZ** [aws/amazon-ecs-agent#894]
We are deploying a container that starts some processes internally. It could take about 5 minutes until the processes in the container can service requests. Is there a way to tell the ecs-agent that even though the container is up it is not yet in a "Running" state ? Or perhaps would it make sense to add a configuration option to the ecs-agent to set the container state to "Running" after at least X seconds after it is in up state ?

This would be useful when updating the ECS service with a new task definition in order to prevent downtime during ECS service update (as all containers will be replaced and in up state but the processes inside the container not yet completely initialized). With the delay in place we would have first half of the existing containers replaced and updated and the processes inside them ready to process new requests before the second half of the containers is replaced.

**Comment by samuelkarp** [comment]
Are you using an ELB or ALB with your service(s) today?  ECS respects the health check settings provided by ELB/ALB and will not count a task as healthy until it passes the health check.

If you're not using ELB/ALB, I think we're already tracking a slightly different mechanism to cover the same use-case with Docker `HEALTCHECK`s here: https://github.com/aws/amazon-ecs-agent/issues/534.

**Comment by EugeniuZ** [comment]
We are not using ELB/ALB. I've checked #534 and it seems to address a more general issue of using docker healthchecks. I'll comment in that issue then. This one can be closed.
