### ISSUE TITLE
Agent consuming memory that seems to be invisible

### ISSUE THREAD

**Issue by aboarya** [aws/amazon-ecs-agent#901]
I am running the ECS Agent on an `Ubuntu 16.04` with an 8 GB EBS volume.  Doing a `df` on the Ubuntu host shows that there's only `10%` of space left and that many containers are consuming that space.

However running a `du` on the container shows no such memory usage.
```
root@ip-10-0-18-229:~# 
root@ip-10-0-18-229:~# df -h
Filesystem      Size  Used Avail Use% Mounted on
udev            7.9G     0  7.9G   0% /dev
tmpfs           1.6G   10M  1.6G   1% /run
/dev/xvda1      7.7G  6.9G  858M  90% /
tmpfs           7.9G   12M  7.9G   1% /dev/shm
tmpfs           5.0M     0  5.0M   0% /run/lock
tmpfs           7.9G     0  7.9G   0% /sys/fs/cgroup
none            7.9G     0  7.9G   0% /run/shm
none            7.7G  6.9G  858M  90% /var/lib/docker/aufs/mnt/fa0556e6a03b69924ef8f91e7137ebc1798647e98462b04c7aec05ea0e44ba3e
shm              64M     0   64M   0% /var/lib/docker/containers/b3ed8f164f9a58537419c0b562c30759142e77940c617c19e09d1e3aea35027f/shm
none            7.7G  6.9G  858M  90% /var/lib/docker/aufs/mnt/b10ee048014828b1e1802f060c0f50b6bd02450832d86b32d416173ef3276837
...
tmpfs           1.6G     0  1.6G   0% /run/user/1000
root@ip-10-0-18-229:~# docker exec -it --user root 1d2457a2d039 /bin/ash
/var/app/node_modules/app # du -hs /*
812.0K	/bin
0	/dev
304.0K	/etc
200.8M	/home
2.6M	/lib
16.0K	/media
4.0K	/mnt
3.5M	/opt
0	/proc
180.0K	/root
4.0K	/run
220.0K	/sbin
4.0K	/srv
0	/sys
3.1M	/tmp
53.6M	/usr
62.7M	/var
/var/app/node_modules/app # 
```

**Comment by aboarya** [comment]
Any update on this? Any questions I can clarify to find a solution for this?

**Comment by canha** [comment]
`df`, at most, shows you that those particular mounts seem to be to on the same filesystem where `/` is, and that _that_ filesystem is getting filled up. You'll need to investigate a bit with `du` on the host to see what folders/files are taking up the most space.

**Comment by jahkeup** [comment]
Hi @aboarya, Docker uses an overlay filesystem to reduce actual disk usage and share layers between container images. It appears you're using the aufs storage backend which uses a CoW (Copy on Write) approach to eliminate duplication, Docker's [aufs docs](https://docs.docker.com/engine/userguide/storagedriver/aufs-driver/) explain the filesystem specifics in technical detail. To see what the actual and virtual disk space is consumed by your containers you can run `docker ps -a -s`, which will print out something like this:

```bash
$ docker ps -a -s --no-trunc # --no-trunc used for command invocation.
CONTAINER ID                                                       IMAGE               COMMAND                                                            CREATED             STATUS                      PORTS               NAMES               SIZE
dc40a9a901eaa355ae7a11d46613e46a1dde806c1cea3119aad430d5104bd052   debian:latest       "sh -c 'dd if=/dev/zero of=/more-consumed-space bs=1M count=20'"   47 seconds ago      Exited (0) 46 seconds ago                       hello-5             21 MB (virtual 144 MB)
6332db7fe1a25c72c11664d9c5f0e5688d705f3b1e15e82ea8d5816c149afd3b   debian:latest       "echo 'no space!'"                                                 8 minutes ago       Exited (0) 8 minutes ago                        hello-4             0 B (virtual 123 MB)
a2739491c278ad06ea33494a67127e2a4d375540ec0ad67f152372bb340a8919   debian:latest       "sh -c 'dd if=/dev/zero of=/consumed-space bs=1M count=20'"        11 minutes ago      Exited (0) 11 minutes ago                       hello-3             21 MB (virtual 144 MB)
d11038eab007436a2da275f11fc4cc6a4fe902c2f222d07978759064473eae47   busybox:latest      "sh -c 'dd if=/dev/zero of=/consumed-space bs=1M count=20'"        11 minutes ago      Exited (0) 11 minutes ago                       hello-2             21 MB (virtual 22.1 MB)
5a799a0e9c6174629fd9f356af540a4c212e4358491aeb44f2aee1190c353b54   busybox:latest      "echo hello!"                                                      12 minutes ago      Exited (0) 12 minutes ago                       hello-1             0 B (virtual 1.11 MB
```

The containers `hello-1` and `hello-4` do not write to disk, but nonetheless are virtually `1.11MB` (`busybox:latest`'s size) and `123MB` (`debian:latest`'s size) - these are the images' sizes. The containers `hello-2`, `hello-3`, and `hello-5` write `21MB` to disk and total up to `22.1MB` (`busybox:latest + data`) and `144MB` (`debian:latest + data`). 

```bash
# On disk usage:
$ sudo du -d 0 -m -h /var/lib/docker/aufs
197M	/var/lib/docker/aufs
```

In total, these containers add up to `197MB`, which is comprised of the base images (`1.11MB`, `123MB`), the data from all containers (`21M * 3 = 63M`), and additional metadata. Note that this does not add up to the virtual amounts (which adds up to ~`450MB`), as reported by `docker ps -a -s` and `du -hs /*` inside the container.

8GB may not be sufficient for both the OS and container data. If you poke around the `/var/lib/docker/*` directories on the host with `du` you'll find that both your application's data and the images that are used by your containers. These can take up a fair amount of space and may require cleanup either manually (via `docker rm` or `docker rmi`) or automatically by the ECS Agent. The ECS Agent will regularly perform cleanup of your task's STOPPED containers and unused images according to [`ECS_ENGINE_TASK_CLEANUP_WAIT_DURATION`](https://github.com/aws/amazon-ecs-agent/blob/master/README.md) and [`ECS_IMAGE_CLEANUP_INTERVAL`](https://github.com/aws/amazon-ecs-agent/blob/master/README.md), both values may be reduced to fit your needs.

Does this help clarify how containers are using the disk space observed?

**Comment by jhaynes** [comment]
@aboarya we haven't heard back from you in awhile so I'm going to close this question. If we haven't answered it, feel free to re-open or create a new issue if you have other questions.
