### ISSUE TITLE
How does the ecs agent pull images from ecr?

### ISSUE THREAD

**Issue by sesh-kebab** [aws/amazon-ecs-agent#904]
I'm having trouble understanding somethings about how the ecs agent actually pulls images from hosted on aws ecr:

- How does the agent determine based on the image being pulled, that it is or isn't being hosted in ecr?

Although ECR is a private registry, the documentation here [Private Registry Authentication](http://docs.aws.amazon.com/AmazonECS/latest/developerguide/private-auth.html) doesn't have any mention of what information the ecs agent needs and where it needs it to be in order to determine if an image is hosted in aws ecr and whether ecr authentication is required.

Any information at all would be helpful. I don't have an issue in being able to specify services/tasks with images hosted in aws ecr but i'm not sure how it is working.

**Comment by samuelkarp** [comment]
The agent pulls from Amazon ECR without additional configuration, as long as the IAM role you're using has access to ECR and to the repositories you reference.  If you're interested in looking at the code, you can see the agent's logic for obtaining credentials to pull from ECR [here](https://github.com/aws/amazon-ecs-agent/blob/v1.14.3/agent/engine/dockerauth/ecr.go).

Does that answer your question?

**Comment by sesh-kebab** [comment]
@samuelkarp thanks for the quick reply.

I somewhat understand how the ECR image is being pulled but what I can't determine by reading the code is how the ecs agent determines for a given image, (if it is in a public repo vs private repo vs ECR) how the agent determines which authentication method to use?

For example if I have an image: `hello.io/abc/imagex:1`, how does the agent determine whether this is an image being hosted in ECR or not? This is the part i'm unable to understand.

**Comment by samuelkarp** [comment]
Got it.  The agent receives that information as part of the payload from the ECS backend telling it to launch a task; you can see how that's modeled [here](https://github.com/aws/amazon-ecs-agent/blob/v1.14.3/agent/acs/model/api/api-2.json#L176-L183).  When the agent pulls, it checks whether the backend indicated that the image is in ECR or not and [gets an auth token](https://github.com/aws/amazon-ecs-agent/blob/v1.14.3/agent/engine/docker_container_engine.go#L332-L342) if necessary.  For non-ECR private registries, the credentials are [statically configured](https://github.com/aws/amazon-ecs-agent/blob/v1.14.3/agent/engine/docker_container_engine.go#L156).

**Comment by sesh-kebab** [comment]
Oh I see. Thanks - I think I have all the missing pieces of the puzzle now.

**Comment by fitzn** [comment]
@samuelkarp Is there a command to execute on the EC2 instance itself (say, when I am ssh'd in) that will cause the _ECS agent_ to pull down an arbitrary image? I have an EC2 instance that launches, joins an ECS cluster, downloads an image from ECR and runs tasks without issue when initiated via the API or AWS Console. So, the IAM permissions are all correct for pulling down ECR images.

However, `docker pull <account>.dkr.ecr.us-east-1.amazonaws.com/<repo>:latest` fails with the `no basic auth credentials` error if I ssh in to the instance and attempt to download an image manually.

I understand why: I am not logged in through docker. I can download the aws cli and I'm sure IAM would allow me to get an ECR login and the docker pull would work. But I am wondering: is there some way I can command the ECS agent to do it for me?  I read through that Go code you linked above and it appears that the user/password are base64 encoded in a blob somewhere that the ECS agent knows about. Can I access that data somehow and pass that to `docker login`? Basically, the ECS-optimized AMI doesn't come with aws cli and I'd like to avoid custom modifications/start-up scripts if I can.

Thanks very much for your insight!

**Comment by petderek** [comment]
@fitzn Not directly. You could run a custom task that uses the image, with a command like "echo" or "exit".

I'd also look at the ecr credentials helper for docker, which may handle this use case for you.

https://github.com/awslabs/amazon-ecr-credential-helper

**Comment by fitzn** [comment]
@petderek Thank you very much for the response and the pointer. I took a look at the credential helper and that would achieve what I am after. It's similar to downloading the aws cli and using the standard `get-login` approach.  Intuitively, I think I expected the ECS-optimized AMI (but maybe not others) to come with one or both of these tools because `docker pull` seems common, but I totally understand that there is probably a very high bar for including utilities in the official AMI and certainly not everyone needs them.

Thank you again!

**Comment by samuelkarp** [comment]
@fitzn The credential helper is available in the Amazon Linux 2 yum repositories, if that makes it easier.  You can find instructions for [installation](https://github.com/awslabs/amazon-ecr-credential-helper#amazon-linux-2) and [configuration](https://github.com/awslabs/amazon-ecr-credential-helper#docker) so you can use it.

**Comment by fitzn** [comment]
Makes sense. Thanks, @samuelkarp!
