### ISSUE TITLE
ECS agent crushed and won't restart

### ISSUE THREAD

**Issue by fadwa-corexpert** [aws/amazon-ecs-agent#907]
i m using ecs in an amazone linux , i ran into a problem where my container crushed and all tasks launched by the service are stopped immediately .

when i check my machine i found the /var/lib/ecs/data/ecs_agent_data.json file corrupted 
i'm using ecs-agent 1.14.2 
and i download and launch my docker and ecs-agent from the user data

thanks for your help

**Comment by jahkeup** [comment]
Hi @fadwa-corexpert! 

Can you provide me with the logs for your instance? From the information you've provided it appears that you're running a known affected version of the agent that we released an immediate bugfix for; you may want to try running with 1.14.3 to see if the problem you're running into has been addressed. Regardless, it would be helpful to look over the logs and see what caused the problem you've encountered. You can collect the relevant logs from your instance by using our [ECS Log Collector](http://docs.aws.amazon.com/AmazonECS/latest/developerguide/ecs-logs-collector.html).

Please feel free to post your logs here, or if you'd rather not post your logs on a public issue you can send them to me via email at jakeev at amazon.com

**Comment by fadwa-corexpert** [comment]
@jahkeup it's was in fact a problem with the ecs-agent version , i never got the notification that they're is a new version and the old one was bugged .
thanks for you're help
