### ISSUE TITLE
Get pending ECS Tasks

### ISSUE THREAD

**Issue by xennygrimmato** [aws/amazon-ecs-agent#919]
Some of my tasks remain Pending for a long period of time and I have to manually "Run more like this" from the UI to get them Running.

A. Is there a programmatic way to find pending tasks?
B. Does ECS internally handle conditions in which tasks remain pending for a long time and schedule them to run on a different container instance?

**Comment by richardpen** [comment]
@xennygrimmato Sorry for the late response, if you still have this issue, could you send me the logs that can be collected by the [ecs log collector](https://github.com/awslabs/ecs-logs-collector) along with the task ids that has been pending for a long time. If you're not comfortable publishing the logs publicly, please send to my email: penyin (at) amazon.com.

> A. Is there a programmatic way to find pending tasks?

On the instance you can use the [ecs introspection API](http://docs.aws.amazon.com/AmazonECS/latest/developerguide/ecs-agent-introspection.html) to find the task that is pending. Or you can listen to the [ecs event stream](http://docs.aws.amazon.com/AmazonECS/latest/developerguide/ecs_cwe_events.html) and track every task that has been start but not transition to running for a long time.

> B. Does ECS internally handle conditions in which tasks remain pending for a long time and schedule them to run on a different container instance?

Today ECS backend doesn't have the mechanism to replace the long-pending task to another instance. It's probably hard to replace the task without knowing the reason why it's pending.

Thanks,
Peng

**Comment by richardpen** [comment]
@xennygrimmato Since we haven't heard from you, I'm going to close this for now, feel free to reopen if you run into this problem in the future.
