### ISSUE TITLE
ECS_RESERVED_PORTS environment variable should include TCP 5986 as default port on Windows

### ISSUE THREAD

**Issue by pcgeek86** [aws/amazon-ecs-agent#920]
TCP 5986 is the default port that Windows Remote Management (WinRM) service listens on, if configured with a TLS listener. I'd suggest adding this to the default list of reserved ports for the ECS Agent. WinRM is the service used for PowerShell Remoting connections.

TCP 5985 is already included, but that is the default for unencrypted HTTP connections.

Cheers,
Trevor Sullivan
Amazon Web Services (AWS)

**Comment by adnxn** [comment]
fix was merged and released with v1.21.0
