### ISSUE TITLE
ECSinstances won't deregister automatically 

### ISSUE THREAD

**Issue by fadwa-corexpert** [aws/amazon-ecs-agent#921]
i'm testing ECS , whenever i change something in the EC2 instance i get a new ECS  instance added in my cluster.
the problem that the old containers won't deregister on their own , and that might cause a problem with the " /var/lib/ecs/data/ecs_agent_data.json " file that register the configuration of the old cluster, this will lead to the ecs agent not starting and we end up with a cluster without any container instances liked to it and so we can't start our task/service.

So we don't have this problem , the solution is to remove the ecs instances that are not used anymore . is there a way to do it automatically ?

Thanks,
Fadwa.

**Comment by richardpen** [comment]
@fadwa-corexpert Please correct me if I misunderstand.
> i'm testing ECS , whenever i change something in the EC2 instance i get a new ECS instance added in my cluster.

Are you make a new AMI of the instance after you made some change, or can you elaborate the steps what you did to reproduce this problem? 

We already have a [fix](https://github.com/aws/amazon-ecs-agent/pull/892), if the agent was started on a different instance it will registered as a new instance into the cluster. Will that solve your problem? But for the old instance you will need to manually deregister it from cluster or it will be automatically deregistered when it was terminated.

Thanks,
Peng
