### ISSUE TITLE
A way to link ALB logs to the ECS Task they connected to

### ISSUE THREAD

**Issue by dcosson** [aws/amazon-ecs-agent#940]
I have some services (but this should apply to tasks running outside of a service too) that expose a single port and don't specify the `hostPort` parameter, so that ECS and the ALB target group can map them automatically to an open port and run more than one instance of a task on a single ECS Host Instance.

In my logs, I would like to be to filter down to showing the ALB access logs with all of the logs for a single task in that service. This is simple to do for a single request using the Trace ID, but I don't think there's any way to do this for all the logs in a given task across all the requests it gets while running.

The ELB logs don't know anything about the ECS task ID or ECS Service, since they use the abstraction of a target group. And the ECS Tasks don't know anything about what target group they're in as far as I can see, they just bind to a certain host IP & hostPort which gets registered with the targetGroup. So it seems like without making additional API calls in my logging handlers, the only piece of information we can use to join ELB logs to the ECS Task logs is the host IP and hostPort that the ECS task has bound to.

The problem is, as far as I can tell the hostPort isn't exposed anywhere in the [logging context](https://github.com/moby/moby/blob/17.05.x/daemon/logger/loginfo.go) that docker provides.

Would it be possible for the ECS Agent to set a docker Label containing either the target group ARN that the task is registered to, or the hostPort that the task has bound to? It already sets labels for things like `com.amazonaws.ecs.task-arn=arn:...` to make information about the ECS Task available to the docker process if necessary.

(Sorry for the wall of text but the different pieces of docker & ECS get pretty complex)

**Comment by richardpen** [comment]
@dcosson Thanks for the details of your use case, it helps us a lot to understand the feature request. Currently we are working on the container metadata service feature which will expose the metadata of container including the port mapping and taskArn information to container. So inside the container, the process can get the taskArn and the hostPort it uses. Would this feature solve your problem?

The proposal of the container metadata service feature: #709, and we are working on #913 for the implementation.

Thanks,
Peng

**Comment by dcosson** [comment]
Great I'll follow those PR's. As long as it contains both sides of the port mapping (so the port that it is bound to on the ECS Host Instance) that should work.

**Comment by dcosson** [comment]
Although the docker label would still be helpful because Labels get included in the docker logging context, so my log aggregator container such as fluentd can get access to those values in a consistent way across all my various services.

**Comment by aaithal** [comment]
Hi @dcosson, the container metadata feature was released in ECS on Nov 2nd 2017 and should be available with the latest ECS agent. I am closing this issue for now. Please let us know if you have questions/comments regarding the same and we can re-open this issue.

Thanks,
Anirudh
