### ISSUE TITLE
ECS Windows Agent v1.14.4

### ISSUE THREAD

**Issue by JonCubed** [aws/amazon-ecs-agent#954]
The console is reporting that my windows ECS Windows agent is out of date and I can see that v1.14.4 was released for linux agent. 

Is the windows agent holding off until  #729 is done? 

Is there a way to find out what agents have been released for windows even if like [Container Agent Versions](http://docs.aws.amazon.com/AmazonECS/latest/developerguide/container_agent_versions.html) page in documentation?

**Comment by cabbruzzese** [comment]
Thanks for reporting this. I'm sorry for the confusion. We're working on resolving the outdated agent message and improving the overall experience for windows containers. I can't comment specifically on the road map but we've been working on addressing #729 in recent pull requests (i.e. #783, #924) and understand that it is a pain point.

I'll provide an update when this is resolved.

**Comment by JonCubed** [comment]
@cabbruzzese  thanks, looking forward to it. Out of curiosity are there plans or has it been discussed releasing an AMI with ECS agent already baked in like the one for linux?

**Comment by JonCubed** [comment]
@cabbruzzese  thanks, looking forward to it. Out of curiosity are there plans or has it been discussed releasing an AMI with ECS agent already baked in like the one for linux?

**Comment by chappoo** [comment]
FWIW, I've put together a basic packer template that provisions a windows AMI boostrapped with the latest agent built directly from source.   While the service is still in beta, this might help to plug the gap.

https://github.com/chappoo/amazon-ecs-windows-ami.

**Comment by samuelkarp** [comment]
We've released ECS agent [v1.14.5](https://github.com/aws/amazon-ecs-agent/releases/tag/v1.14.5), which now works with newer versions of Docker on Windows.

**Comment by JonCubed** [comment]
thanks @samuelkarp
