### ISSUE TITLE
Task Event sends RUNNING on failed allocation

### ISSUE THREAD

**Issue by pecigonzalo** [aws/amazon-ecs-agent#955]
### Summary
When a task is scheduled on a container instance, even if the task is unable to allocate due to insufficient memory/cpu/etc an event is sent to cloudwatch that the task is `RUNNING`.
This should not be the case as the container is never in that state and it causes problems with events triggered for `RUNNING` tasks

### Expected Behavior
Task remains in `PENDING` state

### Observed Behavior
Task resports `RUNNING`

**Comment by adnxn** [comment]
@pecigonzalo Can you provide more details regarding the environment you're running in? Which OS, docker version and ecs-agent version? Thanks.

**Comment by pecigonzalo** [comment]
OS: Ubuntu 16
Docker: `17.03.1-ce`
Agent: `1.14.3`

**Comment by adnxn** [comment]
Thanks =] Some additional information would be very helpful to investigate this behavior. Could you send me the logs that can be collected by the [ecs log collector](https://github.com/awslabs/ecs-logs-collector)? Also include the cluster id, and specifically the task ids that are misreporting their status. 

Please send the above information to adnkha at amazon dot com, and feel free to update this issue once you've sent it out. Thanks again.

**Comment by pecigonzalo** [comment]
@adnxn I sent the requested logs.
Bare in mind that it is not occurring right now, as I rebalanced the cluster to allow for the task to allocate.

The example case was a task being unable to allocate due to the port being used or insufficient memory on the node, regardless I was getting `RUNNING` followed by an immediate `STOPPED` event when I believe the task should remain in `PENDING` state till it actually allocates and runs.

**Comment by adnxn** [comment]
@pecigonzalo, received. Thanks! We're reviewing the logs and researching the issue you've described.

**Comment by adnxn** [comment]
> Bare in mind that it is not occurring right now, as I rebalanced the cluster to allow for the task to allocate.

@pecigonzalo just to check in on this issue. Have you experienced the problem since?

**Comment by adnxn** [comment]
@pecigonzalo closing this issue since we do not have a repro or sufficient logging data to investigate this any further. Please reopen the issue or cut a new issue if you experience this problem again. Thanks.

**Comment by pecigonzalo** [comment]
@adnxn I had no time to reply before, sorry for the delay. I can try and reproduce this again, as mentioned it happened when the task, for example, fails to allocate due to the port being already in use by another task or similar.
