### ISSUE TITLE
Is there any way to enable docker content trust in ECS?

### ISSUE THREAD

**Issue by cyc115** [aws/amazon-ecs-agent#960]
### Summary
I'm looking for a way to enable docker content trust either via environment variable `DOCKER_CONTENT_TRUST=1` or via parameter at docker run time `--disable-content-trust=false`.\
Does anyone have suggestion on how I could possibly achieve this? :) 

Thanks in advance !

**Comment by richardpen** [comment]
@cyc115 Today the docker content trust is integrated in the docker cli, and there is no remote api for this feature. While ECS Agent relies on the remote API to interact with docker, so it's not possible for ECS to support this today.  But there is a related issue discussing about implementing this in remote api: moby/moby#16654, we will keep tracking on this, and will update if we have any information.

thanks,
Peng

**Comment by aaithal** [comment]
@cyc115 you can also modify the docker config when you start the instance to set `DOCKER_CONTENT_TRUST=1`. Here's some relevant documentation for that: http://docs.aws.amazon.com/AmazonECS/latest/developerguide/bootstrap_container_instance.html#bootstrap_docker_daemon. Let us know if that helps with your use-case. Thanks!

**Comment by adnxn** [comment]
> Today the docker content trust is integrated in the docker cli, and there is no remote api for this feature. While ECS Agent relies on the remote API to interact with docker, so it's not possible for ECS to support this today. But there is a related issue discussing about implementing this in remote api: moby/moby#16654, we will keep tracking on this, and will update if we have any information.

closing this for now since this feature is not available in the docker remote api and there is no action to take on the ecs agent.
