### ISSUE TITLE
Makefile default rule doesn't work as documented due to undeclared dependencies

### ISSUE THREAD

**Issue by nmeyerhans** [aws/amazon-ecs-agent#977]
### Summary

Default `make` rule does not declare adequate dependencies. The `release` makefile target appears to be missing a dependency on `get-cni-sources`.

### Description

README.md indicates that an agent container image can be built with `make`, but the default makefile rule is missing dependencies and the build fails.

### Expected Behavior

`make` should generate an `amazon/ecs-container-agent:make` docker image, per the README.

### Observed Behavior

`make` results in a build failure:

```
mkdir -p "/home/local/ANT/nmeyerha/src/go/src/github.com/aws/amazon-ecs-agent/out"
Sending build context to Docker daemon 57.63 MB
Step 1 : FROM golang:1.7
 ---> f69c27b2f59a
Step 2 : MAINTAINER Amazon Web Services, Inc.
 ---> Using cache
 ---> 79102635ad24
Step 3 : RUN mkdir -p /go/src/github.com/aws/
 ---> Using cache
 ---> cee2a83cb6ed
Step 4 : WORKDIR /go/src/github.com/aws/amazon-ecs-cni-plugins
 ---> Using cache
 ---> baec03feb959
Step 5 : CMD make plugins
 ---> Using cache
 ---> 650612a2d7e1
Successfully built 650612a2d7e1
make: *** No rule to make target 'plugins'.  Stop.
Makefile:126: recipe for target 'cni-plugins' failed
make: *** [cni-plugins] Error 2
```

**Comment by jhaynes** [comment]
This change was release with [Agent v1.14.5](https://github.com/aws/amazon-ecs-agent/releases/tag/v1.14.5)
