### ISSUE TITLE
Makefile can't clean up after itself

### ISSUE THREAD

**Issue by nmeyerhans** [aws/amazon-ecs-agent#978]
### Summary

`make clean` fails after `make release` due to permission failures.

### Description

The `docker-release` make target (or its dependencies) runs processes as root in a container that write to subdirectories of the source directory via a mounted volume. Thus the subdirectories and files that it creates are owned by root and can't be cleaned up by `make clean`

### Expected Behavior

`make clean` deletes files created by `make release`

### Observed Behavior

Following `make release`, `make clean` fails as follows:

```
$ make release
...
Successfully built 4b5485b82cc6
Built Docker image "amazon/amazon-ecs-agent:latest"
$ make clean
# ensure docker is running and we can talk to it, abort if not:
docker ps > /dev/null
rm -f misc/certs/ca-certificates.crt &> /dev/null
rm -rf out/*
rm: cannot remove 'out/cni-plugins/ecs-eni': Permission denied
rm: cannot remove 'out/cni-plugins/ecs-ipam': Permission denied
rm: cannot remove 'out/cni-plugins/ecs-bridge': Permission denied
Makefile:169: recipe for target 'clean' failed
make: *** [clean] Error 1

```

**Comment by jhaynes** [comment]
This change was release with [Agent v1.14.5](https://github.com/aws/amazon-ecs-agent/releases/tag/v1.14.5)
