### ISSUE TITLE
Container NetworkBindings missing when linked to another container

### ISSUE THREAD

**Issue by bndw** [aws/amazon-ecs-agent#994]
### Summary
NetworkBindings are missing for a container that is linked to another container when using the `DescribeTasks` API.

### Description
I'm running two containers in a task definition, `proxy` and `app`. Both containers have Port Mappings that map container port `80` to a dynamic host port. I've now linked the `app` container to the `proxy` container. Now when I use the `DescribeTasks` API, the `app` container's Network Bindings are missing. If I remove the link, they are present.

Could this be a timing issue? In the below `DescribeTasks` output, I notice in the unexpected state of no NetworkBindings that the container is in a `PENDING` state?

### Expected Behavior
I expected to have NetworkBindings for my `app` container when it's linked to another container in the task. The `proxy` container relies on this information for service discovery.

### Observed Behavior
I have no NetworkBindings for the container that defines the link, even though I've added Port Mappings to the Container Definition

`DescribeTasks` containers without the link:
```json
"Containers": [
                {
                    "ContainerArn": "arn:aws:ecs:us-west-2:xxx:container/14593d36-b11f-460c-945b-bd2f08389bbf",
                    "ExitCode": null,
                    "LastStatus": "RUNNING",
                    "Name": "proxy",
                    "NetworkBindings": [
                        {
                            "BindIP": "0.0.0.0",
                            "ContainerPort": 80,
                            "HostPort": 32907,
                            "Protocol": "tcp"
                        }
                    ],
                    "Reason": null,
                    "TaskArn": "arn:aws:ecs:us-west-2:xxx:task/b6fad2f6-f8a8-4259-ae5d-049b59720f62"
                },
                {
                    "ContainerArn": "arn:aws:ecs:us-west-2:xxx:container/719c753f-6fd5-4871-955a-0f271ad89570",
                    "ExitCode": null,
                    "LastStatus": "RUNNING",
                    "Name": "app",
                    "NetworkBindings": [
                        {
                            "BindIP": "0.0.0.0",
                            "ContainerPort": 80,
                            "HostPort": 32906,
                            "Protocol": "tcp"
                        }
                    ],
                    "Reason": null,
                    "TaskArn": "arn:aws:ecs:us-west-2:xxx:task/b6fad2f6-f8a8-4259-ae5d-049b59720f62"
                }
            ]
```

`DescribeTasks` containers with the link (Unexpected):
```json
"Containers": [
                {
                    "ContainerArn": "arn:aws:ecs:us-west-2:xxx:container/9a4e42d3-cf4a-4f50-a343-f9b56ccf53ce",
                    "ExitCode": null,
                    "LastStatus": "PENDING",
                    "Name": "app",
                    "NetworkBindings": null,
                    "Reason": null,
                    "TaskArn": "arn:aws:ecs:us-west-2:xxx:task/597febf9-da06-4654-b018-dcc0f37ad2e7"
                },
                {
                    "ContainerArn": "arn:aws:ecs:us-west-2:xxx:container/c5edcfe2-35c7-42da-b01c-05a2c6b56e9e",
                    "ExitCode": null,
                    "LastStatus": "RUNNING",
                    "Name": "app",
                    "NetworkBindings": [
                        {
                            "BindIP": "0.0.0.0",
                            "ContainerPort": 80,
                            "HostPort": 35716,
                            "Protocol": "tcp"
                        }
                    ],
                    "Reason": null,
                    "TaskArn": "arn:aws:ecs:us-west-2:xxx:task/597febf9-da06-4654-b018-dcc0f37ad2e7"
                }
            ]
```

##### Docker info
```
Containers: 88
 Running: 7
 Paused: 0
 Stopped: 81
Images: 16
Server Version: 1.12.6
Storage Driver: overlay
 Backing Filesystem: extfs
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: overlay null host bridge
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: seccomp selinux
Kernel Version: 4.9.16-coreos-r1
Operating System: Container Linux by CoreOS 1298.7.0 (Ladybug)
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 1.956 GiB
Name: ip-10-10-0-75.us-west-2.compute.internal
ID: X3BK:YAO4:HKZI:IQTF:X3DH:PJIB:WFBZ:MCLP:7ZDQ:SGSF:MZMN:KCPU
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Insecure Registries:
 127.0.0.0/8
```
###### curl http://localhost:51678/v1/metadata
```json
{
  "Cluster": "xxx",
  "ContainerInstanceArn": "arn:aws:ecs:us-west-2:xxx:container-instance/36dde22d-b432-4a16-a155-0d3d84298c42",
  "Version": "Amazon ECS Agent - v1.14.3 (15de319)"
}
```

**Comment by bndw** [comment]
This seems to be a race, where if I wait a little bit the NetworkBinding will show up in the output of DescribeTasks. What's the proper way to handle the case where container A *depends* on container B to be RUNNING? I've marked them both `essential` but there still seem to be race conditions.

**Comment by adnxn** [comment]
@bndw This is not a race condition. Since the containers are not transitioning to running in exact lock step, we expect there to be some delay before both are RUNNING. 

> What's the proper way to handle the case where container A depends on container B to be RUNNING? 

In the usecase described, linking `app` to`proxy` will ensure that `proxy` transitions to RUNNING before `app`.

> I expected to have NetworkBindings for my app container when it's linked to another container in the task. The proxy container relies on this information for service discovery.

Given the dependency requirement, linking `proxy` to `app` would ensure that `app` transitions to RUNNING before `proxy`.

**Comment by bndw** [comment]
Thanks for following up @adnxn. Due to outside constraints I must link `app` to `proxy`. To handle the transition I've implemented retry logic in the `proxy` to handle PENDING state.
