### ISSUE TITLE
Always pull latest image version (digest) of the specified tag

### ISSUE THREAD

**Issue by psarakis** [aws/amazon-ecs-agent#995]
### Summary

If an image-tag combination is present on the ECS host, the latest version (digest) will not be pulled from the repository, on any subsequent task runs. This operation (force pull) is implemented in other orchestrators such as [Mesos](https://github.com/mesosphere/marathon/blob/48bfffdbb2920732ba726ce19ade6deb00121794/docs/docs/rest-api/public/api/v2/examples/app.json#L26).

### Description

Although, building using the same tag is not advisable, in some cases it may make sense. For example, as a convention, Docker tags may follow Git tags. If there is any issue with the Docker image build process/system, the resulting image may be flawed. In this scenario, a new build will be triggered but the tag must remain the same. If a deployment has already triggered the image pull on the ECS hosts, the latest image digest will not be pulled again on the host.

I believe this is not a bug but more of a feature request. Is that something that you would be willing to merge? Also, I think this behavior should be configurable, so please advise on the API.

**Comment by jhaynes** [comment]
Hi @psarakis What you're describing sounds like the way we expect the agent to work today. In short, for every task, we effectively call `docker pull` which will, at the minimum, download the manifest and verify that a local image matches the one in the remote registry.

If this is not the behavior you're seeing, please let us know!

You can see https://github.com/aws/amazon-ecs-agent/issues/413#issuecomment-222028159 for some additional discussion around a similar topic.

**Comment by psarakis** [comment]
Hello @jhaynes, thanks for your reply. We encountered this issue using the ECS agent 1.14.3 & 1.14.4 versions on ECS optimized AMIs, using ECR as registry. My understanding is that there is no such setting (`ECS_AGENT_PULL_BEHAVIOR`) as the proposal suggested in the linked issue (#413). If you need more details please let me know.

**Comment by samuelkarp** [comment]
@psarakis We haven't heard from you in a while, so I'm going to close this issue.  Please feel free to re-open the issue if you need additional help.  Thanks!

**Comment by psarakis** [comment]
@samuelkarp sorry for not replying. Thank you very much for the feedback. I will re-open if we observe or manage to reproduce this behavior again.

**Comment by bartimaeus** [comment]
I have a similar issue with my ECS instances not pulling the latest images. I was initially tagging the images with `latest` and then updating the task definition and service [from the command line](https://github.com/bartimaeus/aws-deploy-scripts/blob/master/ecs/deploy.sh).

I started getting complaints of things not working. I pulled up both ECS instances and noticed that only one of the instances was updating to the `latest` image.

I read that I should tag with version numbers so I switched to using versions as the tag and notice the same issue.

![selection_008](https://user-images.githubusercontent.com/403832/39540603-5e91751c-4e00-11e8-9386-34abacd55d41.png)

A `force deploy` from the AWS console still doesn't seem to work either. Not sure what else to do at this point. I will try the ECS Log Collector and see if I find anything else.

**Comment by bartimaeus** [comment]
I will create a script after successful deploys to clean up old containers, images, and volumes. The thin pool is something that I don't want to have to change on new ECS instances that I spin up.

**Comment by okarthikeyan** [comment]
Update the digest on the task definition when pushing the new image.

**Comment by ktamas77** [comment]
Hey - just to clarify; If I have a Fargate task with a specified image (let's say: image:latest), and i stop the task (let's say autoscale scales down the service to zero), and then i update the image with the same tag (image:latest), and then autoscale starts to scale up the service, then the new tasks will automatically pull the latest, update image of (image:latest)? 

or do i need to use 'force-new-deployment' on all tasks in order to pull the latest images with the same tags?

force new deployment will restart the tasks to pull the new image, and i'm wondering if i can avoid restarting if immediate update is not mandatory (just over the time for the new tasks).

**Comment by rohanmangal** [comment]
@ktamas77 
> 
> Hey - just to clarify; If I have a Fargate task with a specified image (let's say: image:latest), and i stop the task (let's say autoscale scales down the service to zero), and then i update the image with the same tag (image:latest), and then autoscale starts to scale up the service, then the new tasks will automatically pull the latest, update image of (image:latest)?

While scaling down old tasks are already stopped and new task are being launched with scale up operation, in this case Fargate will always pulls fresh image(whatever tagged to image:latest).

> or do i need to use 'force-new-deployment' on all tasks in order to pull the latest images with the same tags?
> 
> force new deployment will restart the tasks to pull the new image, and i'm wondering if i can avoid restarting if immediate update is not mandatory (just over the time for the new tasks).

['force-new-deployment'](https://docs.aws.amazon.com/AmazonECS/latest/APIReference/API_UpdateService.html#ECS-UpdateService-request-forceNewDeployment) is only required when you want to trigger a new deployment without changing any ECS/Fargate configurations, By default Deployments are not forced, which means if there are no changes in config nothing will happen to running tasks.

**Comment by ktamas77** [comment]
> While scaling down old tasks are already stopped and new task are being launched with scale up operation, in this case Fargate will always pulls fresh image(whatever tagged to image:latest).

@rohanmangal thank you for clarifying! this is very helpful.
